---
title: "Yüksel Güran Savunması"
editor: source
---

## Mahkeme Başkanı

Mahkeme Başkanı : Evet iddianamesi geldi. İddianameyi zaten sabah özetlemiştim kısmen. İddianameyi biliyorsunuz. Avukatlarınız var. Yasal haklarınız sorularımıza cevap vermeme hakkına sahipsiniz. Susma hakkına sahipsiniz. Sabah diğer sanıkları hatırlattığım yasal haklarınız vardır. evet sizi dinliyorum. Kızınızı diğer sanıklarla birlikte iştirak halinde öldürmekten yargılanıyorsunuz. Ne dersiniz?

Yüksel Güran : Evet. O zaman herkesin yanında söylüyorum. Türkçem fazla kuvvetli değildir. Bazen Kürtçeyi karıştırıyorum. Kusura bakmayın.

Mahkeme Başkanı : Yok önemli değil. Türkçe Kürtçe anlaşırız inşallah. Buyurun.

Yüksel Güran : Sabahtan başlayayım. Olay günü. Sabah beşte ben kalkmışım.

Mahkeme Başkanı : Bir dakika bir uğultu var arkadaşlar. Ses mikrofona tam alınmıyor. Gelmiyor. Biraz daha sessiz olalım. Hah. Biraz daha sessiz. Kendi aramızda da sessiz. Buyurun Yüksel Hanım.

Yüksel Güran : Saat 5'te ben kalkmışım. Beşte bamyama gittim. Bahçeme gittim. Bamyamı topladım. Geldim zaman kaç sıram kalmış. Baktım önümüze bir ölü hindi çıkmış. Dedim köpek hindimizi yemiş. Geldim eve saat altı, altı buçuktu Osman'ı kaldırdım. Ongözlü'ye işe gönderdim. Arif zaten akşam geç geldiği zaman dama çıktığı zaman annesi otogara geldiği zaman de Yüksel beni sabah biraz erken kaldır. Batman'a gideceğim. Sonra sabah olduğu zaman hani ben bamyaya geldim Osman'ı gönderdim. mutfağıma girdim. Çok sevinçliydim. İki üç oğlum gurbetten gelmişti. Ne kızarttım, ne yaptım? Gözüm doymuyordu. Sonra çocuklarım yavaş yavaş diğerleri aşağıya iniyordular. Kahvaltımı bitirene kadar dedim çocukların babanı kaldırın, ağabeyini kaldırın aşağıya insinler. Şimdi zaman baktım Arif Muzaffer telefonla konuşuyordu. Kim kimi aradı bilmiyorum onu. Dedi Yüksel beni sesledi. Dedi Yüksel Muzaffer kahvaltıya gelecek. Dedim tamam. Muzaffer geldi. Kahvaltımız bıraktık. Soframızı bıraktık. O gün çok sevinçliydim. İçime girdi dedim ölürüm. Osman tek bize eksiktir. Allah hakkımızı kabul etmesin. Son soframız güzel oldu. Bunu da herkese söylüyorum.

Mahkeme Başkanı : Niye son sofranız diyorsunuz?

Yüksel Güran : Son sofra çünkü bize sonra zehir ettiler.

Mahkeme Başkanı : Ha o manada.

Yüksel Güran : Herkesin yanında bunu söylüyorum. Sonra biz yemeğimizi yedik. Muzaffer, Arif, Baran birlikte çıktılar. Muzaffer, Arif, Batman'a gidecekler. Baran da gelini alışverişe götürecekti. Sonra dedim Enes oğlum kalk banyoya. Çünkü Enes küçüktür. Her şey aklına gelmiyor. Ben gördüm ifadeleri bir öne bir önce söylüyordu. Sonramıza Enes banyoda çıktığı zaman ben Narin Eren'i de yıkadım. Sonra kız kardeşimi aradım. Dedim makinem, makinem numarası bozuktur. Hediye. Yok kız kardeşim Salihe Güran. Aradığım zaman dedi abla iki makine elbisem vardır. Öğleden getir. Hediyeyi aradım. Eltim. Hediye Güran. Aradım, dedi getir. Dedim Enes'e elbiseleri getireceğim. Dedi tamam güzel getir. Bütün elbise Enes'e aitti. Kalktım Hediye Güran'a götürdüm. Mutfağa kadar götürdüm. Dedi otur da oturmadım.

Mahkeme Başkanı : Bunların saat olarak hatırlıyor musunuz tam olarak?

Yüksel Güran : Sabah. Sabah da biz başlıyoruz. Öğleden önceden bahsediyorsunuz şu an. Sabah da başım hala Narin evdedir.

Mahkeme Başkanı : Tamam. Narin evdedir.

Yüksel Güran : Evet. Hediye'gilden geldim. Narin, Eren ikisi de balkonda oynuyordular. Çok sevinçliydiler. Eve içine girdim. Çünkü biz çocuklarım vardır. Evin içine gittim. İşimi yapıyorum, gücümü yapıyorum. Bir Eren ya Enes Narin yanıma koşuyor. Anne ne zaman elbiseye gideceğiz? Anne bana gelinlik alacaksın. Anne bana bunu alacaksın. Ben de kızıma diyorum tamam kızım. Sana söz veriyorum yarın alacağım. Allah hakkımızı kabul etmesin. Bırakmadılar kızıma gelinlik alayım. Sonra bir yanıma koşuyor, bir abinin yanına koşuyor. Abi niye bana oyuncak getirmedin? Abiciğim patronum para vermedi. Söz veriyorum. Paramı gönderse sana alacağım. Sonra işimi bitirene kadar balkonumu yıkadım. Balkonumu yıkadığım zaman baktım, çocuklar, abiler mutluydular içeride. Ben dinamoyu kapattım. Amcam gelini Batman'da gelmişti. Kız kardeşimgildeydi. Onun yanına dedim gideyim bir hoş geldin diyeceğim. Gittim onlar mutfaktaydılar. Çay, kahve içiyordular. Ben de onun yanına oturdum. Kahve bana da getirdiler. İçtim. Biraz oturdum baktım Ferhat Kaya. Dedi teyze ya Enes ya Eren bunu tam hatırlamıyorum. Dedi aramış. Dedi annem eve gelse biz acıkmışız. Eve geldim. Çünkü bizim düğünümüz vardı. Geldiğim zaman Muhammed telefonla bir cihaz almıştı. Şarkı söylüyordu. Narin'i Eren'i elini tuttum. Biraz oynadık.

Mahkeme Başkanı : Şimdi Yüksel Hanım siz bunları yaptığınızda evden dışarıya çıktığınızda telefonunuz yanınızda mıydı? Evde mi bıraktınız?

Yüksel Güran : Telefonum evdedir.

Mahkeme Başkanı : Hep evdedir. Telefonum Süreym.. Muhammed Narin evde olsa telefonum her zaman evdedir.

Mahkeme Başkanı : Onlar çocuklar telefonla oynadıkları için mi?

Yüksel Güran : Evet. Hani duruyorlar ben dışarıya gidiyorum, bahçeye gidiyorum.

Mahkeme Başkanı : Evet tamam.

Yüksel Güran : Oraya gidiyorum.

Mahkeme Başkanı : Telefonda da çocuklar oynuyor yani.

Yüksel Güran : Ses çıkmıyorlar ondan. Telefon onların yanındaydı. Sonra Narin dedi, çocuklar dedi biz acıkmışız. Narin dedi, anne bize patates kızart. İyi ki kızarttım, kızıma verdim. Patates kızarttım. Kahvaltımızı hazırlıyorum. Yani öğle yemeğidir. Tamam. Baktım Muhammed, Narin kavga ettiler telefon için. Onların elinden aldım. Sofra üstüne oturduğum zaman yine birbirine girdiler. Ben bunu gayet hatırlıyorum. Sürekli bende telefon yani saat istiyorlar. Saat kaç? Saat kaçtı? O zaman saat 1'de biz sofra üstündeydik.

Mahkeme Başkanı : Şimdi Yüksel Hanım evde kimin, kimlerin telefonu var?

Yüksel Güran : Evin içinde herkes telefonu vardır.

Mahkeme Başkanı : Narin'in telefonu var mı?

Yüksel Güran : Sadece Muhammed, Narin, Eren, ben bir telefonduk.

Mahkeme Başkanı : Narin'in telefonu yok?

Yüksel Güran : Hayır, Narin telefonu yoktur.

Mahkeme Başkanı : Tamam.

Yüksel Güran : Biz sofra üstüne oturduğumuz zaman, ben bunu gayet hatırlıyorum. Sadece bunu biliyorum. Ben saate baktım saat 1'di. Biz yemeğimizi yedik. Bulaşığımı yıkadım. Halımı gırgırladığım zaman koltukta oturdum. Baktım Narin televizyon tozu alıyordu. Birde bir gözü saate girdi. Çünkü biz akşam Hüseyin Güran'a gittiğim zaman, akşam Hatice ona dedi yarın gel. Kur'an kursa gideceğiz. Bir de bir gözü saate girdi. Dedi anne Kur'an kursa geç kaldım. Dedim kızım gitme. Sıcaktır. Etme etme ikna edemedim. Sonra dedi, anne 4'e kadar ders veriyor. Ne olur? Yalvarırım. 4'ten sonra Hatice, Fatma'nın yanına gideceğim. Dedim kızım gitme. Amcan hastadır. Etme etmedim. İkna edemedim. O beni ikna etti. Gitti kalktı. O zaman ben ona dedim, tamam. Kızım çığlık attı. Çok sevindi. Parmakı böyle yaptı. Dedi 4'e kadar dersimiz var. Ondan sonra gideceğim, akşama kadar Hatice yanında oynayacağım. Normalde zaten çocuk köyde 5'te çıkıyorlar. Akşama kadar zorla onları eve getiriyoruz. O daha Kur'an kursa gitti. Yani içeri gitti. Ben ona dedim hatta dedim de kızım insan bu bacakla Kur'an kursa gitmez. Dedi anne üstüm başım bir şey giyeceğim. Yemin ederim, yemin ederim Narin evde o odadan çıktığı zaman gözüm kör olsa ben daha Narin'i görmedim. Benle Enes oturuyordu. Enes de telefonla oynuyordu. Hiçbir mesele bizim dikkatimi herhalde çekmemişti. Hatta Enes bana öyle dedi. Anne patronumuz para göndermezse, abim askere gidiyor. Düğün masrafı ne olacak? Dedim, oğlum öyle bir şey dert etme. Baban halledecek. Sonra ben çok yorulmuştum. Ben biliyordum, Narin dışarı çıktığı zaman Muhammed içeri geldi. O zaman besleme çantası Muhammed görmüştü jandarmaya söylemişti. Ben çok yorgundum. 5'te kalkmıştım. Enes de gece yarısı gelmişti. O zaman ben yattım. Yattığım zaman ne kadar yattım bilmiyorum. Kalktım Muhammed yatıyor. Enes de yatıyor. Eren telefonla oynuyor. Bir mutfağa kadar gittim, bir bardak su içtim. Tekrar geldim tekrar yattım. Yattığım zaman yine kalktığım zaman Muhammed, Eren uyanıktı. Hala Enes yatıyordu. Baktım Eren'le Muhammed ikisi bana söylediler. Anne yenge Hediye elbisemizi getirmiş. Dedim oğlum niye beni kaldırmadın? Dedi anne yenge Hediye bırakmadı. O zaman biraz herhalde evi içine yani odanın içine topluyordum. O arada Muhammed çıkmış çıkmamış hiç hatırlamıyorum. Baktım Enes Hediye geri geldi. Dedim Hediye oğlan ben de yeni çocukları bana söyledi. Dedi Yüksel ben geldim sen yatıyordun. Dedim kalkmasın. Dinamo muhtarın kapısındadır şantili. Dinamoyu çalıştırmışım. Suyumu almışım, geldim Dinamoyu kapatacağım. Dedim şu anda Yüksel kalkmış. Hediye bize geldi. Bayağı oturduk. Konuştuk. Elbise almaktır, düğündür. Ben de diyorum Baran askere gidecek. Misafirimiz öyle. Konuşmamız öyleydi. Sonra aklıma geldi. Gittim Enes'in valizi, elbiseleri getiriyorum. Evin içinde odada. Katlıyordum baktım Enes'in telefonu çaldı. Bildiğim kadar bence iki defa çaldı. Bırakmadım onu uyandırsınlar. Kalktı arkadaşıyla konuştu. Dedim, oğlum kimdir dedim, anne arkadaşımdır. O da yengesine sordu. Yenge de ona sordu. O arada Enes çıktı. Enes ne kadar içeride kaldı kalmadı, ben bunu bilmiyordum. Benle Hediye konuştuk. Konuştuk, o zaman ne kadar konuştuk bilmiyorum. Saate hiç bakmadım. Ben biliyorum daha akşama doğru gidiyor. Hediye dedi ben eve gideceğim. Hediye'yle kapı önüne çıktık. Baktım Enes geldi.

Mahkeme Başkanı : Yani siz Hediye geldiğinde Enes evde miydi?

Yüksel Güran : Hediye birinci Hediye geliyor hala biz yatıyoruz.

Mahkeme Başkanı : Tamam.

Yüksel Güran : İkinci Hediye geliyor ben kalkmışım. Hala Enes yatıyordu. Bayağı biz oturduk. Valizi elbiseyi katlıyordu. Enes'in telefonu çaldı. Enes telefonla kalktı.

Mahkeme Başkanı : Tamam. Hediye evde yani.

Yüksel Güran : Evet. Enes evdedir hala. Dedim oğlum kim? arkadaşımdır. Hatta ona öyle dedim. Oğlum yeter kalk öldün uykudan. Biraz daha kendine dışarı çık. Enes odadan çıktı. Daha ne zaman havaya çıktı? Ne zaman dışarı çıktı bilmiyorum. Benle Hediye oturuyoruz, konuşuyoruz. Sonra Hediye de eve gideceğim. Biz Enes'in arkasında da bayağı oturduk. Hiç aklıma gelmiyor, ne kadar oturdum. Sürekli ben de karakolda saat kaçtır? Saat kaçtır, dedim bilmiyorum. Saat hiç bakmamış.

Mahkeme Başkanı : Aynı soruları biz de soracağız. Saat kaçtı diye.

Yüksel Güran : Bilmiyordum.

Mahkeme Başkanı : Olabilir.

Yüksel Güran : Hiç bakmamışım.

Mahkeme Başkanı : Şu an bile saatin kaç olduğunu bilmeyebilirsiniz. Ama işte bu saatlerle dakikalarla oynadığımız için bu soruları belki saat kaçtı diye biz de sürekli sorabiliriz yani. Haklısınız ama ben de haklıyım çünkü bilmiyorum. Böyle şey olacak.

Yüksel Güran : Saate bakmamışım.

Mahkeme Başkanı : Olabilir. Bakmayabilirsiniz.

Mahkeme Başkanı : Hatırlamayabilirsiniz.

Yüksel Güran : Baktım Enes geliyor Hediye de eve gitti. Hatta ben Enes'e dedim oğlum neredesin diye, çeşmenin yanındadır. Cami yanına bir şey de söyledi. Onu tam aklıma girmiyordu. Daha ben mutfağa koştum. Enes'i gördüm, içeride o televizyon odasına girdi. O araydı. Önceydi, bilmiyorum. Dedim babasını ara. Baba nerededir? Baba aradığı zaman diyor ben Batman Melkişköy'deyim. Dedim zaten bu yemeğe yetişmiyor. Biliyordum, Baran'la Sultan bana dedi ben akşam amcam Kurtuluş'a gideceğim yemeğe. Sonra yemeğimin etini üstüne bıraktım. Biraz evi toparladım. Enes o arada her halde dışarıya daha yeni çıkmış. Çıktığım zaman o zaman komutanım bana dedi ki, sen o gün Salim'i hiç gördün mü? Dedim yemin ederim komutanım ben Salim'i hiç görmedim. Sonra aklıma geldi. Ben şalteri indirdiğim zaman Hüseyin Güran'ın kapısını görüyorum. Hala Hüseyin amca oradadır. Ablası oradadır. O zaman bence Salim'di. Saniyede ben Salim orada gördüm. Tekrar komutanın kapısını çalıyor. Komutanım sen bana söyledi. Ben dedim ben görmemişim. Dinamoyu çalıştırırız, o zaman sanki Salim saniyede ben Hüseyin Güran'ın kapısında gördüm.

Mahkeme Başkanı : Sanki. Emin değilsin. Emin misin? Değil misin?

Yüksel Güran : Oradaydı oradaydı. Evet oradaydı yani.

Mahkeme Başkanı : Yani o gün Salim'le konuşmanız oldu mu?

Yüksel Güran : Hayır hayır, kesin konuşma olmadı. Yemin ederim, yemin ederim.

Mahkeme Başkanı : Peki. Yüksel Hanım Nevzat'ı gördünüz mü?

Yüksel Güran : Hayır.

Mahkeme Başkanı : Yani aşağı indin geldin?

Yüksel Güran : Hayır.

Mahkeme Başkanı : Hediye Nevzat'ı görmüş mü?

Yüksel Güran : Çünkü biz Nevzo'nun tarafına evine gitmiyoruz.

Mahkeme Başkanı : Ya gitmiyorsunuz da evin etrafında, dışarıya çıkarken ben evinizin videolarını izledim. Yani böyle dışarıya çıkarken etrafa baktınız mı?

Yüksel Güran : Hayır. Ya hiç bakmamışız. Yani baksanıza biz hiç onları görmemişiz.

Mahkeme Başkanı : Görmemişsiniz.

Yüksel Güran : Hayır yemin ederim. Dinamoyu çalıştırdım. Balkonu yıkadım. Biraz evi şeyi hışları yıkadım. Su bahçemiz damlamadır. Suyu bahçeye gönderdim. Evin içine girdim. Biraz evi toplarım da, çocukturlar. Evi biraz toparladım o zaman. Dama çıktım. Dama çıktığım zaman yatakları sereceğim. Gördüm Enes'leri arkadaşları sesler oradan geliyordu bana. Aşağıya indim. Pilavı üstüne bıraktım, fırla dışarıya attım kendime. Baktım Eren de o tarafa da geliyordu. Dedim oğlum abin hala orada, anne abim orada. Gittim Enes'te iki kardeş onları Ufuk, Furkan adları karıştırıyorum. Büyüğü oradaydı. O şey Yusuf. O zaman dedim Yusuf'tur, İsa'dır. Tam fark etmiyor. Yani adları karıştırıyorum. Evet. İkisi de oradaydılar. Enes'in aklına gelmiyordu. İkisi sigara içiyordu. Enes sigara içse içmezse bilmiyorum. Çünkü elinde görmedim. Dedim oğlum yazık günahtır. Sizin ciğerinizi nedir siz sigara içiyor? İkisi de geldi.

Mahkeme Başkanı : Tekrar sorayım. Diyarbakır'da sigara bizim bildiğimiz sigara olarak anlaşılmayabilir. Normal düz sigara değil mi?

Yüksel Güran : Normal sigaradır.

Mahkeme Başkanı : O esrar değildir?

Yüksel Güran : Ya hayır hakimim sonra televizyona yayılmışlar. Sigaradır, tütündür, eroindir. Afedersiniz.

Mahkeme Başkanı : Diyarbakır'da sigara içiyorum demek esrar içiyorum demek.

Yüksel Güran : Ya biz, biz de sigara diyoruz.

Mahkeme Başkanı : İşte bizim de sanıklar sigara diyor. Biz de sigara diyor. Başkanım bir sigara içtik diyor. Bir sigara dediği esrar. Bize de cigara içtik diyorlar. Sigaraya sigara diyorlar. Esrara cigara diyorlar.

Yüksel Güran : O zaman da Show TV oradaydı. Saatler de geçmedi. Baktım bizimki hepsi üstüme geliyorlar. Dedi Yüksel sen dedi tütündür, eroindir. Kızı çağırdım. Oradan Büşra'ydı neydi adı. Dedim gel bunu düzelt. Ben sana dedim sigara, bu nedir? Tekrar şey Show TV aradı. Dedi Yüksel oğlan siz diyorsun sigara biz diyoruz ki tütün. Hatta bana da öyle dedi. Bütün de sigarasından çok bir fark yok canım. Yani o öyle dediler. Sonra bizi onu çağırdı. Enes'i çağırdım. Enes geldi. Ben içmediğim için. Zaten öyle de Enes'e demişim. Oğlum akşam biz o ahırın penceresi kapatayım. Köpek hindimizi yemiş, ahıra hindileri koyayım. Enes geldi, bana yardım etti. O pencereyi kapattık.

Mahkeme Başkanı : Tamam. Şöyle. Burada müdahale edeyim. Devamı zaten var. Şimdi yani daha önceki bu konuda verdiğiniz beyanlarınız da benzer mahiyette.

Yüksel Güran : Doğru.

Mahkeme Başkanı : Peki Yüksel Hanım şimdi televizyonlara verdiğiniz röportajda.

Yüksel Güran : Evet.

Mahkeme Başkanı : Röportajlarda hep şöyle diyorsunuz. işte kim öldürdüyse gelsin bir yere koysun. En azından cesedi belli olsun.

Yüksel Güran : Bunu hiç dememişim. Yemin ederim bunu dememişim. Mesela etrafımızda millet vardı. Her zaman diyorum Allah'ım. Ölüm bunu yanında tatlıdır. Çünkü sekiz yaşında kızım vardır. Kayıptır. Bütün Türkiye arıyor, kızımı bulamıyorlar. Dedim ölüm bunun yanında tatlıdır. İnsan ölse bir mezarı olacak. Kızım ortada yok. Bütün Türkiye kızımı arıyor yoktur. Ben bunu için demişim. Her ne konuşmuşum tersine gitmişler.

Mahkeme Başkanı : İşte tersine gitmiştir o yüzden biz de soruyoruz.

Yüksel Güran : Evet ben bunun için diyorum. Ölüm bunun yanında tatlıydı.

Mahkeme Başkanı : Ben notumu almışsın. Vermiş olduğunuz 28.08. Gazal diyor ki beyanında; 28.08'de saat 19:00'da kimle birlikte geldi? O vardı. Arkadaşlar kim vardı arkasında? Enes vardı. Bir de şey vardı. Yüksel'in 19 sıralarında geldiğini dizine vurarak "Hanginiz kızımı götürdü? Kim götürdüyse geri getirsin bir köşeye bıraksın. Mezarı belli olsun" diye.

Yüksel Güran : Hayır. Kesinlikle yemin ederim yalan söylüyorsunuz 19'la. Ben sayın avukatlarım da söylüyordum. Öyle söylüyorsun ben anlamıyorum. Mesela saat 7.

Mahkeme Başkanı : 7. Saat 07:00. 07:00-08:00. Olay günü. Evet.

Yüksel Güran : Oraya kadar gelsem söyleyeyim. Evet yani bitene kadar.

Mahkeme Başkanı : Tamam.

Yüksel Güran : Evet şu anda ben neredeydim?

Mahkeme Başkanı : Neredeydin en son? Neredeydi? Enes'le birlikte sigarayı geçtik. Sigarayı geçtik. Evet sigarayı içiyorduk. Hindi hindi. Evet. Hindideyiz.

Yüksel Güran : Enes geldi. Biz ahırın penceresini kapattık. Hindileri iki dakika ahıra koydum zaman. Tamam. Sonra Muhtar'ın kapısına gittim. Muhtar'ın kapısına. Çünkü Melek'in babası göz ameliyatı olmuştu. Nazan orada. Dilek orada. Gamze orada. Oraya gittim, dedim geçmiş olsun. Sizin babanın durumu nasıl? Çok şükür iyidir. Böyle konu elbiseye girdiği zaman da ben onlara da dedim vallahi pilavın üstünde yanar. Eve koştum. Koştum zaman gittim, baktım Muhammed o taraftan geliyor. Eren de geliyor. Enes de o zaman geliyor diler. Çocuklar zaten önce diyor bize açın. Dedim Muhammed sen Maşallah biz tepede birbirini çağırıyoruz. Narin'i çağır, Narin eve gelsin. Ben mutfağa koştum. Soframızda hatta dedim Eren de Enes de bilmiyorum. Bence Eren dedim oğlum Sofrayı ser. Pilavın temsili üstüne bıraktığım zaman baktım Muhammed mutfağa geldi. Diyor, anne Narin orada değil. Öyle dediği zaman oğlum nasıl Narin orada değil? Narin oraya gitti. Anne yenge Maşallah diyor Narin buradadır. O zaman ben Hediye'yi aradım. Hediye dedi, Yüksel Narin bize de dedim Damla ya Ecrin birisi Yasemin'e Gül'e koysun ha Narin orada diyor. Ben tepeye çıktım. Enes Muhammed'e de aşağıya gönderdim. Dedim gidin cami yanına Narin oradadır Narin getirin. Hiç Narin kaybolma aklımızın ucuna girmiyordu. Tepede Maşallah çağırdım. Maşallah dedi, Yüksel Narin burada değil. Dedim kızlara söyle. Narin size gelecekti. Kızlara konuştu. Kızların sesi bana gelmiyordu. Dedi Yüksel vallahi Narin burada değil. Ben bilmiyordum öğleden oraya gitmemiş. Ben diyordum ki belki Narin gitmiş, sonra Narin çıkmış. Aklıma gelmiyor Narin, kayboldu. Camide oraya gitmemiş. Sonra Süveyla abla oradaydı. Saman dolduruyordu. Dedim Narin İbrahim kızın yanına gelmemişti. Dedi vallahi İbrahim işte kızını yeni hastanede getiriyor. Narin nereye gidecek? Ya Hediyegil'dedir ya Yasemingil'dedir. Ben tekrar Hediye'yi aradım. Çünkü önce de Hediye'yi aramıştım. Hediye dedi Yüksel vallahi kızlar daha gelmemiş. Dedim, Eren Yasemin'in numarasını bilmiyordum çıkartayım. Eren oradaydı. Dedim Eren'in numarasını çıkart, Eren de Muhammed tam aklıma gelmiyordu. Yasemin numarayı aradık. Yasemin dedi Yüksel Narin buradadır. Saliha Kaya'yı aradım. Kız kardeşimdir. Eren'in fotoğrafı onun numarası üstünde olduğu zaman biliyordum. Kızı çıktı, dedi vallahi teyze Narin buraya gelmemiştir. Tak aklıma halası kaldı. Dedim kesin halasına gitmiş Azize Kaya. Azize demiş, Narin gitme akşam birlikte gideceğiz. Ben de koşarak gittim. Gittim Azize'nin kapısını çaldım. Dedim Narin buraya gelmemiş? Dedi vallahi Yüksel Narin buraya gelmemiş. Korktum, dedim cami çok büyüktür. İnşaattır. Dedim inan ki Narin orada oynamış. Kafası bir yere değilmiş. Kimse görmemiş. Kafama da söylüyorum. Ben camiye koştum. İki elle caminin kapısına vuruyorum. Gelin kapıyı açın. Gelin kapıyı açın. Narin kayıptır. Millet topladı bana. Baktım İsa Kaya yanımda. Dedi Yüksel saat 6'da da Narin buradaydı. Öyle dediği zaman ben gevşeledim. Dedim okul arkadaşları oradadır. Demek ki havuçlara dalmış. Oynamaya dalmış. Hepimiz aramaya başladık. Bir aşağıya gidiyoruz, bir yukarıya gidiyoruz. Her tarafa gidiyoruz. Narin'i arıyoruz. Narin'i bulamıyoruz. Hatta Gazal. Nevzo'nun karısı da benimle geldi. Beni teselli ediyor. Yüksel korkma. Yüksel bir şey olmuyor. Yüksel belki bir yere düşmüyor. Belki bir yere yatmıştı. Hatta bunu da gayet hatırlıyorum. Ben tarlada bir gece tarlada yatmışım. O da beni teselli ediyor. Sonra bana yetişti. Bütün köy etrafımızda hepimiz Narin'i arıyoruz. Bir delik nerede olsa oraya gidiyor. Bir çukur nerede olsa gidiyor. Bir tehlikeli yer nerede olsa hepimiz Narin'i aramaya başladık. Sonra kim jandarmayı aradı, bilmiyorum. Bir baktım dünya bizim başımıza yıktı. Herkes telefondur. O onu aradı. O onu aradı. Dünya daha hepsi sanki bütün dünya Tavşantepe'ye girdi.

Mahkeme Başkanı : Yani Narin'i sen öldürmedin?

Yüksel Güran : Yemin ederim ben nasıl kızımı öldüreceğim?

Mahkeme Başkanı : Peki Salim öldürdü mü?

Yüksel Güran : Hiç aklıma gelmiyor.

Mahkeme Başkanı : Salim'in öldürmesi?

Yüksel Güran : Hayır.

Mahkeme Başkanı : Nevzat'ın öldürmesi aklına geliyor mu?

Yüksel Güran : İşte ortadadır. Ben bunu hiç kimseye savunmuyorum.

Mahkeme Başkanı : Şimdi ortada, ortada dediğin şey, Nevzat ben öldürdüm demiyor. Salim'le öldürdü. Salim öldürdü. Ben aldım. Yüksel gördü diyor.

Yüksel Güran : Salim öldürmüşse kim öldürmüşse ben onları Allah'a havale ediyorum size havale edeceğim. En ağır ceza onlara vereceksin.

Mahkeme Başkanı : Oğlun öldürmüş olabilir mi?

Yüksel Güran : Hayır.

Mahkeme Başkanı : Yüksel Hanım başından beri tutanaklarda sizde Kürtçe söyleşi yapılmış o tutanaklarda işte bilmiyorum ne kanallarına katıldığınız farazi kanallarına katıldığınız verdiğiniz röportajlarda hep diyorsunuz ki işte biz Yasin okuduk. Narin'in cesedini bir kere bırakın. Kim Narin'i öldürdüyse getirsin en azından yerini bilerim.

Yüksel Güran : Hayır kesinlikle biz bunu söylememişiz. Yemin ederim hiçbir zaman Narin'i öldürmekten hiç şey olmamışım. Abi Enes'in dediğim gibi Hüseyin Hüseyin Kaya vardı dedi. Saat üçte biliyorum kaç dakika geçiyor. Hızla bir kornet araba kapımızı öne geçmiş zaman hep bizim ailemiz hani kendim adıma söyleyeyim aklım o arabadaydı. Diyorum kesin Narin gelmiş Narin'i kaçırmışlar. Bingo'lu kızı da söylüyoruz ki yemin ederim kendimden geçmiştim. Bu koltuğu üstünde benim ailem beni uzattığı zaman sonra baktım görümcem geldi dedi Yüksel kalk bu sana soruyor. Kalktım kalkmadım kadın kız benim boynuma sarıldı ağladı ağlıyordu. Ben zaten ağlıyorum. Dedi annem hastadır yatalaktır kardeşimi kaybetmişim dedi git Yüksel'in yanına. Beni zaten tanımıyordum. Kim gelseydi üstüme atıyor ağlıyordu ben de ağlıyordum.

Mahkeme Başkanı : Peki bu direk konudan konuya geçelim ki biraz da beyin fırtınası olsun. Bu kadınlar kavgasından haberiniz var mı senin?

Yüksel Güran : Hayır. Ben o zaman ambulansın içindeydim.

Mahkeme Başkanı : Kadınlardan sana yani hakaret verecek sözler söyleyerek de doğruyu konuşsaydınız bu aşamaya gelmezdi. Sana bakarak "orospu" gibi şeyler söylemiş.

Yüksel Güran : Hayır ben hiç kimse görmemişim. Zaten kendimde değildim. Hülya komutan geldi. Önceden daha televizyonda duydum. O jandarma o şey ben biliyorum artık Narin'e bir şey gelmişti. Hala dedi, ailem beni teselli ediyor. Ya hala belli değil, belli değil bana söylüyor der.

Mahkeme Başkanı : Peki jandarma arkadaşlar senin neden Enes'i koruduğuna kanaat getirmişler? Çünkü tutanaklarda annenin Enes'i koruduğunu acaba Enes'i nasıl kurtarırım? Acaba Enes'i nasıl korurum? Diye böyle bir tutanaklar var. Böyle bir izlenimleri var jandarmanın.

Yüksel Güran : Bunu da söyleyeceğim. Ben karakoldaydım. Affedersin ben lavaboya gittim. Hülya komutan benimle lavabo içine geldi. Dedi Yüksel yarın size geleceğim. Ben diyeceğim ben adetliyim. Beni yatak odasına al. Ben sana bir şey söyleyeceğim. Ben de diyorum Allah'ım bu komutan gelecek bana ne söyleyecek? Birinci gün gelmedi, ikinci gün geldi. Beni aynı o şekilde lavaboya gitti. Benim o ben onu o yatak odasına aldım. Dedi Yüksel Ankara'da bir daire içinde senin fotoğrafın vardır. Enes'in bütün ailenin kocanın bütün fotoğrafları vardır. Hepsini öldüreceğim onları. Mafyadır, büyük bir mafyadır. Ve hepsi size soruyorlar. Affedersin bu cümleyi milletin içine söylüyorum, utanıyorum de söylüyorum.

Mahkeme Başkanı : Söyle utanma boş ver.

Yüksel Güran : Mecburum söyleyeceğim. Dediler biz Enes'e sikeceğiz kapıyı önüne atacak. Ben Eren'i öldüreceğim, onu öldüreceğim, onu bak. Ben şu anda ikna etmesinler. Bunlar hepsi bana dedi. Ben de o korkuda her zaman diyordum. Allah'ım çocuklarıma ne olacak? Enes'e ne olacak?

Mahkeme Başkanı : Bu sana mantıklı geliyor mu?

Yüksel Güran : E bana öyle söyledi.

Mahkeme Başkanı : Tamam. Sizin bir mafyaya ne husumetiniz olacak da?

Yüksel Güran : Bana söyledi.

Mahkeme Başkanı : Ya Yüksel Hanım ben de sana söylüyorum. Benim her söylediğime inanıyor musun da? Sen bilmem ne komutanın öyle bir iddiasına inandın.

Yüksel Güran : Ben inanmadım. Belki ondan ben Enes'i. Mesela karakola içindeydim. Oğlum küçüktür.

Mahkeme Başkanı : Demedin mi bizim mafyayla ne işimiz olur? Biz kendimiz köyümüzde bir vatandaşız demedin mi?

Yüksel Güran : Söylüyordum. Söylüyorum dedi. O bana dediği zaman ben de şoktaydım. Allah'ım bu ne mafyası?

Mahkeme Başkanı : O zaman sen ondan sonra o Enes'i nasıl kurtarırım demeye başladın.

Yüksel Güran : Karakola gidiyordum. On kişi jandarmanesinin etrafındaydım. Bütün zaten o memurlar o.

Mahkeme Başkanı : Bu komutan adı ne?

Yüksel Güran : Hülya komutan bana öyle.

Mahkeme Başkanı : Hülya komutan.

Yüksel Güran : Evet.

Mahkeme Başkanı : Sana böyle bir şey söyledi.

Yüksel Güran : Evet bana söyledi.

Mahkeme Başkanı : Sen de ondan sonra acaba ben nasıl Enes'i kurtardım moduna girme. Yani senin Enes'i nasıl kurtardım demenin sebebi bu. Öyle mi?

Yüksel Güran : Evet bundan korkuyordum. Mesela karakolda dedi. Bütün memurları artık tanıyordum. Enes elinde kelime odayı götürüyor. ben ona soruyordum. Enes nasıldır? Ona söyledim Enes nasıldır. Hatta orada komutana da rica edeyim ne olur? Bana izin verin bir oğluma sarılayım. Ve bundan beni çocuklarıma, çocuklarıma hiçbir şey günahı yoktu. Ben niye çocuklarımdan korkuyacağım? Niye koruyacağım?

Mahkeme Başkanı : Yani bana böyle dediği zaman bir oradaki iddia şudur. Yani bunu bunu şu şekilde yorumluyorlar. İşte Enes şeyi öldürdü. Narin'i öldürdü. Hani burada da bu coğrafyada erkek çocuğu kıymetlidir. Narin gitti. Bari Enes gitmesin de cezaevine girmesin. İddia bu.

Yüksel Güran : Yemin ederim. Öyle bir şey yoktur aramızda.

Mahkeme Başkanı : Peki dur. Bu soruya cevap vermeme hakkına sahipsin. Narin'i, Enes öldürse kendi ellerinle teslim eder misin?

Yüksel Güran : Yemin ederim, teslim ederim.

Mahkeme Başkanı : Peki.

Yüksel Güran : Hiç kimse burada Narin kadar benim için kıymetli değil. Dünyada bir kızım vardır. Yedi yaşında Tülin'i besledim. Bir gün bana anne demedi. Bir gün bana demedi bunu yedir. Bir gün bana demedi bunu yedir. Kızım özürlüydü. Kızım öldüğü zaman bütün sevgimi Narin'e verdim. Beş çocuk oğlum vardı. Babası da orada hepimiz Narin'in üstünde ölüyorduk.

Mahkeme Başkanı : Adını da o yüzden mi Narin koydunuz?

Yüksel Güran : Yo diğeri Tülin'dir, bu Narin'dir.

Mahkeme Başkanı : Niye Narin koydunuz adını?

Yüksel Güran : Kızım diğer kızım Tülin'dir.

Mahkeme Başkanı : Tamam onu anladım.

Yüksel Güran : Buna Narin ismini. Bizim için çok kıymetli.

Mahkeme Başkanı : Anladım. O yüzden Narin mi koydunuz diye.

Yüksel Güran : Evet. Narin için hepimiz ölüyorduk.

Mahkeme Başkanı : Anladım. Şimdi yani bu şey tekrar bunu tekrar soruyorum. İşte kim öldürdüyse getirsin. Cesedini bilelim. En azından yerini bilelim. En azından mezarını bilelim. söylemlerin sebebi neydi?

Yüksel Güran : Kesinlikle bunu bir şey söylememişim. Yemin ederim bunu bile şöyle söylememişim. Sadece o kadar bütün Türkiye Narin'i arıyor. Delik delik ediyorlar. Narini bulmuyorlar. O kadar acımız çoktur. O kadar ciğerimiz yanıyordu. Dedim ölüm bunun yanında tatlıdır. İnsan öldüğü zaman mezarı oluyor. Narin nerededir? Sekiz yaşında bir kızdır. Ben bunu içi söylüyorum.

Mahkeme Başkanı : Ha bunun için öyle cümleler kullanmış olabilirsin ama o cümleleri o manada kullanmadın yani.

Yüksel Güran : Yo hayır kesinlikle.

Mahkeme Başkanı : Yani o cümleyi kullanmadığını inkar etmiyorsun da kullandığın düşünce yani altındaki mananın o olmadığını söylüyorsun doğru mu?

Yüksel Güran : Evet. Onda sadece dedim ölüm bunun yanına tatlıydı. Bütün Türkiye kızımı arıyor bulamıyorum.

Mahkeme Başkanı : Peki şimdi Yüksel Hanım bu HTS analiz raporu var. Avukatlarınız itiraz ediyor. Onu biz yargılamanın sonunda bunun rapor olup olmadığına kanaat getireceğiz. Bu rapora göre senin telefonun evde.

Yüksel Güran : Evet telefonum evdedir.

Mahkeme Başkanı : Enes'in telefonu da evde.

Yüksel Güran : Evet, Enes götürmüş götürmemiş bilmiyorum. Muhammed'i ben belki götürmüşse hiç telefonu kullanmıyordum.

Mahkeme Başkanı : Bir yerde 15:20'de Salim eve giriyor.

Yüksel Güran : Kesinlikle!

Mahkeme Başkanı : Şimdi bakın.

Yüksel Güran : Kesinlikle evimize gelmemiş!

Mahkeme Başkanı : Şimdi bize Nevzat'ın öldürdüğünü söylüyorsunuz ya. Yani öyle Nevzat diyor ya. Şimdi Nevzat'ın beyanına göre Nevzat'ın beyanına göre dediniz ya o Nevzat söylüyor. Nevzat da eve geldiğini söylüyor. Bak Nevzat'ın eve geldiğindeki baz verileri eve girdiğini söylüyor. Diyor ki, evet Nevzat Arif'lerin evine girmiştir diyor bazda. Ama aynı baz senin de evde olduğunu söylüyor. Aynı baz Enes'in de evde olduğunu söylüyor. Aynı baz Salim'in de eve geldiğini söylüyor.

Yüksel Güran : Kesinlikle yemin ederim. Yemin ederim, ne Salim ne Nevzat evimize gelmemişler. Evi etrafına gezmişler. Biz bilmiyoruz. Biz evde yatıyoruz yemin ederim.

Mahkeme Başkanı : 16'da evde yatmıyorsun. Yani onların gezdiği saatte de ayaktasın. Onların evin etrafını gezdiği saatte uyumuyorsun sen.

Yüksel Güran : O saat kaçtır?

Mahkeme Başkanı : O saat kaçtır? 15:30'dur. Üç buçuk, üç buçuk.

Yüksel Güran : 3, 15. Biz evdeyiz.

Mahkeme Başkanı : Tamam evdesin, uyumuyorsun, ayaktasın. Evin etrafında gezse görmez misin?

Yüksel Güran : Kesinlikle evin etrafına gelse biz evi içindeyiz. Biz şey yapıyoruz. Sıcaktır. Klimamız çalışıyor. Penceremiz kapatıyor. Biz nerede bulacağız? Nerede göreceğiz?

Mahkeme Başkanı : Ya gölgelik olur.

Yüksel Güran : Hayır görmüyoruz. Penceremiz.

Mahkeme Başkanı : Köy yerinde evin etrafında gölgelik olmaz mı pencereden?

Yüksel Güran : Dışarıda kim gelse biz nerede biliyoruz? Evde oturuyoruz, uzanıyoruz.

Mahkeme Başkanı : Nasıl köy ya burası?

Yüksel Güran : Bizim etrafımızda ev yoktur.

Mahkeme Başkanı : Tamam işte. Tamam işte. Evin etrafında ev olmadığı için dışarıda olan bir sesten daha çok merak eder çıkarsın.

Yüksel Güran : Evi içindeyiz. Hediye gelene kadar biz yatıyoruz. Dışarı hiç çıkmıyoruz. Yemin ederim biz çıkmamışız.

Mahkeme Başkanı : Yani dışarıda hiçbir ayakkabı sesi, konuşma sesi, hiçbir şey duymadınız?

Yüksel Güran : Hayır.

Mahkeme Başkanı : Araba. Hiç ne araba?

Yüksel Güran : Binlerce ifade vermişim. Arabayı görsem sesi gelse de pencereyi açacağım. Bu araba kimdir?

Mahkeme Başkanı : Diğer bir iddiayı söylüyorum. Salim'le bir ilişkiniz var mı?

Yüksel Güran : Hayır. Yemin ederim, yemin ederim Salim'le hiçbir alakamız yoktur. Kur'an-ı Kerim yoktur.

Mahkeme Başkanı : Peki Yüksel Hanım şimdi Nevzat iftira atıyor diyelim. İddiayı söylüyorum. Söylemlerimin hepsi tüm iddianamenin de iddiaları sanık müdafilenin de iddiaları Diyarbakır Barosu'nun da iddialarıdır. Hiçbirini kabul etmiyorum tamam mı? En son neyi kabul ettiğimizi gerekçeli kararda size izah edeceğiz. Şimdi sen öncelikle şunu sorayım. Sen ahıra girdiğinde oğlunun başka biriyle uygunsuz bir şekilde gördün mü?

Yüksel Güran : Hayır.

Mahkeme Başkanı : Başka bir kızla ilişkisini gördün mü?

Yüksel Güran : Kesinlikle.

Mahkeme Başkanı : Başka bir hayvanla bir ilişki?

Yüksel Güran : Hayır, hayır, hayır. Öyle bir şey benim çocuklarım akıllı bir çocuklar, öyle bir şey yoktur.

Mahkeme Başkanı : Enes'in öyle bir şeyine şahit olmadın?

Yüksel Güran : Kesinlikle öyle bir şey yoktur.

Mahkeme Başkanı : Öyle bir şey yok. Peki Nevzat şimdi Salim ailesiyle Arif ailesi yani iki aile arasında sizin aile ilişkileriniz nasıl? Normal, yani bu ilişki manasında şey ilişkisi değil cinsel ilişki değil. Akrabalık ilişkisi soruyorum.

Yüksel Güran : Hiçbir sorunumuz yoktur.

Mahkeme Başkanı : Evin Salim Güran ailenin reisi midir?

Yüksel Güran : Salim kendine evinin reisidir. Arif kendine evinin reisidir. Sadece Salim'in elinde tarla vardır. Hiçbir şey kimse kimse evin reisi değildir.

Mahkeme Başkanı : Değildir.

Mahkeme Başkanı : Nevzat'ın Salim'e iftira atma ihtimali var mı?

Yüksel Güran : Onlar biliyor. Allah biliyor.

Mahkeme Başkanı : Onu Allah biliyor.

Yüksel Güran : Allah biliyor.

Mahkeme Başkanı : Allah her şeyi biliyor. Nevzat'ın size iftira atma ihtimali var mı?

Yüksel Güran : Tabii kesinlikle iftira atıyor.

Mahkeme Başkanı : Ben de onu soracağım. Tamam. Ben de işte neden? Tamam. Çok güzel. Ben de onu soracağım. Neden Nevzat iki kişiye birden iftira atıyor? Sadece ben öldürdüm. Salim de, Salim de bana cesedi verdi dese Salim'e iftira atıp Salim'i yakar. Seni niye yaktı bu o adam?

Yüksel Güran : Ya ben sana bir şey söyleyeyim. Gerizekalı. Tavuk öldürmüş Salim. İki dakikada suç ortağı oluyor.

Mahkeme Başkanı : 7 dakika.

Yüksel Güran : 7 dakika'da 5 dakika nasıl suç ortağı oluyor?

Mahkeme Başkanı : İşte bakacağız.

Yüksel Güran : Ben buradan çıkartmak istiyorum. Ben Narin'in istiyorum. Ben Narin'in sebebini istiyorum.

Mahkeme Başkanı : İnşallah.

Yüksel Güran : Bırakmadılar. Sayın Hakimim Narin'e gelinlik giydireyim. Kefen giydirdiler onu. Kefen kızıma giydirdiler.

Mahkeme Başkanı : Biz de onun için.

Yüksel Güran : Hayalimizi yıktılar. Evimizi yıktılar. Namusuma leke sürdüler. 22 sene ben evliyim. Gidin o köyde sorun. Gidin bütün telefona bakın. Ben kocamı tırnaklı görenleri benim aileme tırnaklı dünyaya veremem. 22 sene ben evliyim. Hiçbir hata olmadı. 5 tane çocuklarım var. Allah ıslah etsin. Bakın bunların hepsi şeydir. Ben nasıl namusuma leke sürüyorum? Kocam bu 22 sene bir gün tokat bana vurmamış. Bir gün yüzüme tükürmedi. Beni gül gibi baktı. Ben kocama saçımı süpürge ediyordum. Ben böyle bir kadınım. 5 kilo, 4 kilo bamya için saat beşte kalkıyorum. Gözüm dışarıda olsa 5'te kalkmıyorum 4 kilo bamya için. Çocuklarım harçlığı için. Çocuklarımın geleceği için. Evime bir tabak alsın. Bir battaniye alsın çocuklarıma. Beni öldürün. Salim'le benim alakam yok burada. asın beni burada.

Mahkeme Başkanı : Peki niye Nevzat böyle bir iftira atıyor?

Yüksel Güran : Yalan söylüyor. Bakın yüzüne.

Mahkeme Başkanı : Bana bak.

Yüksel Güran : Bu insandır?

Mahkeme Başkanı : Bana bak, bana bak.

Yüksel Güran : Bu insandır? Beni öldürün, namusuma leke sürmeyin. Güran'lara leke sürmeyin.

Mahkeme Başkanı : Yoktur böyle bir şey diyor.

Yüksel Güran : Kesinlikle öyle yoktur.

Mahkeme Başkanı : Tamam. Enes de eve gelmedi. Şey Salim de eve gelmedi.

Yüksel Güran : Yemin ederim, yemin ederim, Kur'an-ı Kerim yemin ederim Salim, Nevzat evimize gelmemişler. Günahım geldi bana. 5 tane çocuklarım vardır. Eren şey cezaevi geliyor. Anne niye buradasın? Annen niye eve gelmiyor? Yazık bütün çocukların psikoloji bozulmuş.

Mahkeme Başkanı : Evet. Zaten olan yine çocuklar oluyor da camiye kaç gibi gittiniz? O ikindi öğleden önce akşama yakın caminin kapısını vurdu, merkez geldi dediniz ya.

Yüksel Güran : Evet.

Mahkeme Başkanı : Saat kaç gibiydi?

Yüksel Güran : Saat biz evdeydi, ezan okuyorduk.

Mahkeme Başkanı : Akşam ezanı. Akşam ezanı okunuyordu. 21 Ağustos 7.5-8 sekiz arası ezan okunuyor.

Yüksel Güran : Sonra biz camiye gittiği zaman Narin'i aramayı başladığı zaman sonra sayın hakimim biz eve geldiği zaman bütün dünya jandarma hepsi geldiği zaman bu bu ifadeleri çıktılar. Şeyma Kaya, Şeyma Kaya demiş İbrahim Güran geldi dedi yenge. Şeyma Kaya dedi 4-4.5'ta ben Narin'i görmüşüm. Üzüm yaprakları topluyordun.

Mahkeme Başkanı : Evet. Söyledin.

Yüksel Güran : Evet. Söyledim.

Mahkeme Başkanı : Anladım. Anladım. Ben sadece saati merak ettim. Çünkü o da başka bir saat söylediğin için. Soru var mı? Hakim Bey? Sormak istediğiniz bir şey var mı? Tamam biz daha sonradan tekrar. Sayın savcım sormak istediğiniz soru var mı? Buyurun mikrofonu yakın. Buyurun.

## Duruşma Savcısı

Duruşma Savcısı : Saat 13:30 gibi Narin evden çıktıktan sonra uyuduk dedin, değil mi?

Yüksel Güran : Narin çıktığı zaman biz uyuduk.

Duruşma Savcısı : Tamam. Önemli değil. Evet. O civarda. Kaç gibi kalktınız dedin?

Yüksel Güran : Bilmiyorum saat kaçtı.

Duruşma Savcısı : Ortalama mesela.

Yüksel Güran : Ortalama hiç saatim aklıma gelmiyor. Birinci ben kalktım bir su içtim.

Duruşma Savcısı : 2, 3, 4?. 8'e kadar uyumadınız?

Yüksel Güran : Yo yo size Hediye geldiği zaman saat kaçtı bilmiyorum. Yemin ederim saat bilmiyordum.

Duruşma Savcısı : Tamam Muhammed de uyuyor muydu?

Yüksel Güran : Hediye geldiği zaman. Hediye geldiği zaman Muhammed kalkmıştı.

Duruşma Savcısı : Kapıyı kim açtı Hediye'ye? İki kere geliyor.

Yüksel Güran : Birinci diyor Hediye sorabilirsin.

Duruşma Savcısı : Sana kim söyledi Hediye'nin geldiğini ilk?

Yüksel Güran : Muhammed Eren.

Duruşma Savcısı : Muhammed evet.

Yüksel Güran : Muhammed Eren kapıyı onu açıyor herhalde.

Duruşma Savcısı : Kapıyı Eren açıyor. Evet.

Yüksel Güran : Birinciyi açıyor. İkinciyi açıktır Hediye içeri geliyor.

Duruşma Savcısı : Tamam sen ilk ifadende savcılıkta Muhammed kapıyı açmış.

Yüksel Güran : Bilmiyordum. Bana söylemiş demiştin. Bu bilmiyordum.

Duruşma Savcısı : Muhammed kapıyı açtı demiştin.

Yüksel Güran : Ben demişim. Doğruyu söylüyorum. Ben demişim kalktı ikisi dedi anne; Hediye yenge elbisemi getirmişti. Ben dedim Muhammed'tir. Sonra duyduğun zaman Eren açmıştı.

Duruşma Savcısı : Tamam.

Yüksel Güran : Çünkü ben yatıyordum.

Duruşma Savcısı : Öğlen Muhammed de uyudu dedin. Evet. Birlikte uyudunuz değil mi? Enes saat, az önce, dedi ki Enes ifadesinde. 16'da kalktım dedi. 16'da kalktım dışarı çıkacak Enes.

Yüksel Güran : Evet.

Duruşma Savcısı : Muhammed uyuyordu dedi.

Yüksel Güran : Enes yanlış görüyordu.

Duruşma Savcısı : Efendim?

Yüksel Güran : Enes yanlış söylemişti. Çünkü ben oradaydım.

Duruşma Savcısı : Enes bütün hayatı boyunca yanlış söyleyemez. Savcılıkta da yanlış söyledi.

Yüksel Güran : Çocuklar aklına gelmiyordu.

Duruşma Savcısı : Bekle biraz. Bak, 1.5'ta yattık dedin. Tane tane gidiyoruz.

Yüksel Güran : Evet.

Duruşma Savcısı : Saat 4 oldu. Enes çıkacak. Hediye gelmiş Hediye yengem. Uyandım. Hediye yengem evdeydi.

Yüksel Güran : Evet.

Duruşma Savcısı : Muhammed yatıyordu. Muhammed hala yatıyor.

Yüksel Güran : Hayır Muhammed yatmıyordu.

Duruşma Savcısı : Yatmıyordu.

Yüksel Güran : Eren yanlış Enes yanlış söylüyor.

Duruşma Savcısı : Enes tamam. Enes yalan söylüyor yani.

Yüksel Güran : Yalan değildir. Yalan.

Duruşma Savcısı : Uyuyup uyumadığını bilirsin Yüksel.

Sanık Yüksel Müdafi : Demin bu soruyu bana sordurtmadınız.

Yüksel Güran : Evet. Yani yanlış söyledi. Belki çocuk yanlış görmüş.

Mahkeme Başkanı : İyi etmişim. Ona da iyi etmişim.

Sanık Yüksel Müdafi : Sordurdunuz ama.

Mahkeme Başkanı : Tamam ona da iyi etmişim dedim. İkisine de iyi etmişim dedim yani.

Sanık Yüksel Müdafi : Yalan söylüyorsunuz da.

Mahkeme Başkanı : Tamam işte avukat ikisine de iyi etmişim dedim yani. Ne diyeyim?

Yüksel Güran : Ben burada da söyleyeyim. Her şey Enes'in aklına belki gelmiyor. Çocuktur.

Duruşma Savcısı : Tamam peki. Enes'in aklına gelmiyor çocuktur. Burayı kapattık. Kapının önüne çıktım dedim. Enes dışarı, Enes dışarı çıktı saat 4'te. Önemli değil. O kısım saat önemli değil. Hediye'yi uğurlayacaksın evden değil mi?

Yüksel Güran : Evet.

Duruşma Savcısı : Kapıya çıktık dedin. Enes neredeydi o an? Karşıdan mı geliyordu?

Yüksel Güran : Biz kapıya çıktık. Balkona böyle geçiyoruz ya. Enes dışarıda geldi.

Duruşma Savcısı : Enes'le Hediye karşılaştı mı?

Yüksel Güran : O Hediye oradaydı. Enes diyor ben görmüyorum ben de şaşırdım.

Duruşma Savcısı : Tamam, Hediye sana ifadesinde şey dediğini söylüyor.

Yüksel Güran : Evet, belki hani görmemişti ve aklına geldi.

Duruşma Savcısı : Sen "Oğlum niye erken geldin? Dışarıda kimseyi bulamadım çok fazla."

Yüksel Güran : Evet.

Duruşma Savcısı : Böyle bir cümle kuruldu mu?

Yüksel Güran : Bence öyle ya dedim aşağı oğlum senin.

Duruşma Savcısı : Hediye yanında mıydı bu konuşma olduğunda?

Yüksel Güran : Evet öyledir.

Duruşma Savcısı : Tamam yani Enes ikinci kere nakavta çıktı şu an. Enes gene. Tamam.

Yüksel Güran : Evet Enes yanlış söylüyor. Ben de buradaydım gördüm yanlış söylüyor.

Duruşma Savcısı : Tamam. Bu Enes Osman kardeşini aramış. Senin yanında mı aradı terlik için?

Yüksel Güran : Ben mutfaktaydım ama sesleri bana geliyordu.

Duruşma Savcısı : Sesleri sana geldi. Terlik istedi yani.

Yüksel Güran : Evet hatta ona dedim oğlum Dörtyol'a kadar gitse gelse geç kalır.

Duruşma Savcısı : Terlik istediğinden haberin var?

Yüksel Güran : Evet, sesim ben mutfaktayım görüyorum dedi kardeşim geldi.

Duruşma Savcısı : Bu kadar terlik kıtlığı mı vardı? Neden bu?

Yüksel Güran : Ya çocuk işte gelmiş, terliği yırtmış, kardeşine terlik istemiş.

Duruşma Savcısı : Yine işten gelen, garsonlukta çalışan bir çocuğa, dolmuşla eve gelen bir çocuğa kasabadan terlik aldıracaksınız.

Yüksel Güran : Söylüyorlar, bizi ihtiyacımız neyimiz varsa biz söylüyoruz.

Duruşma Savcısı : Şimdi saat 4 civarı bitecek bir kurs var değil mi? Kızının 4'e kadar kursu vardı. Saat olmuş 19:11. Yani hesaplamalarımıza 19:11 akşam ezanı. O bölgede olması lazım. Üç saat geçmiş aradan. Değil mi ortalama?

Yüksel Güran : Evet.

Duruşma Savcısı : Şimdi fark ettiğin an Maşallah'a sesleniyorsun, çabaya giriyorsun. E kurstan 4'te çıkan bir kız 3 saat geçmiş düştü mü, kaldı mı? Bir yerde acıktı mı? 3 saat boyunca hiç düşünmedin mi o kızı?

Yüksel Güran : Bana dedi Fatma Hatice'ye gideceğim.

Duruşma Savcısı : En azından bir Fatma Hatice dediğin Hediye'nin yok. Maşallah kızları.

Yüksel Güran : Evet.

Duruşma Savcısı : Maşallah bir seslenmek ya Narin orada mı? 3 saat olmuş.

Yüksel Güran : Bana dedi ki, bana dedi, anne bana izin ver ben olay çok olay.

Duruşma Savcısı : Tamam anladım aklına gelmedi mi?

Yüksel Güran : Akşam da kalacak.

Duruşma Savcısı : Tamam. Rahattın yani 3 saat.

Yüksel Güran : Binlerce ben o eve bırakmışım. Bir hastaneye gitseydim bir yasa gitsem nereye gitseydim Narin olarak akşama kadar oradaydı.

Duruşma Savcısı : Tamam. Sizin kapınızın zili var mı?

Yüksel Güran : Hayır zilimiz.

Duruşma Savcısı : İçeri giren nasıl giriyor? Tel mi var? Bir tel mi var?

Yüksel Güran : Evet tel çekiyor.

Duruşma Savcısı : Yani senin çocukların ve Narin teli çekip içeri giriyor mu? Hani kapıyı çalmasına gerek yok mu?

Yüksel Güran : Narin içeride. Ben avukatlara da söyledim, iteliyor açıyor ama dışarıda geldiği zaman açamıyor.

Duruşma Savcısı : Tamam. Anladım. O gün eve yani çocuklar eve nasıl giriyor genelde Narin? İterek mi?

Yüksel Güran : Yok kapıyı çalıyorlar. Dışarı çıksa açıyorlar. Ben sayın avukatlarıma da söyledim. Ama dışarıda zor açıyordu. Böyle sert ya zor açıyorlar.

Mahkeme Başkanı : Çekmeli mi şu şekilde iple çekiyorsunuz? Gücü yetmiyor yani?

Yüksel Güran : Gücü yetmiyor. Dışarıda içeride gittiği zaman iteliyorlar.

Mahkeme Başkanı : Anladım.

Yüksel Güran : Açıyordu ama dışarıda zor açıyordular.

Duruşma Savcısı : Anladım. Tamam. Tamam başkanım sağ olun.

Mahkeme Başkanı : Evet hakim hanım. Ha evet. Bu Hediye ikinci geldiğinde kapı açıktı demişsin. Kapı açık mıydı?

Yüksel Güran : Evet.

Mahkeme Başkanı : Ya şimdi evde klimalar çalışıyor.

Yüksel Güran : Açıkta değildi. Bence öndeydi. Ama bir baktım Hediye geldi.

Mahkeme Başkanı : Yani sen Hediye'ye kapıyı sen açmadın?

Yüksel Güran : Hayır.

Mahkeme Başkanı : O zaman, o zaman şeyi çekip de açmış olabilir mi?

Yüksel Güran : Ben diyorum önündeydi herhalde. Bence açıldı. Hediye de sorabilirsin. Yani bir baktım Hediye içeri geldi.

Mahkeme Başkanı : Tamam. Sen onu bilmiyorsun. Hediye soralım.

## Diyarbakır Barosu

### Av. Mehdi Özdemir

Av. Mehdi Özdemir : Yüksel Hanım Gazal Bahtiyar'ı tanır mısınız?

Yüksel Güran : Evet tanırım.

Av. Mehdi Özdemir : Olayın olduğu gün akşam saatlerinde.

Yüksel Güran : Evet.

Av. Mehdi Özdemir : Saat 16'dan sonra sizin için söylüyorum.

Yüksel Güran : Onlara dönebilirim.

Av. Mehdi Özdemir : Narinin kaybolduğunu anladığınız an.

Yüksel Güran : Evet.

Av. Mehdi Özdemir : Muhammed'e söylediniz. Muhammed gitti. Bulamadığını söyledi ve siz çıktınız.

Yüksel Güran : Evet.

Av. Mehdi Özdemir : Maşallahın Hediye'nin ve pek çok eve gittiniz. Baktınız.

Yüksel Güran : Telefonda evet.

Av. Mehdi Özdemir : O esnada Nevzat Bahtiyar'ın evine doğru giderken Gazal'la karşılaştınız mı?

Yüksel Güran : Hayır. Gazal cami yanına bizim yanımıza gelmiştir.

Av. Mehdi Özdemir : Peki.

Yüksel Güran : Ben Nevzat'ın evin etrafında geziyordum.

Av. Mehdi Özdemir : Tamam. Peki Gazal'la karşılaştığınızda o caminin bulunduğu kısımda Gazal'la bir konuşmanız oldu mu?

Yüksel Güran : Ben arıyorum Narin'i. Bağırarak, ağlayarak Narin'i arıyorum. O da arkamda beni teselli Ediyor. Yüksel dur, Narin'i bulacaksın. Bir yerde yatacak. Kendine gel. Öyle şeyler bana anlatıyordu.

Av. Mehdi Özdemir : Hanginiz kızımı götürdü şeklinde bir söyleminiz? Gazal'a da olabilir, başkalarına da olabilir. Böyle bir konuşma geçti mi? Hatırlıyor musunuz?

Yüksel Güran : Hayır ben hiç bunu hatırlamıyorum. Gazal'a dememiş ki Narin ortada oldu. Yok olduğu zaman biz Narin'i arıyoruz. Yani mutlaka ya bir çalındı ya bir şey olmuştu. Narin ortada yoktu. Biz Narin'i arıyoruz. O zaman aklıma gelmiyor ama dememiş kim çalmışsa kızımı getirsinler.

Av. Mehdi Özdemir : Peki o sıralarda kızımın bir mezarı olsun şeklinde?

Yüksel Güran : Kesinlikle.

Av. Mehdi Özdemir : Bir bağırışınız, bir söylemeniz, herhangi bir şey hayır?

Yüksel Güran : Kesinlikle ben bunu söylememişim.

Av. Mehdi Özdemir : Söylememişsin.

Yüksel Güran : Yemin ederim.

Av. Mehdi Özdemir : Olay günü Narin Kur'an kursuna gitmek için saat 1 sıralarında öğleden sonra 1 sıralarında size gitmek istediğini söyledi değil mi?

Yüksel Güran : Evet.

Av. Mehdi Özdemir : Peki siz başta itiraz ettiniz. Akabinde izin verdiniz. İzin verirken de Narin'in aslında saat 16 sıralarında yani 4 sıralarında kursunun biteceğini eve geleceğini biliyordunuz değil mi?

Yüksel Güran : Yok, dedi "Fatma, Hatice yanına gideceğim. Ana akşama kadar orada kalacağım."

Av. Mehdi Özdemir : Akşam kaça kadar kalacağını?

Yüksel Güran : Normalde çocuklar zaten akşama kadar 6-7'ye kadar biz zorla onları caddede ya orada orada köy çocukları oynuyor biz onları getiriyoruz. Biliyordum yemeğe kadar gelmiyordu.

Av. Mehdi Özdemir : Narin evden ayrıldıktan sonra yani saat 1.5 sıralarından sonra.

Yüksel Güran : Evet.

Av. Mehdi Özdemir : Akşam saat 4 sıralarına kadar. Hatta dört buçuğa kadar. Tümüyle evde miydiniz? Yoksa evden dışarı çıktınız?

Yüksel Güran : Hiçbir yere gitmemişiz.

Av. Mehdi Özdemir : Herhangi bir yere gitmediniz.

Yüksel Güran : Yok, yemin ederim, çocuklar da başka. Ben hiçbir yere gitmemiş. Enes gitmiş, Muhammed gitmiş. Ben hiçbir yere gitmemişim.

Av. Mehdi Özdemir : Evin etrafında Salim'i veya başka birisini gördünüz mu?

Yüksel Güran : Hayır.

Av. Mehdi Özdemir : Görmediniz.

Mahkeme Başkanı : Kayıt yapıyorsunuz değil mi? Gözlükte avukat hanım mıdır? Siz? Telefonlar yukarıya kalktığı zaman dikkat çekiyor da. Kayıt yok değil mi? Avukat mısınız? Sizler? Evet. Siz? Yok değil mi? Arkadaşlar lütfen istirham ediyorum. Video kaydı yok. Bakın video kaydı bizi de zor durumda bırakıyor. Ben anlıyorum sizi. Şurada video yapmak, kayıt atmak çok cazip. Twitter kullanmıyorum ben ama retweet alır. Yani güzel şeyler sizin için ama mahkemeye saygısızlık anlamına geliyor ve Türk Ceza Kanunu'na göre de bu suçtur. Anlatabildim? Yani böyle bir ithamla karşılaşmamak için rica ediyorum tamam? Çünkü telefonu şöyle tuttuğunuz an ben öyle algılıyorum. Kayıt yapabilirsiniz, haklısınız. Ben de dikkat edeyim ama sizden ricam dikkat edin. Buyurun avukat bey.

Av. Mehdi Özdemir : Gündüz olabilir, akşam olabilir. Yani Narin'in kaybolmadan önceki saat dilimleri de olabilir. Narin kaybolduktan sonra akşam saatleri de olabilir. Salim'i hiç gördünüz mü?

Yüksel Güran : Yemin ederim görmemişim. Hiç görmedim. Sadece ben diyorum ki, ha şarteli indirdiği zaman Hüseyin Güran'ın kapısında görmüş. Saniyede görmüşüm Yemin ederim ben görmemişim.

Av. Mehdi Özdemir : Gün içerisinde evde olduğunuz sırada telefon sürekli yanınızda mıdır?

Yüksel Güran : Telefon çocukların yanındadır.

Av. Mehdi Özdemir : Evden çıktıktan sonraki akşamda telefonu yanınıza alır mısınız?

Yüksel Güran : Ben?

Av. Mehdi Özdemir : Evet.

Yüksel Güran : Hayır, kesinlikle çocuklar evde olduğu zaman telefonu kullanmıyor. Çünkü çocuklar evde telefonla durduğu zaman ben nereye gitsem söylüyorum oğlum bak ben buradayım beni arıyorlar. Ben kesinlikle telefonu götürmüyorum.

Av. Mehdi Özdemir : Salim'in çocuklarının isimlerini söyleyebilir misiniz?

Yüksel Güran : Tabii. Dilek, Gamze, İlayda, Devran, Gülsüm, Miran.

Av. Mehdi Özdemir : O gün yani Narin'in kaybolduğu gün hiç bu çocukları gördünüz mü?

Yüksel Güran : Hayır, ben hiç onları görmedim.

Av. Mehdi Özdemir : Evin önünde, evin ahırda, avluda, bahçede, sokakta, Salim'in evinin önünde herhangi bir yerde?

Yüksel Güran : Hayır hiçbir saat akşam üstü onun çocukları karısı, çocukları onun karısı, kardeşi hepsi kapıdaydılar. Akşam üstü saat 5'ten sonra hepsi çocuklar dışarıdaydılar. Ama öyle ben hiç yemin ederim onları görmemişim. Evin etrafında da gitmemişim.

Av. Mehdi Özdemir : Olaydan sonra evin içerisindeki halı veya yolu ve benzeri şeyleri yıkadınız mı?

Yüksel Güran : Kesinlikle bunu yıkamamışız. Sabah elbisenin Enes'in, Enes'in elbiseleri Hediye'lere göndermişim.

### Av. Nahit Eren

Av. Nahit Eren : Bir anneye soru soracağım. Bu açıdan birkaç şey söyleyeceğim.

Mahkeme Başkanı : Yorum yapmadığınız takdirde evet.

Av. Nahit Eren : Yorum yapmayacağım. Aynı zamanda içerisinde soru da barındıracak bu değerlendirmeyi yaptığımda Narin dosyası ilk başladığı andan itibaren çünkü bir anneye soru soracağım. Ben bir anneye soru sormadan önce az evvel bahsedilen Diyarbakır Baro'sunun kurumsal kimliğinin böyle bir ağırlığı da var. Ben seni sorgulamayacağım. Birkaç soru soracağım. Bu bir sorgudur aslında. Ben bir anneyi sorgulamam ama niye sorgulamayacağımı söyleyeceğim size ve sadece soru soracağım. Bugün bu salondaki kalabalığı görüyorsunuz değil mi? Bir sürü insan gelmiş. Daha önce hiç duruşma, dava gördünüz mü?

Yüksel Güran : Hiç hayatımda, hayatımda ne karakol, ne böyle bir şey görmedim.

Mahkeme Başkanı : Ben görmedim, o nasıl görsün ya?

Av. Nahit Eren : Biz gördük de başkanım o yüzden anlatıyorum. Evet sizin de avukatlarınız var, savunma hakkına da hepimiz saygı duyuyoruz. Savunma hakkı da kutsaldır. Sizin avukatlar dışındaki avukatların insanların tamamı Türkiye'nin birçok yerinden yaklaşık başkanım tutanağı geçirmedi. Elliye yakın baro başkanı burada.

Mahkeme Başkanı : Yazdım yazdım. Sonradan devre arasında yazdım.

Av. Nahit Eren : Elliye yakın baro başkanım var. Türkiye'de kadın hakları, çocuk hakları alanında çalışan bütün kurumların temsilcileri burada. Milletvekilleri burada.

Yüksel Güran : Sağ olasın.

Av. Nahit Eren : Biz buradayız. Çok özel bir şey de söyleyeceğim. Çok özel. Aslında neyi anlatacağım sana? Hepimiz hepimiz Narin için buradayız.

Yüksel Güran : Hepimiz Narin için buradayız.

Av. Nahit Eren : Hiçbirimizin herhangi bir şekilde bu dosya üzerinden iddia edildiği gibi bir şey konuşmak, bir şey söylemek, bir yerlere çıkmak herkes bir şekilde rüştünü ispatlamış avukatlardır. Bizim Narin üzerinden, Narin'in dosyası üzerinden bu salonda kim kim nemalanıyorsa tırnak içerisinde o anlamda o anlamda bana göre Narin'i öldürenle aynı kategoridir.

Yüksel Güran : Allah hakkını Narin'i bırakmayacak.

Av. Nahit Eren : Bakın nereye bağlayacak?

Yüksel Güran : Bırakmayacak.

Av. Nahit Eren : Hepimiz katılmak istedik bu dosyaya. Herkes katılmak istedi. Narin için bir şey yapmak için. Yani savcı hanımın yanında durup savcı hanımla birlikte bu davadaki gerçek nedir açığa çıksın. Öldürenler ceza etsin diye hepimiz buradayız. Sana çok senin bir kızın iki kızın bir kızın öldü. İkinci kızın da öldürüldü. Öldürüldü. Öldürüldü. İkinci kızın da öldürüldü. İki kızın da öldürüldü.

Yüksel Güran : Beni de öldürmüşler.

Av. Nahit Eren : Allah çocukları da sana bağışlasın.

Yüksel Güran : Beni de öldürmüşler.

Av. Nahit Eren : Ben senin vicdanına seslendiğim için bu konuşmayı yaparım. Vicdanına sesleneceğim. Tabii. Bu dosyayı görüyor musun?

Yüksel Güran : Görüyorum.

Av. Nahit Eren : Şu kağıtları görüyor musun hepsini? Şu yazıların düzenini görüyor musun?

Yüksel Güran : Görüyorum.

Av. Nahit Eren : Kim yaptı biliyor musun bu dosyayı? Ben Narin'in otopsisine girdiğimden beri benim de üç tane kızım var. Üç kızım var. Şu etiketleri evdeki çocuklar Narin için yaptı. Narin'in dosyasına katkı için yaptılar. Şunların hepsi benim kızlarımın yazıları. Narin'in faili çıksın diye. Bir küçük katkımız olsun diye. Türkiye'de Türkiye'de Türkiye'de bugüne kadar bir çocuk bu kadar sahiplenilmedi. Belki eksiğimiz hatamız geçmişte buydu ki bugün Narin'i kaybettik. Daha önce bu değeri gösterebilmiş olsaydık bugün Narin'i kaybetmemiş olacaktık.

Mahkeme Başkanı : Avukat bey artık soruya geçelim.

Av. Nahit Eren : Soruya aslında sorumla da bağlantılı. Yani duygusuna, vicdanına sesleneceğim. Ben bu davanın çözümlerine aslında bir annenin vicdanı bu davayı sanık sanık soracağım.

Mahkeme Başkanı : Diyarbakır barosunun da işkenceden çok hassasiyet olduğunu bir önceki celsede tartıştık ya.

Av. Nahit Eren : Sayın Başkanım herkes Diyarbakır barosunu çok iyi biliyor. Hiç sorun değil. Hiç sorun değil. Şunu soracağım kendisine. Sadece dedim ya sorgulamayacağım. Hıh. 25.08'de müşteki olarak, müşteki nedir biliyor musun? Şu an benim durduğum yerde sen durmalısın. Sen olmalısın burada annesi olarak normalde.

Yüksel Güran : Ben biliyorum.

Av. Nahit Eren : Müşteki dediğimiz şey odur. Müşteki olarak seni çağırmışlar. 25'inde karakol seni çağırmış, ifadeni almış. Evet. Kızına ne oldu? Bize bir şey söyle, bulalım diye. Hıh. Ben bir cümle kullandım televizyonda. Bu bu bu meseleyle ilgili bir defa çıktım sonrasında. Dedim ki, bu dosyada aile bize yardımcı olmuyor cinayet dosyalarında anne bize bir şey söyler. Anne söyler, baba söyler, kardeş söyler, amca söyler, köylü söyler. Biz cinayeti çözeriz. Savcılıkta çözer. Şimdi sana gelmiş sormuşlar. Demişler ki, ya eşarp var sen demişsin merdivenin üstünde.

Yüksel Güran : Bu ne?

Av. Nahit Eren : Ben sorayım. Ben sorayım. Evet. Ben sorayım Yüksel Hanım. Dedi demişsin ki imama. Evet. "Narin'in öldüğü günün ertesi günü geldi merdivende buldum mor eşarbı. Dedi ki imam, bu eşarpla mı geldi Narin senin Kur'an kursuna camiye" pardon.

Yüksel Güran : Ben söyleyeyim.

Av. Nahit Eren : İmamı sana hatırlatmak için bunu söylüyorum. Sen de imam sana ne cevap verdiğini hatırlıyorsun.

Yüksel Güran : Evet.

Av. Nahit Eren : Evet dedi bu mor eşarp gibi bir eşarp başındaydı.

Yüksel Güran : Hayır. Bu eşarp.

Av. Nahit Eren : Hayır imamın ifade senin söylediğin ifade. Hatırlatabilirim. Bu eşarp nerede? Nerede bu eşarp?

Yüksel Güran : İkinci gün geldi bana.

Av. Nahit Eren : Şu an bu eşarp nerede?

Yüksel Güran : Eşarp dedi bu değil.

Av. Nahit Eren : Nasıl?

Yüksel Güran : İmam dedi buna benziyor ama ben emin değilim.

Av. Nahit Eren : Ben okuyayım.

Yüksel Güran : Hayır, eğer deseydi budur o zaman o eşarp jandarmaya teslim edecektim. Ben evdeydi.

Av. Nahit Eren : Tamam bana benzediğini söyledi diyorsun. Ben bir şey soracağım. O eşarp nerede? İmama gösterdiğin eşarp?

Yüksel Güran : Evdeydi.

Av. Nahit Eren : Şimdi nerede? Şu anda da evdedir herhalde.

Av. Nahit Eren : Hala duruyor mu?

Yüksel Güran : Evet.

Av. Nahit Eren : Sen nerede buldun?

Yüksel Güran : Biliyorsun. Ama o eşarp öğlen orada dedi. Çünkü ben akşam ötsüyü o balkonu yıkadım.

Av. Nahit Eren : Tabii nerede buldun diye soruyorum.

Av. Nahit Eren : Ben önce söyleyeyim. İmam bize geldi. Balkonda bir sürü insan vardı. Beni çağırdı. Dedi Yüksel ben camide ders veriyordum. Baktım Narin çocuklar pencerede bize bakıyordular. Dedi ben demişim burası sinema değil. Eğer ders alıyorsun gelin içeride ders alın. Sonra dedi bir baktım Narin geldi. Üstü başı bir etek, bir mor etek var, bir mor şal vardı. Dedi ben hatta dedim Mina senin kardeşsindir. Dedi yo Arif amcamın kızıydı. Dedi vallahi ben bilmiyordum Arif'in kızıydı. Gözleri Osman'a benziyor. Aynı imam bana böyle dedi. Sonra dedi ki çıktı dersini aldığı zaman, çıktı zaman dedi baktım eteği de çıkarttı, şalı da çıkarttı. Saçı ya açıktır. Mor eteği de çıkarttı zaman. Dedim hoca etek, mor eteği var doğrudur. Muhammed diyor evi çıktığı zaman besleme çantası vardır. Pembedir. O da Muhammed söylüyor jandarmaya söylüyor. Dedim hocam ben akşam bu balkonu yıkamıştım bir şey yoktur. Akşam ben ağlıyordum. Kadınları benim burada çünkü benim mor şalım yoktu daha. Yani böyle karıştırma varsa da bilmiyordum. Dedim ben akşam beni kadınlar beni oturduğu zaman böyle şişlerin arasında bu şalı gördüm. Budur hocam.

Av. Nahit Eren : Şişler dediğin?

Yüksel Güran : Balkon. Dışarıdaki. Evet dışarıda.

Av. Nahit Eren : Gördün onu.  Size ait değil mi? Yani senin eve ait değil mi?

Yüksel Güran : O benimdi.

Av. Nahit Eren : Bu gösterdiğin?


Yüksel Güran : Gösterdi dedi baktı dedi vallahi bilmiyorum ama tam emin değilim. Aynı ifademi de öyle söylemişsin. Eğer dediyseydi evet bu şal odur. O şalı hemen jandarmaya teslim edecektim. Bizim balkon.

Av. Nahit Eren : O şal hala evde?

Yüksel Güran : Evet şu anda böyle evdedir. Çünkü ben iki ay evde değilim. Şu an herhalde evdedir. Evdedir. Biliyordum.

Av. Nahit Eren : Ben dedim ya sorgulama değil bir şey daha çünkü ifadelerden gidiyorum. Hediye geldi size.

Yüksel Güran : Evet.

Av. Nahit Eren : Üçte gitti, kapattı açtı vanayı, evine gitti.

Yüksel Güran : Evet.

Av. Nahit Eren : Geldi bıraktı sizin evinize o elbiseleri gitti kendi evine dolduğunu gördü geri geldi 15:45'te geldim diyor. Geldiğinde Muhammed ne yapıyordu?

Yüksel Güran : Muhammed, bence Muhammed evdeydi.

Av. Nahit Eren : Yatıyor muydu?

Yüksel Güran : Yok Muhammed yatamıyor diyorsa.

Av. Nahit Eren : Muhammed'le Hediye şimdi aynı oda içindesiniz hepiniz değil mi? Muhammed Hediye'yi gördü mü? Sence?

Yüksel Güran : Muhammed bence Hediye geldi Muhammed oradaydı ama şu anda Muhammed'i ben evde değildim. Ama bildiğim gibi evdedir.

Av. Nahit Eren : Muhammed evdedir. Evde değilim demiyor. Evdedir. Gördü mü?

Yüksel Güran : Muhammed geldiyse Hediye geldiği zaman ben Hediye'ye dedim. Bak çocuklar diyor yenge Hediye gelmiş, elbiseyi bırakmış gitmiş. Dedim oğlum niye beni uyandırmadın? Dediği anne o bırakmadı. Ben tam anlatıyordum. Bir iki dakika geçmedi baktım Hediye oradaydı. Hediye bize geldi. Hediye geldiği zaman ben en iyisi Hediye'yi de öyle dedim. Ama Muhammed orada.

Av. Nahit Eren : Bunları anlatmışsın. Ben sadece senden şunu istiyorum. Muhammed evdeydi ve Hediye'yi bizle birlikte gördü mü?

Yüksel Güran : E vallahi bence Muhammed evdeydi. Gördü. Evet yani, diyorum Muhammed evdeydi. Tam aklım almıyor. Hani bana söylemişse sonra şey çıkmışsa bilmiyorum.

Mahkeme Başkanı : Bence diyor. Bence değil mi? Emin değilsiniz ama.

Yüksel Güran : Evet.

Av. Nahit Eren : Muhammed Enes'le birlikte çıktı mı evden?

Yüksel Güran : Yok, Enes hala yatıyordu.

Av. Nahit Eren : Sonra çıktılar ya. Enes çıktı ya. Enes uyandı. Enes uyandı.

Yüksel Güran : Enes yanlış söylüyor.

Av. Nahit Eren : Enes diyor ki, ben uyandım, Gördüm Hediye'yi. Sordum nasılsın? Sonra çıktım evden. O çıkarken Muhammed de ondan sonra çıktı mı?

Yüksel Güran : Muhammed önce çıkmıştı.

Av. Nahit Eren : Muhammed önce çıkmıştı.

Yüksel Güran : Bak ben burada dedim, Enes yanlış görmüş. Enes kalktığı zaman Muhammed orada değildi. Yatmıyordu. Enes uyku sersemi kalkmıştı. Ben de şu anda da ben size Enes yanlış söyledi. Enes kalktığı zaman Muhammed yatmıyordu.

Av. Nahit Eren : Muhammed'le Enes eve birlikte mi geldiler?

Yüksel Güran : Akşam?

Av. Nahit Eren : Evet.

Yüksel Güran : Enes bir kere daha geldi. Enes tekrar tepeye çıktığı zaman aşağıya geldiği zaman eve geldi. Tepeye arkadaşlar.

Av. Nahit Eren : Onu sormuyorum.

Yüksel Güran : Evet.

Av. Nahit Eren : Bize sen de dinledin. Enes diyor ki ben ilkinde gittim. Tahir markete gittim içecek aldım. Tamam. Geldim yolda araçtan oradan geçecektim. Süheyla yardım etmemek için ben eve yürüme gittim. Evet. Orada gelirken Muhammed yanında mıydı?

Yüksel Güran : Hayır Muhammed onun yanında değildi.

Av. Nahit Eren : Değil.

Yüksel Güran : Hiç aklım almıyor. Yani o zaman işe girmişti. Muhammed gelmiş gitmemiş. Siz daha Hediye'yleseniz. Hediye daha evde.

Mahkeme Başkanı : Yüksel Hanım, Yüksel Hanım mikrofon.

Av. Nahit Eren : Hediye daha evde.

Yüksel Güran : Enes geldi. Muhammed Enes geldiği zaman Muhammed ya Hediye gitti. İkinci.

Av. Nahit Eren : Gördüler birbirlerini ama.

Yüksel Güran : Enes de içeri geldiği zaman hala Hediye kapıdaydı.

Av. Nahit Eren : Hediye o gün sizin evinize son kez daha vicdanına sesleniyorum. Hediye o gün sizin evinize geldi mi hiç?

Yüksel Güran : Yemin ediyorum iki defa geldi.

Av. Nahit Eren : Yemin etmene gerek yok.

Yüksel Güran : Birinci geliyor. Ben yatıyorum. İkinci.

Av. Nahit Eren : Hediye o gün sizin evinize geldi.

Yüksel Güran : İki saatte de bizde kalmıştı.

Av. Nahit Eren : Saat üçten önce Hediye nerede olduğunu hiç sana söyledi mi? Hani sohbet ediyorsunuz ya sabah gittin teslim ettin eşyaları yıkasın diye saat 10 gibi.

Yüksel Güran : Hayır onu anlatmamış.

Av. Nahit Eren : Hiç o sohbet edince anlatmadınız.

Yüksel Güran : Hayır hiç anlatmamış.

Av. Nahit Eren : Mesela bir şey söyleyeyim. Abdurrahman'ı biliyorsun Hediye'nin oğlu.

Yüksel Güran : Evet.

Av. Nahit Eren : Yetişkindir, büyüktür.

Yüksel Güran : Evet.

Av. Nahit Eren : Mesela Hediye uyandığında diyor ki ben uyandığımda evde saat 1'di. Hediye evde yoktu. Ben en son Hediye'yi bir daha 5'te gördüm.

Yüksel Güran : Ben onu bilmiyorum.

Av. Nahit Eren : Yani seninle hiç Hediye o saate kadar nerede olduğuna dair bir sohbet yapmadı?

Yüksel Güran : Dedi Yüksel elbiseni getirmişim. Sen yatıyordun. Gidim dedim dinamoyu çalıştırayım. Depomu doldurduğu zaman geldim dinamoyu kapattım. Zaman dedim şu anda Yüksel kalkmış, onun yanına gideceğim. Başka eve hiçbir şey anlatmamış.

Av. Nahit Eren : Bize bu da bir de son bir şey benim kafamı da heyetin de kafasını çok karıştırmıştır. Şu kan meselesini de bir anlatabilir misin? Şey kanı. Ambulansa gitme kanı değil. Hindinin kanı meselesini ben anlatıyorum.

Yüksel Güran : Ben hiç onu bilmiyordum.

Av. Nahit Eren : Hindi hindi.

Yüksel Güran : Evet. Hindi. Hindi. Ben diyordum ya. Sabah 5'te kalktım.

Av. Nahit Eren : Bir gün önce mi oldu?

Yüksel Güran : Aynı o gece olmuştu.

Av. Nahit Eren : Şimdi bazı yerlerde diyorsun daha önceki günü olmuş. Şu merdivenlere giden kan için söylüyorum. Çünkü bir şey anlatayım sizin evinizden başkanım delili anlatayım. Sizin evinizden merdivenden bir kan örneği bulunuyor.

Yüksel Güran : Onu diyorsun, Tahir Kaya'nın kanıdır. Ben onu hiç bilmiyorum.

Av. Nahit Eren : Bir kan var, insan kanı var. Ama aradan geçen zaman DNA o kadar küçük ki DNA araştırmasına sen DNA yani kime ait olduğu tespiti yapılıyor. Ama bir insan kanı sizin o eklentideki merdivenden alınmış. Ben de o yüzden soruyorum. Sen bize bu hindinin meselesini hindiyle köpek meselesini bir anlatabilir misin? niye bu ifadelerine geçti? Niye hindinin kanından bahsediyoruz? Benim kafamda soru işareti var.

Yüksel Güran : İçeri gelmemişti. Sabah. Sabah hindinin kanı içeri gelmemiş. Sabah ben bamya topluyorum ya. 5'te. Kalktım kaç sıramız kaldı? Baktım ölü bir parçalı hindi karşımda çıktı. Ben kendim dedim vallahi köpek çünkü akşam hindimiz dışarıdadırlar. Dedim bu gece hindi köpeğimiz yemiş. Geldiği zaman biz akşam hindiyi ahıra koyduk. Ama evi kanı sonra ben duydum. Dedim Tahir Kaya. Dışarıda burnu kanıymış, kan içmiş. Kanıyı gördüğü zaman içeri gitmiş peçete istemiş. Ben de bunu milletten duydum. Hani olay günü vardı. İkinciydi, üçüncüydü ben hiç aklıma gelmiyordu. Sonra duydum dedi. Daha dışarıda bir sürü çocuklar da oradaydılar. Dedi burnu kanıymış.

Av. Nahit Eren : Kayalıklarda ki kandan bahsetmiyorum ha. Sen kayalıklardaki kandan bahsediyorsun. Ahırın yanındaki taşlardaki kan mı Tahir'in kanıydı?

Yüksel Güran : Evet o kanıydı.

Av. Nahit Eren : Kim söyledi bunu?

Yüksel Güran : Çocuklar söylüyordu. Sonra duydum ha.

Av. Nahit Eren : Çocuklar söyledi. Valinin açıklama yaptığı bir mesele vardı. O kan. Kim dedi Tahir'indir mesela?

Yüksel Güran : Bir sürü çocuklar oradaydılar. Ben sonra duydum.

Av. Nahit Eren : Ben bir şey söyleyeyim mi? Mesela o kanın kime ait olduğu insan kanı kime ait olduğu tespit edilemedi. Niye? Taştan geçen zamandan dolayı. Ama insan kanı. Ben de ben bu Tahir'in çünkü yeni bir kan değil. Ki çünkü bu dört dördüncü günde görüldü. Ben o yüzden soruyorum. Tahir'in kanının iddia edildiği taşlardaki kan değil. Merdivenlerde bulunan bir kan örneği var.

Yüksel Güran : Ha ben de sonra duymuşum. Bu kanı evet Tahir'in kanıyı da sonra duydum.

Av. Nahit Eren : Merdivendeki de mi sence Tahir'indir?

Yüksel Güran : Bakın bunu söylüyorum. Sonra az jandarma geldi. O kan man istiyor diyorlar. Söylüyorlar. Sonra dedim ne olmuş? Bu kanı ne kanı bahsediyorlar? Dedi ki çocuklar oradaydı. Dedi Tahir Kaya burnu kanamış taşı üstüne bayağı kan dökmüş. Sonra eline vurmuş, geldi içeri peçete istemiştir. Yemin ederim zaten hiç haberim o kanda yoktu. Hiç haberim bile yoktu o kandan ha. Sonra ben duydum.

Av. Nahit Eren : Evet.

Mahkeme Başkanı : Başka bir sorunuz var mı Nahit Bey?

Av. Nahit Eren : Teşekkür ediyorum başkanım.

Mahkeme Başkanı : Ben teşekkür ederim. Diyarbakır Baro'sunun sorusu var mı? Evet ondan sonra kapatacağız.

Av. Nahit Eren : Senin telefonunda internet var mı?

Yüksel Güran : Telefonun internet hattınız varsa internet zaten çocuklar bırakmıyorlar.

Av. Nahit Eren : Var mı? Internet hattı var mı telefonda senin?

Yüksel Güran : Evet, telefonun yani galiba internet varsa var yani.

Av. Nahit Eren : WhatsApp var yani.

Yüksel Güran : WhatsApp var.

Mahkeme Başkanı : Şey ya telefon ve terlik fotoğrafı geldi. Yok yani orada orada bir çelişki var da var var. Yok demiş. Var var. Onu ben gördüm de. O var olduğu sabit. Onu ben de gördüm. Ama terlik fotoğrafı var ve şey ya çok üstünde durmadım. Durmadık yani.

Av. Nahit Eren : Bir soru soracağım. Böyle yine senin bacıların içerisinde Narin'i en çok seven kim? Kardeşlerin?

Yüksel Güran : Evet. Herkes seviyor onu.

Av. Nahit Eren : En çok mesela. Bacıların bacıların?

Yüksel Güran : Bacılarım vallahi herkes Narin'i seviyordu. Çünkü bir kızım vardı, ailem hepsi onu seviyordu.

Av. Nahit Eren : Yasemin herkesten daha çok seviyordu diyebilir miyiz?

Yüksel Güran : Yasemin de seviyor. Herkes Narin'in üstünde çok titriyor. Çünkü bir kızım vardı bir özürlüydü kaybettim. İkinci oldu herkes seviyordu kızımı.

### Av. Asya Cemre Işık

Av. Asya Cemre Işık : Az önce soruldu, onun eksik kaldığı için devamını getirmek adına soruyorum. Mor yazma sizin yazmanız mıydı?

Yüksel Güran : Mor yazma bu benim değil.

Av. Asya Cemre Işık : Sizin kendi yazmanız değil mi? İmam geldi dedi ki, Narin mor bir yazmayla gelmişti. Siz o yazmayı nerede gördünüz? Merdivenlerde mi? Kapının önünde?

Yüksel Güran : Balkonun böyle şiş var ya. Ben onu görmedim. O da dedim. Dedim hocam bak gece ben bu mor şalı burada gördüm. Budur bu değildir. Baktı dedi vallahi tam emin değilim.

Av. Asya Cemre Işık : Tamam.

Yüksel Güran : Öyle bana dedi. Eğer deseydi evet Yüksel bu mor şalı ben hemen jandarmaya teslim edeceksin. Bakım imam diyor bu şaldır.

Av. Asya Cemre Işık : İmam size dedi ki bu yazma Narin'in başını örttüğü yazmaya benziyor.

Yüksel Güran : Benziyor ama.

Av. Asya Cemre Işık : Ve bu yazma da sizin yazmanız.

Yüksel Güran : Evet o benimdi.

Av. Asya Cemre Işık : Sizin yazmanızı Narin almadıysa başka da kız çocuğunuz yok sizin yazma takacak Siz de getirip koymadınız demirlere şişlere dışarıya. O yazma nasıl dışarıya geldi diye sorgulamadınız mı?

Yüksel Güran : Bak ben bu balkonu yıkadım. Zaten bir şey yoktur. Balkonu yıkamışım. Gece bu olay olduğu zaman ya olduğu zaman kim o balkonu sermişler? Vata yani şey minder getirmezsin. yastıkta bırakıyor. Millet oturuyor. Beni zorla hani biz Narin'i arıyoruz. Dışarı çıkıyor zorla. Beni kadında beni oturduğu zaman o mor yazma gözüme girdi. Sonra hiç yani aklıma gelmiyordu ya Narin götürmüş ya onu götürmüş ya onu götürmüş. İmam dedi mor yazma başındaydı. Ben hemen gittim. O mor yazmayı getirdim. Dedim hocam budur dedi. Yuva baktı. Vallahi ben tam emin değilim. Eğer deseydi evet Yüksel vallahi bu mor yazmaydı, ben hemen o moru yazmayı jandarmaya teslim edecektim.

Av. Asya Cemre Işık : Tamam imamın şöyle Yüksel hanım şöyle imamın o yazmayı doğrudan teşhis edememesi normal. Ama bu sizin yazmanız sizin evinizin içindeydi ve siz müdahale etmediğiniz halde bu yazma kapının dışarısında bulunuyor. Bu yazmayı Narin'in çıkarma ihtimalini düşünüp de neden jandarmaya bu bilgiyi vermediniz? Sonuçta bu evde iki tane cinsiyeti kadın olan ve yazma kullanabilecek iki insan var. Biri sizsiniz biri de Narin.

Yüksel Güran : Ben de söylemiştim. O zaman binlerce ifade vermişim. Dedim eğer imam deseydi evet bu mordur. Ben diyecektim kim getirmişse gece bu şalı getirmişti. O gece getirmişti.

Av. Asya Cemre Işık : Ben size başka bir şey soruyorum. İmam bu mor yazmayı benzetti ve siz de o mor yazmayı dışarıya koymadınız. Ve bunun Narinin çıkarmış olduğunu düşünemediniz mi? Neden bunu vermediniz?

Yüksel Güran : İmam dedi mor bir etek var mor bir şal var. Dedim hoca eğer mor şal var dedim bu değildi. Bunu gece ben burada görmüşüm. Dedi vallahi ben emin değilim. Eğer deseydi evet bu şal buydu. Ben hemen o şalı jandarmaya teslim edecektim. Biz sonra evin içini aradık aradık aradık binlerce ifade vermişim. Ne o besleme çantayı biz gördük. Ne o mor eteği de gördük. Biz bunu binlerce de ifade vermişim. Evet başka soru yok.

Mahkeme Başkanı : Arif Güran vekili sormak istediğiniz bir husus var mıdır? Yok.

## Aile ve Sosyal Hiz. Bakanlığı

### Av. Elif Aslı Şahin Torun

Av. Elif Aslı Şahin Torun : 25 Ağustos tarihli bir ifadeniz var. Şimdi burada akşam ezanı vakti Muhammed'e sordum. "Anne Narin yok" dedi. Maşallah Güran'ı yanıma çağırdım. Saat 5 gibi bizim evdeydi demiş Maşallah Güran.

Yüksel Güran : İfadeleri sonra...

Av. Elif Aslı Şahin Torun : Bir saniye ben bitireyim. Sonra camiye gitmişsiniz. İsa Kaya yanınıza gelmiş. Demiş ki abla Narin'i saat 6 gibi cami önünde gördüm. Bu saatlerde Narin çoktan katledildi dere kenarına bırakıldı. Siz bir anne olarak bu insanlara sormadınız mı? Yani neden bana böyle beyanda bulundunuz diye?

Yüksel Güran : Akşam İbrahim Güran jandarmalar yanıma bunu bırakmadılar. Ben tam olarak bu ifadeleri için. Dedi yüksel yenge bak diyor ki Şeyma 04:00-04:30'da görmüş.

Av. Elif Aslı Şahin Torun : 04:30 ama saat 5'de evdeydi demiş Maşşallah.

Yüksel Güran : O 5 Maşşallah'dır. Şeyma, Şeyma Kaya. Sonra İsa Kaya da zaten kendi ağzına bana dedi.

Av. Elif Aslı Şahin Torun : Saat 6'da gördüğünü söyledi.

Yüksel Güran : Sonra dedi Maşşallah Güran. Dedi ben saat 05:00-05:30'da ütü yapıyorum. Telefonla konuşuyorum. Kapımız çaldı. Dedim birisi kapıyı açtı. Dedim kızım kimdir? Dedi Narin de kızlara sormuş. Ben dedim anneannesine gitmiştir. Sonra Hülya Komutan bana karakolda dedi. Yüksel Maide Kaya. Kamerada gözüküyor. Tepeye bakıyor. Dedim Maide sen kiminle konuşuyorsun? Dedi ben Narin'le konuşuyorum. Dedim Narin gel aşağıda oynayalım. Narin dedi Maide ben yorulmuşum. Uykum geliyor. Açım eve gidiyorum. Narin nerede? Narin nerede? Narin saat 7'de gelmiş sende. Enes burada. Narin nerede? Üstüme geliyordu. Sonra Hülya Komutan evimize geldi. Beni çağırdı. O batıya aşağıya kalezyon vardır. Bir görümcemin oğlum oradaydı. Çocuğa dedi git orada eve kadar git. Dedi bak Yüksel. 3 santim tutmuyor. Narin nerede? Enes burada. Narin nerede? Üstüme yüklüyor. Dedim Komutanım saat 7'de sen söylüyorsun. Hüseyin Güran'ın kapısında bir sürü insan var. Süveyla Okulun yanına saman dolduruyor. Enes Güran arkadaşları burada. Bir sürü kadınlar, erkekler, çocuklar Enes'in arkasındadır. Muhtarın kapısında bir sürü çocuklar, karısı, abla, kardeşi hepsi orada. Narin saat 7'den nereye gidiyorsun? Beni ifade alıyorlar, sorguluyorlar. Çocuklar yalan söylemiyorlar.

Av. Elif Aslı Şahin Torun : Yani sonuç itibariyle Maşallah Güran size saat 5'te, İhsan Kaya'da 6'da gördüğünü söyledi mi?

Yüksel Güran : Maşallah jandarmaya söyledi. İbrahim Güran geldi bana söyledi. Jandarma bana söyledi.

Av. Elif Aslı Şahin Torun : Yanıma çağırdım demişsiniz, yanıma çağırdım. 5 gibi bizim eve gelmiş.

Yüksel Güran : Maşallah sonra bize geldi söyledi. Önce zaten ifade vermişti. Sonra bize geldi.

Av. Elif Aslı Şahin Torun : Bu saatlerde artık Narin yaşamıyor. Bunu sorgulamadınız mı peki?

Yüksel Güran : Sorguluyordu. Önce jandarma bizim üstümü yüklüyordu. Saat 7'de olmuş, saat 7'de olmuş. Narin nerede, Narin nerede? Sonra dedi ahırda olmuş.

Av. Elif Aslı Şahin Torun : Bu kişilere sormadınız yani neden yalan söylediklerini?

Yüksel Güran : Ben ki gitmemişim. Benim halim yoktu. Başkasına gitse, ben Maşallah dedim. Maşallah dedim, benim kanıtım vardır. Telefonla konuşuyorum, işte kanıtımız oradadır. Diğerleri hiç görmedim. Sonra dedi ahırda olmuş, ahırda olmuş. Bizim üstümüzü yüklüyorlar. Hep üstümüze atıyorlar. Bu olay ahırda olmuş, ahırda olmuş. Hani Narin nerede? Sonra bu çıktığı zaman evi içine attılar. Tekrar üstümüze geliyorlar. Evi içinde olmuş, evi içinde olmuş. Ne kıra gidiyor, nereye koşuyor, evimizi üstümüze atıyorlar.

Av. Elif Aslı Şahin Torun : Peki İsa Kaya neden böyle bir şey söylesin?

Yüksel Güran : Bilmiyorum. Ben bağırarak, çağırarak kapıyı, pencereyi, caminin kapısını vuruyorum. Narin nerede? Gelin caminin kapısını açın. Ben diyorum, cami inşaattır. Belki Narin bir yere düşmüştü. Baktım yanımda dedi, Yüksel abla, Narin 6'da buradadır. Hülya Komutan, biz kanıtlı gelmişiz, saatte bakmışız. Saat 5'e ne kadar MOBESE kamera çıkıyor, İsa Kaya köye giriyor. Sonra dedi, bu şahitler yalan. Hepsi siz tutmuşsunuz. Muhtar tutmuş. Yani bize, üstümüze bizi başka bir yere göndermişler. Dedi 7'de olmuş. Hep üstümüze atıyorlar. Önce çocuklar yalan söylemiyor. Olay 7'de olmuş. Sonra dedi ahırda olmuş. Sizin yüzünüzden kötü şey söylemiyorum. Bu çıkmış evi içine atıyorlar. Nereye atıyorlar? Benim üstüme, benim çocuğumun üstüne atıyorlar. Yemin ederim biz Narin'i görmemişiz. Yemin ederim Narin'i tırnağını dünyaya veremiyorum.

Av. Elif Aslı Şahin Torun : Teşekkür ederim.

Mahkeme Başkanı : Ben teşekkür ederim. Var mı soru?

### Av. Abdullah Yılmaz

Av. Abdullah Yılmaz : Siz Narin kaybolduktan sonra ne zaman eşinize haber verdiniz? Arif Güran'a ne zaman haber verdiniz?

Yüksel Güran : Ben haber vermedim. Çünkü biliyorum yoldadır, bak bana geliyor. Desem Narin kayboldu, adam kafayı yiyecek. Ben aramadım. Çünkü herkes beni teselli ediyor. Ya burada düşmüş, ya belki buradadır, ya belki buradadır. Ben onu aramadım. Sonra o beni aradı. Kim söylemişse bilmiyorum. Ama bildiğim gibi bence Cevat Kaya diye Arif siz Narin'i bulmuşsunuz. Sonra öyle duydum.

Av. Abdullah Yılmaz : Bir de şimdi Arif Güran'ın da Salim Güran'ın da Nevzat ile aralarında bir sorun olmadığını, bir husumetin olmadığını söylüyor. Siz Nevzat'la bir husumet seziyor muydunuz yani? Biliyor muydunuz böyle bir şey?

Yüksel Güran : Hiç bizim, benim hiç.

Av. Abdullah Yılmaz : E niye o zaman kızı mesela öldürsün, siz de diyorsunuz o öldürmüştür diyorsunuz. Enes aynısını söylüyor, oğlunuz.

Yüksel Güran : Ben demiyorum, kimseye hiç savurmuyorum Sayın Avukatım.

Av. Abdullah Yılmaz : Niye öldürsün mesela Yüksel Hanım? Mesela Nevzat niye öldürsün? Amca diyor ki, aramız iyi diyor, bizim aile dostumuz. Baba diyor ki, bizim bir husumetimiz yok, kendi beyanları bu arada, benim beyanlarım değil. Böyle bir şey niye yaşansın mesela?

Yüksel Güran : Kızım birkaç gün olaydan önce, geldi elinde böyle 20 milyon para vardı. Dedi anne bak param vardı, ben biliyordum ben 20 milyon vermeyeceğim. Dedim kızım bu para kim sana verdi? Nevzat abi bana verdi. Ben hatanı sonra hakimin yanına da, sayın hakimin yanına da söylettim. Ben savcı yanına bilmiyordum. Sonra Nevzat ortaya çıktığı zaman nezarete girdi mi aklıma geldi. Dedim o kızım günahtır, ayıptır niye alıyorsun? Bana da Süleyha'ya para vermişti. Sonra bilmiyorum. Yani şu anda adam çıkıyor, burada almış, burada almış. Bak ben önce de söylüyorum. Önce Salim'in arabada dedi DNA'sı vardır, öyle dediler. Yol kenarında bana vermiş, öyle şeyler. Ben bir anneyi yüreği sanki kafama girdi. Allah'ım bu adam delirmiş, kızımı öldürmüş. Sonra ifade değiştiriyor, evin içinde ben diyorum yalan konuşuyor. Bak eğer deseydi caddede, DNA'sı arabasına da çıkmıştı. O caddede beni tehdit etmiş, bana vermiş, böyle şeyler söylerdi. Belki bir anneyi yüreği kafama giderdi. Belki bu yapmış. Ama sonra evi içinde yemin eden bu şerefsiz evimize gelmemiş.

Mahkeme Başkanı : Tamam, tamam.

Av. Abdullah Yılmaz : Son soru başkanım. Teyzesi Yasemin Hanım'ın, Yasemin Gül. Orada Narin'in cansız bedenini çıkartıldığında ailede bir kavga oluyor kadınlar arasında. Hatta size dönüyor.

Yüksel Güran : Ben şey içindeydim. Ambulans geldi, Hülya Komutan dedi başım sağ olsun. Ben zaten biliyorum Narin'i kaybetmişim. Ben kendime değildim, bayılmışım, nedir bilmiyorum. Bir baktım ben ambulansın içindeydim, kendime geldim. Dedim komutanım beni bırak, çocuklarımın yanına gideceğim. Bir baktım sesler geliyordu. Kadınları görmüyordum. Arka ambulansın kapısı, erkekleri jandarma görüyordum. Dedim beni çıkartın, komutan bırakmadı, ben çıkayım.

Av. Abdullah Yılmaz : Diyor ki, bak doğruyu söyleseydiniz böyle olmazdı diyor. Diğerleri biraz...

Yüksel Güran : Bilmiyorum. Kim kavgaydı hiç bilmiyorum.

Av. Abdullah Yılmaz : Ama sonra hiç konuşmadınız mı kardeşinizle?

Yüksel Güran : Hiç bilmiyorum. Sayın hakimin yanına da bana dedi. Senin Maşallah kardeşin kavgayı biliyorsun. Dedim vallahi ben bilmiyorum. Beş gün nezarete kaldım. Melike, Maşallah görüyordum kardeşimin adını söylüyordu. Ama kavganın ne yapmış ne...

Av. Abdullah Yılmaz : Ondan sonra hiç konuşmadınız bu kavga hakkında?

Yüksel Güran : Hayır. Ne ben sordum ne onlar bana sordular.

Mahkeme Başkanı : Yüksel Hanım bu parayı gördüm dediniz ya.

Yüksel Güran : Evet.

Mahkeme Başkanı : Bunu eşinize, çocuklarınıza Enes ben böyle bir şey bilmiyorum dedi. Bunu birilerine söylediniz mi Nevzat para veriyor diye?

Yüksel Güran : Yok söylemedim, bilmiyordum ki. Normal kızı...

Mahkeme Başkanı : Şüphelenmediniz yani?

Yüksel Güran : Normal vermiş, kesin Narin orada da Narin'e de vermiş.

Mahkeme Başkanı : Daha önce verir miydi böyle?

Yüksel Güran : Bilmiyordum.

Mahkeme Başkanı : Bilmiyorsun.

Yüksel Güran : O gün bana söylemiş.

Mahkeme Başkanı : Tamam. Sanıklar müdafinden soru var mı? Buyurun. Öne alalım sizi.

## Sanık Salim Güran Müdafi

### Av. Onur Akdağ

Av. Onur Akdağ : Yüksel Hanım. Narin Salim'in aracına hiç bindi mi daha önce?

Yüksel Güran : 14 Temmuz'da binmişti.

Av. Onur Akdağ : Ne için bindi?

Yüksel Güran : Berat'ın nişanıydı. Arif evde değildi, bizim arabamız yoktu. Yerimiz yoktu. Narin, Eren o arabaya bindik. Zaten Salim o zaman arabası vardı. Devran kullanıyordu. Hediye, çocuklar hepsi o arabayla gittiler. Benle Muhammed, Memduh Güran'ın arabasına gittiler. Geliş gidiş o arabayla geldi.

Av. Onur Akdağ : Yani Narin Salim'in aracına bindi değil mi?

Yüksel Güran : Evet, o araba içine gittiler.

Av. Onur Akdağ : Evet. Olaydan önce siz kendi aracınıza Narin'le birlikte hiç bindiniz mi?

Yüksel Güran : Arabamız.

Av. Onur Akdağ : Arif'in aracına?

Yüksel Güran : Evet.

Av. Onur Akdağ : Arif sizi olaydan bir gün önce, iki gün önce hiçbir yere götürdü mü? Yani Narin o araca bindi mi?

Yüksel Güran : Evet, biz bir gün önce de Diyarbakır'a misafirliğe yemeğe gittik. Her yere nereye gitseydi, arabamızla gidiyorduk.

Av. Onur Akdağ : Evet. Nevzat, senin hiç evine geldi mi? Yani kapından dışarı girdi mi daha önce? Olay gününü söylemiyorum, olay gününü kastetmiyorum. Nevzat, sizin evinize hiç gelir miydi misafiriniz?

Yüksel Güran : Nevzat'ı bizim evimize hiç görmedim. Kuyuları birkaç ay önce vardı, sürekli evimizin etrafındaydı. Kuyuları bittiği zaman sürekli geliyor, tepede oturuyorduk. Ben daha önce Nevzat'ı görmemiştim.

Av. Onur Akdağ : Yani Nevzat sizin evinize hiç gelemez miydi?

Yüksel Güran : Hayır, hiç gelmiyordu. Hiç hatırlamıyorum.

Av. Onur Akdağ : Gazal Bahtiyar, Gazal Bahtiyar hiç misafirliğe geliyordu.

Yüksel Güran : Gazal geliyordu. Allah bin belası versin, zaten suları yoktu, her gün bize geliyor su alıyordu. Gazal geliyordu bize. Bu da bizim iyiliğimizdir, sayın avukatım. Bu da bizim iyiliğimizdir, susuz kalıyordu. O da bizim iyiliğimizi Nevzat başımıza getirdi.

Mahkeme Başkanı : Ama şimdi şöyle bir şey var, Yüksel Hanım. Bakın, ciddi bir husumet yok. Biz burada, ben belki yüz, belki bin mübalağa olur ama yüzlerce cinayet dosyasına karar verdim. Baktım, okudum. Yani taraflar arasında bizim soracağımız bir husumetten bahsederiz. Bir husumet. Şimdi siz bir husumet yok diyorsunuz, bir de iyilik yaptık diyorsunuz, su verdik diyorsunuz. Husumet yok, iyilik yapmışken. O zaman şöyle mi, yani Nevzat kötü bir şey yapıyordu. Biz hani sizin cinsel ilişkiniz var mı dedik, Enes'in cinsel ilişkisi var mı dedik. Nevzat'ın, özür dilerek soruyorum, şimdi özür diledim, haberlere düşmüşüm, kötü olmuşuz da. Özür dileyerek soruyorum, Nevzat'ın diğer 3'ünüzde bir ilişkisi vardı, onu gördü de mi öldürdü?

Yüksel Güran : Sadece bunu söylüyorum, avukatlarım da söyledi. Nevzat'ın karısı, hatta komutan bana dedi, Nevzat size gelmişti, yani Gazal. Dedim, yok bize gelmez dedi, önce size gelmişti. Dedim, e vallahi doğru, Gazal bize geldi. Kaç gün önceydi, bir aydı, bir ne kadardı bilmiyorum. Gazal bak, ben kapıdaydım, baktım Gazal Belkıs'ın yanına geliyordu. O da Belkıs'a amca kızıydılar. O olay Karakoç olayındaydı. Dedim, Gazal gel içeri gidelim. Gazal bize geldi.

Mahkeme Başkanı : Birazcık sessiz, bir uğultuyu kesebilir miyiz?

Yüksel Güran : Gazal bize geldi. Belkıs'a gile gittim, ben de Yeni Salihagil'den geliyorum. Dedim, durumu nasıldı? Biraz böyle konuştuk. Sonra ben Gazal'a geldim. Dedim, Gazal, Hatiye Zeyno hiç bizimle konuşmuyor. Ben ona selam veriyorum. Hatiye Zeyno nasıl, iyisin, bana da konuşmuyor. Niye? Baktım, Gazal güldü. Dedi, sen boş ver ona. Dedim, vallahi bilmiyorum. Öyle aklıma geldi. Bu araba için Hatiye Zeyno bize konuşmuyordu. Dedi, sen ona hiç bakma. Dedim, vallahi gerçekten Gazal, ben bu olayı hiç bilmiyordum. Bir gün baktım, Arif dedi, ben bugün Muhtargil'e gideceğim. Ben Gazal'a anlattım. Ben dedim, hayır. Nevzat önce araba aldı, çalıntı çıktı. Biz gidip oraya konuşacağız. Arif geldi. Dedim, ne oldu? Dedi, vallahi ben dedim, biz toplantı yapacağız. Ani ne ben ne o. Başka yabancı getireceğiz. O zaman Cevat Kaya getirdi. Rukedin Kaya getirmişti. Onlar ne desem, onlar gibi yapacağım. Dedi, baktım, Gazal dedi. Yüksel, vallahi ne Cevat Kaya ne Rukedin Kaya, hepsi Salim'in tarafını tutmuşlar. Bu para Nevzat'ın boyuna atmışlar. Dedim, vallahi öyle bir şey bilmiyorum. Dedi, vallahi Yüksel bana öyle dedi. Kesinlikle Ferhat bu parayı vermiyordu. Dedi, ben kendimi de öldürsem, başkasını da öldürsem bu parayı vermeyeceğim. İbrahim dedi, İbrahim de onun oğluydu. Dedi, ayıptır. Siz vermezsen, Salim vermezsen, Arif nereden getirecek? Ayıptır. Bu yük bir para değildir. Sonra dedim, ben ona dedim. Dedim, vallahi ben baktım, tepede Arif, Nevzat konuşuyor. Ben onları yanına dedim. Nevzat, hoş geldin. Bu parayı konuştu, konuşuyordu. Dedi, Arif ona diyor ki, vallahi ben avukata vereceğim. Avukat zaten avukata vermez. Bu parayı, eğer avukat halletse, sana paranı tekrar geri vereceğiz. O da dedi, bir şey olmaz. Ben de, hatta Nevzat işte burada. Dedim, ayıptır. Biz kaç sene biz komşuyuz. Büyük bir para değildir. Arasında bu parayı verin. Bizim aramızda çocuklarımız, hepsi arkadaştılar. Sonra ben ona dedim, evine hayırlı olsun. Sen ne yaptın? Mutfakla konuştu. O kalktı, evine gitti. Hiç bu araba aklımıza gelmiyordu. Hiç bizim evimizde, bu olayda hiç kocamla, çocuklarıma, hiç kimseye demedim. Ferhat böyle söylemiş. Onlar kafana koymuşlar. Ama bizim tarafımızda bir şey yoktu. Bir şey yoktu. Eğer olsaydı biz önce söyleyecektik. Bizim bu olay olmuş. Ne güzel belki. Hiç aklımıza böyle bir şey gelmiyordu.

Mahkeme Başkanı : Peki, Nevzat'ın olay günü biriyle cinsel ilişkiye girdiğini duydunuz mu? Öyle bir dedikodu duydunuz mu köyde?

Yüksel Güran : Kimden?

Mahkeme Başkanı : Şimdi ne bilelim. Sizin Salim'le ilişkiniz olduğu iddia ediliyor ya. Belki Nevzat bir dili akılda ilişkiye giriyordu. Narin gördü. Narin görünce Nevzat öldürdü.

Yüksel Güran : Kim niye söylemiş? Allah bin belasını versin. Yemin ederim.

Mahkeme Başkanı : Nevzat'ın biriyle ilişkiye girdiğini duydunuz mu?

Yüksel Güran : Hayır. Hayır duymamış.

Mahkeme Başkanı : Bunu ben söylüyorum. Bana beddua etme. Dur ya. Bana niye beddua ediyorsun?

Yüksel Güran : Ben bunu bilmiyorum.

Mahkeme Başkanı : Böyle bir şey var mı? Böyle bir şey duydun mu?

Yüksel Güran : Hayır.

Mahkeme Başkanı : Hemen beddua ettin sen de.

Yüksel Güran : O kadar istiyorum ki şu anda. Tamam tamam. Parça parça edeyim ya. Bak ben burada şimdi de söylüyorum. Hiç Allah'tan korkmuyor. Senin de çocuklarını Allah'a havale ediyorum.

Mahkeme Başkanı : Evet ya şimdi bak. Sen parça parça edeceğim dedin. Doğru mu? Nevzat diyor ki, eğer ben öldürsem beni parça parça ederler. Onun da o minvalde bir sözü var. Onun için seni burada duydum. Dur bak sen de parça parça edeceğim dedin. Zaten o aklıma geldi ya. Tamam. Tamam ben ona onu demiyorum. Arif de parça parça eder. Belki Enes belki sen Eren'e kadar daha önce de söyledim. Yani bu kadar parça parça etme ihtimali varken. Nevzat bu cesedi alıp saklamışken ondan sonra 19 gün 20 gün ya da 21 gün rakamların çok bir önemi yok. Köyde duruyor. Gözünüzün önünde. Doğru mu?

Yüksel Güran : Biz bilmiyoruz.

Mahkeme Başkanı : Ama bir yerde öğreneceksiniz. Nevzat bunu öğrendiğinde. Tüm Türkiye bir olmuş aramış. Nevzat şunu bunu parçalayacak adam bunu öldüren adam bunun planını yapan adam ya bu ortaya çıkınca bu aile beni öldürür deyip tüm ailesiyle birlikte kaçmayı akıl edememiş mi?

Yüksel Güran : Akıl etseydi yapmazdı.

Mahkeme Başkanı : Neyi yapmazdı?

Yüksel Güran : Suç ortağı o yapmazdı.

Mahkeme Başkanı : O ben yaptım demiyor ama. Ben yaptım demiyor ama. Öldürdüler bana verdiler ben götürdüm gömdüm şey yere yattım diyor. Ben yaptım demiyor.

Yüksel Güran : Biz onu diyoruz. Biz onun gibi yapmıyoruz.

Mahkeme Başkanı : Tamam da şimdi bak şimdi şöyle. Nevzat da ben yaptım demiyor ki. Nevzat diyor ki, ben geldim ben cesedi bana verdiler. Ben cesedi aldım götürdüm gömdüm diyor. O yüzden de oraya kaçmadım diyor. Ben yapmadım diye kaçmadım diyor. Nereden anladın yalan söylediğini?

Yüksel Güran : Herkes biliyor, yalan söylüyor.

Mahkeme Başkanı : Neden? Nereden biliyor herkes yalan söylediğini?

Yüksel Güran : E çünkü evimize çıkartmamış. Bak ben burada diyorum başka bir yerde olsaydı.

Mahkeme Başkanı : Evinize gelmedi.

Yüksel Güran : Evimize yemin ederim yemin ederim. İkisi de gelmemiş.

Av. Onur Akdağ : Salim'in son zamanlarda kullandığı araç kime ait?

Yüksel Güran : Onunki vardı. Kaza ettiği zaman kaç gün Metin Kaya'nın arabasını kapıda görüyordum. Ben hatta dedim belki kendine araba almış. Çocuklar dedi yok Metin Kaya'nın arabasıydı. Onun eniştesidir. Sonra Metin Kaya'nın arabası ortadan kaybolduğu zaman kardeşinin arabasını kullanıyordu.

Av. Onur Akdağ : Kardeşinin ismi ne?

Yüksel Güran : Fuat.

Av. Onur Akdağ : Fuat. O aracı Salim'in evinde evinin civarlarında kapısının önünde ya da başka bir yerde o gün hiç gördün mü?

Yüksel Güran : Hayır, kesinlikle görmemişim o gün.

Av. Onur Akdağ : Yani hareket halindeyken hiç evinin önünde park ederken görmedin?

Yüksel Güran : Hayır, yemin ederim o gün saniyede onu Hüseyin Güran'ın kapısında görmüşüm. Ne onu ne çocukları görmemişim. Akşama kadar onun kapısına girmişim çocukları görmüşüm.

Av. Onur Akdağ : Narin en çok Salim'in hangi çocuklarıyla oynardı?

Yüksel Güran : İlayda, Yusuf'la oynuyordu. Genelde de İlayda oynuyor. Benim çocuklarım aslında Narin fazla kimse oynamıyor. Ya Fatma Hatice'lere gidiyordu. Küçükler sürekli onlara teslim ediyordum. Ya da Hediye Güran'la gidiyordu.

Av. Onur Akdağ : Salim'in evinin önünde hiç çocuklar oynar mıydı?

Yüksel Güran : Orada olsaydı oynardı ama bu ikisi orta olsaydı Narin fazla onlarla oynamıyordu. Sürekli ben bir yere gitseydim ya Hediye'lere gidiyordu ya da Hüseyin Güran'lara gidiyordu. Onlar çocuklarla oynuyordu.

Av. Onur Akdağ : Şimdi diyorsunuz ki kim suçluysa ortaya çıksın.

Yüksel Güran : Evet bunu istiyorum. Katil istiyorum.

Av. Onur Akdağ : Nevzat sizin hakkında iftira atıyor?

Yüksel Güran : Evet.

Av. Onur Akdağ : Diyor ki, ağlarken gördüm. Aynı iftirayı Salim hakkında atmış olamaz mı?

Yüksel Güran : Ben onu bilemem.

Av. Onur Akdağ : Yani sizi ağlarken gördüğünü söyleyen kişi Salim'in de bu işi yaptığını söyleyemez mi?

Yüksel Güran : Bilmiyorum onu Allah'a havale ediyorum.

Av. Onur Akdağ : Ama sizin hakkınızda diyorsunuz ki iftira atmış.

Yüksel Güran : Tabii.

Av. Onur Akdağ : Aynı olayı anlatıyor.

Yüksel Güran : O bana itiraf atıyor.

Av. Onur Akdağ : Salim'i koyuyor hem Yüksel'i koyuyor.

Yüksel Güran : Evet ikimizde itiraf atıyor çünkü öyle bir şey yok. Yemin ederim öyle bir şey yok.

Av. Onur Akdağ : İftira atıyor öyle mi?

Yüksel Güran : İtiraf atıyor bana.

Mahkeme Başkanı : Var mı başka sorunuz Avukat Bey?

Av. Onur Akdağ : Yok efendim teşekkür ederim.

Mahkeme Başkanı : Yüksel Hanım oturabilirsiniz sağ olun.

Yüksel Güran : Ama burada katil istiyorum.

Mahkeme Başkanı : Hepimiz istiyoruz.

Yüksel Güran : Narin'in katilini gerçi istiyorum Narin'in katilini çıkartın bana.

Mahkeme Başkanı : Bir dakika bekler misiniz? Bir sorumuz var. Şimdi şunu tekrar sorayım. Şimdi sizin evde olduğunuzu biliyoruz. Narin'in de en son 15:11'de okulun kamerasında gözüktüğünü biliyoruz. Orada bir artı 4 dakika oynama var ama 15:11. Okulla da sizin evinin arası yaklaşık 5 dakika olduğunu varsayıyoruz. Narin görmemesi gereken başka bir şey görmüş olabilir mi? Daha yine dedim ya işte Nevzat'ın başkasıyla bir ilişkisini görmüş olabilir. Yani şimdi şunu merak ediyorum. Bakın. Şimdi Gazal'la anlattınız arabayı konuştunuz. Dediniz ki o kaza yaptı. Arabasında başkasının arabasını görüyordum kapısının önünde dediniz. Köy yeri böyledir. Çok fazla meşguliyet yani harici tarla meşguliyet diye dışında vakit boldur. Karşı komşuya kim geldi kim gitti bunları çok takip edilir. Biz de köyde büyümüş bir nesiliz. Doğru mu?

Yüksel Güran : Evet.

Mahkeme Başkanı : Köye bir tane yabancı plakalı araba gelse hemen bu gelmiş niye gelmiş diye takip edilir. Doğru mu? Doğru mu?

Yüksel Güran : Sen görsen söylerim.

Mahkeme Başkanı : Yani birbirinize dedikodu mahiyetinde konuşursunuz. Peki Narin bu 4 dakikayı da 5 dakika köyde buna ilişkin bir dedikodu duydunuz mu?

Yüksel Güran : Hayır.

Mahkeme Başkanı : Duymadınız. Narin 5 dakika içerisinde öldürülmeden önce herhangi bir şey görmüş. Nevzat'tan ya da Salim'den. Olabilir mi?

Yüksel Güran : Görmemişim ki. Görseydim yemin ederim en başta söylerdim bağırırdım.

Mahkeme Başkanı : Görmediğinizi söylüyorsunuz da ben dedikoduyu duydunuz mu diye soruyorum.

Yüksel Güran : Hayır dedikodu görmemiş. Ne duymuş ne görmüş.

Mahkeme Başkanı : Tamam teşekkür ederim buyurun arkaya oturabilirsiniz. Bir soru geldi bekleyin.

Mahkeme Başkanı : Tam ses olmuyor ya lütfen. Tam ses olmuyor avukat bey biliyor musunuz?

Av. Mustafa Demir : Şimdi bu yazmayla ilgili çok şey soruldu ya. Acaba bu yazma evde hani bulduğunda imama soruyor. Yani buradan şunun için mi soruyor eve gelip gelmediğini teyit etmek için mi? Yani o gün eve ulaştı mı ulaşmadı mı? Bunun teyidi için mi sordu imama? Veya bunu yetkilileri de açıkladı.

Mahkeme Başkanı : Soralım yani yazmayı imama niye sordunuz?

Yüksel Güran : Yazma. İmam dedi ki, mor bir etek vardı üstüne mor bir yazma vardı. O dediği zaman ben de dedim bakayım hocam bu yazma benimdir. Ben gece benim bayanları benim oturduğu zaman burada görmüştüm. Acaba budur bu değildir? Dedi vallahi ben emin değilim bu sanki bu değildir. Ondan ben soruyorum.

Mahkeme Başkanı : Mor etek nerede?

Yüksel Güran : Mor etek bilmiyorum.

Mahkeme Başkanı : Yani mor etek giydi mi o gün?

Yüksel Güran : İmam öyle söylüyordu.

Mahkeme Başkanı : Evden çıkarken mor etek giydi mi?

Yüksel Güran : Biz aradı mor eteği görmedik.

Mahkeme Başkanı : Çünkü cesette de yok. Doğru mu?

## Sanık Enes Güran Müdafi

### Av. Mustafa Demir

Av. Mustafa Demir : Var var şeyde var.

Mahkeme Başkanı : Cesette mor etek var mı? Tamam ben gözden kaçırmışım.

Av. Mustafa Demir : Bunu şunun için sordum. Buradan biri mi getirdi düşündün yoksa eve geldi Narin bıraktı bir yere gitti mi diye düşündün?

Yüksel Güran : Hayır. Çünkü o balkonu ben yıkadım. O balkonu sonra bayanlar sermişti. Yastık minder getirdiği zaman. Öyle beni getirdiler. Ağlarlar beni böyle şişlere bıraktılar ya. O böyle gözüme girdi. Gördüğü zaman sabah oldu ikinci gün. İmam geldiği zaman dedi böyle etek mordur yazma mordur. Ben hemen gittim o yazmayı getirdim. Dedim hocam bu yazmadır? Dedi vallahi ben tam emin değilim. Dedi bak beni getirdi. Aynı o gece ben bu mor yazmayı bu şiş arasında gördüm. Dedi vallahi ben tam emin değilim.

Av. Mustafa Demir : Kimin koyduğunu kimin getirdiğini bilmiyorsunuz.

Yüksel Güran : Yok bilmiyorum.

Av. Mustafa Demir : Buradan ne çıkaracaktın? Mesela imam deseydi ki bu mor yazma evet o mor yazma. Sen ne anlayacaktın?

Yüksel Güran : Ben ne anlayacaktım? Hemen jandarmaya verecektim. Dedim bak bu gece birisi bu mor yazmayı getirmiştir.

Av. Mustafa Demir : Gece birisi bırakmıştır.

Yüksel Güran : Diyecektim bak bu mor yazma gece buraya gelmiştir. Bu benimdir. Ama ben balkonu yıkamış önce burada değildi. Bayanlar burayı istediği zaman ben burada görmüş. Hemen jandarmaya teslim edecektim.

Mahkeme Başkanı : Tamam buyurun. Teşekkür ederim.

## Sanık Yüksel Güran Müdafi

### Av. Yılmaz Demiroğlu

Av. Yılmaz Demiroğlu : Sayın Başkanım şimdi iddianamede telefon kayıtlarının bazı zapt kayıtlarının silindiği şeklinde bir iddia ileri sürülmüş. Siz herhangi bir şekilde telefon kaydınızı mesajları sildiniz mi?

Yüksel Güran : Kesinlikle.

Mahkeme Başkanı : Hayır? kesinlikle hayır?

Yüksel Güran : Bilmiyorum, silmeyi de bilmiyorum. Zaten ben normalde WhatsApp'ta oynamıyorum.

Av. Yılmaz Demiroğlu : İddianamede telefonun kapatıldığı söyleniyor. Şu 15, kritik saatlerde 15:30'a kadar falan telefonun kapatıldığı söyleniyor. Böyle bir şey oldu mu yoksa?

Yüksel Güran : Telefonu kimse kapatmamıştı. Çocuklar elindedir.

Av. Yılmaz Demiroğlu : Uyku halindeydiniz, anladım. Peki Maide Kaya, Maşallah ve Birsen 17:40'ta pardon Maide biraz daha geç bir saatte söylüyor.

Yüksel Güran : Evet 07:30'ta, 7'ye 20 dakika kalıyor, bize öyle söylediler.

Av. Yılmaz Demiroğlu : 7'ye 20 kadar söylediler. Şimdi iddianamede diyor ki, Güran ailesi bu tanıkları etkilemiş?

Yüksel Güran : Evet aynen bize öyle dediler.

Av. Yılmaz Demiroğlu : Bu nedenle olmuş. Siz de jandarma bu tanıkların beyanına başvurulduktan sonra sizin Didem Aslan Yılmaz ile Vazgeçme isimli bir televizyon programında bir röportajınız var.

Yüksel Güran : Evet.

Av. Yılmaz Demiroğlu : Orada bas bas bir şey bağırıyorsunuz. Diyorsunuz ki, Narin orada gitmiyor ya tepeye çıkıyor ya oradan dolanıyor şeklinde bir röportajınız var. Bunu açıklar mısınız? Niçin böyle bir şey söylediniz? Ya da hatırlatayım. Şöyle, kızım asla yabancı arabaya gitmez.

Yüksel Güran : Evet söylemişim.

Av. Yılmaz Demiroğlu : Bir tanıdık kızıma gel bunu al derse o zaman giderim şeklinde bir ifadeniz oldu mu?

Yüksel Güran : Evet söylemişim.

Av. Yılmaz Demiroğlu : Peki Maşallah ve Birsen ilgili yani bu saatler konusunda siz duyduğunuzda ne düşündünüz? Yani o saatte Narin göründü mü?

Yüksel Güran : O zaman bize dediler yani Maşallah diyor 5. Evet. Mahide diyor 7'ye 20 dakika kalıyor. İsa yanında dedi 6. Şeyma dedi 4 buçuk. Biz buna dediler Narin nerededir? Bütün jandarma üstümüze yüklüyordu. Narin 7'de kaybolmuş. Narin 7'de eve gelmiş. Sen de Enes evdeydin. Bütün yükü bizim üstümüze attı. Bu çocuklar yalan söylemiyor. Sonra jandarma bir ekip geldi. Elinde alet vardır. ahırın etrafına her gün geziyor. Her gün geziyor. Yok bu olay. 3'te ahırda olmuş. Bu şahitleri muhtar siz yalanla bu şahitleri tutmuşsunuz. Bunları siz tutmuşsunuz. Siz zorlamışsınız. Biz sonra Nevzat ortaya çıktı. Narin evde çıkartmışsın. Tekrar yine bizi üstümüze yüklüyor. Narin evde çıkmış. Nereye gidiyor, üstümüze atıyor. 7'de biz yapıyoruz. Sonra 3'e aldılar. Bu şahitler siz yalan söylemişsiniz. Onları zorlamışsınız. Sonra ahırda çıktığı zaman Nevzat evi içinden almışım. Tekrar üstümüze atıyorlar. Sen de Enes oradasın. Ya Salim oradadır. Yine evi içine attılar. Yani nereye götürdüler bizim boynumuza atmışlar. Evet.

Av. Yılmaz Demiroğlu : Tamam teşekkür ederim.

Mahkeme Başkanı : Ben teşekkür ederim.
