---
title: "Tavşantepe Köyü masum olabilir mi?"
date: 2024-09-16
author: "Yıldıray Oğur"
source: https://www.karar.com/yazarlar/yildiray-ogur/tavsantepe-koyu-masum-olabilir-mi-1601201
description: |
 21 Ağustos'ta öldürülmesi üzerinden neredeyse bir ay geçti ama hâlâ 8 yaşındaki Narin Güran'ı kimin ve neden öldürdüğünü bilmiyoruz. Bütün önyargıların, sızıntıların ve suçlamaların gerçek katile yardım edip etmediğini sorgulayan; Diyarbakırlı yüksek lisans öğrencisi Miham Akkul'un "İtham ediyorum" mektubu üzerinden cinayet soruşturmasını yeniden okuyan yazı.
categories: [Narin, Medya eleştirisi, Tavşantepe, Önyargı, Miham Akkul, Salim Güran, Nevzat Bahtiyar, Sahte haber]
---

21 Ağustos'ta öldürülmesi üzerinden neredeyse bir ay geçti ama hâlâ 8 yaşındaki Narin Güran'ı kimin ve neden öldürdüğünü bilmiyoruz.

Peki neden?

Televizyonlara göre köy sessizlik yemini edip, katili koruduğu için.

Bazı yorumculara göre Jandarma cinayet soruşturmalarında yetersiz olduğu için.

Ya peki şu anda bu cinayetin aydınlanması önündeki en büyük engel, köylülerin sessizliği değil de geri kalan herkesin gürültüsüyse?

Bir köy; tarikatçı, Hizbullahçı, feodal ilan edildi, ailede neredeyse herkes hakkında yasak cinsel ilişki iddiası ortaya atıldı, bütün köy halkı sorguda ser verip sır vermeyen Omerta Kanunu'na sadık kararlı militanlar gibi şeytanlaştırıldı, bütün oklar Güran ailesine yöneltildi.

Bu saatten sonra katil Güran ailesinden biri çıkmazsa, şartlandırılan milyonlarca insan buna nasıl ikna olacak?

Galiba şu anda soruşturmanın önündeki en büyük engel günlerdir televizyonlardan yayılan kültürel önyargılar, ideolojik propaganda, siyasi hesaplaşmayla dolu bu kanaat çöplüğü.

Peki bütün bu önyargılar, sızıntılar, suçlamalar katile yardım ediyor olabilir mi?

Narin cinayetiyle ilgili bana bu soruyu sorduran, bütün propaganda makinesinden uzakta Fransa'da yüksek lisans yapan, mahalleyle ve aileyle bir yakınlığı olmayan Diyarbakırlı Miham Akkul'un en başından itibaren bütün haberleri, delilleri, ifadeleri takip ederek yazdığı çarpıcı mektup oldu.

Mektup şöyle başlıyor:

> "Doğup büyüdüğüm bu yerde olan hadiseler için 'j'accuse' (İtham ediyorum) diyeceğim. Zira 8 yaşındaki kız evladı katledilen bir anne, iffetsizliğinin hırsına kızını kurban ettiği suçlamasıyla demir parmaklıklar ardına itildi.
>
> Ülkenin muhalifleri için amiral gemisi olan kanalın muhabiri ve İstanbul'daki stüdyoları gerçeği değil adeta Salim Güran'ı suçlayacak bir kanıt arıyor. Bütün bu konuşmalar tartışmalarda, Kürtler arasındaki ensest ilişkiler, Mustafa Kemal'in ağaları CHP mebusu yaparak feodaliteye karşı verdiği amansız mücadele, tarikat, cemaat aralara sıkıştırılıp asıl suçlular ima ediliyor.
>
> Hatta bu rüzgâra kapılan Kürt hareketinin tutuklu eski genel başkanın avukatı 'zihniyetimizi sorgulamalıyız' diyerek yeterince ehlileşmemiş olmanın mahcubiyetini duyuyor. DEM Partisi 'kahrolsun Hizbullah' diye sloganlarla yürüyüşler düzenliyor, 32. Gün'ün Silvan'da Hizbullah mezar evlerinin çıktığı Yolaç Köyü'nden çektiği video Tavşantepe Köyü diye paylaşılıyor binlerce beğeni alıyor.
>
> Bazıları hızını alamayıp yeraltı arama cihazlarında Hizbullah'ın kayıp silahlarının çıktığını iddia ediyor ve derin devletin direktifleriyle Narin olayının bu yüzden kapatıldığı söyleniyor.
>
> Peki gerçekte ne oldu ve bu Tavşantepe köyündekiler kimdi?
>
> Tavşantepe Köyü'nün seçim sonuçlarına baktığımızda 2015 yılından itibaren çeşitli partilerin birinci çıktığını görebiliyorduk. 2015'te HDP, 2023'de İYİ Parti, 2024'de AK Parti birinci olmuştu. Köy Hizbullah'ın filan değildi hatta ailesi gözaltında olan Baran Güran kızkardeşinin cenazesini almış, devlet ve iktidar destekli medya Baran'ın Newroz görüntülerini paylaşmış, aileyi DEM ve PKK sempatizanlığıyla suçlamıştı. Hizbullah kanadı da DEM'lilerin küçük Narin'i Suriye'ye kaçırıp YPG için yetiştirdiğini ima eden twitler atmıştı. Hüda-paralılar morg önünde cenaze bekleyenlere başımıza ne geldiyse Avrupa'dan geldi diskuru çekmişlerdi.
>
> Güran ailesi yüzyıllar önce Şehrizor bölgesinden Diyarbakır'a göçmüştü. Öyle derin politik angajmanları filan olan bir aile değildi. Diyarbakır büyüyüp surların dışına taştıkça değerlenen arazileri sayesinde iyice zenginleşmişlerdi. Köy muhtarı Salim Güran, şehre göçenlerin tarlalarıyla da ilgilenir herkese çeşitli bilgilendirmeler yapardı. Kısaca akrabalarının malına mülküne göz kulak olup ailenin reisi rolünü oynardı.
>
> Narin'in kaybolduğu 21 Ağustos günü Antalya'daki Mehmet Şerif Güran'ı da aramış ona pamuklarının kurtlandığını fotoğraflar eşliğinde haber vermişti. Bu görüşmeyi cinayeti örtbas için profesyonel destek almak için yaptığı bile öne sürülmüştü."

Ardından mektupta delillere ve iddialara bakılıyor.

2 Eylül günü gözaltına alınan amca Salim Güran'ın üzerine şüpheleri çeken ilk iddia, Güran'ın 15 Ağustos tarihli son Facebook postunun altına yazılmış bir nottu.

Benzin istasyonu çalışanı Murat Çınar Çatalca'nın yazdığı iddia edilen not 4 Eylül günü tüm medyada haber olmuştu:

> "Salim Güran köyün muhtarıdır. HTS kayıtlarında olay öncesi ve sonrasında Narin Güran'ın annesi ile hem mesajlar hem de aramalar kayıtları var. Olay günü Narin kaybolduktan 15-20 dk sonra bu it Salim Güran kendi aracıyla hızla köyden çıktı. Yakıtını da almıyor. Bir petrole giriyor marketten ıslak mendil alıyor. Kamera kayıtları alındı. Yemin ederim kamera kayıtlarını kendim verdim jandarma komutanına. Benim görüntülerden hiçbir şey paylaşmamam istendi. Hatta paylaşmamda delil medyaya vermekten ceza alırım denildi. Bu muhtar Narin'in erkek kardeşi Enes ile de görüşüyordu. Telefon kayıtlarına göre olay sonrası ve kamera kayıtlarında ne yazık ki Narin ya baygın ya da Salim elleriyle boğmuş vaziyette yatıyor ön koltukta ve üstünde koyu kahve renginde bir battaniye vardı. Muhtarı petrol çalışanları da tanıdığı için şüphe yoktu. Ayrıca muhtar telefonu kapalıydı ve 2 saat sonra köye karanlıkta dönüyor. Bu sefer köye döndüğünde sanki hiçbir şeyden habersiz gibi davranıp ne olmuş Narin'e diye ağlamış üzüntü süsü vermiştir."

Haberlerde benzincide çalışan Murat Çınar Çatalca'nın bu nottan sonra Jandarma'ya gidip ifade verdiği iddia edilmişti.

Sonra tuhaf bir şekilde aynı iddiaları yazan başka Facebook hesapları da ortaya çıktı.

Ama aslında ortada ne ifade vardı, ne benzinci, ne de benzinciden Jandarma'ya verilmiş güvenlik kamerası kaydı.

Aslında ortada 2019 yılında intihar notu paylaşmış Murat Çınar Çatalca diye biri de yoktu.

Kısa süre sonra hem onun hesabı, hem de ona destek veren diğer hesaplar kapanıp, ortadan kayboldular.

Mektuptan okuyalım:

> "Narin Güran'ın kaybolduğu ilk hafta Salim Güran hakkında ortaya asılsız bir benzinci hikayesi atıldı. Güya Salim Güran Ağustos ayının 40 derecelik Diyarbakır sıcağında Narin'i öldürmüş ve o sıcakta battaniyelere sarıp herkesin göreceği şekilde ön koltuğa oturtmuş, ıslak mendil almaya çıkmıştı. Bu absürt iddia günlerce tartışıldı hatta pompacının ölümle tehdit edildiği söylendi."

Ama medyada günlerce dolaşan bu sahte paylaşımdaki **"Güran'ın arabasında ön koltukta battaniyeye sarılmış Narin'in cesedi"** iddiası birkaç gün sonra kritik bir ifadede ortaya çıktı.

Cinayette en kritik dönüm noktası köyün yakınlarındaki Jandarma gözlem noktasındaki güvenlik kameralarından çıkan bir görüntü oldu.

Görüntülerde Kırmızı bir otomobilin, Narin'in kaybolduğu 21 Ağustos'ta saat 15.40'ta dereye yakın bölgeye gelip, park ettiği ve yaklaşık 50 dakika boyunca orada kaldığı görülüyordu.

Derede aramalar yoğunlaştırıldı. Ve üç gün sonunda 8 Eylül günü sabah saatlerinde Narin'in çuval içindeki cesedinde ulaşıldı.

Kırmızı arabanın sahibi de gözaltına alındı: Sıva ustası Nevzat Bahtiyar.

Cesede dokunmuş, doğrudan cinayete karışmış olabilecek bir şüpheli vardı artık.

Ama daha önce de diğer köylüler gibi ifade veren ve hiçbir şey söylemeyen Bahtiyar, yakalanır yakalanmaz itirafçı oldu ve 9 Eylül günü Jandarma'ya verdiği ilk ifadede suçu muhtar Salim Güran'a attı.

Bunu yaparken de günlerdir medyada okuduğu sahte benzincinin iddialarını kullanmıştı:

> "İlk ifadesinde köyde Salim'e rast geldiğini ve Salim'in arabanın ön koltuğunda battaniyeye sarılı Narin'i kendisine teslim ettiğini iddia etmişti. Olmayan benzincinin ön koltuktaki battaniyeli uydurma hikayesinden faydalanıyordu Nevzat. Elbette 3 haftadır dedektifçilik oynayan medya mensuplarının aklına Salim'in neden Narin'i bagaja değil de ön koltuğa en görünen yere koyduğunu sormak gelmiyordu."

Nevzat Bahtiyar'ın Bağlar İlçe Jandarma Komutanlığı'nda 9 Eylül gecesi saat 00.52'de başlayan ifadesi 03.12'de bitti.

Bahtiyar bu ifadesinde Narin'in cesedini niçin alıp dereye gömdüğünü şöyle anlattı:

> "(Salim Güran) Aracın ön yolcu koltuğunda bulunan battaniyeye sarılı bir şeyi göstererek 'Bunu yok edeceksin' dedi. Ben de gösterdiği şeyin yanına yanaştım, bakınca battaniyeye sarılı ve hareketsiz yatan bir insanın olduğunu gördüm. Şaşırdım ve tereddüt ettim. Salim Güran bana 'aileyi düşün, sana 200 bin lira veririm' dedi."

Fakat Nevzat Bahtiyar, bir gün sonra savcılığa verdiği ifadede bu hikayesini değiştirdi.

Hâkimlik ifadesinde neden değiştirdiğini şöyle anlattı:

> "Savcılıkta verdiğim ifademde geçen Salim'in bana dediği 'Arif'in kızını öldürdüm, sen de bu cesedi alıp yok edeceksin. Yoksa seni ve aileni öldürürüm' şeklindeki ifade doğrudur. Daha önce ifademde bu durumdan bahsetmemiştim çünkü Salim Güran'dan korkmuştum."

Bir gün arayla verdiği iki ifade arasında çok sayıda çelişki vardı.

Jandarma ifadesinde cesedi çuvala Salim Güran'la beraber koyduklarını anlatmıştı:

> "Bana hitaben 'Aracında torba var mı?' dedi. Ben de aracımın bagajından rengini hatırlamadığım bir çuval çıkartarak Salim Güran'a verdim. Battaniyeye sarılı çocuğu alıp çuvalın içerisine beraber koyduk. Mezarlığın yanından inerek Villalar mevkiine gittim (…) Derenin yanındaki stabilize yoldan inerek aşağı inerek uygun bir yer baktım. Aracımı derenin kenarında durdurdum."

Savcılık ifadesinde ise evine gidip, cesedi çuvala kendisinin koyduğunu anlattı:

> "Daha sonra ben kendi ikametimde Narin'in cesedini tek başıma çuvalın içerisine yerleştirdim."

Yine Nevzat Bahtiyar, jandarma ifadesinde çuvaldaki cesedin kime ait olduğunu bilmediğini söylemişti:

> "Beraber çuvala koyduğumuz esnada cesedin Narin Güran olup olmadığını anlamadım. Dere yatağına inip çuvalın ağzını bağladığım esnada cesedin Narin Güran olduğunu anladım."

Ancak savcılık ve mahkeme ifadesinde bunu da değiştirdi:

> "Salim bana 'Arif'in kızını öldürdüm, sen de bu cesedi alıp yok edeceksin' dedi."

Halbuki 9 Eylül'deki Jandarma ifadesinde "Salim Güran'ı Narin'i neden öldürdüğüyle ilgili bir bilginiz var mı" sorusuna şöyle cevap vermişti:

> "Bana neden öldürdüğünden ve kendisinin öldürdüğünden bahsetmedi. Ama kendisi öldürmediyse neden bana bu cesedi ortadan kaldır desin"

10 Eylül'deki Savcılık ifadesinde ise Salim Güran'ın Narin'i neden öldürmüş olabileceğiyle ilgili iddialı teoriler ileri sürdü:

> "Salim Güran'ın Yüksel Güran (Narin'in annesi) ve amcasının eşi Maşallah Güran ile ilişkisi olduğu konuşuluyordu. Ama bu hususta kimsenin ifade vereceğini düşünmüyorum. Benim tahminin bu kadınlardan biriyle yaşadığı cinsel ilişkiyi Narin'in gördüğü yönünde. Bu nedenle Narin Güran'ı öldürebileceğini düşünüyorum. Ancak ben kendi gözlerimle bu kadınlardan biriyle bir ilişki yaşadığını görmedim. Ayrıca şu hususu belirtmek isterim. Uğurcan Güran'ın 25 Ağustos'ta düğünü olacaktı. Erkeklerin büyük çoğunluğu davetiye dağıtmak için köy dışında olduğundan Salim Güran'ın böyle bir cinsel ilişki yaşamak için Tavşantepe Köyü'nde kalmış olabileceğini düşünüyorum. Salim Güran'ın beni ilk çağırdığı nokta Arif Güran'ın ahır olarak kullandığı yerdi. O ahırda bir cinsel ilişki yaşanmış olabilir. Narin de bu noktada bir şeyler görmüş olabilir."

Peki, bir gün önceki ifadesinde olmayan bu "yasak ilişki", "ahırda cinsel ilişkiyi gördüğü için Narin öldürülmüş olabilir" iddiaları nereden çıkmıştı?

Çok basit.

Çünkü bu savcılık ifadesinden bir gün önce 9 Eylül günü Didem Arslan Yılmaz, amca Salim Güran ile Narin'in annesi arasında ilişki ve Narin'in bunu gördüğü için öldürüldüğü iddiasını televizyonda anlatmıştı.

Nevzat Bahtiyar, benzincinin battaniye hikayesinden sonra bu yasak ilişki iddiasını da ifadesine eklemişti.

Ama **'Arif'in kızını öldürdüm, sen de bu cesedi alıp yok edeceksin'** gibi Yeşilçam replikleri benzeyen bu abartılı ve çelişkili ifadeler kimseyi şüpheye düşürmemişti.

Mektuptan okuyalım yine:

> "3 haftadır dedektifçilik oynayan medya mensuplarının aklına Salim'in neden Narin'i bagaja değil de ön koltuğa en görünen yere koyduğunu sormak gelmiyordu. Daha sonra bu abuk ifadesini değiştiren Nevzat, Narin'i eve götürdüğünü itiraf etmek zorunda kaldı ve Salim'in parayla değil ailesiyle tehdit ettiğini öne sürdü. Ve Salim'in Narin'in annesiyle ahırda ilişkiden ötürü öldürüldüğünü tahmin ettiğini söyledi. Kimse Nevzat'a zaten Narin'i öldürmekle suçladığı Salim'i neden yalan ifadeyle suçlamak ihtiyacı hissettiğini sorgulamadı. Yani Nevzat en kötüsünü zaten söylüyordu bu en kötü iddiayı ortaya attıktan sonra gerçeğini neden anlatamamış ve ilk ifadesini değiştirmişti demeyi kimse akıl edemiyordu. 30 yıllık inşaat ustası Nevzat'ın 40 dakika içinde dereye 8 yaşındaki Narin'i bırakıp üzerine bir kaç taş koyamayacağı bile iddia edildi."

Ama itirafçı olduğu için dokunulmazlık kazanan Nevzat Bahtiyar'ın ifadelerindeki çelişkilerle ilgilenmedi, onun yerine köylüler şeytanlaştırıldı.

**Narin** bulunduktan sonra köylülerin akıllı telefonlar yerine **tuşlu telefon** kullanmaya başlamaları, "korkunç derecede kriminal, soğukkanlı, örgütlü olmalarına, üst bir akıldan talimat almalarına" bağlandı.

Halbuki gerçek çok basitti: Jandarma telefonlara el koyup köylülere tuşlu telefon vermişti:

> "Aile ve bireyleri organize katı bir suskunluk yemini etmekle suçlanıp köye OMERTA KÖYÜ ismi uygun görülürken daha geleneksel olanlarca 'ŞEYTAN TEPE YA DA DİLSİZ ŞEYTANLAR KÖYÜ' tabelasının daha münasip olacağı söylendi. Bunca köylü insanın, kadınların, gençlerin Marxist bir örgütün militanları gibi ağzı sıkı, sorgulara dirençli olmasının imkansızlığı tartışılmadı. Manipülatif şekilde 'Neden konuşmuyorlar' diye ekranlarda tartışılıp duruldu. Konuşacak bir şeyleri olmayabilirdi ama bu ihtimal kimin umurundaydı? Ortada organize bir cinayetin olmadığı daha sonraki gözaltılarda da açıkça belliydi, zira anneye 'kızınız Salim'in arabasına bindi mi' diye sorulduğunda 'evet nişana gitti o arabayla arabayı Salim'in oğlu Devran sürüyordu ama kızım arkaya bindi' demişti. Yani Salim'in aleyhine olabilecek bir detayı değiştirerek söylemiyordu. Keza Enes 2-3 yıl önce babası ve amcası arasında bir maddi problem olduğunu söylemişti o da amcasını korumak derdinde filan değildi herkes bildiğini olduğu gibi anlatıyordu."

Bu arada Salim Güran aleyhine en güçlü delillerden biri olan arabasında çıkan Narin'in DNA'sında yer değişikliği olmuştu.

Salim Güran'ın ilk ifade tutanağında Jandarma'nın sorduğu sorulara göre arabasındaki Narin'e ait DNA örneği aracın ön sağ koltuğunda tespit edilmişti. Yani arabanın ön koltuğunda cesedin taşındığıyla ilgili tezi doğrulayan bir tespitti bu.

Ama Salim Güran'ın yeni ifadesinde sorulan soruda "Narin'e ait DNA'nın aracın arka sağ koltukta, kapının iç kısmında bulunduğu" söylenmişti.

İsmail Saymaz, rapordaki bu kritik çelişkiyi televizyonda anlattı:

> "Bu DNA nerede duruyor? Sağ ön koltukta olmasıyla sağ arka koltukta olması arasında fark var. Çünkü daha önce bu konuda Salim'in karısına sorulduğunda, 'sağ ön koltuk' demişti. Sağ ön koltukta Narin'in DNA'sı var diye sorulduğunda, yanıt olarak şu ifadeyi kullanmışlardı: 'Biz bundan bir ay önce yeğenimizin nişanı için köyden bir yere gittik. Önde Hediye oturuyordu, ön koltukta. Arabayı Devran kullanıyordu. Arka koltukta ise çocuklar vardı. Narin ise arkada oturuyordu.' Şimdi bu sorguda diyor ki, aslında DNA arka koltukta, kapının iç tarafındaymış. Şimdi DNA önde olduğunda Salim'in ve karısının yalan söylediği ortaya çıkar. Veya DNA arkadaysa Narin'in annesinin doğru söylediği ortaya çıkar."

Ve geldik son en güçlü delile.

12 Eylül akşamı Halk TV'de Ferit Demir, "cinayeti çözecek ses kaydı" diyerek Salim Güran'ın, yanında çalışan 15 yaşındaki R.A.yla telefon konuşmasından bir cümleyi paylaştı:

> "Salim Güran, R… A…'la, Narin'in kaybolduğu 15.15'ten kısa bir süre sonra bir telefon görüşmesi yapıyor. Telefon görüşmesinde şunu soruyor, R… A…'un telefonundan elde edilen ses kaydında; 'R…, kız yaşıyor mu öldü mü?' Tekrar ediyorum, 'R…, kız yaşıyor mu öldü mü?' Bu kadar, kısacık bir ses kaydı, R… A…'un telefonunda kaydediliyor. Bu tutanaklara da geçti ve bunu birkaç farklı kaynaktan da doğrulattık. En az 4 ayrı kaynaktan doğrulattık."

Ertesi gün telefondaki ses kaydının dökümleri ortaya çıktı.

Kayıtlarda "R…, kız yaşıyor mu öldü mü?" diye bir cümle yoktu.

Görüşme Ferit Demir'in iddia ettiği gibi Narin'in kaybolmasından kısa bir süre sonra değil, Narin'in ortadan kaybolmasından yaklaşık 3,5 saat sonra 18.38'de yapılmıştı.

Orijinali Kürtçe olan sesli mesajlaşma Türkçe'ye şöyle çevrilmişti:

> **Salim Güran:** O sondaki köşede bir şeyin düşmüş ha, sana ait bir şey sondaki yamaçta, yamacın köşesi taş.
>
> **R.A.:** Eee
>
> **Salim Güran:** Biri yerde
>
> **R.A:** Tamam henüz bende değil, daha ölmemiş.

Salim Güran'a yeni ifadesinde bu görüşme soruldu:

> "Bahsetmiş olduğunuz görüşme içeriğini hatırladım. Ben bahse konu mısır arazisinin sulamasını yaparken kullandığım trafonun elektriğini bazen kaçak yapmak için bir alet kullanıyordum. Olay günü de o aleti R.A.'ya bırakmış olduğum taş dibinden alması için aradım. Görüşme içeriği tamamen bununla alakalıdır. Narin'in ölümü ile bir alakası yoktur."

Miham Akkul, mektubunda bu ses kaydının çevirisiyle ilgili bir sorun olduğunu iddia ediyor:

> "Bu diyalogda sondaki ölmemiş kelimesinin bağlamdan kopukluğunu şifreli konuşmuşlar ve dosyadaki en büyük kanıt diye medya afişe etti. Peki işin gerçeği neydi? Aslında bu diyalog 18:35 sıralarında Salim ve 15 yaşındaki işçisi arasında idi, kaçak elektrik meselesi ile alakalıydı. 18:35 olan bu konuşmanın aslı Kürtçeydi yani ortada bariz bir çeviri hatası vardı, Kürtçe daha ölmedi derken: 'hin nemiri' denir. Muhtemelen 'hin nemiri' değil 'hin neliviri' burda değil yahut 'nemirayi' bende değil denmişti. Zaten Kürtçede 'ne' ile başlayan olumsuz eki daha pek çok kelimeyle karıştırılmış olabilirdi. Bir başka apaçık tuhaf çelişki de zaten 15:30 civarlarında cesedi çoktan gömmüş olan Nevzat'ın hikayesiyle bu olayın kopukluğuydu. Zalim, kurnaz, paralı, Kürt, dinci bu muhtar Narin'i kâh Nevzat'a kâh 15 yaşındaki bir işçiye verip öldürüp yok etmelerini istiyordu. Narin aynı anda iki yerde katledilip feodal Salim'in cumhuriyetin değerlerinden nasiplenmemiş marabaları tarafından mütemadiyen katledilip gömülüyordu."

Bu kritik ses kaydının Kürtçe'den Türkçe'ye çevirisi adli makamlar tarafından yeniden yapılıyor. Yeni çeviri gerçeği ortaya çıkarabilir.

Yani özetle ortada medyanın başat bir rol oynadığı ideolojik önyargılar, sürekli sızdırılan bilgiler ve bazı gazetecilerin suçu bir aileye ve köye atmak ve günün sonunda yanılmamak için yaptıkları manipülasyonlarıyla içinden çıkılmaz hale gelen bir soruşturma var.

Ve katil bütün bunlardan yararlanıyor.

Miham Akkul, "İtham ediyorum" diye başladığı mektubunu şöyle bitiriyor:

> "Narin Güran'ın hikayesi bana Billy Wilder veya Sydney Lumet'nin 50 ve 60'lı yıllarda medyanın yıkıcı ve öldürücü tarafları üzerine yaptıkları filmleri hatırlatıyor. Daha çok da 1952 yapımı *Ace in the Hole* filmini. 2024 yılının ağustos ayında Narin, Nevzat Bahtiyar tarafından gömüldü, ailesi ise bu kapkara cinayetin oluşturacağı kontrastla beyaz hissetmek isteyen histerik bir toplumun hıncıyla aynı şekilde taşlanıp gömüldü. Şimdi bu gömünün üzerinden sarımtırak dere değil ama köyün mahfıyla sonuçlanacak yıllar süren duruşmalar, açılıp kapanan demir kapılar, telaşlı mübaşirler, paragöz avukatlar akacak …."
