---
title: "Salim Güran Savunması"
editor: source
---

## Mahkeme Başkanı

Mahkeme Başkanı : Evet iddianame size geldi. İddianameyi okudunuz. Hakkınızdaki iddiaları biliyorsunuz.

Salim Güran : Evet.

Mahkeme Başkanı : Avukatlarınız var. Tekrar hatırlatmak gerekirse sorulara cevap vermem hakkına sahipsiniz. Susma hakkına sahipsiniz. Avukatınızın huzurunda beyanda bulunacak mısınız? Siz dinliyorum. Buyurun.

Salim Güran : Şimdi her zamanki gibi ben sabah erken kalkarım. Şimdi bize sulamacı tutmuşuz. Yüzdelik. Yüzde sekize.

Mahkeme Başkanı : Biraz daha yüksek sesle bağırarak.

Salim Güran : Ondan sonra onlar her sabah ben onlardan önce beraber tarlaya gideriz. Ben gittiğim zaman orada oturmuyorum. Ben çalışıyorum zaten. Kendimi bildim bileli çiftçiyim çalışıyorum. Herkes biliyor yani. Aynı gün yine sabah kalktım. Kalktım tarlaya beraber gittik, çalıştık. Sondajın yanına gittim. Bizim Karakoç'la Tavşantepe arasında bir sondaj var. Bir de aşağıda var. Gittik yukarıda oturuyoruz, yiyoruz, içiyoruz, orada oturuyoruz. Saat 10-11 gibi eve geldim. Geldim çocuklarıma dedim. Düğündür. Gidelim size elbise alalım. Devran oğlum hariç diğerleri hepsini arabaya bindirdik. Diyarbakır Bağlar Sağlık ocağına gittik. Onlara elbise aldık. Elbise dönüşü geldik. Polis noktası Çarıklı'ya yetişmeden Opet'te 200 TL yakıt aldım. Oradan Çarıklı'dan köye istikametine gittim. Eve gittik. Yani ortalama saat 02:45 - 02:50 falan. Eve gittik. Sıcaktı hava. Klimayı çalıştırdılar işte. Eşim bana yemek hazırladı. Yemek yedim. Yemek yedikten sonra uzandım. İstirahat ettim. Yaklaşık 1 saat, 1 saat 20 dakika falan. İstirahat ettikten sonra kalktım. Arabaya bindim. Yine yukarı sondaja gittim. Yukarı sondaja gittim. Oradayken elektrikçiler geldi. İki tane elektrikçi. Hayırdır? Dedi vallahi Mehmet Şerif Güran amcanın oğlunun trafosunda arıza vardır. Dedi ki, biz onun için gelmişiz. Onunla konuşmuşuz. Ben dedim vallahi doğrudur. Bak hala da ateş atıyor dedim. Dedi bizimle gel oraya dedi. Tarla yoluydu, bozuk yol. Arabası da eski. Bir tane mavi şahin. Oturduktan sonra orada hatta bir şeyler de yediler yani karpuz falan yediler. Kalktık beraber gittik. Mehmet Şerif'in tarlası, trafosu, araba yanına gitmiyor. Epey yürüyoruz. Yürüdüğümüz zaman ben pamuğun içinde yürüdüm. Ben pamuktan anlıyorum. Ben çiftçiyken, ben bildim bileli çiftçiyim. Kontrol ediyorum. Bakıyorum yeni yeni pamuk kurtlanmış. Aradım amcam oğlunu. Amca oğlu dedim vallahi pamuğum güzeldir. Ama yazıktır kurtlanmış, bunu ilaçla dedim. Dedi tamam amca oğlu. Yine aradı. Dedim bak dikenli kurttur. O beni aradı. Hangi ilacı atayım? Dedim krojen al. Öyle telefonlaştık. Sinek ilacı at falan filan. O sırada Abdulsamet bir de öbürü elektrikçi, ismini unuttum.

Mahkeme Başkanı : Dosyada var. Ben hatırlayamadım da. Önemli değil.

Salim Güran : Her neyse Abdulsamet direğin üstüne çıktı. Öbürü de ot topluyor.

Mahkeme Başkanı : Hasan Hasan.

Salim Güran : Hasan ot topluyor. Topluyor. Ben de pamuğun içine dolaşıyorum. Pamuğu seviyorum. Hastalarına bakıyorum. Ondan sonra Abdulsamet indi. Salim dedi. Dedi amcan onunla konuş dedi. Vallahi üç buçuktan aşağıya ben bu arızayı yapmam dedi. Yok dedim ben niye arıyorum dedim. Sen ara dedim. Baktı o aradı. Pazarlık ettiler. Deme beş yüzü indirdi. Üç bine yapıyor. Ondan sonra dedi bine beni aradı amcam oğlu Mehmet Şerif. Dedi vallahi adı üç bine demiş yapıyor. Dedim bir şey olmaz. Üç binde bir şey olmaz dedi. Ne olacak? Baktı dedi bana bir tane uzun sırık lazım. Dedim burada uzun sırık. Sana nereden getireyim? E kalktık dedi sondajın yanına gidelim bizim barındığımız yere. Orada işinize yarayacak bir şey varsa getirirsiniz. Gittim oraya. Beraber gittik tabii. Ondan sonra orada indik bak işinize buldular. Onlar gittiler, ben onlarla gitmedim yani. Miran oğlum oradaydı. Miran oğlumu da aldım. Eve geldim.

Mahkeme Başkanı : Saat takriben kaçtı?

Salim Güran : Eve geldiğim zaman altı civarı falan.

Mahkeme Başkanı : Yani altıya geldi.

Salim Güran : He altı civarı falan.

Mahkeme Başkanı : Yani o zamana kadar tarladasın?

Salim Güran : Tabii tabii. Ondan sonra Hüseyin amcanın Hüseyin amcam Mersin'den gelmişti. Onu görmemiştim. Eve gittim bir cihaz vardı. Onu da aldım, arabaya koydum. Oğlum Miran dedi baba ben de geliyorum. E dedim sen de gel. Kalktık. Hüseyin amcanın yanına gittik. Fatma halam da gelmişti. Gittim ellerini öptüm. Onlar yandayken Ramazan Atasoy beni aradı. Abi dedi şüpheli bir araç var dedi yukarıda geldiğim yerde. Şüpheli bir araç var dedi. Ben de amca dedim vallahi böyle bir durum var. Hatta Osman yeğenim dedi amca dedi ben de geleyim yok dedim gelme dedim. Miran oğlumu da arabadan indirdim. Miran oğlum zaten kamerada gözüküyor. Patikadan yukarı çıkıyor. Ben de arabayla okulun yanından geçiyorum. Sokağın yanında geçerken Nevzat Bahtiyar ağaçlarının içindeydi. Ben ona selam bile vermeden geçtim gittim. İki buçuk üç aydır bu adamla ne oturmuşum, ne yemişim, ne içmişim, ne kahveye gitmişim. Yalan atmasın. Bu Arif'e musibetinden bu yana ne o beni arıyordu, ne yanıma geliyordu, biliyordum çünkü Arif'ten onun kalbini kırdı. Dedi vermiyorum bu parayı. Yoktur dedi. Arif dedi eşek gibi vereceksin dedi bu parayı dedi. Nasıl vermiyorsun dedi. Kekeke yapma dedi. Simsiyah oldu. Arif dedim. Ayıptır dedim. Sen niye bu kelimeyi söylüyorsun dedi. Hangi gün biz yan yana oturmuşuz Arif'ten bu yana. Yolun kenarından geçiyor. Niye? Madem ki biz samimi dostuz. Niye gelip yanımda oturmuyor? Her gün de geçiyor. Ben de geçiyorum. Vallahi ben selam da vermiyorum. Biliyorum artık kalbini kırmış Arif. E ona kırmış, bize de kırmış. İnşaat meselesine gelince zaten Arif öyle deyince açıkçası dedim ya dedim demiş ya param yoktur. Yahu dedim Nevzat dedim. Zaten bizim evini yapacağız. Feyzi diyoruz. Sıvayı yapacağız. Sen de sıvacısın. Dedim gel bu sıvayı yap. Babam dedim yirmi bin de ben kendim vereceğim. Diğerini de sen Arif'te kırk halde bir şey verecek. Sen de kırk tamam diyecek bu sekseni. Tamam dedi. Gitti eve baktı beni aradı. Diyor ya yüz elli demiş. Bana iki yüz dedi. On almıyorum yüz doksan dedi. Yahu dedim ayıptır adı adamlar. Ben Memduh kardeşime demiş yüz yetmiş beşe. Bari yüz yetmiş beşe yap dedim. Bak yirmi bin de ben veriyorum dedim sana. Vallahi dedim beni kurtarmıyorum. Kim yüz yetmiş beş demişse ona ver dedi. E o zaman ben dedim o yirmi bini de ben sana vermiyorum dedim. Kendisine dedim buradadır.

Mahkeme Başkanı : Evet. Bir dakika şu oturum kapalı diyor ya o şey gel hani. O kayıtlarda bir sıkıntı olmaz değil mi? Tamam.

Salim Güran : Olay günü tarladaydım.

Mahkeme Başkanı : Peki Narin'in kaybolduğunu ne zaman öğrendin? Ya da kaybolduğunu, ilk başta kaybolduğunu.

Salim Güran : Narin ben Hüseyin amcanın yanındayken 06:30 - 06:40 falan bilmiyorum yani ortalama diyorum. Saat dakikayı tam bilmiyorum. Telefon bana geldi ya Ramazan. Ben gittim zaten bizim eski muhtarın iki tane torunuydu. Bir tane beyaz Chevrolet orada tur atıyordu. Zaten karakolun kamerasında da gözüküyor. Dedim hayırdır, dedi vallahi biz şoför ehliyet alacak şoförlüğü öğreniyoruz. Ben de kalktım yine oraya gittim. Telefonu oraya gittim.

Mahkeme Başkanı : Tamam oraya gittin, Narin'in ne zaman öğrendin?

Salim Güran : Oraya gidince mi? Narin'i biz şimdi Narin'i biz gittik oraya. Saat altı süre altı kaç ediyor yani?

Mahkeme Başkanı : Süre altı buçuk. Tamam.

Salim Güran : Altı buçuk süre altı altı altı buçuk yedi arası.

Mahkeme Başkanı : Evet yedi arası.

Salim Güran : Ondan sonra biz şimdi ben durmuyorum. Benim ruhum durmuyor. Ben tarlada çocukluktan beri mısırın etrafında tur attım. Çıktım direğin üstüne fotoğraf çektim. Mısırın fotoğrafını çektim direğin üstünden. Mehmet Selim Atasoy'u aradım. O da geldi yanıma. Ondan sonra biz geldik. Tabii mısırı turluyoruz yani. Geldik yine soğutucunun yanına geldik. Telefon bana geldi. Gizem kızım beni aradı. Baba dedi Narin kaybolmuş dedi.

Mahkeme Başkanı : Gizem mi?

Salim Güran : Evet. Gizem kızım.

Mahkeme Başkanı : Ha tamam. Teyit etmek için sordum.

Salim Güran : Baba dedi. Narin kaybolmuş. Kızım dedim. Nasıl kaybolmuş dedim. Oralara bakın geliyorum dedi. Mehmet Selim Atasoy abi dedi dur ben de geleyim. İki tane oğluyla orada Ramazan diğer küçüğünün ismini bilmiyorum, hatırlamıyorum. Mehmet Selim Atasoy. Feneri de aldı. Artık akşamdı zaten. Feneri de aldı. Beraber evin yanına geldik. O arabayı oraya park ettim. Baktım köy halkı hepsi orada.

Mahkeme Başkanı : Sen o zaman öğrendin.

Salim Güran : Ben o zaman öğrendim. Yo telefon bana geldiği zaman. Geldim baktım vallahi ciddi. Kalktım Şakir Başçavuş'u aradım. Herkesten önce ihbardan önce de Şakir Başçavuş'u ben aradım.

Mahkeme Başkanı : Saat 20:18'de.

Salim Güran : Evet. Komutanım dedim bak böyle bir durum vardır. Kardeşimin kızı kayıptır dedim.

Mahkeme Başkanı : Tamam. Şimdi bu seninle bir şey öğrendik biz. Mahkeme heyeti olarak daha da bilmediğimiz bir şey. Telefonun ses kaydını konuşanları kaydetme. Bu sistemi neden indirdin telefonuna?

Salim Güran : Şimdi ben toplantıya gidiyorum bazen saati unutuyorum.

Mahkeme Başkanı : Tamam.

Salim Güran : Basıyorum. Saat kaçtadır? Ve hangi adrestedir? Onları kaydetmek için.

Mahkeme Başkanı : Peki sonra niye sildin ya? Asıl şimdi çok güzel bir şey söyledin. Dedin ki bende unutkanlık var. Doğru mu?

Salim Güran : Evet.

Mahkeme Başkanı : Bunun için ben. Şimdi siz köy muhtarısınız. Evet. Doğru mu?

Salim Güran : Evet.

Mahkeme Başkanı : Bir köyde özellikle bu coğrafya için konuşalım. 5 senedir bu coğrafyadan biri olarak da bu coğrafyayı öğrendim. Bir köyde muhatap asker içinde asker içinde polis içinde ondan sonra köy halkı içinde birinci muhatap sizsiniz. Doğru mu?

Salim Güran : Doğru.

Mahkeme Başkanı : Peki Narin kaybolduktan sonra asıl o program lazım. Biri arar sayın muhtarım falanca yerde buldum ben bunu kaydedesin. Ama sen 22.08'de o programı siliyorsun.

Salim Güran : O programı ben silmemişim. O programa ben karışmamışım. Zaten bana dediler.

Mahkeme Başkanı : Bakın. Sen bu asabi bunu karşı tarafta itiraz edebilir ama 22.08.2024. Saat 00:31. Gece on üç buçukta on üç, gece on iki buçuk. Yani Narin'in kaybolduğunun gecesinde.

Salim Güran : Evet.

Mahkeme Başkanı : Bu program devre dışı bırakılmış. Sekizden önce. Narin yirmi bir sıfır sekizde 21.08'de kayboluyor ya. Onun gecesinde saat 12'de gece yarısında programı devre dışı bırakmışsınız.

Salim Güran : Ben o programdan anlamıyorum.

Mahkeme Başkanı : Ya bakın Salim Bey ben Enes'e de dedim çok zeki bir çocuksun. Bir dakika dur. Ben gene herhalde haberlere düşeceğiz ama ben Enes'e de dedim. Çok zeki bir çocuksun. Sana da diyorum çok zeki bir adamsın. Tamam mı? Sen bununla bizim buradaki en az yarısını suya getirir, susuz götürürsün.

Salim Güran : Estağfurullah.

Mahkeme Başkanı : Yok. Bir dakika. Ben ne demek istiyorum? Şimdi sen telefonla bu programı kurdun. Ve bana dedin ki.

Salim Güran : Bana kuran kişinin ismini size dedim.

Mahkeme Başkanı : Ya önemli değil. Kurmuşsun ve bunu akıl edebilmişsin. Hani kaydetmeyi değil mi? Asıl o tarihten sonra işine yarayacak bu program. Niye siliyorsun?

Salim Güran : Duruyor. Ben o programla ekrandan silmemişim o programı.

Mahkeme Başkanı : Ama işte programın kendisi dijital rapora göre devre dışı bırakılmış program. Bakın ben şu an senin kayıtlarını okuyorum. Saat 20:01'de "Alo şahıs sen neredesin? Vallahi ben sondajın yanındayım. Geliyorum şimdi. Ne sesin gelmiyor? Diyorlar ki Arif kız mı ne kaybolmuş? Ne olmuş? Şimdi telefon ettireyim bana ben şimdi geliyorum." Bak bu programın kaydı. Akabinde komutanı arıyorsun.

Salim Güran : Tamam. Bunlar o günün saat 8'inde var.

Mahkeme Başkanı : Ertesi günün o gün gecesi programı iptal etmişsin.

Salim Güran : Programı ben devre dışı etmemişim.

Mahkeme Başkanı : Devre dışı bırakmışsın. Bu çok şüpheli bir hareket.

Salim Güran : Vallahi o programı ben iptal etmemişim. Yani ne varsa odur.

Mahkeme Başkanı : Bir dakika kayıt dondu.

Salim Güran : Asla.

Mahkeme Başkanı : Yok şey sistemde hata var.

Mahkeme Başkanı : Tekrar kayda başlıyorum. Bir şunu izah edeyim. Salim'in beyanlarına alınırken SEGBİS sisteminde bir donma olduğu için SEGBİS kaydı sonlandırıldı. Tekrar SEGBİS sistemine kayıt yapıldı. Eğer teknik çözüm yapılırken bu hususta bir eksiklik olursa iş bu husustaki eksikliği diğer kamerayla giderilmesi hususuna dikkat çekelim tamam mı? Ona dikkat edersin Geylani. Evet Salim Bey tekrar söylüyorum. Tekrar şu kamera kayıt telefon kayıt sisteminden bahsediyoruz. Sen kendin bilerek böyle bir şey silmedin, doğru mu?

Salim Güran : Yok.

Mahkeme Başkanı : O zaman bu sistemin nasıl devre dışı kaldığını bilmiyorsun. Peki bu olaylardan sonra yaklaşık 15 gün, 20 günden sonra bu sistemi kontrol etmek ihtiyacını hissetmedin mi? Yani bu sistemin devre dışı kalıp kalmadığını bilmiyor musun da?

Salim Güran : Bilmiyorum. Bazen de numaralar zaten kayıt da yetmiyordu. Şebeke çekmediği zaman demek ki.

Mahkeme Başkanı : Şey biraz. Arkadaşlar biraz daha sessiz.

[Bu esnada mahkeme başkanı, izleyiciler, mahkeme üyesi, baro başkanlarından biri ve katılan vekillerinden birinin dahil olması ve seslerin birbirine karışması nedeniyle sesler anlaşılamadı.]

Mahkeme Başkanı : Tamam. Evet. Tekrar başlıyoruz. Baştan alıyorum. Yani bu programı...

Salim Güran : Ben konuşmak istiyorum.

Mahkeme Başkanı : Tabii ki.

Salim Güran : Şimdi o programı ben anlamıyorum. Ben Cahit Kaya, kayınbabamın kardeşinin avlusunda oturmuştu. Onun oğlu Şeyhmuz Kaya bana indirmişti. Biz çay içerken aklıma geldi. Ya Şeyhmuz dedim. Bazen numara bu kayıt etmiyor ses kaydı. Dedi bana dediği şebeke çekmediği zaman kayıt ediyor. Bana öyle söyledi.

Mahkeme Başkanı : Ama işte ondan sonra senin telefonlarını şebeke çekmiş, sana ulaşmışlar. Yani sen bu programı bilerek ve isteyerek devre dışı bırakmadıysan bu programın çalışması gerekiyor.

Salim Güran : Yok.

Mahkeme Başkanı : Tamam. Tamam. Onu bilerek ve isteyerek devre dışı bırakmadığını söylüyorsun. Peki yine senden de ele geçen telefonlarda telefon görüşmelerini silmişsin. WhatsApp geçmişini silmişsin. Bunun sebebi nedir?

Salim Güran : Sebebi hayat kadınları da görüşmüşüm. Eskortlarla görüşmüşüm. Silmişim.

Mahkeme Başkanı : Şimdi şöyle onu silmemişsin ama. Eskortla mesajın duruyor.

Salim Güran : Bilmiyorum yani ben sildiğimi biliyorum.

Mahkeme Başkanı : Şimdi belki birden fazla eskortla görüştün. Onu bilemem ama şimdi böyle bir şey silmen gayet normal. Buna bir şey diyemem. Ama asıl silmen gerekeni silmemişsin. Eskort mesajları duruyor. Ben biliyorum. Dosyada var.

Salim Güran : Kim biliyor?

Mahkeme Başkanı : İşte yok. Yani asıl silmen gereken mesajlar dosyada dururken silmemen gereken rutin konuşmaları siliyorsun.

Salim Güran : O kadar anladım.

Mahkeme Başkanı : Bak bu da şüpheli bir hareket. Şimdi Salim Bey baştan tekrar söylüyorum. Benim nezdimde siz zeki bir insansınız. Tamam mı? Köyün muhtarı olmanız hasebiyle de soruşturmalara vakıf bir insansınız. Doğru mu? Diyarbakır'da bir soruşturma köy muhtarıyla yürütülür. Zaten başından beri de bu kayıp vakası sizin yönlendirmenizle yürütüldü. Oraya geleceğim. Tamam mı? Şimdi WhatsApp görüşmelerini siliyorsunuz.

Salim Güran : Evet.

Mahkeme Başkanı : Eskort için konuşmalarım açığa çıkmasın diye sildim diyorsunuz.

Salim Güran : Sildim çok.

Mahkeme Başkanı : Ama Eskort konuşmaları duruyor.

Salim Güran : Sildiğimi biliyorum.

Mahkeme Başkanı : Onu silmemişsiniz. Peki sizce Narin'i kim öldürdü?

Salim Güran : Ben görmemişim kim öldürdü.

Mahkeme Başkanı : Şimdi size bu soru sorulduğunda üvey annenizden biraz şüphelenmişsiniz. Doğru mu?

Salim Güran : Mesela.

Mahkeme Başkanı : Yok ben ilk başta şüphelendiğiniz kim var dendiğinde üvey anneniz, üvey kardeşlerinizi söylemişsiniz.

Salim Güran : Ben söyleyeyim hakim bey. Bir tane şey getirdiler. Bu ne diyorlar?

Mahkeme Başkanı : Büyücü mü?

Salim Güran : Büyücünün yok başka bir ismi var.

Mahkeme Başkanı : Muskacı? Ne bileyim burada ne diyorsunuz? Ne?

Salim Güran : Üfürükçü.

Mahkeme Başkanı : Tamam.

Salim Güran : Getirdiler. Getirdiler. Onların evinin etrafında, Nevzat'ın evinin etrafında diyor bu buralarda bir yerdedir.

Mahkeme Başkanı : Üfürükçüye siz gitmediniz mi?

Salim Güran : Üfürükçü geldi o ayrı. Onu da size söyleyeyim.

Mahkeme Başkanı : Ha bu başka üfürükçü. Bir de gittiğiniz üfürükçü var.

Salim Güran : Onu onu da ben söyleyeceğim.

Mahkeme Başkanı : Olur.

Salim Güran : Onu ben götürmedim. Beni güvenlik güçleri götürdü. Onların ismini de verebilirim.

Mahkeme Başkanı : Tamam. Ya verin ya, yani verin.

Mahkeme Başkanı : Söyleyeceğim. Ondan sonra yahu bir de Nedim Kaya Gazal'ın abisi yahu dedim ne diyeyim dedim vallahi ben bunu ben bundan çünkü ben böyle şeylere inanmıyorum. Yav Nedim dedim sen onunla uğraş dedim. Götürüyor getiriyor eve annemin evinin etrafında götürüyor getiriyor. Garajın etrafında götürüyor getiriyor. Şimdi o o şekil...

Mahkeme Başkanı : Ya inanmadığın bir şeyden niye şüphelenip de benim üvey annemi ben şüpheleniyorum dedin? Tamam. Ben şunu diyorum. Üvey annenden dahi şüphelenmişsin bak. İnanmadığın bir üfürükçünün hareketiyle üvey annenden de şüpheleniyorum diye jandarmaya söylemişsin.

Salim Güran : Doğru.

Mahkeme Başkanı : Ama yaklaşık 15-20 gün içerisinde Nevzat'tan şüphelendiğine dair hiçbir ibare yok.

Salim Güran : Şüphelenmedim. Ama benim jandarma beni çağırdığı zaman dedi sizin bir musibetiniz var mı? Yok dedim. Kimseyle bir musibetimiz yok. Ama dedi küçük de olsa söyle. Dedim küçük olursa Nevzat Bahtiyar'la var dedim.

Mahkeme Başkanı : İşte küçük. Küçük. Diye dikkat çekmedi mi diyorsun?

Salim Güran : E yani şimdi Nevzat Bahtiyar'la benim evimde o hareketi yaptıktan sonra ben bana dediler ki, biz sormuşuz Arif'e Arif demiş sorun yok. Paramı vermiş sorun yok. Arif'te bir şey yok.

Mahkeme Başkanı : Peki sen bu Birsen neyin oluyor senin?

Salim Güran : Amcamın kızı.

Mahkeme Başkanı : Amcanın kızı.

Salim Güran : Evet.

Mahkeme Başkanı : Melike de amcanızın kızı. Peki bunlara Narin'i saat 17:40'ta gördünüz diye beyanda bulun diye telkinde bulundunuz mu?

Salim Güran : Asla. Hepsinin ifadesini döverek değiştirmişler. Öyle bir şey yok.

Mahkeme Başkanı : Amcanızın kızı öyle diyor.

Salim Güran : Tamam. Ben amcamın kızıyla konuşmamışım ki. Ben niye ona söyleyeyim bu saatte söyle?

Mahkeme Başkanı : Peki niye jandarma onları dövsün de sana suç isnat etsin?

Salim Güran : Şimdi Hakim Bey bakın arabamda bir sürüntü diye bir şey.

Mahkeme Başkanı : Ona geleceğiz. Geleceğiz. Sırayla gidiyoruz. Evet. Yani şimdi jandarma onları dövüp de neden Salim'e bunu söyleyin dedirtti? Niye Salim?

Salim Güran : Beni gözaltından aldıktan sonra değiştirdiler.

Mahkeme Başkanı : Ya tüm köyü gözaltına aldıran niye Salim diyorum? Arif olur, Fuat olur, Erhan olur.

Salim Güran : Siz onlara sorun onu Hakim Bey.

Mahkeme Başkanı : Soracağım. Ama sana da sorayım. Onlar diyor ki Salim.

Salim Güran : Söylememişim.

Mahkeme Başkanı : Sen söylemedin.

Salim Güran : Söylememişim, konuşmamışım.

Mahkeme Başkanı : Konuşmamış. Peki yine jandarmanın tutmuş olduğu tutanaklarda senin sürekli onları başka yönlere yönlendirmen var. Bunu şüpheli hareket olarak.

Salim Güran : Ben kimim koskoca devleti yönlendireyim?

Mahkeme Başkanı : Yok.

Salim Güran : Beni sonra bırakmıyorlar bir araba. O indiriyordu, o bindiriyor.

Mahkeme Başkanı : Yok. Sen kimsin değil. Ben onu bunu söyleyeceğini bildiğim için. Evet. Ondan önce sen muhtarsın. Evet. Muhtarla soruşturmayı seninle yürütür diye girizgah yaptım. Ben kimim deme. Tamam. Yani o yeri bilen bir insanla soruşturma yapılır.

Salim Güran : Kim geliyordu muhtar? Kim geliyordu muhtar?

Mahkeme Başkanı : Tamam.

Salim Güran : Yemek yemiyordum.

Mahkeme Başkanı : Tamam. Evet. Ama neden sürekli jandarmayı şüpheli yani jandarmanın şüpheli hareketlerine yol açacak yerlere işte bir çingeneler var demişsin. Bir başka kırmızı araba var demişsin. Çingene biz Suriye çadırı var demişsin.

Salim Güran : Bunu da söyleyeceğim. Güçleriyle kaç tane kuyu var dedi. Kuyuları geziyoruz en son Hacı Mehmet Emin Kaya'nın orada baktım hepsi beraber fırladı gitti. Ne oldu? Hiçbir şey söylenmedi. Arabalar hızır hızır gidiyor. Dedim hayırdır beni de götürün dedi. Dedi yok dedi. Onlar gitti. En son bir tane transit yabancı yukarıda elimi kaldırdım dedim ya Allah'ım beni de götür bunlar bizimkiler hepsi nereye gitti? Gittim baktım çadırın orada çingenenin orada. Kim yönlendirmiş? Muhtar yönetmiş. En son duyan muhtar.

Mahkeme Başkanı : Şimdi efendim? Evet. İki tane çingeneden bahsediyorsun.

Salim Güran : İki tane çingene. E şimdi köy halkı ilk akşam kalabalık ya. Dediler vallahi iki tane çingene köyü girişinde sulama kanalının orada görmüşler diyor.

Mahkeme Başkanı : Kim, kim söyledi size bunu?

Salim Güran : Kalabalığın içinde birbirlerine söylüyorlar.

Mahkeme Başkanı : Siz de bunu jandarmaya ilettiniz.

Salim Güran : Yok jandarmaya iletmedim. Ne de jandarmaya?

Mahkeme Başkanı : Jandarma sizden duydu diye tutanak yazmış. Yani söylentiyi herkes biliyor. Köy halkı hepsi biliyor. Ha siz yani siz de muhtar olarak bir ileride bir şey söylüyor. Siz de bunu jandarmaya iletiyorsunuz. Kendi gördüğünüz duyduğunuz değil de. Birisi de diyor ki. Sadece söylentiyi.

Salim Güran : Muhtar Bey diyor iki tane çingene gördük diyor.

Mahkeme Başkanı : Sen jandarmaya söyledin.

Salim Güran : Köye gelmiş diye acaba o çingeneler mi bu çocuğu getirdi?

Mahkeme Başkanı : Ha sen görmedin, sana biri söyledi, sen de jandarmaya söyledin. Şimdi bu kabul etmediğimiz diğer şey iddia yani sanık müdafilerinin kabul etmediği HTS analiz raporu var. Bu analiz raporuna göre sen 15:19'da Arif Güran'in evinin çevresindesin. 15:20'de eve giriyorsun. Sen de dedin ki kesinlikle ben mısır tarlasındayım diyorsun. 15. Siz Arif Güran'in evine hiç girdiniz mi?

Salim Güran : Yok.

Mahkeme Başkanı : Olay günü Nevzat'ı hiç gördünüz mü?

Salim Güran : Olay günü saat altıyı kırk falan geçiyor sokakta geçerken ağaçların içindeydi. Kapı, kapının önündeydi. Böyle ona selam bile vermeden geçtim.

Mahkeme Başkanı : Altıyı kırk geçe bu peynir almaya gitmedi mi baldızın yanına?

Salim Güran : Ben Hüseyin amcanın yanında giderken okul kamerası da gözüküyor. O saatte gidince oradaydı.

Mahkeme Başkanı : Onu gördün, dikkat çekti ama selam vermedin.

Salim Güran : Selam bile vermedim.

Mahkeme Başkanı : Peki siz Arif'in evine hiç girdiniz mi?

Salim Güran : Yok.

Mahkeme Başkanı : Ama baz verilerine göre mutfak karşısındaki boş odaya kadar gittiğiniz iddia ediliyor.

Salim Güran : Bizim evimiz en fazla 30-35 metre yakındır zaten. Eğer benim bazım gidiyorsa üç tane telefon daha var evimde. Onların bazına da baksınlar.

Mahkeme Başkanı : Yani onların bazına niye bakıyorlar?

Salim Güran : O zaman onlar da oradadır. Ben evdeyim çünkü.

Mahkeme Başkanı : İşte evde değilim diyorsun ama.

Salim Güran : Yok ben evde dörde on on falan kala çıktım tarlaya gittim.

Mahkeme Başkanı : Tarlaya gittin.

Salim Güran : Bahtiyar'ın da bazını yazsınlar. O da tuvalette çıkar affedersiniz.

Mahkeme Başkanı : Dilek kızım kim?

Salim Güran : Kızımdır.

Mahkeme Başkanı : Dilek.

Salim Güran : Evet.

Mahkeme Başkanı : Yani kimlikteki ismi ne?

Salim Güran : Rezan.

Mahkeme Başkanı : Rezan. 15:39'da Rezan'la WhatsApp üzerinde bir konuşmanız var.

Salim Güran : Kızımdır, aramış.

Mahkeme Başkanı : Hatırlamıyorsun. 15:45'te de Rezan arıyor. WhatsApp'ın silinen verilerinden. Enes de 15:57'de sizin evinizde baz veriyor.

Salim Güran : Evimiz yakındır Hakim Bey.

Mahkeme Başkanı : Enes evinize geldi mi? Siz evden çıkmadan?

Salim Güran : Ben evdeyken gelmemiş.

Mahkeme Başkanı : Enes'in herhangi bir kızınızla ilişkisine şahit oldunuz mu?

Salim Güran : Kesinlikle. Ne olmuş, ne duymuş.

Mahkeme Başkanı : Sizin Yüksel'le bir ilişkiniz var mı?

Salim Güran : Kesinlikle bu şerefsizliği bu adiliği ben kardeşimin namusuna laf getirmem. Ben Salim Güran'ım. Hakim Bey ben kırk beş yaşımdaki kadın bir de kardeşimin namusu ben bu kadar alçak mıyım? Bu kadar namussuz muyum? Kardeşimin namusuna laf getireyim.

Mahkeme Başkanı : O zaman Narin'i kim öldürdü?

Salim Güran : Şimdi Hakim Bey siz bana diyorsa Narin'i kim öldürdü?

Mahkeme Başkanı : Ya tahminin var mı diye soruyorum ya.

Salim Güran : Şimdi Narin şimdi gözle görülen Nevzat Bahtiyar götürüp bu Narin'i gömmüş. Tamam. Nevzat Bahtiyar bu Narin'i sen mi öldürdün? Kim öldürdü? Erkek gibi çık söyle.

Mahkeme Başkanı : Bana, bana bakarak konuş da.

Salim Güran : Öbür dünyanın hesabını da yap. Cehennemin ateşinde yanacaksın sen.

Mahkeme Başkanı : Bana bakarak.

Salim Güran : Evet. Şimdi üç günlük dünya için ebedi dünyanı kaybetme. Adam gibi çık konuş.

Mahkeme Başkanı : İşte o konuştu, ben öldürmedim, ben cesedi aldım, sakladım diyor.

Salim Güran : Hepsi, hepsi oyun, hepsi yalan atıyor.

Mahkeme Başkanı : Ya şimdi Nevzat bu kadar bunları planlayabilecek sizin bakış açınızla bakıyorum. Bunları planlayabilecek kapasitede bir insan mı?

Salim Güran : Değil ama ben size söyleyeyim. Ben gözaltına alındım Hakim Bey.

Mahkeme Başkanı : Evet.

Salim Güran : Adam televizyonunda kendine dersini çalıştı.

Mahkeme Başkanı : Ama değil diyorsun. Hı? Değil diyorsun.

Salim Güran : Nasıl?

Mahkeme Başkanı : Ben dedim ki Nevzat bunları planlayabilecek kapasitede bir insan mı dedim, değil dedin.

Salim Güran : Ama televizyon söylüyor. Televizyonun önünde her şeyi ayarladı kendini.

Mahkeme Başkanı : Şimdi her şeyi ayarlayan bir insan. Şimdi bak. Her şeyi ayarlayan bir insan sana iftira atarken niye Yüksel'le ilişkin var deyip Yüksel'e de iftira atıyor?

Salim Güran : İftira atıyor Hakim Bey.

Mahkeme Başkanı : Neden? Sadece sana iftira atar. Ya kendini kurtarmak için sana sadece iftira atması daha mantıklı değil mi?

Salim Güran : Şimdi şimdi ben 8 yaşındaki Narin'i, bir meleği, kızımla farkı yok. Niye öldüreyim Hakim Bey?

Mahkeme Başkanı : İşte o iddiaya göre ilişkiyi gördüğü için.

Salim Güran : Yalan atıyor, Allah belasını versin. Yok öyle bir şey.

Mahkeme Başkanı : Yok öyle bir şey. Peki bu WhatsApp geçmişlerinizi, telefonları silmen. Evet. Bunları niye sildin?

Salim Güran : Ben Burada Hakim Bey. Şimdi ben size dediğim gibi sildim onu. En sonda hani ben dedim ya kolluk kuvvetleri beni üfürükçüye götürdü.

Mahkeme Başkanı : Tamam.

Salim Güran : Oradayken Arif kardeşimin ahırında 380 tane keleş mermisi yakalanmıştı. Vızır vızır arama WhatsApp telefon numarasıyla arıyorlar. O yüzden onu da sildim.

Mahkeme Başkanı : O yüzden onu da sildin. Aynen. O Mehmetoğulları neyiniz oluyor sizin?

Salim Güran : Efendi Mehmetoğlu. Ha?

Mahkeme Başkanı : Taner Mehmetoğlu falan var. O WhatsApp grubunda. O silahları kadınlara verin diye mesaj atıyor. İşte WhatsApp grubunda arama yapılacak evde silahları, mermileri kadınlara verin diyor.

Salim Güran : Grupta onlara bağlı değilim.

Mahkeme Başkanı : Haberin yoktur.

Salim Güran : Yok benim haberim yok. İlk defa duyuyorum Hakim Bey.

Mahkeme Başkanı : Narin WhatsApp grubu diye bir WhatsApp grubundan haberiniz yok mu? Yok.

Salim Güran : Kesinlikle.

Mahkeme Başkanı : Kesinlikle. Ben ne anlıyorum öyle bir şeylerden de. Sen bu baz verilerini kabul etmiyorsun?

Salim Güran : Kesinlikle.

Mahkeme Başkanı : Bu kadınların kavgasından haberin var mı?

Salim Güran : Yok. Yani onların söylediği sözler, tutukluydum.

Mahkeme Başkanı : Onların söylediği sözlerden bir haberiniz yok?

Salim Güran : Yok.

Mahkeme Başkanı : Çünkü onlar bir şeyler söylerken Erhan'dır, Fuat'tır, şey Erhan'dır değil mi? Ağzını kapatıyor kadınların, susun diyor, oraya ayırıyor.

Salim Güran : Bilgim yok Hakim Bey. Onu onlara sorun.

Mahkeme Başkanı : Onu onlara, onlara da soracağız. Size de bir soralım. Var mı? Tanıklara yönlendirme yaptın mı? Doğruyu söyleyin diyor. Tanıklara kendini kendini korumak için tanıklara şu şekilde beyanda bulunduğunu herhangi gibi sen söyledin mi?

Salim Güran : Kesinlikle hiç kimseye bu kelimeyi söylemedim. Hiç kimseye bir şey söylememiş. Hiç kimseye bir şey söylemedim.

Mahkeme Başkanı : WhatsApp konuşmalarını da sorduk. Telefonlarını sorduk. Telefonlarını neden getirmediğini sorduk. Olay günü Nevzat'ta bir sesli görüşmem var.

Salim Güran : Asla ben aramamışım. Asla.

Mahkeme Başkanı : 17:46'da gelen bir arama var. 41 saniye.

Salim Güran : Ben onu aramamışım WhatsApp'ta Hakim Bey. O da beni aramamış, konuşmamış. Asla.

Mahkeme Başkanı : Ya bakın her şeyi inkar etme hakkına sahipsiniz. Susma hakkına sahipsiniz. Ancak.

Salim Güran : Yok ben cevap vereceğim Hakim Bey.

Mahkeme Başkanı : İşte bu dosyada olan ciddi vahim bir iddia. WhatsApp verileri. Yani orada diyor ki 17:46'da arama var. Olay günü.

Salim Güran : Nevzat Bahtiyar mı beni aramış ben mi onu aramışım?

Mahkeme Başkanı : O seni aramış.

Salim Güran : Kesinlikle yok öyle bir şey. Kesinlikle.

Mahkeme Başkanı : Bu Vecdi ya da Vedat.

Salim Güran : Evet.

Mahkeme Başkanı : O konuda ne diyorsun?

Salim Güran : Bundan beri beni arıyordu. Ne yaptınız? Buldunuz, bulmadınız. Arıyordu beni.

Mahkeme Başkanı : Peki onunla konuştuktan sonra Nevzat'la konuşmaları var onun. Ona o, o sen değil.

Salim Güran : Konuşmamışım.

Mahkeme Başkanı : Ya sen onla Nevzat'a talimat yönlendirdin mi?

Salim Güran : Kesinlikle böyle bir şey yoktur. Şimdi yok öyle bir şey.

Mahkeme Başkanı : Çocuk kayıp. Tüm Tavşantepe Narin'i arıyor. Herkes Narin'i arıyor. Sen ise bu sırada fırsatını bulduğun kısacık bir vakit var. O vakit nedir? 22:47. Fırsatını bulduğun kısacık vakitte 22:47'de cesedin olduğu yere gidiyorsun?

Salim Güran : Kesinlikle gitmemişim.

Mahkeme Başkanı : Kesinlikle gitmedin. 22:55'te de oradan ayrıldığın iddia ediliyor.

Salim Güran : Köpek gibi 2-3 defa her yeri arıyorduk. Her yeri 2-3 defa arıyorduk.

Mahkeme Başkanı : Ama orada benim şahidimdir.

Salim Güran : Ben ilk akşam köyden çıkmamış.

Mahkeme Başkanı : Oraya bir arabanın gittiği de belli. Gece oraya şimdi Nevzat'ın kırmızı arabasının gittiğine kanaat getirdik ya. Ondan sonra kırmızı arabanın oraya gittiğine dair bir görüntü var. O kamerada da gece oraya bir arabanın gittiği görüntüsü var. Bu görüntülerde size HTS analiz baz raporuyla uyumlu olup 22:47'de senin cesedinin olduğu yere gittiğin görüntü var. Şimdi şöyle bak şunu söylüyorum. İddia rağmen de ilk iddiada oraya o tarihte bir arabanın gittiği iddia ediliyor. Bu arabanın ne olduğunu bilmiyoruz. Evet. Renault marka araba mıdır? Kırmızı araba mıdır? Bilmiyoruz. Daha sonradan dosyaya giren yaklaşık bir ay sonra dosyaya giren veride de senin oraya gittiğin var. Şimdi o zaman Diyarbakır Cumhuriyet Başsavcılığı sana bir kumpas kuruyor. Bir arabayla oraya giden biri var. Aa diyor dur o zaman bunu da Salim'e yıkalım. Böyle mi yapıyor?

Salim Güran : Hakim Bey ben oraya gitmemiş asla.

Mahkeme Başkanı : O zaman neden böyle bir iddiada bulunsun Diyarbakır Cumhuriyet Baş Savcılığı? Sen bu savcılığa ne yaptın da sana bu kadar iftira atıyorlar?

Salim Güran : Hakim Bey yani bana bırakmadılar, hakaret bırakmadılar.

Mahkeme Başkanı : Salim Bey bak bu iddiayı Yüksel'e söylememişler. Bu iddiayı Enes'e dememişler. Bu iddiayı Erhan'a dememişler. Diyorlar ki Salim gitti diyorlar.

Salim Güran : Kesinlikle.

Mahkeme Başkanı : Ya sen sen vatan haini misin?

Salim Güran : Asla.

Mahkeme Başkanı : O zaman vatan haini değilsen böyle bir iddiadan böyle bir sizin bakış açınızla bakıyorum. Diyarbakır Cumhuriyet Baş Savcılığı neden böyle bir iftira atıyor sana?

Salim Güran : Bilmiyorum, onlara sormak lazım.

Mahkeme Başkanı : Onlar da diyor ki, biz iftira atmıyoruz.

Salim Güran : O araba nereden geldi madem ki kamera yakalamış.

Mahkeme Başkanı : Gece vakti kamera yakalamış. Araba belli değil. Oradan zaten küçücük bir alanda giren bir araba, bilinmiyor. Gece vakti. Çünkü gece vakti.

Salim Güran : Benim köyde 3 tane tarlam vardır. Bir parça dereye yakındır zaten. Yaklaşık 300-400 metre yakındır.

Mahkeme Başkanı : Şimdi bu arabanızda çıkan DNA var. Tam şoför koltuğunun alt kısmında. Yani tam oturduğunuz yerde çıkan bir DNA var.

Salim Güran : Evet.

Mahkeme Başkanı : Bu konuda ne diyeceksiniz?

Salim Güran : O araba benim değil. Az önce Yüksel yengemiz dedi ya. Araba yeğenimin dedi. İmran'la beraber getirdik kapıya. Al dayı dedi sana devran kaza yapmış dedi. Araba Broadway doksan dört model Allah korusun az daha içinde ölüyordu. Dedi sen bunu kullan ben sattığım zaman bana verirsin. Tamam dedi. Kalktım 6-7 gün kullandım o arabayı. En son Çarıklı'da sondajcının yanında tamircinin yanında geldiler yanıma o İmran Berat'la Kurtuluş. Dayı dedi vallahi biz arabayı satmışız dedi. Ali'ye geldim dedi mi götürdü. İki günde arabasız kaldım. Mehmet Selim Atasoy'un motosikletiyle gidiyordu, geliyordu. Dolmuş ile gidiyordum geliyordum. En son Devran oğlum dedi, baba dedi Fuat amca Van'a gitmiş traktörün üstünde. Biçerin altında çalışıyor. Bunun arabasını çalıştıralım. Hadi tarlaya gidelim, gelelim. E çalışıyor mu dedim? Dedi çalıştıracağız. Kalktı elektrikçi geldi çalıştırdı. Ben Diyarbakır'a gittim ofiste istop ettim bir daha çalışmadı. Evet. Bir tane vatandaşla dedim geldi tavkı etti çalıştırdım. Geldim dedim, o elektrikçiye götürdü Çarıklı'da. Dedi aküsü şarjı bitmiş. Kalktı şarja koyduk. Bizim o araba da ustanın yanındayken de aradık. Bizim karşı Gönen'de bize oturuyor. Dedi ya o akü gelirken babam kendilerine getir. Bu Fuat'ın arabasının üstüne atar mı? Kendimize kullanırız. Zaten kapısı bozuk, penceresi bozuk. Her gün çocuklar biniyor. Benim çocuklarım da biniyor. Arif'in de biniyor. Fuat'ın da biniyor. Hepsinin çocukları biniyor zaten.

Mahkeme Başkanı : Tamam hepsinin çocukları biniyor da.

Salim Güran : O gün bile benim 4 tane kızın saçı açık. Biz Bağlar Sağlık Ocağı'nda çarşıda gidiyoruz.

Mahkeme Başkanı : Şimdi hepsinin çocukları biniyor da arabanın DNA'nın ele geçirildiği yer. Şoför koltuğu. Şimdi şöyle bir iddia var. Gene iddiayı söylüyorum. Bu Narin kızımızın ağzında köpük vardı ya. Köpük aktığını söylüyor Nevzat. O köpük senin eline bulaşıp sen de arabaya binerken bu şekilde o koltuğa silmiş olabilir misin?

Salim Güran : Kesinlikle.

Mahkeme Başkanı : Ya da battaniyeden, onu sordum. Battaniye ıslak mı diye? Islak değil dedi. Battaniyenin ıslak bir yerinden eline bulaşan bir tükürüğü arabaya silmiş olabilir misin?

Salim Güran : Hakim Bey böyle bir şey yok. Battaniye meselesi de nereden çıktı? Ben petrolden 200 TL yakıt aldım.

Mahkeme Başkanı : Evet. 200 TL.

Salim Güran : 200 TL. Orada bütün ailem arabada, eşim önde, çocuklarım hepsi arkada. Bir tanesi diyor orada gitmiş üç paket şey almış. Islak mendil.

Mahkeme Başkanı : Tamam.

Salim Güran : Yahu ben arabadan inmemişim. Bir tanesi demiş Narinin cesedi battaniyeye sarılı görmüş. Neler söylediler neler? Hepsi asılsız çıktı.

Mahkeme Başkanı : Asılsız çıktı derken?

Salim Güran : Yok öyle bir şey. Yok öyle bir şey.

Mahkeme Başkanı : Ben tamam sosyal medya. Tamam tamam tamam. Ben tamam ben tamam biz iddianame şey ya tamam hatırladım. Ben de ne olduğunu idrak edemedim. Hangi konuya temas ettiğini tamam şimdi anladım. Teşekkür ederim. Şimdi toparlayacak olursak, toparladıktan sonra hakimlerimize ve sayın savcıma söz verip devam edeceğim. İddianameye göre arabanızda DNA izi var. HTS baz verilerine göre Salim'in Arif'in evine girdiğiniz iddia ediliyor. Ve olay yerine olay yerinde gece 22 tekrar saatini söylemem gerekirse 22:47'den 22:55. 8 dakikalık da bir olay yerinde keşfiniz var.

Salim Güran : Kesinlikle yok öyle bir şey.

Mahkeme Başkanı : Bundan hiçbiri doğru değildir?

Salim Güran : Doğru değil.

Mahkeme Başkanı : Tanıkları yönlendirmediniz.

Salim Güran : Yok.

Mahkeme Başkanı : Kolluk kuvvetleri başından beri bu şey bulunmasın diye yanlış bir şekilde bir yerlere yönlendirmediniz. Yani yanlış işte kırmızı araba kesinlikle ben yönlendirmediniz. Siz yönlendirmediniz. Telefonunuzdan ses kayıt ses kayıt cihazını bilerek kapatmadınız.

Salim Güran : Yok kesinlikle.

Mahkeme Başkanı : Ondan sonra WhatsApp verilerini sildiniz ama eskort sehven kalmış. Tamam. Ben sormak istediğiniz bir şey var mı?

Mahkeme Üye Hakimi : Salim Bey ses kayıtlarının yani telefonunuzda ses kayıt cihazının olduğu ve bu nedenle de telefonunuzdaki ses kayıtlarının dosyaya girdiği sabit. Zaten böyle bir cihaz kullandığınızı da kayıt yaptığını da kabul ediyorsunuz. Telefon kayıtları, duyabiliyor musunuz şimdi?

Mahkeme Başkanı : Yok yok. Kayıt sadece.

Mahkeme Üye Hakimi : Bu kayıt mikrofonu. Biraz daha sessiz söyleyeyim o zaman. Telefonunuzda ses kayıt programı kullandığınızı bunu zaten sizin unutkanlık sebebiyle de kendinize yararlı olsun diye kullandığını söylemiştiniz.

Salim Güran : Tamam unutuyorum bazen ha.

Mahkeme Üye Hakimi : Bu programı kullandığınızda sabit olup dosya kapsamında da bu ses kayıtları dosyaya girmiş durumda. Bu kayıtlarda sormak istediğim iki husus var. Birincisi Ramazan Atasoy'la yaptığınız bir konuşmada siz diyorsunuz ki ifadenizde işte tarlanın orada şüpheli bir araç var. Araçtan bahsederekten size bilgi verdiğini ve uyardığını bu yüzden de sizin tarlaya gittiğinizi söylüyorsunuz. Ancak telefon kayıtlarına baktığımızda bir fıskiye yani tepedeki bir fıskiyeden ya da işte bir şey kaldığına dair bir çeviri söz konusu. Bu bahsettiğiniz telefon yani şu anki bahsettiğiniz ifadenizde geçen beyanlarla ses kayıtları örtüşmüyor. Tam olarak bunu bir açıklar mısınız?

Salim Güran : Şimdi bakın Hakim Bey ben dedim ya evden bir cihaz aldım. O cihazı da aldım Hüseyin amcanın yanına gelirken şimdi beni telefonu arayınca ben TEDAŞ ekibi zannettim. Ben kalktım gittim oraya. TEDAŞ ekibi değildi, muhtarın iki tane torunuydu. Ondan sonra Ramazan Atasoy'un yanına gittim. Bir tane cihazımız var. Haftada iki üç gün takıyoruz. Yoksa kurtarmıyoruz zaten çiftçiler. Elektrik.

Mahkeme Üye Hakimi : Yani bu bahsettiğiniz Ramazan mı konuşma bu cihaza ilişkin mi yoksa şüpheli araca ilişkin mi?

Salim Güran : Şüpheli araç söyledi zaten şüpheli araç var.

Mahkeme Üye Hakimi : Tamam. İkinci bir sorum daha var. Ses kayıtlarınızdaki bu dosya kapsamında bulunan konuşmalarda Narin on altıdan itibaren kayıp, Narin on altı otuzdan itibaren kayıp, Narin on beşten itibaren kayıp, Narin on yedi, on sekizden itibaren, on dokuzdan itibaren kayıp şeklinde yani 20:01'de başlayan telefon konuşmalarınızda 16'da başlayan kayıp saati 19'a kadar değişiyor. Yani her bir konuşmada bir yarım saat atmış neredeyse. Bunun sebebi nedir?

Salim Güran : Şimdi az önce Hakim Bey'den mesaj söyledi. Kalabalık bir tanesi diyor beş buçukta görmüş. Bir tanesi diyor beş kırkta görmüş. Bir tanesi diyor altıda görmüş. Bu ona dayanarak tamam.

Mahkeme Üye Hakimi : Yani ifadelerde beş kırk var. Maide Kaya'nın ifadesi var. İsa Kaya'nın ifadesi var. Bunlar hep ama hepsi beş buçuk sonrası. Dört nereden itibaren? Kimden duydunuz ya da?

Salim Güran : Konuşulanları ben söylemişim demek. Niye hatırlamıyorum onu? Bilmiyorum.

Mahkeme Başkanı : Nevzat sizi kaçta aramıştı? 15. Nevzat. 15:08.

Salim Güran : O su meselesi için beni aradı.

Mahkeme Başkanı : Ha bu doğru yani.

Salim Güran : Ha su meselesi için beni aradı. Dedi suyum gelmiyor. Eğer suyu gelmiyorsa zaten köyün belki on beş yirmi kişi kadın erkek hepsi beni arar. Ne hikmetse onun suyu tek gelmiyor. Komple su kulesinde bir boru tek bütün köye geliyor. Niye herkesin suyu geliyor? Niye onun gelmiyor?

Mahkeme Başkanı : Niye bundan şüphelenmedin de şimdi şüpheleniyorsun?

Salim Güran : Yok öyle şimdi böyle olunca ben dedim yani niye?

Mahkeme Başkanı : Ama sen her şeyden şüphelenen biz ona üfürükçüden..

Salim Güran : Tespit etsin onun suyu geliyor mu gelmiyor mu?

Mahkeme Başkanı : İşte Salim Bey üfürükçüden şüphelenen sen, bundan niye zamanında şüphelenmedin de Nevzat'ı bir araştırın demedin?

Salim Güran : Ondan başka da beni aramadı zaten.

Mahkeme Başkanı : Bak soruma cevap vermiyorsun. İnanmadığın üfürükçünün bir hareketinden şüphelenip de benim üvey annemi araştırın diyen sen, neden sudan şüphelenmeyip de Nevzat'ı araştırmıyorsun?

Salim Güran : Araştırmadım onu.

Mahkeme Başkanı : Bunlar şüphelenmedin yani. Üstüne Vedat da arıyor değil mi? Vedat da sürekli arıyor.

Salim Güran : Evet üstüne Vedat da arıyor. yani Vejdi Vedat arıyor. Buldunuz bulmadınız diyor.

Mahkeme Başkanı : Tabii şey bunlardan dolayı hiç Nevzat'tan şüphelenmedin mi?

Salim Güran : Ben bakın söyledim. Güvenlik güçlerine söyledim. Dedim Nevzat'ı arabanın arasında böyle bir musibet geçmiş.

Mahkeme Başkanı : Ya bakın senin Nevzat'la ilgili dosyada tek dikkat çeken detay kırmızı araba. Sen bir yerde bir kırmızı arabadan bahsediyorsun.

Salim Güran : Ben iki çingene kırmızı araba kesinlikle konuşmamışım. Yani böyle bir kişiyle mi konuşmuşum?

Mahkeme Başkanı : Konuşmak değil. Tutanakta jandarmaya bir iki yani çingenelerin kırmızı arabayla geçtiğini söylüyorsun. Tek Nevzat da, biz bizim ortak olarak yakaladığımız o kırmızı araba Nevzat'ın kırmızı arabası. Başka Nevzat'a dair bir iddian yok senin.

Salim Güran : O kırmızı arabayı ben bilmiyorum. Söylediğimi kesinlikle.

Mahkeme Başkanı : Ha biri söylediği için.

Salim Güran : Bir çingene söyleniyordu.

Mahkeme Başkanı : Söyleniyordu. Var mı hakim bey soru? Hakim Hanım soru? Sayın savcım sorunuz var mı? Buyurun.

## Duruşma Savcısı

Duruşma Savcısı : Salim Güran. Az önce sayın başkanımın söylediği bu kırmızı araba konusu senin döndürülen Kürtçe tercüme tutanaklarında var. Silinen ses kayıtlarında. Bir değil, iki değil, üç değil. Komutanlarla da görüşmen var. Kırmızı eski bir arabadan bahsediyorsun tamam. Böyle bir konuşman yok mu?

Salim Güran : Kesinlikle iki çingene kırmızı bir araba ben hatırlamıyorum.

Duruşma Savcısı : Peki bakalım. Tamam. 15:08'de Nevzat seni su için aradığında neredeydin?

Salim Güran : Evdeydim.

Duruşma Savcısı : Evdeydin. Ne kadar görüştünüz? 

Salim Güran : Gelmiyor dedi. İşte dedim tamam dedim.


Duruşma Savcısı : Arızayı giderebileceğinden oraya buraya ulaşacağından bahsettin. Peki resmi bir arama gerçekleştirdin mi suyun kesintisine dair?

Salim Güran : Yok.

Duruşma Savcısı : E bayağı evde kaldın 16'ya kadar.

Salim Güran : Yedim biraz da uzandım. Kendimi dinlendirdim.

Duruşma Savcısı : Yani su arızası gidermek için hiç aramadın kimseyi?

Salim Güran : Yok kimse beni aramadı, ben de aramadım.

Duruşma Savcısı : Nevzat seni aradı ya su için.

Salim Güran : Evet, o aradı başka kimse aramadı.

Duruşma Savcısı : Tamam, sen bunun üzerine bir aktivite gerçekleştirdin mi suyun tamiri için? Bildirdin mi?

Salim Güran : Yok yapmamışım.

Duruşma Savcısı : Tamam. Sana başkasının kurduğu bir program dedin değil mi, bu ses kayıt programını? O zaman kendin silmediğini söylüyorsun.

Salim Güran : Evet.

Duruşma Savcısı : Kurana mı sildirdin?

Salim Güran : Yok. Asla öyle bir şey yapmamışım.

Duruşma Savcısı : Yine getirilen ses kayıtlarında tercümeli tutanaklardan bahsediyorum. Badin diye birinden bahsediyorsun, Bahattin.

Salim Güran : He. Telefon tamircisi. Evet evet.

Duruşma Savcısı : Bir tuş tamiri için fazla teşekkür etmişsin adama.

Salim Güran : Bizim bu Ramazan'ın onun telefonu bozulmuştu. Aynen. Badin Karatay. Karamuz'dadır dükkanı. Ona verdi tamiri 900 TL'ye dedi yapacağım dedi. Onun önündeydi.

Duruşma Savcısı : Aslansın, kaplansın, helal olsun tamir ettiğin için falan diye söylemişsin.

Salim Güran : Çünkü 3-4 yere götürdüler yapmadılar. Ama o yaptı.

Duruşma Savcısı : O silmiş olabilir mi senin için o programı?

Salim Güran : Benim telefonum değil ki.

Mahkeme Başkanı : Sana yardım eden o Badin olabilir mi?

Salim Güran : Yok Değil. Yok kesinlikle. O Ramazan hatası onun telefonu belki hala da telefonu olmamıştı. Bilmiyorum.

Duruşma Savcısı : Yine baz bilgilerinden bahsederek gireceğim. Saat 22 civarı Narin'in, Narin kızımızın kaybolduğu akşamına doğru Dicle Üniversitesi'nin oradan bir bazın geliyor. Dicle Üniversitesi'nin orada birinin çay bahçesi varmış. Kim o biliyor musun? Sizden birinin Güran ailesinden bir işletilen bir çay bahçesi hatırlıyor musun? böyle bir şey? Var, var bir şey orada değil mi?

Salim Güran : Var, amcam Güran'ın var orada.

Duruşma Savcısı : İşte o bölgeden sizin bazınız geliyor. Kabul etmek zorunda değilsin. Ben sorumu soracağım. Devran Güran ve Muhammed Kaya'da Derik ilçesinden geliyor, Mardin Derik pardon. Oradan gelince oradan baz veriyorlar.

Salim Güran : Doğrudur onlar kart dağıtmaya gitmişler.

Duruşma Savcısı : Sizin aynı zaman dilimine denk geliyor bu. Bunlar iddialarım. Cevabını verirsin. Oradan geliyor aynı bazın. Neyse görüşme sağlandığını düşünerekten savcılık makamı olarak, görüşmediğini iddia ediyorsun. Oradan  gelmiyor.

Salim Güran : Yok.

Duruşma Savcısı : Öbür sabah Muhammed Kaya yeğeniniz değil mi? Dayısı oluyorsun.

Salim Güran : Evet.

Duruşma Savcısı : Muhammed Kaya'yı akşam gördün mü? Geldiler Derik ilçesinden ya.

Salim Güran : Tabii Muhammed'i gördük.

Duruşma Savcısı : Nasıl benim Dicle Üniversitesi iddiama yok dedin? Sonrasında tamam. Akşam Narin'in kaybolduğu gün Muhammed Kaya'yı gördün mü?

Salim Güran : Şimdi kalabalık bütün yeğenlerim hepsi oradaydı. Oradaydı.

Duruşma Savcısı : Anımsıyor musun? Anımsıyor musun? He? Anımsıyor musun?

Salim Güran : Yani büyük ihtimalle o da oradaydı. Bilmiyorum yani. Yüzlerce insan yani.

Duruşma Savcısı : Şimdi bu çingene iddiaları Suriyeli iddialarına ek olarak Muhammed'i de gördüğünü düşünerekten öbür gün sabah Muhammed Kaya bir terlik buluyor Suriye çadırının orada.

Salim Güran : Doğru.

Duruşma Savcısı : Doğru.

Mahkeme Başkanı : Tamam tamam. Lütfen müdahale yok. Sadece nezaket olarak. Soralım.

Duruşma Savcısı : Sorduktan sonra isteğinizi söyleyebilirsiniz. Sadece nezaket istiyorum.

Mahkeme Başkanı : Hah. Şey yok müdahale yok. Tamam avukat hanım. Avukat Bey. Evet sayın savcım buyurun.

Duruşma Savcısı : Ses kayıtlarında Çingeneli Suriye'den bahseden sensin. Bir gün sonra çadırın orada bir terlik bulunduğu iddiası var. Terlik bulunmuyor. Jandarma bulmuyor. Muhammed Kaya arabada bir buçuk saat saklıyor bu terliği ve bu terliği Suriyelilerin Suriyelilerin oradan bulduğunu iddia ediyor. Sen mi ayarladın bu işi?

Salim Güran : Kesinlikle böyle bir şey yoktur. Benimle ilgisi yok.

Duruşma Savcısı : Saat yine, bazdan. Cevap vermek durumunda değilsin ben iddiamı sunuyorum. Saat 22:44'te gece Narin kızımızın cansız bedenin olduğu yerden baz sinyali veriyorsun. Ve jandarma ve AFAD geldi. Baktın ortalık karıştı. Olay büyümeye başladı. O civarda gidip Nevzat Bahtiyar'ın ben çalı çırpı koymadım, tek taş koydum dediğinin üzerine üç taşı geri kalan iki taşı, özür dileyerek, geri kalan iki taşı ve çalı çırpıyı ekleyen sen misin?

Salim Güran : Kesinlikle. Bakın Savcı Bey, Savcı Hanım, bakın. O dere bir göl değil. O dere kilometre uzun bir deredir. Bir göl müdür? Ufak bir göl müdür orası? Sekiz defa aranan yerde ceset bulunmamış. O kadar sağlam saklamış. Ben mi gidip bulacağım?

Mahkeme Başkanı : Sen gitmedin zaten değil mi dereye? Tamam.

Duruşma Savcısı : Sayın Başkanımın az önce belirt diye DNA'yı kabul etmedin. Araçtan çıkan. Çocuğu biniyor. Ha benim çocuklarımın DNA'sını yazsın Fuat'ın DNA'sı her şey çıkmaz. Sana rapordan bir cümle söyleyeceğim. Araçtan çıkan DNA ile senin Narin'in kıyafetlerden çıkan DNA uyumlu. Anlatabildim mi bu cümlenin derinliğini?

Salim Güran : O gün Narin o arabaya binmemiş.

Duruşma Savcısı : Cümlenin derinliğini ben iletebildim mi? Başkasının saçı kılı değil Narin'in olay günü kıyafetlerinden çıkan DNA. Bir sıvı herhangi bir bulgu saç değil, Narin'in kıyafetlerinden elde edilen bir DNA.

Salim Güran : Kesinlikle o gün Narin o akşam arabaya o gün binmemiş. Çünkü araba bendeydi.

Mahkeme Başkanı : Zaten iddia makamının Narin arabaya bindi gibi bir iddiası yok. O ağzından tükürük oldu ya o tükürükten eline bulaştı. Arabaya sildi gibi bir iddiası var. Biz, yani iddia makamı değil mi sayın savcım? Arabaya bindi gibi bir iddianız var mı? Bu şekilde iddia makamının böyle bir iddiası yok. Arabaya bindi gibi iddiası yok. Senin elinden Narin'in ağzından çıkan köpüklerin....

Salim Güran : Yok öyle bir şey.

Duruşma Savcısı : Yani ben o gün rastgele binilebileceğinden değil de DNA Narin'in kıyafetlerinden çıkan olay günü oluşabilen bir bulgudan bu.

Mahkeme Başkanı : Arabaya binip binmediği değil.

Salim Güran : Ben o arabayı oraya bıraktıktan sonra artık o arabaya binmedim zaten.

Mahkeme Başkanı : Tamam. Yani iddiayı söylüyorum.

Salim Güran : Fuat kardeşim işten geldikten sonra araba sürüyor. Tamam. Ben yeğenlerimin arabasına binmek diğer kurtuluş kardeşimin arabasına bineyim.

Duruşma Savcısı : Gelen Mersin'den gelen amcanız Hacı Hüseyin'in yanından saat kaçta gittiniz?

Salim Güran : Saat 06:35 - 06:40 arası falan.

Duruşma Savcısı : 06:35 - 06:40 arası. Mehmet Selim Atasoy'un kızlarını götürdüğünüz iddiasını kaçta yaptınız?

Salim Güran : Ayın 20'siyle 21'ini karıştırıyorum.

Duruşma Savcısı : Karıştırdığınız için karıştırdığınız için aslında bir gün önce götürmüşsünüz öyle mi?

Salim Güran : Evet.

Duruşma Savcısı : Yani ama beyanda farklı vermiştiniz.

Salim Güran : Yani o stresle işte artık.

Duruşma Savcısı : Bu Mehmet Selim Atasoy beni aradı. Şüpheli bir araç var dedin. Hacı Hüseyin amcanın evindeydin. Değil mi?

Salim Güran : Evet.

Duruşma Savcısı : Hemen çıktın mı?

Salim Güran : Oturmuştum amcamın yanına.

Duruşma Savcısı : Aceleyle çıktım dedin az önce ya.

Salim Güran : Hatır istedim onlardan çıktım bitti.

Duruşma Savcısı : Hemen mi çıktın?

Salim Güran : Evet.

Duruşma Savcısı : Anında aradığı an.

Salim Güran : Aradığı an işte bir iki işte kaç çıktım yani odur.

Duruşma Savcısı : Mehmet Selim Atasoy seni 18:27'de arıyor. Sen okulun kamerasına 18:57'de takılıyorsun. Arada 30 dakika var.

Salim Güran : Mehmet Selim değil Ramazan Atasoy aramış.

Duruşma Savcısı : Mehmet Selim. Tamam aynı şey. Mehmet Selim adına kayıtlı. 1521 sonu. Değil mi? Aynen. Mehmet Selim Atasoy adına kayıtlı. Yani Ramazan Atasoy ben sana resmi belgeden konuşurum. Ramazan Atasoy. 18:27'de arıyor. Sen 18:57'de kameraya takılıyorsun. Hacı Hüseyin'in oradan o inerek.

Salim Güran : Amcamın yanında direkt.

Duruşma Savcısı : Anladım. 30 dakika var ama. 2 dakika yok. Miran'ı hemen önüne bıraktım dediğin. 30 dakika var.

Salim Güran : Çıktığı gibi ben gittim o zaman.

Duruşma Savcısı : Anlatabildim mi sorumu?

Salim Güran : Miran patikadan çıktı. Ben de oradan tarlaya.

Duruşma Savcısı : Tamam otuz dakika var orada. Hemen gitmiyorsun yani.

Salim Güran : Hiç bilmiyorum yani.

Duruşma Savcısı : Peki Sayın Başkanım. Teşekkür ederim.

## Diyarbakır Barosu

### Av. Aydın Özdemir

Av. Aydın Özdemir : Salim Bey, Devran Bey sizin oğlunuz Devran Güran.

Salim Güran : Evet.

Av. Aydın Özdemir : Siz Devran'a hiç köyde veya civarda bulunan kameraların yerlerini tespit et dediniz mi?

Salim Güran : Herkese demişim ne kadar kamera varsa hepsini tespit edin.

Av. Aydın Özdemir : Bunu niye siz yaptınız? Bir jandarma talimatı var mıydı elinizde? Kim size?

Salim Güran : Zaten ben hepsini tespit ettim. JASAT'a, istihbarata. Bir taneyi gösteriyorum. Bütün hepsini kameraları yolları arabadan iniyorum. Baktım bir tanesi. Kardeşim şimdi.

Av. Aydın Özdemir : Jandarmaya teslim ettiniz mi gelen konum bilgilerini? Yakup Tunç. Size konum gönderdi mi Devran aracılığıyla? Kameraların yerlerine ilişkin. Devran size gönderdi mi? Kameraların bulunduğu yerleri.

Salim Güran : Bir taneyi gönderdi.

Av. Aydın Özdemir : Peki siz bunu jandarmaya teslim ettiniz mi?

Salim Güran : Jandarmaya gönderdi.

Av. Aydın Özdemir : Size göndermiş ama değil mi?

Salim Güran : Ama jandarmaya da gönderdi.

Av. Aydın Özdemir : Size gönderdi mi?

Salim Güran : Yok. Dedim jandarmaya gönderdi.

Av. Aydın Özdemir : Size ulaşmadı hiç kayıt.

Salim Güran : Ben öyle biliyorum yani. Jandarmaya gönderdi dedim. Bana niye gönderiyorsun?

Av. Aydın Özdemir : Tamam. Bir diğer sorum şu. Sizin telefonunuzdaki imaj kayıtlarının içeriğine göre yapılan görüşmelerden biri şu. Vallahi en son karşıdaki ne diyorsunuz? Üç falan görmüşler. Üç otuz işte on beş otuzda. Yine birinde de üç otuz on dört gibi. Üç otuz yani on üç otuz dört gibi. On beş otuz on altı gibi. Narin'i görmüşler diyorsunuz. Yapılan görüşmelerde olayda Narin'in gerçekten kaybolduğu saatlere ilişkin bir veri veriyorsunuz. Bu görüşmeyi de saat hemen tam saatini söyleyeyim. 20:46'da yapıyorsunuz. 20:46'da yapılan bir görüşmede saat üç buçuk dört civarında Narin'in kaybolduğunu söylüyorsunuz. Siz o saati, nereden biliyordunuz bu saati? Narin'in o saatte kaybolduğunu?

Salim Güran : Onu bilmiyorum. Onu hatırlamıyorum.

Av. Aydın Özdemir : Hatırlamıyorsunuz.

Salim Güran : Jandarma erken geldi. Geldiği gibi dedi kamera. Dedim okulun kamerası var.

Av. Aydın Özdemir : Bakın aramalar saat 7'de başlamış.

Salim Güran : Sabri Kaçan geldi. Tabii okulun kamerasını açtılar.

Av. Aydın Özdemir : Yapılan görüşmede üç buçuk dörte bu çocuk kayboldu dediniz. Bunu nereden biliyorsunuz?

Salim Güran : Bilmiyorum onu ben hatırlamıyorum öyle bir şey.

Av. Aydın Özdemir : Yani köydeki bütün aramalar yani olay tutanaklarının tamamı saat 18:30-19:00'dan sonra.

Salim Güran : Hani söylentiler kimle diyordu biz ne söylüyoruz?

Av. Aydın Özdemir : Kim size bunu söyledi? Çocuğun üç buçuk dörte kaybolduğunu.

Salim Güran : Hatırlamıyorum.

Av. Aydın Özdemir : Hatırlamıyorsunuz. Biri söylemiş olabilir mi?

Salim Güran : Yani hatırlamıyorum.

Av. Aydın Özdemir : Peki Çingenelerin bu çocuğu kaçırmış olabileceğini nereden öğrendiniz? Kim size söyledi?

Salim Güran : Ben az önce Hakim Bey'e söyledim. En son giden benim. Oraya.

Av. Aydın Özdemir : Tamam ama konuşmalarda bakın. Çingenelerden, terliklerden çok net bilgiler veriyorsunuz. Kim size bu bilgiyi verdi? Nereden biliyorsunuz bunu?

Salim Güran : Bizim benim ailem ve bizim köy halkı gitti oraya.

Av. Aydın Özdemir : Köy halkından isim verebilir misiniz? Bana Çingenelerle ilgili bilgiyi bu kişi verdi diyebileceğiniz..

Salim Güran : Ben gittim oraya şahsen. Oraya gittim. Güvenlik güçlerinin yanına gittim. Çingenelerin...

Av. Aydın Özdemir : Tekrar edeyim. Çingenelerin Narin'i kaçırmış olabileceği bilgisini size akrabalarınızdan biri mi verdi? Nereden öğrendiniz?

Salim Güran : Hatırlamıyorum.

Av. Aydın Özdemir : Hatırlamıyorsunuz. Jandarmaya bu yönde bir bilgi verdiniz mi?

Salim Güran : Jandarma benden önce gitmişti.

Av. Aydın Özdemir : Herhangi bir tutanak yok dosyada.

Salim Güran : Yani o iki çingene söylenti var da onu demişsem bilmiyorum. Başka bir şey söylememiş.

Av. Aydın Özdemir : Peki. Nevzat bu olaylardan sonra yani birinci gün Narin kayboldu.

Salim Güran : Evet.

Av. Aydın Özdemir : Sizi hiç aradı mı sonrasında?

Salim Güran : Yok.

Av. Aydın Özdemir : Hiç aramadı mı? Yani yakalandığınız güne kadar hiç aramadınız. Beraber onu aradınız mı? Narin'i?

Salim Güran : O akşam onu fark etmemişim ama diğer gün köy halkı dedi gelin kapıları açıyoruz. Herkes gelsin. Biz akrabayız.

Av. Aydın Özdemir : Nevzat'la birlikte aradınız mı?

Salim Güran : Katıldı.

Av. Aydın Özdemir : Katıldı.

Salim Güran : Evet.

Av. Aydın Özdemir : Hiç görüştünüz mü bu süre içerisinde?

Salim Güran : Yok.

Av. Aydın Özdemir : Nevzat'la hiç konuşmadınız?

Salim Güran : Konuşmadık.

Av. Aydın Özdemir : Peki yani kendisi ifade verdi. "Otuz yıllık arkadaşım. Kendisiyle samimiyiz." Sorumu bitireyim sonra cevap verirsiniz. Bu kadar yakın birinin hiç en yakınınızdaki arkadaşınız sizin. Eşiniz de diyor ki "kardeş gibiydiler". Arif Bey de maktulün babası diyor ki "kardeş gibiydiler" lokanta restoranlara beraber giderlerdi" diyor.

Salim Güran : Yani iki defa iki ete götürmüşüm beraber yemek yemişiz.

Av. Aydın Özdemir : Bunu o demiyor. Arif Bey diyor ben şunu sormak istiyorum. Yani bu kadar yakın olan, bu kadar samimi olan birinin birlikte aramaması size tuhaf gelmedi mi? Niye ifadelerinizden hiçbirine?

Salim Güran : Şimdi akşam kalabalıktır. Belki aramalara katıldı. Ama gündüz aramalara katıldı. Evlerin içine giriyordu kendisi.

Av. Aydın Özdemir : Hiç gelip size destek dayanışma?

Salim Güran : Kesinlikle.

Av. Aydın Özdemir : Bulunmadı.

Salim Güran : Yok.

Av. Aydın Özdemir : Peki WhatsApp'tan geri getirilen bazı kayıtlar var. Arama geçmişiyle ilgili. Tam olay saatiyle senkronize yani olayın eylemin muhtemelen gerçekleştiği saatlerde hemen sonrasında Mehmet Güran, Mehmet Şerif Güran ve Nevzat Bahtiyar'la bazı görüşmeleriniz var.

Salim Güran : Mehmet Güran az önce söyledim zaten. O biz tarla konusunu konuşuyorduk. Nevzat Bahtiyar'la su meselesi için beni aradı.

Av. Aydın Özdemir : Mehmet Şerif Güran'la niye görüştünüz?

Salim Güran : O tarla okul meselesi. Elektrikçiler gelmişti, iki tane elektrikçi. iş.

Av. Aydın Özdemir : 16:43 ile 17:59 arasında. Yani 1 saatin biraz üzerinde bir süre boyunca.

Salim Güran : Doğru.

Av. Aydın Özdemir : Tam 5 kez 353 saniye boyunca görüşmüşsünüz.

Salim Güran : Doğru. Ben de az önce dedim kaç defa görüşmüşüz. Aramış.

Av. Aydın Özdemir : Bu süre boyunca tarlanın orada mıydınız? Kurulu olan tarla.

Salim Güran : Mehmet Şerif'in görüşmelerinde ben tarladaydım.

Av. Aydın Özdemir : Tarladaydınız.

Salim Güran : Evet.

Av. Aydın Özdemir : Elektrikçiler geldi, elektrikçilerle birlikte gittiniz.

Salim Güran : Evet.

Av. Aydın Özdemir : Peki elektrikçiler sizi sabah 11'de aramışlar. Bu çelişkiyi nasıl açıklayabilirsiniz?

Salim Güran : Beni aramamış. Çünkü ben onlardan haberim yok. Onlar geldiler de benim oraya, biz ben gördüm gelin dedim. Hayırdır dedim. Dedi Mehmet Şerif amcanoğlu. Dedi trafosu, he vallahi dedim, arızalıdır dedim.

Av. Aydın Özdemir : Sabah değil ama bu bahsettiğiniz öğleden sonra.

Salim Güran : Tabii tabii.

Av. Aydın Özdemir : Sabah elektrikçiyle hiç görüştünüz mü? Tarla başına gittiniz mi?

Salim Güran : Yok. Bilmiyorum. Hatırlamıyorum.

Av. Aydın Özdemir : Elektrikçi sadece sabah 11 gibi aramış sizi ve elektrikçi sizi ararken tarlanın başında değil köyde.

Salim Güran : O elektrikçiler geldiği zaman beni aramamış. Aramadan gelmişler. Benim için gelmemişler onlar.

Av. Aydın Özdemir : Peki kolluğun, kolluktaki yani jandarmadaki ifadenizde şöyle bir beyanınız var "Arif'in ahırında mermi bulununca ben WhatsApp kayıtlarını bu nedenle sildim".

Salim Güran : Arama.

Av. Aydın Özdemir : Tamam WhatsApp arama kayıtlarını bu nedenle sildim. Şu anda da diyorsunuz ki ben hayat kadınlarıyla görüştüğüm için sildim. Hangisi doğru?

Salim Güran : İkisi de doğrudur.

Av. Aydın Özdemir : İkisi de doğrudur. O gün eve gittiniz. Yani şehir merkezine alışverişe geldiniz. Alışverişiniz bittikten sonra aile üyelerinizle birlikte kendi ikametinize gittiniz.

Salim Güran : Evet.

Av. Aydın Özdemir : Ondan sonra dinlendiniz mi? Yemek yediniz mi?

Salim Güran : Evet.

Av. Aydın Özdemir : Yemek yediniz. Yemekten sonra da dinlendiniz ayrıca değil mi?

Salim Güran : Evet.

Av. Aydın Özdemir : Peki niye önceki ifadelerinizde böyle bir şey yoktu?

Salim Güran : Ben söyledim ya. Zaten 6-7 gün ne doğru düzgün yemek yedik. Bir ekip beni indiriyor diyor. Vallahi bir kese yemek getirdi tam önüme değil. Yemeden geldi. Kalktı. Beni yine götürdüler. Affedersin köpeği gibi birbirini elinden götürüp getiriyordular.

Av. Aydın Özdemir : Bunu ama savcılıkta sulh cezada da tekrar ediyorsunuz.

Salim Güran : Yani sulh cezayı da söyleyeyim. Sabah erken beni getirdiler buraya adliyeye. Yaklaşık bir buçuk saat..

Av. Aydın Özdemir : Özel müdafiniz de var. Özel müdafinin imzası da var.

Salim Güran : Bir dakika geç geldi. Bir buçuk saat yaklaşık beni o nezarette sidik kokan yerde. 6-7 saatte ayakta oturmasın diyordu.

Av. Aydın Özdemir : Bakın bu beyanınızın müdafiniz geldikten sonra bir süre sonra geliyor.

Salim Güran : O sonrada geldi. O yoktu ama zaten.

Av. Aydın Özdemir : Tamam. Bir sorum daha var. Bir sorum daha var. Bitireyim. Bir sorum daha var. Bitiriyorum. Siz hayat kadınlarıyla görüşürdüm dediniz.

Salim Güran : Evet.

Av. Aydın Özdemir : Peki yani eşim görür diye hiç endişe etmediniz mi? Telefonunuz evde miydi? Çocuklarınız eşiniz bakar mıydı telefonu?

Salim Güran : Ben evde konuşmam.

Av. Aydın Özdemir : Evde konuşmazsınız. Telefonunuzu kurcalamaz mı eşiniz?

Salim Güran : Şifre koymuşum.

Av. Aydın Özdemir : Şifre koymuşsunuz. Eşiniz hiç arama yapmaz mı telefonunuzdan?

Salim Güran : Yok.

Av. Aydın Özdemir : Hiç arama yapmıyor.

Salim Güran : Sadece ya Hediye'yi arar ya kız kardeşini arar. O da benim çocuklarım paralı numarayı böyle konuşur.

Av. Aydın Özdemir : Saat kaçta arıyor genelde? Eşiniz örneğin.

Salim Güran : İşi olduğun zaman arıyor ben ne bileyim.

Av. Aydın Özdemir : Teşekkürler.

### Av. Derya Yıldırım

Av. Derya Yıldırım : Salim Bey Narin'in kaybolduğu gün kaç defa üzerinizi değiştirdiniz?

Salim Güran : Elbise mi?

Av. Derya Yıldırım : Evet.

Salim Güran : Değiştirmedim.

Av. Derya Yıldırım : Şimdi biraz önce beyan verdiğinizde iki buçuk gibi eve geldik. Üzerimi değiştirdim dediniz.

Salim Güran : Yok elbise değiştirmemişim.

Av. Derya Yıldırım : Şöyle biraz önce beyan.

Salim Güran : Yok.

Av. Derya Yıldırım : Ha tamam pardon. Savcılık ifadenizde iki buçuk gibi eve geldik. Üstümü değiştirdim dediniz.

Salim Güran : Yok.

Av. Derya Yıldırım : Akabinde...

Salim Güran : Aynı o elbiseyle ben tarlaya gittim.

Av. Derya Yıldırım : Tarlaya gittim döndüm tekrar değiştirdim gibi bir ibare kullandınız.

Salim Güran : Yok elbisemi değiştirmemişim.

Av. Derya Yıldırım : Tamam. Diğer sorumu sorayım. Şimdi bir düğün olacak ondan kaynaklı bir davetiye dağıtımı yapılacak. Buna ilişkin herhalde bir görev dağılımı yapmışsınız. Kimin evinde yaptınız bunu? Ve kimlerle?

Salim Güran : Erhan ağabeydi. Arif'ti. Zaten Arif beni çağırdı. Gel işte bu kartları.

Av. Derya Yıldırım : Kimin evinde?

Salim Güran : Erhan ağabeyin evinde.

Av. Derya Yıldırım : Tamam.

Salim Güran : Ondan sonra üvey annemdi. Bir de her halkıydı. Başka karabalık kimse yoktu zaten.

Av. Derya Yıldırım : Anladım. Şimdi şöyle Arif Bey'in daha önce verdiği bir beyanda kendisi Hüseyin'in evinde ve Salim yok diyor.

Salim Güran : Erhan ağabeyin evinde.

Av. Derya Yıldırım : Tamamdır. Şimdi daha önce Eğertutmaz deresinde boğulan bir çocuk vakası oldu mu köyde? Ya da DSİ kanalına düşen?

Salim Güran : Duymamışım bilmiyorum.

Av. Derya Yıldırım : Peki neden doğrudan jandarma ekiplerini DSİ'ye yönlendirdiniz? DSİ kanalına?

Salim Güran : Köpekleri götürdü oraya.

Av. Derya Yıldırım : Tamam niye Eğertutmaz deresi değil de DSİ?

Salim Güran : Tamam köpekleri gitti evimizin arkasında girdi oraya. Üç dört gün biz kanalla uğraştık. Yetkilileri aradık, suyu kestik. Su kestirmeden biz suya giriyorduk, arıyorduk.

Av. Derya Yıldırım : Anladım.

Salim Güran : Köpeği götürdü biz.

Av. Derya Yıldırım : Peki şöyle bir şey tarladaki bir cihaz için  Ramazan Atasoy'u aradığınızı söylemişsiniz. Ramazan Atasoy beyanında herhangi bir cihaz için aramadığınızı söylüyor. Siz herhalde kaçak işlemi için bir cihazdan bahsediyorsunuz. Ama Ramazan böyle bir konuşma yapmadığınızı söylüyor.

Salim Güran : Bana dedi şüpheli araba var Ramazan'da.

Av. Derya Yıldırım : Şüpheli araba var derken?

Salim Güran : Ben de dedim belki TEDAŞ ekibidir o da dedi belki TEDAŞ ekibidir. Ben gittim baktım TEDAŞ değil. Oraya gittim.

Av. Derya Yıldırım : Bilgisi var mı o kaçaktan? Şöyle, telefon görüşmesi kendisine sorulduğunda kaçağa dair bir konuşma yapmadık. Bunun için aramadı dedi.

Salim Güran : Telefonda nasıl diyeceğim kaçak yapıyor?

Av. Derya Yıldırım : Cihaz soruyorsunuz ama cihazın buna dair olmadığını hatta tarlada böyle bir cihazın olmadığını beyan ediyor.

Salim Güran : Hüseyin amcanın yanına gittim. Oradan da yukarı gittim.

### Av. Nahit Eren

Av. Nahit Eren : Ben tam da avukat hanımın sorduğu aslında hakime hanımın da sorduğu ama bence hakime hanımın eksik sorduğu neden eksik sorduğu hakime hanım sizin ses kayıtlarınızın analiz raporuna göre fıskiyelerden bahsetti. Ramazan'la olan görüşmeyi ben bitireyim. Evet doğrudur ancak dosyada bir bilirkişi raporu var. Bilirkişi raporu çünkü o konuşma Kürtçe. Şimdi açıp zaten dinleyebiliriz. Orada ama Kürtçe yeminli bir tercümana çeviri yapılıyor. Fıskiye değil. Kürtçe'sini de söyleyeceğim. Türkçe'sini de söyleyeceğim. Saat 16:28'deki konuşma.

[devamında Kürtçe olarak söylenmiştir.]

Mahkeme Başkanı : Başkanım Türkçe'yi de çevirir misiniz?

Av. Nahit Eren : Var zaten çeviri var.

Mahkeme Başkanı : Siz de söyleyin. Siz de söyleyin Türkçe'yi.

Av. Nahit Eren : Zaten çevirdim.

Mahkeme Başkanı : Konuştuğunuzu bir de Türkçeye çevirin. Anlamayanlar vardır burada. O yüzden.

Av. Nahit Eren : Ben dosyadan direkt okuyayım size. Şu an. "Senin bir şeyin orada düşmüş" diyor. Ben de yani en son bentteki taşların arasında. Ben şimdi buradan okuyorum. Ramazan ha. Sona doğru senin sona doğru mesaj değil konuşma. Konuşma burada. Tamam. Konuşma. Diyorsun ki Ramazan. Ha efendim. Bu neyi biliyor musun? Birileri haber yaptı bunu. Dediler ki orada bir ölü var yerde. Hatırlıyor musun? Hayır ha bu televizyonu seyretmişsinizdir yani bundan öyle bir haber çıktı. Bu konuşma o aslında. Ne diyorsunuz? Sona doğru senin bir şeyin düşmüş. Sınırın orada. Sona doğru. Şimdi Kürtçe'sini söylüyorum. ''Kürtçe olarak söylenmiştir.''Ha. He sanırım orada senin bir şeyin. Sınırın orada, sınırda taşların orada. Ramazan diyor ki tamam ben şimdi gider alırım diye çevirmişler. Ben burada da dinletirim. Salonun yüzde doksanı Kürtçe biliyor. Ben bitireyim. Şunu hatırlatıyorum. Çünkü hakime hanım bunu fıskiye diye sordu. Siz de alet diye. Fıskiye burada fıskiye. Türkçe konuşuyor.

[Salim Güran ve katılan vekili Av. Nahit Eren birkaç cümle Kürtçe konuştu.]

Av. Nahit Eren : Burada, burada fıskiye yok. Senin bir şeyin düşmüş. Bendin orada taşların orada. Ben de soruyorum. Diyorum ki bu soruyu bu şekilde düzeltelim rapora göre dosyadaki rapora göre. Ve o Ramazan'ın da kabul etmediği sizin savunmalarınızda ifade ettiğiniz daha önceki savunmalarınızda ifade ettiğiniz ve savcıların da sonra Ramazan'a sorduğu bu konuşmadan siz herhangi bir kaçak elektrik için bir alet aldınız mı oradan bu konuşma üzerine? Diyor ki hayır benim böyle bir konuşmam yok. Böyle bir alete dair. Şimdi ben soruyorum. Sana ait olan bir şeyin düştüğü yerdeki şeyi al demekten kastınız olan şey nedir?

Salim Güran : Biz genellikle o kaçak aleti zaten tarafının orada taşların dibinde otun altına saklıyoruz. O olabilir başka bir şey yok. Ne diyeceğim Ramazan'a?

Av. Nahit Eren : Yani bu Narin'le ilgili bir sohbet değil. Şimdi bu düzeltmeyi yaptıktan sonra ben çok net bir size dair dosyadaki iddialarla birlikte oturup okuduğumuz zaman bütün ifadeleri şöyle bir sonuca varıyorum. Sorumuzu soracağım için bir ifadelerden yola gidiyorum. Delil üzerinden gidiyorum. Kendinizi kendinizi ilk bütün savunmalarınızda eve vardığınız 02:33'te Çarıklı'dan döndükten sonra eve vardığınız veya HTS kayıtlarına göre de 02:52'de çıktığınız evinizden saat 4'e kadar bir şekilde daraltılmış baz istasyonların olduğu yerin dışında bir yerde gösterecek bir kurgu içerisinde olmuşsunuz. Niye? Bir Hüseyin'lerin evine neden daha önce 02:30'da geldim gittim dediniz? Öyle bir beyanınız var. "Eve geldim, çocukları bıraktım, Hüseyin'lerin evine gittim". Bakın soru soruyorum. Niye? Niye Hüseyin'lerin evinin önüne gittin?

Salim Güran : 6'da gittiğimi 02:30'da 02:40'ta gittiğimi biliyordum.

Av. Nahit Eren : Bunun sebebi bu.

Salim Güran : Yani yok bir şoktaydık, yorgunduk.

Av. Nahit Eren : E ben de onu soruyorum.

Salim Güran : Evet.

Av. Nahit Eren : Bu ifadeyi verdiğin tarih olayın yaşandığı tarih değil. 29'undan bahsediyorum.

Salim Güran : Evet.

Av. Nahit Eren : Yani ikisinin sizin tutuklandığınız dönemden bahsediyorum.

Salim Güran : Evet.

Av. Nahit Eren : Orada bile ifadenizde diyorsunuz ki ben olaydan on gün sonra.

Salim Güran : Beni yatırmıyordular. Sabaha kadar uykusuz bırakıyorduk. İçme suyu vermiyordular. Ben de beyin mi bırakıyordular?

Mahkeme Başkanı : Sayın Başkan ben sorularıma devam edeceğim. Bir düzeltme de yapmak istiyorum. Hani bu konuda Diyarbakır Barosu'na ithamlarda olduğu için bu bir buçuk saat aşağıda beni beklettiğinizde reddetmişler dediniz ya ifade esnasında. Size atadığımız yedinci avukatı diye gönderebildik. Çünkü atadığımız her avukat sistem üzerinden reddetti, reddetti, reddetti avukat bulamadık.

Salim Güran : Yarım saat oturtamazlar mıydı?

Av. Nahit Eren : Ha onu bilemiyorum. Ama o bir buçuklukta. Ona bir şey demiyorum. Ama ben ben bir baro başkanı olarak yönetim kurulu üyesi arkadaşlarım burada sana sistemin atadığı her avukat görevi reddettiği için biz avukat gönderemiyorduk. Ve en son bir meslektaşımız kabul etti gitti ve özel avukatınız geldi.

Salim Güran : Ama niye oturtmuyor?

Av. Nahit Eren : Evet ben burada başkasının yaptığı fiili savunmak adına değil. Bu bir buçuk saatlik meseleyi bizden de kaynaklı avukatlar görevi kabul etmiyordu. Şimdi iki buçukta sen nihayetinde eve geldikten sonra çocukları bıraktıktan sonra ben Hüseyin'lerin evine gitmedim diyorsun. Burada hemfikiriz. Nereye gittin?

Salim Güran : Şeye, Ramazan'la biz konuştuktan sonra ben oradan Hüseyin amcaya gittim. Köyün içindeydi.

Av. Nahit Eren : 06:57'de yakalandığın okul kamera kaydında Hüseyin'lerin evinin önünden gittiğini ben de kabul ediyorum. 06:00-06:30'da gittin oraya.

Salim Güran : Evet.

Av. Nahit Eren : Daha önce bu bu o kurguyu iki otuza niye getirdin soruyorum. Ve diyorsun olayın şokuyla o saate getirdin. Tamam ben de soruyorum. Diyorum ki iki otuzda çocukları eve bıraktıktan sonra 02:52'de baz istasyonuna göre Arif'lerin o evinin aralığındasın. Çıkmadın mı?

Salim Güran : Evdeydim.

Av. Nahit Eren : Eşiniz yalan mı söylüyor? Evdeydim ya ben. Melike sizin eve geldikten sonra yemeğini yedikten sonra 10-15 dakika bir süreden sonra, pardon on beş on dakikalık bir süre kullanmıyor. Yemek yedikten sonra çıktığınızı söylüyor. Bu yalan mı?

Salim Güran : Yemek yedim ama bu saat kaçta çıktık?

Av. Nahit Eren : Ben de onu soruyorum. Kaçta çıktın evden?

Av. Nahit Eren : Saat dört olmadan bir 10-15 dakika kalmış ya da kalmamıştı. Yukarı sondaja gittin diyorum. Elektrikçiler geldi diyorum.

Av. Nahit Eren : Bugüne kadar yukarıya elektrikçilerden önce de gidip Uzunbahçe Köyü'ne kızları bıraktığını söyledin. Şimdi ben senin o aralıkta hayır hayır hayır bakın Salim Güran ben neyi soruyorum? Şimdi diyorsun ki ben dörde kadar evdeydim. Değil mi? Biz sen daha önce bugüne kadarki bütün ifadelerinde o süre zarfı içerisinde Hüseyin'lerin evinde Uzunbahçe Köyü'nde oradan gelip elektrikçilere hatta daha başka bir şey söyleyeyim kayınbabanın çiftliğinde Ramazan'la birlikte. O gün gittin mi? Ramazan'la.

Salim Güran : Çiftliğe mi?

Av. Nahit Eren : Çiftliğe o gün.

Salim Güran : Ramazan'la gittik.

Av. Nahit Eren : O gün gittin. Ben işte o zaman şu kurguyu beraber kuralım. Sen evden saat dörtte çıktın. Dörtte çıktıktan sonra nereye gittin ben soruyorum.

Salim Güran : Bak konuşayım. Ayın 20'sini 21'i söylüyorum ayın. Biz onun kız kardeşini bıraktıktan sonra geldik, oradan çiftliğe geçtik.

Av. Nahit Eren : Bu ayın 21'inde Narin'in kaybolduğu günde olduğumu olmadı.

Salim Güran : Ayın 20'sinde oldu diyor.

Av. Nahit Eren : Ayın yirmisinde oldu. Ben de tamam onu ayın yirmisine götürdük. Evet. Zaten başlarken söyledim. Bir şekilde yapmış olduğunuz insanların tanık olduğu fiillerin hepsini ben okuduğum zaman sizin savunmalarınız. Sizin ifadeleriniz. Hepsini olay günü saat on iki on dört otuzdan on altıya kadar sıkıştırmışsınız hepsini. Ben de o yüzden size soruyorum. Eğer bunlar iki gün öncesi yirmi de değil on dokuzunda. On dokuzunda Uzunbahçe Köyü'ne o iki kızı götürmüşsün. Çünkü bu çıktı HTS kayıtlarından çıktı. Çünkü Ramazan'da kabul etti. Şunu soruyorum. Şimdi bunu tamam. Şimdi bize o gün ne yaptığını o zaman bugüne kadar söylediğin bütün ifadeler yanlış o zaman senin. Şimdi bize ne yaptığını saat saat hatırladığın kadarıyla. Anlat.

Salim Güran : Dedim mesela kız çarşıdan gelirken...

Av. Nahit Eren : Eve geldik. Evden yemeğini yedin. Sen eşin diyor ki yediği gibi çıktı. Tarlaya gidecekti.

Salim Güran : Biraz dinleneyim.

Av. Nahit Eren : Ama sen bir az evvel bir saat söyledin. Dörte çıktım dedin.

Salim Güran : Dört olmadan çıktım.

Av. Nahit Eren : Dört olmadan çıktın. Ne yaptın? Onları bir daha dinleyebilir miyiz başka? Ne yaptın?

Salim Güran : Karakoç ile Tavşantepe Arasındaki sondajıma gittim.

Av. Nahit Eren : Yani Uzunbahçe'ye gitmedin.

Salim Güran : Bir oraya gittim. Oraya orada elektrikçiler geldi. Elektrikçiler geldi. Ramazan bir de öbürünün ismini hatırlamıyorum.

Mahkeme Başkanı : Hasan Hasan.

Av. Nahit Eren : O gün çiftliğe de gitmediniz. Ramazan'la gittiniz mi çiftliğe?

Salim Güran : Vallahi çiftliğe yani...

Av. Nahit Eren : İstikrarlı bütün ifadelerinizde var. Yaklaşık bir 7-8 tane, pardon 6-7 tane ifadeniz var.

Salim Güran : Gitmiş olabiliriz gitmemiş olabiliriz de yani onu tam emin değilim. Çünkü o da ayın 20'sinde olabilir.

Av. Nahit Eren : Tamam. Ramazan'dan sondajın orada daha önceki bütün ifadelerinde Mehmet Selim Atasoy'u arayıp gelmesini istediğini söyledim.

Salim Güran : Evet.

Av. Nahit Eren : Mehmet Selim Atasoy sizin yanınıza saat kaçta geldi?

Salim Güran : O biraz geç geldi çünkü ben o geldiği zaman ben saat altı kaçta giderken.

Av. Nahit Eren : 16:30.

Salim Güran : O daha yeni geldi.

Av. Nahit Eren : Yani sen saat 16, Ramazan'ın ifadesine göre 16'da sondajın olduğu yerde seninle birlikteyken Mehmet Selim'in sondaj bölgesine geldiği anı hatırlamıyor musun?

Salim Güran : Yok, bak ben sana diyorum saat 6'da falan ben gittim. O da benden sonra geldi.

Av. Nahit Eren : Saat 18'de mi geldi Mehmet Selim Atasoy? Aşağı tarlaya kaçta gitti?

Salim Güran : Aşağı tarlaya mı?

Av. Nahit Eren : Evet.

Salim Güran : Ben gitmedim orada kaldım.

Av. Nahit Eren : Sen gitmedin. Mehmet Selim Atasoy Çarıklı'yla Tavşantepe Köyü arasındaki bu tarla mısır tarlası.

Salim Güran : İki parçadır. İki parça aşağıda.

Av. Nahit Eren : Buraya buraya saat kaçta gönderdin onu?

Salim Güran : Ben göndermemişim. O gitmiş.

Av. Nahit Eren : Kendisi. Hayır hayır kendisi ifadesini sana söyleyeyim. Saat 16'da geldiğini söylüyor. Sen ve Ramazan'ın pardon 18'e doğru, on altı on altı gibi. Orada çünkü sen baz istasyonu verilerine göre doğrudur saat dört ondan itibaren yukarı tarlaya gittin. Bir müddet sonra Mehmet Selim geldi. Mehmet Selim Atasoy'u nereye gönderdiniz? Su yönünü değiştirsin diye mısır tarlasına gönderdiniz.

Salim Güran : Onu hatırlamıyorum. Nereye göndermişim hatırlamıyorum.

Av. Nahit Eren : Mehmet Selim seninle bu konuşmaları yaptığı zaman 16:28'de bir aracın patinaj yaptığını söylüyor. Nerede? Ses kayıtlarını açabilir miyiz başkanım? Salona verebilir miyiz?

Mahkeme Başkanı : Tabii ki. Teknik ve arkadaşlar yapabilir miyiz? Tamam.

Av. Nahit Eren : Saat 16:28'de.

Mahkeme Başkanı : Hatırlıyor mu ama? Hatırlamıyorsa hatırlıyor mu bu?

Av. Nahit Eren : Hayır kendi konuşması ses kaydı. Telefondaki ses kayıtlarını inkar ediyor musunuz?

Mahkeme Başkanı : Yok hatırlıyor mu diye soruyorum.

Av. Nahit Eren : Telefondaki ses kayıtlarını inkar ediyor mu?

Salim Güran : Atasoy mu diyor araba patinaj çekiyor?

Av. Nahit Eren : Bir aracı bir tekerleği çıkaramıyoruz diyor. Uğraşıyorum uğraşıyorum teker çıkmıyor diyor.

Salim Güran : Ayın kaçında bu olmuş?

Av. Nahit Eren : Aynı gün Narin'in kaybolduğu gün.

Salim Güran : Bilmiyorum.

Av. Nahit Eren : Ses kaydı var açabiliriz. Dosyada var.

Salim Güran : Ona sor.

Av. Nahit Eren : Telefonda ay ben sana soruyorum öbür tarafta sen varsın konuşuyor.

Salim Güran : Ben mi aramışım demişim bir teker patinaj ediyor?

Av. Nahit Eren : O söylüyor sana.

Salim Güran : E hatırlamıyorum.

Mahkeme Başkanı : İnkar etmiyor, hatırlamıyorum diyor. Yani inkar olsa ses kaydını açarız da hatırlamıyorum diyor.

Av. Nahit Eren : Şimdi benim benim varmak istediğim yer neresi? Bu bahsi geçen çünkü sorumu net soracağım sana. On altı o bahsettiğimiz saat bahsettiğimiz saat yani Mehmet Selim Aksoy'un yanlarına gelip aşağı tarlaya gittiği zaman bana göre dosya içerisindeki bilgilere göre sizin ifadelerinize göre oraya giden Nevzat'ın gözcüsü mü? Mehmet Selim Aksoy.

Salim Güran : Asla öyle bir şey yok. Kesinlikle. Asla.

Av. Nahit Eren : O tarlaya sen göndermedin yani.

Salim Güran : Ben onları sulamacı tutmuşum. Ben gidiyorum yanlarına yine ben orada oturmuyorum onlara yardım ediyorum.

Av. Nahit Eren : Ben bunu uydurmuyorum. Kendi ifadesinde geldiğine sizi gönderdiğiniz söylüyor.

Salim Güran : O kendini yönlendiriyor. O kendi sulamasını yapıyor. Ben gittiğim zaman onlara yardım ediyorum. Mehmet Selim neresi sulamış neresi sulamamış biliyor. Ben nereden bileyim? Ben gidiyorum yardım ediyorum ona.

Mahkeme Başkanı : Tamamdır.

Av. Nahit Eren : Buyurun. Bu soru tamamdır. Sana sordular. Ben bir kez daha net bir şekilde soracağım. Bir açıklama da yapacağım. Baz istasyonu çünkü sanık avukatları da aynı değerlendirmeyi yaptı. Çünkü ben iddia makamıyla birlikte bu baz çalışmasının ne olduğunu ifade edeyim. Belki ona göre daha sağlıklı hatırlarsın. Eğertutmaz deresiyle birlikte sizin köy, Tavşantepe köyü Diyarbakır'ın hem Sur, hem Bağlar, hem komşu köylerden baz alan bir yerinde. Dikkat edin, incelediniz mi bu baz istasyonu kayıtlarını? Daraltılmış baz istasyonu raporunu inceleyebildiniz mi?

Salim Güran : Ben incelememiştim.

Av. Nahit Eren : Hiç bakmadınız. Evinizle Arif'in evinin içerisinde ya da o bölgede attığınız her adımda baz istasyonlarının değiştiğine dair veriler var orada. Şunu bize söylüyor baz istasyonu. Ben bu köyde kim nasıl hareket ederse hangi baz istasyonuna yakalandığında konumunu tespit edebiliyorum. Aşırı baz olması vesilesiyle herkesin hareketini kontrol ediyor. Ben de bu baz istasyonunun verileri dosyada bir delil olduğu için bunun üzerinden sana soruyorum.

Salim Güran : Ben ne olduğunu bilmiyorum. Ama eğer Nevzat'ın bazı oradaysa, eğer benim bazım oradaysa, Enes'in bazı oradaysa, o zaman bütün benim aile bireylerinin, Nevzat'ın aile bireyleri, yakın komşuların hepsi oradadır o zaman. Nasıl gidiyor oraya? Gitmediğimiz bir yere nasıl bazımız gidiyor?

Av. Nahit Eren : Ben dosyaya gelen rapora, ben rapora göre söylüyorum. Ben rapora göre soruyorum, soru yani bunu açıklayıp sorumu soracağım. Bu baz verisine göre bu baz verisine göre sen saat 14:52'de kendi evinden çıkıyorsun.

Salim Güran : Tamam.

Av. Nahit Eren : Kendi evinden çıktıktan sonra doğru mu değil mi diye cevaplarsan daha sağlıklı ilerleriz. Çıktıktan sonra o ara yoldan Arif'lere doğru gidiyorsun. Arif'in evine gidiyorsun. Arif'in evine saat 15:20'de giriyorsun.

Salim Güran : Yok öyle bir şey.

Av. Nahit Eren : Hele baza göre giriyorsun. Çıkıyorsun. Bir daha giriyorsun.

Salim Güran : Kesinlikle ben caddenin öbür tarafına geçmemişim. Arabayla binmişim, dönmüşüm, gitmişim.

Av. Nahit Eren : Sen saat dörtte mi evden çıktın o zaman?

Salim Güran : Vallahi tam hatırlamıyorum yani dört gibi. Dört olmamış.

Av. Nahit Eren : Bu bazı kabul etmiyorsun. Bu bazı kabul etmiyorsun. Evdeydin. Peki çok güzel. Sorum şu. WhatsApp kayıtlarınıza ilişkin arama kayıtları dosyaya girdi.

Salim Güran : Evet.

Av. Nahit Eren : Rapor olarak. Yani sizin o sildiğiniz WhatsApp'lar var ya.

Salim Güran : Evet.

Av. Nahit Eren : Arkadaşım az evvel sordu. Ben onu size birazdan akşamki görüşmelerde soracağım. Saat dörde kadar evde olduğunu kabul ediyoruz. Çocuklarının hepsi evde miydi? Kızlarının isimleri neydi?

Salim Güran : Devran evde değildi.

Av. Nahit Eren : Devran dereye gitmiş.

Salim Güran : Dilan'da ben istirahat ederken o teyzesigilden oradan sondaja gitmişti. Benim kızlarım evdeydi.

Av. Nahit Eren : Yani Dilek diye kayıtlı Rezan. Resmiyetle Rezan, Rojin ve Gizem evdeydiler. Saat 15:39. Bize göre, iddianameye göre, baz verilerine göre Ramazan'ın evden çıktığı 15:36'dan sonra. On beş otuz dokuzda Dilek'i arıyorsun. Dilek'le 16 saniye konuşuyorsun. Saat 15:45'te bu defa Dilek seni arıyor. 7 saniye konuşuyorsunuz. Dilek'le aynı evin içerisindeyiz. Birbirinizle telefonla mı görüşüyorsunuz?

Salim Güran : Hatırlamıyorum, bilmiyorum. Hatırlamıyorum.

Av. Nahit Eren : Sen saat 15:39 ve 15:45'te Dilek'le hiçbir görüşme yapmadın.

Salim Güran : Dilek'le numaralar aynı mıdır?

Av. Nahit Eren : Ben sana numaralarını söyleyeyim. Dilek 0531XXX1421. Bu bununla WhatsApp üzerinden saat 15:39'da arıyorsun Dilek'i. 6 dakika sonra 15:45'te bu defa Dilek seni arıyor. Bu bu defa da 7 saniye konuşuyorsunuz.

Mahkeme Başkanı : Bir dakika devam edin. Bir bir şey yapmam gerekiyor. Devam edin başkanım.

Av. Nahit Eren : Başkanım sizin de duymanızı istiyorum ama.

Mahkeme Başkanı : O zaman bir 30 saniye izin verir misiniz? Buyurun. Kusura bakmayın.

Av. Nahit Eren : Bu iki görüşmeyi yaptın mı yapmadın mı?

Salim Güran : Bunu hatırlamıyorum.

Av. Nahit Eren : Hatırlamıyorsun.

Mahkeme Başkanı : Şu başkanım şunu yaptım. Dinleyeceğimiz tanıkların hazır edilmesi için en azından beş altı tanığı.

Av. Nahit Eren : Bugün dinliyor muyuz tanıkları?

Mahkeme Başkanı : Allah'ın emriyle gidiyoruz. Sabaha kadar buradayız.

Av. Nahit Eren : Başkanım bir saniye buradan kopmayalım. Bir daha soruyorum. Saat 16. Başkanım ben ne zaman şey olsam benim konsantrasyonumu bozuyorsunuz. Vallahi billahi var ya kopuyorum.

Mahkeme Başkanı : Tabii herkes bir sakin olsun. Yani daha tanıkları dinleyeceğiz. Çıkmak isteyemezse Salim'in beyanından sonra çıkartırız. Buyurun Nahit Bey.

Av. Nahit Eren : 15:39 ve 15:45'te kızlarınızla görüş kızınla görüşme yaptığını hatırlamıyorsun?

Salim Güran : Hatırlamıyorum ya. Ne hatırlayayım.

Av. Nahit Eren : Hatırlamıyorsun.

Salim Güran : İki ay geçmiş. Ne bileyim ya? Ne görüştüğümü?

Av. Nahit Eren : Olay günü.

Salim Güran : Hatırlamıyorum.

Av. Nahit Eren : Ama aynı evin içindesiniz. Kızların da saat 4'te çıktığını iddia ediyor.

Salim Güran : Ya hatırlamıyorum, sana diyorum.

Av. Nahit Eren : Ben ne bileyim? Böyle bir görüşme yaptın yapmadın mı?

Salim Güran : Hatırlamıyorum sana diyorum.

[Katılan vekilleri tarafından yükselen sesler birden fazla kişi olması nedeniyle sesler ayırt edilemedi.]

Av. Nahit Eren : Yani peki bir şey daha soracağım. Alışverişinizi yaptınız. Hediye pardon eşiniz. Melek. Biz geldik yemek yedik. Evinizde o gün ne yediğinizi hatırlıyor musunuz?

Salim Güran : Ben genelde kahvaltılık yerim. Bana kahvaltılık kesin hazırlanmıştır.

Av. Nahit Eren : Kızlarınızla beraber yediniz?

Salim Güran : Yok. Ben ve iki oğlum, yanlış hatırlamıyorsam, yedik.

Av. Nahit Eren : İsmini saydığım kızların Dilek, Rojin. Onlar seninle yemek yemedi. Peki eşinizin ifadesine göre siz evden çıktınız ama siz diyorsunuz ben evden çıkmadım.

Salim Güran : Yemek yedikten sonra biraz dinlendim.

Av. Nahit Eren : Dinlendiniz. Çocuklarınızın çarşıdan aldığı elbiseleri değiştirdiğine dair gördünüz mü siz de?

Salim Güran : Bazıları değiştirdiler, götürdüler.

Av. Nahit Eren : Yani deneme yaparken gördünüz mü siz de? Şimdi gelelim. Az evvel meslektaşım sordu. Benim somutlaştırarak sormak istediğim bir şey var. Dilek'le olan görüşmeleri hatırlamıyorsun dedin. Saat 19:22'den, 19:22. Yani ne biliyor musunuz? Sizin kamera kayıtlarına yakalandığınız ona 18:57'den 59'dan sonraki 15 dakika içerisinde.

Salim Güran : Nereden kameraya?

Av. Nahit Eren : Okulun orada. Okulun orada. Hüseyin'in evinden çıktın ya. Hızlı hızlı geçtiğin kamera kaydı. Mesela.

Salim Güran : Ya orası yoldur. Yol sürekli kullandığımız yoldur.

Av. Nahit Eren : Ha ben itiraz etmiyorum yani burada bir şey çıkarmadım. Soruya geleyim. Sana hatırlatmak istiyorum. Az evvel dedin ya hatırlamıyorum. Hatırlatmak istiyorum. O süre zarfında o yolda giderken yukarıya dediniz ya şüpheli bir araç var. Beni Ramazan aradı. Ramazan aradı dediniz.

Salim Güran : Evet.

Av. Nahit Eren : Gittiniz. O yol güzergahı ne kadar sürüyor dakika itibariyle. Oraya varman sondaja?

Salim Güran : Üç dört dakika.

Av. Nahit Eren : O oraya vardıktan sonra Mehmet Şerif Güran'la hiç telefon görüşmesi yaptın mı?

Salim Güran : Hatırlamıyorum.

Av. Nahit Eren : Ben belki saatlerini versem hatırlayabilirsin. Yine WhatsApp. Gündüz ki aramalardan bahsetmiyorum. 353 saniye arkadaşımın sorduğu değil.

Salim Güran : Onu hatırlamıyorum.

Av. Nahit Eren : Saat 19:22'de sen arıyorsun. 19:34'te o arıyor. 19:38'de sen arıyorsun. 19:40'ta o arıyor. 19:41'de sen arıyorsun. Ve bir daha o seni 20:37'de arıyor.

Salim Güran : Hatırlamıyorum.

Av. Nahit Eren : Bu WhatsApp görüşmesini yaptın mı? Yapmadın.

Salim Güran : Ben ona görüşme yaptığım zaman WhatsApp'ta ona kurdun fotoğrafını da.

Av. Nahit Eren : Gündüz. O bahçeye gidip o bahçelerde fotoğraf çektiğin saat ne?

Salim Güran : Elektrikçilerle?

Av. Nahit Eren : Evet. Dörtte evdesin.

Salim Güran : Dört üçü beş falan olabilir. Beş. Beş. Yani tam hatırlamadım.

Av. Nahit Eren : Dört dört üç. Vecdin'le hiç telefonla görüştün mü?

Salim Güran : Ben aramadım o aradı.

Av. Nahit Eren : O aradı mı hiç seni?

Salim Güran : Aradı.

Av. Nahit Eren : Sordular sana ben ben de bir kez daha sormak istiyorum. Çünkü sıralı arama var. Sen arıyorsun Nevzat'ı arıyor. Nevzat seni arıyor, Nevzat'ı arıyor. Pardon. Seni arıyor, Nevzat'ı arıyor, Nevzat'ı arıyor, seni arıyor. Ben az evvel ifade ettim o saatleri salondaydın. Kaç defa seninle görüştüğünü söyledim. Dört defa beş defa seninle görüşüyor. Bu görüşmelerin içeriğini hatırlıyor musun? Mesela aynı gün üç defa aramış.

Salim Güran : Bakın aramış bak kardeşim Arif orada. Dedim Vedat da beni sürekli sürekli arıyor. Mesela bu bulundu mu, bulunmadı mı? Hani ne olur inşallah bulunur, dua ediyor. Çıktı, Nevzat çıktı. Dedim hele bak ib*neye bak bakayım hele bak dedim. Dedim demek onun için sürekli beni arıyordu.

Av. Nahit Eren : Sen muhtarken bütün aramalara tanık oldun mu? Köydeki jandarmanın yaptığı arama arama faaliyeti.

Salim Güran : Yok çok geniş çaplıydı.

Av. Nahit Eren : İlk hafta Eğertutmaz'daki suyun yukarıdaki kanalda arama yapıldığı için bütün kanal suyunun Eğertutmaz'a verildiğini,

Salim Güran : Doğrudur.

Av. Nahit Eren : Ve Eğertutmaz'ın yaklaşık bir hafta on gün DSİ kanalındaki suyla beslendiğini.

Salim Güran : Doğrudur.

Av. Nahit Eren : Siz bu işlem yapılırken orada mıydınız?

Salim Güran : Evet.

Av. Nahit Eren : Ne kadar sürdü?

Salim Güran : Gittim bizzat kendim gitti. Mesafe uzun ya. İki yerden suyu kestik.

Av. Nahit Eren :  DSİ'nin su kanalının Eğertutmaz'a verildiği süreç ne kadar? En son ne zaman DSİ'nin suları yerinden kendi mecrasında akmaya başladı?

Salim Güran : Şimdi aramalar bittikten sonra sürdü.

Av. Nahit Eren : Ne kadar sürdü? Sen Narin'in Narin'in bulunduğu yeri şu an dosyadaki bilgilere göre nerede nasıl gömüldüğünü?

Salim Güran : Hiç bilgim yok.

Av. Nahit Eren : Hiç merak etmedin mi neresiydi diye?

Salim Güran : Ben hapiste gidip oraya mı bakayım?

Av. Nahit Eren : Bakmak değil bir şekilde dosyada görüntüler var. Avukatlarınız vasıtasıyla olabilir. Televizyonda yayınlandı. Böyle bir imkanınız var mı?

Salim Güran : Hayır

Av. Nahit Eren : Ben size bulunduğu yeri yeri şu an bilmiyor musunuz?

Salim Güran : Kesinlikle bilmiyorum.

Av. Nahit Eren : Ya içeriye bulunduktan sonra da çünkü siz içeri girdiğinizde bulunmamıştı. Bulunduktan sonra da bilmiyorsunuz?

Salim Güran : Bak bir dere değil.

Av. Nahit Eren : Ben gömüldüğü yeri gömüldüğü yeri şu anda gözünüzün önüne getirebiliyor musunuz?

Salim Güran : Ne bileyim getiremiyorum.

Av. Nahit Eren : Bilmiyorsunuz. Getiremiyorsunuz. O su oraya verildikten sonra biz sana anlatalım. Biz sana anlatalım. Görmemişsin. Hemen hemen o suyun yaklaşık birkaç santim toprağının yanında toprağın kenarında bir çukurun içerisine bırakılmış. Eğertutmaz'a o su geldiği zaman o su sence Narin'in naaşının saklandığı yerin üstüne çıkmış mıdır sence?

Salim Güran : Çıkmıştır.

Av. Nahit Eren : Kaç metre?

Salim Güran : O büyük su gitmişse eğer tabii göle koymuşsa zaten suyun altındadır.

Av. Nahit Eren : Ben neyi öğrenmeye çalışıyorum? Muhtarsın o aramalardasın ya. Ben Narin'in bedeninin bedeninin

Salim Güran : Ben o dereye gitmemişim aramaya da gitmemişim.

Av. Nahit Eren : Hayır su verildi mi diyorsun ya.

Salim Güran : Ben o dereye gitmemişim. Eğer su aramışım.

Av. Nahit Eren : Az evvel dedin ki Eğertutmaz'da sekiz defa arama yapıldı dedin. Kendin dedin.

Salim Güran : Benim avukatımın şeyiyle ben söylüyorum.

Av. Nahit Eren : Ben onu söylüyorum. Diyorum ki Eğertutmaz'a verilen devlet su işlerinin kanalındaki suyun o bölgede akmaya devam ettiği süreyi biliyor musun bilmiyor musun? Net bir soru.

Salim Güran : Evet net olarak bilmiyorum ama epeyi gitti yani.

Av. Nahit Eren : Peki 27, 28, 29, 30, 31'inde Eğertutmaz'ın suyunun Çarıklı'ya Çarıklı'da bir zarara sebebiyet vermemesi için Diyarbakır Büyükşehir Belediyesi'nin kepçelerinin getirilerek önünde çalışma yapılıp 4 gün boyunca yeni bir akar yapılıp suyun yukarıdan tamamen aşağı inmesine ilgili çalışmada var mıydın?

Salim Güran : Yok.

Av. Nahit Eren : Haberin var mı bunda?

Salim Güran : Sadece biz JASAT ile biz kamera tespiti yaparken bizim köyden Gönenli'ye gittik. Gönenli'ye Çarıklı'ya tarafa dönerken kepçenin orada çalıştığını gördüm.

Av. Nahit Eren : O kepçenin orada çalıştığını biliyorsun. O kepçe çalıştığında DSİ'nin suyu hala Eğertutmaz'a akıyor muydu, akmıyor muydu?

Salim Güran : Onu hatırlamıyorum.

Av. Nahit Eren : Sordular, ben de soracağım. Yine baz istasyonlarına göre akşam o Narin'in Nevzat tarafından götürüp saklandığı yere aracınla sen değil misin giden?

Salim Güran : Kesinlikle ben gitmemişim. Gitmişsem köy halkı hepsi gitmiş.

Av. Nahit Eren : Peki baz istasyonu yine seni orada gösteriyor.

Salim Güran : Baz nedir bilmiyorum ama ben gitmemişim.

Av. Nahit Eren : Baz nedir? Ben şu anda buradayım ya. Telefonum burada gösteriyor ya. Evet. Benim şu an baz aldığım yere göre ölçümler yapılıyor. Başka bir baz bazdan çakışıp çakışmadığı.

Salim Güran : Ben baza inanmıyorum.

Av. Nahit Eren : İnanmıyorsun tamam.

Salim Güran : Ben Arif'in evine gitmemişim. Siz diyorsunuz ki siz gitmişsiniz.

Av. Nahit Eren : Ben ben demiyorum. Ben diyorum ki rapor öyle söylüyor. Haber aldığın ana gelelim. Ben o ses kaydının dinletilmesini istiyorum. Dilek seni arıyor. Evet. Baba diyor Narin Narin kaybolmuş diyor. Ne ne diyorsun?

Salim Güran : Ne?

Av. Nahit Eren : Hayır ne? Ne? Anlamıyorsun tam. Evet şebeke. Şebeke gidiyor, kesiliyor. Selim'e Mehmet Selim Atasoy'a o an diyorsun ki hadi Selim gidelim.

Salim Güran : Yok.

Av. Nahit Eren : Kayıtta var. Kayıtta var lütfen dinleyebilir miyiz? Hayır hayır onun ses kaydı ya. Bir teyit ekmek için ben açabilir miyim?

Mahkeme Başkanı : Açın. Açın ya da okuyun. Yani çözümlemesini de okusanız yeter. Nahit Bey yani.

Av. Nahit Eren : Çözümlemesi başkanım ben sesi dinleteyim.

Mahkeme Başkanı : Buyurun.

Av. Nahit Eren : Telefon ses kaydı yaptığı için karşı taraftaki görüşmelerin dışında mahallede bulunan insanların da sesi geliyor. Böyle bir özelliği var. Sadece görüşmeyi kayıt etmiyor.

Salim Güran : Tamam geldim ben sana diyorum Selim Atasoy benimle köye gelmiş. Sen neyin peşindesin.

Av. Nahit Eren : Ben sana bir soru soracağım Bu diyalog doğru mu? Bu diyalog doğru mu? Bu diyalog doğru mu?

Salim Güran : Benimle geldi diyorum.

Av. Nahit Eren : Ben hadi gidelim dedin mi? Demedin mi ona? Onu soruyorum.

Salim Güran : O bana dedi. Dedi hele dur ben de geliyorum iki oğlunu o onu oradan bıraktı. Benimle köye geldi.

Av. Nahit Eren : Ben içerikle ilgili bir şey sormayacağım. Başka bir şey soracağım için sen dinle sana ait bir ses değilse ona göre şey yapalım. Başkan bunu bir dinletiyorum. Çünkü burada onu dinletelim.

Mahkeme Başkanı : Onu dosya numarasını söylerseniz bizim bilgisayardan açabiliriz.

[Heyet, sanık müdafileri ve katılan vekilleri tarafından bahse konu ses kaydının açılması için uğraşıldığı, kaydın bulunmaya çalışıldığı ve seslerin birbirine girmesi nedeniyle buralar zapta aktarılmadı.]

Mahkeme Başkanı : Evet. X bayan şahıs saat sekizde. Doğru mu?

Av. Nahit Eren : Doğru.

Mahkeme Başkanı : X bayan şahıs. Arayan şahsın yanında bulunan küçük kız. Dede diyor. Sonrasında X bayan konuşuyor. Salim X bayan şahıs söylüyorlar Narin kaybolmuş. Salim nasıl kaybolmuş? X bayan şahıs diyorlar Narin cızırtı sesi. Salim H alo alo. Salim yanında olan ilk şahsa Mehmet Şirin benle sen gidelim. Ben bunu soruyorum. Mehmet Şirin.

Av. Nahit Eren : Hatırladın mı?

Salim Güran : Söyledim diyorum.

Av. Nahit Eren : Tamam ben ben sen dedin ki ben öyle bir şey söylemedim. Konuşmayı hatırlatmak için sana bir şey soracağım. Sesi dinletsek Sayın Başkan?

Salim Güran : Mehmet Şirin ile köye gittim dedim sana. Narin'in kaybolduğunu anladım ben.

Av. Nahit Eren : Telefon kesildi değil mi? Ya bir daha arama ihtiyacı hissetmediniz mi?

Salim Güran : Ben gittim 2 dakikaya yakındır. Oradayım.

Av. Nahit Eren : Tam anlayabildiniz mi kayboldu?

Salim Güran : Kayboldu onu anladık.

Av. Nahit Eren : Nasıl? Ne şekilde? Gitmenizi gerektiren bir kaybolma mı?

Salim Güran : Oradayım iki üç dakika.

Av. Nahit Eren : Hayır nasıl bir kaybolma? Kızınız mesela nasıl bir kaybolmanız?

Mahkeme Başkanı : Güzel bir üslupla cevap ver.

Salim Güran : Hayır, hayır.

Mahkeme Başkanı : Hatırlamıyorsan hatırladım.

Salim Güran : Hatırladığımı söyledim.

Mahkeme Başkanı : Sen neyin peşindesin? değil.

Salim Güran : Lütfen susmak istiyorum.

Mahkeme Başkanı : Ha susmak istiyorum de. Cevap vermek istemiyorum de. Tamam. Bu kadar basit.

Mahkeme Başkanı : Sorulara bu soruya cevap vermek istemiyorum dersen biz de devam ederiz. Buyurun Nahit Bey.

Av. Nahit Eren : Bu soruya mı cevap vermek istemiyorum? Genel olarak bu sorulara. Siz devam edin sormak istiyorsanız soruyu sorarak cevap vermek istemiyorum. Soruyu sorarak cevap vermek istemiyorum. Genel değil. Başka sorunuz varsa sorun o. Yok en son sorun buydu. Tamam.

## Aile ve Sosyal Hiz. Bakanlığı

### Av. Abdullah Yılmaz

Av. Abdullah Yılmaz : Melike Güran'ın bir ifadesi var. Direkt konuya giriyorum. Melike Güran'ı tanıyorsunuz değil mi?

Salim Güran : Tanıyorum amcamın kızı.

Av. Abdullah Yılmaz : Tamamdır. Ona siz şey söylemişsiniz. Kendi ifadesi var. Bunlar benim ifadem değil. Siz Narin'in kaybolduğu saatini 17:40 olarak söyle demişsiniz. Bu doğru mudur?

Salim Güran : Kesinlikle.

Av. Abdullah Yılmaz : Peki Birsen Güran'a böyle bir şey söylediniz?

Salim Güran : Ona da söylemedim.

Av. Abdullah Yılmaz : Birsen Güran'dan Maşallah söylemiş. Annesine yani.

Salim Güran : Kesinlikle.

Av. Abdullah Yılmaz : E bunlar niye yalan söylesinler? Mesela niye?

Salim Güran : Kendilerine sorun niye yalan söylüyorlar.

Av. Abdullah Yılmaz : Onlara da soracağız. Şu an size soruyorum. Çünkü söylemişsiniz.

Salim Güran : Ama ben söylememişim.

Av. Abdullah Yılmaz : Peki Hediye Güran'ı tanıyorsunuz. Birkaç gün sonra Narin kaybolduktan sonra telefonunu değiştiriyor. Bundan haberiniz var mıydı?

Salim Güran : Kim değiştiriyor?

Av. Abdullah Yılmaz : Hediye Güran.

Salim Güran : Bilgim yok.

Av. Abdullah Yılmaz : Peki. Tamam. Şimdi Arif Güran'ın başkanım söyle beyanlar üzerinden gidiyorum. Arif Güran'ın bir ifadesi var diyor ki bizim Nevzat'la ilişkilerimiz iyidir diyor. Yine sizin için de aranız iyidir diyor. Onun dışında siz de hatta diyorsunuz Arif Güran diyor ki biz Nevzat Bey'le beraber aradık diyor.

Salim Güran : Bakın ben size söyledim. İki buçuk aydır ben bununla konuşmamışım.

Mahkeme Başkanı : Şey Salim Salim bana bak.

Av. Abdullah Yılmaz : Ama niye bunu? Ama kardeşiniz diyor ki beraber aradık diyor. Hep beraber diyor.

Salim Güran : O ev sıvasından sonra ben ne o beni aramayın ne ben onu..

Mahkeme Başkanı : Tamam bu soruya cevap verdiniz. Üç kere sorduk.

Av. Abdullah Yılmaz : Gazal Bahtiyar'ı tanıyor musunuz?

Salim Güran : Tanıyorum.

Av. Abdullah Yılmaz : Nevzat Bey'in eşi. Şimdi o diyor ki ifadesi bak beni gene bunlar benim ifadem değil. Bunlar tanık olarak bilgi alma olarak alınmış ifadeler. Diyor ki birbirlerine kardeşim derlerdi diyor.

Salim Güran : Ne kardeşi ne hali yok öyle bir şey. Yalan.

Av. Abdullah Yılmaz : Narin'in kaybolduktan sonra da diyor bizi aralarına almadılar diyor. Sizin için söylüyor.

Salim Güran : Ben ifademi alırken diyor çok samimi ya ne çok samimi arkadaşı dedim. Yani normal köylüyle nasıl arkadaşsam öyle arkadaşım. Kalkıyor çok samimi arkadaş vuruyor. Kendine göre vuruyorlar.

Av. Abdullah Yılmaz : Ya bu sizin beyanınız ama Gazal Hanım'ın beyanı da bu şekilde.

Mahkeme Başkanı : Tamam.

Av. Abdullah Yılmaz : Sonra şeyi diyor Narin kaybolduktan sonra Güran ailesi başta sizi kastediyor. Bizi aralarına almadı diyor. Yani yabancıları aralarına almadı diyor. Bakın Narin yirmi birinde kayboluyor. Siz 2 Eylül'de bir saniye abi bir saniye. Soru cevap yapıyorum. Siz 2 Eylül'de tutuklanıyorsunuz. 8 Eylül'de Narin bulunuyor. Şeyleri tarihleri dikkat edin.

Mahkeme Başkanı : Bakın. Ya direkt şöyle. Doğru mu böyle bir şey?

Salim Güran : Yok.

Mahkeme Başkanı : Tamam bitti.

Av. Abdullah Yılmaz : Bilgi alma tutanından almış. Doğru mu diye sordum. Niye yalan söylesen? Bakın çelişki. Onu Başkanımız da söyledi. Sayın Başkan da sordu. Dosyada sadece net belirgin olan on iki tane çelişkili ifade var. Siz kendinizi lehinize olanları hatırlıyorum diyorsunuz. Söyle artık diyorsunuz. HTS'yi kabul etmiyorsunuz.

Salim Güran : Tabi kabul etmem gitmediğim bir yeri niye kabul edeyim.

Av. Abdullah Yılmaz : Onun için sinirlenmeyin. Şimdi Sayın Başkan özetle neyse ben beyan vermeyeceğim ama son olarak başkanım bir soruyla kapatıyorum ben çok da vaktinizi almayacağım. Eğertutmaz deresine. Şimdi Sayın Başkan söyle. Dosyalara üç kere geldi. Sayın Başkan sekiz kere dedi. Siz jandarmalarla orayı aradınız mı? Sekiz kere?

Salim Güran : Ben gitmemişim oraya. Ben aramamışım dedim. Az önce söyledim. Evet.

### Av. Şeyhmus Erdoğan

Av. Şeyhmus Erdoğan : Sesim geliyor değil mi?

Mahkeme Başkanı : Geliyor geliyor.

Av. Şeyhmus Erdoğan : Siz hiç yanınızda silah taşır mısınız silahınız var mıdır?

Salim Güran : Benim beylik silahım var.

Av. Şeyhmus Erdoğan : Çünkü Nevzat Bey'in ifadesinde silahla tehdit ettiğini söylemişti.

Salim Güran : Yalan atıyor. Bu bu hiç. Bu hiç kimseden korkmuyor, korkmuyor. Peki. Eskiden Gazal baktım ya beni aradı bir akşam. Dedi çabuk koş gel dedi kardeşini öldürdü. Ben gittim kardeşinin evine girmiş dipçikle böyle kafasına vuruyor. Kafasına vuruyor. Yetişmezse kardeşini yok.

Av. Şeyhmus Erdoğan : Peki kayıp haberini öğrendikten sonra hiç eve gittiniz mi?

Mahkeme Başkanı : Nasıl?

Av. Şeyhmus Erdoğan : Kayıp olduğunu öğrendikten sonra.

Salim Güran : Evet.

Av. Şeyhmus Erdoğan : Hiç eve uğradınız mı yoksa aramalara mı katıldınız?

Salim Güran : Eve gittim.

Av. Şeyhmus Erdoğan : Eve gittiniz. Benle Arif'in evi karşı karşıya dedi. Eve gittiniz değil mi?

Salim Güran : Evet. Peki bir üstünü değiştirme meselesini onu kabul etmiyorsunuz değil mi?

Mahkeme Başkanı : Değiştirmedim dedi.

## Sanık Enes Güran Müdafi

### Av. Mustafa Demir

Av. Mustafa Demir : Yani silinmiş WhatsApp verileri diye geri getirilen bir belge diye söyleniyor. Şimdi burada bunun WhatsApp olduğu yazmıyor. Bu çıkarma nereden geldi? Sonunda geleceğiz buraya. Burada silinen bilgilerin geri getirilmesi programı uygulamış. Öyle yazıyor yani burada belgede yazıyor. Bu program uygulandıktan sonra bazı arama kayıtları gelmiş. Aramada işte isim telefonda nasıl kayıtlı onlar görsün. Şimdi burada tek tek kimle kaç saniye görüşmüş? Gelen arama mı? Giden arama mı? Yazıyor. Burada muhtemelen şuna baktı savcılık. Nevzat'la görüşmüş mü? Nevzat'la görüştü tespit edilmiş. Ne zaman? 17:46. 17:46:32. Bunu HTS'ye bakmışlar. HTS'de böyle bir arama yok. Bundan şu çıkarım yapılmış. O zaman bu WhatsApp aramasıdır. Yani buna ilişkin bir teknik veri yok. Herkes sorduğunda WhatsApp araması diye sordum. Bu aramayı birebir HTS'yle alt alta koyalım. Bakalım bütün aramalar aynı. Bire bir aynı. Sadece ne farklı biliyor musunuz? Dakika 2 saat 38 dakika 27 saniye kayma var. Yani HTS'deki bütün aramalara 2 saat 38 dakika 27 saniye aradığınızda eklediğinizde şu tablo çıkıyor ortaya. Yani birebir aramalar, süreler, hepsi aynı. Sıralama aynı. Hatta bu WhatsApp olduğu iddia edilen arama da [4446996]{.phone} aranmış. Bu da elektrik arıza yine. Yani WhatsApp'tan elektrik arıza da arandı. Yani bu WhatsApp olduğu yok.

Mahkeme Başkanı : Tamam soru?

Av. Mustafa Demir : Şimdi şuraya. Anladım. Bundan önce sorulmuş sorular ne yazık ki boşa gitti. Yani iddianame bunun üstüne şey oldu. Az önce dedim ya algılarla hep oldu bu iş. Şimdi burada kendisine şunu soracağız kendisi en iyi bildiği için. Bu küçük bir harita. Daha büyüğünü yapacaktık da olmadı. Şurada Narin'in cansız bedeninin gömüldüğü yer. Burada mısır tarlası nerede? Bize gösterebilir mi? Kendisine verelim.

Mahkeme Başkanı : Tabii ki.

Av. Mustafa Demir : Orada mısır tarlasını. Tam şurası Narin'in cansız bedenin bulunduğu yer. Mısır tarlası nerede?

[Sanık Salim Güran'a harita gösterildi ve işaretledi.]

Av. Mustafa Demir : Yani boyadığımız yer mi? Doğru mu boyamışız?

Salim Güran : Evet.

Av. Mustafa Demir : Oranın o sarı nokta var ya uzaklığı ne kadar? Şey mikrofona yakın mikrofon şey. Eğer tepe gösterirsek burada yine mesela daha detaylı anlatacağız da ne için bu önemli? Daraltılmış HTS'de Narin'in cansız bedenine doğru giden bir araçtan bahsediliyor ya. Ancak Salim Bey'in HTS kaydında burada yani mısır tarlasında olduğu söyleniyor. Bu mısır tarlasının yüz ölçümü nedir? Yani kaç dönümdür?

Salim Güran : Ha 135 dönüm.

Av. Mustafa Demir : Yani 135 dönümün içinde herhangi bir yerde olabilir. Ama bunu biz cesede gitti diye yorumlamışız. Öyle anlıyoruz biz o zaman bu daraltılmış HTS'den. Bunun gibi birçok konu var. Bir de bence konuşmasında bu şeyde konuşmada çok kıymetli bir nokta var. Onu sormak istiyorum. Sanırım jandarmayla yapmış. Öyle yazıyor çünkü dökümde. Jandarmaya saat 3, 03:30'da benim anladığım ilk başta zaten müvekillerde sürekli saat kayması şundan yaşanmış. Herkes bir saat söylemiş. Zaten bunu dosyada da görüyoruz. İlgili ilgisiz aslında yaşamadığı saatlerde bile gördüğünü söyleyen insanlar olmuş. Ve bu çekirdek aile diye tabir ettiğimiz kavramın dışında kalan yer. Üçte üç otuzda gördüğünü söylemiş. Köyün içinde o anda iki kişi için genel arabası görmüş. Eski kırmızı araba. Burada hemen daha sonrası. Bu burada konuşma yirmi yirmi dokuz. Doğru mudur böyle bir konuşma hatırlıyor musunuz?

Salim Güran : Ben öyle bir konuşma yapmamışım. Ha çingene konusu geçmiş olabilir ama kırmızı bir araç da geçiyor.

Av. Mustafa Demir : Bilerek veya bilmeden bence güzel bir bilgi vermişsiniz. Konuşma çünkü şeyi var. Burada ikinci defa bir konuşma var. 20:39. Yine bir jandarma personeli. Jandarma personeli de konuşunca kayıptır her yere bakıyoruz falan diyor. Jandarma personeli de diyor ki tepeye baktınız mı? Kendisi de her yere bakıyoruz komutanım bütün köy toplanmış. Tepenin kamerası diyor jandarma personeli. Tamam komutanım diyor. Tepenin kamerası gösteriyor ya. Evet hadi görüşürüz. Bizim için kritik şey şu. Bu tepenin kamerası siz o köyde uzun süredir. Yani orada doğdunuz herhalde büyüdünüz.

Salim Güran : Evet.

Av. Mustafa Demir : Karşıda bir askeri üs var.

Salim Güran : Doğrudur.

Av. Mustafa Demir : Oranın kamerası sizin köyü ne netlikle görüyor?

Salim Güran : Bizim köyü ayna gibi görüyor.

Av. Mustafa Demir : Evet.

Salim Güran : Kamışlo buraların binasını perdesi çekmezse insanı görüyor. Nasıl bizim orayı görmüyor?

Av. Mustafa Demir : Peki bu kamera kaydına bakılmasını istediniz mi?

Salim Güran : Bakmıyorlar, istiyoruz. Evet. Ne bize geldi? Hakim Bey'e söylüyorum Hakim Bey. Ben o kamerayı istiyorum. Zaten kamera ayna gibi gösterir bunun nasıl Narin'i yakalayıp götürdüğünü.

Av. Mustafa Demir : Peki sizin köyde daha öncesinden mesela köy içinde düğünlerde silah çekildiğinde bu kamerayla...

Salim Güran : Evet akşam silah sıkıldı. O karakoldan geldi. Dedi biz sıkmamışız. Dedi sen sıkmışsın. Bu sen sıkmışsın. Getirin.

Av. Mustafa Demir : Ben burada şuna dikkat çekmek istiyorum. Kamera görüntüleri dosyada var. Onları da iki adet göstermek istiyorum. Yani dört adet oluyor. Zaten dosyada var. Bunun büyütülmüşünü göstermek istiyorum. Şimdi burada kritik şey ne? Kameralarda şimdi bizdeki tabii iyi yazıcıdan çıkarmadık. Bir de taramalar oldu. Kaliteli değil bizdeki şu an. Ama ben bunun daha kaliteli olacağını anlıyorum. Nereden? Şurada on ikide videonun kendi zamanına göre anlatıyor. Tavşantepe mahallesi içerisinde bulunan okulun alt tarafında yoldan gelen bir aracın sola dönüş yaparak Diyarbakır Mardin yolu istikametine gitti. Yani şunu anlıyoruz. Okulun şey köyün içindeki tüm araçları belki de daha ötesi insanların hareketlerini görebiliyor. Bunu çünkü raporlamışlar. Eğer bu raporlanabiliyorsa bu gerisi de mümkündür. Şimdi burada şey söylendi bir dönem. Görüntüler var, görüntüler TÜBİTAK'ta. Biz bu görüntülerin bu görüntüler olduğunu sanıp gerçekten iyimser bir şekilde bu olayın aydınlanacağını düşündük. Burada hareketle yani yine 3 saatini vermiş ya saat 03:00-03:30. 03:00-03:30 saati verilmiş jandarma personeline. Eğer bu hareketten ve gelen kayıtlar 18. Yani kayıt da alıyor. Çünkü jandarma personeline 20:00'den sonra verilmiş bilgi. Gelen kayıt 18. Demek ki kayıt var. Bunu biliyoruz. Bu bilgiler cepte. Peki buradan gelseydi tepede sizin hareketliliğiniz yani iddia edildiği gibi iddia edildiği gibi ben sorunu tamamlayayım. İddia edildiği gibi müvekkillerin evine girmiş olsaydınız anlaşılır mıydı?

Salim Güran : Evet.

Av. Mustafa Demir : Peki siz buradan başka bir yola inmişseniz yani okulun yanından indiniz veya Nevzat'ın iddia ettiği gibi diğer taraftan bir battaniye almak için o tarafa gittiyseniz bunların hepsi tespit edilebilir miydi?

Salim Güran : Yoktur. Hepsi tespit ediliyor. Kör nokta diye bir yer yoktur.

Av. Mustafa Demir : Siz muhtar olduğunuz için bu bilgileri daha iyisiniz.

Salim Güran : Çok iyi biliyorum. Gelsinler. Narin'in patikada çıktığı dakikada sonra o kamerayı buradan açsınlar herkes görsün. Benim başım.

Mahkeme Başkanı : Salim Bey ne zaman gözaltına alındınız?

Salim Güran : İkisinden tutuklandım. Tamam. Ondan önce de tabii götürüp getirdim.

Mahkeme Başkanı : Şu an çok iyi biliyorum dediniz. O ifadenin hiçbirinde bu kamera kayıtları talebiniz yok.

Salim Güran : Kamerayı bakacak dedim. Ben ne bileyim? Ya. Bakıyorlar saat dörtten sonra Narin'in patikadan çıktığı saatten sonra baksınlar.

Mahkeme Başkanı : Sen keşke bunu o zamanki beyanında da müdafi huzurundaki beyanında da söyleseydin de biz bu hususları o zamanki beyanlarınızda görseydik. Bu hususlar siz biz iddianameyi kabul edildikten sonra sanık müdafilerin talebinden sonra Arif Bey'in de canlı yayına yani röportaj vermesiyle iddia çıktı. İki aydır niye beklediniz bunu?

Salim Güran : Hakim Bey. Onlar biz bilmiyorduk. Biz dedik ki, Narin'in patikadan çıktığı dakikadan sonra bakmışlar. Meğerse altıdan sonra mı ne bakmışlar? Diyor ki güneş batımı vuruyor. Kamerayı görmüyor. Patikada çıktığı güneş orada yok ki. Güneş tepemiz.

Mahkeme Başkanı : Ha siz güneş vurduğunu düşündüğünüz için şey yapmadınız.

Salim Güran : Yoksa söylerdik. Hakim Bey.

Mahkeme Başkanı : Tamam.

Salim Güran : Benim gördüğüm çok güzel bir kameradır bu.

Mahkeme Başkanı : Tamam, soracağız.

Av. Mustafa Demir : Bir de şeyi sorayım. Telefonumda bu dinleme kaydında sildiği bir şey var mı? Bu dinleme programının olduğundan özellikle sildiği bir şey var mı? Dinleme programı var ya telefonunuzda. Bunda öncesine ait dinlemelerden de sildiğiniz bir şey var mı?

Salim Güran : Eskiden de siliyordum.

Av. Mustafa Demir : Şimdi ben telefonumda iki üç gün her günde silebiliyorum. WhatsApp'tır. Benim şahsi telefonumdur. Yani olaydan sonra değil yani. Ondan önce de siliyordum yani.

Av. Mustafa Demir : Başkanım ben bu şeyle ilgili kısımda kıymetli olduğu için size şöyle sunmak istiyorum.

Mahkeme Başkanı : En sonra alırız avukat bey ya da şimdi hadi.

Av. Mustafa Demir : Sürekli sorular buradan mı soruldu?

Mahkeme Başkanı : Tamam.

Av. Mustafa Demir : 17:46'da bir arama var mı diye soruldu ya. Aslında 17:46'daki arama 15:08'deki arama. Tek arama yani. Çünkü saniye bakarsanız saniyeye kadar bir saniye bazı aramalarda sadece birer saniye salise farkıyla kayma var. Teşekkürler.

Mahkeme Başkanı : Yani ben şunu soruyorum. Sizin sorunuzu bölmeyin. Sen gece mısır tarlasına da gitmedim dedin bana?

Salim Güran : Ben gitmemişim. Sabah saatleri gitmişim.

Mahkeme Başkanı : Tamam. Buyurun.

## Sanık Salim Güran Müdafi

### Av. Onur Akdağ

Av. Onur Akdağ : Sayın başkan Nahit Bey tabii ki iyi niyetli olarak WhatsApp kayıtlarıyla ilgili müvekkilime ısrarlı sorularda bulundu ancak Mustafa Bey de çok nazikçe bu WhatsApp kayıtlarıyla ilgili bazı beyanlarda bulundu. Şimdi şunu söylemek istiyoruz. Çok can alıcı bir hususta savcılık makamının müvekkil aleyhine kati surette tartışmasız bir kanıt elde edemeyince resmen suç delili uydurmuş olmasıdır. Dosyada WhatsApp arama kayıtlarını geri getirmesine yönelik resmi belge sahtedir efendim. Şöyle ki HTS kayıtlarında 21 Ağustos tarihine ilişkin arama arama listesi bir bütün halinde kopyalanmış bir bütün halinde kopyalanmış sıralı bir şekilde her birinin üzerine yaklaşık 2 saat 39 dakika eklenerek yeni bir liste oluşturmuştur. Mesela 15:08'de HTS kayıtlarına göre Nevzat Salim'i aramış 17:46'da da WhatsApp'ta aramış görünüyor. Yine HTS kayıtlarında [4446996]{.phone} numaralı DEPSAŞ'a ait bir arama kaydı mevcut. WhatsApp'ta silinen silindiği iddia edilen kayıtlarda da aynı numara vardır. WhatsApp'ta 444'lü numaraların aranma imkanı var mı Sayın Başkanım?

Mahkeme Başkanı : Ben bu dosyada çok şeyler öğrendim. Bunu da denerim.

Av. Onur Akdağ : Evet. Bunu da deneyelim. Ben denedim çünkü bulamadım. [4446996]{.phone} da bir DEPSAŞ numarası efendim.

Mahkeme Başkanı : Bir de deneyim yarın.

Av. Onur Akdağ : 13:00 ve 16:06'da kızı Dilek'le görüşmüş. Bu ne zaman görüşmüş biliyor musunuz? Diyarbakır'da alışveriş yaparken görüşmüş.

Mahkeme Başkanı : Şimdi savunma mı yapıyorsunuz? Soruyorsunuz.

Av. Onur Akdağ : Hayır hayır. Bunu izah ediyorum efendim. İzah edeyim ki çünkü aynı aynı yanlışla müvekkilimin üzerine gidilmiyor.

Mahkeme Başkanı : O zaman oturun. İki artık bitti. Sizi yerinize alayım. Avukat Bey iki üç dakika savunma yapacakmış.

Av. Onur Akdağ : Üzerine iki dokuz dakika ekleyin. On beş otuz dokuz, on beş kırk altı. İşte alın size WhatsApp'ta getirildiği iddia edilen kayıtların hazin sonu. Ulan sanık sanık salim müdafi sanığın beyanına karşı birkaç cümle söyleyecek. Edilen şey de Nevzat kızı gömdü. Sahibi olan Salim'i arayıp gömdüğünü belirtti. Yani bu senaryoya artık savcı. Özcan. Zihin dünyasına empoze. Hazırla. Biz bunu öncelikle belirtmek istiyoruz ki yani bu yanlış üzerine tekrar yeniden konuşulmasın. Biz normalde savunmamızda belirtecektik. Ancak çok tahrik olduğumuz için yapacak bir şey yok yani. Şimdi söylemek istiyoruz. Evet. Şimdi müvekkilime birkaç ustam usulü sormak istiyorum. Ha oradasınız. Ha. Biz Nevzat Bahtiyar'ı en son ne zaman aradınız?

Salim Güran : Ben mi?

Av. Onur Akdağ : Evet. Yani hangi tarihte aramış olabilirsiniz? Yaklaşık zaman olarak söyleyebilirsiniz yani. Olay gününden bahsetmiyorum.

Salim Güran : Ha iki aydır zaten tutukluyum ben. Olay gününden önce iki buçuk ayda onunla görüşmemişim zaten kesin. Evet. E yani uzun uzun yani görüşmemişim.

Av. Onur Akdağ : Peki siz Nevzat Bahtiyar'la hiç çapkınlıkla ilgili konuşur musunuz? Ya kadınlardan bahseder misiniz? Eskortlardan.

Salim Güran : Yok öyle bir şey kesinlikle.

Av. Onur Akdağ : Yani Nevzat Bahtiyar'la böyle bir samimiyetiniz var mı?

Salim Güran : Yok.

Av. Onur Akdağ : Şimdi Nevzat Bahtiyar ilk ifadelerinde sizden sadece sizden bahsediyor. Yani Yüksel sorulunca sizden bahsetmiyor. Yüksel'den bahsetmiyor. Daha sonraki ifadelerinde neden Yüksel'e bu ifadeler kaymış oluyor? Yani bununla ilgili bir fikriniz var mı?

Salim Güran : O medyaya göre gidiyoruz zaten.

Av. Onur Akdağ : Şimdi 9 Eylül tarihinde Didem Arslan'ın programında ilk defa Nevzat ile Salim'in iftirası ilk defa gündeme gelince Nevzat'ın ifadelerine baktığımızda da zaten Nevzat'ın ifadeleri 9 Eylül tarihinden sonra Salim ile Yüksel'in ifadelerine doğru kayıyor. Yani müvekkilim daha önce belirtmişti ya. Televizyonda 7 gün boyunca dersini çalışmış. Yani dersini çalışmış olması bundan ibarettir. Biz bunu bunu dile getirmek istiyoruz. Evet. Son olarak da Nevzat Bahtiyar senin ismini neden vermiş olabilir?

Salim Güran : Benim ismimi niye verdi? Beni gözaltına aldılar. Benim araba beni al dediler. Ondan sonra benim avukatım kalktı. Seda Tuğrul. Sanki bir şey varmış gibi. Benim de bir kızım var. Kalkıyor. Avukatlığımı bırakıyor. İnsanlar içinde bir algı bırakıyor. Acaba bir şey mi gördü? Medyada beni yerden yere vuruyor. Giden vuruyor. Gelen vuruyor.

Av. Onur Akdağ : Peki Narin Güran, rahmetli Narin Güran. Sizin evinizin önünde hiç çocuklarınızla oynar mıydı? Arabanıza biner miydi?

Salim Güran : Akşam serinliğinde oynar. Tabii biner çocuktur. Biniyor. Bir de o eski araba Fuat Güran kardeşimin arabasıydı. Yıllarca arabadır. Ben de binerim. Arif de biner. Diğer kardeşin de hepimiz binerim.

Av. Onur Akdağ : Sizin aracınızın herhangi bir camı bozuk muydu?

Salim Güran : Bozuktu.

Av. Onur Akdağ : Çünkü Nevzat Bahtiyar hangi hangi camınız bozuk?

Salim Güran : Şimdi şoför tarafı indirdiğiniz zaman şöyle kafa üstü aşağıya iniyor. Onu düzeltmen lazım. Öbür taraf hiç inmiyor. Hiç.

Av. Onur Akdağ : Öbür taraf dediğiniz ön taraf mı?

Salim Güran : Arka tarafı sağ hiç inmiyor. O zaten bozuktur. Arkalarda zaten.

Av. Onur Akdağ : Yani Nevzat Nevzat Bahtiyar ilk ifadesinde arabayı yanaştırdık sağ camdan aldım diyor ya. 9 Eylül, 9 Ekim tarihli cam raporunda da zaten müvekkilimin ifadeleri doğrulanıyor efendim. Bunu belirtmek istiyorum. Teşekkür ediyorum.

Mahkeme Başkanı : Ben teşekkür ederim. 
