---
title: "Nevzat Bahtiyar Savunması"
editor: source
---

## Mahkeme Başkanı

Mahkeme Başkanı : Evet Nevzat Bey, iddianame sana tebliğ edildi. Okudun. İddianameye göre Narin Güran'ı diğer sanıklarla birlikte iştirak halinde öldürmekten cezalandırman talep ediyor. Ne dersin? Seni dinliyorum. Buyur.

Nevzat Bahtiyar : Sadece pişmanım.

Mahkeme Başkanı : Baştan başla. Olay günü neredeydin? Nasıl buluştunuz? Kimle görüştünüz? Ondan bir başlayalım. Salim'i neden aradın? Oradan başla.

Nevzat Bahtiyar : Salim'i su için aramıştım.

Mahkeme Başkanı : Evet, sen mikrofonu alabilir misin? Daha rahat edersin. Tamam, şimdi dinliyorum.

Nevzat Bahtiyar : Su için aramıştım.

Mahkeme Başkanı : Niye?

Nevzat Bahtiyar : Suyumuz kesilmişti.

Mahkeme Başkanı : Suyunuz kesilmişti? Şimdi... Tamam, suyunuz kesildi. Aradınız. Sonra?

Nevzat Bahtiyar : Konuşma hakkım var? yoksa susma hakkım da var?

Mahkeme Başkanı : Her türlü hakkın var. Ama sorularımıza... İşte bize olayı anlat ki biz de ona göre sana soru yönetelim. Olayı anlatmak istiyor musun?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Peki... Diyarbakır Cumhuriyet Başsavcılığı'nda vermiş olduğun beyanların var. Bu beyanların doğru mudur?

Nevzat Bahtiyar : Doğrudur.

Mahkeme Başkanı : Hangisi doğrudur? Bir beyanın ile ikinci beyanın arasında fark var. En son verdiğin beyanın mı doğrudur?

Nevzat Bahtiyar : En son verdiğim beyan doğrudur.

Mahkeme Başkanı : O beyanı aynen tekrarlıyor musun?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : En son verdiğin beyanın doğru mudur?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : O beyanını şu an huzurda tekrarlıyorsun değil mi?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Tamam. Beyanını kısaca okuyayım. Sabah uyandım, buraları hızlı geçiyorum. Bunun üzerine Salim Güran bana "ben arıza için yetkileri ararım" dedi. Daha sonra aramızda herhangi bir konuşma olmadı. Bu konuşmanın hemen sonrasında ikametimden çıkarak bana komşu olan annemin ikametinden su hortumu marifetiyle ikametimin önünde bulunan ağaçları sulamaya başladım. Her ne kadar annemle komşu olsak da ikametlerimize gelen su hatları farklı olduğundan ve sadece benim ikametime gelen su hattında arıza bulunduğundan dolayı annemin ikametinden su alabildim. İkametimin önündeki ağaçları sulamaya başladıktan yaklaşık 15 dakika sonrasında ikametimden yaklaşık 100 metre mesafede ve benim ikametime göre yüksekte kalan Arif Güran'a ait ikametin bahçesinden Salim Güran bana seslenerek benle işinin olduğunu aracıyla yanıma geleceğini ve hazırlanmam gerektiğini söylemesi üzerine ben de ağaç sulama işini bırakarak ikametimin önünden Salim Güran'ı beklemeye başladım.

Nevzat Bahtiyar : Yok yukarıya çıkmıştım.

Mahkeme Başkanı : Nasıl yani?

Nevzat Bahtiyar : Arif Güran'ın evine gitmiştim.

Mahkeme Başkanı : Şimdi O "Seninle işimiz var gel" dedikten sonra yaya olarak mı yukarıya çıktın?

Nevzat Bahtiyar : Evet yukarıya çıktım.

Mahkeme Başkanı : O sırada arabanız neredeydi?

Nevzat Bahtiyar : Arabam aşağıdaydı.

Mahkeme Başkanı : Aşağıdaydı. Siz yaya olarak Arif Güran'ın evinin etrafındaydınız öyle mi?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Salim Güran neredeydi bu arada?

Nevzat Bahtiyar : Yukarıdaydı.

Mahkeme Başkanı : Yukarı dediğiniz yer neresi?

Nevzat Bahtiyar : Yani bizim evin üstüydü.

Mahkeme Başkanı : Sizin evinizin üstü Arif Güran ve evinin ahırının orası mı?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Orada Salim Güran'la mı buluştunuz?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Peki orada buluştuğunuzda başka kim vardı?

Nevzat Bahtiyar : Başka kimseye görmedim.

Mahkeme Başkanı : Şimdi Nevzat Bey, saat 15:18'de, 15:08'de Salim'i arıyor ve telefon görüşmeniz var. 15:18'de Arif'in evinin yakınlarındasınız. Sizi çağırdığında Arif'in evinin yakınlarındayken başka Salim dışında başka birini gördünüz mü?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Yok. "İkametimin önündeki ağaçları sulamaya başladıktan yaklaşık 15 dakika sonra ikametimden yaklaşık 100 metre mesafede ve benim ikametime göre yüksekte kalan Arif Güran'a ait ikametin bahçesinden Salim Güran bana seslenerek benimle işi olduğunu, aracıyla yanıma geleceğini hazırlanmamın gerektiğini söylemesi üzerine ben ağaç sulama işini bırakarak ikametin önünde Salim Güran'ı beklemeye başladım." dedi daha önceki beyanında. Huzurdaki beyanında ise yürüyerek gittim, arabayla gitmedim dedi. Bu sırada etrafta herhangi bir kişi veya araç göremedim. Akabinde birkaç dakika sonrasında Salim Güran 47 XX 388 plaka sayılı Renault marka aracıyla ikametimin önüne köy içerisinde bulunan okul tarafından değil de cami tarafından gelerek durdu.

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Şimdi Salim Güran sana gel benimle işim var dediğinde neredeydi de arabayla geldi ben anlamadım?

Nevzat Bahtiyar : İşim var yukarıdaydı o.

Mahkeme Başkanı : Tamam.

Nevzat Bahtiyar : Ben avluda ağaçları sulama yapıyordum. Dedi "Seninle bir işim var" ben dedi "Yukarıya gelir misin?", dedim tamam geliyorum.

Mahkeme Başkanı : Tamam ondan sonra o sırada arabasıyla mıydı o?

Nevzat Bahtiyar : Açıkta bekliyordu. Arabası yoktu.

Mahkeme Başkanı : Buradaki de çelişkiye gitti. "Bana hemen arabaya bin ve beni takip et" dedi. Böyle bir şey oldu mu?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Olmadı. Bu sırada Salim Güran'ın kullandığı araç içerisinde herhangi bir kimseyi ya da battaniyeyi görmedim. Salim Güran aracıyla hareket etmesi üzerine ben de oğlum adına kayıtlı ancak kullanımımda olan 23 XX 630 plaka sayılı ile aracımla kendisini takip etmeye başladım. Buralar yok o zaman. Böyle bir şey değil. Tamamen yaya olarak görüştünüz. Peki neden savcılıkta böyle bir beyanda bulundunuz o zaman?

Nevzat Bahtiyar : Biraz korkmuştum.

Mahkeme Başkanı : Kimden korkmuştunuz?

Nevzat Bahtiyar : Beni silahla ve ailemle tehdit ettiği için o zaman korkmuştum ifademi...

Mahkeme Başkanı : Tam ve rahat veremediniz. Şu an herhangi bir baskı, işkence, şiddet altında mısınız?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Şu an kendi hür iradenizle bu beyanlarda bulunuyorsunuz doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Peki size bu beyanlarda bulunmanız için ya da bu beyanlarınızı dinleyenler için değiştirmeniz için bu soruşturma dava açıldıktan sonra herhangi bir baskı yapıldı mı?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Birileri tarafından para verilip Nevzat suçu kabul et, Narin'i öldürdüğünü kabul et, ikrar et, sana bakarız, çocuklarına bakarız, arsa veririz. Böyle bir teklifte bulunuldu mu? Böyle bir teklifte de Salim Güran ve ailesi tarafından bulunulmadı değil mi?

Nevzat Bahtiyar : Yok ben görmemişim hiç.

Mahkeme Başkanı : Yani sana böyle bir teklifte bulunan oldu mu?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Cezaevinde olmadı. Tamam. Şimdi biz aslında şu beyanı okuyacağız. Ondan sonra bu çelişkileri giderdikten sonra daha sonra Arif Güran'ın evinin olduğu tarafa gittim. Ben sana ilk beyanını okudum. İlk beyanındaki çelişkileri sordum. İkinci beyanındaki anlattığın hususa geçiyorum şimdi. "Daha sonra Salim Güran ile birlikte Arif Güran'ın evine girdik. Bu eve girdiğimizde bir odaydı. Tüm odaların kapıları kapalı vaziyetteydi." Doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : "Ben evin içinde Enes Güran, Yüksel Güran, Eren Güran, Muhammed Güran ya da başka hiç kimseyi görmedim."

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : "Herhangi bir ses de duymadığımdan kapıları kapalı olan odaların içerisinde bulunup bulunmadıklarını bilmiyorum."

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : "Eve girdiğimizde Salim Güran beni solda bulunan odalardan birine götürdüğünde Narin Güran'ın yerde hareketsiz yatar vaziyette olduğunu gördüm."

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Şimdi Nevzat Bey benim aklıma takılan husus şu. Şimdi Salim sana "Gel bir işim var" dedi. Sen Salim'in yanına gittin doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Bu sırada sen evin içerisinde herhangi bir bağrışma sesi, herhangi bir çağrış sesi, çocuğun öldürülme sesine ilişkin bir ses duydun mu?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Yani evden herhangi bir bağırışma sesi duymadın mı?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : O zaman sen Salim'in seni neden eve çağırdığını bilmiyordun?

Nevzat Bahtiyar : İlk önce bilmiyordum.

Mahkeme Başkanı : İlk önce bilmiyordun. Eve girip Narin'in cesedini görünce öğrendin. Bu sırada tekrar soruyorum. Bu soruyu tekrar tekrar da soracağım. İyi düşün. Narin'in, Salim'in dışında söz konusu yerde başka biri var mıydı?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Emin misin?

Nevzat Bahtiyar : Eminim.

Mahkeme Başkanı : O Arif'in eviyle Salim'in evi yan yana. Aralarında ciddi bir mesafe yok. Birbirlerinin bağırışmalarını görebilir. Salim'in evine dikkat ettiğinde herhangi biri var mıydı?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Yok. Tamam. "Eve girdiğimizde Salim Güran beni solda bulunan odalardan birine götürdüğünde Narin Güran'ın yerde yatar hareketsiz vaziyette olduğunu gördüm. Hatırladığım kadarıyla Narin Güran'ın ağzından köpük şeklinde sıvı vardı. Salim Güran bana Yüksel'le birlikte olduğumuzu kız gördüğü için bu kız beni öldürdü. Bu kızı ben öldürdüm. Artık sen de benim suç ortağımsın. Bu olaya tanık oldun. Dolayısıyla bunu yok edeceksin. Yoksa senin oğlunu gittiği futbol okulundan aldırırım kafasına sıkarım diyerek beni tehdit etti ve bana para teklifinde bulundu." demişsin.

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Burayı bize bir daha anlatır mısın? Eve girdiniz.

Nevzat Bahtiyar : Eve girmiştim. Girdim, gittim baktım beni bir odaya girdi. Baktım, Narin yatıyordu. Orada yatıyordu. Bana söyledi böyle bir olay var.

Mahkeme Başkanı : Böyle bir olay dediği ne?

Nevzat Bahtiyar : Yani annesiyle ilişki olduğu için.

Mahkeme Başkanı : Şimdi o zaman şöyle mi? Salim'le Yüksel ilişkiye girerken Narin eve gelmiş bunları görmüş. Onlar da gördüğü için öldürmüş öyle mi dedi?

Nevzat Bahtiyar : Öyle.

Mahkeme Başkanı : Öyle dedi. Ama şimdi sen 15:08'de, Bak şimdi bu HTS kayıtları var. Senin kullanmış olduğun telefonun markası ne?

Nevzat Bahtiyar : Samsung.

Mahkeme Başkanı : Samsung. A5 miydi?

Nevzat Bahtiyar : C3.

Mahkeme Başkanı : Öyle bir şeydi, tamam. Ona baktık biz de. Çok önemli değil. Kullanmış olduğun hat?

Nevzat Bahtiyar : Otuz üç.

Mahkeme Başkanı : Turkcell. şimdi bak HTS raporu alındığında sen 15:08'de Salim'i arıyorsun ya bu su için. Doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Daha sonra 15:18 yaklaşık 10 dakika sonra Arif'in evinin yakınlarındasın. Salim sana gel diyor. Doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Şimdi bizim en son kamera kaydımıza göre de dosyada bulunan en son kamera kaydına göre de Narin 15:15'de Tavşantepe okulu güvenlik kamerasından patikaya doğru giden yolda gözüküyor. Narin'in eve gelme vaziyetini biz 5 dakika ilave edelim. 20 dakika diyelim. 15:20'deyken bu süre zarfında Salim senin yanında mıydı? Hangi ara Yüksel ile ilişkiye girdi de Narin gördü?

Nevzat Bahtiyar : Bilmiyorum. Görmemiştim.

Mahkeme Başkanı : Tekrar soruyorum. 15:08'de 15:18 gel dediğinde Salim'i hiç gördün mü gel diyene kadar? "Seninle bir işim var" diyene kadar görmedin?

Nevzat Bahtiyar : Görmedim.

Mahkeme Başkanı : Ama sen bu arada evin etrafındasın.

Nevzat Bahtiyar : Ben evdeydim.

Mahkeme Başkanı : Hangi evde?

Nevzat Bahtiyar : Kendi evimde.

Mahkeme Başkanı : Kendi evinde miydin bahçeyi mi suluyordun?

Nevzat Bahtiyar : Evet kendi evimden bahçeyi suluyordum.

Mahkeme Başkanı : Senin evin ile Arif'in evinin arası kaç metre takriben?

Nevzat Bahtiyar : 50 metre falan var.

Mahkeme Başkanı : Salim'in evi ne kadar? O da çok yakın?

Nevzat Bahtiyar : O da yakın.

Mahkeme Başkanı : Yani sen bu sırada Salim'i dışarıda görmedin.

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Salim'i ilk gördüğünde Arif'in evinden mi çıkmıştı?

Nevzat Bahtiyar : Yok ben görmedim o zaman.

Mahkeme Başkanı : Sen Salim'i sadece bahçede gördün.

Nevzat Bahtiyar : Bahçede sulama yaptım. Yukarıya geldi ben onu gördüm. Başka görmedim.

Mahkeme Başkanı : Yukarıya nereden geldiğini görmedin.

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Salim'in bu sırada arabası neredeydi onu gördün mü?

Nevzat Bahtiyar : Arabasını görmemiştim orada.

Mahkeme Başkanı : Arabasını da görmedin. Sen evinde sulama yaparken, çünkü tekrar tekrar söylüyorum, çünkü kopuk kopuk ifade aldığımız için, ifadelerimiz net olsun diye tamam mı? O yüzden tekrar tekrar soruyorum. Sen Salim'i aradıktan sonra evinde bahçeyi sularken akabinde yaklaşık kaç dakika sonra? 10-15 dakika sonra Salim'in sana seslenmesi üzerine Salim'i gördün, doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Onun dışında hiçbir şey görmedin.

Nevzat Bahtiyar : Yok. 

Mahkeme Başkanı : Tamam. Peki eve girdiniz. Evde Narin'in cesedini gördün. Sonra Salim'le ne konuştunuz? Orayı tekrar bize anlatır mısın?

Nevzat Bahtiyar : Sonra bana söyledi, bunu götürüp kaybedeceksin.

Mahkeme Başkanı : Nereye kaybedeceksin dedi?

Nevzat Bahtiyar : Götürüp bir yere at.

Mahkeme Başkanı : Zaten orada ifadenin burası eksik. Nevzat Bey. Şimdi eve girdin. Cesedi gördükten sonra siz nasıl bir plan yaptınız? Sana kim akıl verdi çuval almayı? Sana kim akıl verdi söz konusu dereye götürüp onu atmayı? Bunları nasıl planladın? Kim düşündü? Nereden aklına geldi? Ya da kim söyledi sana?

Nevzat Bahtiyar : Salim söyledi.

Mahkeme Başkanı : Salim sana bunu kaybet mi dedi? Cesedi al, dere kenarına, oraya mı bırak dedi?

Nevzat Bahtiyar : Evet. Söyledi, oraya at. Bir de parça parça halinde suya at. Kimse görmesin, kaybolsun. Ben de oraya götürdüm.

Mahkeme Başkanı : Peki hayatında başka bir ceset gördün mü?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : İlk defa bir ceset görüyorsun. Peki bu soğukkanlılık nereden geliyor? Yani ceset gören bir insanın eli ayağına dolaşması gerekirken sen cesedi alıp, çuvala koyup ya da bilmem nereye götürmen bunun nasıl soğukkanlılıkla aldın bunları yaparken?

Nevzat Bahtiyar : Biraz şey oldum. İlk gördüğüm zaman biraz yani tüm vücudum tutuldu. Ama bana dedikten sonra artık mecbur kaldım. Yapmak zorunda kaldım.

Mahkeme Başkanı : Seni ne ile tehdit etti?

Nevzat Bahtiyar : Silahla tehdit etti.

Mahkeme Başkanı : Ne dedi?

Nevzat Bahtiyar : Okula giden senin oğlun Muhammed'i alıp götürürüm. İlk önce onun kafasına sıkarım sonra sana sıkarım bana dedi. Onun için mecburen baktım kabul ettim.

Mahkeme Başkanı : Peki bu sırada Enes'i falan görmedin?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Muhammed Emre'yi, Eren'i ya da hiç kimseyi görmedin?

Nevzat Bahtiyar : Yok hiç görmedim.

Mahkeme Başkanı : Tamam sonra bu planı yaptıktan sonra Narin battaniyeye sarılı mıydı sen gördüğünde?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Battaniyeyi nereden aldınız?

Nevzat Bahtiyar : Battaniyeyi Salim gitti getirdi, bilmiyorum nereden getirdi.

Mahkeme Başkanı : Başka bir odadan mı gitti getirdi?

Nevzat Bahtiyar : Odada değildi, yani arabanın içindeydi artık.

Mahkeme Başkanı : Yani Salim evin dışına mı çıktı başka bir odaya mı çıktı?

Nevzat Bahtiyar : Evet öyle çıktı.

Mahkeme Başkanı : Evden dışarıya çıktı, battaniyeyi getirdi öyle mi? Narin yerde yatıyordu doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Evin içerisinde herhangi bir ses duymadın? Kimseyi görmedin. Tamam, sonra battaniyeyi sardıktan sonra ne yaptınız?

Nevzat Bahtiyar : Battaniyeyi sardıktan sonra ben yavaş yavaş eve getirdim. Bizim evin ahırına getirdim. Orada torbaya koyduk. Orada arabanın yanına gittim. O da arabasıyla geldi bizim arabanın yanına geldi.

Mahkeme Başkanı : Bir dakika sen battaniyeyle mi aldın cesedi?

Nevzat Bahtiyar : Evet battaniyenin içine koydum götürdüm.

Mahkeme Başkanı : Battaniyenin içine nereye götürdün?

Nevzat Bahtiyar : Arabanın yanına götürdüm.

Mahkeme Başkanı : Sizin arabanız neredeydi?

Nevzat Bahtiyar : Kapının önündeydi.

Mahkeme Başkanı : Sizin kapınızın önündeydi. Peki bu sırada hiç kimse görmedi mi?

Nevzat Bahtiyar : Yok hiç kimse görmedi.

Mahkeme Başkanı : Hiç kimse görmedi. Siz aldınız battaniyeyi kucakladınız. Kendi arabanıza götürdünüz. Kırmızı 23 AN plakalı arabanıza götürdünüz doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Bu sırada etrafta hiç kimse görmedi?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Yüksel neredeydi?

Nevzat Bahtiyar : Yüksel o zaman Narin'i arabanın içine koyduğum zaman başımı kaldırdım. Baktım yukarıda ağlıyordu.

Mahkeme Başkanı : Nerede ağlıyordu?

Nevzat Bahtiyar : Tepede.

Mahkeme Başkanı : Şimdi sen evden aldıktan sonra, Narin'i battaniyeye sardıktan sonra, battaniyeye sardıktan sonra, Salim nereye çıktı?

Nevzat Bahtiyar : Ben aşağıya indikten sonra o da arabasıyla aşağıya doğru geldi.

Mahkeme Başkanı : Şimdi sen battaniye ile çıktın.

Nevzat Bahtiyar : Ben çıktım.

Mahkeme Başkanı : Sen Arif'in evinden çıktıktan sonra ilk nereye gittin? Ahıra mı gittin?

Nevzat Bahtiyar : Evet ahıra götürdüm.

Mahkeme Başkanı : Kimin ahırı bu?

Nevzat Bahtiyar : Bizim ahırdı.

Mahkeme Başkanı : Sizin ahırınız. Neden ahıra götürdün?

Nevzat Bahtiyar : Orada torbaya koydum.

Mahkeme Başkanı : Nereden aklına geldi bu?

Nevzat Bahtiyar : Torbaya koydum.

Mahkeme Başkanı : Niye battaniyeyle götürmedin de torbaya koymak aklına geldi? Bu senin mi aklına geldi? Bunu sen mi düşündün? Senin mi aklına geldi? Salim mi söyledi?

Nevzat Bahtiyar : Ben düşündüm.

Mahkeme Başkanı : Yani Salim sana battaniyeyle verdi, bunu yok et dedi.

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Ondan sonraki planlamalarda Salim'in hiçbir şeyi yok. Sen planladın öyle mi?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Yani çuvala koymak nereden aklına geldi, ben onu da idrak edemedim.

Nevzat Bahtiyar : Ahıra götürdüm. Bizim çuval oradaydı. Çuvalın içine bırakayım.

Mahkeme Başkanı : Peki Narin kızımızda bu sırada kıyafetleri var mıydı? Üzerinde? Çıplak mıydı? Kıyafetli miydi?

Nevzat Bahtiyar : Kıyafet vardı.

Mahkeme Başkanı : Kıyafetlerini hatırlıyor musun?

Nevzat Bahtiyar : Siyah tişört vardı.

Mahkeme Başkanı : Çantasını falan hatırlıyor musun?

Nevzat Bahtiyar : Hatırlamıyorum.

Mahkeme Başkanı : Hatırlamıyorsun. Çuvala koydun. "Ben de cesedi kucağıma alarak ikametten çıktığımda kapı önünde bulunan Narin'e ait terlikleri de Salim'in söylemesi üzerine alıp battaniyenin içerisine koydum."

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : "Ve aracıma koymak üzere ikametime doğru indim."

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : "İlk önce kendime ait ahıra pencereden cesedi koydum."

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : "Daha sonra ahırda bulunan çuvalı cesedin başından geçirdim. Çuvalı aceleyle cesedin başından geçirdim ancak çuvalı bağlamamıştım. Daha sonra cesedi kendi aracımın arka koltuk paspas kısmına bıraktım."

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Battaniyeyi ne yaptınız?

Nevzat Bahtiyar : Battaniyeye Salim geldi, arabasıyla geldi. Arabasıyla geldi, battaniye benden aldı. O zaman aşağıya doğru indiler. Bilmiyorum artık hangi tarafa gittiğini bilmiyorum.

Mahkeme Başkanı : Şimdi Salim senin ahırına arabayla mı geldi?

Nevzat Bahtiyar : Yok yok. Kapının önüne, arabanın yanına geldi.

Mahkeme Başkanı : Şimdi bir dakika, baştan alıyorum. Sen ahıra gittin, çuvala koydun. Battaniyeyi nerede bıraktın?

Nevzat Bahtiyar : Battaniyeyi arabanın yanına götürdüm.

Mahkeme Başkanı : Çuvalla birlikte battaniyeyi de götürdün?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Tamam. Battaniye ıslak mıydı?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Yani şimdi şöyle, bu Salim'in arabasında çıkan bir DNA var. Ağzında köpükler var. Şimdi bu battaniye ıslak olup, o ağzından çıkan köpükler ya da salyalar ya da başka bir şey battaniyeye bulaşıp, battaniyeyi alıp Salim'e bulaşmış ihtimali olabilir mi? Yani battaniyede bir ıslaklık var mıydı?

Nevzat Bahtiyar : Hiç farkına varmadım.

Mahkeme Başkanı : Dikkat etmedin, bilmiyorsun. Sonra kendi evine geldin. Battaniye ve çuvalla geldin. Sizin evde kim kalıyor? Eşiniz?

Nevzat Bahtiyar : Eşim kalıyordu.

Mahkeme Başkanı : Anneniz, babanız sizde mi ikamet ediyor?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Eşiniz bu sırada neredeydi?

Nevzat Bahtiyar : Annem evin içindeydi.

Mahkeme Başkanı : Eşiniz?

Nevzat Bahtiyar : Eşim de içerideydi.

Mahkeme Başkanı : Ama dışarıda değillerdi?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Daha sonra arabanıza çuvalı koydunuz. Artık çuval diyoruz, ceset, Narin çuvalın içerisinde. Çuvalı arabanızda nereye koydunuz?

Nevzat Bahtiyar : Arabanın arka koltuklarına koymuştum.

Mahkeme Başkanı : Arabanın arka koltuğuna? Paspas kısmına koydunuz, öyle mi?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Tamam. Bu sırada Salim mi geldi yanınıza?

Nevzat Bahtiyar : Salim geldi.

Mahkeme Başkanı : Salim ne dedi size?

Nevzat Bahtiyar : Bana söyledi, onu götür. Biz göl diyoruz.

Mahkeme Başkanı : Tamam, göl diyoruz. Göle?

Nevzat Bahtiyar : Oraya götür, parça parça haline at. Kimse görmesin. Ben de o zaman oraya götürdüm. Ben hiç karışmadım. Yani cesedine karışmadım, cesedini oraya bıraktım.

Mahkeme Başkanı : Çuvalı bıraktınız. Arif Bey biraz daha sakin olabilir miyiz? Arif Bey bir yan tarafta lavabo var. Bir oraya götürüp yüzünüzü yıkayabiliriz istiyorsanız. Lavaboyu bir götürelim. Tamam. Oraya götürdünüz, çuvalı bir şekilde attınız, öyle mi?

Nevzat Bahtiyar : Evet, oraya bıraktım.

Mahkeme Başkanı : Peki bu bıraktığınız yeri Salim'e söylediniz mi?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Peki Salim daha sonra bu olaydan akşamleyin saat 22:47'de söz konusu çuvalın, cesedin bulunduğu yere gidiyor. Orayı nereden biliyor Salim?

Nevzat Bahtiyar : Yukarıdan gözüküyor orası.

Mahkeme Başkanı : Yani sizin göl dediğiniz yer orası değil mi?

Nevzat Bahtiyar : Evet, göl.

Mahkeme Başkanı : Sen bu olaydan sonra, göle attıktan sonra Salim'le görüştün, ben bu işi hallettim, tamamdır gibi bir şey verdin mi ona?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Peki sana Salim sordu mu bu iş tamam mıdır diye?

Nevzat Bahtiyar : Yok, hiç görüşmedik.

Mahkeme Başkanı : Ondan sonra hiç konuşmadınız?

Nevzat Bahtiyar : Konuşmadık.

Mahkeme Başkanı : Salim'e nereye koyduğunu, şu ağacın altına koydum, taş koydum gibi bir şey de söylemediniz? O zaman Salim kendi inisiyatifiyle gece vakti o bulunduğu dereye gidip çuvalı mı gözlemledi?

Nevzat Bahtiyar : Bilmiyorum onu. Ben ilk oraya götürdüğüm zaman evin yanından orası gözüküyor.

Mahkeme Başkanı : Arabanızı görmüş olabilir. Peki bu arama sıralarında bu olay oldu. 21.08'de bunlar gerçekleşti. Akabinde Narin'in kayıp ihbarında bulunuldu, doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Kayıp ihbarı bulunulduktan sonra Salim'le bir konuşmanız, görüşmeniz oldu mu?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Yani Salim sana ağzını sıkı tut, çeneni kapat, sakın kimseye bir şey söyleme gibi bir şeyler söylemedi mi bu olaydan sonra?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Hiç konuşmadınız bu olaydan sonra?

Nevzat Bahtiyar : Sadece bir kere bizim annemin avlusuna geldi. Orada bir kuyu vardı, eski bir kuyu. Jandarmalarla birlikte oraya gelmişti. Orada onunla konuştum. Başka hiçbir konuşmam olmadı.

Mahkeme Başkanı : Hiç konuşmanız olmadı. Peki siz niye ceset bulunana kadar gelip doğruları anlatmadınız da ceset bulunduktan sonra konuşma ihtiyacı hissettiniz?

Nevzat Bahtiyar : Korkmuştum.

Mahkeme Başkanı : Kimden korktunuz? Siz bu köyde yabancısınız değil mi? Yani bu köy Güran Ailesi'nin köyü mü, sizin kendi köyünüz mü?

Nevzat Bahtiyar : Onların köyü.

Mahkeme Başkanı : Sen bu köyde dışarıdan gelmiş ve köyde konaklayan birisin, doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : O esnada yukarı doğru, yani Arif Güran'ın evine doğru baktığımda Yüksel Güran'ın yüzünü ellerinin arasına bırakmış şekilde ağlayarak baktığını gördüm demişsiniz. Pencereden gördünüz yani?

Nevzat Bahtiyar : Arabanın yanında gördüm.

Mahkeme Başkanı : Arabanın neresinde gördün? Dikiz aynasından mı gördün, arabadan arkaya bakıp mı gördün? Yoksa arabada giderken yandan mı gördün?

Nevzat Bahtiyar : Arabanın üstüne koyduğum zaman kapıyı kapattım. Yukarı baktım yukarıda ağlıyordu.

Mahkeme Başkanı : Daha araba hareket etmeden, kendi evinin önündeyken gördün, öyle mi?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : O pencereden bakıyordu, öyle mi? Yüksel?

Nevzat Bahtiyar : Yok. Bizim evin önü yüksektir.

Mahkeme Başkanı : Yani evinden çıkmıştı, evin içindeydi?

Nevzat Bahtiyar : Değildi, onu ben bilmiyorum. Onu tepede gördüm. Başka yerde görmemiştim.

Mahkeme Başkanı : Yüksel'i evde değil, o evinin ahırının olduğu yerde, tepede seni izlerken gördün?

Nevzat Bahtiyar : Doğrudur.

Mahkeme Başkanı : Oraya nasıl geldiğini bilmiyorsun. Enes'i gördün mü bu sırada?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Enes konusunda herhangi bir fikrin yoktur?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Peki, tekrar baştan aynı soruyu sormak gerekirse, Narin'in nasıl öldürüldüğünü, yani boğarak mı öldürmüşler, bıçaklayarak mı öldürmüşler, zehir vererek mi öldürmüşler ya da başka bir ihtimalle öldürüp öldürülmediğini biliyor musun?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Sen eve geldiğinde Narin'in öldüğünü biliyorsun. Sence Narin'in nasıl öldürülmüş olabilir?

Nevzat Bahtiyar : Bence bilmiyorum yani, artık boğarak öldürmüş olabilir, ben onu düşünüyorum.

Mahkeme Başkanı : Onu düşünüyorsun ama Narin'de herhangi bir kanama, bıçak, öyle bir şeye rastladın mı, kan var mıydı?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Yoktu. O zaman Enes'e de iştirak halinde kasten öldürmekten dava açıldı. Enes, senin anlattığına göre Salim ile Yüksel öldürmüş oluyor. Enes bu işin neresinde?

Nevzat Bahtiyar : Bilmiyorum.

Mahkeme Başkanı : Enes konusunda bilgin yok. Eğertutmaz deresine doğru cesedi götürdün ve daha önce Narin'in bir ayağı çuvalın dışında kalmıştı. "Aceleyle ve telaşla yaptığım için bağlayamadım, bunu da düzeltemedim. Cesedi belirttiğim şekilde bıraktıktan sonra olay yerinden ayrıldım". Peki neden cesedi parçalamadın da bir bütün halinde çuvalın içerisinde koydun?

Nevzat Bahtiyar : Ben yapamadım, bak yani vicdanım...

Mahkeme Başkanı : Onu yapamadın?

Nevzat Bahtiyar : Yapamadım.

Mahkeme Başkanı : Peki çuvalın içerisine koyarken, o çuvalın o gölden akması için, yani sonuçta çuvalın hareket halinde gidebilir, su alıp götürebilir. Su alıp götürmesin diye taşlarla falan sabitledin mi?

Nevzat Bahtiyar : Sadece bir taş bırakmıştım.

Mahkeme Başkanı : O taşı neden bıraktın?

Nevzat Bahtiyar : O taşı bıraktım, yani suyun altına gitsin diye ben şey yapmıştım.

Mahkeme Başkanı : Ama sen suyun altına gitmesin değil de, o çuvalı direkt suya atsaydın, su götürseydi, sana verilen talimat bu değil miydi?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Sen bunu kendi inisiyatifinle yaptın, doğru mu? Salim'in, yani onu taşa koy o orada kalsın, öyle bir ihtimal var mı?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Çünkü sonraki aşamalarda Yüksel'in basın açıklamasında radyo ya da televizyona verdiği röportajlarda "Kim öldürdüyse getirsin, en azından cesedin yerini bilelim" şeklinde açıklamaları var. Bunları görmüşsündür aramalar yapılırken, doğru mudur? televizyonlarda?

Nevzat Bahtiyar : Hatırlamıyorum.

Mahkeme Başkanı : Hatırlamıyorsun, Peki bu olaydan sonra Yüksel seninle herhangi bir konuşma gerçekleştirdi mi?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Enes'in bir konuşması oldu mu?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : O zaman senin oraya çuvalı taşıdığını sadece Salim ile Yüksel biliyordu öyle mi?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Arif Güran da bilmiyordu öyle mi?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Peki şunları sorayım ondan sonra diğer hususlara geçeyim, şimdi Salim beyanlarında ise ilk beyanlarında tarla işi yaptığını, ardından eve gittiğini, söz konusu yerlerde olmadığını iddia ediyor. Daha sonra, bu olaydan sonra da, tekrar tarlaya gidiyor. Sen Salim'i Bu olaydan sonra ne yaptığını biliyor musun?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Sen tarlaya cesedi bıraktıktan sonra ne yaptın?

Nevzat Bahtiyar : Bıraktıktan sonra ben baldızımın evine gittim.

Mahkeme Başkanı : Baldızınız Zeynep'in evine gittiniz, tamam.

Nevzat Bahtiyar : Bize peynir hazırlamıştı, peyniri aldım eve gittim.

Mahkeme Başkanı : Şimdi Nevzat, anlattığın hususlar, doğru cümleyi bulmak için... çok soğukkanlı anlattığın hususlar. Şimdi hayatında ilk defa bir ceset gördüm diyorsun, doğru mu? "Cesedi gördüm, ne yapacağımı bilemedim, o yüzden parçalayamadım." diyorsun ama cesedi oraya bıraktıktan sonra da hiçbir şey olmamış gibi hayatına devam ediyorsun.

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Bu ikisi çok zor. Sen hayatında ilk defa mı ceset görüyorsun?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Bu soruya cevap vermeme hakkına sahipsin sen daha önce hayatında birini öldürdün mü?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : İlk defa hayatında bir ceset gördün, o cesedi yok ettin, daha sonra hiçbir şey olmamış gibi baldızına peynir almaya gittin öyle mi?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Söz konusu tekrar tekrar soruyorum ki cımbızla laf alıyoruz, cımbızla laf aldığımız için zabıtlara düzgün geçsin diye. Arkadaşlar sorduğum sorulara siz de dikkat edin ki aynı soruları siz de sorabilirsiniz, hakkınızdır ama mümkün mertebe aynı soruyu sorarken buna dikkat ederseniz. Salim ile "dereye at parçala" dışında başka bir görüşmeniz, konuşmanız herhangi bir ona bilgi vermen hiç olmadı?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Ta ki kendin etkin pişmanlıkta bulunup, daha doğrusu buna etkin pişmanlık demeyelim, itirafta bulunana kadar bu konuda hiç kimseyle görüşmedin öyle mi?

Nevzat Bahtiyar : Öyle.

Mahkeme Başkanı : İtirafta bulunmaya da kendin karar verdin öyle mi?, Neden itirafta bulundun?

Nevzat Bahtiyar : Vicdanım.

Mahkeme Başkanı : Neyse vicdanın kabul etmedi diyelim, battaniyeyi Salim'in ne yaptığını bilmiyoruz. Cezaevinde sana herhangi bir haber gelmedi; cinayeti kabul et, beyanlarını değiştir, buna ilişkin bir beyan gelmedi doğru mu?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Kardeşinin bu hususta "Ağabeyime Ali Rıza tarafından haber gönderildi, Nevzat tüm suçu kabul etsin biz ona araba tarla verelim" dedi; sana böyle bir talep geldi mi?

Nevzat Bahtiyar : Geldi.

Mahkeme Başkanı : Yok dedin ya.

Nevzat Bahtiyar : Yok şimdi teklif geldi kardeşim böyle bir teklif var dedi ama gelip bana dememişler.

Mahkeme Başkanı : Hııh tamam sana kimse böyle bir teklifte gelip bulunmadı ama kardeşin gelip "abi böyle bir teklif var" dedi. Peki eşinden sana herhangi bir haber geldi mi?

Nevzat Bahtiyar : Gelmedi.

Mahkeme Başkanı : Bu soruya da cevap vermeme hakkına sahipsin, Arif Güran, Salim'in senin eşinle bir ilişkisi olduğunu iddia ediyor. Öyle bir basın açıklaması var. Senin de iftira attığın yönünde bir takım haberler var. Böyle bir şey doğru mudur?

Nevzat Bahtiyar : Ben böyle bir şey söylememiştim, yani gözümle görmemişim.

Mahkeme Başkanı : Bilmiyorsun. Sen Arif Güran ailesine Salim ya da Güran  ailesine bir iftira atıyor musun?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Aranızda herhangi bir husumet var mıdır?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Onlar diyor ki; Salim Güran'ın avukatı tutukluk itirazında şöyle bir şey var "Nevzat para veriyordu, yine Olay günü Narin'e para verdi, Narin'e kendisine alıştırdı ve olay günün Narin'i öldürdü, bunu 3-4 gün önceden planlıyordu. Bu yüzden dolayı da çocuklara para veriyordu." diye bir iddiaları var bu iddia hakkında ne diyorsun?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Çocuğa para veriyor muydun?

Nevzat Bahtiyar : Yok, vermedim.

Mahkeme Başkanı : Yine sanık müdafileri okuldan çıktıktan sonra Narin'in kendi evine gitmesi için Nevzat Bahtiyar'ın evinin önünden ya da ahırının önünden geçmesi gerekiyordu diyorlar, doğru mu?

Nevzat Bahtiyar : Biraz uzaktır, 30-40 metre mesafe vardır.

Mahkeme Başkanı : Yani o patikadan geçtikten sonra kendi evine ulaşması için senin evin önünden geçmesi gerekiyor mu?

Nevzat Bahtiyar : Yani başka yerden de geçse, o zaman çok uzak kalırdı. En yakın, yani, mesafe oradadır oradan geçmiş.

Mahkeme Başkanı : Peki, yani sen bu sırada herhangi bir plan dahilinde; şimdi şöyle, ben sanıklar müdafilerinin itiraz ederindeki itirazlara söylüyorum, mahkemenin kabulü değildir. Bu konuda herhangi bir şey olmasın, sanık müdafilerine tutukluluk itirazındaki dilekçeleri okuyorum, tamam mı? Şimdi diyorlar ki; senin annen tüm Güran ailesinin erkeklerinin davetiye dağıtmak için köy dışında olduklarını, annenin bunu duyduğunu, annenin bunu sana söylediğini, bunun üzerine senin de Narin'i öldürme planı yaptığını, olay günü evin önünde Narin'i beklediğini, Narin gelince onu aldığını ve öldürdüğünü iddia ediyorlar.

Nevzat Bahtiyar : Doğru değil.

Mahkeme Başkanı : Senin bir husumetin var mıdır Güran ailesiyle?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Sen onların işçisi misin?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Sen köyde sıva işleriyle uğraşan; köyde mi şehirde mi yapıyorsun?

Nevzat Bahtiyar : Köylerde yapıyorum.

Mahkeme Başkanı : Güran ailesinin tarlasında çalışıyor musun?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : O zaman beyanların arasında çelişkiler var. Huzurda verdiğin beyan kendi hür iradenle mahkememize verdiğin ifaden doğrudur?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Bunlar verdiğin en net beyanlardır doğru mudur?

Nevzat Bahtiyar : Doğru.

Mahkeme Başkanı : Savcılıkta verdiğin beyanlarda korktuğun için farklı farklı anlattın öyle mi? Salim sana terlikleri verdi öyle mi?

Nevzat Bahtiyar : Evet.

Mahkeme Başkanı : Terlikleri verirken bir şey söyledi mi?

Nevzat Bahtiyar : Yok, bir şey söylemedi.

Mahkeme Başkanı : Al bu delilleri gizle manasında, öyle mi?

Nevzat Bahtiyar : Ben aldım çuvala koydum.

Mahkeme Başkanı : Başka sormadığımız unuttuğumuz başka bir şey var mı? Notlarımıza bakalım; Sayın savcım sormak istediğiniz bir şey var mı?

## Duruşma Savcısı

Duruşma Savcısı : Sormak istediğimiz sorular var. Nevzat Bahtiyar, az önce mahkeme huzurundaki beyanında Salim'in seni silahla korkuttuğunu söyledin.

Nevzat Bahtiyar : Doğru.

Duruşma Savcısı : Olay günü 15:27 - 15:35 arası dördünüz aynı yerdesiniz; kendi baz bilgilerimizden bahsediyorum. Bu süreçte mi seni tehdit etti? Yanında silahı var mıydı? Bu silahla tehdit olayı nerede oldu?

Nevzat Bahtiyar : Yanında silahı vardı, çıkardı.

Duruşma Savcısı : Ne yaptı çıkarıp?

Nevzat Bahtiyar : Silahla tehdit etti, "Bu cesedi kaybedeceksin, yoksa senin oğlunu götürüp sonra seni de çağırırım, senin gözünün önünde kafasına sıkarım. Sonra senin kafana sıkarım". Bana böyle bir tehditte bulundu, mecbur kaldım.

Duruşma Savcısı : Yani yanındaki silahla yaptı bunu?

Mahkeme Başkanı : Sayın savcım, çok özür diliyorum. Peki Salim sonuçta senin iddiana göre bir cinsel ilişki sırasında Enes'i görüyor, dolayısıyla Salim'in bu esnada kıyafeti nasıldı?

Nevzat Bahtiyar : Hatırlamıyorum.

Mahkeme Başkanı : Yani alelacele giyinmiş bir kıyafet miydi?

Nevzat Bahtiyar : Hatırlamıyorum.

Mahkeme Başkanı : Yani olay nedeniyle bir ter ya da dikkatini çeken bir şey oldu mu?

Nevzat Bahtiyar : Hiç dikkat etmedim.

Mahkeme Başkanı : O da senin gibi soğukkanlıydı?

Nevzat Bahtiyar : Hatırlamıyorum.

Duruşma Savcısı : Salim Güran'ın döndürülen WhatsApp görüntülerinde saat 17:46'da Senden gelen 41 saniyelik bir görüşme var; 0533XXX9779 senin numaran değil mi? Bu numaradan gelen 41 saniye süren bir çağrı var, saat 17:46'dan bahsediyorum. Sen dereye götürüp işini hallettin değil mi? Bu görüşmede neden bahsettiniz?

Nevzat Bahtiyar : Hiç görüşmedim.

Mahkeme Başkanı : 41 saniyelik bir görüşme var.

Nevzat Bahtiyar : Hiç görüşmemişim.

Duruşma Savcısı : Tamam, Salim Güran akşam 22:44'de bazı bilgileri vererek ve kamera görüntülerinden Narin kızımızın cansız bedeninin bulunduğu yere gidiyor. Sence sen tek taştan veya 2-3 taştan bahsediyorsun, değil mi? Cansız bedene bırakılan üzerinde ekstra bir çalı çırpı daha var, bunu Salim Güran yapmış olabilir mi?

Nevzat Bahtiyar : Bir fikrim yok, görmemişim.

Mahkeme Başkanı : WhatsApp'tan neden aradın? ben oraya kaçırdım.

Nevzat Bahtiyar : Ben kimseyi aramamışım.

Mahkeme Başkanı : Sayın savcımın bahsettiği numarayı sen kullanıyorsun, değil mi?

Nevzat Bahtiyar : Normal olarak ben onu bir kere aramışım.

Mahkeme Başkanı : Getirilen bilgilerde, WhatsApp geçmişinde senin söz konusu saatte 17:46'da Salim'i aradığın tespit edilmiş.

Nevzat Bahtiyar : Ben hiç aramadım bilmiyorum.

Mahkeme Başkanı : O saatte sen peynir mi almaya gitmiştin baldızına?

Nevzat Bahtiyar : 17:30'da ben Çarıklı'daydım.

Duruşma Savcısı : Olay günü tekrar dereye Narin'i kucağında götürdüğünü söylüyorsun, değil mi? Çuval içerisine, çuvala koydun, ağzını iple bağlamadın. Dereye doğru yürüdün. Ağustos ayında Ağustos'un sıcağında, dereye doğru yürüdün. 25 kilo bir kız, tek başına mıydın?

Nevzat Bahtiyar : Tek başımaydım.

Duruşma Savcısı : Yanında Salim yoktu, yürüdün. İp aradın, ipi nerede buldun orada?

Nevzat Bahtiyar : Çantanın ipini ben kesmiştim onunla bağlamıştım.

Duruşma Savcısı : İp almadan giderek nasıl güvendin? Taşın çakılın arasında ipi nereden bulacaksın ki orada?

Nevzat Bahtiyar : O esnada ip hiç aklıma gelmedi.

Mahkeme Başkanı : Evet, Nahit Bey buyurun.

## Diyarbakır Barosu

### Av. Nahit Eren

Av. Nahit Eren : Bir sessizlik olursa...

Mahkeme Başkanı : Evet, sessizlik lütfen. Herkes yerinde oturabilir mi?

Av. Nahit Eren : Başkanım, soruya geçmeden önce tabi delil tartışıyoruz burada. Sadece bir cümle kuracağım. Öncelikle Diyarbakır Barosu'nun katılma konusundaki talebinin kabulü yönündeki talebi konusundaki kararınız, bu dava dosyası için anlamlı, kıymetliydi. ilk günden beri biz dava dosyasını takip ediyoruz. Ve bugün hepimiz de maddi gerçeğin açığa çıkması için bu yargılamada yerimizi almış bulunuyoruz. Ben Nevzat'a sorularımı sormaya başlıyorum. Nevzat Salim'i ne zamandan beri tanıyorsun?

Nevzat Bahtiyar : Yani... 30 yıl, 30 yıl var. Daha fazla olabilir çünkü çocukluktan beri birlikteyiz.

Av. Nahit Eren : Çok yakın dostmuşsunuz.

Nevzat Bahtiyar : Evet, doğru.

Av. Nahit Eren : Sürekli görüşüyorsunuz.

Nevzat Bahtiyar : Sürekli, yani sürekli değil. Yani... Vaktimiz olduğu zaman beni arardı, ben onu arardım. Kahveye giderdik.

Av. Nahit Eren : Mesela nerelerde buluşuyordunuz?

Nevzat Bahtiyar : En çok, yani kahvede buluşuyorduk. Yani köyde de buluşuyorduk.

Av. Nahit Eren : Köyde bir araya gelip böyle o patika yollarda yürüyor muydunuz?

Nevzat Bahtiyar : Yok. Yani çay yapardık içerdik. Yani böyle otururduk.

Av. Nahit Eren : Sen onun evine hiç gittin mi?

Nevzat Bahtiyar : Gitmişim.

Av. Nahit Eren : Evin içerisine girip misafir oldun mu?

Nevzat Bahtiyar : Misafir olmuşum.

Av. Nahit Eren : Olaya yakın zamanda hiç gittin mi?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Gitmedin.

Nevzat Bahtiyar : Biz bir kere gittik. Orada... O olayın ikinci günü değil. Ben yukarıya gittim. Orada Jandarma vardı. Böyle bir... 15-20 dakika kaldım aşağıya gittim.

Av. Nahit Eren : Peki, olay gününe gelelim. Olay günü saat 15'i 8 geçe (15:08) Salim'i aradığını söyledin.

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Salim'i aradığın zaman konuştuğun cümleleri hatırlıyor musun?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Ne konuştuğunu hatırlıyor musun?

Nevzat Bahtiyar : Ne konuştuğunu, suya baksın dedim. Onun da söylediği "tamam ekibi ararım. Ekip gelsin baksın.".

Av. Nahit Eren : Senin evinin suyu mu akmıyor?

Nevzat Bahtiyar : Evet. Bizim evimizde su akmıyor.

Av. Nahit Eren : Peki, bu konuda herhangi bir şekilde belediyeye talepte bulundun mu?

Nevzat Bahtiyar : Bilgim yok.

Av. Nahit Eren : Belediyenin dosyaya yansıyan tespitinde evinde herhangi bir su arızası olmadığına ilişkin bir tutanak var. Bilgin var mı bundan?

Nevzat Bahtiyar : Bilgim yok.

Av. Nahit Eren : Peki, saat 15:08'de görüştün. Görüştükten sonra istikameti bize tam anlatabilir misin? Gidiş istikametini. Ağaç sulamaya gittim dedin ya.

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Ağaçları nerede suladın?

Nevzat Bahtiyar : Avluda.

Av. Nahit Eren : Evinin bulunduğu yerin önündeki avluda suladın?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Kaç dakika sürdü sulaman?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Suyu nereden getirdin?

Nevzat Bahtiyar : Annemlerden getirdim.

Av. Nahit Eren : Takılı mıydı hortum?

Nevzat Bahtiyar : Hortum takılıydı.

Av. Nahit Eren : Ne kadar mesafe? Sizin ve annenin evi arasında?

Nevzat Bahtiyar : 20 metre falan.

Av. Nahit Eren : Oradan, senin evine kadar bağlı bir hortum var.

Nevzat Bahtiyar : Evet. Ben bağlamıştım. Ben... İşte gelirken ben bağladım. Bence biraz ağaçları sulama yapayım.

Av. Nahit Eren : Kaç dakika suladığını bir daha söyleyebilir misin?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Hatırlamıyorsun. Eşin Gazal ifadesinde, savcılık ifadesinde sizin Nevzat'ı aradığınızı söylüyor. Pardon, Salim'i aradığınızı söylüyor. Sonra evden çıkıp gittiğinizi söylüyor. Aslında ağaç sulayacaktı ama ağaç sulamadı.

Nevzat Bahtiyar : Evet, ağaç yok. Arka bahçedeydim o zaman. Arka bahçede orada biraz gerçekten gitmiştim. Ben oradaydım.


Av. Nahit Eren : Evin önündeki ağaçları mı, evin arkasındakini mi?

Nevzat Bahtiyar : Arkası. Arkasındakileri. Ben oradaydım. Beni görmemiş.

Av. Nahit Eren : Peki. Nevzat'ı aradın. Pardon, Salim'i aradın. Salim sana bunları söyledi. Salim'le bunları konuştuktan sonra Arif'in evine doğru mu gittin yoksa Salim'in evine doğru mu gittin?

Nevzat Bahtiyar : Arif'in evine doğru gittim.

Av. Nahit Eren : Arif'in evine doğru gittin. HTS kayıtları senin Arif'le Salim'in evinin arasına doğru gittiğini söylüyor.

Nevzat Bahtiyar : Yok. Ben o tarafa doğru gitmemiştim.

Av. Nahit Eren : Salim'in evine doğru gitmedin?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Peki ilk gittiğin zaman Salim seninle ne kadar süre bir temas kurdu dışarıda?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Siz o gün Salim'le telefondan görüştün diye, evde olduğunu biliyorsun diye gidip her zamanki dostluk hukukuyla bir araya gelme gibi bir niyetin var mıydı?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Seni bahçeye gelip yukarıdan seni çağırdı?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Senin görüşme yaptığın dakikadan kaç dakika sonra olduğunu bize söyleyebilir misin?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Hatırlamıyorsun.

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Mesela şöyle diyebilir misin? Ben şu kadar ağaç ya da şu kadar sebzenin olduğu yeri suladım suyu şu kadar değiştirdim. Bu 2-3 dakika sürer sonra beni Salim çağırdı diyebiliyor musun?

Nevzat Bahtiyar : Yok, diyemiyorum.

Av. Nahit Eren : Diyemiyorsun. Peki eve doğrudan mı yöneldin? Salim'in evine mi doğrudan yöneldin? Dışarıda sana ne söyledi de Salim'in evine yöneldiniz?

Nevzat Bahtiyar : Bana...

Av. Nahit Eren : İlk teması söylüyorum. Aradı, seslendi diyorsun. Gittin. Arif'in evinin önünde Salim duruyor. Salim'le teması kurdun. İlk anda Salim sana ne söyledi? İlk an. Selamlaştınız mı mesela?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Ne dedi sana? Peki 30 yıllık dostluktan bahsediyorsunuz. İçeri girme konusunda, Salim'le birlikte girme konusunda, çünkü Arif'in beyanı var. Ömrü hayatında Arif'in evine hiç girmemiş Nevzat dedi. Hiç daha önce girdin mi Arif'in evine? Hayatın boyunca? Bu olayla bağlantısız.

Nevzat Bahtiyar : Bir kere gitmişim.

Av. Nahit Eren : Ne zaman?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Niçin gittiğini hatırlamıyorsun? Yıl olarak mesela.

Nevzat Bahtiyar : Hatırlamıyorum. Bir sefer gitmiştim ama hatırlamıyorum.

Av. Nahit Eren : Gittin, Salim orada. Temas kurdunuz. Ne dediğini demeden eve doğru yöneldiniz.

Nevzat Bahtiyar : Oraya gittikten sonra bilmiyorum.

Av. Nahit Eren : Narin'i sormuyorum. Salim'le temas kurduğun andan itibaren eve girme sürenden bahsediyorum. Konuşmadınız, "Eve girelim" dedi. Birlikte hiçbir şey sorgulamadan eve girdin?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Eve girdin. Kapının önünde ayakkabılar var mıydı?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Eski ayakkabılar var mıydı? Birazdan soracağım için şimdiden sorayım. Terlikleri kapının önünden alıp battaniyenin içerisine koydun ya, alırken başka ayakkabılar var mıydı?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Eski var mıydı? Yani evin içerisinde bir kalabalığı bize gösterecek ayakkabı düzeni var mıydı kapının önünde?

Nevzat Bahtiyar : Yok. Dikkatimi çekmedi.

Av. Nahit Eren : Hatırlamıyor musun? Bir düşün, bir düşün. O anı gözünün önüne getir.

Nevzat Bahtiyar : Düşünüyorum.

Av. Nahit Eren : Salim'in eviyle Arif'in evinin arasındaki uzaklık ne kadar?

Nevzat Bahtiyar : O kadarını bilmiyorum.

Av. Nahit Eren : Ama Arif'in evinden Salim'in evini çok rahat görebiliyoruz değil mi?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Evin önünde araç var mıydı? Araç var mıydı?

Nevzat Bahtiyar : Ben o tarafa hiç bakmadım. Yani dikkatimi çekmedi.

Av. Nahit Eren : Ama yürüdüğün zaman zaten Salim'in kapı kısmına gittiğin zaman, Arif'in evine doğru gittiğinde Salim'in evini görüyorsun. Araç büyük bir şey. Hepimizin göreceği bir şey. Orada bir araç görmedin. Beyaz, Fuat'a ait araç.

Nevzat Bahtiyar : Görmedim. Hiç görmedim.

Av. Nahit Eren : Görmedin.

Nevzat Bahtiyar : Görmedim.

Av. Nahit Eren : Peki Salim'in herhangi bir çocuğunu kızlarını gördün mü o ara?

Nevzat Bahtiyar : Yok. Ben görmedim. Kimse yoktu o arada.

Nevzat Bahtiyar : Olsa da ben görmedim.

Av. Nahit Eren : İçeri girdin.

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : İçeride kaç dakika kaldın?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Mesela "İçeri girdik"; diyorsun ki bana, bütün kapılar kapalı. Bir odaya bizi götürdü. Odada yerde Narin'in cansız bedeni var dedin. Evet. Narin'in cansız bedenini gördüğün zaman tepkin ne oldu?

Nevzat Bahtiyar : Biraz, onu gördüm. Sonra korktum. Biraz çekindim.

Av. Nahit Eren : Salim'e ne söyledin o an? İlk söylediğin şey. Narin'i gördüğün andan itibaren. Salim'e söylediğin ilk cümlen?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Konuştun ama, hatırlamıyorsun. Konuştun, hatırlamıyorsun. Bir sorun oldu mu? Bu kız neden yerde diye sordun mu?

Nevzat Bahtiyar : Ben sormadım.

Av. Nahit Eren : Peki normal hayatta böyle bir şey olsa sormaz mısın?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Bilmiyorsun. Dostluk hukukundan dolayı mı sormadın?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Salim yapmışsa ya da kim yapmışsa, Salim beni getirdiyse burada bir doğru mu var dedin? Düşünmedin mi hiçbir şey?

Nevzat Bahtiyar : O vakitte hiçbir şey düşünmedim.

Av. Nahit Eren : Hiçbir şey düşünmedin?

Nevzat Bahtiyar : Düşünmedim.

Av. Nahit Eren : Peki, gördün. Yerde. Az evvel başkan bey sorunca battaniyeyi dışarıdan getirdi dedin.

Nevzat Bahtiyar : Dışarıdan getirdi, ama bilmiyorum nereden getirdi.

Av. Nahit Eren : Birini aradı mı?

Nevzat Bahtiyar : Yok, hiç kimseyi aramadı.

Av. Nahit Eren : Çocuklarını?

Nevzat Bahtiyar : Yok, ben hiç görmedim.

Av. Nahit Eren : Kızlarını?

Nevzat Bahtiyar : Ben görmedim.

Av. Nahit Eren : Eşini?

Nevzat Bahtiyar : Görmedim.

Av. Nahit Eren : Enes'i?

Nevzat Bahtiyar : Görmedim.

Av. Nahit Eren : Ne kadar sürdü battaniyenin gelmesi?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Ben sana evin içerisinde kaldığın süreyi söyleyeceğim. Bize o süreyi, sen 15:26'da evin içerisine giriyorsun. 15:35'e kadar evin içerisindesin. 9 dakikalık bir süre normal değil mi? Bir hatırla kaldığın süre?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Çünkü 4 dakika sonra aracın kameralarda görünüyor evden çıktıktan sonra. Bu somut bir delil. Kırmızı aracın 41 geçe kameralara yakalandığı an. Çiftlik kamerasından. Sen 26'da evin içerisine giriyorsun. 26'dan 41'e kadar o ev ve o evin etrafındasın. Az evvel başkan beye anlattığın o olay örgüsündeki süreçten bahsediyorum. Yani 15 dakika. Bunların hepsi o 15 dakika içerisinde mi gerçekleşti? Bir daha söylüyorum. Senin evin içerisinden Narin'i alman, battaniyenin gelmesi, battaniyeye sarılması, kapıdan terliği alman ve evden çıkıp sonrasında battaniyeyi de teslim süreni ekliyoruz. Çünkü evine doğru geldin. 15 dakika mı?

Nevzat Bahtiyar : Hatırlamıyorum, bilmiyorum.

Av. Nahit Eren : Süreyi mi hatırlamıyorsun yoksa hatırlamak mı istemiyorsun?

Nevzat Bahtiyar : Süreyi hatırlamıyorum.

Av. Nahit Eren : Süreyi hatırlamıyorsun. Tamam evin içerisindesin. Narini aldın. Narin yerde yatarken çanta neresindeydi?

Nevzat Bahtiyar : Çanta boynundaydı.

Av. Nahit Eren : Çanta boynunda duruyordu o şekilde?

Nevzat Bahtiyar : Boynunda duruyordu.

Av. Nahit Eren : Peki hatırlıyor musun, çantanın ağzı açık mıydı kapalı mıydı?

Nevzat Bahtiyar : Kapalıydı.

Av. Nahit Eren : Sen hiç bakma ihtiyacı duydun mu sonra?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Ama terlikleri dışarı çıktığında aldığın zaman çantayı da Narin'in boynunda aynı şekilde mi muhafaza ettin?

Nevzat Bahtiyar : Terliği içine attım.

Av. Nahit Eren : Mesela nasıl içine attın? Bir daha açtın mı battaniyeyi?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Bize bir anlat mesela göster de ki sen mesela battaniyeye diyorsun ki biz Salim'le beraber sardık değil mi? Salim'le beraber sardınız, battaniye dışarıdan geldi. Yere mi serdiniz battaniyeyi yoksa kucağında mı tuttun battaniyeyi?

Nevzat Bahtiyar : Battaniyeyi kucağımda tuttum.

Av. Nahit Eren : Salim sana nasıl yardımcı oldu?

Nevzat Bahtiyar : Sadece evin çıkardı.

Av. Nahit Eren : Hayır hayır battaniyeye sararken Salim sana nasıl yardımcı oldu? Bize anlatsana nasıl sardığınızı.

Nevzat Bahtiyar : Battaniye üstüne bir kere bu tarafı ben tuttum.

Av. Nahit Eren : Tuttunuz.

Nevzat Bahtiyar : Beni de gördü oraya. Döndü, merdivenden döndü, bana döndü.

Av. Nahit Eren : Evet. İkiniz battaniyenin içerisine bir ucundan tutup koydunuz. İçeride sardınız mı?

Nevzat Bahtiyar : Tam olarak sarmamıştık terliği böyle normal katlama falan yapmıştık.

Av. Nahit Eren : İkiniz beraber mi çıkıyorsunuz tutup yoksa sen tek mi?

Nevzat Bahtiyar : İkimiz de, tek, beraber çıktık.

Av. Nahit Eren : Ne zaman sana terliği de içine koy dedi?

Nevzat Bahtiyar : Terliği kapının önünde bana koy dedi.

Av. Nahit Eren : O an mı gördü sence yoksa daha önce mi? Daha kapıda terliği görmeden mi sana terliği içine koy dedi yoksa gördü mü o da terliği?

Nevzat Bahtiyar : Gördü.

Av. Nahit Eren : Sen baktın oraya. O terlik dışında başka bir şey görmedin, ayakkabı?

Nevzat Bahtiyar : Var var eski.

Av. Nahit Eren : Kaç tane mesela?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Küçük mü büyük çocukların mı? Pardon büyüklerin mi? Kız çocuğu mu erkek çocuğu mu? Ayakkabılar böyle kapının önünde duruyor, spor ayakkabılar?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Hatırlamıyorsun. Tamam. Aldınız Narin'i oradan artık Salim dışarı geldi mi yoksa içeri mi girdi bir daha?

Nevzat Bahtiyar : Ben orada yürürken, bilmiyorum, vallahi yani hatırlamıyorum.

Av. Nahit Eren : Ama sana bir ifadeni hatırlatayım. Ben araca doğru giderken araçtan arkamdan geldi diyorsun. Bu bilgi doğru mu?

Nevzat Bahtiyar : Evet ben aşağı indim arabanın yanına gittikten sonra o geldi.

Av. Nahit Eren : Sen Narin'i aldın kucağında gidiyorsun eve doğru gidiyorsun. Çünkü aracın orada, aracın orada, gidiyorsun.

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Beyanında diyorsun ki; "Arkamdan aracıyla geldi Salim". Daha önceki beyanlarında.

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Nasıl geldi? Yayan mı geldi? Yani yürüyerek mi geldi arkandan?

Nevzat Bahtiyar : Arabayla geldi.

Av. Nahit Eren : Onu soruyorum ben. Hangi arabayla? Beyaz evin önünde duran araba. Evin önünde duruyordu. Çıkarken gördün. Peki Salim'in evinin önündeki araç hareket ederse nereden geçerek seni arabanın yanına gelir?

Av. Nahit Eren : İki yol. Bir yol var.

Av. Nahit Eren : Sen gördün arkadan araçtan geliyor. Hangi yoldan geldi?

Nevzat Bahtiyar : Köy içinden gelmişti.

Av. Nahit Eren : Yani okula doğru olan değil?

Nevzat Bahtiyar : Köy içindeki.

Av. Nahit Eren : Köy, arkadan. Sen evin içinden otuz altı geçe (15:36) çıktın.

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Yani oradan senin yanına gelmesi ne kadar sürer?

Nevzat Bahtiyar : Vallahi bilmiyorum.

Av. Nahit Eren : Normal mesela sen o köyde kaç yıldır yaşıyorsun?

Nevzat Bahtiyar : Ben 52 yaşındayım. 52 yıldır ben o köyde yaşıyorum.

Av. Nahit Eren : Salim'den daha önce onun aracına bindin mi? Bu Renault değil. Kaza geçiren aracına mesela. Ya da daha önceki yıllarda aracına. Evinin önünden senin dediğin eve kadar gelmesi ne kadar sürer Salim'in?

Nevzat Bahtiyar : Bilmiyorum. Tahmini bilmiyorum.

Av. Nahit Eren : Bir öngörün yok mu ya? Üç dakika, beş dakika?

Nevzat Bahtiyar : Bilmiyorum. Ben onu net olarak diyemiyorum.

Av. Nahit Eren : Ama araçla geldi oraya. Araçla geldi oraya. Neden döndü senin evinin önüne geldi? İstikametini senin aracına doğru nasıl çevirdi?

Nevzat Bahtiyar : Çevirmedi. Geldi, orada durdu.

Av. Nahit Eren : Peki okulun önündeki kamera görmez mi onu?

Nevzat Bahtiyar : Görmez.

Av. Nahit Eren : Narin'nin son görüldüğü yere varmadan önceki senin evin sapağından mı girdi?

Nevzat Bahtiyar : Yok. Cami tarafına geldi.

Av. Nahit Eren : Senin evin yolun hangi tarafında kalıyor?

Nevzat Bahtiyar : Üst tarafına kalıyor.

Av. Nahit Eren : Sol. Okula yönümüzü verdiğimizde solda duruyor.

Nevzat Bahtiyar : He, sol.

Av. Nahit Eren : Geldi, okula varmadan senin evine doğru girdi mi Salim'in aracı? Okul tarafında değil.

Nevzat Bahtiyar : Cami tarafında gelmişti.

Av. Nahit Eren : Hayır, hayır. Okul karşı da gitmiyor okula. Caminin oradan döndü, senin evine doğru mu geldi? Arkadan mı geldi?

Nevzat Bahtiyar : Arkadan geldi.

Av. Nahit Eren : Tamam. Ve sen orada battaniyeyi ona teslim ettin.

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Peki, Ramazan Atasoy orada mıydı?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Mehmet Selim Atasoy orada mıydı?

Nevzat Bahtiyar : Yok, hiç kimse görmedi.

Av. Nahit Eren : Senle araca binmediler?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Narin'i götürdüğünde?

Nevzat Bahtiyar : Yok, ben yalnızdım.

Av. Nahit Eren : Battaniyeyi sen Salim'e teslim ettin?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Uzun süre battaniyeye temas ettin değil mi? Mesela bize battaniyeyi anlatsana. Rengi neydi? Şekli neydi? Desen var mıydı üzerinde?

Nevzat Bahtiyar : O zaman, yani, fazla hatırlamıyorum.

Av. Nahit Eren : Salim'in üzerindeki elbiseyi hatırlıyor musun?

Nevzat Bahtiyar : Bir tişört vardı.

Av. Nahit Eren : Rengi neydi?

Nevzat Bahtiyar : Rengi hatırlamıyorum.

Av. Nahit Eren : Battaniye o tişörtten daha büyük. Rengini hatırlamıyor musun?

Nevzat Bahtiyar : Rengi şu an yani hatırlamıyorum.

Av. Nahit Eren : Uzun uzun baktın, Narin'i içine yerleştirdin, katladın. Geldin yukarıda evinin tavanından, aşağıya, penceresinden bıraktın. Hala battaniye sende. İddian o. Battaniye hala sende.

Nevzat Bahtiyar : Battaniyeyi arabanın yanına bırakmıştım. O geldikten sonra ben ona götürdüm.

Av. Nahit Eren : Hayır hayır, yukarıda aldın Narin'i, evinin içine götürüp, Başkan Bey'e anlattın ya, torbanın içerisine, başından aşağıya torba geçirdim dedin. Yukarıdan onu bıraktın. Battaniyeyi ne yaptın?

Nevzat Bahtiyar : Battaniye arabanın yanına götürdüm.

Av. Nahit Eren : Hayır hayır, yukarıda, yukarıda. Sen Narin'i battaniyesiz kendi evinin önüne götürmedin. Ahırına götürmedin. Battaniye sende, Narin içerisinde. Narin'i pencereden ahıra bıraktın. Battaniyeyi ne yaptın? O anı söyleyeyim. Ama battaniye nerede?

Nevzat Bahtiyar : Battaniyeyi aldım, cesetle birlikte arabanın yanına götürdüm.

Av. Nahit Eren : Hayır, yukarıda cesedi aşağı bıraktın ya, çünkü anladığım kadarıyla, yukarıda senin ahırında şöyle bir oluk var.

Nevzat Bahtiyar : Evet, evet.

Av. Nahit Eren : O oluktan aşağıya atmışsın Narin'i.

Nevzat Bahtiyar : Yavaş bırakmıştım.

Av. Nahit Eren : Yavaş bırakmışsın yani. Sonra battaniyeyle birlikte mi aşağıya bıraktın?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Hah, onu soruyorum. Battaniyeyle birlikte aşağıya bıraktın. İndin, gittin ahıra, torbaya koydun. Torbanın ağzını bağlamadın. Nasıl aldın torbayı? Omuzladın mı, sırtına mı, kucağına mı, koltuk altına mı?

Nevzat Bahtiyar : Battaniye. Battaniyeyle almıştım.

Av. Nahit Eren : Elinde battaniyeyle birlikte. Geldin araca. Arkadan Salim'in geldiğini gördün araçla.

Nevzat Bahtiyar : Ben cesedi arabanın içine attım. Salim o zaman yeni gelmişti.

Av. Nahit Eren : Aracın içerisine Narin'i bıraktın.

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : O an battaniyeyi aracın içerisine bırakmadın?

Nevzat Bahtiyar : Yok, bırakmadım.

Av. Nahit Eren : Yine kucağında tutuyorsun.

Nevzat Bahtiyar : Yok, arabanın yanına bırakmıştım.

Av. Nahit Eren : Peki, sen Salim'in geleceğini biliyor muydun ki dışarıya bıraktın? Bilmiyorsan sen mesela Narin'i kaybetmek üzere bir sorumluluk almışsın değil mi?

Nevzat Bahtiyar : Doğru.

Av. Nahit Eren : Öyle ifade ediyorsun. Eğer Narin'i aracın içerisine koyduysan, Salim'in geleceğini bilmiyorsan battaniyeyi, insan suç delilini aracın yanına bırakır mı?

Nevzat Bahtiyar : Bırakmaz ama ben geleceğini biliyordum.

Av. Nahit Eren : Nereden biliyordun? Sana dedi mi?

Nevzat Bahtiyar : Demedi, yani, tahmin ettim. Battaniye için geleceğini biliyordum.

Av. Nahit Eren : Sana oradayken, evdeyken senden battaniyeyi alacağını söyledi mi?

Nevzat Bahtiyar : Söylemedi. Geleceğini ben biliyordum.

Av. Nahit Eren : Peki, o an mı geleceğini yoksa götürüp mahalline, yani Eğertutmaz Deresi'ne gittiğin yere mi geleceğini düşünüyordun?

Nevzat Bahtiyar : Yok, ben orayı düşünmedim.

Av. Nahit Eren : Bizzat evin önüne gelecek gibi bir duygun vardı. Bu duyguya nereden kapıldın? Mesela ben bir cesedi, şöyle soruyorum, bu bir yorum, yorumla birlikte bir soru Sayın Başkan. Ben bir cesedi birine teslim ettikten sonra artık o cesetten kurtuldum diye hiç temas kurmam. Salim böyle bir duyguda sana teslim etmiş olamaz mı? Yoksa eğer böyle etmemişse, sana geleceğini bir şekilde, doğrudan ya da dolaylı hissettirmiştir?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Geldi, sen o an yere bıraktın. Salim geldi, Narin torba içerisinde, araçta, arka koltuğun paspas kısmında. Salim sana nereye koydun dedi mi? Neyin içine koydun dedi mi?

Nevzat Bahtiyar : Yok, söylemedi. Bana böyle bir konuşma olmadı.

Av. Nahit Eren : O an hiç sormadı aracın neresinde?

Nevzat Bahtiyar : Sormadı. Arabanın içine zaten ben koymuştum.

Av. Nahit Eren : Gördü mü sence?

Nevzat Bahtiyar : Arabanın içine koyduğumu görmemişti o zaman.

Av. Nahit Eren : Görmemişti?

Nevzat Bahtiyar : Görmemişti. Yani battaniye arabanın yanına battaniyeyi aldı, benden aldı, götürdü. Ben başka bir şey bilmiyorum.

Av. Nahit Eren : Sence battaniyeyi, 30 yıllık dostundur, sence Salim o battaniyeyi ne yapmış olabilir?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Sence birine mi verdi senin gibi?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Ramazan'a vermiş olabilir mi?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Mehmet Selim Atasoy'a vermiş olabilir mi?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Bu konuda bir bilgin yok.

Nevzat Bahtiyar : Bir bilgim yok.

Av. Nahit Eren : Gittin, aldın, gittin dereye. Derenin o anki ben senin videolarını da izledim. Yani savcılarımızla birlikte olay mahallinde Narin'i o su birikintisinin içerisine koyduğun videoyu izledim. Ben sana bir şey soracağım. O an o suyun seviyesi nereye kadardı aşağıdaki? Eğertutmaz deresinden giden suyu soruyorum. Eğertutmaz'ın suyu senin o gömdüğün yere doğru taşkın mıydı yoksa hiç su yok muydu orada? Çünkü buradaki sudan bahsetmiyorum. Çünkü siz, açıklayayım sana, siz delil tespiti, pardon, yer tespitine gittiğinizde Narin bulunduğunda Narin'in bulunduğu çukurda su var. Ama sen gittiğin zaman o suyun dışında, biliyorsun, o küçük alanla suyun aktığı dere yatağı arasında toprak bir kısım var. Orası su altında mıydı?

Nevzat Bahtiyar : Orası su altında değildi.

Av. Nahit Eren : Ayağın, ayağın herhangi bir suya temas etmedi?

Nevzat Bahtiyar : Orada su vardı.

Av. Nahit Eren : Onu soruyorum. Sen küçük bir yere küçük bir oyuğa gizlemişsin Narin'i. Ben Narin dışarıda sen dışarıdasın ya dışarıda oraya koyuyorsun. Ayakların o an suyun içinde mi? O su birikintisi dışındaki sudan bahsediyorum.

Nevzat Bahtiyar : Suyun içerisindeydi.

Av. Nahit Eren : Seviyesi ne kadardı? Bacağından yani ayaklarından nereye kadar geldi?

Nevzat Bahtiyar : 50 santim falan vardı. Yani 40 santim falandı.

Av. Nahit Eren : Bir şey soracağım. Sen köyden saat 15:41'de çıktın. Mahalle vardığın süre çıkardığımız zaman 5-6 dakikalık bir süre yanılıyor olabilirim. O süre açısından arkadaşlarım da hatırlatabilir. Şunu soruyorum. 38 dakikalık bir süreçten bahsediyoruz. Bu mahalledeki 38 dakikanın aracı park ettiğin yerden Narin'i bıraktığın yere kadar her birini maksimum 4 dakikalık süre kabul edelim. 4 gittin 4 döndün 8 dakika. 30 dakika boyunca orada ne yaptın? Mesela 30 dakika, hazır bir çukur var orada. Su var. Suyun içerisine koydun. Çok özenli ki beyanlarına göre tırnak içerisinde söylüyorum. Gizleme yönünde bir kamuflaj çaban yok. Çünkü öyle dedin. O çalıları ben koymadım dedin mesela.

Nevzat Bahtiyar : Ben koymadım.

Av. Nahit Eren : "Ben bir taş koydum" dedin. 3 taş çıktı mesela. Peki o an o süre o 38 dakika suyun yüksekliğinden dolayı daldın mı suyun içine elbiselerini çıkarıp dışarıya mı bıraktın? Ayakkabıyla pantolonla mı gittin?

Nevzat Bahtiyar : Yok o su o kadar yüksek değildi.

Av. Nahit Eren : Sen elbiselerini çıkardın mı? çıkarmadın?

Nevzat Bahtiyar : Yok, çıkarmadım.

Av. Nahit Eren : Ayakkabını çıkardın mı?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Pantolonunu çıkardın mı?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Kaç dakika sonra Zeynep'lerin evine vardın?

Nevzat Bahtiyar : Hatırlamıyorum ben onu.

Av. Nahit Eren : Oradan çıktın direk peynir. Eşin sana diyor ya, 15:08'de konuştun ya. Evden araçtan çıkıyorsun ya. Zeynep'lerden peynir getir diyor ya akşam gelirken?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Akşam peyniri almak için Zeynep'lere gittin. Narini gömdükten sonra. Evleri nerede? Uzunbahçede değil mi? Uzun bahçeyle Eğertutmaz arasındaki mesafe ne kadar?

Nevzat Bahtiyar : Bilmiyorum ben.

Av. Nahit Eren : Kaç kilometre?

Nevzat Bahtiyar : Ben onun mesafesini bilmiyorum.

Av. Nahit Eren : Daha önce hiç gitmedin mi?

Nevzat Bahtiyar : Daha önce gitmiştim ama mesafesini bilmiyorum.

Av. Nahit Eren : Kaç dakika sürdü daha önce gittiğinde?

Nevzat Bahtiyar : Bilmiyorum hatırlamıyorum.

Av. Nahit Eren : Ama doğrudan oraya gittin.

Nevzat Bahtiyar : Evet oradan, zaten bıraktıktan sonra oradan dedik.

Av. Nahit Eren : Gittin Zeynep'in evine oturdun, çay içtin, yemek yiyordular. Yemek ısmarlamak istediler, kabul etmedin, çay içtin.

Nevzat Bahtiyar : Yemek falan.

Av. Nahit Eren : Çay içtin ama.

Nevzat Bahtiyar : Çay içtim.

Av. Nahit Eren : Peki, suya girdin. Maksimum yarım saat.

Nevzat Bahtiyar : Suya ben girmemiştim.

Av. Nahit Eren : Az evvel dedin ya ben Narin'i o çukura koyarken su seviyesi yüksekti?

Nevzat Bahtiyar : Yüksek değildi ben dedim.

Av. Nahit Eren : Ben mi yanlış anladım? Yüksekti dedin sanki.

Nevzat Bahtiyar : Ben dedim yani.

Av. Nahit Eren : Kırk elli santim dedin ya. Kırk elli santimi bize bir göstersene. Sence kırk elli santim ne kadar? O diz kapağına kadar suya girdin.

Nevzat Bahtiyar : Ben girmedim. Suya hiç girmedim.

Av. Nahit Eren : Çıkardın pantolonunu.

Nevzat Bahtiyar : Ben pantolonumu da çıkartmadım, orada taş vardı ya. Suya girmedim dedim.

Mahkeme Başkanı : Suya girmedim dedi. Hiçbir kıyafet çıkarmadım dedi. Tekrar sorun da teyit edelim.

Nevzat Bahtiyar : Ben suya hiç girmedim.

Av. Nahit Eren : 40-50 santimlik su seviyesi nerenin su seviyesi? 40-50 santimlik bir su seviyesinden bahsettin. Yüksekti dedin.

Nevzat Bahtiyar : Yani ben öyle söylüyorum.

Av. Nahit Eren : Peki o su seviyesine temas etmeden bir köprü mü kurdun? Şöyle mi bıraktın?

Nevzat Bahtiyar : Taş vardı taş. Bir taş vardı orada.

Av. Nahit Eren : Biz birbirimizi iyi anlayalım Nevzat. İyi anlayalım. Bir daha anlatayım. O yamaçtan aşağı indin. Koltuğunun altında Narin var. İndin. Sen kafanda oraya gömmeyi daha önce neredeyken tasarladın?

Nevzat Bahtiyar : Ben orayı uygun gördüğüm için ben oraya bıraktım.

Av. Nahit Eren : Nerede düşündün bunu?

Nevzat Bahtiyar : Ben gittim, orada.

Av. Nahit Eren : Evden çıktın ya. Evden çıkınca kafanda bir yer tasarladın mı?

Nevzat Bahtiyar : Yok. Hiç tasarlamadım.

Av. Nahit Eren : Balıkçısın da galiba? Yanlış mı hatırlıyorum?

Nevzat Bahtiyar : Ben iyi bir balıkçı değilim.

Av. Nahit Eren : Balık avlıyorsun ama orada.

Nevzat Bahtiyar : Yok. Ben oraya hiç gitmemişim.

Av. Nahit Eren : O dereyi iyi biliyorsun ama.

Nevzat Bahtiyar : Ben biliyorum. Aşağısında balık tutmaya gitmiştim.

Av. Nahit Eren : O gömdüğün yere daha doğrusu sakladığın yere daha önce hiç gitmiş miydin?

Nevzat Bahtiyar : Yani oradan geçmiştim.

Av. Nahit Eren : Orada o çukurun olduğunu biliyor muydun? Çünkü etrafı kapalı. Böyle bir...

Nevzat Bahtiyar : Daha önce bilmiyordum. Gittim orada çukur diye ben oraya bıraktım.

Mahkeme Başkanı : Şimdi o videoyu ben de izledim. O dereye gittiğin zaman konulabilecek, inilebilecek tek yer orası. Doğru mu? Yani o yüzden mi sen oraya indin?

Nevzat Bahtiyar : Orayı uygun gördüm. Ben orayı bıraktım.

Mahkeme Başkanı : Orayı uygun görmenin sebebi neydi?

Nevzat Bahtiyar : Ben oraya bıraktım. Yani... Bilmiyorum.

Av. Nahit Eren : Ben bir daha soracağım. Çukurun olduğu yerle dere yatağının olduğu Eğertutmaz deresindeki suyun aktığı yer arasında toprak bir mesafe var. Yeşillikli, çimli.

Nevzat Bahtiyar : Evet, çimlidir.

Av. Nahit Eren : Otlu. Sen oraya gittiğinde o otlar suyun içinde miydi?

Nevzat Bahtiyar : Suyun içinde... Yani yok, fazla su içinde değildi.

Av. Nahit Eren : Yani sen Narin'i gömünce, pardon saklayınca hiç ıslanmadın?

Nevzat Bahtiyar : Yok. Sadece yani... Ayağımda terlik vardı.

Av. Nahit Eren : Terlik mi? Ayakkabı mı?

Nevzat Bahtiyar : Terlik vardı. Ayakkabı yoktu. Yazlık terlik.

Av. Nahit Eren : Yazlık terlikti. Gün boyu mu ayağındaydı?

Nevzat Bahtiyar : Yani gün boyu da değil. Böyle sıcak olduğu zaman ben yani.

Av. Nahit Eren : Yani genelde dışarıda da terlikle geziyorsun. Yani bu olayda Eğertutmaz'a gidiyorsun diye terlik giymedin.

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Tamam. Ama pantolonun ıslanmadı. Yukarı çektin.

Nevzat Bahtiyar : Yok. Hiç ıslanmadı. Evet. Suyun içerisine girmedim.

Av. Nahit Eren : Otuz sekiz dakika orada bekledin.

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : 38 dakika içerisinde Narin'in bacaklarını yine ifadelerin üzerinden söylüyorum. Bir, bacağının seni zaman kaybını söyleyeyim sana. İki, iddialar o anlamda doğru torbanın ağzını, kırmızı Narin'in çantasının bağcığıyla bağlamaya çalışmışsın. Ben 38 dakika boyunca orada olduğunu biliyorum. Mahkeme de biliyor. Çünkü tartışılmayacak dijital bir materyal var. Aracın geliyor, duruyor, gidiyorsun, biniyorsun. Bunlar tespitli. 38 dakika. Sen de bil. 38 dakika. 38 dakikada sen Narin'i oraya saklarken bacağının dışarıda kaldığını göre göre bıraktın.

Nevzat Bahtiyar : Bıraktım.

Av. Nahit Eren : Demedin mi ya dışarıda kalır, bir canlı gelir, çeker, kokusunu alır, dışarı çıkar. Özür diliyorum Arif Bey. Böyle böyle bir böyle bir duygu gelişmedi mi sende? Köyde yaşıyorsun, çiftçisin, bilirsin köyünüzde bir sürü hayvan var, köpekler var. Bir sürü değil mi sokak köpeği?

Nevzat Bahtiyar : Hiç düşünmedim.

Av. Nahit Eren : Bir şey sorayım. Sence daha sonra biri oraya gitmiş de seni tam bağladığın çantayı, seni tam bağladığın torbayı biri açmış olabilir mi?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Sence Ramazan oraya gitmiş olabilir mi?

Nevzat Bahtiyar : Hiçbir bilgim yok.

Av. Nahit Eren : Mehmet Selim?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Salim?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Gitmemişler mi?

Nevzat Bahtiyar : Bilmiyorum. Ben yani gitmiş olabilir. Ben görmedim.

Av. Nahit Eren : Niye üç taş var sence?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Sen bir tane koydun değil mi?

Nevzat Bahtiyar : Ben bir taş koymuştum.

Av. Nahit Eren : Sen bir taş koydun?

Nevzat Bahtiyar : Ben bir taş koymuştum.

Av. Nahit Eren : Sen çalı koymadın?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Bulunurken üç taş var, çalı var. Senin dışında orada olduğunu bilen kim?

Nevzat Bahtiyar : Nasıl yani?

Av. Nahit Eren : Senin dışında Salim'i pardon Narin'i oraya sakladığını bilen kim senin dışında?

Nevzat Bahtiyar : Ben yani...

Av. Nahit Eren : Salim biliyor?

Nevzat Bahtiyar : Evet, Salim biliyor.

Av. Nahit Eren : Nokta yeri bilmiyor ama değil mi?

Nevzat Bahtiyar : Nokta yeri bilmiyor.

Av. Nahit Eren : Nokta yeri bilmiyor. Şimdi gelelim, Savcı Hanım'ın sana sorduğunu ben daha açıklayıcı bir şekilde sana sorayım. Bütün Güran ailesi, pardon bütün demeyeyim. 6-7 kişi, isim saymayacağım. Narin'in kaybolmasından sonra kimisi 22'sinde, kimisi 23'ünde telefonundaki bütün görüşme kayıtlarını silmiş. Ne olduğunu biliyor musun?

Nevzat Bahtiyar : Bir bilgim yok.

Av. Nahit Eren : Hayır hayır, ne olduğunu biliyorsun, değil mi? Kayıt silmenin ne olduğunu biliyorsun. Kimi aramışsan böyle siliyorsun.

Nevzat Bahtiyar : Yani ben onu bilmiyorum, yani bir bilgim yok.

Av. Nahit Eren : Hayır hayır, bu teknik meseleyi biliyorsun, değil mi?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Biliyorsun. Salim'in telefonundaki, ben şimdi açıyorum, sildiği bütün kayıtlar geri getirilmiş.

Nevzat Bahtiyar : Bir bilgim yok.

Av. Nahit Eren : Silmedikleri zaten telefonunda, sildikleri geri gelmiş. Özellikle WhatsApp.

Nevzat Bahtiyar : Bir bilgim yok.

Av. Nahit Eren : WhatsApp. Getirilmiş bu bir delil, somut delil, tespit. Önümüzde dosyada bilirkişilerin imzaladığı, daraltılmış baz istasyonu verilerinden bahsetmiyorum. Somut, Salim'in telefonunda, cihazında bütün kayıtları, sildiği kayıtları geri getirmişler.

Nevzat Bahtiyar : Bir bilgim yok.

Av. Nahit Eren : Bir bilgin yok bunda?

Nevzat Bahtiyar : Bilgim yok.

Av. Nahit Eren : 15:46'da sen onu aramışsın, pardon 17:46'da sen onu aramışsın?

Nevzat Bahtiyar : Ben bilmiyorum, yani aradığımı bilmiyorum. Yani sadece ben 15:08'de aramıştım.

Av. Nahit Eren : Onda sıkıntı yok, o normal bir arama, o zaten silinmemiş. Kayıtta var, telefonda var. 17:46'da, bakın bu yakın zamanda, iddianamede de var bu husus. 17, bir daha yanlış söylemeyeyim sana. 17:46 saniye 32'de 41 saniyelik telefon görüşmen var senin.

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Sana ne dedi?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Bir daha beni arama mı dedi?

Nevzat Bahtiyar : Yok, ben bilmiyorum yani.

Av. Nahit Eren : Teknik, teknik, hatırlamıyorsun.

Nevzat Bahtiyar : Hatırlamıyorum yani.

Av. Nahit Eren : Vecdi senin neyin?

Nevzat Bahtiyar : Vecdi, Vecdi benim kardeşimdir.

Av. Nahit Eren : Senden büyük mü, küçük mü?

Nevzat Bahtiyar : Benden ufak.

Av. Nahit Eren : Halk arasında başka bir ismi var mı? Yani siz mesela Vecdi'ye, Vecdi Bahtiyar dışında taktığınız bir isim var mı aile içerisinde, köy içerisinde?

Nevzat Bahtiyar : Vallahi, yani yok. Yok, Vecdi yani de, bir ismi yok.

Av. Nahit Eren : Peki sana bir bilgi daha vereyim. Salim'in telefonunda kardeşin olan Vecdi, Vehbi diye niye kaydedilsin? Sen biliyor musun? Böyle bir isim biliyor musun? Pardon ben, pardon Vedat diye. Vedat diye. Salim Bey siz de burada dediniz başka bir ismi var. Vedat mı? Vedat diye herkes içerisinde bilinen bir ismi var mı?

Nevzat Bahtiyar : İsmi yani kimlikte Vecdi'dir. Yani normalde biz Vedat diyoruz.

Av. Nahit Eren : Ben onu soruyorum sana, Vedat. Vedat da o gün Hatay'daydı, biliyorsun, değil mi? İnşaat çalışması için.

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Sen kaç defa Vedat'la görüştün?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Görüştün.

Nevzat Bahtiyar : Yani görüşme, bilmiyorum yani. Görüşme olmuş olabilir yani, ben hatırlamıyorum.

Av. Nahit Eren : Ne konuştun? Ya bir çocuğu götürmüşsün. Biraz, biraz vicdanımızı ortaya koyalım. Bir çocuğu götürmüşsün dere yatağına. Sekiz yaşında bir çocuğu götürmüşsün dere yatağına. Saklamışsın o çukura. Ağabeyinle ne konuşabilirsin? Başkan bey sana sordu. Kendi hayatında kimse öldürmemişsin.

Nevzat Bahtiyar : Hiç kimseyle konuşmadım. Bunun hakkında hiç kimseyle konuşmamışım.

Av. Nahit Eren : Vecdi ile ne konuştun? Soruyorum. Vecdi, sen Vecdi'yi aradın.

Nevzat Bahtiyar : Ben bilmiyorum, yani onunla konuştum da, ben hatırlamıyorum.

Av. Nahit Eren : Vecdi seni Narin'in bulunduğu sabah 06:34'te aradı.

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Nahit Eren : Aradı mı, aramadı mı?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Sabah 06:34'te. Vecdi Hatay'dan geldikten sonra Çarıklı'daki evi, Çarıklı'da evi değil mi?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Çarıklı'daki evinde kalıyor. Çarklı'daki evinden Eğertutmaz deresi görülüyor mu? Bir düşün ben de bilmiyorum.

Nevzat Bahtiyar : Görünmüyor.

Av. Nahit Eren : Ama 06:34'te seni aradı.

Nevzat Bahtiyar : Bilmiyorum, hatırlamıyorum.

Av. Nahit Eren : Narin'in orada saat kaçta aranmaya başlandığını hiç duydun mu?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Kendi evinden baktığında gördün mü?

Nevzat Bahtiyar : Yok ben hiç görmedim.

Av. Nahit Eren : Vecdi seni aramadı?

Nevzat Bahtiyar : Yok ben aramadım.

Av. Nahit Eren : 06:34'te Vecdi seni aramadı?

Nevzat Bahtiyar : Ben hatırlamıyorum.

Av. Nahit Eren : Son kez soruyorum.

Nevzat Bahtiyar : Belki aramış olabilir, yani, belki yani, hatırlamıyorum.

Av. Nahit Eren : Vecdi ile Salim'in arası nasıl?

Nevzat Bahtiyar : Arası, yani normaldi yani.

Av. Nahit Eren : Senle olan hukuk kadar bir hukukları var mı? Dostlar mı? Arkadaşlar mı?

Nevzat Bahtiyar : Arkadaş, yani normal, yani köyde birlikte büyümüş, yani iki kişi gibi yani böyle.

Av. Nahit Eren : Sana somut bir delil daha söyleyeceğim. Sen 17:46'da arıyorsun ya Salim'i. Arıyorsun, kayıtlara göre konuşuyorum, baz kayıtlara göre arıyorsun. Ve bir daha hiçbir şekilde Narin'in meselesini bırak, dostluk hukukunuza göre de hiçbir şekilde Salim'i aramıyorsun. Salim de seni aramıyor. Peki sana bir soru sorayım. Salim senin bütün bu iddialarını inkar ediyor değil mi? Duymuşsundur.

Nevzat Bahtiyar : İnkar ediyor.

Av. Nahit Eren : Bir soru soracağım sana. Bunu Salim'e de soracağım. Bu kadar dost olduğunuz biri, arkadaş olduğunuz biri. Eğer gerçekten senin bu söylediklerine Salim "doğru değil" diyorsa, bakın tırnak içerisinde. Seni "Narin kayboldu" diye kaç defa arardı? Gel beraber arayalım diye arardı, değil mi?

Nevzat Bahtiyar : Bilmiyorum.

Av. Nahit Eren : Normal gerçekten Narin'i o gün biri kaçırmış. O bahsettikleri beyaz araç var ya patinaj yapıyor. Köyden kaçırıyor.

Nevzat Bahtiyar : Zaten köyde aramıştık.

Av. Nahit Eren : Hayır hayır, Narin'i aramaktan bahsetmiyorum. Örneğin ben geldim, Narin'i kaçırdım. Köyden aldım, kaçırdım Narin'i. Salim normal şartlarda seni "Ya Nevzat köyde benim yeğenimi kaçırdılar, gel bir" der mi, demez mi? Arar değil mi seni?

Nevzat Bahtiyar : Evet arar.

Av. Nahit Eren : Birlikte arardınız. Her gün arardınız.

Mahkeme Başkanı : Bir dakika soruya itiraz var galiba. Buyurun.

Sanık müdafileri : Israrla yönlendirme var bizce bu soruda. İki defa soruldu değil mi diye hani arardı değil mi?

Mahkeme Başkanı : O şey, rutin hayatın olan akışı içerisinde arar mıydı diye soralım o zaman.

Av. Nahit Eren : Tabii zaten bunu sordum.

Mahkeme Başkanı : Hayatın olan akışı içerisinde arar mıydı?

Av. Nahit Eren : Ben kaçırdım. Normal şartlarda eğer dışarıdan biri Narin'i kaçırmış olsaydı, 30 yıllık dostun, evine gidip kaldığın biri, Salim bu kaçırmadan dolayı en çok irtibat halinde olacağı aile bireyleri dışındaki kişi sen olurdun. Onu soruyorum, değil mi?

Nevzat Bahtiyar : Yani, sadece ben tanımıyorum ya, köydeki her şey aynı.

Av. Nahit Eren : Hani sizin hukukunuz var ya.

Nevzat Bahtiyar : Yani köydeki hepsi yani aynı şekil. Yani sadece ben tek değilim.

Av. Nahit Eren : Seni hiçbir defa aramamış olması normal mi? Sence?

Nevzat Bahtiyar : Ben hatırlamıyorum.

Av. Nahit Eren : Hayır, hatırlamıyorum değil. Başka bir yorum sorusu soruyorum. Normal şartlarda kaybolmuş olan Narin'in bulunması için Salim'in seni araması lazım sürekli, değil mi? Çünkü yakın dostun, onu soruyorum.

Nevzat Bahtiyar : Sürekli yani araması.

Mahkeme Başkanı : Yorum sorusu sormayalım.

Av. Nahit Eren : Yorum değil, çünkü bir delil soracağım şimdi.

Mahkeme Başkanı : Tamam delil soralım.

Av. Nahit Eren : Seni hiç aramadı. Seninle hiç temas kurmadı. Sence Vecdi ile temas kurar mı?

Nevzat Bahtiyar : Ben sanmıyorum.

Av. Nahit Eren : Sanmıyorsun. 22.08.2024 Narin'in bulunduğu ertesi gün 10:21, 22.08.2024 17:02, 22.08.2024 22:41, 23.08.2024 12:32; 4 defa Vecdi Salim ile görüşmüş ve bütün aramalar ne tesadüftür, Vecdi aramış. Sence bir hukukları mı var?

Nevzat Bahtiyar : Yani o kızdan dolayı onu aramış olabilir. Yani kaybolduktan.

Av. Nahit Eren : Hepsinde öncesinde seni de arıyor.

Nevzat Bahtiyar : Bilmiyorum yani.

Av. Nahit Eren : Senden aldığı bilgiyi, senden aldığı bilgiyi, siz Vecdi'nin üzerinden iletişim mi kuruyorsunuz? Sıralı arama var.

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Sıralı arama nedir biliyor musun? Ben seni ararım. 10 dakika sonra, 1 saat sonra Aydın Bey'i ararım. Sizin köprü iletişiminiz Vecdi miydi?

Nevzat Bahtiyar : Yok, öyle bir şey yok.

Av. Nahit Eren : Değildi.

Av. Nahit Eren : Fadile seni kızın mı?

Nevzat Bahtiyar : Evet.

Av. Nahit Eren : Hiç Fadile ile bu olayı konuştun mu?

Nevzat Bahtiyar : Hiç konuşmadım.

Av. Nahit Eren : Hiç Fadile'nin verdiği ifadeleri duydun mu?

Nevzat Bahtiyar : Hiç duymadım.

Av. Nahit Eren : Sen bu dosyadaki ifadeleri okudun mu?

Nevzat Bahtiyar : Yok.

Av. Nahit Eren : Kim ne demiş?

Nevzat Bahtiyar : Hiç okumadım. Bir bilgim yok.

Av. Nahit Eren : Mesela Enes senin için diyor ki; "Çok silik biridir, çok sessiz biridir, yönlendirilmeye çok açıktır. Eğer Salim ona ne derse yapar" gibi bir cümlesi var.

Nevzat Bahtiyar : Biz dosttuk yani.

Av. Nahit Eren : Bu bilgiler doğru yani. Seni köyde herkes böyle biliyor.

Nevzat Bahtiyar : Yani köyde, yani, birbirimizi seviyorduk. Yani Salim.

Av. Nahit Eren : Ben kızına, bunu teyit ettikten sonra kızının beyanını sana söyleyeceğim. Kızının beyanını hiç duymadın.

Nevzat Bahtiyar : Hiç duymadım.

Av. Nahit Eren : Yüksel, Narin'in annesi, Narin'in kaybolduğunu tırnak içerisinde kendi beyanına göre öğrendiği andan sonra sizin eve doğru yöneliyor ve şu cümleyi kuruyor; "Kızımı nereye bıraktıysanız, kızımı kim götürmüşseniz getirin, bir köşeye bırakın. Bari bir mezar olsun" diyor. Bu 19 gün içerisinde sen dışarıdasın ya, 19 gün içerisinde sana bunu, Narin'in kaybolduğu gün, bununla ilgili hiçbir şey söyledi mi?

Nevzat Bahtiyar : Söylemedi, ama köyde sürekli konuşmalar oluyordu. Sizin eve gidip, Ben onu bilmiyorum.

Av. Nahit Eren : Sen bu bilgiyi bilmiyorsun, kızın hiçbir şekilde sana bunu 19 gün içerisinde söylemedi?

Nevzat Bahtiyar : Hatırlamıyorum, bilmiyorum. Bütün köyler konuşuyordu bu konuyu. Kim götürmüşse getirsin bir yere bıraksın. Böyle bir konuşma vardı, ama bilmiyorum.

Av. Nahit Eren : Başkanım, bir kontrol edeyim, bir dakika.

Mahkeme Başkanı : Tabii ki. Tekrarlı bir sorgu oluyor ama yapacak bir şey yok. Beyanlar alınırken zorlanıyoruz, O yüzden tekrarlı sorularla en azından Nevzat konusunda tekrarlı sorularla devam ederiz. Ancak Salim ya da diğer konuda tekrarlı sorulara dikkat edelim, yani yarısını da ben de sordum ama bir şey alamıyoruz ya da "Hatırlıyorum", "hatırlamıyorum" gibi. Bakın başkanım notlarınıza, yoksa sıradaki arkadaşlara söz verelim.

Av. Nahit Eren : Başkanım, benim şu anki sorularım Nevzat'a bu kadar.

Mahkeme Başkanı : Tamam sizden soru sormak isteyen var mı?

Av. Nahit Eren : Pardon başkanım, bu konu özür diliyorum, çok özür diliyorum, çünkü ben otopside bulunduğum için bir şey soracağım. Özür diliyorum, arkadaşlarım belki tarifleyemez onu, biz otopsi işlemine başlamadan önce delil tespiti yapılırken torba içerisinde bir kanca çıktı. Metal ahşap görünümlü simsiyah ve dere yatağında kaldığı için niteliği adli tıp raporuna da yansıdı. Senin böyle bir kanca, çünkü o torba senin. Seri numaralarıyla zaten senin diğer ahırındaki torbalarla eşleştiği belli gübre torbası. Bu konuda eminiz. O torba içerisinde, sen o torbayı aldığın zaman torbalar istifli miydi yoksa bir yerde içinde bir şeyler mi vardı?

Nevzat Bahtiyar : Ben... bir şey içinde... bilmiyorum, hatırlamıyorum.

Av. Nahit Eren : Çünkü Narin'e ait de olmayan bir metal parçası vardı?

Nevzat Bahtiyar : Ben hatırlamıyorum.

### Av. Aydın Özdemir

Av. Aydın Özdemir : Nevzat Bey, Narin'i siz mi boğdunuz?

Nevzat Bahtiyar : Yok.

Av. Aydın Özdemir : Peki kim boğdu?

Nevzat Bahtiyar : Salim.

Av. Aydın Özdemir : Salim, nereden biliyorsunuz?

Nevzat Bahtiyar : Kendisi bana söyledi.

Av. Aydın Özdemir : Kendisi boğduğunu mu söyledi yoksa biri boğmuş al götür sakla mı?

Nevzat Bahtiyar : O söyledi: "ben boğmuşum".

Av. Aydın Özdemir : Nasıl boğduğunu anlattı mı hiç? sordunuz mu?

Mahkeme Başkanı : Biz bunları sorduk ama her şey sıfırdan.

Av. Aydın Özdemir : Sıfırdan olmayacak.

Mahkeme Başkanı : Bir yere getireceksiniz, bağlayacaksınız; anladım ama en azından bizim beyanlarımız "Bak böyle böyle dedin tamam mı". Konuya giriş yapın lütfen.

Av. Aydın Özdemir : Silahla sizi kim tehdit etti? İlk bölümde başkan bey size soru sorarken "Silahla beni tehdit ettiler" dediniz.

Nevzat Bahtiyar : Salim.

Av. Aydın Özdemir : Yok, şunu soruyorum: "Ben korkmuştum, silahla tehdit etmişlerdi, o yüzden ifade vermedim". Bu noktada bir isim vermemiştiniz.

Duruşma Savcısı : Avukat bey, onu ben sordum. Evde silahla tehdit ettiğini söyledi.

Av. Aydın Özdemir : Yine Salim, tamam. Kardeşine kim para teklif etmiş? Kardeşin cezaevine geldi, sana "bana işte para ve arazi teklif ettiler" dedi. Kardeşine kim bunu teklif etmiş?

Nevzat Bahtiyar : Bilmiyorum, kardeşimin kimden öğrendiğini ben bilmiyorum.

Av. Aydın Özdemir : Sana söylemedi mi?

Nevzat Bahtiyar : Bana söyledi. Ziyaretime geldiği zaman. Böyle bir kelime bana söyledi ama.

Av. Aydın Özdemir : Ne teklif etmişler?

Nevzat Bahtiyar : Söylemiş, gelsin şeyle konuşsun, Hacı Hasan vardı. Herhalde Salim'in amcası, ona demişti.

Av. Aydın Özdemir : Hangi amcası?

Nevzat Bahtiyar : Hacı Rıza Güran.

Av. Aydın Özdemir : Ne demiş?

Nevzat Bahtiyar : Onların söylediğini ben bilmiyorum.

Av. Aydın Özdemir : Tabii tabii.

Nevzat Bahtiyar : Hacı Hasan'a demiş: "Git söyle, eğer istiyorsa böyle bir miktar para, bir arazi verelim, ondan sonra evini iyi hale getirelim". Böyle bir şey söylemişler bilmiyorum.

Av. Aydın Özdemir : Bunu kardeşiniz size söyledi?

Nevzat Bahtiyar : Evet kardeşimiz.

Av. Aydın Özdemir : Ona da Rıza Güran aracılar vasıtasıyla teklif etmiş?

Nevzat Bahtiyar : Bilmiyorum.

Av. Aydın Özdemir : Onun size söylediğini soruyorum. Tamam. Sizin Arif Güran'la bir husumetiniz var mı?

Mahkeme Başkanı : Bu soruyu sorduk Avukat Bey. Lütfen lütfen. O zamana getirin direkt, Aranızda bir husumet yoktu.

Av. Aydın Özdemir : Hemen söylüyorum.

Mahkeme Başkanı : Bakın şöyle yapalım, daha önceki beyanınızda "Aramızda bir husumet yoktu" dediniz, sorunuzu sorun.

Av. Aydın Özdemir : Tamam başkanım.

Av. Aydın Özdemir : Şöyle, Nevzat'a ailenin şöyle bir iddiası var; "Daha önce biz Nevzat'a kekemedir, kekeme olduğu için işte kekemelik üzerinden onunla dalga geçtik, bu nedenle bizim kızımızı öldürdü" gibi bir iddia var. Sizinle kimse böyle bir dalga geçti mi?

Nevzat Bahtiyar : Yok.

Av. Aydın Özdemir : Peki bu olaydan önce, yani Narin'in olayından önce, olay gününden önce Salim size ben Narin'i öldüreceğim dedi mi?

Nevzat Bahtiyar : Yok.

Av. Aydın Özdemir : Salim tutuklandığı gün, Süveyla Özkan, tanıyor musunuz?

Nevzat Bahtiyar : Evet tanıyorum.

Av. Aydın Özdemir : Süveyla Özkan Sizin eşinize ve ailenize "Salim tutuklandı, Nevzat'ı da tutuklayacaklar" şeklinde bir şey söyledi mi?

Nevzat Bahtiyar : Yok.

Av. Aydın Özdemir : Eşinizle böyle bir beyan oldu mu?

Nevzat Bahtiyar : Yok.

Av. Aydın Özdemir : Siz eşinizle bu olayla ilgili konuştunuz mu? Olaydan sonra hiç bilgi vermediniz?

Nevzat Bahtiyar : Yok.

Av. Aydın Özdemir : Cesedi tek mi götürmüştünüz oraya? Peki cesedin bir bacağının kesik olduğu tespit edilmiş veya hayvanlar tarafından parçalandığı tespit edilmiş.

Nevzat Bahtiyar : Bilmiyorum.

Av. Aydın Özdemir : Salim Güran, siz ilk beyanınızda "Salim bana cesedi başta parçala" dedi demiştiniz, parçaladınız mı hiç cesedi?

Nevzat Bahtiyar : Hiç ellemedim.

Av. Aydın Özdemir : Ayağı kesilmiş miydi?

Nevzat Bahtiyar : Ben hatırlamıyorum, yani ayağı kesik falan değildi.

Av. Aydın Özdemir : Hatırlamıyorsunuz.

Nevzat Bahtiyar : Yani ayağı kesik değildi.

Av. Aydın Özdemir : Kesik değildi.

[Müşteki Arif Güran'ın yüksek sesle konuşarak birtakım sözler söylediği duyuldu.]

Mahkeme Başkanı : Arif Bey, lütfen ya. Seni bir lavaboya götürsünler. Su verin ona. Arif Bey, beni duyuyor musun? Tamam. Birazcık daha sakin olun lütfen. Bana ne diyor bu adam? Anlayışla karşılıyorum, lütfen diyorum. Bir su alın, yüzünüze su vurun.

### Av. Erdem Kaya

Av. Erdem Kaya : Ramazan Ayla'yı tanıyor musunuz?

Nevzat Bahtiyar : Ramazan Ayla, Ramazan Ayla bizim damattır.

Av. Erdem Kaya : Evet İstanbul'da yaşıyor.

Nevzat Bahtiyar : Ramazan Ayla. Yok, Diyarbakır'da yaşıyor.

Av. Erdem Kaya : Şimdi olaydan bir gün sonra, 22 Ağustos'ta 3 defa aramışsınız. 23 Ağustos'ta da 2 defa aramışsınız. Bu kadar sık görüşür müsünüz her gün?

Nevzat Bahtiyar : Vallahi sürekli, yani bu şey konusunda beni arıyordu. Kız bulundu mu, yani ne oldu?

Av. Erdem Kaya : Aradığınız zaman İstanbul'da mıydı? Yoksa Diyarbakır'da mıydı?

Nevzat Bahtiyar : İstanbul'da. Diyarbakır'da ben hatırlamıyorum. Beni aradı, Narin için aradı. Yani, buldunuz ne oldu? Yani, bir haber var mı yok mu? O konuda beni aramış.

### Av. Asya Cemre Işık

Av. Asya Cemre Işık : Daha önceki ifadelerinden birinde Nevzat "Narin'i ilk gördüğümde kulağının arkasında bir kan vardı" dedin. Bunu bize anlatır mısın?

Nevzat Bahtiyar : Kan değildi. Böyle bir morluk falan vardı. Ya solda ya sağda vardı. Morluk vardı kan yoktu.

Av. Asya Cemre Işık : Neden kan dedin o zaman?

Nevzat Bahtiyar : Kırmızı olmuştu.

Mahkeme Başkanı : Diyarbakır Barosu bittiyse Arif Güran vekiline söz veriyorum.

## Katılan Arif Güran vekili

### Av. Berat Kocakaya

Av. Berat Kocakaya : Arif Güran'la bir ticaretiniz var mıydı?

Nevzat Bahtiyar : Yok.

Av. Berat Kocakaya : Hiç araba alışverişinde bulundunuz mu?

Nevzat Bahtiyar : Almıyorum, yani.

Av. Berat Kocakaya : Bir para muhabbeti oldu mu arabanın aranızda? veya bir başkası tarafından bir aracın alışverişinden dolayı sizden para teklif edildi mi? Bir ticarette bir sıkıntı yaşadınız mı?

Nevzat Bahtiyar : Yok sıkıntı. Sadece bir arabada yaşamıştık.

Av. Berat Kocakaya : Yani demek ki daha önce ticaret yapıyorsunuz.

Nevzat Bahtiyar : O arada hiç yapmamıştım.

Av. Berat Kocakaya : O aracı açıklayabilir misin? Sıkıntı olan aracı?

Nevzat Bahtiyar : Antakya arabası. Ben almıştım. 2 aydır 1 aydır bende kaldı. Sorun çıktı ruhsatta. Ruhsattan dolayı ben götürdüm, ben dedim, geri vereyim orada arabayı. Adama geri verdiler, orada Arif'le birlikte arabayı sattılar. Arabayı sattılar ama araba parça halinde olduğunu biz de bilmiyorduk. Şasi numarası başka, kapakları hepsi ayrı. Ondan dolayı adam almıştı, bir arkadaş almıştı o arabayı. Kaza yapmıştı, adam kaza yapmıştı. Kazadan dolayı polis falan gelmişti. İnceleme yaptıktan sonra araba parça parça.

Av. Berat Kocakaya : Evet arabada bir sıkıntı çıkmıştı. Peki, bu sattığınız adam sizden bir talepte bulundu mu? Sizden veya Arif Bey'den?

Nevzat Bahtiyar : Bilmiyorum, yani onlar söylediler 80 bin lira cezayı bize kesmişler.

Av. Berat Kocakaya : Sattığınız insanlar?

Nevzat Bahtiyar : 50 bin lira ben verdim.

Av. Berat Kocakaya : 50 bin lira siz verdiniz.

Nevzat Bahtiyar : 50 bin lira ben verdim 20 bin lira da ben vereceğim.

Av. Berat Kocakaya : Evet Peki bu 50 bin lira yüzünden Arif Bey'e bir kininiz bir düşmanlığınız var mı?

Nevzat Bahtiyar : Yok, sadece ben onunla konuştum. Bu kelimeyi o bana söyledi. Dedi; mahkemeye vermiş, mahkeme kazansa 50 bin lirayı vereceğim.

Av. Berat Kocakaya : Bu kadar? Başka bir ticaretiniz yok? Bundan dolayı da bir kininiz var?

Nevzat Bahtiyar : Yok.

Av. Berat Kocakaya : Peki teşekkür ederim.

## Aile ve Sosyal Hiz. Bakanlığı

### Av. Elif Aslı Şahin Torun

Av. Elif Aslı Şahin Torun : Salim Güran'la yakın arkadaş olduğunuzu söylüyorsunuz. Yüksel Güran ile Salim Güran arasındaki ilişkiyi daha önceden biliyor muydunuz?

Nevzat Bahtiyar : Bilmiyordum.

Av. Elif Aslı Şahin Torun : O gün öğrendiniz yani?

Nevzat Bahtiyar : Yani, ben o gün öğrendim. Başka ben hiçbir şey bilmiyorum.

Av. Elif Aslı Şahin Torun : Ama çok yakın arkadaşmışsınız.

Nevzat Bahtiyar : Evet ama ben onunla hiçbir şey bilmiyorum.

Av. Elif Aslı Şahin Torun : Peki Narin bu ilişkiyi cinsel ilişki şeklinde mi görmüş? nasıl anlattı Salim Bey?

Nevzat Bahtiyar : Bilmiyorum ben, onunla bir bilgim yok.

Av. Elif Aslı Şahin Torun : Ama ilişki yaşarken gördüğünü söyledi, değil mi?

Nevzat Bahtiyar : Kendisi söyledi, ama ben görmemişim.

Av. Elif Aslı Şahin Torun : Tamam, şimdi savcılıkta son alınan beyanlarınızın doğru olduğunu söylediniz ancak 21.09.2024 tarihli beyanda "Ayakları çuvala sığmadı, çuvalın ağzını bağlayamadım" demiştiniz. Şimdi de çuvalın ağzını çantasının ipiyle bağladım dediniz. Hangi ifadeniz doğru?

Nevzat Bahtiyar : İpi bağlarken bir ayak dışarıda kalmıştı.

Av. Elif Aslı Şahin Torun : Yani nasıl dışarıda kalabilir?

Nevzat Bahtiyar : Kapattıktan sonra bir ayak dışarıda kaldı. Ben ayağı çuvalın içine koymadım. Öyle bıraktım.

Av. Elif Aslı Şahin Torun : Yani ayağını parçalamadınız?

Nevzat Bahtiyar : Yok.

Av. Elif Aslı Şahin Torun : Uzuvlarında herhangi bir eksiklik yoktu?

Nevzat Bahtiyar : Yok.

Av. Elif Aslı Şahin Torun : Evde bir ceset taşıma var, konuşma var, tehditler var. Ancak HTS kayıtlarına göre evde Enes ve anne de var. Hiçbir gürültü vs. bir tartışma konuşma duymadınız mı evde?

Nevzat Bahtiyar : Hiç duymadım.

Av. Elif Aslı Şahin Torun : Kimseyi de görmediniz. Peki Eğertutmaz deresine cesedi nereye koyacağınızı daha öncesinde Salim Bey'e söylemiş miydiniz?

Mahkeme Başkanı : Bunu da sorduk Başka?

Av. Elif Aslı Şahin Torun : Başka bir şey yok.

### Av. Abdullah Yılmaz

Av. Abdullah Yılmaz : Öncelikle şunu samimi olarak belirtmek isterim, elbet sorulmuş olabilir ama nihai bir hedefe ulaşmak içindir sorular, çünkü efendim herkes de görüyor, beyanlar kesik kesik, değişiyor beyanlar. Sürekli hatırlaması gereken yerlerde hatırlamıyor.

Mahkeme Başkanı : Hızlıca buyurun.

Av. Abdullah Yılmaz : Şunu söylemek istiyorum efendim. Buranın çok önemli olduğunu düşünüyorum, HTS baz kayıtlarının Yüksel Güran 14:28'de 15:38 arasında evde efendim. Nevzat Bahtiyar 15:41 arasında Nevzat Bey 15:08'de Salim Bey arıyor 15:27'de evde.

Mahkeme Başkanı : Netice? direkt soru Avukat Bey.

Mahkeme Başkanı : Soruyu alabilir miyim?

Av. Abdullah Yılmaz : Soru şu efendim. Beyanları sürekli değiştiği için HTS kayıtlarından, beyanlarından sonuç çıkartamadık. Savcım da sordu, Diyarbakır Barosu Başkanımız da sordu ama Salim Güran 14:52 ile 15:19 arası evde. Ahıra gidiyor, sürekli gidip geliyor 16:10'a kadar evde.

Mahkeme Başkanı : Avukat Bey soru soru, savunma değil.

Av. Abdullah Yılmaz : 17:40'da arıyor kendisini, 17:46'da Salim'e tekrar dönüş yapıyor WhatsApp'tan. Net olarak anlatılmadı efendim.

Mahkeme Başkanı : Hatırlamıyorum, WhatsApp'tan aramadım dedi ya.

Av. Abdullah Yılmaz : Bir de efendim, son olarak "evde ben kimseyi görmedim" diyor. Evden çıkarken "Yüksel Hanım ağlıyordu" efendim, bunlarda bir çelişki var.

Mahkeme Başkanı : Şimdi WhatsApp'tan aradığımı "hatırlamıyorum" diyen adama WhatsApp'tan ne konuştun diye nasıl sorabilirim ben?

Av. Abdullah Yılmaz : Ama efendim, işte beyanlar sürekli değişiyor biz ısrarla soracağız.

Mahkeme Başkanı : Ben de 33 kere sordum, 33 kere de o sordu. WhatsApp'tan aramadım, diyor. Aramadım diyen adama WhatsApp'tan ne konuştun, diyemem.

Av. Abdullah Yılmaz : Evde sadece Salim Güran var diyor.

Mahkeme Başkanı : Sordum "Yüksel'in nereden geldiğini bilmiyorum tepede gördüm."

## Enes Güran Müdafi

### Av.Mahir Akbilek

Av. Mahir Akbilek : Nevzat Bahtiyar. İlk bilgi sahibi beyanlarında, şüpheli sıfatıyla verdiğin beyanlarda söz etmemene rağmen, Yüksel Güran'dan daha sonra söz etme nedenin bu çok önemli ayrıntıyı söz ettiğin tarihte hatırlaman mıdır? Yoksa şu an sayın mahkemeyle daha önceden de Cumhuriyet Başsavcılığı'yla ve kolluk görevleriyle paylaşmadığın başka bir husus daha mı var?

Nevzat Bahtiyar : Bilmiyorum. Bir bilgim yok.

Av. Mahir Akbilek : Daraltarak tekrarlayacağım. Daha önceki sıralı beyanlarınızda Yüksel Güran'dan bahsetmemenize karşın en son beyanınızda Yüksel Güran'dan bahsetme sebebiniz, onu gördüğünüzü ifade etmeniz onun ağladığını tarif etmeniz sadece o tarihte hatırlamanızdan mı mütevellittir? Ondan kaynaklı mıdır? Bu çerçevede anlatmadığınız başka bir husus da var mı?

Nevzat Bahtiyar : Yok başka bir husus yok.

Av. Mahir Akbilek : Tamam. Narin ile ilgili yakalanma tarihine kadar hiç kimseyle, aileniz dahil, konuşmadığınızı ifade ettiniz.

Nevzat Bahtiyar : Evet.

Av. Mahir Akbilek : Tamam. Neden siz yakalandıktan sonra aile üyeleriniz sizinle ilgili alibi delilini de kapsayacak şekilde beyanlarda bulunurlar? Yani örneğin sizin Pirinçlik'te olay tarihinde Derviş isimli bir şahsın villasının sıva işini yaptığınıza ilişkin birinci derece kan hısımlarınız tanıklık içeren beyanlarda bulundu. Sizin bir yönlendirmeniz var mıdır bununla ilgili?

Nevzat Bahtiyar : Yok.

Av. Mahir Akbilek : Sizin, siz konuşmadıysanız aile üyelerinizle, neden sizi bu şekilde bir sahte delil silsilesi yaratarak koruma ihtiyacı hissettiler?

Nevzat Bahtiyar : Ben ailemle hiç konuşmadım ama ailemle hiç konuşmadım.

Av. Mahir Akbilek : Peki. 15.08 (2024) tarihli telefon aramasını başlatan sizsiniz. Siz arıyorsunuz.

Nevzat Bahtiyar : Ben arıyorum.

Av. Mahir Akbilek : Evet. 21 Ağustos 2024 tarihinde saat tam olarak kaç gibi konutunuzdan çıktınız? Veya Tavşantepe mahallesinden ayrıldınız? Saat belirterek ya da hatırladığınız kadarıyla.

Nevzat Bahtiyar : Şu saat hatırlamıyorum yani.

Av. Mahir Akbilek : Sabah saatlerinde ayrıldınız mı?

Nevzat Bahtiyar : Sabah, evet. Ben oradaki inşaata gitmiştim. Bizim bizim ev inşaatı. Elektriğini çekmek için ustayı çağırmıştım.

Av. Mahir Akbilek : Oğlunuzun inşaatına mı?

Nevzat Bahtiyar : Evet. Elektriği çağırmıştım.

Av. Mahir Akbilek : Yanınızda başka kimse var mıydı?

Nevzat Bahtiyar : Yok başka kimse yoktu.

Av. Mahir Akbilek : Hangi araçla gittiniz? hangi vasıtayla gittiniz? 23 plakalı bir kırmızı araç.

Nevzat Bahtiyar : Kırmızı araç.

Av. Mahir Akbilek : Bu araç sürekli gün içinde sizde miydi? El değiştirdi mi? Saat 11'de, 12'de bir de.

Nevzat Bahtiyar : Yok hiç değiştirdi.

Av. Mahir Akbilek : Sürekli sizdeydi?

Av. Mahir Akbilek : Az önceki beyanlarınızda ifade ettiğiniz üzere evinizin Süveyla Özkan'ın evine bakan cephesinde mi park halindeydi?

Nevzat Bahtiyar : Evet.

Av. Mahir Akbilek : On beş on altı dolaylarında?

Nevzat Bahtiyar : Evet.

Av. Mahir Akbilek : Tamam. Peki siz yine başkan beyin sorusuna okul ile sizin ahırın ucu arasındaki patika yolu kullanarak, çağrılmanız sonrasında, tepeyi çıktığınızı söylediniz.

Nevzat Bahtiyar : Oradan yani böyle gidip geliyorlar.

Av. Mahir Akbilek : Siz de oradan çıktınız değil mi? Salim sizi çağırdığında dediniz.

Nevzat Bahtiyar : Evet.

Av. Mahir Akbilek : Yaya vaziyette çıktınız?

Nevzat Bahtiyar : Ben biraz onun bu tarafından yani, tamam.

Av. Mahir Akbilek : 15:08'de aramayı yapıyorsunuz. 42 saniyelik bir görüşme saat 15:09 sularına yaklaştı. Okul kamerasında da 3.5-4 dakika arası bir farklılık var. Güncel değil. Yani aslında 15:11 sularında Narin tepeyi çıkıyor, çıktı veya bitti. Siz nasıl karşılaşmadınız onunla? Siz de yaklaşık 15:10 civarında o tepeyi çıkıyor olmanız gerekir.

Nevzat Bahtiyar : Ben, ben onu görmedim.

Av. Mahir Akbilek : Arif'in ev ahır eklentilerinde, bamya tarlasının orada, balkonun önünde, Salim ile Arif'in evinin arasında, Narin'i ve Narin'le bir çocuğu veya başka bir insanın sesini, hareketlerini gördünüz mü, duydunuz mu?

Nevzat Bahtiyar : Yok.

Av. Mahir Akbilek : Dümdüz mü gittiniz? Yani tepeyi çıktınız, dümdüz?

Nevzat Bahtiyar : Dümdüz.

Av. Mahir Akbilek : Başka insan görmediniz?

Nevzat Bahtiyar : Yok başka kimse görmedim.

Av. Mahir Akbilek : Evet. Peki kardeşleriniz özellikle Mehmet Bahtiyar, Vecdi/Vedat olarak bildiğiniz kardeşiniz görüşler yapılırken, yani cezaevinde siz bulunduğunuz süre içerisinde görüşler icra edilirken sadece bu şekilde size dışarıdan öğrendikleri bilgileri mi aktardılar?

Av. Mahir Akbilek : Yok.

Av. Mahir Akbilek : Mesela neden sizinle ilgili ilk evrelerde yalan beyanda bulunduklarını daha sonra aşama aşama doğruya doğru beyanlarını değiştirdiklerini, bunun nedenini size anlattılar mı? Veya siz karşılıklı bir diyalog şeklinde mi konuşuyordunuz?

Nevzat Bahtiyar : Sadece gel eee hal hatırını soruyordular. Bu konuda yani yani başka yani bir konuyla bizimle birlikte konuştuk. Konuştuğumuz bir şey yok. Yani sadece yani hal hatırını nasılsın iyisin ailemi ben özellikle ben istiyordum. Ailemi göreyim, ailemi göreyim. Yani başka yani bir nedenle yani oraya gelmemişim.

Mahkeme Başkanı : Bir dakika burayı tekrar alalım. Biraz kesik oldu. Tekrar söyler misiniz?

Nevzat Bahtiyar : Nasıl Sayın başkanım?

Mahkeme Başkanı : Yani aile bireylerinden hiçbiri sizinle normal rutin konuşmalar gerçekleştirdi, değil mi?

Nevzat Bahtiyar : Yani beni orada ziyaret ziyaret etmek için buraya gelmişti.

Mahkeme Başkanı : Sizi ziyaret etmek için gelmişti?

Nevzat Bahtiyar : Evet. Yani başka yani bir konuda yani bilmiyorum sadece o şey teklifi sadece onu, onu söylediler eee şey başka yani.

Mahkeme Başkanı : Para teklifinde bulundular?

Nevzat Bahtiyar : Yani başka yani bir şey tamam.

Av. Mahir Akbilek : Nevzat Bey, eşiniz Gazal hanım neden peki siz 15:08 görüşmesini yaptıktan hemen sonra arabayla evden ayrıldığınızı söylesin?

Nevzat Bahtiyar : Haberi, bunun haberi yoktu. Yani arka tarafta arka bahçede yani orada olduğumu bilmiyordu. Ben oradaydım.

Av. Mahir Akbilek : Siz kolluk ifadesi sırası sırasında sıra dışı bir baskı kötü muameleyle karşılaştınız mı?

Nevzat Bahtiyar : Yok.

Av. Mahir Akbilek : O dönemki beyanlarınızı yer gösterme tutanağında ve görüntülerine yansıyan davranışlarınızın sizin özgür iradenizle burada olduğu gibi sarf ettiğiniz beyanlar olduğunu varsayabiliriz yani.

Mahkeme Başkanı : Varsaymayız, sorduk, evet dedi de.

Av. Mahir Akbilek : Siz çok güzel bir şekilde sordunuz.

Mahkeme Başkanı : Evet dedi yani.

Av. Mahir Akbilek : Nevzat Bey, Salim'den ne kadar korkuyorsunuz? Ne kadar korkarsınız yani?

Nevzat Bahtiyar : Yani o ııı şeyden dolayı biraz çekindim, korktum. Ya başka bir korkumuz yok yani.

Av. Mahir Akbilek : Salim'den korkunuz neden geçti şu an? Ya bu beyanları artık daha ayrıntılı beyanlarda bulunabiliyorsunuz.

Av. Mahir Akbilek : Her şey ortaya çıktıktan sonra artık korku gitti.

Av. Mahir Akbilek : İlk beyanlarınızı verirken korku tesirinde kaldığınızı söylemiştiniz.

Nevzat Bahtiyar : Doğrudur.

Av. Mahir Akbilek : Peki korkmanıza rağmen neden Salim'den bahsettiniz? Salim'in çocuğu öldürdüğünü, onu söylediniz.

Nevzat Bahtiyar : Evet.

Av. Mahir Akbilek : O esnada da, o esnada da korkmadınız mı Salim'in size bir kötülük yapabileceğine ve yaptırabileceğinden?

Nevzat Bahtiyar : Düşünmedim.

Av. Mahir Akbilek : Başkanım teşekkür ederim.

Mahkeme Başkanı : Ben teşekkür ederim avukat bey.

### Av. Mustafa Demir

Av. Mustafa Demir : Şimdi öncelikle beyanında orada ailesi dışında kimsenin olmadığını söylüyor. Eski muhtarla bir akrabalığı var mıdır Nevzat'ın?

Nevzat Bahtiyar : Yok.

Av. Mustafa Demir : Hiç yakından, uzaktan, annenizin akrabalığı, hiçbir bağınız yok?

Nevzat Bahtiyar : Yok.

Av. Mustafa Demir : Şimdi olayda eve gittiğini söylüyor. Yani şöyle mi anlayalım biz? Salim öldürdü. ceset evde. Çıkıyor dışarıya. Yani sizi aramaya mı çıkıyor? Yani ne diye çıktı? Telefonda bununla ilgili bir şey konuştunuz mu?

Nevzat Bahtiyar : Yok. Hiç konuşmadık.

Av. Mustafa Demir : Peki cesedi aldınız. Az önceki beyanınızda şunu söylediniz. Evde, annem evdeydi. Çocuklarım evdeydi. Eşim evdeydi. Evinizin ahır penceresi diye söylediğiniz yer aslında çatı. Çatıdan çocuğu attınız. Haliyle bir ses çıkması gerekir. Bu ses çıkmadı mı? Kimse duymadı mı?

Nevzat Bahtiyar : Yok.

Av. Mustafa Demir : Kimse duymuyor. Yani ses çıkmadı.

Nevzat Bahtiyar : Yok.

Av. Mustafa Demir : Ha. Peki aldınız çuvalı. Haliyle nereden, siz ev ahıra nereden giriş yaptınız?

Nevzat Bahtiyar : Oradan şeyden giriş yaptım. bizim o bahçe patlıcan filan ekmiştir. Oradan, oradan ahıra.

Av. Mustafa Demir : Oradan ahıra giriş var mı? Biz oradan baktığımızda ahıra bir giriş kapı görmedik?

Nevzat Bahtiyar : O oradan yukarıdan ben bahçeye indim. sebze bahçesine gittim. Patlıcan filan. Oradan kapıdan şey gittim.

Av. Mustafa Demir : Arka tarafında bir oradan, ya ahıra siz kapıdan girmediniz mi?

Nevzat Bahtiyar : Yok kapıdan değil. Arka tarafında pencereden girdim.

Av. Mustafa Demir : Siz de pencereden girdiniz.

Nevzat Bahtiyar : Pencereden.

Av. Mustafa Demir : Orada bir pencere var ve siz o pencereden girdiniz?

Mahkeme Başkanı : Neden pencereden girdin peki? Niye pencereden girdin?

Nevzat Bahtiyar : Pencereden ııı yani oradan girdim. Dedim ön taraftan gidim belki biri görür. Ben ondan dolayı yani kalktım arka taraftan ben pencereden oradan.

Mahkeme Başkanı : peki bunu sana Salim mi söyledi?

Nevzat Bahtiyar : Yok. Yok başkanım.

Mahkeme Başkanı : Sen neden biri görür diye korktun? Yani neden biri görür deyip de böyle bir plan yaptın?

Nevzat Bahtiyar : Yani ailemden biri görür çünkü benim hanım evdeydi.

Mahkeme Başkanı : Onu sordum. Anneniz de evdeydi?

Nevzat Bahtiyar : Annem aşağı taraftaydı.

Mahkeme Başkanı : Tamam. Onlar görmesin diye böyle yaptınız.

Av. Mustafa Demir : Pencerenin yerden yüksekliği ne kadar? Yani rahat geçebileceğiniz bir pencere?

Nevzat Bahtiyar : Evet.

Av. Mustafa Demir : Yani bu, evet anladım. Peki siz evde 15:08'de aradınız. Suyla ilgili konuştunuz değil mi? 15:08'de Salim'i aradınız.

Nevzat Bahtiyar : Evet.

Av. Mustafa Demir : Peki o sırada ne yapıyordunuz? hani niye arama gereği duydunuz? Su konusu nasıl açıldı? Onu hiç anlatmamışsınız. Su konusunda evde su mu yoktu? Peki ya ne yapıyordunuz tam o sırada?

Nevzat Bahtiyar : O sırada yani ııı başka su yoktu. bizim hanım ben söyledim suyumuz geliyordu, suyumuz gelmiyor. Ben de ben Salim'i aradım. Gelsinler, ekip gelsinler, baksınlar yani. Bu nedendir yani?

Av. Mustafa Demir : Anlaşılmadığımı düşünüyorum, tekrar soruyorum. Şimdi siz çalışmak için Tavşantepe'de oğlunuzun evine gittiniz. Öğlen yemeği için eve geldiniz. İfadenizde böyle geçiyor.

Nevzat Bahtiyar : Evet. Yemek için gelmiştim.

Av. Mustafa Demir : Yemek yediniz mi?

Nevzat Bahtiyar : Yemek yedim.

Av. Mustafa Demir : Yemekten sonra mı aradınız Salim'i?

Nevzat Bahtiyar : Yemekten sonra.

Av. Mustafa Demir : Peki yani el yıkamak için mi su ihtiyacı oldu? Niçin su ihtiyacı oldu? Ben anlamadım yani niye?

Nevzat Bahtiyar : Bahçeyi ağaçları sulamak için.

Av. Mustafa Demir : E ağaçları sulamak için hortum takıldı zaten?

Nevzat Bahtiyar : Ben o suyu ben annemlerden ben çekmiştim.

Av. Mustafa Demir : Evde su var mıydı?

Nevzat Bahtiyar : Evde su vardı.

Av. Mustafa Demir : E o zaman evde suyunuz kesik değil?

Nevzat Bahtiyar : Ben annemlerden alıyordum. Su var diye.

Av. Mustafa Demir : Anlamadım.

Mahkeme Başkanı : Ya şunu soruyor avukat hanım. Şey avukat bey. Evdeki musluklardan su akıyor muydu? Bunu soruyor.

Nevzat Bahtiyar : Yok akmıyordu.

Av. Mustafa Demir : Tamam. Peki 15:08'de aradınız. Yemek falan bitmişti. Aradınız. Suyunuz yok. Ondan sonra hemen sonra mı çıktın? Oturdun mu?

Nevzat Bahtiyar : Hani hatırlamıyorum.

Av. Mustafa Demir : Yani bahçeyi sulamaya çıkmadın mı hemen?

Nevzat Bahtiyar : Çıktım yani.

Av. Mustafa Demir : Bahçeyi de netleştirelim.

Nevzat Bahtiyar : Sulamaya çıktım.

Av. Mustafa Demir : Bahçeyi netleştirelim. Kafada soru işareti kalmasın. Evinin ön tarafında bir dut ağacının olduğu yer var.

Nevzat Bahtiyar : Evet.

Av. Mustafa Demir : Bir de arkada patlıcanların olduğu yer var. Evet. Sen nereyi suladın?

Nevzat Bahtiyar : Eee dut ağacı onun.

Av. Mustafa Demir : Az önce patlıcan dedin. İlk soru ilk anda sorulduğunda heyet tarafından patlıcanların olduğu yeri dedin?

Nevzat Bahtiyar : Patlıcan ilk, ilk değil. Yani ben oradan, yani patlıcanın içine gitmiştim. Orada yani sulama, yani patlıcandan sulama değil. Patlıcan olduğunda oraya gitmiştim. Yani bizim hanımı görmemiştim.

Av. Mustafa Demir : Yani ben şöyle anlıyorum net sorayım. 15:08'de konuştuktan sonra patlıcanlara mı çıktın? Dutların olduğu yere mi çıktın? yani hatırlaman lazım.

Nevzat Bahtiyar : Hatırlamıyorum ben onu. Yani en son yani bildiğim kadar yani ben eee avluya çıkmıştım.

Av. Mustafa Demir : Şimdi senin evinde avlu, nereye çıktığını bilmediğimiz için, bilmiyor yani, sen hortumu çektiğinde hortum nereden açılıyor? Ya açman da lazım ya. Hortum arkada mı? Önde mi? Yani patlıcanların olduğu tarafta.

Nevzat Bahtiyar : Yok. Yani hortum eee dut ağaçlarının tarafındaydı.

Av. Mustafa Demir : Peki ucu neredeydi yani? Sulama yapacağın uç neredeydi? Şimdi şunun için soruyorum. Eğer 15:08'de sen çıktıysan ve patlıcanların oradaysan Narin'i görmeme ihtimalin yok?

Nevzat Bahtiyar : Ya yani ben Narin'i görmedim yani. Şimdi yani görsem, diyeceğim görmüştüm.

Av. Mustafa Demir : Peki biz kabul etmeyeceğiz. Zaten anlatacağız birazdan bu daraltılmış HTS'yi de. HTS'ye göre de 15:08'de konuştuktan sonra 15:10'da Arif'le Salim'in arasındaki alanda olduğunu söylüyor. Sen hangi güzergahı kullanarak yukarıya çıktın?

Nevzat Bahtiyar : Ben, şey tarafından, ben yukarıya çıktım. Patlıcan.

Av. Mustafa Demir : Patikadan çıktın yani? Anladım. Peki o çuval, şeyi, açık alanda elinde şey, yürüdün. Peki araban nerede park halindeydi?

Nevzat Bahtiyar : Arabam aşağı taraftaydı.

Av. Mustafa Demir : Nerede? Evinin neresinde? Yani kapına ne kadar? Sıfır mıydı? Sen peki ahırına giren bir anladığımız yukarıdan baca var. Bir pencere varmış. Başka ne var? Kapı?

Nevzat Bahtiyar : Kapı iç tarafta var.

Av. Mustafa Demir : Nereye açılıyor bu? Avlu dediğin neresi? Senin evin mi? Annenin evi mi? Dut ağacının olduğu yer mi?

Nevzat Bahtiyar : Evet.

Av. Mustafa Demir : Tamam çok güzel. Peki dut ağacının olduğu yer. Evinin içinden görünüyor mu? Evinin içinden avlu dediğin yeri görebiliyor musun? Pencereden, kapıdan?

Nevzat Bahtiyar : Görebiliyoruz.

Av. Mustafa Demir : Peki. Sen cesedi aldın, bir çuvala koydun. Onunla nasıl çıktın? Ha nereden çıktın? Yani kapıdan çıktın? Avlunun olduğu kapıdan çıktın?

Nevzat Bahtiyar : Avlunun kapısından ben çıktım.

Av. Mustafa Demir : Yani sonra da dönüp battaniyeyi mi aldın?

Nevzat Bahtiyar : Yok, battaniyeyle birlikte çıktım.

Av. Mustafa Demir : Birlikte çıktın. Evden kimse seni görmedi bu anda. Ya bir ses falan olmadı mı hani çuvalı ararken? Çocuğu atmışsın. Kendin o dar alandan girdin. Hiç ses çıkmadı bu arada? Burada sen eşim öyle değil diyorsun ama eşinin 10.08.2024'de alınan ifadesinde şöyle diyor; "Nevzat aradıktan sonra ağaçları sulayacağım diye çıktı. Arabaya bindi. Ben de arkasından çıktım. Aşağı yola indiğini gördüm" diyor.

Nevzat Bahtiyar : Yok.

Av. Mustafa Demir : Eşin yalan mı söylüyor?

Nevzat Bahtiyar : Ben böyle bir şey, yani gitmemiş miyim?

Mahkeme Başkanı : Bu soruya cevap vermeme hakkına sahipsin. Tanık olan eşi soruşturma geçirebilir. Yalan mı söylüyor diye sorulmaz.

Mahkeme Başkanı : Yok bu soruya cevap vermiyorsun. Yo yo yo bu bu Gazal'ı şüpheli sıfatına sokar avukat bey bu olmaz.

Mahkeme Başkanı : Başka Enes müdafilerinden sorulmak isteyen biri var mı? Tamam. Enes müdafilerini bitirdim. Teşekkür ederim. Yüksel müdafilerinden soru sormak isteyeni alabiliriz. Buyurun.

## Yüksel Güran Müdafileri

### Av. Yılmaz Demiroğlu

Av. Yılmaz Demiroğlu : Meslektaşlarımız sağ olsun sizler de olası bütün soruları sordunuz. Sadece bir hususu çok net bir şekilde izah etmenizi istiyoruz. Nevzat Bahtiyar, tüm Türkiye'nin sabrı tükendi.

Nevzat Bahtiyar : Doğru.

Av. Yılmaz Demiroğlu : Lütfen doğru cevap verin. Salim Güran'ın sizin evinizden gidişte Salim Güran'ın evi mi önce gelir Arif Güran'ın evi mi?

Nevzat Bahtiyar : Net olarak anlamadım yani.

Av. Yılmaz Demiroğlu : Sizin evinizden çıktığınızda Salim Güran'ın evine gitmek istediğinizde önce Arif Güran'ın evi mi gelir Salim Güran'ın evi mi?

Nevzat Bahtiyar : Arif Güran'ın evi gelir.

Av. Yılmaz Demiroğlu : Sonradan itiraz edeceğimiz daraltılmış baz raporuna göre Arif Güran'ın evini 15:10'da geçmiş ve Salim Güran'la Arif Güran'ın evi arasında bulunan patika yolda görünüyorsunuz. Bu kayda göre ve yine okul kamerasında tespit edildiği üzere Narin Güran en son 15:11'de görülüyor. Yani Narin bu kayda göre henüz eve ulaşmadan siz patika yoldasınız. Narini o patika yoldan alıp mı gittiniz ahıra?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Bu kaydı kabul etmiyorsunuz. Kabul etmemekle birlikte değil mi? O daraltılmış, kabul etmemekle birlikte soruyorsunuz?

Av. Yılmaz Demiroğlu : Kabul etmemekle birlikte soruyoruz.

Mahkeme Başkanı : Tamam. Cümleye öyle başlayalım.

Av. Yılmaz Demiroğlu : Sadece bunu soruyoruz. Şimdi bu daraltılmış baz raporuna göre yaptığınız hareketlere göre o patika yolda Narin giderken görmüş olmanız lazım. Hiç mi görmediniz?

Nevzat Bahtiyar : Hiç görmedim.

Av. Yılmaz Demiroğlu : Hiç görmedin. Narin'i seviyor muydunuz?

Nevzat Bahtiyar : Narini herkes seviyor.

Av. Yılmaz Demiroğlu : Ben de seviyorum.

Nevzat Bahtiyar : Benim de çocuğum aynı. O da aynı. Herkesin ki aynı.

Av. Yılmaz Demiroğlu : Sen seviyordun yani Narin'i.

Nevzat Bahtiyar : Ben normal bir çocuktu yani. Seviyorum.

Av. Yılmaz Demiroğlu : Narin'in torununla arkadaşlığı var mıydı?

Nevzat Bahtiyar : Bilmiyorum.

Av. Yılmaz Demiroğlu : Bilmiyor musun?

Nevzat Bahtiyar : Bilmiyorum.

Av. Yılmaz Demiroğlu : Toruna alışveriş yaptığında Narin'e yapar mıydın hiç?

Nevzat Bahtiyar : O da olsaydı, ona da yapardım.

Av. Yılmaz Demiroğlu : Verdin mi hiç cips falan?

Nevzat Bahtiyar : Yok hiç vermedim.

Av. Yılmaz Demiroğlu : Hiç böyle "Narin al bu harçlık senin olsun" demedin mi?

Nevzat Bahtiyar : Yok.

Av. Yılmaz Demiroğlu : Peki. Az önce meslektaşım sordu tekrar soruyoruz. Sizin eşiniz olay günü "Ben Nevzat'a kız kardeşim olan Zeynep'ten giderken peynir almasını istedim".

Nevzat Bahtiyar : Doğrudur.

Av. Yılmaz Demiroğlu : Nevzat evden çıktığı sırada ben de balkondaydım.

Nevzat Bahtiyar : Balkona çıkmış olabilir yani ben.

Av. Yılmaz Demiroğlu : Arabayla gittiğinde arabayla gittiğini gördüm diyor. Buna ne diyorsun?

Nevzat Bahtiyar : Ben gitmemiştim. Arabayla gitmemiştim.

Av. Yılmaz Demiroğlu : Peki. Siz az önceki sorgunuzda dediniz ki; "Ben gittiğimde Narin'i evin içerisinde yerde yatar vaziyette gördüm. Battaniyeye sardık ve o şekilde bana teslim edildi. Ben gittim eve", değil mi? Evin içerisinde sana teslim edildi.

Nevzat Bahtiyar : Yok.

Av. Yılmaz Demiroğlu : Birlikte dışarıya getirmiştim.

Av. Yılmaz Demiroğlu : Birlikte Salim'le dışarıya getirdiğinizi söylüyorsunuz. Sonra Salim geldi battaniyeyi almak için?

Nevzat Bahtiyar : Evet.

Av. Yılmaz Demiroğlu : Aşağı arabayla geldi değil mi? Araba ile? Siz evden çıktığınızda biz Arif Güran'ın evini net bir şekilde artık haritalardan gözle gördük. Tam ahır tarafından geldiğinde tabak gibi meydan, köy meydanı. Değil mi? Bütün her taraftan görülür.

Nevzat Bahtiyar : Evet.

Av. Yılmaz Demiroğlu : O tepe her taraftan görünüyor değil mi köyün her tarafından?

Nevzat Bahtiyar : Yani o, yani köyün her tarafını yani.

Av. Yılmaz Demiroğlu : Sizin ahıra giden ahıra gittiğinde Arif Güran'ın evinden ahıra gittiğinde köyde kimse görmez mi orayı?

Nevzat Bahtiyar : Ama kimse yoktur.

Av. Yılmaz Demiroğlu : Görebilir, kimse yoktur. Peki Salim'in arabası varken niye siz battaniyeyle taşıma gereği duydunuz? Arabaya atsaydınız daha pratik değil miydi?

Nevzat Bahtiyar : Bilmiyorum.

Av. Yılmaz Demiroğlu : Nasıl bilmiyorsunuz? Daha güzel, en azından kimse görmez. Söylediğinde neden bahsetti?

Mahkeme Başkanı : Salim'in arabayı görmedi ki.

Av. Yılmaz Demiroğlu : Salim battaniye için arabayla iniyor ya ahıra.

Mahkeme Başkanı : Yok yok, ilk beyanında sordum ya. Sen Salim'in arabayı gördün mü? Arabasını görmemişti.

Av. Yılmaz Demiroğlu : Hayır ben şeyi soruyorum. Hani eğer madem. Cansız bedeni alıyor. Kucağında taşıyıp ahıra kadar götüreceğine.

Mahkeme Başkanı : Anladım demek istediğinizi.

Av. Yılmaz Demiroğlu : Araba varken neden kucağında taşıma ihtiyacı hissettin?

Nevzat Bahtiyar : Arabayı görmemiştim.

Av. Yılmaz Demiroğlu : Salim arabayla tam olarak battaniyeyi sizden nerede aldı? Tam olarak.

Nevzat Bahtiyar : Tam olarak arabanın yanında aldı.

Av. Yılmaz Demiroğlu : Arabanız neredeydi?

Nevzat Bahtiyar : Arabam kapının önündeydi. yani avlunun aşağı tarafındaki.

Av. Yılmaz Demiroğlu : Avlunun aşağı tarafında, okul tarafında. Evet.

Nevzat Bahtiyar : Okula giden yol.

Av. Yılmaz Demiroğlu : Okula giden yol tarafında. Tamam efendim. Teşekkür ediyorum.

### Av. Tuncay Erkuş

Av. Tuncay Erkuş : Salim Güran'la birlikte mi Narin Güran'ın olduğu eve girdiniz? Arif Güran'ın evine girdiniz?

Nevzat Bahtiyar : Evet birlikte girdik.

Av. Tuncay Erkuş : Odaya birlikte mi girdiniz? Narin Güran yerdeydi.

Nevzat Bahtiyar : Yerdeydi.

Av. Tuncay Erkuş : Girdiniz odaya.

Nevzat Bahtiyar : Hangi oda olduğunu ben hatırlamıyorum.

Av. Tuncay Erkuş : Odada neler vardı? Odayı tarif edebilir misiniz?

Nevzat Bahtiyar : Ben çok hatırlamıyorum yani. Hani herhangi bir şey bir zaten ben ııı meselesini hatırlamıyorum.

Av. Tuncay Erkuş : Boş oda diyorsunuz. Onu tarif edelim.

Av. Tuncay Erkuş : Evin girişinden hangi tarafa döndünüz? Hiçbir şekilde hatırlamıyorsunuz.

Nevzat Bahtiyar : Hatırlamıyorum.

Mahkeme Başkanı : Ben bir dakika avukat bey. Şimdi sen eve girdin. Eve girdiğin zaman girdikten sonra ne tarafa yöneldin? Sol tarafı sağ tarafı mı? Dikine mi gittin? Narin'in sol tarafı değil mi? Narin'in cesedi neredeydi? Ya hangi odaya girdin?

Nevzat Bahtiyar : Vallahi onu net olarak yani hatırlamıyorum. Hangi oda olduğunu.

Mahkeme Başkanı : Şimdi iddianamede belirtilen baza göre söylüyorum. kesinlikle iddiayı, iddiayı söylüyorum. 15:22'de Salim Güran eve girdiğinde 15:22'yle 15:26 arasında mutfağın karşısındaki boş odada.

Nevzat Bahtiyar : Hatırlamıyorum.

Mahkeme Başkanı : Tamam. Amin.

Av. Tuncay Erkuş : Efendim şunu da sormak istiyoruz. Bir araç ticareti var. Arif Güran'la bir araç ticareti yapmışsınız. Araçla ilgili problem çıktıktan sonra araç iade edilmiş ve sizden bir para talep edilmiş. Bu parayı ilk etapta sormuştu. İlk etapta sizden para talep edilince siz parayı direkt götürüp verdiniz mi? Yoksa bununla ilgili bir cemaat mi kuruldu? Böyle halk diliyle cemaat dediğimiz kimler vardı o cemaatte?

Nevzat Bahtiyar : Rükbettin Kaya vardı, Cahit Kaya vardı.

Av. Tuncay Erkuş : Evet. O parayı ne kadar sizin ödemeniz gerektiğini söylediler size?

Nevzat Bahtiyar : Orada yani 50 ilk önce 50 bin lira dedi. Sonra 40 bin lira vereceksin. Salim dedi 10 bin lira 20 bin lira ben vereceğim. 20 bin lira ve arı dedi ben vereceğim. 80 bin lira. Sonra Salim dedi ben vermiyorum.

Nevzat Bahtiyar : Ben de sen vermezse de yani ben vereceğime 50 de veririm.

Av. Tuncay Erkuş : Salim onu vermeyince 50'sini siz vermek zorunda kaldınız.

Nevzat Bahtiyar : 50'sini ben verdim.

Av. Tuncay Erkuş : Parayı nasıl ödediniz? Nereden temin ettiniz?

Nevzat Bahtiyar : Ev sahibi önce 40 bin verdi. Ben kalktım gönderdim. Arif'e gönderdim. Ondan sonra 10 bin lirası da ben onu aradım dedi ben taziyedeyim. Ben ben de hesap numarasını at. Ben 10 bin lirayı sana hesabına atayım.

Av. Tuncay Erkuş : 10 bin lirayı kardeşiniz mi ödedi? Siz mi ödediniz onu?

Nevzat Bahtiyar : Kardeşimi gönderdim. Mehmet gönderdi.

Av. Tuncay Erkuş : Evet. Söylemediniz az önce. Sonradan söylediniz. Peki bütün soruşturma evrelerindeki ifadelerinizde korktuğunuzu, Salim Güran'dan korktuğunuzu ki burada defalarca soruldu.

Nevzat Bahtiyar : Evet.

Av. Tuncay Erkuş : Yani Narin Güran'ın cansız bedenine ulaşması hususunda herhangi bir beyanatta bulunamayacağını söylediniz. Salim Güran'ı 02.09.2024 tarihinde tutuklandığına göre artık tehdit kalkmıştı ortadan. Herhangi bir tehdit altında değildiniz.

Nevzat Bahtiyar : Doğru.

Av. Tuncay Erkuş : 6 gün boyunca 3000'i aşkın personel işte helikopterler 80 tane drone aramaya devam ediyordu. Yani daha bir güvenilir yerdeydiniz. Artık tehdit kalkmıştı. Neden yerini söylemediniz? Hala aramalara devam edilmesini sağladınız? Veya bulunmasaydı siz hala yerini söyleyecek miydiniz?

Nevzat Bahtiyar : Yani fırsatım yani olmadı. Fırsat fırsat bulamadım. Onu oradan çıkartmaya.

Av. Tuncay Erkuş : Evet yani ayın 8'inde fırsat bulmuş olsaydın siz çıkaracaktınız. Yani siz mi çıkardınız? İtiraf mı ettiniz yoksa kolluk kuvvetleri yaptıkları araştırma sonucu mu buldu?

Nevzat Bahtiyar : Ben.

Av. Tuncay Erkuş : Yani dolayısıyla itirafçı siz değilsiniz.

Nevzat Bahtiyar : Ben eve geldim. Bilirim yani beni alacaklarını biliyordum. Ben evde oturdu ben kaçmadım. Yani kaçabilirdim de. Ben kaçmadım.

Av. Tuncay Erkuş : Yani küçük Narin'e ne zaman ulaşılmış olsa siz alınacaktınız.

Nevzat Bahtiyar : Bunu biliyordum.

Av. Tuncay Erkuş : Yani ona rağmen söylemediniz. Tehdit de ortada yok. Tamam efendim teşekkür ederim.

Mahkeme Başkanı : sen neden cesedi oradan almayı düşündün? Nevzat? Saklayacağım dedin. Yani niye saklama ihtiyacı hissettin?

Nevzat Bahtiyar : Iıı yani onu düşündüm yani sonra yani ben yani ki kendime düşündüm. Ben dedim niye ben orayı bıraktım? Yani oradan yani çıkartacaktım yani.

Mahkeme Başkanı : Çıkartacaktın, ancak fırsat olmadı öyle mi?

Nevzat Bahtiyar : Fırsat olmadı.

Nevzat Bahtiyar : Bir bir yolun üstüne bırakacaktım. Bir kişi gelip alacaktım.

Mahkeme Başkanı : Yani tesadüf eseri bulunsun gibi düşündün ama yapamadın.

Nevzat Bahtiyar : Yapamadım.

Mahkeme Başkanı : Bunu kendin düşündün. Salim'le falan planlamadınız. Peki niye kaçmayı hiç düşünmedim dedin? Yani neden? hani bunu iten saik neydi? Yani neden böyle bir düşünceye girdin? Kaçayım mı? Kaçmayayım mı derken?

Nevzat Bahtiyar : Yok vallahi hiç kaçmayı düşünmedim zaten. Ben de yani bulunmasını, ben de istedim zaten biliyordum yani niye?

Mahkeme Başkanı : Yakalanacağını biliyordun?

Nevzat Bahtiyar : Evet biliyordum.

Mahkeme Başkanı : O yüzden hiç kaçmaya gerek yok mu dedin?

Nevzat Bahtiyar : Kaçmaya gerek yok. Nasıl yakalanıyorum ben.

### Av. Furkan Çakır

Av. Furkan Çakır : Öncelikle sorularıma geçmeden önce bu menfur olaydan dolayı milletimizin başı sağ olsun. Tek gayemiz söz konusu yargılamada tüm maddi gerçekliğin şeffaf bir şekilde ortaya çıkarılmasıdır. Bu gaye doğrultusunda herkes burada. Eee şimdi Nevzat Bey söylemiş olduğunuz tüm ifadelerde özellikle sistemli bir şekilde Salim Güran'dan korktuğunuzu beyan ediyorsunuz. Ama Salim Bey 02.09.2024 tarihinde tutuklanıyor. Tutuklandıktan sonra gerçek anlamda bir pişmanlık hissi duyduğunuzu da söylüyorsunuz. Neden bu 6 günlük süreç zarfında gidip itirafçı olmadınız?

Nevzat Bahtiyar : Hiç düşünmedim.

Av. Furkan Çakır : O zaman gerçek anlamda bir şey yok. Hani vicdani bir rahatsızlık yok sizde?

Nevzat Bahtiyar : Düşünmedim. Yani ben sadece hani oradan bir caddenizde bir yolun içinde bırakacaktım. Yani bulmaları için.

Av. Furkan Çakır : Pekala. Şimdi siz vermiş olduğunuz ifadelerinizde "Ben eve girdim. Yüksel Güran'ın evine girdim. Eve girdikten sonra Narin Güran'ın bedeninin, ölü bedeninin soldaki bir odada olduğunu, bulunduğunu" söylediniz. Şimdi solda kaç tane oda vardı hatırlıyor musunuz?

Nevzat Bahtiyar : Hatırlamıyorum ben.

Av. Furkan Çakır : Peki eve girdiniz. Solda hangi odaya girdiğinizi hatırlıyor musunuz?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Furkan Çakır : Peki. Peki, odada eşya falan var mıydı? Peki, odada eşyalar yoktu diye varsayalım. Odada taşınılması mümkün olmayan bir eşya dikkatinizi çekti mi? Tamam peki. Şimdi Sayın Başkanım biz baz kayıtlarına yönelik, özellikle bilirkişi raporuna yönelik itirazlarımızı hani saklı tutmak kaydıyla. Evet. Söyleyecek ama varsayalım ki baz kayıtları doğru. Şimdi sizin söylemiş olduğunuz beyana göre siz cesedi aldınız, gittiniz arabaya koydunuz. Çok özür diliyorum ceset dediğim için. Narin'in cansız bedenini aldın, aldınız gittiniz arabaya koydunuz. Arkanıza baktığınızda Yüksel Güran'ı gördüğünüzü söylüyorsunuz. Ama baz kayıtlarında yani gerçekten doğruysa o saatlerde o tarihte Yüksel Güran evinde görülüyor. Yani tepede görme durumu nasıl gerçekleşiyor peki?

Nevzat Bahtiyar : Ben onu orada gördüm. Sadece orada gördüm. Yani evin içinde görmedim.

Av. Furkan Çakır : Yani tepede bizzat gördüğünüzü hatırlıyorsunuz. Ama baz kayıtlarıyla çelişiyor bu. Peki. Pekala. Şimdi Sayın Başkanım harici bir soru olacak ama bizim dikkat ettiğimiz hususlardan bir tanesi de şu. Oğlunuz İbrahim Bahtiyar ve kardeşiniz bazı beyanlarında "Güran'lardan uzak durun" şeklinde bir ifadesi var. Ama siz çoğu ifadenizde Güran'lar bizim dostumuzdur, Salim Güran benim otuz yıllık dostumdur diyorsunuz. Böyle bir ifadede bulundunuz mu?

Nevzat Bahtiyar : Yok.

Av. Furkan Çakır : Bulunmadınız. Peki son sorum bu arada. Sizin yakalanma anınız ve yakalanma şeklinizi bize anlatabilir misiniz? Nasıl yakalandınız? Nerede yakalandınız? Ve yakalanma şeklini verin. Tarihsel şekilde. Nerede?

Nevzat Bahtiyar : Eee evin içindeydi.

Av. Furkan Çakır : Kimin evindeydiniz?

Nevzat Bahtiyar : Oğlumun evindeydim.

Av. Furkan Çakır : Oğlunuz?

Nevzat Bahtiyar : Onun evinin, odanın içindeydim.

Av. Furkan Çakır : Kaç gibiydi, hatırlıyor musunuz?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Furkan Çakır : Peki siz, örnek veriyorum, kolluk geldi. Jandarma personelleri geldi. Jandarma personelleri kapıyı çalıp mı girdi yoksa bir zaten sesli bir durum mu duydunuz?

Nevzat Bahtiyar : Kapı yanlış anlatsam açıktı yani.

Av. Furkan Çakır : Açıktı, direkt jandarma personelleri içeri girdi?

Nevzat Bahtiyar : Zaten aşağıdan nasıl geldikleri, tamam. Jandarma olduğunu zaten biliyordum.

Av. Furkan Çakır : Tamam siz jandarma personeli gördüğünüz zaman tepkiniz nasıl oldu? Ya da direkt jandarma personelinin karşısına mı çıktınız yoksa saklanma gereği duydunuz mu?

Nevzat Bahtiyar : Odanın içinde oturmuştum. Oğlumu aldılar. Bugün de dedi, babam da dedi, sen de gel. Dedi sen kimsin, ben de Nevzat dedim. Beni yukarıya götürdüler.

Av. Furkan Çakır : Peki son devamlı bir sorum olacak. Siz o vakte kadar itirafçı olmayı ya da anlatmış olduğunuz durumu tahayyül etmiş olduğunuz durumu bizce. Söylemeyi düşündünüz mü? Yoksa jandarmayı gördükten sonra mı buna karar verdiniz?

Nevzat Bahtiyar : Jandarma gördükten sonra.

Av. Furkan Çakır : Direkt jandarmayı gördüğünüzde mi buna karar verdiniz?

Nevzat Bahtiyar : Evet.

Av. Furkan Çakır : Tamam teşekkür ederim.

### Av. Doğuş Can Kurucu

Av. Doğuş Can Kurucu : Nevzat Bey, benim de size bir sorum var. Salim Bey'le Arif Bey'in evinin karşılıklı olduğunu biliyorsunuz.

Mahkeme Başkanı : Mikrofonu alalım avukat bey. Diğer mikrofonu da alırsanız herkes duyar. Hıh.

Av. Doğuş Can Kurucu : Salim Bey'le Arif Bey'in evinin karşılıklı olduğunu söylediniz. Ya zaten bu dosya içinde belli. Salim Bey saat 14:33'te PTS kaydında da net bir şekilde görüleceği üzere evine çocuklarla birlikte geliyor. Evinin Arif Bey'in eviyle karşılıklı olmasından dolayı Salim Bey'in iddia edildiği üzere Yüksel Güran'la ilişkiye girdikten sonra Narin'i katledip size vermesi aklınıza mantığınıza sığıyor mu? Hiç bunu kendi içinizde sorguladınız mı? Garip karşılamadınız mı? Peki size garip gelmiyor mu? Hiç sorgulamadınız mı? Başka sorumuz yok başkanım.

Mahkeme Başkanı : "Hiç sorgulamadım, garip gelmiyor" dedi. Tamam. Onu söylüyorum ki zabıta düzgün geçsin.

## Salim Güran müdafi

### Av. Onur Akdağ

Av. Onur Akdağ : Narin'i en son ne zaman canlı gördünüz?

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Onur Akdağ : Yani olay günü canlı görmediniz mi

Nevzat Bahtiyar : Hatırlamıyorum.

Av. Onur Akdağ : Olay öncesi hiç canlı gördünüz mü?

Nevzat Bahtiyar : Bilmiyorum yani eğer evde olmuş olsam yani belki görmüş olabilirim yani bilmiyorum.

Av. Onur Akdağ : Salim'in evinde para meselesi yüzünden toplandınız mı?

Nevzat Bahtiyar : Nasıl?

Av. Onur Akdağ : Salim'in evinde mi para meselesi yüzünden toplandınız?

Nevzat Bahtiyar : Evet.

Av. Onur Akdağ : Toplantı orada gerçekleşti değil mi?

Nevzat Bahtiyar : Evet.

Av. Onur Akdağ : Ne zaman toplandınız peki? Çalıntı araç meselesi yüzünden son taksiti ne zaman ödediniz? Çalıntı araç meselesi yüzünden araç meselesi yüzünden iade edilen araç var ya dava açtığı en son sahibi. Bu, bu mesele yüzünden bir para gönderildi. Son 10.000 TL'yi o son taksidi Arif'e ne zaman ödediniz?

Nevzat Bahtiyar : Hatırlamıyorum ben.

Av. Onur Akdağ : Yani yakın zamanda mı? Çocuk öldürüldükten çok yakın zamanda mı yoksa aylar öncesinde mi?

Nevzat Bahtiyar : Hatırlamıyorum ben.

Av. Onur Akdağ : Para meselesi, ne zaman toplantı oldu?

Av. Onur Akdağ : Yani 2024 yılı içerisinde mi? Yaz mıydı, kış mıydı, ilkbahar mıydı? Ne zaman?

Nevzat Bahtiyar : 2024 yüzyılda. Yaz mıydı? Yani o yaz olduğunu ben yani hatırlamıyorum ya. Yaz, yaz mıydı yani?

Av. Onur Akdağ : Olay esnasında, olay anında hiç Arif, Arif'i düşündünüz mü? Yani Arif aklınıza hiç geldi mi? Ben bunun çocuğunu taşıyorum, ben bunun vebalini alamam.

Nevzat Bahtiyar : Yok. Hiç düşünmedim.

Av. Onur Akdağ : Olay esnasında Arif'e hiç kızgın mıydınız?

Nevzat Bahtiyar : Yok. Kızgın değildim yani.

Mahkeme Başkanı : Yani paranı geri alacağım dediğinde sen Arif'e güvendin mi? Ya alabilirim bu paramı.

Nevzat Bahtiyar : Güvendim yani. O halde hanımıyla birlikteydi.

Mahkeme Başkanı : Ha yani inandın yani.

Nevzat Bahtiyar : Eğer alsak paranı verir, almasak zaten sen paranı vermişsin.

Mahkeme Başkanı : Sen de buna inandın. Peki.

Av. Onur Akdağ : Peki, Salim senden battaniyeyi istedi. Bunu tuhaf karşılamadın mı? Yani çocuk, Salim sana çocuğu vermiş, tüm cesedi vermiş. Gelip battaniyenin peşine mi düştü?

Nevzat Bahtiyar : Bilmiyorum.

Av. Onur Akdağ : Çocuğun bulunduğu yere Eğertutmaz deresine daha önce daha sonra hiç uğradın mı, gittin mi?

Nevzat Bahtiyar : Yok hiç gitmedim.

Av. Onur Akdağ : Hiç gitmedin mi?

Nevzat Bahtiyar : Hiç gitmedim.

Av. Onur Akdağ : Yer gösterme içinde mi gitmedin?

Nevzat Bahtiyar : Hiç. Yani yer göstermesi için şeyle jandarmayla birlikte. En son gittim.

Av. Onur Akdağ : Sonra, yani olaydan sonraki günlerin gecesi gecelerinde neden kendi evinizde uyumadınız da, Çarıklı'daki oğlunuzun evinde uyudunuz? Yani bir gözaltına alınma korkunuz mu vardı?

Nevzat Bahtiyar : Ben orada hiç yatmadım. Hep köydeydim. O ilk gün zaten yakalandığım gün zaten yollar kapalıdır. Giriş çıkış kapalıdır bize dediler. Ben ondan dolayı ben şeye geldim, Çarıklı'ya eve geldim. Yoksa köye giderdim. Köye gitsem orada yakalanırdım zaten.

Av. Onur Akdağ : Efendim olaydan önce Salim ile aranız nasıldı?

Nevzat Bahtiyar : İyiydi.

Av. Onur Akdağ : Peki neden Salim sizi yaklaşık iki ay, üç ay boyunca telefondan aramadı?

Nevzat Bahtiyar : Bilmiyorum.

Av. Onur Akdağ : Siz aradınız mı?

Nevzat Bahtiyar : Aramış olabilirim.

Av. Onur Akdağ : Hiç kahveye, okeye, okey oynamaya falan gittiniz mi? Yani bir yakınlaşmanız, bir arkadaşlığınız bab'ında hiç buluştunuz mu köyde?

Nevzat Bahtiyar : Yani ara sıra okey kahveye gidiyordu, okey oynamaya gidiyordu.

Av. Onur Akdağ : En son ne zaman gittiniz?

Nevzat Bahtiyar : Hatırlamıyorum.

Mahkeme Başkanı : Yani oradaki manâ bu olaydan sonra okey oynamaya gittiniz mi?

Av. Onur Akdağ : Hayır, hayır hayır. Olay, olaydan son üç ayda.

Mahkeme Başkanı : Tamam onu anladım bir de bu olaydan sonra buluştunuz mu hiç kahvehanede?

Nevzat Bahtiyar : Yok.

Mahkeme Başkanı : Tamam.

Av. Onur Akdağ : Yani siz para meselesi yüzünden Salim ile aranızın bozulduğunu düşünmüyor musunuz?

Nevzat Bahtiyar : Yok. Konuşuyorduk.

Av. Onur Akdağ : Cemaat toplandığı zaman Salim size bir teklifte bulundu mu? bu sıva meselesi yüzünden?

Nevzat Bahtiyar : Teklifi, yani evi vardı. Evet. Kardeşinin evi vardı. Yani biz anlaşmadık. Aramızda yani para konusunda anlaşmadık. Ben yapmadım.

Av. Onur Akdağ : Yani ondan sonra Salim ve kardeşinin yaptıracağı ev bununla ilgili sıva işini size vermedi mi?

Nevzat Bahtiyar : Sıva, sıvayı bana vermedi.

Av. Onur Akdağ : Yani siz sıva ile ilgili hiç konuşmadınız mı? Sıvada bir fiyat biçtiniz. Ondan sonra, çok yüksek bir fiyat biçtikten sonra.

Nevzat Bahtiyar : 150 bin lira fiyat vermiştim.

Av. Onur Akdağ : Hah sıva meselesi yüzünden konuştunuz yani değil mi? Bu araç meselesi yüzünden mi oldu yani?

Nevzat Bahtiyar : Yok. Yani araç meselesi konusunda değildi yani. dedim istersen Salim'e bir söyleyin. Yani isterse ben yine de yaparım. Para konusunda yani mesele değildi ben dedim. Ben o kelimeyi de kullandım.

Av. Onur Akdağ : Peki olay günü 15:08'de su meselesi yüzünden Salim'i aradığınızda Salim'in nerede olduğunu hiç sordunuz mu?

Nevzat Bahtiyar : Yok hiç sormadım.

Av. Onur Akdağ : Salim'in ne yaptığını hiç sordunuz mu?

Nevzat Bahtiyar : Yok yok.

Av. Onur Akdağ : Eşiniz Gazal Bahtiyar ifadesinde Salim'in o sırada yemek yediğini yemekten sonra su işine bakacağını söyledi.

Nevzat Bahtiyar : Bilmiyorum.

Av. Onur Akdağ : Sizin suyunuzun şebekesiyle annenizin suyunun şebekesi bir mi ayrı mı?

Nevzat Bahtiyar : Birdir. Birdir. Ama onlarınki aşağıda olduğu için onlarınki geliyor, bizimki gelmiyor.

Av. Onur Akdağ : Sizin suyunuzun şebekesiyle köyün suyunun şebekesi bir midir? Ayrı mıdır?

Nevzat Bahtiyar : Birdir.

Av. Onur Akdağ : Şimdi o gün kimsenin suyu kesik değildi. Neden sizin suyunuz kesikti? Neden su için Salim'i aradınız?

Nevzat Bahtiyar : Suyumuz gelmiyordu zaten. Ben onun için zaten ben aradım. Yani, yani gelsinler şebeke personeli gelsinler bir baksınlar. Yani bu neyinden de tıkanmış mı artık? Niçin gelmiyor? Ondan dolayı ben onu aradım.

Av. Onur Akdağ : Şimdi Salim'den neden korkuyorsunuz? Yani Salim'i daha önce herhangi bir suç işlerken gördünüz mü? Birini döverken, birine mukavemet gösterirken, tahakküm ederken ya da sizi hiç tehdit etti mi?

Nevzat Bahtiyar : Ben o konuda konuşmak istemiyorum.

Av. Onur Akdağ : Konuşmak istemiyorsun. Sizin aileniz ve Gazal Bahtiyar'ın ailesi geniş bir aile midir? Yani sizin aileniz Çarıklı'daki aileniz geniş bir aile mi yoksa küçük çekirdek bir aile mi?

Nevzat Bahtiyar : Normal yani. Sekiz kardeşiz.

Av. Onur Akdağ : Sekiz kardeşsiniz. Hepsi de yetişkin değil mi? Evet. Peki Gazal Bahtiyar'ın ailesi nerede yaşıyor? Abileri, korucu olan abileri? Onlar geniş midir peki?

Nevzat Bahtiyar : Geniş ailesi.

Av. Onur Akdağ : Geniş ailesi. Yani başınız dara düştüğünde, sizi biri tehdit ettiğinde, size birisi yapmak istemediğiniz bir şeyi yaptırmak istediğinde kardeşleriniz imdadınıza yetişmez mi? Ya da Gazal Bahtiyar'ın ailesi imdadınıza yetişmez mi?

Nevzat Bahtiyar : Kardeşlerim yetişir ama benim kayınçolarım, sanmam.

Av. Onur Akdağ : Kardeşleriniz nasıl yetişir?

Nevzat Bahtiyar : Bir kardeşleri gelir, amcaları gelir.

Mahkeme Başkanı : Kimin kardeşleri gelir?

Nevzat Bahtiyar : Yani benim başım bir yani şehir geçse yani kardeşlerim gelir.

Mahkeme Başkanı : Ha, kardeşleriniz gelir, ha?

Nevzat Bahtiyar : Tamam. amcam gelir. Yani başka kim gelir.

Av. Onur Akdağ : Tamam. Tekrar teyit etmek için soruyorum. Siz köyde kaç yıldır bulunuyorsunuz ailecek?

Nevzat Bahtiyar : Boş olmazsan 50, 56, 56.

Mahkeme Başkanı : Doğduğundan beri dedi ya.

Av. Onur Akdağ : 2 saat, 2 saat önce sanki böyle köyde sığıntı gibi yaşıyormuşsunuz gibi söylediniz de.

Mahkeme Başkanı : Yok yok, doğduğundan beri dedi.

Av. Onur Akdağ : Sığıntı yaşamıyor musunuz?

Nevzat Bahtiyar : Sığıntı yaşamıyordum, yani.

Av. Onur Akdağ : Peki bir şey sorayım. Güran ailesi mi daha kalabalık yoksa Kaya ailesi mi kalabalık?

Nevzat Bahtiyar : Ben onu bilmiyorum.

Av. Onur Akdağ : Güran ailesinin üyeleri mi daha fazla yoksa Kaya ailesi? şimdi siz olay günü birinden 5000 lira aldığınızı söylediniz borç olarak. Kimden aldınız o parayı?

Nevzat Bahtiyar : Kardeşim Mehmet'ten almıştım. Yani onu.

Av. Onur Akdağ : Mehmet'in eşinden aldığınızı söylediniz.

Nevzat Bahtiyar : Evet.

Av. Onur Akdağ : Mehmet'in eşinin ismi ne?

Nevzat Bahtiyar : Ayşe Batu. Ben ondan aldım yani, o şey parasını verdim. Elektrikçi parasını verdim.

Av. Onur Akdağ : Niye mesela köyden başka birinden almadınız da, Ayşe'den almaya ihtiyacınız var mı?

Nevzat Bahtiyar : Yok.

Av. Onur Akdağ : Şeyma Kaya'yla aranızda bir gönül ilişkisi var mı?

Nevzat Bahtiyar : Yok.

Av. Onur Akdağ : Daha önce birini boğmak istediniz mi? Daha önce birini boğmaya çalıştınız mı?

Nevzat Bahtiyar : Yok.

Av. Onur Akdağ : Bunu savunmamda söyleyeceğim. 4-5 sene önceki bir mesele yüzünden söyleyeceğim. Yine yine hatırlayın isterseniz. Tanıklarımızla da bunu şey yapacağız yani.

Nevzat Bahtiyar : Yok.

Av. Onur Akdağ : Peki Nevzat Bey, sık sık ifade değiştirmenizde herhangi bir kamu görevlisinin, JASAT ekibinin ya da eşiniz Gazal Bahtiyar'ın size bir telkini oldu mu?

Nevzat Bahtiyar : Yok.

Av. Onur Akdağ : Yani zaten söylemeniz gereken şeyi söylemişsiniz. Salim'den korktuğunuzu Salim'in öldürdüğünü söylemişsiniz. Neden yani ifadelerinizdeki bazı süslemeleri değiştirdiniz? Bazı ayrıntıları güzelleştirdiniz?

Nevzat Bahtiyar : O zaman ben korkuyordum. Hı hı.

Av. Onur Akdağ : Gazal seni çocuğu ahırına ya da evine götürdüğünde seni görmüş olabilir mi?

Nevzat Bahtiyar : Yok.

Av. Onur Akdağ : Gazal'a bu olayı gözaltına alınmadan önce anlattın mı?

Nevzat Bahtiyar : Hiç kimse, hiç kimse, yok.

Av. Onur Akdağ : Efendim teşekkür ediyorum.

Mahkeme Başkanı : Ben teşekkür ederim avukat bey. sanık Nevzat Müdafi'nin bu aşamada savunma ekleyecek herhangi bir hususu var mıdır avukat hanım? Bu aşamada savunma ekleyecek bir hususu yoktur. Mütalaadan sonra ayrıntılı savunmada bulunacaksınız.
