---
title: "Gazal Bahtiyar İfadesi"
editor: source
---

## Mahkeme Başkanı

Mahkeme Başkanı : Gazal Hanım, buyurun. Avukatlara haber verin. Haber verin. Gazal orada. Salim orada. Enes orada. Enes nerede? Başlıyoruz Gazal Hanım. Öncelikle Nevzat sizin eşiniz oluyor, doğru mu?

Gazal Bahtiyar : Evet.

Mahkeme Başkanı : Ceza muhakemeleri kanununa göre tanıklık yapmama hakkına sahipsiniz. O sizin eşiniz. Dolayısıyla öncelikle bu hakkı soruyorum. Tanıklık yapmak istiyor musunuz? Yok, siz söyleyemezsiniz de. Şahitlik yapmak ister misin? Ama kanunen, Nevzat senin eşin ya, Nevzat'ın da suçunu ortaya çıkaracak sorular sorabiliriz. Bu nedenden dolayı şahitlik yapmama hakkına sahipsin. Sen, biz şahitlik yapmak istemiyorum dersen, biz de sana bu saygıyı gösteririz. Şahitlik yapmak ister misin? Yani tanıklık. Şahitlik yapmak ister misin? Evet, o zaman şöyle yapıyoruz. Kürtçe çeviren bir... Evet, avukat hanım. Sizin herhangi bir katılan sıfatınız yok. Diyarbakır Barosu avukatısınız ancak, dosyaya müdahil değilsiniz.

Avukat Hanım : Müdahillik talebi kabul edilmedi. Vardır her işte bir hikmet.

Mahkeme Başkanı : Demek ki bu yüzden kabul etmemişiz. Niye müdahillik talebinde bulundunuz? Olmaz, şimdi reddettim ya. Adliyenin, polis arkadaşlarından Kürtçe çeviren bir arkadaş. Buyurun. Şimdi, sizi müdahilliği reddet... Neyse. Polis arkadaşın, bir Kürtçe konuşun. Aynı Kürtçe lehçesiyle iletişim kurabiliyor musunuz? Onu bir deneyin. Eğer olursa, oradan devam edelim. Bir konuş, bir şeyler sor. Nasılmış, iyi miymiş, keyfi nasılmış? O zaman, tanıklık yapacak. Evet, Gazal hanım Kürtçe dilinde kendini daha iyi ifade edebileceği için, huzurda bulunan bir polis memuru mahkememizce tercüman olarak atanmıştır. Adını soyadınız?

Tercüman : Hacı Ahmet Sardoğan.

Mahkeme Başkanı : Gazal Hanım'ı tanıyor musunuz? Tanımıyorsunuz. Tanımıyorsunuz. Siz doğru söyleyeceğinize namusunuzla vicdanın üzerine yemin edip yemin eder mısınız?

Tercüman : Yemin ederim.

Mahkeme Başkanı : Evet Gazal Hanım tanıklık yapacağınızı söylediniz. Ancak sanığın eşi olduğunuz için yeminsiz bir şekilde sizi dinliyoruz. Şimdi bu Narin'in kaybolduğu gün Yüksel hanım sizin evinize geldi mi?

Gazal Bahtiyar : Yok. Gelmedi.

Mahkeme Başkanı : Hiç gelmedi?

Gazal Bahtiyar : Hiç gelmedi.

Mahkeme Başkanı : Yüksel Hanım'ı o gün hiç görmediniz?

Gazal Bahtiyar : O gün saat akşam 7'de gördüm.

Mahkeme Başkanı : Tamam. O gün akşam saat 7'de geldi. Ne dedi?

Gazal Bahtiyar : Yok bize gelmedi. Ha. Gördüm onu.

Mahkeme Başkanı : Gördün. He. Nerede gördün?

Gazal Bahtiyar : Zaten Narin'in kaybolduğu gün benim eşim Türkçe biraz biliyorum ha.

Mahkeme Başkanı : Tamam. Yarı Türkçe, yarı Kürtçe. Sen önemli olan senin kendini ifade edebilmen. Hangi dilde konuşmak istersen sana konuş. Bize ifade etmen yeterli.

Gazal Bahtiyar : Tamam. Narin'in kaybolduğu gün benim eşim Çarıklı'da benim oğlumun evinin elektriğini yapıyordu. Bir ustayla beraber. Ondan sonra orada ikiydi, iki buçuktu. Neydi? Yani ben bilmiyorum. O hava sıcaktı. Eve geldi, dedi ben acıkmışım, yemek hazırla. Ben ona yemek hazırladım. O da gitti namazını kıldı. Geldi beraber yemek yedik. Sonra dedi bizim şebeke suyumuz geliyor mu? Gelmiyor mu dedi. Ben de dedim ona su gelmiyor. Bir Salim'i arayayım. Salim de muhtardır.

Mahkeme Başkanı : Tamam.

Gazal Bahtiyar : Bir arayayım suyu yani yapsın. Salimi aradı, benim yanımda aradı. İkimiz beraberdik. Kızımla gelinim de komşudaydı. Sabri Kaçan'ın evindeydi. Sonra konuştu.

Mahkeme Başkanı : Evde kim vardı senin dışında?

Gazal Bahtiyar :  Benle oydu.

Mahkeme Başkanı : İki kişiydiniz.

Gazal Bahtiyar :  He.

Mahkeme Başkanı : Kaynananız neredeydi?

Gazal Bahtiyar :  Kaynanam evdeydi.

Mahkeme Başkanı : Evdeydi.

Gazal Bahtiyar :  He.

Mahkeme Başkanı : Siz neredeydiniz?

Gazal Bahtiyar :  Biz de evdeydik.

Mahkeme Başkanı : E o zaman.

Gazal Bahtiyar :  Kaynanam ayrıdır. Evi ayrıdır ha.

Mahkeme Başkanı : Tamam evi ayrıdır da sizin evde değildi?

Gazal Bahtiyar : Yok, kaynanam bizim evde değil.

Mahkeme Başkanı : Tamam.

Gazal Bahtiyar : He. He. O zaman biz beraber yemek yiyorduk. O dedi suyumuz gelmiyor? Ben de dedim gelmiyor. Dedi bir Salim kardeşimi arayayım? Bizim suyumuzu yapsın. Aradı. Salim de dedi, o dedi suyumuz gelmiyor Salim. Bu nasıl? DİSKİ DİSKİ. DİSKİ'yi ara, bizim suyumuzu yapsın. O sonra Salim de dedi, tamam arayacağım. O kapattı. Yani bir dakika konuşmadı. Ondan sonra eşim dedi, benim kaynanamın evinden su çekti. Dedi ben çekeceğim bu ağaçları sulayacağım. Avlumuzda ağaç vardı. Ağaçları sulayacağım dedi. Ben de içerideydim.

Mahkeme Başkanı : Dışarıya çıktı?

Gazal Bahtiyar : He? He dışarıya çıktı, ağaç sulamaya çıktı.

Mahkeme Başkanı : Hangi ağaçları suladı? Şimdi burada biz bunu bayağı tartıştık. Patlıcanlar mı? Yok yok, ağaç meyve ağacı.

Gazal Bahtiyar : Meyve ağacını sulamaya çıktı.

Mahkeme Başkanı : Sen bu sırada onu dışarıda ağaçları sularken gördün mü?

Gazal Bahtiyar : Ben içerideyim. Tamam.

Mahkeme Başkanı : İçerideydin. Pencereden ya da şeyden gördün mü?

Gazal Bahtiyar : Yok. Görmedim. Dedi sulamaya gidiyorum. O zaman ben de içerideydim. Bilmiyorum ne kadar geçti, dedi ben Çarıklı'ya gideceğim.

Mahkeme Başkanı : Gazal Hanım kendinizi suçlayıcı, suçunuzu ortaya çıkaracak sorulara cevap vermeme hakkına sahipsiniz. Ben de bu hususu hatırlatacağım. Onu da avukatlarımızdan sıcak soru sorarken unutursam lütfen müdahale edin. Tanığımızın hakkını şey olmazdı tamam. O gün köyün erkeklerinin köyün dışında olduğunu biliyor muydun sen?

Gazal Bahtiyar :  Nasıl yani?

Mahkeme Başkanı : Köyün erkekleri başka yerlere davetiye dağıtmış Güran ailesinin erkekleri. Davetiye dağıtmaya çıkmış ya. Sen bunu biliyor muydun?

Gazal Bahtiyar : Bilmiyordum.

Mahkeme Başkanı : Batman'a gittiğini ya da Diyarbakır Merkez'e gittiğini, alışveriş yapacağını biliyor muydun? Eşin biliyor muydu? Yani eşine söyledin mi böyle bir şey?

Gazal Bahtiyar : Bilmiyorum.

Mahkeme Başkanı : Kaynananla aranızda bu şekilde bir konuşma gerçekleşti mi? Yok, bilmiyordunuz. Tamam. Sonra eşiniz dışarıya çıktı. Siz eşiniz dışarıya çıktıktan sonra eşinizle bir daha ne zaman diyalog kurdunuz? Ne zaman konuştunuz?

Gazal Bahtiyar : Dedi ben bilmiyorum, yirmi dakikaydı, ne kadardı? Yarım saatti neydi geçti. Sonra dedi, ben Çarıklı'ya gideceğim. Benim biraz işim var. Ben yani oğlumun evine hani elektrik çekiyordu.

Mahkeme Başkanı : Tamam ne kadar zaman sonra?

Gazal Bahtiyar : Yarım saatti, yirmi dakikaydı, bilmiyorum. Yani o kadar yani.

Mahkeme Başkanı : Şimdi bak yani bu süre Gazal Hanım biz burada bir dakikanın tartışmasını yapıyoruz.

Gazal Bahtiyar : Süreyi hatırlamıyorsun.

Mahkeme Başkanı : Süre önemli yani bizim için bu bir dakika.

Gazal Bahtiyar : Dedi ben gidiyorum. O yani ben şey balkona çıktım. O arabaya bindi gitti. Gitti. He.

Mahkeme Başkanı : Sen balkona çıktın?

Gazal Bahtiyar : He. Yani baktım o arabaya bindi gitti.

Mahkeme Başkanı : O arabaya bindi. Yani Nevzat'ın arabaya bindiğini kırmızı arabaya bindiğini gördün?

Gazal Bahtiyar : Gördüm. Yani bindiğini gördüm gitti.

Mahkeme Başkanı : Bindiğini gördün gitti. O arabaya bindiğinde etrafta başka birileri var mıydı?

Gazal Bahtiyar : Görmedim.

Mahkeme Başkanı : Görmedim. Salimi gördün mü? Görmedim. Bu soruya cevap vermeme hakkın var. Tamam mı? Şimdi Nevzat diyor ki ben Salim'i aradım. Salim'i aradıktan sonra işte orada sularken yaklaşık on on beş dakika sonra Salim bana geldi bir işim var dedi. Ben Salim'in yanına gittim. Daha sonra Salim beni Arif'in evine çağırdı. Arif'in evinde Narin'in cesedini gördüm. Daha sonra onu alıp battaniyeyle götürdüm, ahıra koydum. Ahırda bir çuval aldım. Akabinde götürdüm. Arabaya koydum. Bu sırada da battaniyeyi Salim'e verdim. Diyor. Sen arabayla giderken gittik dedin ya.

Gazal Bahtiyar : He.

Mahkeme Başkanı : Bu dikkat çeken çuvaldan ya da ahırdan arabaya nereden bindiğini görmedin?

Gazal Bahtiyar : Aynı kapının da arabaya bindi.

Mahkeme Başkanı : Arabaya bindi. Arabanın arka kapısını falan açıp bir şey koydu mu?

Gazal Bahtiyar : Görmedim.

Mahkeme Başkanı : Görmedin.

Gazal Bahtiyar : Görmedim.

Mahkeme Başkanı : Orada arabaya gittikten sonra olay yerinde battaniyeyi gördün mü?

Gazal Bahtiyar : Yok. Görmedim.

Mahkeme Başkanı : Battaniyeyi de görmedin? Şimdi bunlar tekrardan kaçmasın. Ben özellikle soruyorum. Sizler de soru sorarken tekrar olmasın yani. Herhangi bir battaniyeyi görmedin.

Gazal Bahtiyar : Görmedim.

Mahkeme Başkanı : Peki ondan sonra sizin o arabanın olduğu yere başka bir arabanın geldiğini gördün mü?

Gazal Bahtiyar : Görmedim.

Mahkeme Başkanı : Beş dakika sonra on dakika sonra.

Gazal Bahtiyar : Görmedim. Zaten o gitti, ben de içeriye girdim.

Mahkeme Başkanı : Peki başka bir araba gelseydi fark eder miydin? Yani arabanın sesinden anlar mıydın?

Gazal Bahtiyar : Yani ev yani böyle yukarıdadır.

Mahkeme Başkanı : Yani o Salim'in, Eşinizin arabayla gittiği yere başka bir araba gelse evinizden mutfakta bulaşık yıkarken, temizlik yaparken, televizyon izlerken ya da başka bir meşguliyetiniz varken o arabanın sesini anlayabilir misiniz?

Gazal Bahtiyar : Yok.

Mahkeme Başkanı : Niye yok?

Gazal Bahtiyar : Yani ses yani. Araba falan görmez. Ses gelmedi.

Mahkeme Başkanı : Görmedin? Yok yok. Ben gördün demiyorum. Başka zaman bir hafta önce evin önünden bir araba geçse patikadan anlar mısın?

Gazal Bahtiyar : Evin önünden araba geçse.

Mahkeme Başkanı : Hah.

Gazal Bahtiyar : İçeride olsa ses. Yani.

Mahkeme Başkanı : Pencere açıksa ses gelirse anlarım. Tamam.

Gazal Bahtiyar : Açılsa gelir. Kapanırsa gelmez.

Mahkeme Başkanı : Yani o zaman hiçbir araba görmediniz. Battaniye falan da görmediniz. Nevzat telefonla konuştuktan sonra çıktı. Çıktıktan sonra bir de arabaya bindiğini gördünüz. Gitti. Ondan sonra peynir almaya mı gitti? Nereye gitti?

Gazal Bahtiyar : Kız kardeşime peynir istemiştim. İki üç iki üç gün önce dedim, bize peynir yap. O dedi, o da yanımdaydı aradığım zaman. Baktım saat beşti neydi. Nevzat bize peynir getirdi. Peynir getirdiği zaman peyniri bıraktı. Kaç dakika yani bizim yanında oturdu balkonda. Sonra yine gitti, dedi Ferhat işten gelir. Ben Çarıklı'dan onu alıp eve geleceğim. O Ferhat'ı almaya gitti. Ondan sonra ben de dama çıktım. O yani dama çıktığım zaman saat yediydi.

Mahkeme Başkanı : O bayağı geçmişti.

Gazal Bahtiyar : He ben. Dama çıkarken yediydi. Yatak sermeyene gittim. Kaynanam da damdaydı. Baktım Yüksel Güran. Enes Güran, Hediye Güran. Yukarıda bağırırken aşağıya doğru geldi. Yani dedi Narin kaybolmuş. Narinim kaybolmuş, Narin yok. Narin, yani böyle dedi. Ben de dedim Yüksel. Komşularına sor önce. Önce eltilerine sor. Yani sormak belki onların evindedir. Yüksel de dedi. Benim Narin'im gitti, kayboldu, gitti dedi. Bağırarak köyün içine girdi. Biz de onunla beraber kızı aramaya gittik caminin yanına.

Mahkeme Başkanı : Narin'i öldürdüler dedi mi?

Gazal Bahtiyar : Dedi kaçırdılar mı? Öldürdüler. Böyle yani kendini vuruyordu ya.

Mahkeme Başkanı : Bak. bir dakika, bir dakika, bir dakika. Söyleyeceksin size de tanıklar için size de söz hakkı vereceğim. Bu sefer ilk söz hakkı size ait zaten. Öyle değil. Yani benim ondan sonra kızımı kaçırdılar mı? Hani böyle dert yanmak dizini vurmak mı? Benim kızımı öldürdüler diye söylemek mi? Çünkü daha saat yedi. Narin'in ölüp ölmediği belli değil.

Gazal Bahtiyar : O öyle dedi. Benim kızımı öldürdüler mi? Kaçırdılar mı? Benim kızım yoktur.

Mahkeme Başkanı : Ha ikisini birlikte söyledi.

Gazal Bahtiyar : Bağırdı, aşağıya doğru geldi. Onunla birlikte Enes'ti ve Hediye Güran'dı.

Mahkeme Başkanı : Daha önce demişsiniz ki, dizine vurarak hanginiz kızımı götürdüyse getirsin, bir köşeye bıraksın, mezar olsun.

Gazal Bahtiyar : Öyle de dedi.

Mahkeme Başkanı : Onu da dedi? Peki bu olaydan sonra köyde herkes Narin'i arıyor. Narin'i tartışıyorsunuz. Eşinizin hal ve hareketleri nasıldı?

Gazal Bahtiyar : Her zamanki haliydi.

Mahkeme Başkanı : Eşinizden şüphelendiniz mi hiç?

Gazal Bahtiyar : Yok.

Mahkeme Başkanı : Hiç tedirgin olacak bir şey sergiledi mi?

Gazal Bahtiyar : Yok. Hiç şüphelenmez. Zaten şüphelenseydim kendi elimle teslim ederdim onu.

Mahkeme Başkanı : Yani eşinizin bu yaklaşık 25-30 gün arası hiçbir hareketi sizin dikkatinizi çekmedi?

Gazal Bahtiyar : Yani dikkatimi çekseydi, eğer şüphelenseydim..

Mahkeme Başkanı : Söylerdim.

Gazal Bahtiyar : Söylerdim, teslim ederdim. Zaten benim dayım korucudur. Mensur Kaya. Zaten benim amcam oğlu Erdal Kaya korucudur. Zaten benim amcam oğlu Hacı Kaya korucudur. Yani şüphelenseydim teslim ederdim.

Mahkeme Başkanı : Teslim ederdiniz. Peki eşinizin itiraf ettiğini biliyor musunuz?

Gazal Bahtiyar : Nasıl yani?

Mahkeme Başkanı : Daha yeni anlattım ya. Salim'in evine, Arif'in evine gittim. Salim kızı öldürmüş.

Gazal Bahtiyar : Televizyondan görüyoruz.

Mahkeme Başkanı : Ha. Eşiniz bugün de böyle dedi. Dedi ki, Salim'in evine gittim. Salim'in evine gittiğimde ceset oradaydı. Aldım götürdüm. Özetliyorum, teferruatlı değil. Dereye attım dedi. Arif'in evinden Salim'den aldı. Evet. Yani bu bunu söyledi bugün eşiniz. Yani siz hiç şüphelenmediniz değil mi bu sözü? Peki bu olaylardan sonra eşiniz tutuklandıktan sonra Güran ailesi tarafından size gelen oldu mu?

Gazal Bahtiyar : Bizim eve?

Mahkeme Başkanı : Evet pazarlık yapmak için?

Gazal Bahtiyar : Hani Ali Rıza'ydı nere? Ali Rıza.

Mahkeme Başkanı : Ali Rıza Güran.

Gazal Bahtiyar : Ali Rıza Güran. Bir teklifte bulundu.

Mahkeme Başkanı : Size mi bulundu? Hı hı. Sen Ali Rıza Güran'ı gördün mü hiç?

Gazal Bahtiyar : Biz köyde yaşıyorduk ha, daha önce ya.

Mahkeme Başkanı : Ya yaşlı biri mi? Ben bilemiyorum nasıl biri? Ben daha hiç görmedim.

Gazal Bahtiyar : Ya yaşlıdır, yaşlı.

Mahkeme Başkanı : Yaşlıdır da diyor.

Gazal Bahtiyar : Yaşlı biri. Yaşlıdır.

Mahkeme Başkanı : Ha. O size evinize mi geldi? Nerede bu teklifte bulundu?

Gazal Bahtiyar : Benim Hasan Kaya. Batıkarakoç'tadır. Onu aramış. Demiş, yani eğer Gazal çocuğu evladın çocukları kabul ederse, gelsin köyde kendi evinde yaşasın, her ihtiyacını gideririz. Nevzat da bu suçu üstüne alsın demiş.

Mahkeme Başkanı : Size bunu Hasan mı söyledi?

Gazal Bahtiyar : Evet.

Mahkeme Başkanı : Siz ne dediniz?

Gazal Bahtiyar : Ben de dedim asla kabul etmem. Dünyayı da versen kabul etmem. Kim ne kim kızı öldürmüşse, kim bu şeyi yapmışsa cezasını çeksin cezasını.

Mahkeme Başkanı : Peki bunun sonra eşinize kim söyledi? Yani bu tekliften eşinizin nasıl haberi oldu? Eşiniz cezaevinde ya.

Gazal Bahtiyar : Kardeşi vardı.

Mahkeme Başkanı : Hangisi?

Gazal Bahtiyar : Vecdin.

Mahkeme Başkanı : O mu söyledi eşine?

Gazal Bahtiyar : Herhalde o söylemiş.

Mahkeme Başkanı : Sen bilmiyor musun? Kim söyledi?

Gazal Bahtiyar : O o söylemiş ya. Biz beraber gidiyorduk ya onun yanına.

Mahkeme Başkanı : Tamam sen söylemedin, senin yanında o mu söyledi?

Gazal Bahtiyar : O söyledi. Yani bu adam bize böyle bir teklif yaptı. Ha. Ha biz de söyledik.

Mahkeme Başkanı : Ya birlikte, yani sen Vecdi'yle Vedat da Vedat ya da Vecdi. Vedat'la birlikte cezaevi ziyarete gittiğinizde Nevzat'a mı söylediniz bunu?

Gazal Bahtiyar :  Hı.

Mahkeme Başkanı : Birlikteydiniz. Ne zamandı bu hangi tarihte hatırlıyor musunuz?

Gazal Bahtiyar : Vallahi hatırlamıyorum.

Mahkeme Başkanı : Hatırlamıyorsun. Normal. Hatırlamaman konusunda bir sıkıntı yok. Bunu şey anlama. Biz sadece ısrarlı soruyoruz ki belki hatırlarsınız diye, tamam. Bu Salim'in üvey annesi Süveyla'yı tanıyor musunuz?

Gazal Bahtiyar : Tanıyorum.

Mahkeme Başkanı : Tanıyorsunuz. Hı. Onun sizinle bir diyaloğunuz oldu mu?

Gazal Bahtiyar : Nasıl yani?

Mahkeme Başkanı : Nasıl yani. Bu olaylar sırasında gelip size bir şeyle söyledi mi?

Gazal Bahtiyar : Söyledi.

Mahkeme Başkanı : Ne söyledi?

Gazal Bahtiyar : Söyledi. Geldi dedi, Salim tutuklandı, Nevzat da tutuklanacak.

Mahkeme Başkanı : Niye Nevzat tutuklanacakmış?

Gazal Bahtiyar : Ben de niye dedim? Dedi ha gidip ifadesini alacaklar. Öyle dedi. Sonra öyle çevirdi, öyle dedi.

Mahkeme Başkanı : Süveyla da yaşlı biri?

Gazal Bahtiyar : O da yani çok yaşlı değil.

Mahkeme Başkanı : Yani Salim tutuklanacak, Nevzat da tutuklanacak?

Gazal Bahtiyar : Yok Salim tutuklanmıştı.

Mahkeme Başkanı : Salim tutuklanmıştı, Nevzat da tutuklanacak. Bunu söylediğinde Narin'in cansız bedeni bulunmuş muydu? Daha bulunmamıştı. Sen sormadın mı? Sen hayırdır?

Gazal Bahtiyar : Evet. Ben dedim. Nevzat niye tutuklanacak? Dedim, hayrola, niye Nevzat tutuklanacak? Dedi, yok yok. Ben dedim yani onun ifadesi de alınacak. Öyle dedi.

Mahkeme Başkanı : Ha yani o zaman şey de olabilir. Yani sen burada bunu söylerken tutuklanacak, hani köyce, hani ya işte gözaltına alınacak da tutuklanacak anlamına gelerek mi söyledi? Ya ifadesi alınacak yoksa Nevzat suçlu da mı alınacak?

Gazal Bahtiyar : Bana böyle dedi. Dedi bak Salim tutuklandı, Nevzat da tutuklanacak. Ben de dedim niye Nevzat tutuklanacak? O da dedi ki, yok yok, onun ifadesini de alacak.

Mahkeme Başkanı : Sonra sen niye alınacak diye sordun mu?

Gazal Bahtiyar : Bütün köyün ifadesi alındı.

Mahkeme Başkanı : Ha bunu normal karşıladınız. Bundan şüphe uyanmadınız. Güran ailesiyle aranızda bir husumet var mıdır?

Gazal Bahtiyar : Çok iyidir.

Mahkeme Başkanı : Bu araba muhabbeti var. Bu araba muhabbeti ne?

Gazal Bahtiyar :  Araba.

Mahkeme Başkanı : Yani bu borç ödeme, ödememe.

Gazal Bahtiyar : Zaten ödedi. Elli milyar. Onlar kırk milyar, elli milyar Nevzat ödendi.

Mahkeme Başkanı : Peki Nevzat o gün Arif'le aralarında bir tartışma geçtikten sonra akşam eve geldiğinde sinirli miydi? Çünkü Nevzat'la dalga geçmişler.

Gazal Bahtiyar : Zaten bak aranız aralarında husumet olsaydı niye benim oğlum onların evinde yatacaktı?

Mahkeme Başkanı : Ne zaman?

Gazal Bahtiyar : Narin kaybolduğu, yani aynı cenazesi gün bulduğu gün benim oğlum onların evindeydi.

Mahkeme Başkanı : Niye?

Gazal Bahtiyar :  E arkadaştı, kardeş gibidirler.

Mahkeme Başkanı : Muhammed Emre'yle mi arkadaştır?

Gazal Bahtiyar : Yok. Baran'la arkadaş.

Mahkeme Başkanı : Baran'la arkadaşlar. O akşam mı onlarda kalacaktı?

Gazal Bahtiyar : E zaten jandarmalar benim oğlumu akşam dörtte onların evinden aldı. Getirdi.

Mahkeme Başkanı : Akşam dörtte. Yani sabaha geliyordu o. Sabaha karşı dörtte?

Gazal Bahtiyar : He. Beraber Çarklı'ya gittik.

Mahkeme Başkanı : Akşam dörtte mi? Akşam dört dersen?

Gazal Bahtiyar : Yok yok sabah.

Mahkeme Başkanı : He sabaha karşı dört. Çünkü akşamın dördü zaten saat mefhumu zaten var. Sabaha karşı dörtte.

Gazal Bahtiyar : Bizim bir husumetimiz, bir kavgamız, bir şeyimiz yoktu. Bu Salim'e diyordu kardeşim, o Salim'e diyordu kardeşim. Ya kardeşim. Kardeşim dedi, Salim onu sırtında vurdu.

Mahkeme Başkanı : Yani bu araba muhabbeti ne? O konuda ne biliyorsunuz?

Gazal Bahtiyar : Araba muhabbeti hani Nevzat onlardan almıştı.

Mahkeme Başkanı : Tamam.

Gazal Bahtiyar : Sonra Salim de Nevzat'tan aldı.

Mahkeme Başkanı : Tamam.

Gazal Bahtiyar : Salim de sattı. Sonra dedi araba çıktı. Yani öyle dediler. Sonra dedi adam kaza yapmış o arabayla. Bilmem böyle şeyler söylendi. Dedi bu parayı aramızda veririz. Arif de verdi. Hatırlamıyorum Arif ne kadar verdi. Salim de on milyar verdi. Nevzat da elli milyar verdi.

Mahkeme Başkanı : Nevzat bu parayı öderken ben bunun intikamını alırım. Bu elli bin liranın bir kuruşunu bile bırakmam dedi mi?

Gazal Bahtiyar : Yok.

Mahkeme Başkanı : Söke söke alırım bu parayı dedi mi?

Gazal Bahtiyar : Hiç. Hiç böyle bir şey söylemedi. Zaten o parayı da verirken kardeş gibidirler, sürekli birbirlerinin yanına gidiyorlardı.

Mahkeme Başkanı : Ha o paradan sonra da bir sıkıntı olmadı. Daha rutin hayatlarına yani normal hayatlarına devam ettiler?

Gazal Bahtiyar : Kardeş gibidirler. Vallahi o da diyordu kardeşim, o da diyordu kardeşim. Evet. Onu Kur'an'ın üstünde yemin ederim. O da kardeşim. Salim de diyordu kardeşim.

Mahkeme Başkanı : Peki Gazal Hanım, Salim Nevzat'ı kendi şahsi işleri için kullanır mıydı? Kendi şahsi işlerinden kastım; bu tarla işidir, yardım işidir değil de erkek özel işleri diye kibarca sorayım.

Gazal Bahtiyar : Hayır.

Mahkeme Başkanı : Anladın mı sen benim sorumu?

Gazal Bahtiyar : Evet.

Tercüman : Anlamış.

Mahkeme Başkanı : Yani bu çapkınlıkta, mapkınlıkta kullanır mıydı Nevzat'ı?

Gazal Bahtiyar : Benim kocam çapkın değildi.

Mahkeme Başkanı : Değildir.

Gazal Bahtiyar : Değildir.

Mahkeme Başkanı : Salim onu....

Gazal Bahtiyar : ben onunla 30 yıldır evliyim.

Tercüman : Ne üzerime tükürdü, ne bana küfür etti, ne çocuklarıma küfür etti. Bana her zaman iyi davrandı. Çevrede de her zaman iyi tanınır.

Mahkeme Başkanı : İyi tanınır. Yani şimdi yine Nevzat'ın itirafından geliyorum, tamam mı? Nevzat diyor ki; Salim bu kızı öldürdü. Benim Yüksel'le ilişkim vardı. Kız Narin bizi gördü. Dolayısıyla da ben bunu öldürdüm. Al bu cesedi sakla, yok et diye Nevzat'a veriyor. Yok yok; değilsin de o yüzden sordum sana. Nevzat Salim, Nevzat'ı kendi şahsi işleri için kullanır mıydı bu şekilde? Yani şimdi bir insan...

Gazal Bahtiyar : Bak kardeş diyordu sürekli. Yani ikimiz kardeş gibiyiz. Yani eğer ona öyle demişse de kardeşimdir diye belki sırrımı saklar diye..

Mahkeme Başkanı : Nevzat'tan sır çıkar mıydı?

Gazal Bahtiyar : Çıkmaz.

Mahkeme Başkanı : Çıkmış ama. Yani o yüzden, yani sır çıkmaz diye güvendiği için onu verdi.

Gazal Bahtiyar : Salim de onu kullandı.

Mahkeme Başkanı : Bu Diyarbakır'da mı? İstanbul'da mı bir Nevzat'ın kardeşi var. Biliyor musun sen onu? Nevzat'ın kardeşi kaç tane Nevzat'ın kardeşi var?

Gazal Bahtiyar : Sekiz kardeş.

Mahkeme Başkanı : İstanbul'dakinin adı neydi? Hatay'da Hatay'da. Ha Vedat Vecdi ya. Pardon. Tamam.

Mahkeme Başkanı : Bu Vedat'ı tanıyor musunuz?

Gazal Bahtiyar :  Benim kaynımdır.

Mahkeme Başkanı : Vedat'la bu olaylar sırasında, Narin'in kaybolması sırasında sık sık sizi arayıp şimdi Narin bulundu mu falan böyle bir muhabbetler oldu mu? Nevzat'la ya da sizinle?

Gazal Bahtiyar : Salimi aramış, Nevzat'ı aramış. Yani aramış.

Mahkeme Başkanı : Sen nereden duydun aradığını?

Gazal Bahtiyar :  Hepimiz birbirimizin yanındayız yani.

Mahkeme Başkanı : Ha yani öyle duydun?

Gazal Bahtiyar : Evet.

Mahkeme Başkanı : Yani televizyondan mı duydun yoksa köyden bizzat şahit oldun mu?

Gazal Bahtiyar : Yok yok, Vedat yani, dedi ben sormuştum ne Salim'e de sormuştum, Nevzat'a da sormuştum yani kız bulundu mu?

Mahkeme Başkanı : Ha ne yani Vedat'ın bu kadar çok aramasının sebebi kızı merak etmesi?

Gazal Bahtiyar : Bilmiyorum ne kadar aramış.

Mahkeme Başkanı : Ama bu manada aramış. Diyorsunuz öyle mi? Bu kadınlar kavgası etmişler bir kadınla. Sen var mıydın orada?

Gazal Bahtiyar : Yok.

Mahkeme Başkanı : Peki köyde yapılan dedikodularda Narin'in, yani bu Narin'in bulunma aşamasında hani köyde toplantılar yapılıyor, sohbetler yapılıyor, konuşuluyor, konuşuluyordur. Tüm Türkiye'nin konuştuğunu köyde konuşuyordur. Bu sırada Narin'i birinin öldürdüğü şeklinde kulağınıza bir şey geldi mi? Bir duydunuz mu böyle bir dedikodu, duyum? Duymadınız.

Gazal Bahtiyar : Sadece Salim tutuklandığı zaman diyordu Salim öldürmüş.

Mahkeme Başkanı : Kim dedi onu?

Gazal Bahtiyar : Köyde öyle diyorlar.

Mahkeme Başkanı : Ha Salim tutuklandı, Salim öldürmüş. Ama daha kız bulunamadı. Daha kız bulunmadan değil mi?

Mahkeme Başkanı : Evet, Yüksel Hanım seni dinliyorum. Bir mikrofon verelim. Ha Yüksel Hanım buraya gelir misiniz? Ha şu mikrofonu ver.

Yüksel Güran : O burada oturacaktı ama ben buradayım, O orada olsun. Bana diyor ki, Enes, Hediye, Yüksel yukarıya doğru evimize geldiler.

Mahkeme Başkanı : Evet.

Yüksel Güran : Ben burada hepsi şahittir. Önce Ayzakaya'ya gidiyorum. Hiçbir şey yoktu Narin'i arıyoruz. Camiye gidiyorum. Orada fırtınalarla kıyametle diyorum Narin yoktur. Sonra tekrar tepeye çıkıyorum. Hani diyor ki, İshak Kaya dedi ki, ya belki Narin yani 6'da buradaydı. Tekrar eve gidiyorum. Tekrar aşağıya indiğim zaman camide ilk aramada kendi buradadır. Arkama koşuyordu. Yüksel böyle yatma. Yüksel kendine gel. Yüksel bir gün bir gece akşama kadar ben tarlada yatmışım. Nevzat geldi, beni tarlada gördü. Arkamda koşuyor. Narin dere kenarında gördüğü zaman bir gün önce karşımdadır o kadar sene ben ona abla gibi iyilik yaptım. Evime geldi yanımda oturuyor. Yüksel kusura bakma, senin yanına gelmedim. Jandarma bırakmıyordu. Narin kaybolduğu gün. Rüya gördüm. Tavşantepe'de yangın çıkmıştı. Sonra ben dün de rüya görmüşüm. Narin eve gelmiş. Bu şerefsiz de demiş ki; aa ya o kadar içim yanıyor ya. Dedi ki, Valla Gazal senin rüyalar enteresedir. Size Narin kayboldu zaman yangın çıkıyor. Bugün sen görsün, Narin rüyama gelmiş. İşte Narin eve gelmiş. İnşallah Narin eve gelecek. Çok rüyama. Şimdi. Doğruyu çıkıyor.

Mahkeme Başkanı : Ne sormak istiyorsunuz?

Yüksel Güran : Diyorum ki, yalan söylüyor.

Mahkeme Başkanı : Yani o gün gidip işte sen Enes saat 19 gibi Gazal'a gidip görüp benim kızım nerede? İşte böyle bir..

Yüksel Güran : O camiden arkamda koşuyor.

Mahkeme Başkanı : O onun zaten ev değildi. Arkandan koştu yüz yüz. Böyle bir şey söyledin mi?

Yüksel Güran : Arkamda bana teselli ediyordu. Yani diyor ki, önce Hediye ile birlikte evime kadar gelmiş ve Narin'i arıyor. Narin nerede? Birisi Narin kaçırmış. Biri narisini öldürüyor. Ben ondan diyorum.

Mahkeme Başkanı : Tamam onu söylediniz.

Yüksel Güran : Ha ben bilmem hala kızım kaybolmuş. Ben nerede bileceğim kızım ölmüştü.

Mahkeme Başkanı : Tamam onu söylediniz zaten. Siz ne dersiniz bu konuda?

Gazal Bahtiyar : Yüksel Güran öyle söylüyor. Bak ben saat yedide damdaydım. Yüksel Güran'la Enes, Güran'la Hediye Güran aşağıya doğru geldi. Bak şimdi sen diyorsun. Yalan söylüyor ama ben yalan söylemiyorum. Siz aşağıya doğru geldiniz. Sen bağırdın, çağırdın dedin benim kızım yoktur. Kaçırmışlar. Doğru söylüyorum Yüksel. Ferhat Bahtiyar da şahittir. Ferhat Bahtiyar da şahittir. Ferhat da bizimle beraber camiye geldi, hatta kapı kilitliydi. Ferhat pencereden girdi, bütün caminin içini kontrol etti. Dedi belki kız caminin içinde uyuyakalmıştır. Ben yalan söylemiyorum.

Yüksel Güran : Bir sürü insan ben burada herkes buradadır. Ben demiyorum ben aynı dakikaya gitmişim.

Mahkeme Başkanı : Tamam tamam.

Gazal Bahtiyar : Sen ilk önce aşağıya doğru indin. Senle Enes'ti, bir de Hediye Güran'dı. Bir de aşağıya doğru geldin. Sen söyledin. Ben de seninle caminin yanına kadar geldik. Camiyi etrafına hepsi aradık. İçini aradık. Oğlum da pencereden caminin içine girdi. Camiyi bütün camiyi kontrol etti. Dedi, belki uyuyakalmıştır. Sonra baktı, bir şey yoktur. Biz saat on buçuğa kadar onunla köyün içine yani arama ettik.

Mahkeme Başkanı : Tamam. Tamam. Başka sormak istediğiniz bir şey var mı? Yok. O tabii siz. O zaman şöyle yapalım. O mikrofon, o mikrofon olmadı. Aynen. Değiştirin. Aynen.

Salim Güran : Affedersin. Affedersin, bir itle canım kardeşim derim buna söylemem. Yalan atıyor.

Mahkeme Başkanı : Soru soru. Sorun var mı? Soru sormak istiyor musun Gazal'a?

Salim Güran : Benim kocamı sırtından vurdu? Ne şekil vurmuş böyle bir açıklama yapsın. Açıklama yapsın.

Mahkeme Başkanı : Evet.

Gazal Bahtiyar : Açıklama yapıyorum.

Salim Güran : Yap böyle.

Gazal Bahtiyar : Yapıyorum. Nasıl yapmış?

Salim Güran : Nasıl sırtında vurmuşum?

Gazal Bahtiyar : Hani ben, siz hep benim eşimin üstüne atıyorsunuz. Benim eşim sizin tavuğunuzu bile öldüremez.

Salim Güran : Bak, kamera kayıtları çıkacak zaten Allah'ın izniyle.. O kız patikadan yukarı çıkmamış.

Gazal Bahtiyar : Çıkmış. Yav testler yalan mı? Bazlar yalan mı? Senin araban yalan mı? Her şey mi yalan?

Mahkeme Başkanı : Enes gel. Sormak istediğin bir şey varsa.

Enes Güran : Gazal Hanım, hani sen diyorsun ya. Bizim eve doğru geldiniz. Biz hangi yoldan geldik?

Gazal Bahtiyar : Siz patika yollarından aşağıya doğru geldiniz.

Enes Güran : Hangi patika?

Gazal Bahtiyar : He, aşağıya doğru geldin.

Enes Güran : Ben de, tamam, bak sana ben bunu inkar etmiyorum. Ben aşağıya inmişim. Ama ben hangi yoldan indim?

Gazal Bahtiyar : O patika yolundan.

Enes Güran : Hangi patika?

Gazal Bahtiyar : He benim evin arkasından doğru aşağıya geldiniz. Geldin, sendin.

Enes Güran : Ben geldim, senin evine?

Gazal Bahtiyar : Evime gelmedin.

Enes Güran : Nereye?

Gazal Bahtiyar : Aşağıya doğru geldiniz. Biz de sizinle beraber camiye yanına gittik.

Enes Güran : Kim kimdik?

Gazal Bahtiyar : Annendi bir de Hediye Güran.

Enes Güran : Hediye Güran. Bir kere Sayın Hakim, biz tepeye çıktığımız esnada kesinlikle Hediye Güran bizimle de geldi.

Gazal Bahtiyar : Üçünüz beraberdiniz.

Enes Güran : Ben burada konuşuyorum söz sende de geldi. Ben Hakim Bey'le konuşuyorum. Hakim Bey. Ben, annem, Muhammed Güran tepeye çıktık. Maşallah Güran'a seslendik. Ve Maşallah Güran da yok deyince ben Muhammed kardeşimi alıp cami tarafına Muhammed kardeşimi ilk başı olarak Azize Güran'a.

Mahkeme Başkanı : Tamam bunları anlattın.

Enes Güran : Evet Sayın Hakim.

## Diyarbakır Barosu

### Av. Nahit Eren

Av. Nahit Eren : Saat 15:08'de Nevzat Salim'i arıyor ya su için. O görüşmeyi yaptığında evin içinde miydi?

Gazal Bahtiyar : Nevzat telefon konuştuğu zaman?

Av. Nahit Eren : Evet.

Gazal Bahtiyar : Evet.

Av. Nahit Eren : Sen o konuşmayı duydun?

Gazal Bahtiyar : Duydum.

Av. Nahit Eren : Suyla ilgili konuştular?

Gazal Bahtiyar : Evet.

Av. Nahit Eren : Suyun arızanın giderilmesiyle.

Gazal Bahtiyar : Evet.

Av. Nahit Eren : Sen ondan sonra araçla ayrıldı, gitti diyorsun ya. Ben yukarıdan baktım. Böyün altına mezarlık yoluna doğru gittiğini gördüm diye bir ifaden var.

Gazal Bahtiyar : Var.

Av. Nahit Eren : Araçla gittiğini gördün.

Gazal Bahtiyar : Evet.

Av. Nahit Eren : Ben sana şunu soracağım. Bu konuşmadan ne kadar süre sonra aracına binip gitti? Hemen konuşmayı yaptığı gibi ben onu soracağım. Araca bindiği saatten o konuştuğu 15:08 arasına sence ne kadar? 10 dakika, 5 dakika, yarım saat. Ne kadarlık bir süre geçti?

Gazal Bahtiyar : Telefonla konuştu içeride. Sonra dışarıya çıktı. 20 dakikaydı, 15 dakikaydı, ben bilmiyorum.

Av. Nahit Eren : Yani konuştuğu gibi çıkıp gitmedi, araca gitmedi?

Gazal Bahtiyar : Yok, dedi ağaç sulamaya gidiyorum.

Av. Nahit Eren : Tamam.

Gazal Bahtiyar : O zaman gitti. Daha yani kaç dakika geçtiğini bilmiyorum. Sonra dedi ben Çarıklı'ya gideceğim.

Av. Nahit Eren : Tamam. Sen Nevzat'ın götürüp oraya Narin'i sakladığına ilişkin haberleri televizyondan gördün?

Gazal Bahtiyar : Hı hı.

Av. Nahit Eren : Öncesinde bilmiyorsun zaten?

Gazal Bahtiyar : Evet.

Av. Nahit Eren : Sonrasında Zeynep'ten sana peyniri de getirdiğini biliyorsun?

Gazal Bahtiyar : Evet.

Av. Nahit Eren : Akşam gelince peynir var?

Gazal Bahtiyar : Getirdi.

Av. Nahit Eren : Hiç sonrasında Zeynep'le bu konuyu bir konuştun mu? Yani Nevzat yakalanıp cezaevine konduktan sonra. Hani size geldi, bu olaydan sonra Zeynep bacına. Nevzat sana geldiği zaman nasıl bir haldeydi? Gitmiş ki oraya oturmuş, çay içmiş, sohbet etmişler. Ondan sonra eve gelmiş. Sen hiç Zeynep'le oturduğu gün sonra...

Gazal Bahtiyar : Zeynep zaten benim evime geliyor. Benim kardeşimdir.

Av. Nahit Eren : Bu konuyu konuştun mu hiç kendisiyle? Bak dereye götürüp saklamış, televizyona çıktı. Kendisi kabul ediyor. Geldiği zaman sana bir şey söyledi mi? Sen bir şeyden şüphelendin mi kendisinden?

Gazal Bahtiyar : Sordum. Dedi, hiç şüphelenmedim.

Av. Nahit Eren : Yani hiçbir şey olmadı?

Gazal Bahtiyar : Olmadı.

Av. Nahit Eren : Az evvel bir şey söyledim. Başkan bey sordu, teklif. Dediniz ki; teklif gelmiş. Daha doğrusu Nevzat'ın kardeşine gelmiş, kardeşi cezaevine getirdim. Siz de oradaymışsınız.

Gazal Bahtiyar : Teklif bize geldi.

Av. Nahit Eren : Evet teklif kardeş bize geldi. Biz sana mı teklif geldi?

Gazal Bahtiyar : Bize geldi.

Av. Nahit Eren : Bu teklifte Nevzat'ın suçu üstlenmesi konusunda doğrudan sana geldi. Kim geldi sana?

Gazal Bahtiyar : Hasan Kaya. Hasan Kaya dedi ha. Dedi Ali Rıza Güran bu teklifi yapmış. Demiş Gazal kabul etsin. Köye gelsin. Evinde otursun. Ben her şeyini karşılarım. Nevzat bu suçu üstüne alsın.

Av. Nahit Eren : Gittiniz cezaevinde. Vecdin'le beraber, Vedat'la birlikte kendisiyle sohbet ederken aktardı ona, kardeşi.

Gazal Bahtiyar : He.

Av. Nahit Eren : Nevzat'ın tepkisi ne oldu? Sen oradasın görüşmede. Açık görüşte konuştunuz?

Gazal Bahtiyar : He.

Av. Nahit Eren : Nevzat ne dedi?

Gazal Bahtiyar : Biz kabul etmiyoruz.

Av. Nahit Eren : Sen değil. Nevzat bu teklife ne dedi?

Gazal Bahtiyar : Söyleyecek, kabul etmiyor.

Av. Nahit Eren : Hani söyledi mi, söylemedi mi?

Gazal Bahtiyar : Hatırlamıyor.

Av. Nahit Eren : Hatırlamıyor. Tepkisi ne oldu böyle bir şeye? Sen mesela teklifi kabul etmesin diye önceden görüşünü kardeşlerine, Vecdi'ne falan söyledin mi?

Gazal Bahtiyar : Bu teklifi kabul edeyim yani?

Av. Nahit Eren : Edeyim, etmeyeyim.

Gazal Bahtiyar : Ben karşıyım.

Av. Nahit Eren : Sen bunu kardeşlerine aktardın mı? Vecdin'e söyledin mi?

Gazal Bahtiyar : Böyle bir şey dedim.

Av. Nahit Eren : Vecdin'e?

Gazal Bahtiyar : Dedim, böyle bir teklif gelmiş. Zaten ben asla kabul etmem.

Av. Nahit Eren : Sen Nevzat'ın yanında olmasaydın Nevzat'ın kabul etme ihtimali var mıydı?

Gazal Bahtiyar : Hayır.

Av. Nahit Eren : Yine de kabul etmezdi o?

Gazal Bahtiyar : Etmezdi.

Av. Nahit Eren : Başkan bey sordu. Üvey anneleri bildiğim kadarıyla Süreyya.

Gazal Bahtiyar : Süveyla.

Av. Nahit Eren : Süveyla. Biliyorsun Narin'nin kaybolduğu gün okulun kamerasına da yansıyor. Orada samanlıkta, bak orada saman torbalıyor sürekli. Sence Süveyla bir şeye tanık olduğu için mi sana Nevzat'ı daha Salim'den sonra gelip tutuklayacaklar dedi? Yoksa sen bir şey isteyebilir mi? sonrasında kaygılanmadın mı? Henüz daha Nevzat'ın oraya sakladığı bilinmiyor ama bir kadın köyünüzden bir hanımefendi geliyor.

Gazal Bahtiyar : Zaten öyle. Öyle.

Av. Nahit Eren : Sen bunu Nevzat'la paylaştın mı? Nevzat bak, Süveyla geldi. Bana dedi ki, efendim kocan da tutuklanacak. Salim'den sonra. Hiç konuşmadın mı Nevzat'la bunu? Niye bize söylüyor?

Gazal Bahtiyar : Konuşmadım.

Av. Nahit Eren : Hiç konuşmadın. Kaygılanmadın mı yani?

Gazal Bahtiyar : Yok, zaten öyle dedi. Ben de dedim, hayrola niye Nevzat tutuklanacak? Dedi yok yok, ifade herkes yani ben ifadeye gideceğim dedim. O bana öyle dedi sonra.

Av. Nahit Eren : Bir şey olursa ifadeye mi gideceğim yoksa ben ifadeye zaten gideceğim?

Gazal Bahtiyar : Yok yok. Bak Süveyla Güran bana dedi ki, Salim tutuklandı. Nevzat da tutuklanacak.

Av. Nahit Eren : Birkaç gün geçtikten sonra.

Gazal Bahtiyar : Öyle dedi. Ben de dedim, niye Salim tutuklandı? Niye Nevzat tutuklanacak? Ben dedim.

Av. Nahit Eren : Sen bir ifadende demişsinki, bu aile sır küpüdür.

Gazal Bahtiyar : Nasıl?

Av. Nahit Eren : Sır küpü. Belki sen Kürtçe mi ifade ettin? O şekilde mi yazmışlar, bilmiyorum. Sen kendi imzaladığın bir ifadeyle sır....

Mahkeme Başkanı : Kürtçe söyleyin bunu. Kürtçe de söyleyebilirsiniz avukat bey.

Av. Nahit Eren : Sır küpü kelimesi o senin söylemin mi? Niye?

Gazal Bahtiyar : Yani nasıl?

Av. Nahit Eren : Sen niye onlara diyorsun ki bunlar bir şeylerini konuşmaz kimseler?

Gazal Bahtiyar : O sır küpü ben yani söylememişim. Ben diyorum, sürekli arasına sürekli toplantı bir yapıydı ya.

Av. Nahit Eren : Öncesinde aileyle ilgili bir yorum yapıyoruz. Bu aile toparlayacağız. Kendi içlerindeki bilgileri, kendi içlerindeki konuşmaları dışarıya aktaran bir aile değil. Sır küpü odur. Yani kendi içlerinde sen bu anlama gelecek bir cümle kullanırsın. Devamında onu söylüyorsun. Diyorsun ki, ikinci günden sonra içlerine kapandılar diyorsunuz. Kimseyi yabancı kimse işlerine almadı. Buradan kastın, yani niye sen gittin? Almadılar mı?

Gazal Bahtiyar : Biz gidiyoruz. Bak iki üç gün gidiyorduk.

Av. Nahit Eren : Siz niye gidiyorsunuz?

Gazal Bahtiyar : Yani ya Yüksel'in yani. He. He. Gidiyor. Sonradan gidiyorduk. Diyordu aile toplantımız var. Kimse gelmez.

Mahkeme Başkanı : Onu ben toparlayayım. Sır küpü dediğini ancak daha sonra ailecek yapılan toplantılarda kendilerinin toplantıya alınmadığını kastetti. Doğru mu?

Gazal Bahtiyar : Evet.

Mahkeme Başkanı : Doğru. Buna itirazı olan var mı? Yok. Çünkü orada diyaloglar kopuk oldu. Zapta. Sır küpü kullanmadım dedi. Orada diyaloglar kopuk oldu. Zapta yanlış geçmesin. Tamam zaptı bu şekilde toparlarız.

## Aile ve Sosyal Hiz. Bakanlığı

### Av. Abdullah Yılmaz

Av. Abdullah Yılmaz : Başkanım biz de her şeyi konuşup zaten sadece tek bir soru soracağım.

Mahkeme Başkanı : Buyurun.

Av. Abdullah Yılmaz : Çuval ile şahsın ahırında, yani şu çuval anlatımına göre ahıra gidiyor, pencereden giriyor, çuval alıyor, cesedi koyuyor. Siz hiç şahit olmadınız mı böyle bir olaya?

Gazal Bahtiyar : Hayır.

Av. Abdullah Yılmaz : Peki o zaman evde değil miydiniz?

Gazal Bahtiyar : Evdeydim, içerideydim.

Av. Abdullah Yılmaz : E hiç duymadınız mı?

Gazal Bahtiyar : Yok.

Av. Abdullah Yılmaz : Köy evi sonuçta.

Gazal Bahtiyar : Görmedim. Görseydim zaten kendi elimle teslim ederdim. Yemin ederim.

Av. Abdullah Yılmaz : Siz cezaevine gittiniz. Bunları sormadınız mı? Sizi tehdit ettiler mi? Eşinizi tehdit ettiler mi? Bunu söylüyorsunuz zaten ama kim tehdit etti açık açık?

Gazal Bahtiyar : Nasıl yani?

Av. Abdullah Yılmaz : Yani senin kocan böyle bir suç işler mi?

Gazal Bahtiyar : Böyle suç.

Av. Abdullah Yılmaz : Böyle bir suç işler mi normalde?

Gazal Bahtiyar : Hayır.

Av. Abdullah Yılmaz : Kim tehdit etti sence?

Gazal Bahtiyar : İnanmıyorum. Eşim böyle bir suçu asla işlenmez.

Av. Abdullah Yılmaz : Niye o zaman eşini üçü birden suçluyor mesela sence? Tehdit ediliyor, ediliyor muydu?

Gazal Bahtiyar : Hani bak. Sana hiç anlatmadım.

Av. Abdullah Yılmaz : Siz hiç anlatmadınız mı?

Gazal Bahtiyar : Bak şimdi ifademde söylemiş. Beni tehdit etmiş. Tehditle bu çuvalı bu kızı bana vermiş, ben götürmüşüm. Zaten her şey televizyonda çıkıyor. Elimiz olanı görmedim.

Av. Abdullah Yılmaz : Görmedim.

Mahkeme Başkanı : Bu Gazal Hanım toplantılarına sizi almadılar derken bu ne demek? Yani bu ailenin bir şey saklamaya çalıştığı bir organizasyonun içerisinde....

Gazal Bahtiyar : Yani bir, yani nasıl diyeyim Hakim Bey? Ondan sonra gidiyordu, diyordu. Gelmeyin.

Mahkeme Başkanı : Gelmeyin. Yani aralarında. Bu hareket, bu şüpheli bir şey mi? Yani aile kendi içerisinde kendi derdiyle dertlenmek istemez mi? Yani dışarıdan birinden ziyade kendi içinde ağlamak istemez mi? Bu şüpheli bir şey mi? Bundan şüphelendiniz mi? Yani bu ailenin sizi yanınıza almaması, bu ailenin bunu Narin'i kaybettiği anlamına kayıp edip öldürdüğü anlamına gelir mi?

Gazal Bahtiyar : Hakim Bey ben böyle diyorum. Biz çıkıyordu, diyorduk, teselli etmeye gidiyoruz. Aile toplantısı var, bizi aralarına almıyordu. O kadarını biliyorum.

Mahkeme Başkanı : Toplantıda kim var?

Gazal Bahtiyar : Aile var.

## Duruşma Savcısı

Duruşma Savcısı : Beyanlarında ifadelerinde hatırladığım kadarıyla savcılık sorgusunda da "Burası yasak, buraya giremezsiniz" şeklinde kızının ve senin hatırlıyor musun?

Mahkeme Başkanı : Öyle bir şey söylediler mi?

Duruşma Savcısı : "Burası yasak, bu bölgeye giremezsiniz". İlk günden itibaren Arif Gürangil'in evinin tarafına. Çocukların ve senin beyanların var bu şekilde, bilgi sahibi.

Tercüman : Biz oraya gittiğimizde aile toplantısı var kimse gelmesin diyordu.

## Sanık Enes Güran Müdafileri

### Av. Mahir Akbilek

Av. Mahir Akbilek : Soracağım bazı sorulara cevap vermeyebilirsiniz ama cevap vermeyeceğinizi söylemeniz gerekir. 9 Eylül 2024 tarihinde bilgi alma tutanağı adı altında ifadenize, bilginize başvurulmuş. Orada olay günü sabah Nevzat kahvaltı yaptıktan sonra Oğlunuz Ferhat ile beraber, Ferhat Bahtiyar ile beraber Çarıklı mahallesindeki bu bahsettiğiniz inşaat halindeki evin elektrik işlerini yapmaya gittiğini söylemişsiniz. Hatırlıyor musunuz?

Gazal Bahtiyar : Eşim oraya gitti. Ferhat değil, Ferhat Pirinçlik köyünde çalışıyordu.

Av. Mahir Akbilek : İfadenizi okuyorum ben. 09.09.2024 tarihli ifadenizden alıntı yapıyorum. Bire bir. Bu ifadedeki bu cümleyi hatırlıyor musunuz?

Gazal Bahtiyar : Hatırlamıyorum ama...

Av. Mahir Akbilek : Hatırlamıyorsunuz. Tamam. Daha sonra 18 Eylül 2024'te bir ifadeniz daha var. Burada düzeltiyorsunuz. Ferhat'ın ayrı gittiği. Açıklıyorsunuz artık. Bu ikinci ifadenizi hatırlıyor musunuz?

Gazal Bahtiyar : Yani o ifadeyi hatırlamıyorum. Ama benim bildiğim, Ferhat Pirinçlik köyünde çalışıyordu. Nevzat saat 06:30'da Çarıklı'ya gitti, elektrik işi yapıyordu. Benim hatırladığım budur. Nevzat'ın bir tane işçisi vardı, Vedat ismi. Ceyeran, elektrikçiydi.

Tercüman : Oğlu Pirinçlik'te çalışıyor, Nevzat da bir işçiyle tekmiş.

Av. Mahir Akbilek : Evet. Az önce ifadenizde bu bir soruya verdiğiniz cevapta, oğlunuz Ferhat'ı şahit gösterdiniz kendinize. Dediniz ki, Yüksel Hanım'ın hatta soru olarak soramadı da, dediniz ki benim oğlum Ferhat da o gün geldi senin, yani onu demek istediniz. Kızını aramak için. O da camide uğraşlar içine girdi dediniz.

Gazal Bahtiyar : Tamam, saat 7'ydi zaten. Ferhat işten geldi. Baktı kalabalıktı. Yüksel'le, Enes'le, Hediye'yle beraber biz caminin tarafına gidiyorduk. Ne oldu? dedi. Biz dedik Narin kaybolmuş. Oğlum da bizimle beraber caminin içini bütün aradı. Pencereden girdi. Dedi belki kız uyuyakalmış.

Av. Mahir Akbilek : Tamam, hatırlıyorsunuz. Tamam. Oğlunuz size göre eşiniz gibi, öyle söylediniz, güvenilir bir insan mıdır? Size göre.

Mahkeme Başkanı : Anneye bu soru ilginç olmadı mı Avukat Bey?

Av. Mahir Akbilek : Olmayacak Sayın Başkanım. Peki. Olmayacak. Size göre oğlunuz güvenilir bir insan mıdır?

Gazal Bahtiyar : Güvenilir.

Av. Mahir Akbilek : Siz güveniyor musunuz?

Gazal Bahtiyar : Evet.

Av. Mahir Akbilek : Tamam. Peki, oğlunuz neden aynı şekilde, sizinle aynı şekilde, önce kocanızı, Çarıklı'da ki eve, o inşaata gitme noktasında destekleyici beyanda bulunduğu kayın biraderleriniz ile birlikte, Mehmet Bahtiyar ile birlikte, yani olay günü özetle, olay günü neden kocanızın Çarıklı'da bir inşaata çalışmaya gittiğiyle ilgili daha sonra kendinizin düzelttiği, kendinizin yalanladığı bir tanıklık ifadesi vermeye mecbur hissettiniz? Sebep neydi?

Gazal Bahtiyar : Benim eşim, o gün, yani tutukladığı gün, o evde çalışmıyordu.

Av. Mahir Akbilek : Soruma, cevap verseniz aslında. Benim sorma, cevap verip, ya da cevap vermek istemediğinizi sorayım bu soruya.

Mahkeme Başkanı : Soruyu anlayamadı.

Av. Mahir Akbilek : Neden ihtiyaç duydunuz?

Mahkeme Başkanı : Anlayamadı galiba.

Av. Mahir Akbilek : Şimdi, birinci bilgi sahibi ifadesinde, oğlum Ferhat ve kocam Nevzat, birlikte aynı araçla Çarıklı'ya gittiler der, kahvaltıdan sonra der.

Tercüman : Sabah erken birlikte çıktılar, Ferhat Pirinçlik'e gitmiş......

Av. Mahir Akbilek : Tamam beraber çıktılar.

Tercüman : Tam olarak hatırlamıyorum. Hatırlamıyorum ha.

Av. Mahir Akbilek : Hangisi? Hangisi? Az önce siz çevirdiniz. Az önce siz dediniz ki oğlum ve eşim birlikte gitti Çarıklı'ya. Daha sonra oğlum başka bir yere, Pirinçlik'e gitti.

Gazal Bahtiyar :  Hani ben hatırlamıyorum ha. Ben hatırlamıyorum.

Av. Mahir Akbilek : O gün. Ama bu sorumun cevabını hatırlamıyorum olarak mı veriyorsunuz? Evet. Tamam.

Av. Mahir Akbilek : Yani bu dava kapsamında şu an devam eden ana soruşturmada 202446201 olması lazım. Ana soruşturma dosyası kapsamında sadece yalan söylediği düşünüldüğü için, saatler konusunda bulunduğu yer konusunda, yanında bulunduğunu ileri sürdüğü bir kişinin daha sonra bunu ileri süren kişinin yanında olmadığının açıklığa kavuştuğu değerlendirilerek şu anda cezaevinde tutuklu yargılandığını biliyor musunuz?

Gazal Bahtiyar : Biliyorum.

Av. Mahir Akbilek : Bilginiz var mı? Tamam. Peki kocanızı övdünüz. Az önce kocanızı övdünüz. Bundan şunu anlayabilir miyiz? Eğer siz kocanızın bu iğrenç suça iştirak ettiğine inansaydınız...

Mahkeme Başkanı : Kendi ellerimle teslim ederdim. Teslim ederdim.

Av. Mahir Akbilek : Teyit alalım Sayın Başkanım.

Mahkeme Başkanı : Üç kere sordum. Üç kere sordum. Yok yok bunu.

Av. Mahir Akbilek : Ben aynı soruyu sormayacağım Sayın Başkanım. Güveni yıkılır mıydı kendisine?

Av. Mahir Akbilek : İnanmıyorum değil mi dedi?

Mahkeme Başkanı : Türkçe'ye çevir. Ben anlamadım. Türkçe'ye çevir.

Tercüman : Başkanım dedi ki, ben inanmıyorum onun öldürdüğünü dedi.

Mahkeme Başkanı : Tamam.

Av. Mahir Akbilek : Kocanız sizinle 21 Ağustos 2024'ten gözaltına alındığı tarihe kadar herhangi bir şekilde bu cinayeti anlattı mı? Veya bu işin içinde yer aldığından kuşkulanmanızı sağlayacak bir takım anlatımlarda bulundu mu?

Gazal Bahtiyar : Hayır.

Av. Mahir Akbilek : Asla. O zaman ilk sorumu bir daha soruyorum size. Neden onunla ilgili böyle bir beyan verdiniz? Neden dediniz ki oğlum Ferhat'la birlikte ayrıldı? Siz bunu neden söyleme gereği duydunuz?

[Tercüman ve tanık kendi aralarında Kürtçe konuştu.]{.bracket-box}

Av. Mahir Akbilek : Hayır ben onu sormuyorum ama anlıyorsunuz benim sorumu. Diyorum ki, Tavşantepe'den Çarıklı'ya, öyle söyleyeyim o halde. Tavşantepe'den Çarıklı'ya ayrılışa kadar. Çarıklı'dan sonrasını sormuyorum ben. Neden? Kocanızın yanına oğlunuzu katma gereği duydunuz? Madem hiçbir sıkıntısı yok. Siz güveniyorsunuz zaten ona. Hiçbir iştirakten de kuşkulanmıyorsunuz.

Gazal Bahtiyar : Yani. Evet.

[Tercüman ve tanık kendi aralarında Kürtçe konuştu.]{.bracket-box}

Av. Mahir Akbilek : Soruma cevap vermiyorsunuz ama.

Mahkeme Başkanı : Ne cevap verdi? Yüksel. Ne söyledi?

Av. Mahir Akbilek : Başkanım Hatırlamıyorum diye cevap vermiş, değil mi?

Tercüman : Eşiniz işe gidiyor. Neden oğlunuzla beraber işe gittiğiniz ifadenizde belirtilir, diyor. Belirtme ihtiyacı duydunuz. anlatıyorum.

Gazal Bahtiyar : Beraber işe gidiyorlardı, öyle söyledim. Bazen ablasıyla, arabasıyla gidiyordu. Çarşıya kadar gidiyordu bazen. Başkanım, evden çıktıkları zaman kadın evde. Beraber çıkıyorlar evde. Bazen amcasıyla ama görmüyor tabii. Görmemişim.

Mahkeme Başkanı : Yani evden çıktığını biliyorsun ancak sonrasını bilmiyorsun. Oldu mu avukatım?

Av. Mahir Akbilek : Peki. Daha sonra ifadenizde neden bu beyanınızdan vazgeçmeye ihtiyacı duydunuz? Neden? 18 Eylül'deki ifadenizde bu kez kocam tek başına gitti, oğlum ayrı gitti, Mehmet Bahtiyar'la gitti bu kez.

Tercüman : Sesi anlaşılamadı. Kısık sesle konuştu.

Av. Mahir Akbilek : Tam çevrilmesini istiyoruz. Bende Kürtçe biliyorum tam anlayamadık.

Tercüman : O zaman bilmiyordum bana sorulunca böyle cevap verdim.

Mahkeme Başkanı : Bu hususta çelişki gideremedi. Artık bu soruyla son noktayı koyalım. Çelişkiyi gideremedik.

Av. Mahir Akbilek : Şimdi koyacağız müsaadenizle son noktayı. Peki. Sizi anladık. Kayın biraderiniz Mehmet Bahtiyar neden sizinle aynı zaman döngüsü içerisinde sizinle aynı şekilde hareket etti? Sizin, sizin beyanlarınızla birlikte aynı iddiada bulunup sonra sizin beyanlarınızın dönüşümüyle birlikte aynı iddiadan geri çekildi. Bu konu hakkında bir bilginiz ve bir fikriniz var mı?

Mahkeme Başkanı : Bilgim yok dedi.

Av. Mahir Akbilek : Peki, ben buna organize kötülük desem mesela? Çok üzülürsünüz değil mi? Sayın Başkanım ben olay günüyle ilgili de müsaadenizle bir iki çok kısa soru soracağım. Sabrınız için teşekkür ederim.

Mahkeme Başkanı : Rica ederim. Ne demek.

Av. Mahir Akbilek : Evin içerisinde siz, kocanız Nevzat, olay günü, olay tarihinde kaynananızın ayrı bir evde oturduğunu belirttiniz bizlere. Aklınızda canlansın diye ayrı ev deyince biz bizim evler gibi düşünüyoruz. Ayrı ev derken birbirinizi hiç duymaz mısınız? Ses gelmez mi bir evden?

Gazal Bahtiyar : Ses gelmez.

Av. Mahir Akbilek : Kocanız arabaya binip gitti dediniz ya beyanınızda. Arabaya binip gittiği zaman siz aracın yönünü kontrol ettiniz mi? Köyün altına doğru mu, üstüne doğru mu gittiğine bakma ihtiyacı duydunuz mu? Baktınız mı? Arabaya binip gittiği zaman? Okul, mezarlık o tarafa doğru mu? Yani mezarlığın yanına doğru mu? Yani sizin evin kapısına göre sola doğru mu gitti?

Mahkeme Başkanı : Nereden sola, nereden sağa? Mezarlığa doğru gitti.

Av. Mahir Akbilek : Mezarlığa doğru gitti. Kocanız telefonla görüştükten sonra arabaya binip mezarlığa doğru gittiği o iki aralıkta yaya olarak herhangi bir yere gitmek için evden çıktı mı? Gördünüz mü?

Gazal Bahtiyar : Ben içerideydim.

Av. Mahir Akbilek : Böyle bir ses duydunuz mu? Size Gazal çıkıyorum falan veya siz ayak sesi..

Gazal Bahtiyar : Zaten bana dedi ki, ben ağaç sulamaya gidiyorum. avluda ağaç suluyordu. Ben de daha içerideydim. Kaç, bilmiyorum kaç dakika geçti aralarında. Sonra geldi dedi, Gazal ben Çarıklı'ya gidiyorum. Benim biraz işim var orada. Oğlumun evinde yani elektrik işi. Sonra dedi ben gidiyorum. Ben de dedim, tamam. Yani gördüm arabaya bindiğini gördüm. Bindi aşağıya doğru gitti.

Av. Mahir Akbilek : Teşekkür ederim.

### Av. Muhammed Fatih Demir

Av. Muhammed Fatih Demir : Narin'i köyde ne sıklıkla görüyordunuz?

Gazal Bahtiyar : Nasıl?

Av. Muhammed Fatih Demir : Narin'i köyde ne sıklıkla görüyordunuz? Her gün görüyor muydunuz onu?

Gazal Bahtiyar : Narin. Yok ben görmüyordum.

Av. Muhammed Fatih Demir : Narin'i görmüyordunuz?

Gazal Bahtiyar : Benim çocuklarımın yaşında değil ki ben onu göreyim.

Av. Muhammed Fatih Demir : Narin dışarı çıkmıyor muydu?

Gazal Bahtiyar : Dışarıya çıkmıyordu ama çocukların, yani kendi yaşıt çocuklarıyla gidiyordu. Hacı Hüseyin'in evine gidiyordu.

Av. Muhammed Fatih Demir : Dışarı çıkarken sizin evinizin yakından geçmiyor muydu?

Gazal Bahtiyar : Nasıl yani?

Av. Muhammed Fatih Demir : Evinden çıktığı zaman Narin Kendi evinden dışarıya.

Gazal Bahtiyar : Bizim evin yakınından geçmiyor.

Av. Muhammed Fatih Demir : Camiye gitmiyor muydu?

Gazal Bahtiyar : Arkasında da vardı yol. Evin önünde de vardı. Bizim evin arkasında da yol vardı.

Av. Muhammed Fatih Demir : Ondan dolayı göremediniz, doğru mu? En son ne zaman gördünüz bu olaydan önce?

Gazal Bahtiyar : Bir aydır görmedim.

Av. Muhammed Fatih Demir : Sizin eviniz ile Arif Beylerin evi arasında ne kadar mesafe var?

Gazal Bahtiyar : Onlar tepede de. Bizimki aşağıda.

Av. Muhammed Fatih Demir : Tahmini ne kadar mesafe? Kaç dakikada gidilir?

Gazal Bahtiyar :  3-4 dakika.

Av. Muhammed Fatih Demir : 3-4 dakikalık bir yer ama Narin'i hiç görmediniz. Siz Narin'i görseydiniz eğer köyde, onunla konuşur muydunuz? Selam verir miydiniz ona mesela?

Gazal Bahtiyar : Konuşurduk.

Av. Muhammed Fatih Demir : Severdiniz değil mi Narin'i?

Gazal Bahtiyar : Yani ben görseydim konuşmazdım. Çocuktur.

Av. Muhammed Fatih Demir : Seviyordunuz onu. Konuşurdunuz değil mi?

Gazal Bahtiyar : He.

Av. Muhammed Fatih Demir : Peki eşiniz görseydi eğer, O da konuşur muydu onunla?

Gazal Bahtiyar : Eşim Nerede görecekti? Nasıl nerede görecekti?

Av. Muhammed Fatih Demir : Aynı köyde yaşamıyorlar mı? Bir ihtimal, çok küçük bir köy, 3 ayda bir gördüğünü düşünelim sizin beyanınıza göre. 3 ayda bir gördüğü zaman Nevzat Bey Narin'e selam verir miydi? Merhaba Narin. Nasılsın Narin?

Gazal Bahtiyar : Ben görmedim.

Av. Muhammed Fatih Demir : Tahmininiz de yok bu hususta. Tahmin edemiyorsunuz, değil mi?

Gazal Bahtiyar : Görmedim bilmiyorum.

Av. Muhammed Fatih Demir : Peki. Olay günü, ayın 21'inde sizin bir tane çocuğunuz Arif Beylerin evinde yatıya kalmıştı. Kimdi o çocuğun adı?

Gazal Bahtiyar : İbrahim Bahtiyar.

Av. Muhammed Fatih Demir : Daha önce İbrahim Bahtiyar orada kalıyor derken "Biz birbirimizi çok seviyorduk. Aramızda bir husumet yok" dediniz, değil mi? Aranızda bir husumet yoksa, birbirinizi seven iki aileyseniz Neden Nevzat Bey onu gördüğünde Selam vermesin?

Gazal Bahtiyar : Hani siz diyorsunuz selam vermiş, Ben de diyorum ben görmemişim.

Av. Muhammed Fatih Demir : Bir gördükleriniz vardı, bir tahmin ettikleriniz vardı.

Gazal Bahtiyar : Belki de konuşurdu.

Av. Muhammed Fatih Demir : Mesela Narin onun önünden geçseydi ve Nevzat Bey ona gel deseydi, çağırsaydı ya da belli bir yerde buluşsaydı bu mümkün olabilecek bir ihtimal mi?

Gazal Bahtiyar : Narin hiç kimsenin yanına gelmezdi.

Av. Muhammed Fatih Demir : Hiç kimsenin yanına gelmezdi. Evleriniz yan yana. Birbirinizi seven iki ailesiniz. Aranızda bir husumet yok ama yine de Narin Kimsenin yanına gitmezdi, öyle mi?

Gazal Bahtiyar : Akıllı bir kızdı.

Av. Muhammed Fatih Demir : Siz kimsesiniz o zaman orada?

Gazal Bahtiyar : Yani kimsenin yanına gitmezdi.

Av. Muhammed Fatih Demir : Yani siz o zaman yakın değilsiniz iki aile?

Gazal Bahtiyar : Yani nasıl? akraba değiliz? Yani yakınız, akraba değiliz.

Av. Muhammed Fatih Demir : Peki. Size bir şey soracağım. Bitireceğim Sayın Başkan. Çok sorular soruldu. Eşiniz normalde sıva işi için bir yere gidiyor. O gün olayın olduğu gün oğlunun evine elektrik işi için gitti, değil mi?

Gazal Bahtiyar : Evet.

Av. Muhammed Fatih Demir : Siz de beyanınızda bunu belirtmişsiniz. Her gün sıva işine giden biri neden o gün Elektrik işi için gitti?

Gazal Bahtiyar : Oğlum, onun evi bitirmişti hepsi. Tamam. Eşyaları içeriye çekmişti. Tek elektrik işi vardı. Kalmıştı öyle. Bir usta o gün elektrik işi yapıyordu. Elektrik çekiyordu.

Av. Muhammed Fatih Demir : Sizi doğru mu anladım? Oğlunuz Ferhat'ın evinde bir elektrikçi vardı değil mi? Vedat.

Gazal Bahtiyar : Vedat. Eşimle o beraber gitmişti.

Av. Muhammed Fatih Demir : Eşiniz elektrikçiydi değil mi? Eşiniz neden Vedat'la birlikte gitti peki oraya?

Gazal Bahtiyar :  Elektrikçidir o.

Av. Muhammed Fatih Demir : Tamam. Onu anladım zaten ben. Eşiniz diyorum, neden elektrikçi? Evde kimse yok. Boş bir ev. Yeni bitmiş. Özel bir eşyaları yok.

Gazal Bahtiyar : O adam tek o eve elektrik işi yapmaya gitmezdi ki. Mecbur ev sahibi orada olsaydı.

Av. Muhammed Fatih Demir : Pekala. Son bir kısım var. Hep bir karakter analizi yapılıyor, soruluyor. Gazal Hanım'dan da duymak istiyorum. Nevzat Bey'in karakter yapısını duymak istiyorum. Yani şu anlamda. Köyde, sosyal hayatında akrabalarla arası nasıl biriydi?

Gazal Bahtiyar : Yani ahlaklıydı, huyu güzeldi.

Av. Muhammed Fatih Demir : Yani çok konuşan biri miydi yoksa böyle susan biri miydi?

Gazal Bahtiyar : Suskun.

Av. Muhammed Fatih Demir : Suskun biri miydi? Anladım.

## Sanık Yüksel Güran Müdafi

### Av. Yılmaz Demiroğlu

Av. Yılmaz Demiroğlu : Gazal Hanım sizin demin ifadenizde korucu akrabalarınız olduğunu söylediniz.

Gazal Bahtiyar : Evet.

Av. Yılmaz Demiroğlu : Onlar hangi köyde oturuyor?

Gazal Bahtiyar : Batıkarakoç'ta.

Av. Yılmaz Demiroğlu : Batıkarakoç'ta. Soyadları Kaya değil mi?

Gazal Bahtiyar : Kaya.

Av. Yılmaz Demiroğlu : Peki köyde Kaya'lar var mı? Tavşantepe köyünde?

Gazal Bahtiyar : Var.

Av. Yılmaz Demiroğlu : Kaç aile Kaya'lardan oluşuyor? Güran'lar mı çok kayalar mı?

Gazal Bahtiyar : Güran'lar daha çok.

Av. Yılmaz Demiroğlu : Peki. Oğlunuz olay günü Pirinçlik'te çalışıyordu, değil mi?

Gazal Bahtiyar : Evet.

Av. Yılmaz Demiroğlu : Akşam eşiniz eve geldiğinde, Çarıklı'ya geldiğinde arabayı kim kullanıyordu?

Gazal Bahtiyar : Zaten eşim Çarıklı'daydı. Benim oğlum da Pirinçlik'ten, işten geldi. Eşim onu aldı. Beraber eve geldiler.

Av. Yılmaz Demiroğlu : Tamam. Eşiniz mi arabayı kullanıyordu?

Gazal Bahtiyar : Evet. Nevzat kullanmıştı.

Av. Yılmaz Demiroğlu : Nevzat kullanıyordu. Demin dediniz ya Ferhat gitti camiye, Yüksel bağırdığında.

Gazal Bahtiyar : Saat 7'de eşimle oğlum eve vardı. O akşam eve vardı. Biz de, ben de dama çıktım. Baktım ses geliyor. Yüksel Güran. Enes Güran bir de Hediye Güran.

Av. Yılmaz Demiroğlu : Evet.

Gazal Bahtiyar : Çağırıp bağırıyordu. Yani Narin kaybolmuş, Narin'i kaçırmış. Narin. Öyle dedi. Yani biz de onunla beraber caminin etrafını içini yani Ferhat da bizimle beraber geldi. Beraber gittik, camiyi aradık. Oğlum hatta kapı kilitliydi. Oğlum pencereden girdi. Bütün caminin içini aradı. Dedi belki kız uyuyakalmış. Oğlum da bizimle beraber camiyi aradı. Biz de on buçuk'a kadar Yüksel'le beraber köyü dolaştık, aradık.

Av. Yılmaz Demiroğlu : Aradınız. Peki oğlunuz bu kadar fedakarken o eşiniz size niye yardım etmedi? O da niye aramalara katılmadı?

Gazal Bahtiyar : Eşim de doğru eve geldi.

Av. Yılmaz Demiroğlu : Eşiniz bir şey yapmadı mı o arada? Ya bir çocuk kayıptır. Gidip arayalım gibi. Teklif etmediniz mi?

Gazal Bahtiyar : Bir şey demedim.

Av. Yılmaz Demiroğlu : Sizin torununuz var mı? Torununuz Narin'in yaşlarında mı?

Gazal Bahtiyar : Torunum. He.

Av. Yılmaz Demiroğlu : Mesela torununuzla Narin hiç oyun oynar mıydı?

Gazal Bahtiyar : Okulda oynardı. Beraber oynardı.

Av. Yılmaz Demiroğlu : Beraber oynardı. Peki aynı zamanda komşusunuz Arif'lere, değil mi?

Gazal Bahtiyar : Kızım komşum değil. Kızım benden uzaktır.

Av. Yılmaz Demiroğlu : Siz komşusunuz değil mi? Yok yok, onu demiyorum. Siz Arif'le komşusunuz değil mi?

Gazal Bahtiyar : He ya. Yani yakınız.

Av. Yılmaz Demiroğlu : Yakınsınız. Peki torununuz size geldiğinde Narin hiç gelmez miydi?

Gazal Bahtiyar : Yok. Hiç gelmez.

Av. Yılmaz Demiroğlu : Orada konuşmazlar mıydı?

Gazal Bahtiyar : Hiç görmedim Narin. Hiç benim, yani evime ne geldi ne avluma geldi. Görmemişim.

Av. Yılmaz Demiroğlu : Salim olay günü aradığında, eşinizi aradığında duydunuz. Su meselesi dediniz, değil mi? Ne kadar sürdü bu su muhabbeti?

Gazal Bahtiyar : Ya bir dakika sürmedi.

Av. Yılmaz Demiroğlu : Bir dakika sürmedi. Bak bunu iyi hatırladın. Bir dakika sürmedi diyorsunuz. Bu sohbetten ne kadar süre sonra Salim evin dışına çıktı? Pardon. Arif. Nevzat.

Gazal Bahtiyar : Sofradaydık, yemek yedik konuştuk.

Av. Yılmaz Demiroğlu : Yemek ne kadar sürdü? Yani konuşmadan sonra hemen yemek bitti mi?

Gazal Bahtiyar : Telefon geldiğinde yemek yedik ama kaç dakika sürdü bilmiyorum.

Av. Yılmaz Demiroğlu : Başkanımız da bunu izah etmeye, anlamaya çalıştı sorularınızla. Biz de anlamaya çalışıyoruz. Yani bir insan yemeğe otururken telefondan sonra o yemeğe devam etti mi yoksa devam etmedi mi?

Tercüman : Yemek yedik biraz. Biraz oturdu.

Av. Yılmaz Demiroğlu : O telefondan sonra yemek yedi. Biraz oturdu. Ondan sonra ben ağaç sulamaya gideceğim dedi?

Gazal Bahtiyar : Çok oturmamış.

Av. Yılmaz Demiroğlu : Ağaç sulamaya gittiği zaman sizin kaç tane ağacınız var? Nerededir bu ağaçlar?

Gazal Bahtiyar : Avludadır.

Av. Yılmaz Demiroğlu : Peki patlıcanlarınız var mı?

Gazal Bahtiyar : Yok.

Av. Yılmaz Demiroğlu : Patlıcan sulanır mıydı?

Gazal Bahtiyar : Yok.

Av. Yılmaz Demiroğlu : O gün sulanmazdı, değil mi?

Gazal Bahtiyar : He?

Av. Yılmaz Demiroğlu : O patlıcanınız olmadığı için sulanmazdı, değil mi?

Gazal Bahtiyar : Ağaç suladı.

Av. Yılmaz Demiroğlu : Ha. Eşiniz patlıcan....

Gazal Bahtiyar : Patlıcan tabii. Ayrı vardı.

Av. Yılmaz Demiroğlu : Nerede o patlıcan?

Gazal Bahtiyar : O da yani, o dedi ben ağaç sulamaya gidiyorum.

Av. Yılmaz Demiroğlu : Tamam. Avluda mı patlıcan yoksa evinizin arkasındaki patika yolda mı patlıcan?

Gazal Bahtiyar : O zaman patlıcanlar o zaman patlıcanlar kurudu, yoktu.

Av. Yılmaz Demiroğlu : Eşi Nevzat o sırada evin arkasında patlıcanı da suladığını huzurunuzda beyan etti. Eşiniz de diyor ben patlıcan suladım. Hangisi doğru acaba?

Gazal Bahtiyar :  Patlıcan vardı ama dur. Patlıcan vardı ama o bana ağaçları sulamaya gitti dedi.

Mahkeme Başkanı : Kürtçe ya. Zaptı düzgün geçsin de yazıyor. Söylüyorum. Çünkü polis beyin şeyi yok.

Av. Yılmaz Demiroğlu : Kaynananız Zeynep. Bu Arif'le olan para alışverişi nedeniyle herhangi bir surat murat astı mı? Yüksellere, ailesine vesaire.

Gazal Bahtiyar : Hayır. Görmedim.

Av. Yılmaz Demiroğlu : Bununla ilgili bir muhabbet aranızda geçti mi? Yüksel size hiç dedim ya bu Zeynep niye böyle davranıyor?

Gazal Bahtiyar : Görmedim.

Av. Yılmaz Demiroğlu : Görmedin. Sana soru sormadı mı?

Gazal Bahtiyar : Duymadım, görmedim. Hani husumetimiz yoktu onlarla.

Av. Yılmaz Demiroğlu : Şimdi son bir soru soracağım. Aracı avluda gördüğünüz avlunun önündeki kapıda gördünüz değil mi? Kırmızı aracı.

Gazal Bahtiyar : Evet.

Av. Yılmaz Demiroğlu : Balkondaydınız o sırada.

Gazal Bahtiyar : Zaten bana dedi ben gidiyorum. Çarıklı'ya gidiyorum.

Av. Yılmaz Demiroğlu : Seslenmiş. Ben Çarıklı'ya gidiyorum. Hareket etti. Mezarlık yolundan gitti.

Gazal Bahtiyar : Yani mezarlık yönüne gitti. Yani ben görmedim. Aşağı doğru gitti. Yani aşağı doğru gitmiş ama hangi tarafa gittiğini görmedim. Aşağı doğru gitti. Ya gittiğini net gördüm.

Av. Yılmaz Demiroğlu : Burada bir battaniye alışverişi zaten yok dediniz?

Gazal Bahtiyar : Görmedik.

Av. Yılmaz Demiroğlu : Başka aracı da görmediniz?

Gazal Bahtiyar : Görmedim.

Av. Yılmaz Demiroğlu : Peki sizin tam o arabayı hareket ettiği noktada oradan baktığınızda Arif Güran'ın evi görünür mü?

Gazal Bahtiyar : Bizim evde.

Av. Yılmaz Demiroğlu : Hah. Sizin evde.

Gazal Bahtiyar : Yok görünmez. Yani bizimki aşağıdadır.

## Sanık Salim Güran Müdafi

### Av. Onur Akdağ

Av. Onur Akdağ : Eşiniz yapısı gereği korkak birisi mi? Kimseden korkar mı eşiniz?

Gazal Bahtiyar : Onu bilmiyorum.

Av. Onur Akdağ : Yani 30 yıldır eşinizi tanıyorsunuz. Eşiniz kimseden korkar mı? Yani birinden çekinir mi? Salim'den korkar mı?

Mahkeme Başkanı : Uğultu bir kesebilir miyiz? Yani bir uğultu var oradan. Hah.

Gazal Bahtiyar :  Yani kimseyle kavga etmediği için kimseyle kavga etmez.

Av. Onur Akdağ : Eşiniz peki sık sık yalan söyler mi?

Gazal Bahtiyar : Asla. Asla yalan söylemez. Asla. Aynı başı kesse de yalan söylemez.

Av. Onur Akdağ : Peki huzurdaki ifadesiyle birlikte 6 ifadesi var. Hepsi birbirinden farklı. Neden bu kadar yalan söylüyor?

Gazal Bahtiyar : Ben onu bilmiyorum.

Av. Onur Akdağ : Kaynananız Zeynep Bahtiyar "Arif bizim evimizi yıktı. Arif 50 bin lira bizi dolandırdı" şeklindeki beyanını duydunuz mu?

Gazal Bahtiyar : Duymadım.

Av. Onur Akdağ : Şimdi 30 yıldır eşinizi tanıdığınızı söylüyorsunuz. Çocuklarınız sizden daha az tanıyor. Yaşı itibariyle. Ferhat Bahtiyar mesela Nevzat'ın ruh durumunu anlatırken işte eşim Yüksel'in ağlamalarına hiç tepki vermedi. Sessizce evine gitti. Balkondan bizi seyretti dedi. Ondan sonra Fadile aramalara katılmadığını söyledi. Peki siz neden hiç tedirginliğini sezmediniz? Çocuklarınız bu yaştayken eşinizin o kadar tedirginliğini sezdi. Siz sezmediniz.

Mahkeme Başkanı : Yani bu soruya cevap vermeme hakkına sahipsiniz. Suçlayıcı bir sorudur. Bu soruyu es geçiyorum. Bu tanığı suçlayıcı bir soru.

Av. Onur Akdağ : Peki bir şey daha soracağım. Narin'in bulunduğu gün, Narin'in bulunma haberini aldığınız an hiç bayıldınız mı? Baygınlık geçirdiniz mi?

Gazal Bahtiyar :  Hayır. Zaten hepimiz onun için ağlıyorduk vallahi.

Mahkeme Başkanı : Bir önceki soruya da itiraf, şey öbür türlü sanık kendisi suç altında kaldığı için, o soruya müdahale ettim.

Av. Onur Akdağ : Hiç sıkıntı yok. Sizce Narin'i taşımak, Narin'in cesedini taşımak, Narin'i öldürmek kadar vahşi bir durum değil mi?

Mahkeme Başkanı : Bilmiyorum dedi.

Av. Onur Akdağ : Yani neden eşinizi bu kadar savunuyorsunuz? Ben eşimi görseydim, bu halde görseydim, asla savunmazdım. Eşiniz itiraf ediyor. Şimdi bu dosyada zaten iki gerçek var. Birisi Narin'in ölümü, diğeri de eşinizin itirafları. Başka diğerleri hepsi artık....

Mahkeme Başkanı : Bu soruya da müdahale ediyorum. Bu da suçluyu kayırmaya girer. Bu soruyu da es geçiyoruz.

Av. Onur Akdağ : Peki. Eşinizin en büyük aktivitesi nedir? Yani, mesela ne yapmayı sever, hobileri nelerdir?

Gazal Bahtiyar : Eşim neyi sever? Hep salavat çeker, namaz kılar, böyledir. Böyle bir insandır. Yani temiz bir insandı.

Av. Onur Akdağ : Mesela sık sık balık tutar mı?

Gazal Bahtiyar : Balığa da gider.

Av. Onur Akdağ : Sık sık gider mi?

Gazal Bahtiyar : Yani işi olmadığı zaman gidiyor.

Av. Onur Akdağ : Yani Eğertutmaz deresini avucunun içi gibi bilecek kadar gider mi?

Gazal Bahtiyar : Oraya gitmez de, şeye gider, hani nereye? O gün komutanlar da zaten oraya geldi, o balıktaydı.

Av. Onur Akdağ : Gönenli köyünde insanlar eşiniz hakkında sık sık şunu söylüyor. Biz sazan balıklarını buraya koyuyoruz ki sazan balıkları çoğalsın ve biz toplayalım. Nevzat geliyor. Balıklarımızı toplayıp gidiyor. Eşinizden şikayetçi. Siz hiç Eğertutmaz deresine gittiğini görmediniz mi?

Gazal Bahtiyar :  Eğertutmaz deresine gittiğini görmedim. Yani başka bir yere gidiyordu beraber. Kaç kişi arabaya biniyordu gidiyordu.
