---
title: "Maşşallah Güran İfadesi"
editor: source
---

## Mahkeme Başkanı

Mahkeme Başkanı : O zaman yeminli. Evet herkes ayağa kalkabilir mi? Evet. Maşallah hanım. Doğru söyleyeceğinize namusunuz ve vicdan üzerine yemin eder misiniz?

Maşşallah Güran : Ederim.

Mahkeme Başkanı : Bakın yalan tanıklık yapmak suçtur. Bu yargılamanın sonunda eğer böyle bir kanaate getirirsek hakkınızda suç duyusunda bulunuruz. Siz şu an tutuklusunuz değil mi? Başka bir suçtan. Bu yüzden dolayı da sorularımıza cevap vermeme hakkına sahipsiniz. Kendinize suçlayıcı sorular sorarlarsa buna cevap vermeme hakkına sahipsiniz. Ben de zaten bu konuda size müdahalede bulunacağım. Niyetimiz sizi rahat bir şekilde beyanlarınızı alabilmek tamam mı? Sakin kalmak zaten.

Mahkeme Başkanı : Bu öncelikle şeyden bahsedeyim. Bu bayanlar arasındaki kavga. Nedir bu kavganın muhabbeti? Niye böyle bir kavga yaptınız? Bir dakika, bir Arkadaşlar bir uğultu başladı. Ben kendimi de duyamıyorum yani. O kapının orada da çok ciddi bir uğultu var. O kapının oradakileri bu tarafa da alabiliriz.

Maşşallah Güran : Narin'in bulunduğu gün Hülya Komutan geldi. Hepimiz ağlıyoruz. Hepimiz toplanmışız. Hülya Komutan geldi. Yüksel'e haber verdi. Yüksel de dedi ki komutanım bana söz vermiştin, hani benim Narin'im? Hani Narin'imi getirecektin? O anda çığlık attı, bayıldı. Bayıldı, kucağıma düştü. Kucağıma düşünce Hülya Komutan ile beraber onu ekiple ambulansa aldık. Aldığımız zaman tekrar yerime geçtim. Kusuruma bakmayın biraz...

Mahkeme Başkanı : Nasıl rahat ediyorsanız.

Maşşallah Güran : Yerime oturdum. Hepinizden de özür dilerim. Ben de dedim o Narin hangi şerefsizler sana kıydı? Hangi şerefsizler sana kıydı? Allah belalarını versin. Özür dilerim. Sonra şey geldi. Yüksel'in kız kardeşi ismini unuttum. O geldi. Anlatsaydınız böyle olmazdı. Biz bir şey bilmiyoruz. Biliyorsan dedim sen anlat. O konuda tekrar konuştu. Ben konuşmadım. Kızım ayağa kalktı. Biliyorsan anlat. Biz bir şey bilmiyoruz. O sırada kızım bayıldı. Kızımla ilgileniyorum. Kızımı aldım. Her iki kızımı aldım, eve gittim.

Mahkeme Başkanı : Hangi kızınız?

Maşşallah Güran : Birsen'le Melike.

Mahkeme Başkanı : Peki herkes her şeyi biliyor. Beni konuşturmayın diye bağırmışsınız.

Maşşallah Güran : Kesinlikle. Ben kullanmamışım. Ben onu kabul etmiyorum.

Mahkeme Başkanı : Ben bir şey bilmiyorum. Bilsem söylerim mi dediniz?

Maşşallah Güran : ...

Mahkeme Başkanı : Yok yok. Şimdi öyle dediniz de ben bir şey bilmiyorum. Bilsem sen biliyorsan sen söyle.

Maşşallah Güran : Yaser'e, O'na söyledim. Dedim biliyorsan sen söyle. Biz bir şey bilmiyoruz.

Mahkeme Başkanı : Sizin ağzınızı kapatmaya çalışmışlar erkekler. Senin ağzını kapatan oldu mu?

Maşşallah Güran : Kesinlikle. Öyle bir şey yok.

Mahkeme Başkanı : Kızınızın ağzını kapatanlar oldu mu?

Maşşallah Güran : Yok. Zaten onlar diğer taraftaydı. Belki onun tarafındaydı. Kızımı aldım. Diğer kızımı, küçük kızımı aldım. Onu da aldım, eve gittim.

Mahkeme Başkanı : Eve gittiniz. Peki şey, Birsen'in de biz mi yaptık sanki? Ne üzerimize geliyorsunuz? diye bir şey var. Onu niye böyle bir cümle kurdu bizden? Biliyor musun?

Maşşallah Güran : Onu görmemişim.

Mahkeme Başkanı : Duymadın böyle bir şey?

Maşşallah Güran : Duymadım.

Mahkeme Başkanı : Bir de Maşallah hanım. Şimdi bu soruyu şöyle sorayım. Herkesin sormak istediği soruyu sorayım. Salim sizi bu olaylardan sonra, yani Narin'in kaybolduğundan sonra Narin olabilir, Salim olabilir, Yüksel olabilir, Enes olabilir, Nevzat olabilir. Sizi yönlendirdi mi? Şu şekilde yalan beyanlarda bulunun dediler mi?

Maşşallah Güran : Hayır kesinlikle.

Mahkeme Başkanı : Çünkü siz bizim eve geldi diyorsunuz Narin. Kızımdan öyle duydum diyorsunuz.

Maşşallah Güran : Narin saat iki civarları geliyor. Kızlarımı soruyor. O saatte kızlarım camiye gidiyor. Öğleden önce ben kızlarımı götürüyorum. Annemgile bırakıyorum. Sonra ben eve geliyorum. Kızlarım kalıyor. Ondan sonra Narin geliyor. İki civarları. Kızım da kapıyı açıyor. İki dakika durmadı. Hani Hatice, Fatma dedi anneannemgilde. Kızım bilmiyor camiye gittiğini. Sonra bana söyledi. Ben dedim, camiye bırakmışız. Dedi tamam Narin geldi. Dedi tamam. Sonra 05:40 dememizin sebebi Mina geliyor. Mina geldiği zaman Narin kaybolduğu zaman Mina tamamen aklımdan çıkıyor. Hep Narin diyorum. Hani art bir niyet yok sayın.

Mahkeme Başkanı : Yani o 05:40'ta Narin geldi demeniz aslında Mina geldi. Mina geldi.

Maşşallah Güran : Karışıklık oradan oldu.

Mahkeme Başkanı : Peki bu beyanınız mı? Biz senin beyan verdiğin tarih 29.08. Yani olaydan yaklaşık 7-8 gün sonra.

Maşşallah Güran : Diyorum ya. Hep Narin aklımda. Narin sürekli bizdeydi.

Mahkeme Başkanı : Anlıyorum.

Maşşallah Güran : O da benim çocuğumdu.

Mahkeme Başkanı : Yani Narin sabah geldi. Saat iki gibi. Evet. Şimdi bu meşhur bir video var. Narin'in hatta sosyal medyada da çok ciddi tartışmalar açan bir video. Narin bir geliyor, sonra koşarak gidiyor. O sırada, o arada Narin sizin eve mi geldi?

Maşşallah Güran : Kaçta efendim?

Mahkeme Başkanı : İki iki....

Maşşallah Güran : Evet evet, camiye gidiyor.

Mahkeme Başkanı : Yani o sırada Narin sizin eve geliyor. Sizin kızlarınızı soruyor. Kızlarınız evde olmadığı için camiye koşarak gidiyor. Bu sosyal medyada işte acaba Narin ne gördü de kaçıyor gibi haberler yapıldı. O videodan önce sizin evinize geldi. Kızlarınızı sordu. Kızlarınızı görmeyince camiye onlara yetişmek için gittiğini varsayıyoruz.

Maşşallah Güran : Çünkü akşamdan sözleşmişti her üçü de.

Mahkeme Başkanı : Saat on yedi, on yedi buçuk gibi Narin gelmedi. Olay günü Narin'i sadece saat ikide gördünüz.

Maşşallah Güran : Ben görmedim. Kızım kapıyı açtı.

Mahkeme Başkanı : On yedi kırkta kapıyı açtı dedin. Mina geldi.

Maşşallah Güran : Mina geldi.

Mahkeme Başkanı : Sen Birsen'den Narin'i gördüm dediğinde aslında zaman olarak sabahkini kastediyorsun ama saat on yedi buçuk gibi olmuş.

Maşşallah Güran : Kaybolduğu zaman karışıklık işte oradan oldu. Yani art bir niyetimiz yok. Çabuk bulunsun diye.

Mahkeme Başkanı : Anlıyorum. Yani bir art yani bu şekilde yanlış beyan vermeniz birilerini yönlendirmek için Salim'in.

Maşşallah Güran : Hayır.

Mahkeme Başkanı : Çünkü şöyle bir iddia var iddianamede. İddia makamının iddiası şu. Diyor ki, Salim de bunu tertipledi. Çünkü Birsen'in şöyle bir beyanı var. Birsen miydi o? Şey bizi ha Birsen'de Melike'nin şöyle bir beyanı var. Salim bize geldi. Siz 17:40'ta geldi deyin diye bir sözü var. O yüzden dolayı Birsen'in böyle bir beyanda bulunma ihtimali var mı?

Maşşallah Güran : Öyle bir şey yok sayın hakimim.

Mahkeme Başkanı : O gün.

Maşşallah Güran : Birsen'le Salim abi Narin kaybolduktan sonra bu saat konusunu söylüyor. Hani bana anlattı, evdeyken anlattı. Hangi saatte gelmişse o saatte devletimize söyleyin, çabuk bulsun. Bunu söylüyor.

Mahkeme Başkanı : Ama kızınızın işte 17:40'ta söyleyin diye bir beyanı var. O konuda bir bilginiz var mı?

Maşşallah Güran : Ondan bilgim yok.

Mahkeme Başkanı : Bu olaylar sırasında Salim hiç evinize geldi mi?

Maşşallah Güran : Salim geldi. Altı altı buçukta geldi. Amcasının elini öptü. Halasının elini öptü. Halası yeni gelmişti. Biz de Mersin'den geldiğimiz için bizi de sordu. O sırada ben yukarı çıktım. Geldim, gitmişti. Beş dakika kapımızda durmadı.

Mahkeme Başkanı : Siz amcasıyla, yani amcası dediğiniz sizin kayın babanız mı?

Maşşallah Güran : Yok benim eşim Hüseyin Güran.

Mahkeme Başkanı : Hüseyin Güran pardon. Hüseyin Güran Salim'in amca oluyor.

Maşşallah Güran : Evet amcasıdır.

Mahkeme Başkanı : Siz nereden gelmiştiniz olay günü?

Maşşallah Güran : Mersin'den gelmiştik.

Mahkeme Başkanı : Mersin'den gelmiştiniz. Saat altıda elini öpmeye geldi amcasının.

Maşşallah Güran : Evet, geldi. Amcası kapıdaydı, öyle halası.

Mahkeme Başkanı : Tam olarak saati hatırlıyor musun?

Maşşallah Güran : Tam hatırlamıyorum. Altı altı buçuk vardı.

Mahkeme Başkanı : Peki hiç sen görüştün mü o sırada Salim'le? Gördün mü?

Maşşallah Güran : Gördüm. Oğlu ile beraberdi.

Mahkeme Başkanı : Peki o tarih itibariyle Narin kayboldu. Bir iddiaya göre de Narin'i Salim öldürdü. Peki Salim'de böyle bir şüpheli bir şey sezdin mi?

Maşşallah Güran : Yok, her günkü haliydi.

Mahkeme Başkanı : Normal her günkü haliydi?

Maşşallah Güran : Normal her yani geldiği zamanki haliydi.

Mahkeme Başkanı : Hiç panik yoktu? Heyecan yoktu?

Maşşallah Güran : Ben görmedim.

Mahkeme Başkanı : Yani gördüğün kadarıyla hiç şüphelenmedin yani?

Maşşallah Güran : Yok. Zaten o sırada ben yukarı çıktım, geldiğim de yoktu.

Mahkeme Başkanı : Nevzat'ı tanıyor musunuz?

Maşşallah Güran : Tabii bizim komşumuzdur.

Mahkeme Başkanı : Sizin komşunuzdur. Evet. Nevzat da Güran ailesinin arası nasıldır? Genel olarak ya da Salim Güran'la arası nasıldır?

Maşşallah Güran : Yani genel olarak iyiydi. Bugüne kadar iyiydi bizim için. Ama şimdiden bu saatten sonra bizim için iyi değil.

Mahkeme Başkanı : Niye?

Maşşallah Güran : Bu şüphe hep ona gidiyor. Salim'e de gidiyor.

Mahkeme Başkanı : Salim'e de gidiyor. Yüksel'e de gidiyor. Enes'e de gidiyor. Şüphe şu an dörde bölündü. Dördüne gidiyor.

Maşşallah Güran : O zaman dörde bölündüyse o kayıt kamerasını çıkarın karakolun. Çıkarın.

Mahkeme Başkanı : İnşallah. İnşallah.

Maşşallah Güran : İnşallah çıkarsa hepsi açığa çıkar.

Mahkeme Başkanı : İnşallah.

Maşşallah Güran : Bizden de olsa Allah belasını versin, kim olursa olsun.

Mahkeme Başkanı : Çıkacak da. Kamerayı isteyeceğiz de. Nevzat'la Salim'in arasında herhangi bir probleme şahit olmadınız bugüne kadar. Ama bu olaydan sonra artık Nevzat'ı şüphelendiğiniz için sildiniz.

Maşşallah Güran : Bunları karakolda zaten öğrendim.

Mahkeme Başkanı : Ondan sonra Nevzat'ı sildiniz. Ama Nevzat'tan bu zamanda bir husumetiniz yok?

Maşşallah Güran : Yok.

Mahkeme Başkanı : Şüphelerinizi temizleyerek, şüphelerinizden arınarak bir soru soruyorum. Nevzat'ın birini öldürme ihtimali var mı?

Maşşallah Güran : Yani şu ana kadar yoktu.

Mahkeme Başkanı : Hah. Şu ana kadar yoktu. Salim'in birini öldürme ihtimali var mı?

Maşşallah Güran : Onun da yok. Bugüne kadar bu kadar çocuğumuz var. Bir fiske ondan dayak yemedi.

Mahkeme Başkanı : Peki Yüksel kızını öldürme, Enes kardeşini öldürme ihtimali var mı?

Maşşallah Güran : İnanmıyorum.

Mahkeme Başkanı : İnanmıyorum. Delal Kaya kimdir?

Maşşallah Güran : Yeğenimdir.

Mahkeme Başkanı : Mahide Kaya da. Onlar eve geldiler mi?

Maşşallah Güran : Evet.

Mahkeme Başkanı : Saat kaçta geldiler?

Maşşallah Güran : Saati tam olarak ben bilmiyorum. köye gelmişti. Beni aradılar. Ben istemiştim. Dedim bana çorap getirin.

Mahkeme Başkanı : Onlar çorap satıyor, değil mi?

Maşşallah Güran :  Satmıyor. Arabacı getirmişti. Dedim bana getirin. Onlar da bana getirdiği çorapları aldılar gittiler. Ben çorap aldım. Onlar gittiler eve.

Mahkeme Başkanı : Ya Salim geldiğinden önce mi geldi sonra mı geldiler?

Maşşallah Güran : Onu ben tam olarak hatırlamıyorum.

Mahkeme Başkanı : Çünkü Mahide'de beyanında saat 18 gibi halini gördüm diyor da o yüzden soruyoruz. Bu Mahide'nin size geldiği saat Salim'in geldiğinden önce mi, geldiğinden sonra mı?

Maşşallah Güran : Hatırlamıyorum. Hatırlamıyorum.

Mahkeme Başkanı : Evet. Şimdi şundan şey. Sizin eviniz nerede?

Maşşallah Güran :  Köyde.

Mahkeme Başkanı : Köyün neresinde?

Maşşallah Güran : Köyün biraz dışında. Okulun arka tarafındadır.

Mahkeme Başkanı : Tepede?

Maşşallah Güran : Tepe değil. Tepenin altındadır.

Mahkeme Başkanı : Yani o etrafınıza vakıf olabileceğiniz bir şeyde değil mi? Yani böyle etrafınıza baktığınızda.

Maşşallah Güran : Evim tektir orada.

Mahkeme Başkanı : Ya tektir.

Maşşallah Güran : Okulun arkasında.

Mahkeme Başkanı : Evin, yani evin. Arif'in evi nerede? Arasında ne kadar mesafe var?

Maşşallah Güran : Yani tepe olduğu için, uçurum olduğu için ben onu bilemem ne kadardır.

Mahkeme Başkanı : Yani şunu söyleyeyim. Sizin evinizden Arif'lerin evini görebiliyor musunuz?

Maşşallah Güran : Aşağıdan mı?

Mahkeme Başkanı : Sizin evinizden Arif'lerin evini.

Maşşallah Güran : Şeylerin çatısını görüyorum.

Mahkeme Başkanı : O bahçe ahırı görebiliyor musunuz? Çünkü Yüksel ilk size geliyor değil mi? Narin nerede diye.

Maşşallah Güran : Evet tepeden çağırıyor.

Mahkeme Başkanı : Narin nerede diye ses sesleniyor değil mi? Onun sebebi kızınızla birlikte Kur'an kursuna gittiği için midir? Yani sizin o Narin'in öldürüldüğü saat 15:15'te ve 15:30 arasında Yüksel'in evinde bir hareketlilik gördünüz mü?

Maşşallah Güran : Ben görmedim. Evden hiç çıkmadı.

Mahkeme Başkanı : Hiç çıkmaz. Nevzat'ın evini görebilir misiniz?

Maşşallah Güran : Ben göremem onun evini.

Mahkeme Başkanı : Yani herhangi bir araba, kırmızı araba, beyaz araba böyle bir hareketlilik görmediniz? Duymadınız da?

Maşşallah Güran : Duymadım. Yani kapımda görsem muhakkak duyarım. Kapımda da ben görmedim geçtiği.

Duruşma Savcısı : Narin 2'de geldi dediniz, değil mi? Maşallah hanım. Mine kaçta geldi dediniz?

Maşşallah Güran : 17:40'dı.

Duruşma Savcısı : 17:40 gibi Mine geldi diyorsunuz. Karıştırdınız diye.

Maşşallah Güran : Evet.

Mahkeme Başkanı : Anladım.

Maşşallah Güran : Onu karıştırdık.

Duruşma Savcısı : Yusuf Kaya kaçta geldi? O da Yeğeniniz değil mi Yusuf Kaya?

Maşşallah Güran : Yeğenim yani. Bir buçuk vardı. Onunla oğlum beraber iki iki buçukta çıktılar evden.

Duruşma Savcısı : Yusuf niye geldi eve?

Maşşallah Güran : Bize ekmek getirdi. Ekmeğim kalmamıştı. Eşim de evde değildi. Aradık, bize ekmek getirdi.

Duruşma Savcısı : Kahvaltı geç mi yaptınız?

Maşşallah Güran : Evet.

Duruşma Savcısı : Yani bir buçuk civarı mı yaptınız kahvaltı?

Maşşallah Güran : Kızlarım gelince beraber yaptık.

Duruşma Savcısı : Bir buçuk gibi.

Maşşallah Güran : Daha fazla, geç.

Duruşma Savcısı : Yani Beyanınızda saat 15 gibi Yusuf Kaya geldi diyorsunuz. Üç gibi.

Maşşallah Güran : Yok yok, üç gibi değil.

Duruşma Savcısı : Kaçta?

Maşşallah Güran : Hayır, ben sürekli demiştim.

Duruşma Savcısı : O Yusuf Musuf'u geç. Kahvaltıyı kaçta yaptın? Çok aslında basit bir soru.

Maşşallah Güran : Kahvaltıyı üç, üç buçukta falan yaptık yani.

Duruşma Savcısı : Değil mi? Evet. O şekilde beyan vermişsin.

Maşşallah Güran : Evet.

Duruşma Savcısı : Yusuf Kaya'nın üç gibi ekmek getirdiğini, Maide Kaya halan değil mi? Halasısın Maide'nin.

Duruşma Savcısı : Evet halası.

Duruşma Savcısı : Zelal'in?

Maşşallah Güran : Onun da teyzesiyim.

Duruşma Savcısı : Ha. İkisi bu çorap satma olayından dolayı 17 civarı geldiklerini söylüyorlar size. 17'de evden çıkıyor pardon. 17:30-17:40. O bölgelerde senin evinde olduğunu söylüyor çocuklar.

Maşşallah Güran : Tamam çorap getirdiler. Aynen. Ama saatin kaç olduğunu ben bilemem.

Duruşma Savcısı : Maide diyor ki, biz evdeyken kapıyı sadece Yusuf çaldı diyor. Yusuf o Eee. Ben sana beyanları söylüyorum. Cevap versene. 17-18 civarı sadece Yusuf geldi diyor. Yani Yusuf 17'de geldi diyor.

Maşşallah Güran : Sayın Savcım Yusuf benim yeğenim ayrıdır. Benim eşimin torunu ayrıdır. Yusufcan Güran ayrıdır. İki Yusuf var.

Duruşma Savcısı : İki Yusuf var. Evet. Saat 18 civarı gelen Yusuf Kaya diyorlar. Maide Yusuf Kaya'dan bahsediyor.

Maşşallah Güran : Yusuf Kaya'yı Maide görmedi.

Duruşma Savcısı : Anladım. O görmedi.

Maşşallah Güran : Zaten aldı oğlumu onlar beraber kahveye gittiler.

Duruşma Savcısı : Tamam. Bu sadece başkanım bir de iki tane telefon var, göstermek istedim. Uygun musun?

Mahkeme Başkanı : Tabii ki.

Duruşma Savcısı : Bu Birsen, ilk beyanında. Evet. İlk beyanında bu saat ikiyle alakalı Zerrin ablamla konuşuyordu annem diyor. On dört civarı.

Maşşallah Güran :  Onunla da konuştum.

Mahkeme Başkanı : Mikrofonu Savcı Hanım'a mikrofon verir misiniz?

Duruşma Savcısı : Saat iki gibi Zerrin ablanla HTS kayıtların bende. 13:32 civarı Taner Mehmetoğlu adına.

Maşşallah Güran : O da görümcemdir.

Duruşma Savcısı : Buradaki Zerrin hangisi? Zerrin ablan?

Maşşallah Güran : Benim eşimin kızıydı.

Duruşma Savcısı : Numara Zerrin yok?

Maşşallah Güran : Ben numara bilmiyorum.

Duruşma Savcısı : Anladım. 14 civarı bu görümcen mi? Taner Mehmetoğlu görümcen mi?

Maşşallah Güran : Onun adına olduğu için.

Duruşma Savcısı : Ha tamam o yani. Evet. Tamam. Burada Zerrin yok yani, değil mi? Burada şu an bu numaralarda?

Maşşallah Güran : Ben numara olarak bilmiyorum.

Duruşma Savcısı : Sen bunu biliyorsun ama bu görümcen. Bak bir şey söyleyeceğim. Dinle beni. HTS'nde sadece 13:32 var. 14'te görüşmen yok. Anlatabildim mi? Zerrin yok yani. Ben sana tek elimdeki 13:30'u soruyorum.

Maşşallah Güran : Zerrin değil. Bak Zerrin'le de konuşmuşum. Hangi saatte konuştuğumu bilmiyorum. Fatma ile görümcemdir.

Duruşma Savcısı : Ben kızını söylüyorum sana. Tamam. Bilmiyorum diyorsun.

Maşşallah Güran : Tamam. O da karıştırmış olabilir.

Duruşma Savcısı : Tamam. 17:40 gibi çok net saatler veriyor. O yüzden soruyorum. 17:40 gibi Hatice halamla konuşuyordu, Ben on dördü o yüzden karıştırdım diyor Birsen.

Maşşallah Güran : O Narin kaybolduktan sonra hepimiz karıştırdık.

Duruşma Savcısı : Hatice hala. Evet. Şu numaralara da bak. Bilmiyor musun?

Maşşallah Güran : Ben numara bilmiyorum. Okumam yazmam yok.

Duruşma Savcısı : Görümceyi nasıl tanıdın hemen?

Maşşallah Güran : Hani siz söylediniz ya?

Duruşma Savcısı : Tamam.

Maşşallah Güran : Ben görümcelerimle konuştuğum için söylüyorum.

Duruşma Savcısı : Numarayı görünce söylemedin?

Maşşallah Güran : Ama numara bilmiyorum.

Duruşma Savcısı : Numaraları bilmiyor musun?

Maşşallah Güran : Bilmiyorum.

Mahkeme Başkanı : Evet. Benim okuma yazmam yoktur. Bana göstermiş olduğunuz numaraları bilemiyorum. Ancak ben olay günü kiminle görüşmüşsünüz?

Maşşallah Güran : Görümcem. İki görümcem. Bir de Zerrin kızımızla konuştuk.

Mahkeme Başkanı : Zerrin kızımızla görüştük.

Av. Metin Arkaş : Şimdi Narin'in eve geldiğini, iki kez geldiğini söylüyor.

Mahkeme Başkanı : O mikrofon çalışmıyor mu? Ses geliyor mu? Bir baksanıza Mehmet Bey. Şarjı mı bitmiş. Aç kapa yap. Aç kapa da düzelmiyorsa bozulmuştur. Olmuş mu?

## Diyarbakır Barosu

### Av. Metin Arkaş

Av. Metin Arkaş : Şimdi Narin'in o gün eve iki kere geldiği yönünde beyanlarınız sonradan bir kere geldi şekline dönüyor. Bu beyanları da görümcemle, telefonla konuşuyordum. Kızlarım o saatle ilgili yorum yapınca sonra biz doğrusunu anladık. Narin aslında saat ikide eve geldi diyorsunuz. Halbuki bunlar telefon görüşme saatinizden bağımsız bir durum. Sizin ilk beyanınıza göre, hatta diğer beyanlarınızla da ilk önce saat iki civarında kapı çaldı. Kapı çaldıktan sonra kızım açtı, benim işim vardı. Birsen'e veya diğer kızıma sordum kim geldi diye, Narin geldi. Akşama doğru saat beşte tekrar kapı çaldı ve ben yine sol kapıya bakmadım. Kızlarım baktı. Kızlarıma kim geldi diye sorduğumda tekrar Narin geldi cevabını vermişler.

Mahkeme Başkanı : Bir dakika avukatımız bitirsin.

Av. Metin Arkaş : Bu imzalı, imzalı ifadenizde yer alan bir şey. Yani sizin saati karıştırmanızdan ziyade kapı kapandıktan hemen sonra iki kere sorduğunuz ve iki kere Narin cevabını aldığınız bir durum var. Bu yöndeki ifadeyi neden verdiniz?

Maşşallah Güran : O karışıklık oldu. Narin kaybolduktan sonra Mina geliyor o saatte. Tekrar söylüyorum Mina geliyor. Narin kaybolduğu sırada artık hep Narin kafamda kaldığı için Narin diyorum.

Av. Metin Arkaş : Kapı kapanır kapanmaz. Kızınız aslında Narin geldi dememiş miydi?

Maşşallah Güran : Bana dediler Mina geldi. Dedi. Mina geldi kafamdan çıkmış. Narin kaybolduktan sonra benim tamamen Mina aklımdan çıkıyor. Tamamen çıkıyor. Hep Narin aklımdadır.

Av. Metin Arkaş : Salim sizin evinize geldiğinde o gün bir telefon görüşmesi yaptı mı evde? Gördünüz mü?

Maşşallah Güran : Ben o sırada dışarıda değildim. Yukarı çıktım. Zaten geldi amcasının elini öptü, halasının elini öptü. Bizi de sordu. Biz Mersin'den gelmiştik. Ben o sırada oyla oğlu beraberdi. Ben yukarı çıktım, geldiğimde yoktu. Yani beş dakikada sürmedi kapıda durdu.

Av. Metin Arkaş : Narin kaybolduktan sonra aramalara başladıklarında Enes sizin evinize Narin'i sormaya geldi mi?

Maşşallah Güran : Yok. Yüksel beni çağırdı.

Av. Metin Arkaş : Enes gelmedi?

Maşşallah Güran : Yok Enes'i ben görmedim. Ben onu görmedim.

Av. Metin Arkaş : Yüksel size tepeden seslendiğinde, Yüksel kızını yeni bu saatte mi arıyorsun şeklinde bir cevap vermişsiniz. Normalde.

Maşşallah Güran : Eşim kızdı ona.

Av. Metin Arkaş : Normalde Narin ve diğer çocuklar evlere kaç gibi gidiyor? Sizin kızınız da küçük. Oynadığında eve kaç gibi geliyor?

Maşşallah Güran : Yani annesinden izin alırsa geç saatte de evine gidiyor. Benim evimde olduğu için annesi rahattır. Ben de kızlarımı göndersem evine rahattır. Hani biz birbirimize gönderiyoruz çocuklarımızı.

Av. Metin Arkaş : Sık sık gelirdi çocuklarınız?

Maşşallah Güran : Evet. Sürekli de bırakıp Batman'a da giderdi. Bir yasa da olsa giderdi. Hani bana bırakıp gidiyordular.

Av. Metin Arkaş : Peki annesinin Narin'i size gönderdiği zaman geldi mi şeklinde hiç teyit eder miydi? Arar mıydı sizi? Vardı mı? Geldi mi? Ya da siz gönderdiğinizde?

Maşşallah Güran : Yok bende olsaydı, rahattı. Biliyordu. Ben bırakmam. Biliyordu bırakmam. Ama o gün Narin bize geldi. Yani geldiği zaman hani kızlarımı sormak için geldi. Camiye gitti. Daha ben Narin'i görmedim.

Av. Metin Arkaş : Narin kaybolduktan sonra siz Yükselgilin evinde bir halı yıkaması, battaniye yıkaması, bir genel temizlik gördünüz mü?

Maşşallah Güran : Yok.

Av. Metin Arkaş : Yok.

Mahkeme Başkanı : Teşekkür ederim.

### Av. Aydın Özdemir

Av. Aydın Özdemir : Siz o gün kadınlar arasında olan tartışmanın hiç olmadığını mı söylüyorsunuz yoksa hani ben duymadım mı diyorsunuz? Böyle bir tartışmaya siz mi şahit olmadınız yoksa hiç olmadı mı?

Mahkeme Başkanı : Oldu dedi ya.

Maşşallah Güran : Olduğunu söyledim ya.

Mahkeme Başkanı : Oldu dedi. Tartışma oldu.

Av. Aydın Özdemir : Nesrin Güran'ın bir hakareti oldu mu sizinle beraber?

Maşşallah Güran : Hayır.

Av. Aydın Özdemir : Bir yere dönüp bir şey söylediği, hakaret ettiği?

Maşşallah Güran : Nesrin Güran o lafları ağzına almaz.

Av. Aydın Özdemir : Almaz. Peki. Birsen kızınız, Birsen size "Salim bize saat 17:40'da kızı gördüğünüzü söyleyin. Narin'i gördüğünüzü söyleyin. Yoksa sıkıntı çıkar" gibi bir şey söyledi mi?

Maşşallah Güran : Hayır.

Av. Aydın Özdemir : Gözaltı sürecinde kaldınız. Kaç gün beraberdiniz?

Maşşallah Güran : Gözaltı süreci...

Av. Aydın Özdemir : Aile içindeydiniz.

Maşşallah Güran : O ayrı işte, benim 56 günümdür. Ben cezaevindeyim.

Av. Aydın Özdemir : Kızınızla bahsettiğim şey şu. O süreçte gözaltında ve önceki süreçte kızınız, kendi öz kızınız.

Maşşallah Güran : Evet.

Av. Aydın Özdemir : Onun açık bir beyanı var. "Salim bize 17:40'da gördüğünüzü söyleyin. Yoksa sıkıntı çıkar." Saatlerle ilgili de siz tutuklanmışsınız. Yani tutuklanma gerekçeniz bu. Hiç böyle bir görüşme yapmadınız mı?

Maşşallah Güran : Salim'le mi?

Mahkeme Başkanı : Bu soruyu da sordum. Bu soruyu da sordum.

Mahkeme Başkanı : Çok net sordum. Çok net sordum hem de.

Av. Aydın Özdemir : Son sorum Arif'le Nevzat arasında bir problem olduğunu köyde hiç duydunuz mu?

Maşşallah Güran : Ben duymadım. Ben evde değildim.

Av. Aydın Özdemir : Peki kaç yıldır orada yaşıyorsunuz köyde?

Maşşallah Güran : Doğduğumdan beri ben.

Av. Aydın Özdemir : Doğduğundan beri. Bir husumet olsa, bir sıkıntı olsa kapalı bir toplum duymaz mıydınız? Duyarsınız.

Maşşallah Güran : Duyarım.

Av. Aydın Özdemir : Teşekkürler.

Mahkeme Başkanı : Ben teşekkür ederim. Şimdi Maşallah hanım. Arif'in Narin size geldiğinizde, geldiğinde kızlarınızla oynamak için Arif Yüksel geldi mi diye sizi arıyor muydu?

Maşşallah Güran : Telefonla değil. Onu mu diyorsunuz?

Av. Aydın Özdemir : Yok yok genel. Bir hafta önce bir ay önce rutin, hani bu rutin geliyordu ya ben de kendi çocuğumu karşı komşuma gönderiyorum. Sizler de gönderiyorsunuz. Yani burada Arif Narin'in size eve geldiğini nasıl teyit ediyordu onu merak ettim.

Maşşallah Güran : Hani annesinden izin alır öyle gelir.

Mahkeme Başkanı : O gelince Yüksel takip eder miydi annesini?

Maşşallah Güran : Tabi Yüksel takip ederdi kızını.

Mahkeme Başkanı : Nasıl takip ediyordu?

Maşşallah Güran : Bir anne evladını takip etmez mi?

Mahkeme Başkanı : Akşam akşam karanlık olunca Narin nasıl dönüyordu eve?

Maşşallah Güran : Çocuklarım karanlık olduğu zaman ya oğlum bırakıyor ya iki kızım onu bırakıyordu.

Mahkeme Başkanı : Ha öyle. Öyle bırakıyordu gidiyordu eve. Öyle bırakıyor.

Maşşallah Güran : Öyle.

## Aile ve Sosyal Hiz. Bakanlığı

### Av. Elif Aslı Şahin Torun

Av. Elif Aslı Şahin Torun : 12.09 yani 12 Eylül tarihli beyanınızda olaydan 20 günden fazla geçmiş. Diyorsunuz ki, 17:40'da Narin eve gelmişti. Bu 17:40'ın 40'ına varasıya kadar nasıl aklınızda kaldı? 40'ın sizin için önemi ne?

Mahkeme Başkanı : Avukat Hanım bunu da sordum geçiyoruz. Sordum çok net 3 kere sordum geçiyorum. Sordum geçiyoruz.

Maşşallah Güran : Sorabilir yani.

Mahkeme Başkanı : Sordum sordum. Geçiyoruz, sorduk.

Av. Elif Aslı Şahin Torun : Olay günü Yüksel Saat 7'de orada mı konuşuyor? Enes ya da Muhammed var mıydı? Ya da başka birileri var mıydı?

Maşşallah Güran : Yüksel beni çağırdığı zaman eşim vardı. Görümcem vardı.

Av. Elif Aslı Şahin Torun : Yüksel'in yanında birisi var mıydı?

Maşşallah Güran : Yok tekti. Başka kimse yoktu.

Av. Abdullah Yılmaz : Şimdi Sayın Başkan öncelikle bir konuyu düzeltmek isterim. Sizden de bir talebimiz olacak. Sürekli işte bu sorular soruldu diye sanık müdafilerden de sizden de şey geliyor ama bence çapraz sorgunun mantığı da bu, yani sorular farklı şekilde aynı sorular da olabilir bunlar. Biz her tanığa aynı soruyu da sorabiliriz açıkçası. Çünkü zaten bir tanık dinleniyor, diğer tanıklar dinlenmemiş oluyor henüz. Yani dolayısıyla bu soru soruldu demek.

Mahkeme Başkanı : Evet bunu da reddediyorum. Bir tanığa bir kere soru sormanın yeterli olduğunu düşünüyorum. Bunu da reddediyorum avukat bey. Buyurun.

### Av. Abdullah Yılmaz

Av. Abdullah Yılmaz : Maşallah Nevzat Bey'in de, Nevzat Bahtiyar'ın size yönelik bir iddiası oldu. Bu konu hakkında siz ne düşünüyorsunuz? Salim Bey'le ilgili.

Maşşallah Güran : Ben onu kabul etmiyorum. Onu kabul etmiyorum önce kendi çevresine baksın. Aynasına baksın. İnsan iftiranın arkasına saklanmaz. İftira atmaz.

Av. Abdullah Yılmaz : Sizce niye iftira attı size? Aranız kötü muydu?

Maşşallah Güran : Yok.

Av. Abdullah Yılmaz : Niye böyle bir iftira attı?

Maşşallah Güran : Kendisine sorun.

Av. Abdullah Yılmaz : E sorduk ona da sorduk.

Maşşallah Güran : E tamam kendisine tekrar sorun. Bu iftirayı niye atıyor? Bir insan iftira atmaz. Şerefiyle, namusuyla düzgün konuşur. İftiranın arkasına saklanmaz.

Av. Abdullah Yılmaz : Peki bak Narin kayboluyor, katlediliyor, 19 gün sonra bulunuyor. Bu 19 gün içinde bir sürü dosyada olay oluyor. Yangın çıkıyor, elektrikler gidiyor, çelişkili beyanlar var. Sadece iki tane kızınız Melike ve Birsen'nin üç tane farklı ifadesi var. Sizin farklı ifadeniz var. Hepsi de birbiriyle çelişkili. Dolayısıyla siz hiç böyle bir şüphe uyandıracak, kimin yaptığına dair bir şey konuşmadınız mı? Mesela Birsen Hanım'la konuşmadınız mı kızınızla?

Maşşallah Güran : Yani konuşma...

Av. Abdullah Yılmaz : Ya bu kızı kim niye öldürdü mesela? Hiç düşündünüz mü?

Maşşallah Güran : Ben, Narin'i mi?

Maşşallah Güran : Yani hiç düşünmedik. Yani sordular hani kimi düşünüyorsunuz? Köyde hiç aklımıza biri gelmedi. En sonunda kaçırıldı zannettik. Ama dibimizdeydi, biz bilmiyorduk.

Av. Abdullah Yılmaz : Kim öldürdü sizce? Nevzat mı?

Mahkeme Başkanı : Bu soruya da cevap vermeme hakkına sahipsin. Yok cevap verme olmaz. Bu kadar şeyleri suç ve delilleri olmuyor. Cevap almıyorum.

Av. Abdullah Yılmaz : Şimdilik bu kadar başkanım.

Mahkeme Başkanı : Ya şimdi ben sizi anlayışla karşılıyorum. Dün de buna gayet de izin verdiğimi de düşünüyorum. Aynı soruyu on kere sorduğunuzda, bunu ben sordum, bu taraf sordu, bu taraf sordu, o taraf beşer kere... Yok yok, soruldu. Hassasiyet gösterdi, göstermedi. Tenkit manasında değil, savunma manasında da değil. Dün bunu yaptım. Ama bugün ilk başlangıçtan sonraki vaziyetten sonra fikrim değişti. Artık izin vermiyorum. Ben sorduğum sorunun cevabını aldıktan sonra sizin farklı bir cevap almanız diye bir şey yok.

Sanık Enes Güran : Yenge işte diyorsun ya tepeye çıkmış. O zaman ben de annemin yanındaydım. Muhammed de yanındaydı. Bizi gördün mü yoksa?

Maşşallah Güran : Tepede? Annem beni çağırdığı zaman. Ben o esnada görmedim kurban olayım sana. Görmedim.

Sanık Enes Güran : Tamam.

Sanık Salim Güran : Sanık Maşşallah Güran amcamın eşidir. Benim amcam, baba yarısı değil, benim babamdır. Bize bakmış, bize yedirmiş. Bu iftirayı atan, Allah belasını versin, cehennem ateşine yansın.

Mahkeme Başkanı : Soru, soru, soru. Soru yok. Teşekkür ederim. Soru alacağız. Buyurun sanık müdafinden avukat bey.

## Sanık Enes Güran Müdafileri

### Av. Mahir Akbilek

Av. Mahir Akbilek : Maşallah hanım Enes'i, bu arama tarama faaliyetleri esasında ilk hangi gün, hangi saatlerde gördüğünüzü hatırlıyor musunuz?

Maşşallah Güran : Narinin kaybolduğu gün mü?

Av. Mahir Akbilek : Evet, onu baz alın. Ondan sonra 21'inde mi gördünüz, 22'sinde mi? 21'indeyse saat kaç aralığında, 22'sindeyse ilk gördünüz?

Maşşallah Güran : 20'sinde zaten biz yeni Mersin'den gelmişiz. Kızımın kaydı için gitmişiz. O yol yorgunluğu 21'inde de bu olay olunca hani Enes'i ben görmedim. Gün içinde ben onu görmedim. Enes'i beni çağırdığı zaman onu o zamanda gördüm. Yüksel'i tek gördüm. Hani yukarıda olabilir ama ben Yüksel'i tek gördüm. Çünkü aramızda ağaç vardı. Görmedim ben.

Av. Mahir Akbilek : Ne zaman?

Maşşallah Güran : Hani saat Yüksel beni çağırdığı zaman yedi, yedi buçuktu.

Av. Mahir Akbilek : Hayır, Enes'i gördüğünüz zamanı bir hatırlayın.

Maşşallah Güran : Kaybolduğu sırayı söylüyorsunuz. Narin'in kaybolduğu sıra.

Av. Mahir Akbilek : Bugünden geriye gidin, Narin'in katledildiği güne kadar Enes'i ilk gördüğünüz anı bir hatırlayın. Yüzü böyle karşı karşıya gördüğümüz gibi.

Maşşallah Güran : Ben okulun yanında gördüm. Narin'i aradığımız sırada ben gördüm.

Av. Mahir Akbilek : Hangi gündü?

Maşşallah Güran : İlk kaybolduğu gün.

Av. Mahir Akbilek : Tamam. Enes'in yüzünü, vücudunu gördünüz mü?

Maşşallah Güran : Tabii.

Av. Mahir Akbilek : Yüzünde gözünüze çarpan bir yara, bere, kanama?

Maşşallah Güran : Ben görmedim.

Av. Mahir Akbilek : Teşekkür ederim.

Mahkeme Başkanı : Ben teşekkür ederim. Evet Maşallah hanım. Teşekkür ederiz. Soru varmış. Buyurun. Ben bitti zannettim.

Av. Mustafa Demir : O gün telefonla konuştuğunuzu söylüyorsunuz ya. Sadece kendi telefonunuzla mı konuştunuz yoksa?

Maşşallah Güran : Yok. Kızımın telefonuyla da konuştum. Ben konuşurum.

Av. Mustafa Demir : Yani o zaman bu arama kaydının orada anlaşılmama sebebi bu olabilir mi? Yani kızınızın telefonuyla konuştunuz o gün değil mi?

Maşşallah Güran : Evet. Kızımın telefonuyla konuştum. Kendi telefonumla konuşmuşum. Oğlumun telefonuyla konuşmuşum.

Av. Mustafa Demir : Bir gün önce Mersin'e geldiğinizi söylediniz.

Maşşallah Güran : Evet.

Av. Mustafa Demir : O gün sizin eve gelen giden çocukların sayısını hatırlıyor musunuz? Ne sıklıkla gelindi?

Maşşallah Güran : Ben normalde çocuklar hep evime gelir. Çocukları severim. Çocukları seviyorum.

Av. Mustafa Demir : O gün özelinde soruyorum, şundan dolayı. Zaten sizin evin konumu dolayısıyla sizin evden öteye galiba yol bir yere gitmiyor. Yani okulun önünden geçen yoldan ilerleyince sizin eve geliniyor.

Maşşallah Güran : Evet.

Av. Mustafa Demir : Kameraya baya hareketli Evet.

Maşşallah Güran : Çocuklar geliyor evime.

Av. Mustafa Demir : Sizin eve o gün çok sık çocuk geliş gidişi oldu mu? Bunu soruyorum.

Maşşallah Güran : Oldu.

Av. Mustafa Demir : Evet teşekkür ederim.

### Av. Fatih Demir

Av. Muhammed Fatih Demir : Gazal Bahtiyar'ı tanıyor musunuz?

Maşşallah Güran : Evet. Komşumdur.

Av. Muhammed Fatih Demir : Aranız nasıl? Ondan iletişiniz nasıl?

Maşşallah Güran : Yani.

Av. Muhammed Fatih Demir : Olaydan önce.

Maşşallah Güran : Olaydan önce iyiydi. Geliyordu, gidiyordu. Ben bahçemi veriyordum. Bahçemi ekiyordu. Hani aramız iyiydi.

Av. Muhammed Fatih Demir : Narin ve Sizin çocuklarınız genelde nerede oynardı köyde? Yani okulun önünde mi? Cami tarafında mı?

Maşşallah Güran : Okulun önünde de olurdu. Caminin önüne de giderdi. Annemgile de giderdi. Yani her yere rahatlıkla çocuklarımız giderdi köyümüzde.

Av. Muhammed Fatih Demir : Peki olaydan son 3 aylık süre zarfı içerisinde Gazal Bahtiyar'ın veya Nevzat Bahtiyar'ın Narin'i görmeme ihtimali var mı?

Maşşallah Güran : O gün mü?

Av. Muhammed Fatih Demir : O günden önceki bir ay, iki ay, üç ay, fark etmez.

Maşşallah Güran : Nasıl görmez? Aşağı inse görür. Tepeye çıksa görür. Nasıl görmez?

Av. Muhammed Fatih Demir : Peki. Nevzat Bahtiyar ailesi ile Arif Güran ailesi arasında bir sorun var mıydı? Araları nasıldı olaydan öncesini soruyorum.

Maşşallah Güran : Yani hiçbir sorun yoktu.

Av. Muhammed Fatih Demir : Sorun yoktu.

Maşşallah Güran : Yoktu. Bildiğim kadarı yoktu.

Av. Muhammed Fatih Demir : Peki Narin için soruyorum. Rahmetli için soruyorum. Nevzat Bahtiyar yabancı biri miydi?

Maşşallah Güran : Efendim.

Av. Muhammed Fatih Demir : Narin için yabancı biri miydi? Yoksa amcası gibi görür müydü onu? Yani sever miydi onu?

Maşşallah Güran : Yani torunları olduğu sırada torunlarını severdi. Giderdi.

Av. Muhammed Fatih Demir : Yani o zaman Nevzat Bahtiyar Narin'e gel dese gider miydi Narin? Nevzat amca merhaba, selam der miydi ona?

Maşşallah Güran : Yani görmediğim için buna bir şey diyemem.

Av. Muhammed Fatih Demir : Görmediniz. Görmediğiniz bir bilgiyi sizden istemiyorum. Fakat köyde olduğunuz için tahmin edebilirsiniz. Yani genel bir durumdur.

Mahkeme Başkanı : Tahmin almayalım. Görmedim dedi.

Av. Muhammed Fatih Demir : Teşekkür ederim.

Mahkeme Başkanı : Ben teşekkür ederim.

## Sanık Yüksel Güran Müdafileri

### Av. Furkan Çakır

Av. Furkan Çakır : Yüksel Güran ile aranız nasıldı?

Maşşallah Güran : Aramız çok iyi. Hepsiyle iyi.

Av. Furkan Çakır : Peki olay gününden önce ve sonra Yüksel Güran'da böyle hiç olağan dışı bir hareket, olağan dışı bir davranış sezdiniz mi?

Maşşallah Güran : Beni çağırdığı zaman da normal haliyle beni çağırdı. Her gün çağırdığı gibi beni çağırdı.

Av. Furkan Çakır : Tamam. Şimdi 08.09.2024 tarihinde jandarma personelinin tutmuş olduğu bir tutanak var. Söz konusu tutanakta bir yorumlama var. Yani bu savunma makamı olarak bizim görüşümüzdür. Yorumlamanın da yorumlaması iddianameye geçirilmiş. Şunu soruyorum sadece. Tartışma yaşandığı esnada Yüksel Güran orada mıydı? Ya da Yüksel Güran söz konusu tartışma esnasında bir sinir krizi falan geçirdi mi? Bu olayı bize tam detaylı anlatabilir misiniz?

Maşşallah Güran : Yüksel Güran bayıldı. O tartışma olmadan önce o bayıldı. Onu ambulansa aldık. Ambulansa aldık. Yerime geçtim. Sonra bu tartışma oldu.

Av. Furkan Çakır : Tamam. Teşekkür ederim.

Maşşallah Güran : Yüksel orada değildi.

Mahkeme Başkanı : Tamam. Çok sağ olun.

### Av. Tuncay Erkuş

Av. Tuncay Erkuş : Ya gerçi duyumdan ibaret de olabilir ama dedirtmek için soruyorum. Arif ile Nevzat Bahtiyar arasında araç ticaretinden kaynaklı bir sorun yaşanmış. Cemaat Nevzat Bahtiyar'a bir ceza kestiği söyleniyor. Yani bir para verme olayı ona yüklenmiş. O da parayı verdikten sonra ev içerisinde bir huzursuzluk yaşanmış. Daha sonraki zamanlarda sizin evinizden Gazal Bahtiyar yani Nevzat Bahtiyar.

Mahkeme Başkanı : Soruyu bir bitirsin de.

Av. Tuncay Erkuş : Sizde bulunduğu bir anda hakkımı helal etmiyorum. Biz bu parayı verdik. Zor durumda kaldık. Hakkımızı helal etmiyoruz gibi bir söylemden de ibaret olabilir ama sizin evinizde bu olayın yaşandığı söyleniyor. Böyle bir olay yaşandı mı?

Maşşallah Güran : Kesinlikle. Kesinlikle benim evimde bu hayır. Benim evimde yaşanmadı bu.

Av. Tuncay Erkuş : Gazal Bahtiyar bu parayı verdiğimiz için biz hakkımızı helal etmiyoruz. Yani istemvari bir söylem oldu mu sizin evinizde böyle bir.

Maşşallah Güran : Ben hatırlamıyorum onu. Ben evde değilim. Bir buçuk ay ben evde değilim.

Av. Tuncay Erkuş : Küçük Narin'in kaybolmasından sonra yine böyle kadınların bulunduğu size ziyarete gelen kadınların arasında Gazal Bahtiyar "Biz zaten buradan gidiyoruz. Evimizi taşıyacağız. Başka bir ile gideceğiz. İstanbul'a gideceğiz" gibi bir şey oldu mu?

Maşşallah Güran : Kaybolduğu zaman mı?

Av. Tuncay Erkuş : Kaybolduktan sonraki tarihlerde yani birkaç gün sonra olabilir. Bir hafta sonra olabilir.

Mahkeme Başkanı : Yani Gazal böyle bir şey söyledi mi?

Maşşallah Güran : Yok.

Mahkeme Başkanı : Tamam. Teşekkür ederim. Ben teşekkür ederim.

Maşşallah Güran : Hatta bunu söylemek istiyorum.

Mahkeme Başkanı : Tabii ki.

Maşşallah Güran : Yangın çıkmadı. Hani çıkmamıştı. Ondaki bir önce gün biz Yüksel'lerdeydik. Öyle oturdu konuştu. Ben rüya görmüşüm. Çilye yani Tavşantepe yanıyordu. Hatta ağladı. Sigara da istedim. Sigara da verdim ona. Hani sonraki gün köy yandı. Böyle bir şey olur mu?

Mahkeme Başkanı : Olur. Niye olmaz? Rüyalar alemi diye bir şey var. Yani ben rüyalara inanırım. Hani mahkeme başkan rüyalara inandı değil de ben inanırım yani. Siz inanmıyorsunuz mu?

Maşşallah Güran : İnanırım.
