---
title: "Baran Güran İfadesi"
editor: source
---

## Mahkeme Başkanı

Mahkeme Başkanı : Duruşmaya başlıyoruz. Öncelikle Yüksel senin annen. Enes senin kardeşin, Salim de senin amcan oluyor. Bu yüzden dolayı tanıklıktan çekilme hakkına sahipsin. Yani tanıklık yapmama hakkına sahipsin.

Baran Güran : Yapabilirim.

Mahkeme Başkanı : Tanıklık yapmak istiyor musun?

Baran Güran : Evet.

Mahkeme Başkanı : Tanıklık yapmak istiyorsun. Biz seni yeminsiz olarak dinliyoruz. CMK'ya göre. Evet Baran. Öncelikle genel olarak bu olaylar hakkında ne söylemek istesin? Neye şahit oldun? Seni bir dinleyelim.

Baran Güran : Yani ben de bilmiyorum. Nasıl böyle oldu olaylar? Nasıl buraya geldi? Nasıl böyle gelişti? Benim hiçbir fikrim yok o konuda.

Mahkeme Başkanı : Peki, sen neredesin? Ne iş yapıyorsun?

Baran Güran : Ben iş makinesi operatörüyüm.

Mahkeme Başkanı : Nerede çalışıyorsun? Erzurum'da çalışıyorsun. Erzurum'da.

Baran Güran :  Başkale evet.

Mahkeme Başkanı : Olay günü neredeydin?

Baran Güran :  Diyarbakır'daydım.

Mahkeme Başkanı : Diyarbakır'daydın. Bir dakika. Sen, bu Narin kızımızın kaybolduğunu ne zaman öğrendin?

Baran Güran : Akşam 7-8 civarıydı galiba. Kardeşim Muhammed aradı beni.

Mahkeme Başkanı : Muhammed aradı. Sen de öğrenir öğrenmez jandarmaya mı haber verdin?

Baran Güran : Önce köye gittim.

Mahkeme Başkanı : Önce köye gittin.

Baran Güran : Önce caminin oraya gittim. Büyük bir kalabalık vardı. Oradan hiç durmadan yukarı çıktım. Evin oraya. Narin nerede falan dedim işte. Ondan sonra tam hani hatırlamıyorum 112 mi neydi aradım. Kayıp için aradım, hatta 105 miydi?

Mahkeme Başkanı : Evet.

Baran Güran : Aradım ondan sonra kanala öğrendik. Yani aklıma kanal geldi. Soğuduğu için kanala öğrendim.

Mahkeme Başkanı : Budur. Peki bu olaylardan sonra aile kendi arasında gizli toplantılar yapmış. Yani aile bireyleri arasında toplantılar yapılmış. Amcalarınız evlere kameralar kurulmuş. Böyle iddialar var. Bu konuda ne diyorsun?

Baran Güran : Sayın hakim, gizli bir toplantı olsaydı bu köyde mi yapılırdı? Herkesin göreceği şekilde mi yapılırdı? Yoksa gizli bir yere, Diyarbakır çok büyük bir yer. Ve bu olaylarda bazen bakanlar falan geliyordu. Köye ziyarete. Bakan geliyor, evi boşaltın diyordular. Misafirleri Batman'dan, Diyarbakır'dan gelen bütün misafirleri çıkarıyorduk. Orada da bakan geliyor konuşacaklar, evi boşaltın diyordu. Harici de kimseye özel bir toplantı var demedik de, olmadı da.

Mahkeme Başkanı : Öyle bir şey olmadı.

Baran Güran : Hani ben kendim şahit olmadım. Eğer çok özel bir toplantı olsaydı evimiz zaten aile bireylerinin bütün evleri kör nokta değil. Köylülerin göreceği şekilde bu kadar gizli yapılmış bir toplantı olsaydı, köyde de yapılmazdı bu.

Mahkeme Başkanı : Köyde yapılmazdı. Peki bu bir de kadınlar kavgası var.

Baran Güran :  Ben o gün orada çünkü ilk beni götürdüler atletifa. Ben kavga olduğu esnada orada değildim.

Mahkeme Başkanı : Orada değildiniz. Peki. Bu son adam bu kadınların neden kavga ettiği, amcalarınızın onların ağzını kapatmaya çalıştığı, bu konuda bilgi sahibi misin?

Baran Güran : Sayın hakim orada küslük bir melek olduğu için herkes çok sinirliydi. Herkesin içi yanıyordu. En ufak bir kelimede, yani herkes patlıyordu. Yani ben de defalarca aile bireylerimle hala tartıştım da yani. Bu konuyla ilgili değil ama mesela konu Narin olduğu için en ufak bir şeyde insan hemen patlıyordu. Bu sinirden dolayı.

Mahkeme Başkanı : Yani bu olay işte "Siz her şeyleri biliyorsunuz. Bizi konuşturmayın. Biz mi ne yaptık, sanki erkekler yaptı" gibi söylemler var. Bayanlar. Ya bu söylemler bir şey bildiklerinden dolayı değil de olayın patlamasından dolayı mı?

Baran Güran : Bence patlamasından dolayı. Yani zannetmiyorum sözünüzü kesiyorum hakimim. Eğer bilseydiler, inanırdım ki söylerdiler. Çünkü masum bir kız var ortada.

Mahkeme Başkanı : Peki onların malum yaklaşık 15-20 gün arası siz de bir arayış içerisindeydiniz. Onların bildiklerini bilseydiniz de buna dair bir izlenim elde eder miydiniz? Yani dün onu sormaya çalıştım. Hani bir dedikodusu duyulur köyde. İşte babanıza saatlerce binlerce insandan telefon gelmiş. Kızınız bende falan. Köyde de böyle bir şey duydum işte. Bu kız öldürüldü, şuraya gömüldü, bu kız kaçırıldı. Şu kaçırdı, Bahtiyar öldürdü, Nevzat öldürdü. Daha bulunmadan. Böyle bir bir şey duydunuz mu?

Baran Güran : Hayır Sayın Hakim. Öyle bir şey olmadı ama şöyle bir şey oldu. Olay günü köydeki bazı kişiler o gün köye bir tane suriyeli, mırtıp diyoruz, bir araba geldiğini söylediler. Bu en son Kur'an kursundan geldikten sonra yukarı çıktığında biz dedik acaba kaçırıldı mı? Çünkü aklımıza hiçbir şekilde öldüğüne dair bir şey gelmedi. Çünkü herhangi bir şeyimiz olmadığı için biz dedik belki birileri tarafından kaçırılmıştır. Bu da olayın ilk günü değil. Üç dört gün aradan geçtikten sonra ve şu mesela şeyh falan var diyorlar. Mesela böyle inançları olan insanlar var. Çaresizlikten dolayı onlara bile danıştılar. Ve %80'i şunu söylüyordu. Eğer rahmetli olmuş olsaydı, ben anlardım falan. Hep ümit veriyor, yaşıyor. Biri tarafından saklanıyor ve yaşıyor.

Mahkeme Başkanı : Yani bu kırmızı araba muhabbeti, Suriyeliler muhabbeti, Çingeneler muhabbeti, özellikle Salim'in iddia ettiği bunların köyde duyulanların, yani köyde böyle bir şey duyuyorsunuz, jandarmaya söylüyorsunuz.

Baran Güran : Evet.

Mahkeme Başkanı : Öyle mi?

Baran Güran : Evet, evet.

Mahkeme Başkanı : Yoksa sizin bizzat gördüğünüz bir şey yok.

Baran Güran : Bizzat şahit olmadık.

Mahkeme Başkanı : Her bilgiyi jandarmaya aktardığınız için bunlar da ortaya çıktı.

Baran Güran : Zaten ben de ben döndükten sonra da söyledim. Neden gidip onların etrafını sarmıyoruz? Neden arabalarına neden aramayı yapmıyoruz? Defalarca ben de söyledim. Çünkü yani Suriyeli bugün insanın aklına...

Mahkeme Başkanı : Yani şimdi insan aklına değil. Yani şimdi bir kardeşin kaybolmuş. Öldüğüne daha kanaat getirmemişsiniz, ayın ilk günü.

Baran Güran : Evet.

Mahkeme Başkanı : Ya her taşın altına bakmanız gayet doğal hakkınız. Bu insani bir vaziyettir. Ancak sonradan bu olaylar şüpheli olarak addedildiği için biz bu hususu size soruyoruz. Hani bunların duyumunu nasıl aldınız diye?

## Diyarbakır Barosu

### Av. Nahit Eren

Av. Nahit Eren : Günaydın. Ben de salondaki herkese günaydın demek istiyorum. Başkanım ben dün bir şey konuşmuştum, duruşmadan önce. Bir küçük giriş yapacağım.

Mahkeme Başkanı : Olur.

Av. Nahit Eren : Söz alamadık duruşmadan önce. Çünkü Baran'a bunları söyleyerek başlamak istiyorum. Tıpkı annesi gibi. Şimdi dün biz sorgu yaparken sen dışarıdaydın. Dışarıdaydın. Tanık olarak kapının önünde bekliyordun. Ben Salim Güran'ın sorgusu yapılırken bir şeyler sordum. Yanlış da olabilir, eksik de olabilir. Tabii ki savunma hakkına da saygı duyuyoruz. Meslektaşlarımız orada. Bana sen neyin peşindesin dedi. Böyle bir soru sordu. Daha doğrusu benim soruma böyle bir çıkış yaptı. Ben önce neyin peşinde olduğumuzu izah etmek isteyeceğim. Çünkü biz Baran'la birlikte Adli Tıp'ın önündeydik. Oraya da geleceğim. Çünkü Baran'ın da onun benim peşinde olduğum şeyin peşinde olduğunu hissediyordum, düşünüyordum. Duygum oydu. Ben neyin peşindeyim? Biraz Arif Bey, lütfen, lütfen ben de bir babayım. Ama ben bunu söylemezsem, ben bunu anlatmasam bu duruşma salonunda galiba kuruyan vicdanlar açılmayacak, konuşmayacak. Ben neyin peşindeyim? Hayatın en güzel kokusuna sahip olan bir çocuğun bütün bir binaya üç savcı, on dört çalışan ve bu soruşturmayı yürüten bütün savcılarla üç maske takarak hayatımızda unutamayacağımız bir kokuya tanık olan insanlar. Dördüncü günü ben bu adliyedeyken orada bulunan bir tane kolluk görevlisi bana ne dedi biliyor musun? O koku hala üzerinizde dedi başkanım. Ben bunu hayatım boyunca unutmayacağım. O gün, biz işte neyin peşindeyiz biliyor musun? Hayatında en güzel kokuya sahip olan bir çocuğun getirildiği hale karşı bugün mücadele veriyoruz, adalet mücadelesi veriyoruz. Neye mal olursa vereceğiz. Bu yaşamımıza da mal olsa vereceğiz. Ben bunu bugün bu salonda söylüyorum çünkü dün bu salonda bağıranlar da oldu. Bir kez daha ifade ediyorum. Ben üç çocuk babasıyım. Üç kız çocuğumun babasıyım. Kızların ne olduğunu o kadar iyi biliyorum ki. Erkek çocuğum olsun diye beş altı erkek çocuğunuz var. Allah bağışlasın. Var ya eşimin üçüncü doğumunda kendisiyle gitmedim. Benden sebep olabilir diye gitmedim. Doktor muayenesine gittiği zaman şimdi onun da kız olduğu için o kadar mutluyum ki. Hani belki bendendir. Üçüncüsü erkek olur diye düşünüyorduk. Öyle bir duygumuz var ya bizim. Bak erkek çocuğumuz da olsun diyor. Ben bunu niye anlatıyorum Baran? Adli Tıp'ın önündeydik, savcılarımız üç tane savcımız var bu soruşturmayı yürüten, eksik, iyi, kötü bir şekilde bir iddianame hazırladılar. Sana teşhis yaptıracaktılar. Ben o teşhise müsaade etmedim. Dedim ki, bir abi bu çocuğu bu halde görmesin dedim. Bu kokuyu almasın. Narin'in o küçükken bildiği her gün öperken kokladığı kokusuyla kalsın dedim. Sana göstermede çok ısrarcı oldun. Dışarıda yanına geldim. Baran görme, daha iyi dedim. Ama ben eminim ki, dışarıya gelen kokuyu sen de alıyordun Baran. Alıyordun değil mi Baran? Alıyordun. O yüzden ben neyin peşindeyim? Buna sebep olanların peşindeyim. Diyarbakır Barosu'nun avukatları bunun peşinde. 16 tane avukat, tamam.

Katılan Arif Güran : Anlaşılmayan bir şeyler söylüyor.

[Sanık müdafileri, katılan vekil tarafı, sanık yakınları, izleyiciler tarafından seslerin yükselmesi ve ayırt edilememesi karşısında zapta aktarılamadı.]

Av. Nahit Eren : Bir kez daha özrümü aileden Narin'e ilişki yaptığımız değerlendirmenin yaptığı duygusal manevi tepki olduğunu düşünerek özür diliyorum. Eğer o tepkiyse özür diliyorum. Oradan soruma geçiyorum. Biz senden Adli Tıp'ın önündeyken naaşın defniyle ilgili gelip bir görüşme gerçekleştirdik. Narin'in defniyle ilgili ve Narin'in nereye defnedileceği konusunda bir karar verilmesi gerektiğini söyledik. Ben bu konuda yanında kolluk görevlisi de vardı. Otururken bir soru sordum. Baran genel anlamda Narin'in hani köye götürülüp defnedilmesi konusunda yaygın bir itiraz var. Farklı bir yerde defnedebilir miyiz? Öyle bir talebe sen ne dersin? Karar şu an dosyada tutuklu olmayan, daha doğrusu gözaltında olmayan tek kişi sensin. Dedim sen bana oradan ne cevap verdin Baran? O cevabı bir kez daha dinlemek istiyorum.

Baran Güran : Ben öncelikle zaten ilk baştan beri Narin'i kendi köyüne götürecektim. Bu bir gerçekti. Tabii orada milletin tepkisi vardı. O benim de umurumda değildi. Ne olursa olsun, kendi köyüne götürecektik. Ama orada sayın savcım bana dedi ki, sen nereye? Bu soruyu bana bir iki kere sordu. Nereye, nereye dedi. Ben de o an dedim, zaten belli ama isterseniz babamla görüş. Hani onlar da beni babamın yanına gönderdiler.

Av. Nahit Eren : Benim sorduğum soruya verdiğin cevabı rica ediyorum.

Baran Güran :  Ben hatırlamıyorum.

Av. Nahit Eren : Tam nerede? Görüşmedik mi bu konuyu seninle? Hatırlamıyor musun?

Baran Güran : Yok. Narin'i zaten köye götüreceğimizi söylemiştik.

Av. Nahit Eren : Ben bir bana kurduğun bir cümleyi hatırlatmak istiyorum.

Baran Güran : Hatırlatın.

Av. Nahit Eren : Belki hatırlarsın. Dedim ki, dışarıda amcaların var. Aile büyüklerin var. İstersen bir onlara danış. Bütün köyde ileri gelenleriniz burada. Aile anlamında. Köy tanımını aile için kullanıyorum. Bunun üstüne bana bir cevap verdin.

Baran Güran :  Ne dedim?

Av. Nahit Eren : Hatırlatmamı istersen hatırlatabilirim.

Baran Güran : Ya hatırlat ama bence verdiğim cevap babamla bu konuda...

Av. Nahit Eren : Dedin ki, benim ve babamın dışında hiçbir aile bireyinin söz söyleme hakkı olmayacak dedin.

Baran Güran : Öyledir zaten. Biri abi.

Av. Nahit Eren : Hangi manada söylediğini ben merak ediyorum?

Baran Güran : Sana şöyle cevap veririm abi. Bunu tamamen yanlış yere çekiyorsun.

Av. Nahit Eren : Hayır hayır, yok. Hayır hayır.

Baran Güran : Ben abi lafımı kesme bitireyim. Yanlış yere çekiyorsun. Orada ben zaten tek bırakıldım. Ailem kapının önünde olduğu halde ailemden hiçbir bireyi içeriye alıp yanıma destek vermediniz. Bir abiyi bir kız kardeşinin önünde belki yedi saatten fazla beklettiniz ve içeriye kimseyi almadınız. Tek başıma o Adli Tıp'ın önünde bekledim. 10'a kadar aile bireylerimi istedim. Vermediniz ki kapıdaydılar zaten. Orada da yaralı bir abi olarak ve yaralı zaten annem o ara bildiğim kadarıyla alınmıştı sabah. Gelemeyeceğini de biliyordum oraya aslında. Ben de dedim ki, bu konuda ben ve babam karar verir. Aile bireyleriyle alakası değil.

Av. Nahit Eren : Bu anlamda yani ben anlamını yani bu anlamda yani ailenin büyüğü biziz. Biz sadece karar verebiliriz.

Baran Güran : Aile büyükleri, biz demedik. Aile büyüklerimiz ayrıyeten var. Benim orada demek istediğim sadece şuydu. Eğer siz orada bir abi tek başına altı yedi saat durdurduğunuza bir tane amcamı yanıma getirseydiniz.

Av. Nahit Eren : Yok bunu az evvel söyledin. Dışarıda görüş gel dediğim dedim ya.

Baran Güran : Görüştürmediniz abi.

Av. Nahit Eren : Bunu sağlayabiliriz dedim. Savcılarla görüşüp dışarıda bir aileyle görüş anlamında bir talebin varsa tamam demedim tamam. Ben bir şey daha soracağım. Hani bu maddi gerçeğin açığa çıkması açısından Baran. Bize iki defa geldin. Bizden görüşmeye baroya. İlk görüşmende geldiğin zaman bütün hakikat açığa çıksın istiyorum dedin. Bu kim öldürdüyse ceza yesin. Bu benim köyde Nevzat da olsa bizim aileden biri de olsa ceza yesin. Hatta aynen sana çünkü bunu ikimiz tek değil, yönetim kurulu üyesi arkadaşlarımız da yanımızdaydı görüşmede. Aynen bu anları hatırlayarak sana şöyle bir soru sordum Baran. Bize vereceğin vekalet duruşmada ben bugün babanın burada oturması gibi senin müşteki olarak yan yana oturacağız ama karşımızda eğer bir iddianameye dönüşürse mevcut durumda tutuklu oldukları için annen ve kardeşim de karşımızda olacak. Onları sorgulayacağız dedik. Bunu kabul ediyor musun Baran? Diye sordum sana. Sen bana verdiğin cevabı burada salonda bir daha tekrarlayabilir misin? Cevabı özür dilerim.

[Sanık müdafi tarafından mikrofona konuşulmaksızın soruya itiraz edildiği görüldü.]

Mahkeme Başkanı : Yani burada zaten ben de bu soruya kabul itirazınızı kabul ediyorum. Söz konusunda iki vekalet ilişkisi arasında olabileceğinden bahisle es geçiyorum.

Av. Nahit Eren : Dosyaya delil olarak giren görüntüler var. Biz izledik. Bütün dosyaya, basına da yansıyan görüntüler var. Senin kardeşinle cezaevinde yaptığın görüşmeler var. Hepsini dinledik. Kardeşin bu görüşmelerin içerisine kardeşine yaptığın telkinler, yaptığın düşüncelerini kendisine dik durması, ayakta durması konusunda sohbetlerin var, saygı duyuyorum. Bir sadece bir şey benim dikkatimi çekti. Onu soracağım. Kardeşin sana ısrarla kamerayı soruyor. Sen de tamam bulundu, çıkmış. İki kişi var diyor. Sen de evet diyorsun. Ben mesela dosyada gerçekten böyle bir kamera kaydı görmedim. Sen mesela bu kamerayı bir yerden mi izledin? Çünkü biz seninle birlikte maddi gerçeğin açığa çıkması için çalışıyorduk. Varsa böyle bir görüntü nerede izledin? Nerede mahkemeye sunma konusunda bu delile ilişkin nasıl temas ettin onu soracağım.

Baran Güran : Öncelikle zaten sosyal medyada bir ton yalan haber dönüyordu. Sonradan bir açıklama geldi. Ben bunu sosyal medyada gördüm. Askeri üs bölgenin Kartal Göz kamerasından iki tane karartı olduğunu söylediler. Biz de dedik karartı. Yani iki kişi olma ihtimali vardı. İkinci husus kardeşim de on sekiz yaşında. Hayatı boyunca karakola girmemiş. Aynı şekilde annem de. Kendini savunacak bir şeyde de değil. Bir durumda da değil. Ben orada kardeşim her zaman tamamını bütün görüşmeleri dinleseydiniz. Ne demek istedim ya anlayacaktınız. Büyük ihtimalle tamamı yok.

Av. Nahit Eren : Hepsini dinledim.

Baran Güran : Ha. Ben orada defalarca Enes'in demek istediği şu abi zaten kamera çıktığında her şey gününüzde çıkacak. Mutluyuz. İnşallah abi bir laf mı bitirmesin?

Av. Nahit Eren : Ben bir o yorumu değil. Yani böyle bir delile temas ettin mi? Etmedim onu soruyorum.

Baran Güran : Hayır sosyal medyadaki yalanlardı.

Av. Nahit Eren : Sosyal medyada gördün.

Baran Güran : Evet şu da vardı. Orada benim de babamın da şu görüntüler çok yayıldı. Onu kim yaydı, onu da bilmiyoruz. Sonuçta orada telefona konuşmuşuz. Ayrıyeten 18 yaşında bir çocuk ve cezaevinde.

Av. Nahit Eren : Ben onu sormuyorum.

Baran Güran : Biz onu teselli çok yargıladık.

Av. Nahit Eren : Orada haklısın. Ya ben ona bir şey demiyorum. Kardeşin. Dedim zaten.

Baran Güran : Eee orada dik durması söylenmiş, nedeni şuydu. Dik dur. Allah büyüktür. Çünkü üstüne bir iftira atılmış. Er veya geç çıkacak. Biz bu yüzden yani cezaevine atıldı diye biz kardeşimizi orada sahipsiz mi bırakalım?

Av. Nahit Eren : Ben bunu sormadım.

Mahkeme Başkanı : Zaten. Tamam tamam. Haricen ekstradan da fazla cevap verdi. Evet. Ha tamam.

Av. Nahit Eren : Başkanım benim sorum sadece buydu. Teşekkür ederiz. Ben bir kez daha manevi anlamda diğer tehditleri ya da bize karşı şey değil mi? Manevi anlamda kırmışsam hepinizden yine özür diliyorum. Yine özür diliyorum.

Mahkeme Başkanı : Yani bu herkes bir sakinleşsin. Tamam. Bundan sonra direkt soruya geçiyoruz. Aksi bir durumda dediğim hususu yapacağım. Onu da söyleyeyim. Yani en nefret ettiğim bir şey ama bunu da yapmak zorunda bırakmayın beni. O yüzden güzelce gidelim. Şey şunu tekrar hatırlatıyorum. Baran. Kendini suçlayıcı sorulara ben zaten müdahale edeceğim. Sen de cevap vermek istemiyorum diyebilirsin. Senin cevap vermek istemiyorum demen bizim nezdimizde senin yalan söylediğin ya da başka bir şey olduğu demek değil. Çünkü bu ailenin tamamı şüpheli sıfatı olduğu için ben müdahale edeceğim ama bazen beni müdahale edemediğim gözden kaçırdığım husus olabilir. Yani her soruya cevap vermeme hakkına sahipsin. Çünkü kendini suçlayıcı sorulara cevap vermeme hakkına sahipsin. Kanunen nettir.

### Av. Aydın Özdemir

Av. Aydın Özdemir : Baran Bey hatırladığınız kadarıyla olay günü kardeşiniz ilk hani ilk kardeşinizin ne zaman kaybolduğunu fark ettiniz? Ne zaman aramaya başladınız? Hatırlıyor musunuz acaba?

Baran Güran : Ben saat kaçta kaybolduğunu oradan bir iki gün sonra öğrendim. Çünkü neden? Köyde bulunan okul kamerasının en son üçü on beşte görüldü. Ondan sonra kimse görmedi. Ben de sadece kamera kaynağına inanarak yani sonradan bunu öğrendim. Olayın üçüncü günü falandı.

Av. Aydın Özdemir : Kaçta aramaya başladınız? Hatırladınız kadarıyla?

Baran Güran : İlk gün mü?

Av. Aydın Özdemir : İlk gün, evet.

Baran Güran : Köye geldiğim gibi.

Av. Aydın Özdemir : Saat kaçtı takribi? Bir saat söyleyebilir misiniz yoksa?

Baran Güran : Akşam'a doğru da hatırlamıyorum.

Av. Aydın Özdemir : Hatırlamıyorsunuz.

Baran Güran : Şimdi olsa yalan olur.

Av. Aydın Özdemir : Peki, saat 20:43'te olay günü bir ihbarda bulunmuşsunuz siz. Arayıp beş saattir kardeşimi arıyoruz bulamıyoruz dediniz. İhbarda bulunduğunuzda beş saat kadar geçmiş miydi? Hatırladığınız kadarıyla.

Baran Güran : Ben öğrendiğim zaman o kadar zaman geçmemişti. Dedim dememin nedeni, hani bu tür vakalarda genellikle geç geliyorlar ya. Ben de maksat dedim ki hani dedim uzun zamandır kaybolmuş, uzun bir saattir maksat gerekli personel erken gelsin diye. Yoksa ben yanlış olmasam amcam Kurtuluş akşam yemeği yerken kardeşim beni aradı. Yani o aramayı yaptığım zaman aradan ya bir saat geçmişti ya geçmemişti.

Av. Aydın Özdemir : Bir saat geçmişti.

Baran Güran : Ya geçti ya geçmedi.

Av. Aydın Özdemir : Ama açık bir beyan var. Beş saattir arıyoruz bulamıyoruz.

Baran Güran : Onu dememin tek nedeni sırf bir an önce...

Mahkeme Başkanı : tamam tamam.

Av. Aydın Özdemir : Tekrar, bir daha açıklasın.

Mahkeme Başkanı : Açıkladı duydum.

Av. Aydın Özdemir : Bir daha açıklasın.

Mahkeme Başkanı : Yok yok açıkladı zaten. Bir iki cümle önce açıkladı.

Baran Güran : Bir saat falan kayıptır deseydim. Bana diyecek belki şurada falandır. O düşünceyle ben de uzun zamandır kayıp. O amaçla.

Mahkeme Başkanı : Tamam onu söyledin zaten. İki kere söyledin. Avukat Bey duymamış olabilir.

## Aile ve Sosyal Hiz. Bakanlığı

Av. Abdullah Yılmaz : Baran sence kardeşine ne oldu? Bunu öncelikle direk sorduğum için normalde bağdaştıracaktım ama direk bunu sorayım. Sence ne oldu? Yani normal rutin devam eden bir hayat var. Normal Kur'an kursuna gidiyor, geliyor. Sence ne olmuş olabilir?

Baran Güran : Kendi düşüncem sadece şu. Kardeşim tepe çıkmadan önce bu pislik tarafından kaçırıldığını düşünüyorum, götürüldüğünü düşünüyorum.

Av. Abdullah Yılmaz : Niye onu düşünüyorsun mesela? O kadar arama yapılıyor.

Baran Güran : O Saatte evde olduğunu söylüyor, değil mi?

Av. Abdullah Yılmaz : Tamam ama amcan da o saatte evde olduğunu söylüyor. Annenin de o saatte evde olduğunda.

Mahkeme Başkanı : Bu soruya cevap vermeme hakkına sahipsin. Suçlayıcı bir soru.

Av. Abdullah Yılmaz : Çok uzatmayacağım dediğim gibi ama şimdi arama çalışmaları oluyor. 19 gün kardeşin aranıyor. Arama çalışmaları olurken garip şeyler oluyor. Yangınlar çıkıyor, elektrikler gidiyor, kadınlar birbiriyle kavga ediyor, çelişkiler oluyor. Jandarmanın kendi kolluk tutanakları var. İşte arama çalışmasında yanlış yönlendirdiğine dair. Ne düşünüyorsun bu konuda? Yani mesela jandarma diyor ki, bizi amca başta olmak üzere köylü yanlış yönlendirdi. Bu da tutanak altına alınmış. Dosyada da var. Sayın Başkan da sordu zaten Salim Güran'a. Sen ne düşünüyorsun? Mesela böyle bir şeye şahit oldun mu? 19 gün sonra görülüyor ve bulunduğu yer daha önce defalarca aranan bir dere. Sen hiç böyle bir çelişkiler falan filan var böyle dosyalarda. Mesela Melike ifade değiştiriyor. İşte Birsen ifade değiştiriyor. Maşallah ifade değiştiriyor. Hediye Güran. Hediye ifade değiştiriyor.

Mahkeme Başkanı : Avukat Bey şunu sormak istiyor. Bu çelişkili beyanlar var. Bunları bir plan dahilinde planlayarak mı yaptınız yoksa normal doğaçlama verilen beyanlar mı?

Baran Güran : Sayın hakimim, benim ailem demin dediğim gibi hayatı boyunca karakol savcılığında hakim karakol karşısında ifade veren insanlar değiller. Kendileri karıştırmaları gayet normal. Şehir ortamında büyümüyorlar. Hepsi köyde büyümüşler. Bunları niye kimse göz anda getirip konuşmuyor?

### Av. Elif Aslı Şahin Torun

Av. Elif Aslı Şahin Torun : Enes cezaevindeyken bir görüşmeniz var. Diyor ki sana Narin benim diş fırçamı kullanmıştı. Bir şey çıkar mı diye soruyor. Neyin çıkmasından korktu?

Baran Güran : Zaten buradan anlıyoruz ki, çocuk daha bir şey anlamıyor. DNA'yı gerçekten de rahmetli Enes'in diş fırçasını olabilir. Neden? DNA dediğiniz zaman ben de bu konuda pek şey olmadığım için ben de aklıma o gelir. Acaba en son diş fırçamı kullandı ağzında veya mesela ben bile sordum. En son ben Narin'i öptüm. DNA olarak bu benim, buna mı diyorlar yani? Bu amaçla.

Mahkeme Başkanı : Bu amaçla.

Av. Elif Aslı Şahin Torun : Raporun gelip gelmediğini sürekli soruyor.

Baran Güran : Çünkü merak ediyordu. Bir an önce gelsin diyordu. Tam okumadınız o konuşmayı galiba. Dinlemediniz.

Av. Elif Aslı Şahin Torun : Enes'in peki şiddete ya da madde kullanımına eğilimi var mıydı? Hiç öfke kontrol problemine şahit oldunuz mu?

Baran Güran : Hiçbir şekilde olmadım. Bunu açık arada söyleyebilirim. Bütün köye de söyleyebilirsiniz. Köyde hiçbir şekilde kimse kavga etmeyen Enes'tir.

Av. Elif Aslı Şahin Torun : Kendi kolunu ısırıyormuş. Yüzüne yumruk atmış.

Baran Güran : Kardeşini kaybetmiş. Normal değil mi?

Av. Elif Aslı Şahin Torun : Ama siz yapmamışsınız.

Baran Güran : Ben kafamı duvara vurdum. Siz gördünüz mü?

Baran Güran : Telefonumu duvara vurdum, gördünüz mü? O tür şeylere rapor almıyorlar genellikle.

### Av. Emine Akçalı

Av. Emine Akçalı : Dün annenizi de dinledik. Çok aydınlatıcı bilgiler vermedi. Benim sorum şu. Anneniz sizce amcanızı mı koruyor yoksa Enes'i mi koruyor?

Mahkeme Başkanı : Bu soruyu da cevap vermeme hakkına sahipsiniz. Suçluyu, delilleri karartma iddiasına gider.

Baran Güran : Annem kimseyi korumaz.

Av. Emine Akçalı : Yapmanızı siz mi kendi kendinize?

Baran Güran : Kendi kendime düşün.

Av. Emine Akçalı : Evet 20 yaşındasınız zaten hani.

Baran Güran : 21.

Av. Emine Akçalı : Daha önceden hani sordunuz mu? Niye siz ihbarda, niye ihbarda bulunmadınız diye? Hani biliyor muydunuz onların ihbarda bulunmadığını?

Baran Güran : Olayı bilmiyorum yani arama yapıp yapmadıklarını bilmiyorum ama olayın telaşından insan böyle bir şeyi düşünmemesine normal bir şey. Çünkü telaşlaşıyor ve arıyorsun.

Av. Emine Akçalı : Evet. Nevzat'la ilgili dün aile bireylerine de sorduk. Hani siz ne düşünüyorsunuz? Çok iyi bir izlenim uyandırmadı bizde. Aile bireyleri gözünde. Çünkü Nevzat ve eşi dost olduklarını söyledi amcanızla. Ama aile bireyleri ve amcanız kesinlikle böyle bir şey yoktur dedi. Nevzat'la ilgili bilgi almak istiyordum.

Baran Güran : Uzun zaman.

Mahkeme Başkanı : Kelimelerine dikkat et. Hakaret veya küfür edecek cümleler kurma tamam?

Av. Emine Akçalı : Sadece dostlar mıydı? Yedikleri içtikleri...

Baran Güran : Uzun zamandır konuşmadıklarını biliyordum. Çünkü ben ondan önce normal çünkü köy ortamı olduğu için ister istemez komşusun yani gidip geliyorsun, düğünlerden yerine karşılaşıyorsun. Normal bir köylü neyse odur yani. Peki Nevzat'ın aile bireyleri öyle dediniz. Nevzat'ın her çoğunlukla cevaplarına ben bilmiyorum. Hatırlamıyorum demesine kimse neden bu kadar tepki...

Mahkeme Başkanı : Onu biz değerlendireceğiz Baran. Bizim işimiz bu. O benim işim. Tamam. O mahkeme heyetinin işi. Tamam. Tamam.

Av. Yılmaz Demiroğlu : Baran, Narin ile Nevzat'ın torunu yaşıt mı? Bir bilgin var mı bu konuyla ilgili?

Baran Güran : Yani torunu bir tane Fadile kızının kızı var. Hemen hemen yaşıtlar galiba.

## Sanık Yüksel Güran Müdafileri

### Av. Yılmaz Demiroğlu

Av. Yılmaz Demiroğlu : Tam olaydan önce Nevzat'ın Narin'e harçlık verdiğine dair bir bilgi görgün oldu mu?

Baran Güran : Hani köyde birkaç kere duydum hatta köylüler küfür ediyordu. Hani o köylülerin içinde tam hatırlamıyorum, kim ama demişler hatta şey demişler dört beş tane çocuk olduğuna rağmen sadece Narin'e verildi.

Av. Yılmaz Demiroğlu : Sadece Narin'e.

Baran Güran : Sadece Narin'e.

Mahkeme Başkanı : Bunu köylülerden duydun. Evet. Yani bu gene çingeneleri duyduğunuz gibi yani kim? Hani çingeneleri de söyledin ama köylüden duydum dedin.

Baran Güran : Ama orada sanki amcam Barış'ın kızı, ben hatırlıyorum sanki o söylemişti gibi.

Mahkeme Başkanı : Bunu amcan Barış'ın kızı mı söyledi?

Baran Güran : Küçük o da, Narin'in yakın arkadaşları. Tamam. Öyle bir şey tam hatırlamıyorum ama.

Mahkeme Başkanı : Ben ismen merak ediyorum.

Av. Yılmaz Demiroğlu : Yani bu çocuk grubu içerisinde sadece Narin'e verdi öyle mi? Evet. Teşekkür ediyorum. Peki Nevzat ile babanız arasında herhangi bir araç alışverişinden ötürü bir gerginlik bir tartışma oldu mu? Buna şahit oldunuz mu?

Baran Güran : Oldu şahit oldum ben de oradaydım.

Av. Yılmaz Demiroğlu : Ne oldu?

Baran Güran : Orada bir zarar vardı. Babam bunu Nevzat'a başta güzel bir dinle anlattı. Böyle bir zarar var. Kendisi sözde bizden korkuyormuş, herkes öyle söylüyor. Kendi amcamın evinde sesini bağırarak ben vermiyorum, kabul etmiyorum dedi. Ondan sonra babam da dedi, sen hani böyle diyorsun. Köyden iki tane yaşı büyük adam çağırdık. Babam çağırdı, bak dedi gelin sizin yaşınız büyüktür. Siz ne diyorsanız Nevzat kekelemeye başladı orada. Yok ben bilmiyorum ne babam da orada kızdı ona. Sen seni dövmeyeceğim. Sen bu parayı vereceksin. Onunla tartıştık orada. Hatta ben de orada ona müdahale edecektim. Babam kızdı bana.

Av. Yılmaz Demiroğlu : Sen ona herhangi bir söz söyledin mi?

Baran Güran : Yok. Söz söylemedim ama orada dedim yani saldıracaktım aslında. Çünkü babamla öyle bir üslupla konuşuyordu. Babam tepki gösterince ben sustum çıktım.

Av. Yılmaz Demiroğlu : Sence Nevzat Narin'e bunu bu tartışma için yapmış olabilir mi?

Baran Güran : Yapmış olabilir. Çünkü şöyle cevap vereyim. O kadar çok soğukkanlı ki o kadar rahat ki sanki elli tane cinayet işlemiş gibi rahat ve hiçbir şey olmamış gibi davranıyor.

Av. Yılmaz Demiroğlu : Tamam efendim. Teşekkür ediyorum.

Mahkeme Başkanı : Ben teşekkür ederim. Tamam buyurun sırayla.

### Av. Tuncay Erkuş

Av. Tuncay Erkuş : Baran bey, küçük Narin'in kaybolmasından bir gün sonra halanızın oğlu Muhammed Kaya. Bir terlik buluyor. Bu terliğin fotoğrafı size atılıyor. Bunu ailenize göstermenizi istiyor. Bu terlik olayıyla ilgili bildiklerinizi anlatabilir misiniz?

Baran Güran : Biz evdeydik. Balkonda oturuyorduk. O ara Muhammed, Muhammed'ti, Osman'dı tam hatırlamıyorum ama Muhammed'ti büyük ihtimal. Bana bir resim attı. Dedi ki, bu terliğe baksana dedi yolda bulmuşuz. Bir annene göstersen de onun mu değil mi? Narinin olabilme ihtimali var mı, yok mu? Ben de anneme gösterdim. Annem dedi ki, bu Narin'in terliği. Biz o ara zaten yerimizden fırladık açıkçası. Direkmen o çingene olan yere gittik. Askerlik personel komple etrafını sarmıştı. Orada aramaya başladık.

Av. Tuncay Erkuş : Evet. Bir de şeyi sormak istiyoruz. Baran bey, yani siz de hatta olayı öğrendiğiniz zaman kendinize zarar verdiniz. İşte kardeşiniz Enes kendi kolunu ısırmak suretiyle ve yüzüne vurmak suretiyle kendisine zarar verdiğini söylüyor. Diğer kardeşlerinizden işte kendine zarar veren kimse oldu mu? Daha doğrusu bir şeyleri fırlatan, üzülen, üzüntüden ne yaptığını bilemeyecek duruma gelen kardeşlerinizden biri oldu mu? Kimse oldu mu?

Baran Güran : Osman telefonu kırdı. Ben kaç kere bardağı kırdım. Hatta böyle söyleyeyim. Kaç kere kafamı bile duvar vurdum açıkçası.

Av. Tuncay Erkuş : Tabii olayın şokuyla.

Baran Güran : Olayın şokuyla. Kendi telefonumu da kırdım. Sırf annem üzülmesin diye o da yani bu şahıs daha teslim edilmeden bile sırf annem üzülmesin diye gece kalkıp dama gidip yalnız ağlıyordum. Kimse duymasın, annem ve babam üzülmesin diye. Çünkü bize çok düşkünler. Hani o yüzden dolayı ben de kendime zarar verdim olaylarda.

Mahkeme Başkanı : Baran, bu Nevzat para verdi dedin. Nevzat da çok soğukkanlı cinayet işler ancak hiçbir şey olmamış gibi hayatına devam eder dedin. Peki bu para verdiğinden neden şüphelenmediniz o zaman?

Baran Güran : Çünkü sayın hakim bu bir köy ortamı. Çünkü mesela şu an köydeki insanlar bugün mesela şu anda ben gitsem köydeki birisi o an mesela küçük kardeşime veren var. Para verse ben şaşırmam ki.

Mahkeme Başkanı : Doğru. Şaşırmazsın. Gayet normal.

Baran Güran : Herkes amca gibidir köyde. Köyümüzün nüfusu da büyük.

Mahkeme Başkanı : Ama ben de ona şaşırmadım. Ona şaşırmadığım için onun üzerinde çok durmadım. Ta ki sen bu çok soğukkanlıdır, cinayet işler, hiçbir şey olmamış gibi deyince ben bunu sana soruyorum. Normalde ben de bir para olayına şaşırmam. Gelir o gün ya bugün bir belayı atlattın. Biz bizim dini bakış açımıza göre sadaka belayı def eder düsturuyla. Ya bugün bir üç beş çocuğu sevindireyim de bela def olsun olur. Bu dini inancımıza göre. İşte onu sen öyle söylediğin için ben de akabinde bu çok soğukkanlıdır. Öldürebilir dediğin için bu soruyu sana soruyorum. Dikkat et ben böyle bir soruyu ilk başta sormadım.

Baran Güran : Evet doğrudur sayın hakimim. Şimdi kendisi zaten ifadesinde ilk defa bir cinayet işlediğini söylüyor. Yani bir insan hiç mi telaşlaşmaz? Bir insan hiç mi korkmaz? Sen nasıl her gece geldin? Babamın yanında oturduğun çay içtin bizimle?

Mahkeme Başkanı : Ama şöyle Baran. Şimdi cinayet işledim demiyor da cinayeti şey, cesedi yok ettim diyor.

Baran Güran : Bence yalan atıyor sayın hakimim.

Mahkeme Başkanı : Peki. Tabii ki öne gelelim isminizi tanıtıp sorabilirsiniz tabii ki.

## Sanık Enes Güran Müdafi

### Av. Recep Kızılok

Av. Recep Kızılok : Öncelikle başınız sağ olsun. Olay günü Enes'i ne zaman gördünüz?

Baran Güran : Olay günü ben akşam geldim. Akşam saat kaçtı ama sanki tam hatırlamıyorum abi çünkü çok şeydi, hastanede hastaneye geldi. Çünkü o gün bir ihbar geldi. Narin'e benzeyen bir çocuk memur hastanesinde sahipsiz bir çocuk. Hani orayı net hatırlıyorum ama diğerlerini hatırlamıyorum.

Av. Recep Kızılok : Peki Enes'e bir telaşlı bir panik durumu var mı? Bir heyecan var mı? Yani farklı bir şey sezdiniz mi?

Baran Güran : Beraber ağlıyorduk.

Av. Recep Kızılok : Beraber ağlıyorsunuz. Peki gözünde bir morluk ya da kolunda bir ısırık izi böyle bir şey fark ettiniz mi?

Baran Güran : Yok.

Av. Recep Kızılok : Fark etmediniz değil mi? Tamam, teşekkür ederim.

Mahkeme Başkanı : Ben teşekkür ederim.

Av. Onur Akdağ : Sayın Başkan sorularda biz en sonda olduğumuz için en azından adaletin sağlaması açısından savunmada ilk sırada olursak.

Mahkeme Başkanı : Tamam. Kabul. İlk sizden alalım.

Av. Mustafa Demir : Az önce soruyla ilintili bir soru soracağım. Biz de öğrendik o gün Enes'in hastaneye gittiğini. Mahkemeden Memorial Hastanesi'nin kamera kayıtlarını istedik. Hastane tek bir kamera yollamış. Onda da şöyle bir azizliğe uğradık. Yani, hani her şey şanssızlık oluyor ya. Burada da yine bir şanssızlık. Yani nasıl dün anlattığımız üzere orayı gören birden fazla kamera var. Ama bu kameraların saatiyle bir inceleme yapılmamıştı.

Mahkeme Başkanı : Evet direkt soru.

## Sanık Enes Güran Müdafi

### Av. Mustafa Demir

Av. Mustafa Demir : Yok, soru. Ha. Şu görüntüdeki kişi babası mıdır acaba?

Mahkeme Başkanı : Buyurun. Tanığa yaklaşabilirsiniz. Yok tanığa yaklaşın. Siz de tanığın yanında soru sorabilirsiniz. Yani burada soru sormak istiyorsanız sorabilirsiniz. Biz mikrofondan dolayı oraya yakın koyduk. Yanlış mana anlaşılmasın. Avukat Bey şuraya alayım sizi. Şuraya alayım.

Av. Mustafa Demir : Zaten cevap verdi babasıymış.

Mahkeme Başkanı : Ben duyamadım. Hah. Şöyle size de göstereyim. Ben hemen bir alabilir miyim fotoğrafı? Evet Memorial Hastanesi'ne ait kamera görüntüleri elinde. Aile bireyleri de görmüyor. Tamam. Sanık müdafi tarafından Memorial ambulansına ait bir görüntüde beyaz tişörtlü şahsın babası olup olmadığı Baran'a soruldu. Babası olduğunu söylemiştir. Evet. Mahkememize yapılan izlemede de söz konusu şahsın Arif Güran'a benzediği görülmektedir. Buyurun.

Av. Mustafa Demir : Enes'in o gün gözünde bir morluk iz var mıydı?

Baran Güran : Hayır görmedim.

## Sanık Salim Güran Müdafi

### Av. Onur Akdağ

Av. Onur Akdağ : Şimdi şöyle bir söylenti var. Ali Rıza Güran'ın sizin adınıza Bahtiyar ailesine ara teklif ettiği yönünde. Yani sizin ve ailenizin babanızın Ali Rıza Güran'a böyle bir telkini oldu mu? Ali Rıza Güran'la böyle bir şey konuştunuz mu? Ya da Ali Rıza Güran bunu yapabilecek bir şeye sahip mi yani?

Baran Güran : Benim kız kardeşim aslında öyle bir şey yapamaz.

Av. Onur Akdağ : Peki olaydan sonra Salim Güran'ın ruh durumu nasıldı? Yani Salim Güran üzüntülü üydü? Siz ondan hiç şüphelendiniz mi? Arama faaliyetlerine aktif bir şekilde katıldı mı?

Baran Güran : Salim Güran amcamdır. O çalışma sırasında 7/24 jandarmayla beraberdi. Ben çoğu saat dörtte geliyordu. Sabahın köründe geliyordu. Akşama kadar jandarmayla geziyoruz. Jandarma onu yanından ayırmıyordu.

Av. Onur Akdağ : Salim Güran Enes Güran'ı daha önce hiç dövdü mü? Yani olaydan önce olabilir. Amcası olması hasebiyle ne bileyim bir yaramazlık yapmıştır. Hiç dövdü mü?

Baran Güran : Yaramazlık yapmışsa amcanın burnu normaldir. Amcasıdır ama ben kendim şahit olmadım.

Av. Onur Akdağ : Yani Salim Güran'ın, Salim Güran'ın yeğenlerini dövme huyu var mı? Yani yeğenlerini döver mi?

Baran Güran : Allah yukarıdadır hayır.

Av. Onur Akdağ : Şimdi şöyle bir şey hayal edelim. Bir odanın içerisinde üç erkek var. Ve amcanın da anneyle birlikte olduğu söyleniyor. Bu birliktelikten dolayı da Narin kardeşiniz öldürülüyor. Şimdi siz Enes'i tanıyorsunuz. Enes'in bu durumda amcasına karşı tepkisi ne oldu?

Baran Güran : Kafasına sıkardı. Silah olsaydı kafasına sardı.

Av. Onur Akdağ : Bunun haricinde mesela Enes amcasını kayırıp kız kardeşinin ölümüne rağmen amcasını saklar mıydı?

Baran Güran : Asla. Enes eğer orada Salim Güran'ı ve Nevzat'ı görseydi, silah olmasa bıçakla onları doğrardı.
