---
title: "Osman Güran İfadesi"
editor: source
---

## Mahkeme Başkanı

Mahkeme Başkanı : Tanıklıktan çekinme hakkına sahipsiniz. Öncelikle bu bir yanlış bir şey değildir. Bu tanıklıktan çekinmek istiyorum. Tanıklık yapmak istiyorum, istemiyorum hakkına sahipsiniz. Bu bizim nezdimizde sizi suçlu kılmaz. Tamam mı? Çünkü bir tarafta amcanız, bir tarafta amca oğlunuz var. Bu hakka sahipsiniz. Tanıklık yapmak ister misiniz?

Osman Güran : İstiyorum.

Mahkeme Başkanı : O zaman sizi yeminsiz bir şekilde dinliyoruz.

Osman Güran : Olay gününü mü anlatayım?

Mahkeme Başkanı : Ben, olay gününden başlayacağız. Sonra devam edeceğiz. Osman Bey, tekrar şu hususu da hatırlatayım. Sorulara, kendinizi suçlayıcı sorulara cevap vermeme hakkına sahipsiniz. Ben de bu hususta müdahale edeceğim. Çünkü bazı sorular suçlu ve suçluya övme, suç delillerini gizlemeye yol açma, suçluyu kayırma iddialarına yol açabilir. Bu konuda meslektaşlarımızdan da hassasiyet bekliyorum. Evet Osman Bey, sizi dinliyorum. Bu konuşmalar nedir? Enes'le görüştünüz mü, konuştunuz mu? Olay gününü bize anlatın.

Osman Güran : Ben sadece Enes'le o gün görüştüm. Kaybolduktan sonra görüştüm. Akşam yedi, yedi buçuk civarı kaybolduğunu anladım. Patikadan yengem seslendi, kayboldu diye. O esnada herkesle beraber Enes de oradaydı. Enes'le beraber, köylülerle beraber aramaya çıktık. O gün öncesi hiç Enes'i görmedim. Sadece o gün akşam altı civarı, altı buçuk civarı dedemin evinin önüne gittim. Ben şehir merkezinde kalıyorum. Köyde evim yok, dedemle beraber köye gittiğimde dedemin yanına gidiyorum. Enes'le sadece o gün görüştüm, kaybolduğunu anladığımız zaman.

Mahkeme Başkanı : Evet, Enes'le sadece o gün görüştünüz, kaybolduğu zaman.

Osman Güran : Yani görüştüm derken herhangi bir sohbetimiz olmadı. Sadece aynı ortamdaydık.

Mahkeme Başkanı : Aynı ortamdaydık. Osman, daha sonra ertesi gün aramalara başladınız.

Osman Güran : Doğrudur.

Mahkeme Başkanı : Buna bir terlik bulunmuş, kırmızı bir terlik.

Osman Güran : Evet, doğrudur.

Mahkeme Başkanı : Bu muhabbet, bir de bu muhabbeti bize anlatır mısınız? Yani bu olayı anlatır mısınız?

Osman Güran : Evet. Ben dedemin evinin önündeydim.

Mahkeme Başkanı : Evet Osman. Bu terlik muhabbeti nedir?

Osman Güran : Evet. Dedemin evinin önündeydim. Misafirler vardı. Akşam vaktiydi. Kuzenim olan Muhammed Kaya amcam Arif Güran'in arabasıyla aşağı indi. Arabanın içinden yaşlı büyük halamız Fatma Ünsal araçtan indi. Yukarıdan getirmişti, Arif amcamın evinden. Kolluk kuvvetleri Arif Güran'in evinde sadece aile kalsın demişti. O esnada Fatma Ünsal ve misafirler de Arif amcamın evindeydi. O da o heyecanla yaşlıları aşağı indiriyor, ayakta kaldığını görünce. Aşağı getirince ben de kendi aracımın arkasında misafirlerin aracı var dedim. Sen hazır buradayken bir Kadoil Petrol'e kadar gidelim. Çarıklı girişinde. Biz beraber kadoil Petrol'e gittik. Orada bir şeyler aldık. Ondan sonra Muhammed Uğurcan kuzenimi aradı. Neredesin dedi. Hayvan pazarının orada açık bir alanda oturmuşum dedi. Tamam dedi. Biz de oraya gelelim. Biraz yanında oturalım. Oraya gidince tabii araçta Hüseyin Güran da vardı. Barış amcamın oğlu olan Hüseyin Güran.

Mahkeme Başkanı : Evet.

Osman Güran : Ondan sonra biz oraya gittik başkanım. Arabadan inince ben Muhammed'e dedim ki, Uğurcan'ın zaten arabası var. Misafirler var evde. Hizmet edecek bir genç yok. Benle Hüseyin Arif amcamın aracıyla köye dönelim. Siz ikiniz de oturduktan sonra tekrar dönersiniz. Sonra tamam dedi. Biz Arif amcamın aracına bindik. Ben şoför koltuğuna oturdum. Hüseyin de yanıma oturdu. Koltuğu kendime göre ayarlarken paspas havuzunun içinde bir kırmızı terlik gördüm. Elime aldım. Bu kimin dedim. Muhammed de kuzenlerime şey yeğenlerime marketten alışveriş yapmaya gittim. Yol üstünde rastlarken aldım. Ama o karışıklıkta söylemeyi unuttum dedi, yaşlıları aşağı indirince. Ben de o zaman ağabeyi Baran'a atalım dedim. Narinin olabilir dedim. Ondan sonra ağabeyi barana...

Mahkeme Başkanı : Anlamadım. Muhammed'in şey aldım dediği, terliği nereden almış?

Osman Güran : Yol üstünde. Yol üstünde giderken almış.

Mahkeme Başkanı : Peki bu arkadaş o gün herkes zaten bir terlik arıyor bir şey arıyor. Bunu nasıl unutmuş?

Osman Güran : Yaşlılar yukarıdayken kolluk kuvvetleri Arif amcamın evinden çıkın demiş. Sadece aile kalsın. Herhalde bir konuşma mı yapacakmış aileyle. O da oraya geliyor marketten çıktıktan sonra, eşya aldıktan sonra. O esnada yaşlıların dışarıda ayakta olduğunu görünce gelin sizi aşağı götüreyim diyor. Yaşlıları arabaya indiriyor. O esnada unuttuğunu söyledi.

Mahkeme Başkanı : Çok ilginç değil mi ama unutması? Sana mantıklı mı geldi?

Osman Güran : O öyle söyledi.

Mahkeme Başkanı : Sen de ondan sonra bu terliği kolluk kuvvetlerine mi bildirdin?

Osman Güran : Evet. Baran ağabeyine WhatsApp'tan attık. Baran bir dakika sonra telefonda bize döndü. Narin'in olabilir dedi. Ondan sonra biz de Muhammed'in terliği gördüğü yere gideceğiz dedik. Siz de oraya gelirsiniz dedik. Terliği kolluk kuvvetlerine teslim ettik.

Mahkeme Başkanı : Terliği kolluk kuvvetlerine teslim ettiniz.

Osman Güran : Evet.

Mahkeme Başkanı : Muhammed bulduğu yeri hatırlıyordu değil mi? Sizi o götürdü. Nereden bulduğunu. O bir çift mi iki çift mi?

Osman Güran : Tek terlikti.

Mahkeme Başkanı : Oradan bulmuş unutmuş söylemeyi. Siz arabaya binince oraya gittiniz. Bizim soracağımız sorular. Hakim Hanım'ın aklına takılan bir husus var. Bu arama yaparken oturmaya gittik. Uğurcan falan diyor. Bu oturmaktan mana nedir ya da orada oturuyordumdan mana? Tüm köy seferberlik halinde kızı ararken. Oturmak ne demektir yani?

Osman Güran : Oturma esnasında değil. Uğurcan terliği bulunmadan önce bizden habersiz zaten hayvan pazarının açık alanda oturuyordu.

Mahkeme Başkanı : Hangi günden bahsediyorsun? 21.08 22.08.

Osman Güran :  Olaydan 3-4 gün sonraydı hakim bey. 3-4 gün sonra.

Mahkeme Başkanı : 22.08 ertesi gün aslında. Terliğiniz bulduğunuz gün ertesi gün değil mi?

Osman Güran : Olaya üçüncü gündü tam olarak. Hatırlamıyorum.

Mahkeme Başkanı : Normal. Hatırlamamada bir abes yok.

## Duruşma Savcısı

Duruşma Savcısı : Yine geldik terlik mevzusuna. Bu ifadende şöyle hatırlıyorum. Suriyelilerin olduğunu düşünerek önce alıyor. Fakat Narin'e ait olabileceğini düşünüyor. Böyle bir cümlen var senin beyanında. Sen şimdi 6 kez bu yolu kullandın.

Osman Güran :  Bu terliği ben görmedim.

Duruşma Savcısı : Bu cümlen var değil mi senin? 6 kez geçip gittiğin bir yolu sabah öğlen akşam diye saat verdiğini hatırlıyorum. Aynen. Senin 6 kez görmediğini jandarman Afat'ın görmediğini Muhammed diyor ki araçtan bile inmeden araçtan inmeden eğilerek sürücü koltuğundaki kapıdan eğilerek almış. Bu şekilde mi ifade verdi sana da hatırlıyor musun? Nasıl almış şeyi terliği?

Osman Güran : Bana dedi ki ben markete gittim. Gidince gözüme takıldı. Almadım. Eşyaları aldım. Ondan sonra dönünce terliğin üstünden de geçtim. Hatta tekrar durdum. Geri geri gelince terliği aldım. Kapımı açıp aldım paspasın üzerine bıraktım.

Duruşma Savcısı : Yani görünür bir yerdeydi diyor ve sen 6 kez oradan geçtiğini ve tüm köyü geçti. Oradan o şekilde.

Osman Güran : Görseydim ben dağılırdım.

Duruşma Savcısı : Başkanım bir de bir sorum var. Nesrin Güran anneniz değil mi? Nesrin Güran annenizin bulunduğu bir kadınlar kavgası var. Biliyorsunuz onu değil mi? Annenizin konuştuğu bir konu var mı? Duydunuz mu ya? Bilginiz var mı bu konuyla ilgili?

Osman Güran : Yok.

Duruşma Savcısı : Yüksele karşı bir hakareti var.

Osman Güran : Hayır annem zaten o gün Süveyla Özkan'ın evinin önündeydi. Kavga esnasında yukarıda bile değildi. Tabii o söylüyor öyle. Ben kendi gözümle görmüyorum.

Duruşma Savcısı : Yok ben sadece bilginiz var mı diye.

Osman Güran : Ben annemin öyle bir şey. Tamam.

Duruşma Savcısı : Teşekkür ederim.

Av. Aydın Özdemir : Muhammed siz görüştüğünüzde, Muhammed saat kaçta bulmuş o terliği?

Av. Aydın Özdemir : Kaç saat geçmişti?

Osman Güran : Bana söylediği vakit yarım saat kırk dakika önce demişti. Markete gittim.

## Diyarbakır Barosu

### Av. Aydın Özdemir

Av. Aydın Özdemir : Size yarım saat önce bulduğunu söylemişti. Peki kimse size bu Narin'nin terliği olabilir şeklinde bir söylemde bulundu mu?

Osman Güran : Olayın ilk günü kolluk kuvvetleri yengem Yüksel Güran'ın yanına geldi. Kızın üstünde Narin'in üstünde yani. Hangi elbiseler var dedi. Siyah elbise var dedi ve ayağında kırmızı terlik vardı. O esnada orada olan herkes bunu duydu ve aklımızda öyle kalmıştı.

Av. Aydın Özdemir : Yok. Sormak istediğim şey bu. Daha netleştireyim. Güran ailesinden kimse size bu Narin'in terliği olabilir bu şekilde ifade verin dedi.

Mahkeme Başkanı : Barış kime mesaj atmıştın fotoğrafı?

Osman Güran : Baran ağabeyine atmıştık.

Mahkeme Başkanı : Onu soruyor.

Osman Güran : Hayır.

## Sanık Yüksel Güran Müdafi

### Av. Yılmaz Demiroğlu

Av. Yılmaz Demiroğlu : Şimdi iddia makamı da ve sorularda sanırım iddianameden etkilenerek kadınlar arasındaki kavgada Yüksel Güran'a doğru bir hakaret oluştuğu söylenmektedir. Bu husus tanıklara sürekli sorulmaktadır.

Mahkeme Başkanı : Evet.

Av. Yılmaz Demiroğlu : Ancak lütfen tutanağı okuyalım. Yüksel Güran'a yönelik bir hakaret yok. Evine doğru. Yani burada bir manipülasyon.

Mahkeme Başkanı : Olabilir. Onu manipülasyon değil de yorumlama derim. Yani evet iddia makamı olarak kusur aramanız çok güzel ama manipülasyon değil yorumlama. Yani belki Yüksel'e söylemiştir. Belki Yüksel'in arkasındaki başka bir kadına söylemiştir. Arif'e söylemiştir. Belki Arif'in evinin arkasındaki Nevzat'a söylemiştir.

Av. Yılmaz Demiroğlu : Yani bir ev tarif edilirken genelde erkek.

Mahkeme Başkanı : Olabilir. Olabilir. O sizin. O sizin yorumunuz. Sayın savcılık Diyarbakır Barosu bu şekilde tutanakta tutanan yorumu. Hiçbiri bizi bağlamaz. Mahkeme bütün yorumları alacak. Kendi yorumunu en son söyleyecek.

## Sanık Enes Güran Müdafileri

### Av. Mahir Akbilek

Av. Mahir Akbilek : Osman Bey kollukta kaç gün gözaltında kaldınız?

Osman Güran : Yaklaşık bir gün kolluktaydım. Yaklaşık altı yedi günde nezaretteydim.

Av. Mahir Akbilek : Kötü muamele, kaba dayak, sizi incitecek, nezaketsiz davranış, ağır hakaret, başka buna benzer herhangi bir muameleyle karşılaştınız mı?

Osman Güran : Evet gördüm. Kolluk kuvvetlerinde Narin'in cenazesinin bulunduğu gün ailemi hepsini aldılar, karakola götürdüler. Kolluk kuvvetlerinde dişime kerpeten atma, ayak tırnaklarımı çekme girişiminde bulundular. Gece vaktine kadar düz duvara tutup dayak olsun. Buna benzer şeyler gördük.

Mahkeme Başkanı : İşkenceler gördünüz.

Av. Mahir Akbilek : Buna rağmen neden şikayette bulunmadınız?

Osman Güran : Yani biz suçlunun bulunmasını istiyorduk ailece. Gerçekten ailemizin içinde midir suçlu deyip sustuk.

Mahkeme Başkanı : Bunun da dosyaya bir katkısı olmayacaktı ama bitti zaten. Tamam. Bitmeseydi dosyaya bir katkısı yoktu.

### Av. Mustafa Demir

Av. Mustafa Demir : Terlik konusu soruldu ama ben de bir daha şeyi sorayım. Terlik konusunun kim terliğin Narin'e ait olmadığını tespit etti sonra?

Osman Güran : Terliği kolluk kuvvetleri numarasını sormuştu. Kaç numara giydiğini aileye sormuştu galiba. Öyle hatırlıyorum. Tam şey yapamıyorum ama onun terliği olmadığını söylediler.

Mahkeme Başkanı : Onun terliğinin olmadığını numara uyuşmadığından.

Av. Mustafa Demir : Kısa sürede anlaşıldı mı? Uzun mu sürdü?

Osman Güran : Bir gün sonra anlaşıldı galiba.

Av. Mustafa Demir : Babanın beyanı farklıydı da tespit eden. Şimdi şeyi soracağım. Şu 56 plakalı bir araç var.

Osman Güran : Doğrudur.

Av. Mustafa Demir : 56 XX 763. Okulun kamera kayıtlarına girmiş. 18:32'de geliyor. Bu aracı kullanan kimdi?

Osman Güran : Bendim.

Av. Mustafa Demir : Sizdiniz. Bu saatte nereden geldiniz?

Osman Güran : Ben, dedemin arazilerini, hepsini ben ekerim. O esnada pamuk tarlasındaydım işçileri kontrol etmek amacıyla. Pamuk tarlasından gelip dedemin evine geldim.

Av. Mustafa Demir : Yani tam bu saatte geldiniz. Peki bu saatten sonra 18:56 diye geçiyor ama sanırım 59 diye geçiyor. 4 dakika ileriydi. 18:55 Salim Güran'ın aracı buradan uzaklaşıyor. Siz o sıra orada mıydınız?

Osman Güran : Doğrudur. Ben evin önündeydim. Salim amcam bizim eve geldi. Oturdu. Fatma halama selam verdi. Dedeme selam verdi. Bana selam verdi. Oturduk. Hatta pamuktan bahsettik. İlaçlardan haşerattan bahsettik. Normal sohbetimizi ettik. İşçisi aradığını söyledi. Ve mısır tarlasına gitti.

Av. Mustafa Demir : Yani 18:55 öncesi sizin evin yani dedenize ait evin önünde Salim ile oturuldu, konuşuldu. Sonrasında bir Yüksel Hanım'ın evde Narin'i görmemesi üzerine size doğrusu soruyor galiba. İlk başta daha doğrusu dedenizin evine doğru Maşallah Hanım'a. Oraları falan gördünüz mü?

Osman Güran : Patikanın üstünde Yüksel Yengem sadece Narin orada mı diye seslendi. Biz de burada değil, görmedik dedik. Ondan sonra kaybolduğunu anladık.

Av. Mustafa Demir : Peki Yüksel Hanım, Enes bunlar aramaya köy içine iniyorlar. O anlarda siz yine orada mıydınız? Gördünüz mü onları?

Osman Güran : Yani sadece bir sefer köyün içinde Yüksel Yengem ile karşılaştık.

Av. Mustafa Demir : Enes ile?

Osman Güran : Enes ile yukarıda karşılaştık.

Av. Mustafa Demir : Enes'in gözünde bir morlu falan var mıydı?

Osman Güran : Ben görmedim morluğu.

Av. Mustafa Demir : Siz gördünüz de morluk falan görmediniz. Doğru mudur?

Osman Güran : Doğrudur.
