---
title: "Muhammed Kaya İfadesi"
editor: source
---

## Mahkeme Başkanı

Mahkeme Başkanı : Muhammed Kaya. Muhammed, yine kırmızı giymişsin.

Muhammed Kaya : Başka montum yoktu. Başka montum yoktu efendim.

Mahkeme Başkanı : Ne güzel. Sen tutuklusun galiba. Başka bir soruşturmadan. Öncelikle tanıklıktan çekinme hakkına sahipsin. Bir tarafta dayın, bir tarafta dayının oğlu. Bir tarafta yengen var. Tanıklıktan çekinme hakkına sahipsin. Tanıklıktan çekinmen bizim için yani bu senin yanlış malına anlaşılmasın. Soruları cevap verdi, kaçtı gibi değil. Kanuni bir hakkındır. Tanıklık yapmak ister misin?

Muhammed Kaya : Tamam.

Mahkeme Başkanı : O zaman yeminsiz bir şekilde seni dinliyoruz. Hakkında bir soruşturma var. Bu soruşturmadan dolayı ben müdahale edeceğim bazı sorulara. Sen de seni iddia edilen, yani sana suçlu isnadı, suçlu iddia edilen sorulara cevap vermeme hakkına sahipsin. Şimdi bunu basın mensuplarına da açıklayayım da yanlış mana olmasın. Arkadaşlar olay şu. Arkadaşlar başka bir soruşturmada şüpheli. Dolayısıyla burada o soruşturmadaki sıfatını etkileyecek sorulara cevap vermeme hakkına sahipler. Bu CMK'nın kendilerine tanıdığı bir hak. Anlatabildim mi? Mahkeme başkanının müdahalesi bu yönde müdahale. Bu soru onun suç isnadı olur. Mesela şöyle. Sen Salim'e cesedi öldürmekte yardım ettin mi? Şimdi bu soru ona bir isnatta bulunma sorusudur. Bu yüzden müdahale ediyorum. Müdahalemin sebebi budur. Anlatabildim mi? Yanlış anlaşılmasın. Attığınız her şey başka manalara gidiyor. Bunu da izah edeyim size.

Mahkeme Başkanı : Evet. Muhammed. Bu Narin'in kaybolduğu günden başlayalım. O gün neredeydin? Ne yapıyordun? Hatırlıyor musun?

Muhammed Kaya : Sekizde uyandım. Davetiye dağıtıyorduk. Uğurcan kuzenimin düğünü vardı. Saat iki, iki buçuk civarı da dört kişi Mardin Derik'e doğru gittik. Oralara davetiye dağıtacaktık. Saat iki, iki buçuk civarı köy yollarından Derik'e doğru gittik. Saat yedi otuzda Barış Güran dayımın kaynanasının evinde yemek molası verdik. Saat sekiz otuz beşte kuzenim Devran Güran'a haber geldi. İşte Narin'in kaybolmuş diye. Saat sekiz buçukta oradan çıkıp köye doğru geldik. Yani yaklaşık kırk beş dakika, bir saat içerisinde Derik'ten köye geldik.

Mahkeme Başkanı : Ve arama faaliyetlerine başladın?

Muhammed Kaya : Yani ben köyü aradım. Ondan sonra gece bir Emir dayı diye biri vardı. İşte cinlerim var falan.

Mahkeme Başkanı : Asker arkadaşları şu tarafa alın. Tanığımızın etrafında olmasın. Siz de gelin. Gelin buraya. Hiçbir sıkıntımız yok. Tanığımız da rahat etsin. Rahatsın değil mi? Kendi hür iradenle ifade veriyorsun. Tamam. Bizim görevimiz mahkemece senin rahat bir şekilde ifade vermeni sağlamak. Evet. Devam ediyoruz.

Muhammed Kaya : Köyü aramaya başladım. İşte kuyulara baktım. Kapalı olan kuyuyu da açıp baktım. Boş kuyulara baktım. Kanal tarafına baktım. Ben Uğurcan Güran.

Mahkeme Başkanı : Peki terliği bulduğun güne gelir misin?

Muhammed Kaya : Terliği bulduğum gün ikinci gündü. Ayın 22'si. Kanal köprüsünün üzerindeydik. Yenge aradı beni, dedi çocukların sütü bitmiş. İki tane yeğenim var. Süt alır mısın? Araba var mı? Var dedim. Süt almaya gidiyordum. Terliği gördüm. Köy yolunun üzerinde. Yani yaklaşık iki buçuk kilometre uzaklıktan es geçtim terliği. Yan tarafta çingenelerin çadırları falan vardı. Onlarındır diye düşündüm. Sütü falan aldım. Dönüşte gene terliği gördüm. Belki onundur, belki onun değildir diye alayım dedim. Yengeme gösterdim.

Mahkeme Başkanı : Şimdi arabayla terliğin üstünden geçtin. İlk başta.

Muhammed Kaya : Yolun ortasında.

Mahkeme Başkanı : Peki Muhammed buradaki sır şu. Buradaki tartışma şu. O yoldan belki binlerce insan, belki yüzlerce insan geçti. Onlar o terliği görmedi de sen bu terliği gördün. Buradaki iddia şu. Bu soruya cevap vermeme hakkına sahipsin. Sen sanıklardan birinin telkiniyle, birinin yönlendirmesiyle o terliği oraya koyup soruşturmayı sekmeye uğratmak için böyle bir hamle yaptın mı? Sana o terliği oraya koy, bul ve jandarmayı o yöne çek diyen oldu mu?

Muhammed Kaya : Hayır.

Mahkeme Başkanı : Salim başta olmak üzere diğer Nevzat Yüksel Enes'in böyle bir talimatı oldu mu?

Muhammed Kaya : Hayır kesinlikle.

Mahkeme Başkanı : Peki orada o terliği dediğim gibi diğer sanıklar diğer aile fertleri bulamamışken senin bulmanın hikmeti nedir?

Muhammed Kaya : Yani şimdi böyle bir şey var tesadüf de olabilir. O benim geçtiğim mesela bir araba geçip terliği çocuk arabadan da atmış olabilir. Ya da çingenelerin olabilir.

Mahkeme Başkanı : Bunu nereden bileyim diyorsun? Ben geçtim, gördüm diyorsun.

Muhammed Kaya : Ben geçtim, terliği gördüm. Başta çingenelerindir dedim. Es geçtim. Sonra dönüşte gene oradaydı. Dönüşte aynı yerdeydi. Gene üstünden geçtim. Sonra ne olur ne olmaz bir yengeme göstereyim. Terlik onunsa zaten yerini biliyorum. Terlik onun değilse zaten çöptür. Köye gittim. O esnaf dayımın evinde bir kargaşa vardı. Çok kalabalık vardı. Yeni arabalar falan. Jandarma bağırıyor çağırıyor. O esnafın bir şey oldu diye arabadan indim fırladım direkt eve doğru. Bir şey mi oldu? Yok dedi. Toplantı yapacaklarmış. Herkesi evden çıkarıyorlar. Bir jandarma bağırıyor. Komutan vardı bağırıyordu. Annem falan orada. Ben de öyle şeylere karşıyım. Dedim komutanım siz bağırmayın ben çıkarırım evdekileri. Tamam dedi. Evde herkesi çıkardım. Annemin halası şeker hastası tek başına yürüyemiyor.

Mahkeme Başkanı : Annenizin ismi nedir?

Muhammed Kaya : İlhan.

Mahkeme Başkanı : İlhan.

Muhammed Kaya : Teyzem Azize halama yardım ettiler. Merdivene kadar getirdiler. Ben de ayaklarından tutup merdivenden indirdim. Ondan sonra dedim seni Salim dayımgile götüreyim. Yok dedi beni Hüseyin Güran'in evine götür kardeşi. Tamam dedim. Araba var mı? Var hemen karşıda. Arabaya bindirdim. Poşeti teyzeme verdim. Telefonum şarjdaydı onu istedim. Ondan sonra Hüseyin Güran'in evine gittim. İndirdim arabadan o esnada Osman Güran geldi. Sigaram bitmiş. Petrola kadar gidelim. Tamam dedim. Petrola gittik sigara aldık. Ondan sonra Uğurcan kuzenim aradı. Tepedeyiz. Gel oturalım. Bir beş on dakika. Tamam. Yukarıya çıktık. Sonra Osman dedi ben köye gidiyorum. Osman dedi ben köye gidiyorum. Siz gelirsiniz. İki araba oldu bizde. Tamam dedim. O arabaya bindi. O esnada onun bacakları benim bacağımdan uzun. Koltuğu ayarladı. Terliği fark etti.

Mahkeme Başkanı : Evet.

Muhammed Kaya : Terliği fark etti. Terlik kimin dedi. Ben de işte o esnada aklıma geldi. Yolda buldum. Hemen getir yengeye. Yani Baran'a atalım Yengeye göstersin. Terlik olursa zaten yerini biliyoruz. Çöptür.

Mahkeme Başkanı : Yani senin terliği unutmandaki sebep o toplantı yapacak diye kargaşadan duruyor.

Muhammed Kaya : Ondan sonra da hiç yalnız kalmadım. Bir de 36 saat uykusuzluğum vardı.

Mahkeme Başkanı : 36 saat uykusuzluğum vardı. Ama Muhammed ne iş yapıyorsun sen?

Muhammed Kaya : Memurum. Trakya Üniversitesi'nde.

Mahkeme Başkanı : Yani çok vahim bir delil.

Muhammed Kaya : Cumartesi geldim. Düğün için geldim. Kuzenimin mutluluğu vardı. Onu yaşayacaktık. Başımıza böyle bir olay geldi şimdi.

Mahkeme Başkanı : Yani şunu demek istiyorum çok terlik bulmak büyük bir olaydı o gün için. Hani terlik bulunduysa o yönde kaçırırdı. Bu konuda memursun da zeki de bir çocuksun. Cevaplarından da gayet iyiydi anlıyorum. Kendini de gayet iyi ifade edebiliyorsun. Bunu unutabilmen birazcık ilginç geldi bize. Belki bu ilginç geldiği için tutuklusun. Ben senin neden tutuklu olduğundan ilgilenmiyorum ama mahkeme olarak bize ilginç gelen husus bu. Yani terlik bulduğun zaman ilk bu terliği herkese göstermen gerekmez mi?

Muhammed Kaya : Oradaki kargaşadan ötürü ben o terliği unuttum.

Mahkeme Başkanı : Olay budur.

Muhammed Kaya : Ondan sonra yanımda yani sürekli birileri olduğu için ben o terliği hatırlayamadım.

Mahkeme Başkanı : Daha sonra terliği buldunuz. Kimlere haber verdiniz bu terlik kimin diye?

Muhammed Kaya : Ben Baran'ı aradım, abisi cevap vermedi. Kendi abimi aradım. Berat Kaya'yı. Dedim bir terlik buldum yolda. Sana fotoğrafını atayım yengeye göster. Onunsa zaten onundur, değilse değildir. Kapattım Baran aradı. Narin'in abisi. Narin'in abisi aradı. Evet. Baran aradı, işte abime anlattığımın aynısını ona da anlattım. Ondan sonra fotoğrafı gönderdim. 2-3 dakika geçmeden Baran'ı aradı. Arkada çığlık sesleri. Terlik onundur dedi. Neredesiniz? Ormanın oraya gel. Tamam. Geçtik oraya. Komutan geldi işte. Zaten hiç ifade falan da vermemiştik. Kim buldu? Ben buldum. Numaranı ver bir yere kaybolma. Tamam. Dayım Arif geldi terliğin üstüne. Terlik ben aldım dedi ona. Yani onun terliğidir. O şekilde karakola gittik. Zaten ifade falan vermeye.

Mahkeme Başkanı : Peki terliğin Baran'ın terliği olmadığı nasıl anlaşıldı? Bu konuda sen karakolda mıydın bu sırada?

Muhammed Kaya : Karakoldaydım. Saat 10:00-10:30 civarı karakola gittim. Diğer günün akşam 6'sı beni bıraktılar.

Mahkeme Başkanı : O arada bu terliğin şeyin terliği olmadığı Baran'ın terliği olmadığı. Bunu kim söyledi falan bilmiyorsun?

Muhammed Kaya : Bayram Astsubay var.

Mahkeme Başkanı : Baran değil. Narin'in terliği olmadığını.

Muhammed Kaya : Bayram Astsubay vardı. Geldi odaya dedi. Hiç mi fark etmediniz? Sekiz yaşındaki bir kız 25 numara terlik mi giyer diye. Ben de o komutana dedim ki, benim kızım yok. Ben hiç bir küçük kıza terlik almadım. Ben nereden bileyim numarasının 25 ya da 31 olduğunu.

Mahkeme Başkanı : Ha o şekilde terliğin yani söz konusu terliğin Baran'a ait olmadığı, numarayla anlaşılmış öyle mi?

Muhammed Kaya : Yani o öyle söyledi. O öyle bana.

Mahkeme Başkanı : Komutan öyle söyledi. Komutan söyledi.

Mahkeme Başkanı : Evet. Soru tekrarlarına gelmeyelim. Girmeyelim. Yani baya bir yani teferruatlı soru sorduğumu da düşünüyorum ama beğenmediyseniz sorularımı tabii ki sorabilirsiniz. Aile şey Arif Bey vekili soru yok. Diyarbakır Barosu avukatlarımızdan soru var mı? Yok. Aile bakanlığından soru var mı? Yok. Sanıklardan Yüksel Hanım ne diyeceksiniz?

Mahkeme Başkanı : (Yüksel'in sorusunu tekrarla) Ben özetleyeceğim. Tamam. Terlik bana geldiği zaman bu kırmızı terlik deyince tamam benim kızımın terliği olabilir dedim. Bu konuda çığlık attım. Ancak ilk başta terliğin numarasına dair hiçbir şey aklımıza gelmedi. Sonra baktık, dedi olay bu. Buyurun Sayın Savcım. Sayın Savcımızın bir sorusu varmış.

## Duruşma Savcısı

Duruşma Savcısı : Tekrara girmeden farklı bir şekilde soracağım. Önce şu başka şekilden başlayayım o zaman dur. Derikten kaç gibi döndünüz?

Muhammed Kaya : Saat 08:30-08:45'te kuzenime telefon geldi. Yani 180-220'yle Derik'ten.

Duruşma Savcısı : Bir saat zaten arası ortalama.

Muhammed Kaya : 45 dakika bir saat civarı köye yetiştik. Yani. Buçuk. Dokuz buçuk on civarıydı köydeydik.

Duruşma Savcısı : On civarı Dicle Üniversitesi'nin o tarafta olduğunuz var.

Muhammed Kaya : Doğrudur. Konuşuyordum. Orada bir başka soru geldi. Böldü. Böldü. Emir Dayı diye biri.E mir Dayı dediğimiz bir işçimiz var. Bekçimiz. Ali Rıza Güran. Annemin amcasının işçisi. Bekçi. Teli var. Cinlerim var diyor. Biz de hani ona inanarak tele fısıldıyor. Teli hareket ettiriyor. Bulabilir misin dedik. Bulurum dedi. Sinyal alıyorum dedi. Dicle Üniversitesi fakültesinin o tarafa doğru teli yönlendirdi. Biz de üç araba o tarafa doğru gittik.

Duruşma Savcısı : Orada sizin Güran ailesinden birinin bir çay bahçesi var mı işlettiği?

Muhammed Kaya : Şeyde. Beylerbeyi Garden. Yeni köprünün yukarısında. Orada zaten bekçi Emir Dayı.

Duruşma Savcısı : Anladım. Bu soruya cevap vermek zorunda değilsin ama Salim Güran geldi mi oraya akşam?

Muhammed Kaya : Hayır.

Duruşma Savcısı : Gelmedi.

Muhammed Kaya : Yok.

Duruşma Savcısı : Senin Salim Güran'la ilgili Devran ve birini bir köye beyaz renkli Egea ile gönderdi oğlunu. Böyle bir cümlen var ifadende.

Muhammed Kaya : O komutanlarla beraber köprüde.

Duruşma Savcısı : Devran'ı ve bilmediğim kişiyi bilmediğim bir köye gönderdi. 22 Ağustos'ta diyorsun.

Muhammed Kaya : 22 Ağustos'ta komutanlarla beraber komutan komutanlarla beraber birini gönderdi. Komutan dayım da oğlunu gönderdi. Yani o yanındaki kişi de ya istihbarattan biriydi ya da komutandı. Yani ben bilmiyorum kimdi. O şekilde gönderildi. O da anahtarı bana verdi. Dayım Arif'in arabasını. O şekilde ben de araba oldum.

Duruşma Savcısı : Başkanım size ilk olarak görünen o terlik orada olsaydı herkes görürdü. Tam tersine bence o terlik oraya hiç konmadı. Senin hep yanındaydı o terlik. Madem öğrendin bunu cevap vermek zorunda değilsin. Jandarma niye, jandarma yani jandarmaya niye gitmedin? Her adımda jandarma var orada zaten. Yüksel'e bunu gösterin. Terliğin onun olup olmadığına dair yorum alıp çöpe atmak kabahat, abiyle senin haddine mi bu?

Muhammed Kaya : Hayır estağfurullah. Terliği ben buldum. Jandarma zaten yolun üstünde. Jandarma falan yok, direk atarsın. Hemen orada yani işte gittiğim zaman yol üstünde jandarma falan yok. Herkes evin orada. Dediğim gibi çok büyük bir kargaşa vardı orada. Bütün arabaları da oradan kaldırdı. Hani yengeme gösterip zaten jandarmalar da orada. Kriminaldir.

Mahkeme Başkanı : Tamamdır. Muhammed Bey teşekkür ederiz. Sanık müdafilerinin sorusuna geçiyoruz.

## Sanık Enes Güran Müdafi

### Av. Mustafa Demir

Av. Mustafa Demir : Terlik bulunduktan sonra beni aldılar götürdüler dedin de, orayı tam anlatmadın. Biz orayı da merak ediyoruz da. Neler yaşadın? Ne oldu?

Muhammed Kaya : Terliği buldum. İşte saat on buçukta beni götürdüler karakola. Ben Osman Güran, Uğurcan Güran, Hüseyin Güran, Barış Güran'ın oğlu. Her birimizi ayrı bir odaya koydular. İstihbarattan bir adam girdi bana dedi katil.

Mahkeme Başkanı : Buralara müdahale ediyorum. Bu soruların muhatabı Diyarbakır Cumhuriyet Başsavcılığı'nın suç duyurusudur. Dosyaya bir şey katmayacağı için bu soruyu geçiyorum. Açıklayın ben bu soruyu geçtim.

Av. Mustafa Demir : İddianame bununla başlıyor ya.

Mahkeme Başkanı : Biz alacağımızı aldık. Tanığımızı aldık.

Av. Mustafa Demir : Ben sorduğumu anlatayım mı yine?

Mahkeme Başkanı : Kısaca tabii ki.

Av. Mustafa Demir : İddianame ilk terlikle başlıyor. Terlikten sonra aileye yönelinmiş mi, şüphe duyulmuş mu ve burada kendisi de iddia ediyor. Katil deniyor. İddiası var ya mesela aile kız kayıp olduğu halde öldüğünü düşünüyor gibi iddialar var. Bu iddialar bununla bağlantılı. Bundan dolayı sordum ben.

Mahkeme Başkanı : Bu işkence konusunda suç duyurusunda bulunun. Öyle bir iddianız varsa.

Muhammed Kaya : 9 saat beni darp ettiler. 20 tane istihbarat sürekli. Saat başı gelip darp edildi.

Mahkeme Başkanı : Bu konuda arkadaşlar suç duyurusunda bulunabilirsiniz. Anlatabildim mi? Yasal hakkınızdır. Diyarbakır Cumhuriyet Başsavcılığı'na suç duyurusunda bulunma hakkına sahipsiniz. Tamam.

Av. Mustafa Demir : Ne söylenmiş yarım kaldı. Anlatmaya devam ederse.

Muhammed Kaya : Çektiler o da işte katil dedi. Neyle öldürdün? Boğarak mı öldürdün? Taşla mı kafasını ezdin? Bu tür kelimeler de kullandılar işte. Sonra bir komutan geldi. Sen katil değilsin. Ben uzvumu kesip kendimi kadın yapacağım. Bu tür şeyler söylendi. Ben Derik'te olduğumu söyledim. Yok sen Derik'te değilsin. Sen katilsin. Falan gibi cümleler kurdular işte.

Av. Mustafa Demir : Gece aramalar kaça kadar sürdü? İlk gece yani 21'inde aramalar saat kaça kadar sürdü? Kaça kadar uyanıktınız?

Muhammed Kaya : Terliği bulduğum saate kadar durmadım. Öyle söyleyeyim.

Av. Mustafa Demir : Hiç uyumamıştınız?

Muhammed Kaya : Ondan önceki günde 4 saat uyudum. Yani toplamda 36 saat falan sürdüğüm vardı.

Av. Mustafa Demir : Bir de şey kısmı yarım bence anlaşılmadı. Bir arbede dediniz ya. Tam ne oldu orada o arbedede? Terliği buldunuz, geldiniz, unuttunuz. Yani ne yaşandı ki unuttunuz?

Mahkeme Başkanı : Onu güzel anlattı ya. Hadi bir daha anlat. Ben gayet iyi anladım.

Muhammed Kaya : Ben terliği buldum. Köye geldim. Kargaşa vardı orada. Dediğim gibi baya bir kalabalıktı. Yeni arabalar gelmişti. İstihbarat ben bilmiyorum tabii. O esnada direkt arabadan inip eve doğru koştum. Komutan bağırıyor işte annem güle. Komutanım ne oldu? Toplantı var işte. Ben dedim kimseye bağırmayın. Ben evde kim varsa çıkarırım. Tamam dedi. Annemle beraber herkesi çıkardık. Annemin ablasının şeker hastası. Yürüyemiyor tek başına. Teyzem Azize ile annem yardım etti. Merdivene kadar geldi. Ben de bacaklarını tutup indirdim. Ondan sonra ben dedim seni Hüseyin Gül'ün evine götüreyim. Misafirler de oraya gidiyor. Yok beni Hüseyin'lerin evine götür dedi. Tamam dedim. Arabaya bindirdim. Hüseyin'lerin evine geçtim. Arabadan indirdim. Osman Güran geldi. Sigaram yok. Çarıklı'ya kadar gidelim. Tamam dedim. Çarıklı'ya gittik. Sigarasını falan aldı. Urcan kuzenim aradı. İşte ben hayvan pazarında tepedeyim. Gel biraz hava alalım. Osman ile Hüseyin de yanımda. Sıkıntı yok etsinler dedi. Tamam. Oraya geçtik. Bir 15-20 dakika oturdum. Ondan sonra Osman dedi ben köye geçeceğim. İki tane araba var zaten. Tamam dedim. Arabaya bindi terliği fark etti. Terliği fark etti. Yani terlik kimin dedi, ben de yolda buldum. İşte unuttum. Köye götürdüm göstermek için. Unuttum. Dayan işte sen gösterdin diye aklıma geldi. Hemen bir fotoğraf attım. İşte Baran'a. Ondan sonra köprünün oraya. İstihbarat tanımıyorum.

Mahkeme Başkanı : Tamam tamam. Devamını anlattın. Hatta bir şey eksik anlattı. Bir şey eksik anlattı. Komutana ben böyle şeyleri sevmem ben hallederim dedi. Onu söylemeyi unuttum. Kötü manada değil ya. Sana iyi bir şey söyledim.

Mahkeme Başkanı : Tamam tamam anladım.

Muhammed Kaya : Direkt oradaki küme evlerine saldırdı. Çingenelere kız nerede diye bağırdı onu.

Mahkeme Başkanı : Tamam tamam onu demiyoruz.

Av. Mustafa Demir : Hangi araç sizdeydi?

Muhammed Kaya : Egea. Arif dayımın arabasıydı.

Av. Mustafa Demir : Peki siz gözaltına aldınız bu araçla ilgili. O zaman mı ilk inceleme yapıldı?

Muhammed Kaya : Evet.

Av. Mustafa Demir : Anladım. Teşekkürler.

Mahkeme Başkanı : Ben teşekkür ederim. Başka soru var mı? Buyurun Salim Müdafi Onur Bey.

## Sanık Salim Güran Müdafi

### Av. Onur Akdağ

Av. Onur Akdağ : Dayınız Salim Güran arama faaliyetlerini size yönlendirdi mi? Özellikle çingeneler meselesinde sizi çingenelerin olduğu yere yönlendiren Salim Güran mı?

Muhammed Kaya : Hayır hayır kesinlikle. Ben terliği sadece buldum. Terliği işte Baran'lara attım atıp yengen teyit ettiği onundur dedi. O tarafa doğru geldi.

Mahkeme Başkanı : Bunu da sordum zaten.

Av. Onur Akdağ : O gece Eğertutmaz deresine Salim Güran tek başına Eğertutmaz deresine o gece olay gecesi Eğertutmaz deresine Salim Güran kendi aracıyla tek başına gitmiş olabilir mi?

Muhammed Kaya : Ben görmemişim hayır diyorum.
