---
title: "Enes Güran Savunması"
editor: source
---

## Mahkeme Başkanı

Mahkeme Başkanı : Evet Enes, iddiaları duydun. Hakkındaki iddianameyi biliyorsun. Yasal haklarını biliyorsun. Avukatın var, avukatların var. Yine aynı hususu sana hatırlatayım. Sorularımıza cevap vermeme hakkına sahipsin. Ben susma hakkımı kullanıyorum diyebilirsin. Kendini istediğin şekilde ifade etme hakkına sahipsin. Mikrofon sende, seni dinliyorum. Ne dersin? Sen konuş, biz...

Enes Güran : İfademi komple mi anlatayım?

Mahkeme Başkanı : Baştan anlat, ne anlatmak istiyorsan.

Enes Güran : Malatya Arguvan'dan geldim. Ben kepçe operatörüydüm. Ayın 20'sinde eve geldim. Gece saat bir buçuk civarlarında evde oldum. Babam beni otogardan aldı. Babam sonra uyumak için dama çıktı. Annemin hazırladığı yemeği kendime ısıttım. Yemeğe başladım. Annem geldi damdan. Annem öptü beni. Annem yemeği ısıttığı esnada ben de sonra... Pardon, ben yemeği ısıttığım esnada annem geldi, annem beni öptü. Annem biraz oturdu. Sonrasında annem dama çıktı, ben kendime yemeği ısıttım. Yedim yemeği. Sabah uyandım, saat yedi buçuk civarlarında. Uyandığım zaman içeride annemi gördüm, Muhammed'i gördüm, Eren'i gördüm. İşte onların yanında oturdum. Eren geldi, kucağıma oturdu. Benle konuştu, ben onunla konuştum ve sonrasında babam Arif Güran ve abim Baran Güran ve Narin Güran aşağı indiler onlardan damdan. Ve sonrasında annem bize yemek hazırlamaya gitti. Yemek hazırladı, yemek bıraktı. Muzaffer Güran geldi bize, eşlik etti yemekte. İşte o sırada yemek yedikten sonra herkes kalktığı zaman babam bir de Muzaffer Güran Batman'a gideceğini duydum orada, babamla Muzaffer Güran Batman'a gittiler. Ve abim de gelin hanımı alışverişe götüreceğini söyledi. Ve o sırada da benim, annemdir, Muhammed'dir, Eren'dir, Narin'dir evdeyiz kendimize. Evde oturuyoruz, televizyon izliyoruz, klima açık, hava sıcak, dışarı çıkmıyoruz. Ondan sonra annemin evden çıktığını fark ettim. Yola, elinde teşti var. Teşti diyoruz yani. Elbiselerim, Malatya Arguvan'dan geldiğim için elbiselerim hepsi kirliydi. İşte anneme, annem onları Hediye Güran'a götürecekti. Ondan sonra işte anneme tamam dedim. Annem gitti. Ben de Muhammed, Eren, Narin benim. Evde oturuyoruz kendimize. Ve artık saat biraz geç olduğu zaman işte annemi artık aramaya başladık yemek gelip hazırlasın diye. İşte annem geldi sonradan. Yemek hazırladı bize. Saat 12:00 civarında artık yemeğe oturduk. Yemeğimizi yedik kendimize. Yemekten kalktık, koltuğa oturdum ben. Narin geldi yanımda. Ben kendime sosyal medyada oynuyordum. Narin de beni izliyordu. Ve sonradan Narin'in saate baktığını fark ettim. Ben de arkama baktığım zaman saate bakıyordu işte. Anneme dedi ki; "Saat 1 oldu anne, ben camiye geç kaldım. Ben camiye gideceğim" dedi. Annem dedi; "Kızım hava sıcaktır, gitme bugün". İşte Narin dedi; "Hatice, Fatma gidiyor diye ben de gideceğim". Annem "git" dedi tamam o zaman ve Narin benim yanımdan kalktı. Ben Narin'i görmedim artık. Ve sonradan gece geç saatte yattığım için, sabah erken uyandığım için çok uykum vardı. 5 dakika aradan sonra ben de koltukta uzanıp yattım. Saat 4 civarlarında uyandım. Uyku esnasında bir kişi beni aramıştı. Biri beni aradı, Malatya'dan Şahin diye. Malatya Arguvan'da arkadaşımdır kendisi. Uyku esnasında o beni aramıştı ve sonrasında kapatmıştı. Saat 4 civarlarında uyandım. Annemi gördüm ve Hediye Güran'ı gördüm. Annemle Hediye Güran sohbet ediyordu. İşte Muhammed de yatıyordu. İşte yengeme dedim; "Hoş geldin yenge". O da bana dedi; "Hoş bulduk. Nasılsın, iyi misin? İyiyim, sen nasılsın? İyiyim" öyle. Ondan sonra dışarı çıktım. Aşağı indim çeşme tarafına. Bakkal'ın yan tarafında ağaç var. O tarafta oturdum kendime. Sonrasında Tahir Kaya yanıma geldi. Tahir Kaya'yla biraz sohbet ettim.

Mahkeme Başkanı : Bu sırada evden çıkarken telefonun yanında mıydı?

Enes Güran : Telefonum yanımdaydı.

Mahkeme Başkanı : Bu saat 16:00 gibi. Aşağı yukarı yani zaman dilimi çok önemli değil. 16:00'da çıktığında telefonun yanındaydı.

Enes Güran : Evet.

Mahkeme Başkanı : Tamam.

Enes Güran : Bakkalın yanında işte o ağacın yanında oturuyordum. Tahir Kaya geldi yanıma. Benimle sohbet etti. Ben de onunla sohbet ettim. O sırada hava sıcak olduğu için bakkala gidip kendime enerji içeceği almak istedim. Bakkala gittim, kendime enerji içeceği aldım. Süleyman Kaya da arkamdan bakkala geldiğini fark ettim. Zihinsel engelli, günahım geldi. dedim ki; "Ne istiyorsun? Sana da alayım". Tamam dedi. "Enerji içeceği al" dedi. Ona da enerji içeceği aldım. Hatta 200 TL para vardı. Sabahleyin babam Batman'a gitmeden bana vermişti. Bakkalcıya verdim. Bakkalcı para üstünü bana verdi. Bakkaldan çıktım. O esnada Muhammed Yağmur'u fark ettim. Muhammed'in yanına gittim konuştuk onunla sohbet ediyorduk, sonradan Kerem Güran ile Muhammed Güran, Muhammed kardeşim olur, geldiler yanımıza, Kerem hoş geldin dayı dedi, benle Muhammed sohbet ettiğimiz esnada Süleyha Güran geldi. Süleyha Güran Kerem Güran'a samanımı taşıyın, yardım edin dedi. Kerem de belimiz ağrıyor, edemiyoruz dedi. Sonradan Süleyha Güran Tahir'i fark etti. Tahir Kaya'nın tarafına gittiği zaman Muhammed Kaya, pardon Muhammed Güran ve Kerem Güran köyün aşağı tarafına indiler, benle Muhammed Yağmur sohbet ediyorduk. O esnada Şevket Susam'ın kapının önüne çıktığını gördüm. Onunla da sohbet ettik biraz konuştuk, daha sonra Muhammed Kaya'yı Azize Kaya'nın önünde fark ettim, bakkalın önünde onun yanına gittim, arkamdan Şevket ve Muhammed de geldi. Dördümüz oturduk sohbet ettik. Daha sonra Muhammed Yağmur ve Şevket evlerine gideceklerini söylediler, ben ve Muhammed Kaya çeşme tarafına gittik zihinsel engelli Süleyman Kaya'da yanımıza geldi. Benle Muhammed Kaya sohbet ediyorduk, Süleyman dinliyordu. Muhammed Yağmur'un kapının önünde arabadan çıktığını gördüm. "Nereye gidiyorsun?" dedim. Arabaya yıkamaya gideceğini söyledi. "Beni eve bırakabilir misin?" dedim, edemiyorum dedi. Bende dedim o zaman beni okul tarafına bıraksan ben tepeye giderim. Okul tarafına gittiğimde çocukların saman taşıdığını gördüm. Üvey babaannem Süveyla Güran bana gelip samanımı taşı yardım et dediğinde yok diyemezdim bu yüzden Muhammed'e beni caminin yanına bırak dedim ve sonrasında direk yine tepeye çıkıp evime gittim. Aynı odada aynı koltukta kendime oturdum.

Mahkeme Başkanı : Saat kaç gibiydi eve geldiğinde?

Enes Güran : Saat 17:30 civarlarıydı.

Mahkeme Başkanı : Tamam.

Enes Güran : Ve sonrasında kendime telefonumla oynayamaya başladım. Sosyal medya, YouTube'lardayım. Ve sonradan gurbetten geldiğim için terliğim ve ayakkabım yırtık olduğu için Osman kardeşimin Ongözlü'de çalıştığını bildiğim için erken saatte geleceğini bildiğim için onu aradım. Bana bir tane terlik getir diye, tamam dedi abi. Ondan sonra biraz süreyle telefonla oynadığım zaman annemin gelip bana işte babanla abini bir arasana. İşte yemeğe yetişecekler mi, yetişmeyecekler mi? Ben de telefonuma baktım aslında. Telefonun kapandığını fark ettim. Yüksel Güran annem olur. Ona dedim ki, işte anne kendi telefonunu getir, seni telefondan arayayım. Annemin okuma yazması olmadığı için ben kendim arayıp kendim anneme verdim. İkisi de yemeğe geç geleceğimizi söyledi. Ve ondan sonra sayın hakimim annemin bana ahırın penceresi açıktır. Hindiler çıkıyor, köpek yiyor. Ben de dedim tamam anne. Ben tepeye doğru, ahırın tarafına doğru gidiyorum. Sen gelirsin yanıma. Ahırın tarafına gittiğim zaman yan tepede Ferhat Kaya, Ufuk Kaya, Furkan Kaya'yı fark ettim. Ferhat Kaya ısrarla beni çağırdı. Gel, gel diye. Ben de onların tarafına gittiğim zaman kırmızı bir tane köpekleri vardı. Bana geldi. Ferhat Kaya geldi yanıma. Gel işte ben geldim yanına. Gelmezsen artık. Yahu dedim ben gelmiyorum vallahi. Annem zaten beni çağıracak. Tamam dedim. Misafirlerimiz var. Ben o zaman eve gidiyorum. Tamam dedim. Ufuk Kaya benimle geldi. Furkan Kaya hiç yanıma gelmedi o zaman. Ufuk Kaya'yla birlikte ahırın hemen yanındaki ona tepeye geçtik. Hem de orada oturduk. Benle Ufuk Kaya, kendimize sohbet ettiğimiz esnada Yusuf Kaya'yı cami tarafından Ufuk Kaya fark etti. Ufuk Kaya ayağa kalkarak, elini sallayarak Yusuf Kaya'yı çağırdı. Yusuf Kaya geldi sonrasında sayın hakimim. Yusuf Kaya'yla da oturduk. Kendimize sohbet ettik. Ve sonrasında annemin geldiğini fark ettim. Annem işte bana gelip oğlum pencereyi kapat hindileri içeri koyacağız dedi. Tamam dedim annem. Ben annemin yanına gittim. Pencereyi kapattım. Pencere zor kapanıyordu zaten. İnip bir daha taş alıp, şişe vurup içeri koydum. Tamam pencereyi kapattıktan sonra hindileri içeri koyduk. Ve sonra yine tekrar...

Mahkeme Başkanı : Bu arada arkadaşlarla sigara mı içiyordunuz?

Enes Güran : Evet.

Mahkeme Başkanı : Sigara dediğimiz bildiğimiz düz sigara değil mi?

Enes Güran : Evet.

Mahkeme Başkanı : Diyarbakır'da sigara esrar olarak da bilinir. Yani esrar içenler sigara içiyorlar bizler de. Bu normal esrar değil, düz sigaradan bahsediyorsun. Bildiğimiz. Tamam.

Enes Güran : Ondan sonra işte hindileri içeri koyduğumuz esnada ben tekrardan arkadaşlarımın yanına gittim. Ve annem de yine aynı şekilde yan tarafımıza gelerek arkadaşlarımın elinde sigarayı gördü. O esnada yazıktır, içmeyin. Canınıza yazıktır dedikten sonra annem Yüksel Güran gitti. Biz de arkadaşlarımız sigaramıza oturuyorduk, sohbet ediyorduk. Ve Furkan Kaya geldi yanıma. İşte ona dedim işte sen niye orada gelip elimi tutmadın? Dedi işte işten geldiğim için, elbiselerim pis olduğu için, koku verdiğim için rahatsızlık vermek istemedim. Yok dedim ya sıkıntı yoktur. Ve Furkan Kaya'yla oturduğumuz esnada kendimize Yusuf Kaya, Ufuk Kaya'yla hepimiz birlikte oturuyorduk. Artık hava kararma vaktiydi. Ve Muhammed kardeşimin cami arkasından eve geldiğini fark ettim. Ve Ufuk Kaya'yla birlikte artık dedi hava kararıyor, eve gidelim akşamleyin dışarı çıkarız dedim. Tamam dedi dayı. Ve sonrasında sayın hakimim ben eve doğru gittiğimiz esnada Muhammed Kaya, Güran pardon sayın hakimim soy isimleri...

Mahkeme Başkanı : Önemli değil olabilir.

Enes Güran : Muhammed Güran kardeşim bana yetişti, birlikte eve doğru gittik. Ve sonrasında ben eve girdim yine aynı içeri, aynı odada oturdum, koltukta oturdum, annemin telefonunu aldım. Telefonum kapalı olduğu için, şarjda olduğu için annemin telefonuna baktım, Osman kardeşimin fotoğraflarını annemin telefonuna atmış. Ve Osman kardeşime birinci olan terliği bana getir diyerek telefonu kapattım. Tamam dedi ağabeyim. Ve sonrasında işte Eren'le oynadığım esnada annemin sofrayı serdiğini ve ezan okuduğunu fark ettim.

Mahkeme Başkanı : Bu arada hiç Narin aklınıza gelmedi mi?

Enes Güran : Sayın hakimim saat 1'de Hatice'yle Fatma'yla camiye gideceğimizi dediği zaman, çoğunlukla Hatice'yle Fatma'yla da oynadığı zaman, onların evinde de kaldığı zaman...

Mahkeme Başkanı : Normal şüphelenmediniz.

Enes Güran : Evet sayın hakimim.

Mahkeme Başkanı : Evet.

Enes Güran : Ve sonrasında sayın hakimim işte annem sofrayı serdi, ezan okudu, annem sonra mutfağa gideceği esnada arkasını döndü. Narin nerede dedi. Bilmiyorum dedim. Yani en son saat 1'de camiye gideceğim dedi. Ve sonrasında sayın hakimim, telefonu, annem kendi telefonunu alarak Hediye Güran'ı aramaya başladı. Hediye Güran da yok bizde deyince tepeye çıktık. Bizim hemen Maşallah Güran evi gözüken tepe. Maşallah Güran'lara seslendik oradan işte Narin sizde mi diye. Yok dedi. Ve ben de Muhammed kardeşimi alıp cami tarafına indim. Muhammed kardeşimi Azize Kaya'nın evine gönderdim. Ben de cami taraflarında sesim o kadar yüksek değil. Kısık sesle Narin'i Narin diye çağırıyorum. Yani belki bir yerde oyun oynuyormuştur ya da bir yerde dalmıştır diye. Ve Muhammed kardeşim de gelip bana abi orada da yok dediği zaman bu sefer artık sesimi yükselttim Narin Narin Narin diye. Çeşme taraflarına, cami taraflarına, okul taraflarına gittim. Ama bulamadım. Ve sonradan cami tarafına tekrardan geldiğim zaman babam olan Arif Güran'ın geldiğini fark ettim. Ve köylü de artık ayağa kalktı. Ve hepimiz birlikte Narin Güran'ı aramaya başladık.

Mahkeme Başkanı : Peki bu anlattığın süreç zarfında Salim Güran'ı hiç gördün mü?

Enes Güran : Hayır Sayın Hakim. Hiç görmedim.

Mahkeme Başkanı : Evde uyuduğun zaman da eve gelen çıkan herhangi bir ses duymadım dedin. Sadece bir arkadaşın aradı. Onunla da konuşup konuşmadığını hatırlıyor musun?

Enes Güran : Onunla telefonu açtım işte. Bana dedi Diyarbakır'a gittin. İşte unuttun bizi falan filan. Ben dedim uyuyorum işte sonra ararsın.

Mahkeme Başkanı : Kapattı.

Enes Güran : Tamam dedi kapattı dedi.

Mahkeme Başkanı : Şimdi Enes bu senin son anlattığın beyanın. Şimdi Nevzat gibi senin de aşamalarda birbiriyle çelişen beyanların var.

Enes Güran : Evet Sayın Hakim.

Mahkeme Başkanı : Niye bu çelişen beyanlarda bulunuyorsunuz?

Enes Güran : Sayın Hakim çelişkiden değil. Hatırlamadığım şeyler vardı o zaman. İfademde mesela söyleyemediğim şey. Hatırlamadığım şeyler vardı.

Mahkeme Başkanı : Ha o yüzden bu çelişki bir şey planlayıp da bir şey gizlediğiniz ya da sakladığınız için değil. Olayın şokuyla hatırlayamadığınız için.

Enes Güran : Aynen hakimim.

Mahkeme Başkanı : Anladım. Peki bu bakkal işte bakkalın açık olmadığını söyledi. Avukatlarımız iddiasında bakkalcının tanık olmamak için böyle bir beyanda bulunduğunu ya da evinde olabileceğini gibi şeyler söyledi. Burada da mesela bir çelişki var ama bakkala gittiniz.

Enes Güran : Bakkalın oğlu bile Şevket bile bakkalın açık olduğunu biliyordu.

Mahkeme Başkanı : Evet.

Enes Güran : Şahitlerim de vardır. Muhammed Yağmur, Muhammed Kaya da biliyor.

Mahkeme Başkanı : Şimdi bu HTS baz verilerine göre. Senin ben HTS baz verilerini okuyayım.

Enes Güran : Evet Sayın Hakim.

Mahkeme Başkanı : 14:30'da evdesin. 15:51'e kadar net olarak evde baz veriyorsun. Yani 16'ya kadar. 15:57'de Salim'in evine gidiyorsun. Neden?

Enes Güran : Kesinlikle Salim'in evine gitmedim Sayın Hakim ben.

Mahkeme Başkanı : Gitmedin. Sonra 16:04'de hatta şöyle söyleyeyim. 15:57'de sen Salim'in evine gittiğinde Salim de geliyor peşinden.

Enes Güran : Ben Salim Güran evine bugün kesinlikle gitmedim.

Mahkeme Başkanı : Sonra 16:04'de bilinmeyen bir yerde 16:11'de kendi evindesin. Ardından da 18:13 sıralarında okul civarındasın ve telefonun kapalı.

Enes Güran : Ben okul civarlarında olduğum için okul civarlarında olduğum zaman zaten saat 05:30 civarlarıydı Sayın Hakim.

Mahkeme Başkanı : 18:13.

Enes Güran : Tamam işte telefonum zaten 18:13 saat 5 civarları oluyor değil mi Sayın Hakim?

Mahkeme Başkanı : 6. 18 saat 6. 6'yı 10 geçe.

Enes Güran : 17:30 civarlarında zaten ben çeşme tarafındaydım. Pardon okul tarafındaydım. Oradan zaten Muhammed Yağmur'la cami tarafına dönüp tepeye çıktım.

Mahkeme Başkanı : Yani sen Salim'in evine hiç gitmedin.

Enes Güran : Hayır Sayın Hakim.

Mahkeme Başkanı : Şimdi bir diğer iddia. Yani bu iddia iddianamede sizlerin iştirak halinde öldürdüğünüzü belirtip neden öldürdüğünüze dair bir iddia yok. O yüzden muhtelif iddialar var. Birinci iddia Nevzat'ın iddiası Salim'le annenin ilişkisi. Diğer bir iddia da senin hoş olmayan bir görüntü içerisinde olduğunu ve Narin'in bunu gördüğü için senin Narin'i öldürdüğün iddiası var.

Enes Güran : Kesinlikle hayır Sayın Hakim öyle bir şey yok.

Mahkeme Başkanı : Yani öyle bir şey yok.

Enes Güran : Evet.

Mahkeme Başkanı : Salim'in kızlarıyla aranda bir gönül bağ var mı?

Enes Güran : Hayır Sayın Hakim.

Mahkeme Başkanı : Olay günü Salim'in kızlarını gördün mü?

Enes Güran : Hayır Sayın Hakim.

Mahkeme Başkanı : Onlarla herhangi bir cinsel ilişkiye girdin mi?

Enes Güran : Hayır Sayın Hakim.

Mahkeme Başkanı : Girmedin. Şimdi şöyle olabilir mi? Bak sadece ihtimalleri söylüyorum. Narin eve geldi. Enes abim nerede? Enes abim nerede dedi. Sen de o an ahırda hoş olmayan bir vaziyettesin. O da ahıra geldi. Sen de ahırda onu gördükten sonra ona karşı herhangi bir eylemde bulunmuş olabilir misin?

Enes Güran : Hayır Sayın Hakim. Ben hiç ahıra gitmedim ki.

Mahkeme Başkanı : Hiç ahıra gitmedin. Sen sadece uyuyorsun.

Enes Güran : Evet.

Mahkeme Başkanı : Şimdi tanıklar, Furkan, Ufuk olay saatinde birlikte olduklarını... Şimdi şöyle tekrar onu netleştireyim Enes. Sen ilk beyanında 16:30 gibi aramaya çıktım derken, daha sonraki beyanında ve huzurda verdiğin beyanında 18:30 hatta 19:00 hava karardıktan sonra ben Narin'i aramaya başladım diyorsun. Ama ilk beyanında 04:30'dan Narin'i aramaya başladım diyorsun.

Enes Güran : Sayın Hakimim işte ilk günler, bir de ikinci günler, üçüncü günler köyün içerisinde işte Narin'i ben bu saatte burada gördüm. Saat 4 civarlarında burada gördüm. Saat 6'da burada gördüm. Saat 3'te burada gördüm diyen insanlar vardı. Ve dördüncü günü jandarmaya gittiğimiz zaman saat konusunu pek hatırlamıyorum.

Mahkeme Başkanı : Anladım. Yani kafanın karışıklığının sebebi bu.

Enes Güran : Evet Sayın Hakimim.

Mahkeme Başkanı : Peki babanızla konuşmanızda yemek konuştun değil mi? Kısa bir süre. Çok kısa. 16 saniyelik bir konuşmanız var.

Enes Güran : Evet Sayın Hakimim. Annem konuştu kendisiyle.

Mahkeme Başkanı : Annenin telefonunu sen annenle aradın, annenin telefonunu annen konuştu.

Enes Güran : Evet Sayın Hakimim.

Mahkeme Başkanı : Peki daha sonra babanıza neden haber vermediniz? Babanız Narin'in kaçırıldığını üçüncü bir şahıstan öğreniyor. Kaçırıldığını demeyim, özür diliyorum kaybolduğunu.

Enes Güran : Evet Sayın Hakimim. Sayın Hakimim işte evde telefonum evde şarjlı olduğu için, üzerimde telefonun hiçbir şey olmadığı için aşağı taraftaki köy içerisinde Narin kardeşimi aradığım zaman yani aile bireylerinden biri aklımda değildi. Sadece Narin nerede?

Mahkeme Başkanı : Peki Enes, şimdi her şeyden uzaklaşarak bunu düşün. Şimdi yaklaşık 10 gün, 15 günlük ciddi bir sürede çok ciddi bir arayış var. Doğru mu? Dronlar, kameralar, binlerce ekipler, sizlerle sürekli irtibat. Ancak jandarmanın şöyle bir tutanağı var. Biz sürekli bir arayış içerisindeyken, başta Salim Güran olmak üzere aile üyelerinden sürekli bize yalnış telkinlerde bulunurdu. Ve biz sürekli onların yüzünden farklı mecralarda farklı arayışlar içerisine girdik. Böyle bir şeye şahit oldun mu?

Enes Güran : Hayır Sayın Hakimim.

Mahkeme Başkanı : Yani yanlış arayışlar içerisinde jandarmayı ya da oradaki kolluk kuvvetlerini başka bir alana yönlendirmeye, çalışma içerisine dair oldunuz mu?

Enes Güran : Sayın Hakimim, sadece ben ikinci günün gecesiydi. Askeri ekibimiz okul tarafındaydı. Ben gittim onların yanına. İşte dedim abim gönlüm rahat değildir. Köylü belki hiç bakmamıştır. Bak istediğim yerler vardır. Tamam dedi. İstediğin yere bakarız dedi. Ve sonradan onlarla birlikte bakılmayan yerlere de baktık biz. Hatta Nevzat Bahtiyar'ın o küçük pencere dediği yerden benle askeriye birlikte ben kendim girdim oraya. Ve orayı kontrol ettiğim zaman hiçbir şey görmedim. Ama ben girmediğim zaman Nevzat Bahtiyar'ın damda olduğunu fark ettim. Çıktığım zaman Nevzat Bahtiyar yoktu.

Mahkeme Başkanı : Ne zamandan bahsediyorsun?

Enes Güran : İkinci gündü.

Mahkeme Başkanı : İkinci günden bahsediyorsun. Yani o zaman Nevzat Bahtiyar sizi takip mi ediyordu? Onu mu demek istiyorsun?

Enes Güran : Sayın Hakimim, onu bilmiyorum. Hayır ben onu demiyorum. Biz askeri ekibimizle bir de jandarma ekibimizle aramaya girdiğim zaman ben onlara dedim ki gönlüm rahat değil. Ben yine aramak istiyorum. Tamam dedi Enes. Ve sonrasında Nevzat Bahtiyar'ın ahırına gittiğim zaman, Nevzat Bahtiyar'ın dediği o küçük pencere, arka tarafına bakan, saman tarafına bakan küçük pencere. O tarafta ben girdim. Askeri ekibimiz girmedi. Ama Nevzat Bahtiyar'ı girmeden önce damda gördüm. Çıktığım zaman ise Nevzat Bahtiyar'ı ben kesinlikle görmedim orada.

Mahkeme Başkanı : Tamam yani burada şüpheli bir hareket mi var?

Enes Güran : Sayın Hakimim, yani olay günü yani Nevzat Bahtiyar hiçbir şey aklımızdan geçmiyor. Yani Nevzat Bahtiyar kesinlikle aklımızdan geçmiyor.

Mahkeme Başkanı : Evet ben de onu soracağım. Yani şimdi sizin Salim, üvey annesinin bile kızınızı kaçırdı. Yani Narin'in kaçırıldığı ihtimalini söylerken, babanız ısrarla üvey kardeşlerinin zaten alkoliktir, ben onları sevmem, onlar yapmış derken bir tane kişi bile Nevzat'tan şüphelenmiyorsunuz.

Enes Güran : Doğrudur.

Mahkeme Başkanı : Doğru mu?

Enes Güran : Doğrudur.

Mahkeme Başkanı : Peki Nevzat neden öldürdü o zaman? Sonraki iddialarınızda ise Nevzat öldürdü diyorsunuz.

Enes Güran : Doğrudur.

Mahkeme Başkanı : Peki bu kadar şüphelenmediğiniz gözünüz önünde aranızda herhangi bir husumet dahi olmadığını iddia ettiğiniz olay anı itibariyle sonradaki husumetler, araba husumeti, kız kaçırma husumeti, eve kız getirdi, Askeri kız kaçırdı onları demiyorum.

Enes Güran : Evet Sayın Hakimim. Sayın Hakimim alışveriş vardı bu araba olayları.

Mahkeme Başkanı : Bak onları demedim ama onlar sonradan çıktı. Yani sıcağı sıcağına sizin bu araba olayı sizin nezdinizde çok ciddi bir olay değil ki. Nevzat'tan şüphelenmediniz. Nevzat'ın kardeşi Askeri eve kız getirdi, işte siz araya girdiniz, kız kaçırdı falan diyorsunuz iddia makamının iddialarını söylüyorum. Bu bir olay. İşte bunlar hiç aklınıza gelmedi ki Nevzat'tan hiç şüphelenmiyorsunuz doğru mu?

Enes Güran : Doğrudur Sayın Hakimim.

Mahkeme Başkanı : Peki hiç şüphelenmediniz bir adam neden sizin kardeşinizi öldürsün?

Enes Güran : Bilmiyorum.

Mahkeme Başkanı : Nevzat'ın iddiası doğru olabilir mi? Annenle ilişkisi olduğunu.

Enes Güran : Sayın Hakimim, böyle bir soru yani bana sorulmaz yani annemdir sonuçta.

Mahkeme Başkanı : Ama haklısın, saygı duyuyorum, özür diliyorum bu soruyu sorduğum için ama ben de adaletin ortaya çıkması için çabalıyorum. Sen de kasten öldürmekten yargılanıyorsun. Yani ben burada bir masum varsa bir masumu bir cani varsa bir cani bulma derdindeyim. Yani biz mahkeme hakla batılı masumla zalimi ayıt etmek derdindeyiz. O yüzden soruyorum kusura bakma. Yani Salim'in evine hiç gitmedin değil mi?

Enes Güran : Sayın Hakimim.

Mahkeme Başkanı : Peki neden bu baz verileri bu şekilde veriyor?

Enes Güran : Yani Sayın Hakimim, dediğim gibi uyku esnasında baz verdiği mesela internet açık olur ya da biri arar.

Mahkeme Başkanı : Ama öyle bir şey yok. Bak diyor ki sen şimdi ben evde uyuyorum diyorsun. Baz da diyor ki, evet evde uyuyor. Sabit diyor, evde hareket etmiyor diyor. Ama ne demiştim ben sana? 18:15:57'deyse o evet, evde uyuyor 2 saattir. evde dediği baz 15:57'de diyor ki Salim'in evine gitti.

Enes Güran : Sayın Hakimim, ben o gün kesinlikle Salim Güran'ın evine gitmedim.

Mahkeme Başkanı : Gitmediniz. Yani tekrar soruyorum gitmedin evet ama bunu tekrar sormak zorundayım ki büyük bir ihtimalle herkes aynı soruyu soracak. Sen o gün Salim'in evinde banyo yapmak, kolundaki ısırık izlerini yok etmek için mi gittin?

Enes Güran : Hayır Sayın Hakimim.

Mahkeme Başkanı : Gitmedim diyorsun ama soruyorum yani.

Enes Güran : Kolumdaki ısırığı Sayın Hakimim 3. gün yaptım.

Mahkeme Başkanı : Peki cezaevinden bir dilekçe gelmiş. Görmüşlerdir avukatlarımız bir tane vatandaş olayı çözmüş. Şöyle bir dilekçe yazmış çok hoşuma gitti sana da sorayım. Şimdi diyor Enes eğer sıcağı sıcağına kolunu ısırdıysa niye gözaltına alındığında kolunu ısırmamış diyor. Normal bir Vatandaşımız. 3 gün sonra sen kolunu ısırmışsın ya sonra cezaevinden bir hükümlü arkadaş bir dilekçe göndermiş. Diyor ki Enes sürekli böyle kolunu ısırıp kendine zarar veriyorsa cezaevinde niye kolunu ısırıp zarar vermedi diyor.

Enes Güran : Çünkü babamın beni merak ettiğini ve her gün babamı arayıp onunla görüntülü konuştuğum için yüzümde hiçbir şey görmemesini istedim. Yani ben cezaevinde suçlu olarak girmedim, ben kardeşim için Narin için girdim, adaleti yerine girdim.

Mahkeme Başkanı : Ama cezaevinde sürekli bir telkinlerin var Enes. Abican diye Eren'e söylüyorsun diş fırçasından bahsediyorsun. Sanki böyle bir telkinler bir dikkat edin abican fazla konuşma gibi böyle bir telkinlerin var. Bunun sebebi nedir?

Enes Güran : Sayın hakimim Eren'e de öyle konuşmam. Yani Eren'in benim cezaevime girmediğini bildiğim için ona çalışıyorum abican işte. Her hafta zaten geliyorsun sana çikolata veriyorum. Eren kardeşim cezaevine girdiğimi bilmesin için onunla kimseyle konuşma ve kimseyle gene dikkat et.

Mahkeme Başkanı : O manada söyledin. Evet. Peki bu diş fırçasıydı ben Narin'i öpmüştüm belki DNA çıkabilir abi. Onların sebebi nedir?

Enes Güran : DNA'nın ya da başka bir şeyin ne olduğunu hiç bilmiyorum ben.

Mahkeme Başkanı : Bu olayla öğrendin?

Enes Güran : Evet. Yani içimde kalmasın ailemin bilmesini istedim ben. Babamın abimin bilmesini istedim.

Mahkeme Başkanı : Dediğim gibi 29.08 tarihli beyanında huzurdaki beyanındaki gibi Tahir'le buluştuğunu, bakkala gittiğini falan derken sonraki beyanında bunlardan bahsetmeyip Ufuk, Furkan, Yusuf ile aklının orada oturduğunu, sonra annenin geldiğini diyorsun. Tanıklardan ikisi annen geldi derken bir tanesi hiç annenin geldiğinden bahsetmiyor.

Enes Güran : Furkan Kaya demiyor sayın hakimim. Ben cezaevindeyken hatırladım işte annem beni çağırdığı esnada Ufuk Kaya ve Yusuf Kaya yanımdayken Furkan Kaya yanımda değildi.

Mahkeme Başkanı : Yanınızda değildi.

Enes Güran : Evet sayın hakimim.

Mahkeme Başkanı : Yani ilk beyanında, bunları tekrar soruyorum çünkü ilk beyanındaki eksik olmasının sebebi olay şokuyla. Tekrar sormuyorum o zaman. Çünkü 25.08 tarihinde verdiğin beyan ile 29.08 tarihli verdiğin beyanda çok ciddi çelişkiler var. Bunun sebebi olayın sıcağı sıcağını hatırlayamaman normal bir beyanda bulunmandan kaynaklı. Doğru mu? Terlik muhabbetinden de bahsettin zaten.

Enes Güran : Evet hakimim.

Mahkeme Başkanı : Evet hakime hanım çok güzel bir şey. Şimdi sen Osman'a dediğin zaman bana Narin kayboldu diye söylediler. Ben Çarıklı'ya gittim diyor. Ama sen bu sanki Narin'in kaybolduğundan saat 8 gibi haberdar oldum diyorsun. Osman'la konuşmanızda Narin kayboldu diye Osman'a söylediniz mi?

Enes Güran : Evet hakimim.

Mahkeme Başkanı : Ama Osman neden bu şekilde beyanda bulunuyor?

Enes Güran : Sayın hakim Akın benimle arama çalışmasına girdiği zaman ben arama yaptığım zaman Narin'i çağırdığım zaman Akın Kaya yanımda vardı ve Osman kardeşim Akın Kaya'yı aradı. Ve Osman kardeşim işte Akın ben diyerek Osman arıyor Osman arıyor. Ve ben telefonu ondan alarak işte Narin kaybolmuş neredesin çabuk gel.

Mahkeme Başkanı : Peki bu köyde kadınlar birbirlerine giriyor. Sen de şahit olmuşsun. Bu olay nasıl oldu bir de bunu bize anlatır mısın?

Enes Güran : Tabii ki de sayın hakimim. Sayın hakimim işte Narin'in kaybettiğimizi askeri ekibimiz ve jandarma ekibimiz bize söyledi. Ve önceden sayın hakimim işte Melike Güran vardı. Yasemin Güran vardır bir de. Teyzem olur Yasemin Güran. İşte Yasemin Güran Bismil'den geliyorlar ta onca yoldan Narin'in işte annemle falan filan. Ve sonrasında sayın hakimim Melike Güran işte diyor ki ben biliyordum böyle olacağını. Ve Yasemin Güran da ona doğru işte biliyorsan niye konuşmadın doğruları konuşmadınız diye. Ve sonrasında ben de Yasemin Gül'ü pardon sayın hakimim Yasemin Gül'ü.

Mahkeme Başkanı : Yaser Gül, Yasemin Gül tamam.

Enes Güran : Onu alıp evimin tarafına iterek dedim yani ne yapmaya çalışıyorsunuz bu kavganın sırası mıdır? Onu iterek evimin tarafına ittim.

Mahkeme Başkanı : Peki kadınlar neyi biliyormuş da kendi aralarında kavga ediyorlar, böyle olacağını biliyorduk derken? Sen onu sormadın mı?

Enes Güran : Hayır sayın hakimim.

Mahkeme Başkanı : Neden sormadın?

Enes Güran : Çünkü kavga büyüdü sayın hakimim.

Mahkeme Başkanı : Büyüsün, ben çekerim bir köşeyi ya siz ne biliyorsunuz hayırdır, benim kardeşim kaybolmuş. Kim benim kardeşimi öldürmüş de kavga ediyorsunuz diye sormak aklına gelmedi mi?

Enes Güran : Sayın hakimim.

Mahkeme Başkanı : Ya sen delikanlı bir adamsın akıllı bir adamsın. Avukatlarımız ısrarla genç yaşında kepçe operatörü olacak kadar akıllı diyor. Fen lisesi mezunusun. Doğru mu? Yani her şeyi en ince haline kadar düşünen bir insansın. Avukatlarımız özellikle bütün direktörlerimiz senin zekandan bahsediyor bizlere. Bu kadar zeki insanın onu sormayıp da gidip onun ağzını kapatıp sus bakalım, konuşma mahiyetinde bir hareket göstermesi çok şüpheli bir hareket değil midir?

Enes Güran : Sayın hakimim. Melike Güran onu dediği zaman yani Yasemin Gül bana dedi. Ben Melike'nin dediğini duymadım. Yasemin Gül bana dedi ki, işte bunlar böyle diyor, böyle diyor, konuşsaydılar o zaman doğruyu konuşsaydılar. Ve sonrasında sayın hakimim Yasemin Gül'ü itelediğim zaman ve sonradan işte büyük kadınlar bu sefer işte Salihe Kaya, sonra tepedekilerdir, aşağıdakilerdir, teyzem Gül'dür. Bunlar bu sefer birbirine girdi.

Mahkeme Başkanı : Tabii mesela Maşallah Güran neyin oluyor senin?

Enes Güran : Yengem.

Mahkeme Başkanı : Yengen diyor ki, "Herkes her şeyi biliyor, beni konuşturmayın" daha sonra iki kişi zorla ağzını kapatıyor.

Enes Güran : Onu ben duymamışım sayın hakimim.

Mahkeme Başkanı : Birsen Güran neyin oluyor?

Enes Güran : Kuzenim.

Mahkeme Başkanı : Maşallah kızı.

Mahkeme Başkanı : O da diyor ki; "Biz mi yaptık sanki üzerimize gidiyorsunuz" diyor sonra onun da ağzını kapatıyorlar. Yani bir erkek güruhu kadınlar güruhunun ağzını kapatma derdinde. Sen, Fuat, Erhan değil mi?

Enes Güran : Yok sayın hakimim, yani zaten kadınlar kavga ettiği esnada bir tane kadın bağırdı. Erkekler sizin yüzünüzden birbirine girdi. Ondan sonra ben de o tarafa koştuğum esnada bir askerimiz gelip beni sıkarak tuttu. Ve babam onun elinden beni aldı. Beni bir yere oturttular. Ve sonradan beni alıp biz jandarmaya götürdüler zaten.

Mahkeme Başkanı : Peki Enes bazı kabul etmiyorsun. Kimseyle herhangi bir ilişkim yok diyorsun. Ahırda da değildim evdeydim diyorsun. Ve kardeşini öldürmediğini söylüyorsun. Peki neden burada sanıksın?

Enes Güran : Bilmiyorum sayın hakimim.

Mahkeme Başkanı : Yani bu iddianamelerde neden Muhammed Kaya değil, neden Birsen değil, neden bir başkası değil de evin içinde olan senin iddia makamı tarafından karşımıza getirildiğini düşündün mü hiç?

Enes Güran : Hayır.

Mahkeme Başkanı : Hiç düşünmedin. Ufuk'la Furkan'la ya da diğerleriyle telefonla konuştunuz mu olay günü buluşmak için?

Enes Güran : Buluşmak için mi?

Mahkeme Başkanı : Evet.

Enes Güran : Hayır, sayın hakimim.

Mahkeme Başkanı : Çünkü onlar senin telefonla aradığını, senin banyo yapacağını söylediğini falan söylüyorlar.

Enes Güran : Hayır, sayın hakimim.

Mahkeme Başkanı : Telefonla konuşmadınız mı? Yani sen direkt evden dışarı çıktığında onlar kapıda var mıydı?

Enes Güran : Sayın hakimim ben evden çıktığım zaman, ahırın yan tarafı olan tepeye çıktığım zaman, yan tarafta Ferhat Kaya, Ufuk Kaya bir de Yusuf Kaya'yı fark ettim.

Mahkeme Başkanı : Yani onlarla önceden konuşup planlamadınız?

Enes Güran : Hayır, sayın hakimim.

Mahkeme Başkanı : Ben mi yanlış hatırlıyorum?

Sanıklar müdafileri : Başkanım doğru diyor, ama aradım, ulaşamadım, sordum diyen biri var.

Enes Güran : Hatta ben ona diyorum beni ara işte hele bir telefonum nerede diye şey oluyor zaten orada.

Mahkeme Başkanı : Doğru hatırlıyorum, yani yanlış değil. Tamam. HTS'yle baz verilerini de kabul etmiyorsun. Peki bu olaydan sonra malum arama faaliyetlerinizle başladınız. Sonra ne yazık ki, Narin kızımızın cesedi bulundu. Bu ceset olayına da avukat bey bir düzeltme yaptı, ama biz hukuk nezdinde hep ceset diye bahsettiğimiz için yanlış anlaşılmasın. Hani Narin kızımızın cansız bedeni ama biz dilimizde hukukçu nezdinde hep ceset ve şey diye söylediğimiz için bu konuda yanlış anlaşılmasın. Peki ondan sonra kimden şüphelenin?

Enes Güran : Ondan sonra mı sayın hakimim?

Mahkeme Başkanı : Tabii şimdi aklı başında bir çocuksun bunu tekrar söylüyorum. Ben de bunu senin izlediğin videolarda verdiğin cevaplar ile ailenle görüşmende, mahkemeye verdiğin şu anki vaziyette bunu net bir şekilde görüyorum. Ve senin gibi zeki bir çocuğun bir konuda şüphelenip bir şeylerin peşinden gitmesi gerektiğini düşünüyorum. Ama buna ilişkin bir şey göremedim. Tam zıttı dosyada birbiriyle çelişen, birbirlerini doğrulamayan hatta ve hatta işte kadınlar olayına müdahale ederek sanki delilleri karartmaya çalışan bir Enes görüyorum.

Enes Güran : Hayır, sayın hakimim.

Mahkeme Başkanı : Neden kimden şüphelenme olayını hiç hissetmedin?

Enes Güran : İlk başta bize Salim Güran alındığı zaman arabasında kan bulundu dedin. Narin Güran'ın kanı falan bulundu dedi. Yani ben doğruyu konuşayım. Şüphelendim. Yani amcana kadar amcam da olsa ama benim kardeşim ortada yok. Ama sonradan kıl denildi.

Mahkeme Başkanı : Peki bunu Salim'e sordun mu?

Enes Güran : Hayır, sayın hakimim. Salim, ben zaten 4. günü alınıp 9. günü bırakıldım. Salim Güran'ı zaten görmedim bile.

Mahkeme Başkanı : Yani cezaevindeydi.

Enes Güran : Evet.

Mahkeme Başkanı : Nevzat ile hiç zaten şey görüşmediniz.

Enes Güran : Nevzat ile, 15. günü Nevzat camiye geldi.

Mahkeme Başkanı : Peki annenizle bu konuyu hiç konuştunuz mu?

Enes Güran : Nasıl sayın hakimim?

Mahkeme Başkanı : Bu iddialar çıktığında sen gözaltına alındığında annenle birlikte gözaltına alınmadınız mı? 

Enes Güran : Annemle birlikte gözaltına alındık.

Mahkeme Başkanı : O arada fırsat olduğunda annene sordun mu?

Enes Güran : Hayır fırsat olmadı ki sayın hakimim.

Mahkeme Başkanı : Yani, "Anne senin biriyle ilişkin var mı? Sen mi öldürdün kardeşimi?"" diye bir soru sordun mu?

Enes Güran : Sormadım.

Mahkeme Başkanı : Peki Salim Güran bu evin reisi midir?

Enes Güran : Yok.

Mahkeme Başkanı : Sizin evinizin köyün muhtarı dışında Salim Güran'ın bir sıfatı var mı?

Enes Güran : Yok. Yok.

Mahkeme Başkanı : Salim Güran'ın öldürme ihtimali var mı?

Enes Güran : Onu bilmiyorum, sayın hakimim.

Mahkeme Başkanı : Onu bilmiyorsun. Nevzat'ın öldürme ihtimali olup olmadığı hususunda bir fikrin var mı?

Enes Güran : O sadece araba satışından, orada benim aklım takıldı.

Mahkeme Başkanı : Peki araba satışından dolayı bir kardeşini öldürecek kadar cani midir?

Enes Güran : Bu büyüklerin olduğu cemaatte galiba babam Arif Güran işte Nevzat Bahtiyar kekelediği için işte kekeleme oğlum. Kusura bakmayın sayın savcım.

Mahkeme Başkanı : Söyle söyle küfür edebilirsin açıkça.

Enes Güran : Konuşma oğlum o parayı nereden getiriyorsan getireceksin. Hak'tır çünkü. Mahkeme açılmış parayı vermek zorundadır. Ve sonrasında sayın hakimim Nevzat Bahtiyar diyor ya işte ben tepeye çıktım. İşte Yüksel Güran bir de Arif Güran'a parayı ben orada verdim. Orada ben de oradaydım sayın hakimim. Nevzat Bahtiyar gelip parayı babama verdi. Babam da parayı anneme verdi. Ve Nevzat Bahtiyar aramıza oturdu. Hiç sıkıntı yok dedi. İsterse hiç gelmezsin dedi Nevzat Bahtiyar.

Mahkeme Başkanı : Tamam. Zaten şöyle bir şey var Enes. Babanın yapmış olduğu basın açıklamasında abinin yapmış olduğu ifadelerde senin söylemiş olduğun cümlene de siz söyle başlıyorsunuz. Nevzat kim ki diyorsunuz? Nevzat kim ki bizim evimize gelecek? Hatta abinin çok vahim bir cümlesi var. Nevzat kim ki bizim tavuğumuza bile bakacak bir cümlesi var. Yani Nevzat kim ki dediğiniz adamdan parayı aldıktan sonraki parayı almışsınız. Zaten Nevzat kim ki? Bu adam ezik büzük ki hali hazırda da kekeme olduğuna hepimiz kanaat getirdik. Böyle bir insanın kardeşini öldürecek kadar işte karşı tarafın yani avukatlarının iddiasını soruyorum. İşte herkesin köyden çıktığını belirtip kıza para verip onun yanına çekip böyle bir plan yapacağına kanaatin var mı senin?

Enes Güran : Var sayın hakim. Önceden para vermiş zaten.

Mahkeme Başkanı : Para vermekte ne beis var?

Enes Güran : Yani para verip kendini ona alıştırmış.

Mahkeme Başkanı : Yani o zaman 1-2 haftadır planlıyor diyorsun.

Enes Güran : Evet.

Mahkeme Başkanı : Kaç para ki? 50.000 TL'den bahsediyoruz. Kaç para ki Nevzat şeyi öldürecek kadar gözü dönüyor bu araba olayında?

Enes Güran : Hatta o kelimeyi babam ona o kelimeyi kullandığı için oradan...

Mahkeme Başkanı : Bu olay ne zaman oldu?

Enes Güran : Hani sayın hakimim ben Malatya'ya gitmeden önce oldu.

Mahkeme Başkanı : Tahminen?

Enes Güran : Tahminen bir 4 aydır.

Mahkeme Başkanı : 4 aydır. Yani sen o olaydan dolayı kinlendi, plan yaptığını düşünüyorsun. Evet. Ama Nevzat'ın öldürüp öldürmediği konusunda da senin de bir kanaatin yok.

Enes Güran : Aynen.

Mahkeme Başkanı : Narin'in arkadaşları, Narin'in pedagog eşliğinden beyanlarında Narin'in gerçekten ismi gibi Narin olduğunu, yabancıların arabasına binmeyeceğini, yabancılarla görüşmeyeceğini söylüyor. Narin Nevzat'ı yabancı biri görür mü görmez mi?

Enes Güran : Yani para vermişse görmez, sayın hakimim.

Mahkeme Başkanı : Para vermişse görmez. Peki sen daha önce bu olaylardan önce, bu çıkmadan önce Narin'in, Nevzat'ın para verdiğini gördün mü, şahit oldun mu? Narin söyledi mi böyle bir şey?

Enes Güran : Annem söyledi. Nevzat para veriyor dedi.

Mahkeme Başkanı : E, Nevzat kim ki Narin'e para veriyor hesap sormadınız mı?

Enes Güran : Yok sayın hakimim zaten biz mahkeme çıkmadan önce annem bunu bana dedi.

Mahkeme Başkanı : Mahkeme olayından önce, Narin kızımız kaybolmadan önce sen Nevzat'ın Narin'e para verdiğini gördün mü, duydun mu?

Enes Güran : Hakimim ben o zaman Malatya Arguvan'daydım.

Mahkeme Başkanı : Peki Narin bunu size söylemedi mi?

Enes Güran : Hayır.

Mahkeme Başkanı : Abi Nevzat bana para veriyor diye?

Enes Güran : Ben zaten 20'sinde geldim.

Mahkeme Başkanı : Sen değilse de Muhammed Eren'e söyler. Osman'a söyler. Yüksel'e söyler. Arif'e söyler. Yani senin nezdinde demiyorum. Sen zaten il dışındasın. Onlardan da duymadınız mı?

Enes Güran : Hayır, sayın hakimim.

Mahkeme Başkanı : Çünkü şöyle bir şey var. Eğer Nevzat para verecek olsa, sizin bu aile yapınızdan siz bu parayı duyacak olsanız, Nevzat kim ki cümlesiyle hayırdır kardeşim niye para veriyorsunuz diye çok rahat hesap sorarsınız. Ve bu hesabı benim anladığım Eren bile sorabilir.

Enes Güran : Sayın hakimim bana hiç söylenmedi.

Mahkeme Başkanı : Hiç söylenmedi.

Enes Güran : Evet.

Mahkeme Başkanı : Var mı hakimlerimizden soru? Yok. Sayın savcım sormak istediğiniz bir şey var mı? Buyurun mikrofona yakın sayın savcım.

## Duruşma Savcısı

Duruşma Savcısı : Enes Güran. Fen Teknoloji Lisesi mezunu musun?

Enes Güran : Evet.

Duruşma Savcısı : Başkanımın da altını çizdiği gibi 18 sıraları 5 mi demek derken ne demek istedin? 18 sıraları 6'dır değil mi?

Enes Güran : Evet.

Duruşma Savcısı : Sen şimdi bu 23 Ağustos jandarma görüşme tutanağı, 24 Ağustos bilgi alma tutanağı, 25 Ağustos yine bilgi alma tutanağı, 3 tutanakta da üst üste 16:30 sıralarında Narin'i aradığını söylüyorsun değil mi? Seni aklı başında bir çocuk olarak gördüğümüz için soruyorum bu soruyu.

Enes Güran : Evet, aynen.

Duruşma Savcısı : Bize garip gelen noktalar bunlar. 16:30'da aradığını söylüyorsun dışarıda?

Enes Güran : Evet, aynen.

Duruşma Savcısı : Kabul etmiyorsun bunu değil mi?

Enes Güran : Evet.

Duruşma Savcısı : Kabul etmiyorsun. Neden yanlış beyan verdin? kafam karıştı diyorsun öyle mi?

Enes Güran : Kardeşim kaybolduğunda hala bulunamadığı için yani bir de mahalle insanları çoğunlukla saatleri, saati ben burada gördüm, bu saatte burada gördüm, bu saatte burada gördüm.

Duruşma Savcısı : Yani ilk 3 gün boyunca aynı ifadeyi verme sebebin bu.

Enes Güran : Evet aynen.

Duruşma Savcısı : 1 gün değil, 2 gün değil. 3 gün boyunca 16:30'da kardeşimi arıyordum demen tamamen kafa karışıklığı?

Enes Güran : Evet, aynen.

Duruşma Savcısı : Tamam. Evden kaç kere çıktın sen?

Enes Güran : 2 kere sayın Hakim. 2 kere.

Duruşma Savcısı : Birincisi? Saat 4'de. 16'da çıktın 15:57 civarı. O zaman baz tutuyor değil mi?

Enes Güran : Baz mı?

Duruşma Savcısı : Evet.

Enes Güran : Nasıl yani?

Duruşma Savcısı : Bizim size iddia ettiğimiz baz bilgisi var ya 15:57'de Salim'in evine gittiğin.

Enes Güran : Evet.

Duruşma Savcısı : O tutuyor. Yok yani. 16'da çıktım diyorsun.

Enes Güran : Evine gitmemişim.

Duruşma Savcısı : O tutuyor. Evden çıktığından bahsediyorum. Bir kere çıktın?

Enes Güran : Evet.

Duruşma Savcısı : Ne yaptın bir kere çıktığında?

Enes Güran : Aşağı indim işte çeşme tarafına Tahir kaya, bakkala gittim enerji içeceği istedim.

Duruşma Savcısı : Kaçta geldin geri?

Enes Güran : 05:30'da.

Duruşma Savcısı : 05:30'da geldin. Geri ne zaman çıktın?

Enes Güran : 6 civarlarında.

Duruşma Savcısı : 05:30'da çıktın. Osman'ı kaçta aradım dedin?

Enes Güran : Osman'ı aradığımı hatırlamıyorum.

Duruşma Savcısı : 05:30-06:00 arası olabilir mi?

Enes Güran : Eve geldiğim zaman işte, telefonumu kapatıp deliyim ve ayakkabım yırtık olduğunu fark ettim. Zaman Osman kardeşimi aradım.

Duruşma Savcısı : X-XXX-XXX-26-21 Osman'ın numarası değil mi?

Enes Güran : Bilmiyorum.

Duruşma Savcısı : Osman kullanıyor bu numarayı. Evet. 26-21 sonu.

Enes Güran : Evet.

Duruşma Savcısı : 17:49'da görüşmeniz var. 10 saniye. 17:50'de görüşmeniz var. 4 dakika. 220 saniye. Değil mi?

Enes Güran : Evet.

Duruşma Savcısı : Bir terlik muhabbeti var değil mi arada?

Enes Güran : Evet.

Duruşma Savcısı : 42 numara terlik almasını söylemişsin Çarıklı'dan. 4 dakika bir terlik konusunu konuşmuş olamazsın. Ne konuştun 4 dakika?

Enes Güran : Şey işte Osman kardeşim Ongözlü'de olduğu için, ben de Ongözlü'de arkadaşlarım olduğu için arkadaşlarımla da konuşmuşum.

Duruşma Savcısı : Ongözlü'de kardeşin garsonluk yapıyor?

Enes Güran : Doğrudur.

Duruşma Savcısı : O esnada. Ne yaptın? Anlayamadım yani. 4 dakika ne konuştun diyorum.

Enes Güran : Tamam işte arkadaşlarım da o kafede çalıştığı için işte telefonu ona vermesini istedim yani Osman kardeşime kimse karışmasın ya da laf etmesin diye.

Duruşma Savcısı : Şarjının az olduğu bir zaman bu konuya girdin yani. Şarjın azdı değil mi? Öyle söylüyorsun.

Enes Güran : Evet.

Duruşma Savcısı : 17:43'de babanla ne konuştun 24 saniye?

Enes Güran : Onu hatırlamıyorum Sayın Hakimim.

Duruşma Savcısı : Tam terlikten 3-5 dakika önce.

Enes Güran : Onu hatırlamıyorum Sayın Hakimim.

Duruşma Savcısı : Şarjın kaçta bitti o zaman?

Enes Güran : 6 civarlarında Sayın Hakim.

Duruşma Savcısı : 6 civarları. Baza göre 18:13'de bittiği söyleniyor, telefonunun kapandığı. Uyuşuyor değil mi tam olarak?

Enes Güran : Baza ona göre bakarsan Sayın Savcım.

Duruşma Savcısı : Bazı sormuyorum. Telefonunun kapandığı saat 18:13 yazıyor bizde.

Enes Güran : Evet Sayın Hakim.

Duruşma Savcısı : Uyuşuyor mu?

Enes Güran : Yani uyuşmuyor.

Duruşma Savcısı : Kaçta kapandı? 6 civarı kapandı diyorsun.

Enes Güran : Evet doğrudur.

Duruşma Savcısı : Peki telefonunun kapandığında bize az önce dedin ki annem babama yemeğe gelip gelmeyeceğini sormamı istedi.

Enes Güran : Evet.

Duruşma Savcısı : Tam o sırada ben arayamadım kapandı dedin değil mi? Sonra annenin telefonundan görüştün değil mi?

Enes Güran : Evet annem görüştü onunla.

Duruşma Savcısı : Annen görüştü.

Enes Güran : Evet.

Duruşma Savcısı : Yalnız en son görüşme Osman'la görüştüğün 4 dakika.

Enes Güran : Benim telefonum ben kendi telefonumda babamı aramadım ki hani.

Duruşma Savcısı : Babanı aramışsın zaten 17:43'te.

Enes Güran : Hani ben babamı arayıp da hani yemeğe geç gelecek misiniz falan bir şey demedim.

Duruşma Savcısı : Babanla ne konuştuğunu hatırlamıyorsun o dakika içerisinde.

Enes Güran : Ve sayın hakimim, sayın savcım sadece annem mi bana gelip işte oğlum işte babanla abini bir ara, yemeğe yetişecekler mi yetişmeyecekler mi? Onun için ben de telefonuma baktım aslında telefonun kapandığını fark ettim. Ve anneme söyleyerek kendi telefonunu getir senin telefondan arayalım. Ve annemin okuma yazması olmadığı için ben arayıp anneme verdim. Annem onunla konuştu.

Duruşma Savcısı : Tamam telefonun 18:13'te 6 civarı kapandı. Ne yaptın o sırada?

Enes Güran : Telefonumu şarja taktım.

Duruşma Savcısı : Evdeydin.

Enes Güran : Evet evdeydim.

Duruşma Savcısı : Niye şarja takmadın?

Enes Güran : Şarja taktım.

Duruşma Savcısı : Kaçta açtın telefonunu?

Enes Güran : O gün işte Narin'in kaybolduğunu fark ettiğimizde.

Duruşma Savcısı : Telefonu 19:11'e kadar açmıyorsun ortalama. Bir saat. Bir saat şarjda telefonun. İfadelerine göre konuşuyorum senin. 19:11'de Narin'in ortalama kaybolduğunu fark ediyorsunuz akşam yemeği değil mi? O bazlarda konuşuyorsun o saatlerde. Annen telefonunu getiriyor sana. Annenin telefonundan görüşmeye başlıyorsunuz değil mi? Onunla bununla arıyorsunuz öyle bahsetmişsin. "Annem okuma yazma bilmediği için bize birilerini aramamızı söyledi" dedin değil mi?

Enes Güran : Evet.

Duruşma Savcısı : Ondan bahsettin. Kendin o zaman niye telefonunu açıp insanlara ulaşmak için yardım etmiyorsun tek başına?

Enes Güran : Aklıma gelmedi.

Duruşma Savcısı : Niye tek başına annen arıyor insanları? Niye o sırada babanı arayıp haber vermiyorsun mesela?

Enes Güran : Aklıma gelmedi, yani böyle bir durumun hala olduğunu bile bilmiyorum.

Duruşma Savcısı : Kardeşin kayboldu. Telefonun şarjda takılı olup dolduğu halde telefonunu almadan dışarı çıktın öyle mi?

Enes Güran : Evet.

Duruşma Savcısı : Telefonu almadan, telefonu açmadan kardeşini aramaya çıktın dışarıya.

Sanık müdafileri : Sayın Başkanım çok özür dilerim. Bir izlem hatası söz konusu olacak. O esnada kayıp bilgisi yok. Ama şimdi Enes de her soruya cevap verme arzusunda, tatmin etme arzusunda. Şimdi yine bir o basındaki şeyler gibi olacak.

Duruşma Savcısı : Kayıp hırsı derken anlayamadım.

Av. Mahir Akbilek : Sorular, sorular sayın başkanım hani sorular demeyi ben unuttum meslektaşımızın da belirttiği gibi. Hem şimdi biz çok özür dilerim. Biz 206/2a'dan bahsetmedik bilerek. Biz de tabii ki kendi aramızda tartıştık, ettik. Örneğin, hepimizde dayanağı olarak aslında hani savunulan kavram olarak söyleyeceğim. Savunulan ve niteliği, hukuken niteliği belirsiz. Kimler tarafından tanzim edildiği belirsiz. Şimdi bu evrağı biz peşinen hepimiz maddi delil olarak, hükme esas bir delil olarak kabul ettik mi ki onu bir omurga olarak görüp onun üzerine ilerliyoruz?

Duruşma Savcısı : Birincisi HTS ve BAZ ayrı şeylerdir özür dileyerek başkanım. HTS ve baz ayrıdır. Benim Enes'e bahsettiğim şeyler tamamen HTS ile alakalı. Yani BTK'dan gelen cevaplarda 17:43 aramasının belirtildiği. Bunu kabul ediyor musunuz?

Av. Mahir Akbilek : Çok ciddiyim, bakınız. Emin olun, emin olun. Şimdi söz hakkı gelince CMK'daki usül takip edilip sıra bize geldiği vakit. Biz sizin doğru bildiğinizi zannettiğiniz, belge olduğunu zannettiğiniz evrağın ne kadar inanılmaz, inanamayacaksınız diyeceksiniz ki.

Duruşma Savcısı : Ama bakın bana cevap doğuyor sayın avukatım. Ben HTS'den bahsediyorum, bazdan değil HTS'den bahsediyorum.

Mahkeme Başkanı : Ben sizin yazılı savunmanızı çok iyi okuduğum için siz o bazlarla... Yok yok ben tutukluyorum, bir dakika. Ben Nevzat'a soru sorarken bir yerde bir atıf yaptım. Size yaptım değil mi? Kabul ediyor musunuz bazı dedim. Kabul etmemek şartıyla dediniz. Siz kabul etmemek şartıyla kabul etmediğiniz bir bazla soru sorarken iddianamede bu delil olan biz bununla soru sormamızda neden abes karşıladınız?

Av. Mahir Akbilek : Estağfurullah bakın yine yanlış anlaşılıyor sayın başkanım.

Mahkeme Başkanı : Ben He? Yok tamam sıkıntı yok. Yani ben... Biz o yüzden ben size o atfı..

[Kaydımızın bu kısmında sanık müdafileri, katılan vekilleri ve mahkeme heyeti tarafından konuşulunca, tüm seslerin birbirine girmesi nedeniyle 2 dk döküm yapılamadı.]{.bracket-box}

Sanık Enes müdafi Av. Mahir Akbilek : Hepimizin bildiği bir geçmiş de var. O geçmişteki hatalar zaten önümüzde. Her birimiz, hukukçular, tüm hukukçular, tüm halk. Hepimiz bunu kendi...

Mahkeme Başkanı : Tamam ya neticeye gelelim. Savunmaya gidelim.

Sanık Enes müdafi Av. Mahir Akbilek : Sayın başkanım. Dar alan çalışmasından direkt yola çıkarak sorulan sorularda en azından ilgili sanığın bir düşünmesine fırsat verilse... Tamam. En azından. Sorularda bir 5-10 saniye nefes alıp düşün. Akabinde cevap verebiliriz. sanığın fen lisesi mezunu olması onun Einstein olduğu anlamına mı gelir?

Mahkeme Başkanı : Keşke bu hassasiyeti Nevzat Bahtiyar'a sorarken de tak tak tak değildi. Bir nefes almasını bekleseydiniz. Aynı hassasiyeti Nevzat Bahtiyar'da gösterseydiniz samimi olduğunuza çok kanaat getirirdim. Ancak samimi olduğunuzu düşünmüyorum.

Duruşma Savcısı : Osman'la 4 dakikalık görüşmesinde arkadaşlarım arkadaşlarınla da görüştüm diye açıkladın değil mi? O 4 dakikanın o kadar uzun olduğunu ondan dolayı belirttin. O detaya girecek kadar detaylı bilgiye sahip olduğu için doğal olarak HTS'deki 17:43'te babanla ne konuştun diye sorabilecek noktada olduğumu hissediyorum kendimi. Ve HTS'ye yönelik soruyorum. Baz iddianameyi mahkeme kabul ettiyse baza yönelik sorular benim için mübahtır ve sorarım.

Mahkeme Başkanı : Buyurun savcım.

Duruşma Savcısı : Niye terlik istedin?

Enes Güran : Ayakkabım, ayakkabım yırtık olduğu için. Malatya Arguvan'dan geldiğim için.

Duruşma Savcısı : Bu kadar?

Enes Güran : Evet. Gurbetten geldiğim için.

Duruşma Savcısı : Getirdi mi peki terliği?

Enes Güran : Getirmişti. Ama giymedim.

Duruşma Savcısı : Giymedin. Tamam. Sorumuz yoktur başkanım sağ olun. Tamam teşekkür ederiz.

Mahkeme Başkanı : Diyarbakır Barosu'ndan başlıyoruz soru sormaya. Şimdi biz mahkeme olarak sanık kanun hiçbirine ait etmiyoruz. Ben Nevzat'a tuttuğum tutumu Enes'e de tuttum. Farklı bir izlenimi olan varsa çıksın. Başkanım biz şu izlenimi aldık desin. Ben şu an cübbemi burada bırakırım. Ben çok netim. Şu an cübbemi bırakır bu davadan çekilirim. Aynı tutumumu Yüksel'e de sunacağım. Aynı tutumumu Salim'e de devam edeceğim. Pazartesi günü duruşmam olan falanca bir dosyada da aynı tutumumu yapacağım. Ben hiçbir dosyaya sanık bazlı bakmıyorum. Benim nezdimde bu dosyanın diğer dosyadan ayrı bir özelliği yok. Zaten ben öyle bir özellik taşırsam da bu mesleği bırakırım. Çok net söylüyorum. Biriniz burada Diyarbakır Barosu avukatları dahil biri Mahkeme Başkanı'nın bu dosyada hassasiyetini başka bir dosyada kullanmadığını desin, ben bu dosyayı bırakırım. Diyebilir mi? Diyarbakır Barosu'ndan biri bu cümleyi kursun. Açık net söylüyorum. Bugün duruşmayı erteliyorum. Duruşmadan çekilirim. Ben her dosyaya aynı hassasiyeti gösteririm. Ben her dosya şunu izah edeyim. Akıldaki soru işaretleri gitsin. aynısını basına da söylüyorum. Arkadaşlar bizim için bu dosya diğer mahkememizin dört düz dosyasından bir tanesi. Sizin nezdinizde bu dosya daha ehemmiyet kesbettiği için biz de daha hassasiyet gösteriyoruz. Biz pazartesi de devam edeceğiz. Pazartesi de tutuklu dosyamız var. Cinayet dosyamız var. O dosyada aynı hassasiyeti göstereceğiz. Ben tüm sanıklara aynı saygıyı gösteririm. Uyuşturucu satıcısına da aynı saygıyı gösterdim. Çocuk öldüren iddiasına da eşi öldüren iddiasına da aynı saygıyı gösterdim. O yüzden mahkememizin ve ithamının, ben izah ediyorum. Savunmak için söylemiyorum. Bu iddialara hiç girmeyelim. Aklımda böyle bir soru da olmasın. Aynı sana gösterdiğim saygıyı Nevzat'a da gösterdim. Babamın oğlu değil. Sen de babamın oğlu değilsin. İlk defa görüyorum seni. Yüksel Hanım'a da göstereceğim. Salim Bey'e de göstereceğim. Zaten ben Diyarbakır'lı değilim. Belki bu sene, belki seneye de gideceğim. Aklınızda dedikodu olacak bir husus varsa açıkça söylesin ki, mahkeme eğiliminin hiçbir zan altında kalmadığını herkes bilsin yani. Onu net bir şekilde söyleyeyim. Ki, Nahit Bey de biliyor. Siz de biliyorsunuz. Başından beri de size şeffafiyet gösterdim. Her dediğinizde, amenna dedim, nasıl yapardım? Ben bu izlenimi aldığım için söylüyorum.

## Diyarbakır Barosu

### Av. Aydın Özdemir

Av. Aydın Özdemir : Enes olay günü 17:30 civarında ben eve geri döndüm dedin. Çıktıktan sonra ben geri döndüm dedin. Eve geri döndüğünde evde kimse yok muydu?

Enes Güran : Hiçbir şey görmedim.

Av. Aydın Özdemir : Sizin evinizde, kendi evinizi soruyorum. Geri döndüğünüzde hiç kimseyi görmediniz mi? Anneniz?

Enes Güran : Hayır, görmedim.

Av. Aydın Özdemir : Hediye Güran'ı gördünüz mü?

Enes Güran : Hayır, görmedim.

Av. Aydın Özdemir : Hediye Güran'ı görmediniz mi?

Enes Güran : Görmedim.

Av. Aydın Özdemir : Peki Hediye Hanım, o gün kaç kere gitti geldi?

Enes Güran : Ben bir kere sadece gördüm.

Av. Aydın Özdemir : Siz sadece bir kere gördünüz.

Enes Güran : O da uyandığım esnada evimin içinde gördüm.

Av. Aydın Özdemir : Sonrasında bir daha gelmedi mi?

Enes Güran : Bilmiyorum ben onu.

Av. Aydın Özdemir : 17:30'da geldiğinde Hediye orada değildi ama netsiniz bu konuda. Tamam. Kolunuzu nasıl ısırdınız? Gösterebilir misiniz?

Enes Güran : Bırakayım mı?

Mahkeme Başkanı : Bırak, bırak.

Enes Güran : Göstermenize gerek yok.

Mahkeme Başkanı : Montunu da çıkar. Net bir şekilde gösterebilirsin. Kameraya çekelim.

Enes Güran : Koltuktayım. Böyle oturuyorum. Böyle ısırıyorum. Koltuğa bırakıyorum. Sırf ki pencere tarafında babam oturuyor. Ağlama sesi bana geldiği için, tekrardan üzülmesin, geceleri yatsın diye kolumu sert bir şekilde ısırarak koltuğa doğru bıraktım.

Av. Aydın Özdemir : Nereye ısırdınız?

Enes Güran : Buraya, bakın.

Av. Aydın Özdemir : Bir gösterebilir misiniz?

Enes Güran : Bakın, hala da, bakın.

Av. Aydın Özdemir : Tamam. Peki, ısırdığınızda vücudunuz sizi geri itmedi mi?

Enes Güran : Yok.

Av. Aydın Özdemir : Diş izi çıkmış 3 tane ve adli tıp raporuna göre en az aradan 3 ile 6 gün geçmiş. Buna rağmen belirgin bir şekilde, fotoğraflardan diş izleri net bir şekilde görülüyor. Sadece yetişkin mi değil mi o tespit edilemiyor. Acı seviyesi belli bir aşama geldikten sonra siz isteseniz de istemeseniz vücudunuz sizi geri iter.

Mahkeme Başkanı : Avukat Bey, bu soru çok şey değil.

Av. Aydın Özdemir : İtmedi.

Mahkeme Başkanı : Olayın başka bir vahametiyle bazen insan vurulduğunu 1 dakika sonra anlıyor, bazen 5 dakika sonra anlıyor. Tıp ben, tıpa girmeyelim. Bunu geçelim.

Av. Aydın Özdemir : Başkanım, bazı makaleler var. Böyle değil, daha sonra biz beyan olarak sordururuz.

Mahkeme Başkanı : Bana tıp bunun bu konusunu biz tartışmayalım. Bırakın tıp tartışsın.

Av. Aydın Özdemir : Tıplı bir veri olduğu için sorduk.

Av. Aydın Özdemir : Mısır tarlasına olay günü. Saat kaçta gittiniz?

Enes Güran : Gece saatleriydi.

Av. Aydın Özdemir : Gece saat. Tahmini?

Enes Güran : Telefon yoktu.

Av. Aydın Özdemir : Tamam. Üzerinizde ne kıyafet vardı gece saatlerinde?

Enes Güran : Bu tarafında Kolombiya yazan.

Av. Aydın Özdemir : Biraz daha sesi duyamıyorum.

Enes Güran : Bu tarafında Kolombiya yazan bir kazak vardı. Siyahtı hepsi. Bir de şu pantolonum.

Av. Aydın Özdemir : Siyah bir kazak. Mont var mıydı?

Enes Güran : Yok.

Av. Aydın Özdemir : Mont yoktu?

Enes Güran : Yok.

Av. Aydın Özdemir : Peki, kazak olmasına rağmen sırtınızdaki izleri nasıl açıklayabilirsiniz?

Enes Güran : Sırtımdaki izler de zaten ikinci gün, üçüncü gün ahır taraflarına girdik. Nevzat Bahtiyar'ın ahırına girdik. Ve Süheyla Güran'ın evinin tarafındaki ahırlara girdik. Hiç girilmemişti. O taraflarda benimle Yunus Karacoşan. Yunus Karacoşan'la hatta bu Süheyla Güran'ın evinin tarafında olan ahırlara girdiğimiz zaman Yunus Karacoşan da orada gördü zaten. Hepsi çivilidir, tahtalıdır. Yıkık bir yerdir.

Av. Aydın Özdemir : Peki, Mısır, o izler, sırtınızdaki izleri soruyorum. Mısır tarlasında olmadı mı?

Enes Güran : Yok.

Av. Aydın Özdemir : Mısır tarlasında olmadı. Tamam, teşekkürler. Ben başka sorum yok. Ben teşekkür ederim.

Mahkeme Başkanı : Adınızı söyler misiniz? Buyurun.

### Av. Asya Cemre Işık

Av. Asya Cemre Işık : Öğlen yemeği yediniz, olay günü. Sonra Narin saate baktı, değil mi? Saati fark etti.

Enes Güran : Evet.

Av. Asya Cemre Işık : Sonra ne dedi?

Enes Güran : Anne, işte saat geç oldu. Ben de işte camiye gideceğim. Annem dedi, hava sıcaktır kızım, gitme bugün. Ve annem işte, Narin ısrarla Hatice, Fatma camiye gidiyor diye ben de gitmek istiyorum dedi. Annem de tamam dedi.

Av. Asya Cemre Işık : Peki, Narin şöyle parmaklarını gösterip, saat dörde kadar kurs var, ben oraya gideyim dedi mi?

Enes Güran : Öyle bir şey görmedim ben.

Av. Asya Cemre Işık : Peki. O gün işten geldiniz, çalışıyorsunuz değil mi Malatya'da? Maaş alıyor musunuz?

Enes Güran : Alıyorum.

Av. Asya Cemre Işık : Nasıl alıyorsunuz maaşı?

Enes Güran : Aylık.

Av. Asya Cemre Işık : Aylık. Maaşınızı alıp geldiniz mi?

Enes Güran : Yok.

Av. Asya Cemre Işık : Neden almadınız maaşınızı?

Enes Güran : Ödeme yapamadı. Zor durumdaydı. Ben de ısrarla istemedim ondan para.

Av. Asya Cemre Işık : Paranız olmadan geldiniz?

Enes Güran : Evet, Bana Diyarbakır'a işte gittiğin zaman aradan 3-4 gün işte düğüne kala yetişmeden sana atarım dedi. Tamam dedim.

Av. Asya Cemre Işık : Üzerinizde hiç para olmadan Malatya'dan Diyarbakır'a geldiniz?

Enes Güran : Babam para atmıştı.

Av. Asya Cemre Işık : Tamam. Peki o zaman sabah neden bir daha babanız size 200 TL verdi ve bunu burada vurguladınız?

Enes Güran : Yani nakit olarak üzerime veriyor. Babam hesabıma para attı. Nakit olarak üzerimde para olmadığını biliyor adam. Yani oğluyum onun için çalışıyorum. Aylarca onun için çalışıyorum 200 TL yani sabah da.

Av. Asya Cemre Işık : Muhammed Yağmur'la görüştüğünüzü söylediniz evden çıktığınızda. Muhammed Yağmur'la görüşmeniz ne kadar sürdü?

Enes Güran : Yani sadece onunla mı yoksa Şevket?

Av. Asya Cemre Işık : Muhammed Yağmur'la.

Enes Güran : Yani bir yarım saat falan oldu.

Av. Asya Cemre Işık : Daha önceki beyanlarınızda 1.5 saat görüştüğünüzü söylediniz. Neden beyanınızı şu an değiştiriyorsunuz?

Enes Güran : Saatleri pek hatırlamıyorum.

Av. Asya Cemre Işık : 1.5 saat ile yarım saat arasında çok ciddi bir fark var. Biriyle yarım saat oturmanızla 1.5 saat oturmanız arasında ciddi bir fark var. Bunu hatırlamıyorum diye açıklamanız ne kadar doğru?

Enes Güran : Çok doğru.

Mahkeme Başkanı : Yorumlu sorulardan uzak duralım yani. Bu soruyu geçiyoruz, evet.

Av. Asya Cemre Işık : Abin Osman'dan ne zaman terlik istedin?

Enes Güran : Ben mi? Tamam zaten. Akşam civarlarında ben eve geldim işte. Saat beş buçuk civarlarında eve geliyorum ya. O zaman ben o kardeşimden terlik istedim.

Av. Asya Cemre Işık : Osman'dan terlik istedikten sonra tekrar dışarı çıktın mı?

Enes Güran : Evet.

Av. Asya Cemre Işık : Peki Osman'dan terlik isterken tekrar dışarı çıkacağın halde neden annenin telefonuna göndermesini istedin?

Enes Güran : Şarjım yoktu çünkü. Şarjım azdı. Benim şarj göstergemde % kaç olduğu belirtilmiyor. %20 ya da %15 olduğu zaman ya kırmızı oluyor ne zaman kapanacağı belli olmuyor. Ben bunu size söylemek istiyorum.

Av. Asya Cemre Işık : Evet. Tamam ama bu doğal tabii. Telefonun şarjı biteceği için annenin telefonuna isteyebilirsin. Burada bir tartışma yok.

Enes Güran : Tamam.

Av. Asya Cemre Işık : Ama evde değilsin. Evden çıkacaksın. Neden annenin telefonuna istedin? Gelirse göremeyeceksin çünkü. Neden annenin telefonuna istedin?

Av. Asya Cemre Işık : Annemin telefonuna kardeşim Osman'ın fotoğraflarını niye ona attı diye mi bunu bana soruyorsun? Evet. Neden orayı istedin kendi telefonuna değil? Ondan istedim.

Av. Asya Cemre Işık : Bir sorum daha olacak.

Enes Güran : Buyurun.

Av. Asya Cemre Işık : Cezaevinde Eren'le görüşmelerinde, sayın heyet de sordu, telkinlerin oluyor; "Kimseye bir şey söyleme. Sessiz ol.".

Sanık müdafileri : İtiraz ediyoruz.

Mahkeme Başkanı : Yok itirazlık bir şey yok. İtirazı reddediyorum. Buyurun avukat hanım. Soruyu alayım.

Av. Asya Cemre Işık : Eren'den bunu gizleyebileceğinizi düşünüyor musunuz gerçekten? Çünkü neden gizleyemeyeceğinizi söyleyeyim.

Mahkeme Başkanı : Cezaevine girip giremeyeceğini gizleyebileceğini, onu izah et.

Av. Asya Cemre Işık : Bütün insanlar sizin cezaevinde olduğunuzu Güran ailesini bütün 85 milyon tanıyor. Siz bu bilgiyi Eren'den gizleyebileceğinizi düşünüyor musunuz?

Enes Güran : Biz bilgiyi falan Eren'den gizlemiyoruz ki.

Av. Asya Cemre Işık : O zaman neden Eren... Az önce beyanınızda dediniz ya. Evet. Eren'le cezaevi görüşmesindeki o sebebini açıklarken dediniz ki Eren haberdar olmasın diye söylediniz.

Enes Güran : Tamam ben bunu söylüyorum. Küçük kardeşimdir hala. Ablasının bile öldüğünü bilmiyor. Tatile gitmiş diye ona söylemişiz. Benim cezaevine girdiğimi de bilmesini istemedim.

Av. Asya Cemre Işık : Yani Eren'in bilmeme ihtimali var sizce. Eren öğrenmeyebilir bunu.

Enes Güran : Evet.

Av. Asya Cemre Işık : Öyle düşünüyorsunuz. Peki. Sorularım bu kadar. Teşekkür ederim.

Mahkeme Başkanı : Ben teşekkür ederim.

### Av. Derya Yıldırım

Av. Derya Yıldırım : Sadece iki hususu soracağım kendisine. Cezaevinde yaptığı iki görüşmeye ilişkin. Narin'in ne şekilde öldürüldüğünü ne zaman öğrendin?

Enes Güran : Avukatlarım geldiği zaman.

Av. Derya Yıldırım : Yani cezaevindeyken. Evvelinde bilmiyordun. 20 Eylül 2024 tarihinde Amca İbo diye biriyle bir görüşme yapıyorsun.

Enes Güran : Evet doğrudur.

Av. Derya Yıldırım : Ve rapor belli olmadı mı diye defalarca soruyorsun. Sonra sana dönüp rapor biraz çıkmış. Ağzı burnu kapatılmış diyor.

Enes Güran : Doğrudur.

Av. Derya Yıldırım : Ne cevap verdiğini hatırlıyor musun?

Enes Güran : Avukatlara işte bir şey varsa bir şey eğer çıkmışsa avukatlara söyle bana gelip söylesinler. Öyle galiba hatırlıyorum.

Av. Derya Yıldırım : Yok verdiğin cevabı söyleyeyim. Ben ne zaman çıkacağım buradan? Yani Narin'in ölüm şekline hiç şaşırmamışsın. Nasıl olur gibi bir şey sormamışsın. Yani bu ağzını burnunu kapatılarak...

Enes Güran : Amcam İbrahim Güran'la pek samimi olmadığım için ve hep abim Baran'la ağladığım için...

Av. Derya Yıldırım : Yani şunu söylüyorum Narin'in ölüm şekline hiç şaşırmamışsın. Doğrudan ne zaman çıkacağım diyorsun. Hiç merak etmiyorsun bu şekilde mi öldü.

Enes Güran : Yani cezaevindeyim, 18 yaşındaki bir çocuğum ben. Diyerek zaten onu söylerim. Çünkü rapor çıktığı zaman...

Av. Derya Yıldırım : Şimdi diyorum Narin'i çok sevdiğini söylüyorsun. Ama ölüm şeklini hiç yadırgamıyorsun.

Enes Güran : Peki o cezaevinde defalarca yüzüme vurduğumu siz gördünüz mü hiç? O banyoya girdiğim zaman kafamı duvarlara vurduğum zaman gördünüz mü siz?

Av. Derya Yıldırım : İlk duyduğunuz anda gayet normal karşılıyorsunuz.

Mahkeme Başkanı : Şöyle soralım soruyu biraz, yönlendirmeliyim. Normal karşılıyor musun? Normal mi karşıladın şok mu oldun?

Enes Güran : Şok oldum sayın hakim.

Av. Derya Yıldırım : Orada da üçüncü günden sonra diş izi çıkmaz diye bir soru soruyorsun babana.

Enes Güran : Babama mı?

Av. Derya Yıldırım : Aynen.

Enes Güran : Ne soruyorum?

Av. Derya Yıldırım : Üçüncü günden sonra diş izi çıkmaz.

Enes Güran : Diş izi çıkmaz? Hatırlamıyorum.

Av. Derya Yıldırım : Karşılık olarak da sana avukata söyle bana söyleme gibi bir şey söyleniyor.

Enes Güran : Hatırlamıyorum.

Av. Derya Yıldırım : Yani bu diş izinin çıkıp çıkmaması niçin bu kadar önemli senin için?

Enes Güran : Yani diş zaten ben kendim ısırdığımı biliyorum. Üçüncü gün zaten ben ısırmışım. Yani bunu Narin'le, annemle ya da başka bir kişiyle alakası yok ki.

Av. Derya Yıldırım : Tamam niye ısrarla bunu soruyorsun? Onu soruyorum ben de. Yani diş izinin çıkıp çıkmaması...

Mahkeme Başkanı : Hatırlamıyorum dedi avukat hanım. Hatırlamıyorum dedi.

Av. Derya Yıldırım : Sorumuz bu kadar.

### Av. Nahit Eren

Av. Nahit Eren : Ben de Diyarbakır Barosu vekili olarak sorular soracağım sana.

Enes Güran : Tabii ki de buyurun.

Av. Nahit Eren : 8 yaşında kaybedilen, aslında ilkinde kaybettirilen, sonra da öldürüldüğünü öğrendiğimiz Narin. Yani senin kardeşin olan Narin'le ilgili soru soracağım sana.

Enes Güran : Tamam buyurun sorun.

Av. Nahit Eren : Mesela bu dosyada kaç defa ifade verdiğini biliyor musun?

Enes Güran : Yok.

Av. Nahit Eren : Sence kaç defa olmuş olabilir?

Enes Güran : Bilmiyorum.

Av. Nahit Eren : Ben sorayım. 6 defa ifade vermişsin.

Enes Güran : Evet.

Av. Nahit Eren : 6 ifadeyi de başkan bey de söyledi. Olaya dair gün içerisindeki kurgularının tamamı birbiriyle çelişiyor. Ben şimdi sana o çelişkileri ortaya koyarak soru soracağım.

Enes Güran : Tamam buyurun sorun.

Av. Nahit Eren : Bu anlamda mesela ilk seninle ne zaman temas kuruluyor hatırlıyor musun? İlk temas. Kolluğun ilk teması.

Enes Güran : Kolluğun mu?

Av. Nahit Eren : Kolluk, kolluk. Seninle ilk ne zaman temas kurdu?

Enes Güran : 3. gün müydü? 4. gün müydü? Bizim tepe tarafına, Maşallah Güran'ın tepe tarafına, bakan ev tarafında taşların arasında kan bulundu. O zaman benim ilk ifadem orada alınıyor.

Av. Nahit Eren : Ne sordular sana?

Enes Güran : Yani ben nereye gittim, nerede ne yapıyordum, neredeydim? Bunlar soruldu. Malatya'dan ne için geldin?

Av. Nahit Eren : Sana Narin ne zaman kayboldu diye bir soru sordular mı?

Enes Güran : Sordular.

Av. Nahit Eren : Ne dedin?

Enes Güran : Yani en son saat 1'de gördüm onu dedim.

Av. Nahit Eren : Narin'in kaybolduğunu ne zaman öğrendin diye sana bir soru sordular mı?

Enes Güran : Sordular.

Av. Nahit Eren : Kaç dedin?

Enes Güran : O zaman da 04:30'demiştim.

Av. Nahit Eren : 04.30'da dedin.

Enes Güran : Evet.

Av. Nahit Eren : Narin 4:30'da kaybolmuş, ilk. Yani Narin'in kaybolduğu güne dair insanın, zihninin, hafızasının yerinde olduğu, hatırlayabileceği ilk temas da saat 16:00.

Enes Güran : Bakın.

Av. Nahit Eren : Hayır ben bir şey soruyorum. Sorumu sorayım, sen cevabını ver Enes.

Enes Güran : Tamam buyurun sor.

Av. Nahit Eren : İlk temasta verdiğin ilk bilgi kaçtı bir daha söyle?

Enes Güran : 04:30'du.

Av. Nahit Eren : 04:30'du.

Enes Güran : Bakın bunu söylüyorum.

Av. Nahit Eren : Ben başka bir şey sormuyorum, cevap vermene gerek yok. Sadece sorduğum soruya cevap istiyorum. Saat 4:30'da gördüğünü söyledin mi?

Enes Güran : Evet.

Av. Nahit Eren : 04:30'da görmekle birlikte başka ne yaptığını söyledin mi?

Enes Güran : Hatırlamıyorum.

Av. Nahit Eren : 04:30'da kaybolduğunu düşündüğün bir kardeşinle ilgili insan bir harekete geçmez mi?

Enes Güran : Hatırlamıyorum söylüyorum. Onunla konuştuğun şeyi hatırlamıyorum.

Av. Nahit Eren : Hayır hatırla diye zaten sana soruyu soruyorum. 16:30'da kardeşinin kaybolduğunu öğrendin.

Enes Güran : Evet.

Av. Nahit Eren : Aramaya başladın mı?

Enes Güran : Onlara başladım demiştim.

Av. Nahit Eren : Başladım demiştin.

Enes Güran : Evet.

Av. Nahit Eren : Başlamamış mıydın?

Enes Güran : Yani ben akşam ezanında kardeşimin kaybolduğunu fark ettim. Saat 4 civarlarında.

Av. Nahit Eren : Kimsenin az evvel başkan bey soru sordu. Evet.

Enes Güran : Evet.

Av. Nahit Eren : Savcı hanım soru sordu.

Enes Güran : Evet.

Av. Nahit Eren : 17:30'da Furkan'ı gördüm, 16:00'da gördüm. Kaç gün geçmiş? 2 ay. Hatta 2 ay 10 gün geçti değil mi neredeyse? Bunların hepsini saat saat hatırlıyorsun.

Enes Güran : Çünkü yaşadığım şeylerdi, doğru şeylerdi.

Av. Nahit Eren : Bunlar ilk kollukla temas ettiğin şey, yaşamadığın şeyler mi? Kolluklardan.

Enes Güran : Ya şimdi konuşacağım, olmuyor.

Av. Nahit Eren : Konuş zaten konuşasın diye buradayız. Biz Narin'in katilini bulmak için buradayız değil mi? Saat 16:00'du.

Enes Güran : Avukatımla bir şey konuşabilir miyim?

Mahkeme Başkanı : Konuşabilirsin. İzin verin avukatıyla bir dakika konuşsun.

Mahkeme Başkanı : Tamam, siz ne söylüyorsunuz? Tekrar alayım. Zapta geçemedim, SEGBİS kaydı yapmadık.

Av. Yılmaz Demiroğlu : Zapta geçebilirsiniz.

Mahkeme Başkanı : Tamam, söyleyin.

Av. Yılmaz Demiroğlu : Sayın Başkanım ben mensubu olduğum Diyarbakır Baro'sunun üyesi olmaktan gerçekten gurur duyuyorum. Bizim misyonumuz işkence ve kötü muameleye karşı yıllarca mücadele etmekle geçti ve bundan gurur duyuyoruz. Ancak biz ilk defa bu dava dosyasını aldığımızda sanıklarla yaptığımız ilk temasta o zaman şüphelilerin tamamı kollukta insanlık dışı muameleye yani kötü muameleye maruz kaldığını bize belirttiler. Biz de Diyarbakır Barosu'nun bu konuda eski yöneticisi de olmam hasebiyle bildiğim için gerçekten bu iddialara şaşırdık. Diyarbakır Barosu başkanı, dönemin başkanı, o dönemde bu Narin cinayeti için Narin cinayeti için olayın aydınlanması için mücadele ettiğini beyan etmişti. Biz bu güvenle hareket ettik ve duruşmaya başladığımız sırada şunu ifade ettik, dedik ki biz burada her ne kadar sanık müdafisi olsak da bizim amacımız adalete uygun, hakkaniyete uygun bu davanın sonuçlanmasına hizmet etmektir. Biz bu hizmeti bu hizmet anlayışıyla.

Av. Nahit Eren : Diyarbakır Barosu'nun kurumsal kimliğini mi tartışıyoruz? Çalışma üstünlüğünü mü tartışıyoruz?

Mahkeme Başkanı : Anlayamadım. Toparlayacağız. Anlamadım ki ne dediğini. Meramını anlamadım ki. Lütfen. Şimdi arkadaş bayan arkadaş konuşmasın. Bir izin verin ben bir meramını anlayayım ya. Saygı diyorsunuz daha meramını anlamadım. Bu nasıl saygı? Allah Allah. Toparlayın.

Av. Yılmaz Demiroğlu : Efendim. Hepimizde hukuken biliyoruz ki bu davada müdahil olma hakkı bile yok. Ama biz ne dedik? Amacımız maddi gerçeği aydınlanmasıydı değil mi?

[Bu esnada sanık müdafileri, katılan vekilleri, izleyiciler ve mahkeme heyetinin ortak bir şekilde konuşması sebebiyle ses karışıklığı karşısında zapta aktarılamadı.]{.bracket-box}

Mahkeme Başkanı : Kendi ifadesidir. Dediğim gibi, bu konuda bildikleriniz varsa Diyarbakır Cumhuriyet Başsavcılığı'na suç duyusunda bulunmak en doğal hakkınızdır. İlgili bilgi ve belgeleri sunarsınız. Ona ilişkin de gerekli kişiler hakkında suçlu bildirmeme, suçu kayırma hakkında da dava açılır. Nahit Bey sorularınıza devam edin.

Enes Güran : Ben de bir şey sorabilirim?

Mahkeme Başkanı : Sen de dediğim gibi Enes. Karşı tarafın ettiği küfürler dahi söyleyebilirsin. Hiçbir beis yok. Şimdi söylemek istiyorsan.

Av. Nahit Eren : Sayın Başkan. Az evvel siz kendi meramınızı bu davaya bakış açınızı ortaya koyduğunuz yargıçlar. Buyurun siz de cevap edin. Meslektaşım uzun yıllar baroda yöneticilik anlamında kendisi de hatırlattı. Ben de hatırlatayım. Birlikte yöneticilik de yaptık. İşkenceyle nasıl mücadele ettiğimizi çok iyi bilir. Aile bana iki defa geldi bahar öncesi aile şu an herhalde salondan bana bağıranı da duydum. Aile bana geldi ve ben bütün görüşmelerimde bütün yönetim kurulu üyesi meslektaşlarımla birlikte görüşme gerçekleştirdim. Hepsi de salonda. İlk geldiklerinde bana şunu söylediler. Göz altındayken bizim aile yakınlarımıza kötü muamele ve işkence yapıldığını söylüyorlar. Ben kendilerine Diyarbakır Barosu'ndan CMK'dan giden her avukatımıza CMK avukatları olmaları hasebiyle herhangi bir kötü muamele ya da işkence iddiası varsa sizden ricam ifade esnasında bunları tutanağa geçin diye görüştüm. Üç avukat arkadaşım var ve bize baroya gelen aile bireyleri bu iddiayı dile getirdiklerinde kime ne şekilde yapıldığını bize bir söyler misiniz dedim. Kendileri de belki salonda dinliyorlar. Kimi dişi çekilmiş dedi, kimi tırnağı çekilmiş dedi, kimi yüzüne yumruk vurulmuş kafasına demir çubuklarla vurmuş, kimisi dedi böyle tazyikli suyla annesinin karşısına götürülüp götürülüp bir sürü şey anlatıldı. Ben de dedim ki bunlara ilişkin bize lütfen ilgili ki avukat tutma çalışması içerisindeydiler. Ben de bize bu konuda bir başvuru yapın dedim. Hatta orada aile bireylerinden biri 12'sinde tutuklamaya sevkten sonraki tahliyelerden birilerini aradı. Gelip baroya sana ne yaptılar bir anlat, gel baroya başvuru yap dedi. Ben gelip başvuru yapamam dedi. Çünkü neden başvuru yapmayacağını söyledi? Hayır biz bu konuda gelip herhangi bir başvuru yapmayacağız. Diyarbakır Barosu'na işkence iddiasıyla ilgili yapılmış tek bir başvuru yok. Bu sohbet geçti. Bu sohbetten sonra da aile bize bu konuda herhangi bir başvuru yapmadığı gibi Diyarbakır Barosu değil bu dosya hangi dosya olursa olsun. Eğer şüpheli, fail, sanık ne derseniz desin. İşkence yapılmışsa biz onun da karşısındayız. Biz onun için de mücadele hukuk mücadelesini vermeye devam ederiz. Ama duruşma salonunda Diyarbakır Barosu'nun kurumsal kimliğini tartıştırıp bu davadaki müdahillik ispatımızdan bizi hedef tahtasına oturtacak söylem ve dilden lütfen uzak duralım. Ben şimdi burada ben burada ben burada bu bu sekiz yaşında yaşam hakkı ihlal edilen Narin'in faillerinin hak ettikleri cezayı alması için buradayım.

Mahkeme Başkanı : Tamam. Artık. Tamam. Artık sonuna da geçebilir miyiz? Tamam Eren, artık soruyu direkt soracak. Başkanım.

Av. Nahit Eren : Başkanım. Tekrar çelişkili soruyu alalım. Kendisinin şüpheli sıfatıyla değil. Bir mülakat tutanağından bahsettim. Tamam. Evinin önünde saat 8'de yapılan mülakattan bahsediyorum. Tamam tekrar. Tarih ne? Tarih 23'ü. Narin'in kaybolduğu günün iki gün sonrası.

Mahkeme Başkanı : Tamam avukat bey tekrar soruya gelelim. Buyurun.

Av. Nahit Eren : Soru sordum.

Mahkeme Başkanı : Bir daha sorun da hatırlayalım işte. Konu dağıldı.

Av. Nahit Eren : Saat 04:30'da kaybetti, kaybolduğunu söyleyip dört buçukta kaybolduktan sonra aramaya gidip gitmediğini sordum.

Mahkeme Başkanı : Ha tamam.

Av. Nahit Eren : O da dedi ki ben bunların ilgili avukatlarımla.

Mahkeme Başkanı : Tamam. Şimdi tekrar soruyu aldım. Asker arkadaşlar oturabilir misiniz? Oturun. Tekrar soruyu alalım. Buyurun Enes. Seni dinliyorum.

Av. Nahit Eren : Sayın Hakim'im ilk ifadem zaten Tavşantepe'de alındı. Kan bulunan yerde alındı. Yani Sayın Hakim üç kişi benim etrafıma gelmiş. Bana ifade mesela ne yaptın? Ne ettin? Sayın Hakim ben dörtten sonrasını hatırlamıyorum zaten. Çeşme tarafına gitmişim. Bakkala gitmişim. Tepeye gelip oturmuşum. Hatırlamıyorum zaten o olayları. Onlara da söyledim ben zaten. Bunu demek istiyorum.

Mahkeme Başkanı : Tamam. Buyurun avukat.

Av. Nahit Eren : O mülakatta aynı zamanda gözündeki morluk soruluyor sana.

Enes Güran : Evet.

Av. Nahit Eren : Ne cevap verdiğini hatırlıyor musun?

Enes Güran : Mısır tarlasında olmuştur diyordum.

Av. Nahit Eren : Ben sana söyleyeyim mi ne dediğini?

Enes Güran : Söyleyin.

Av. Nahit Eren : Narin Güran'ın kaybolması nedeniyle içerisine düştüğün ruhi bunalımdan kendi kendine zarar verdiğini beyan etmişsin.

Enes Güran : Ben de bunu söylemek istiyorum. Birinci günün gecesi Mısır tarlasında. Başka sorunuz var mı hala yoksa cevaplayayım mı?

Mahkeme Başkanı : Cevap ver.

Enes Güran : Birinci günün gecesi Mısır tarlasında kardeşimi ararken Berzan Güran telefon geldi Narin hastanede bulunmuş diyorlar ve biz de yola çıktık. Barış Güran amcam olur kendisi. Arabasına bindim hastaneye gittim. Hastanede o olmadığını tespit ettikleri zaman babamın ağlaması abimin ağlaması ve Barış Güran'ın abimle tartışması sebebiyle ben de dayanamayıp köye gelip tekrardan annemin ağlamasını ve babamın ağlaması, hala şeyi kulağımda olduğu için ve abimin üzüldüğü için kendimi bir köşeye çekip defalarca yüzüme vurdum.

Mahkeme Başkanı : Tamam.

Av. Mustafa Demir : Pardon başkanım. Az önce bir şey yanlış geçmiş olabilir bir teyit edeyim. Mülakatla ilgili az önce meslektaşımız soru soru değil mi? Mülakatta 16:30 meselesi geçmiyor.

Mahkeme Başkanı : Çok önemli değil. Mülakattır, araştırma tutanadır. Ya oradaki mana şu Avukat Bey ben de aynı şeyleri sordum. Enes'in bir araştırma tutanağı var. İki sözlü yaptığı mülakatlar var. Üç aşamalardaki beyanlarda 16:30, 16:30 gibi aramaya çıktığı konusunda çelişkiler var. Ben de bu soruyu aynısını sordum. Nahit Bey de aynısını soruyor. Ya çok önemli değil. Tamam tutanaktır, araştırma tutanadır, mülakattır yani.

Av. Nahit Eren : Hem soru sorarken ben kopuyorum. Kendi konsantrasyonu.

Mahkeme Başkanı : Evet. Farkındayım ama.

Av. Nahit Eren : Hem sanık açısından da doğru bir yöntem değil.

Mahkeme Başkanı : Evet değil biliyorum ama.

Av. Nahit Eren : Yöntem açısından da doğru değil. Ben zaten en son.

Mahkeme Başkanı : Acıktınız herhalde ki. Beyanlar alındı zahmet. Herhalde anneannemle, dadanila herkesin bir ciğer yeme vakti geldi. Gelirdiniz. Çabucak sorun da. Millet bir yemek yesin, tansiyonu kendine gelsin.

Av. Nahit Eren : Bir soramadık ki dört keredir bölünüyor.

Av. Nahit Eren : Yirmi dördünde bir daha ifade veriyorsun. Bilgi amaçlı bir ifade veriyorsun. Orada 16:30 jandarmaya bu defa bilgi amaçlı.

Enes Güran : Evet.

Av. Nahit Eren : Mülakat değil, bilgi amaçlı. Jandarma seninle ilgili şöyle bir tespit yapıyor. Buna cevap da vermeyebilirsin. İşte bizim zaten en çok itiraz ettiğimiz husus şu. 23'ünde seninle mülakat yapıldığı zaman şöyle bir tanımlama yapılıyor. Bu onların tanımlaması tedirginliğinden bahsediyor.

Mahkeme Başkanı : Bir dakika. Orada o telefonu alabilir miyim? O telefonu alabilir miyim? Polis arkadaşlar o telefona derhal el koyun. Derhal! Orada bir telefon kayıt var. Ben mi yanlış görüyorum? Avukat Bey kafanızda gözlük olan siz. Sizin önünüzde bir telefon gördüm. Yansıyan gözlük mü var? Telefon mu var orada?

Kalabalıktan gelen ses : Gözlük başkanım.

Mahkeme Başkanı : Tamam. Gözlük. Bir yansıyan bir şey gördüm.

Enes Güran : Sorunuzun cevabını vereyim mi?

Mahkeme Başkanı : Gene böldük.

Av. Nahit Eren : 24'ündeki ifadende 16:30'da kayboldu diyorsun.

Enes Güran : Evet.

Av. Nahit Eren : Sonra 25'inde bir kez daha senden bir ifade alınıyor. Evet. 25.08'de saat 11:30'da.

Enes Güran : Evet.

Av. Nahit Eren : Burada da yine kolunuzdaki ısırık size soruluyor. Yine yumruk attığınızı söylüyorsunuz.

Enes Güran : Koluma ısırılmasına gözünüze.

Av. Nahit Eren : Yumruk attım diyorsunuz.

Enes Güran : Evet. Belki Mısır tarlasını ararken Mısır çöpü de değmiş olabilir. Hatırlamıyorum. Çünkü biz Mısır iş jandarmaya gittiğimiz zamana yine tarafıma kendime baktığım zaman yüzümde hafif hafif kesildiler ve hafif hafif renkli vardı. O zaman orada hatırladım ki Mısır tarlasından sonra da hastaneye gidip ağlama seslerinden sonra da eve gidip kendimi darp ettiğimi onlara zaten yine söyledim ben orada.

Mahkeme Başkanı : Ya şimdi Enes. Tekrar sordum aynı şeyi tekrar soracağım. Başkanım kusura bakmayın araya gittim. Sen Salim'in herhangi bir kızıyla ilişkiye girdin, bundan dolayı yakalandığında Salim seni dövdü mü? 

Enes Güran : Hayır.

Mahkeme Başkanı : İddia bu. Böyle bir şey yok mu?

Enes Güran : Yok.

Mahkeme Başkanı : Tamam. Buyurun başkanım.

Av. Nahit Eren : Bir şey soracağım. 25'inde Mısır'dan kaynaklı olabileceğini söyledin, değil mi?

Enes Güran : Evet.

Av. Nahit Eren : Seni getirdiler, savcılıkta da ifade verdin.

Enes Güran : Evet.

Av. Nahit Eren : Savcılıkta sana bir soru soruyorlar. Tıpkı benim sorduğum gibi. Neden ilk ifadelerinde bunun mısırdan kaynaklı değil de yüzüne yumruk vurduğun için diye bir soru soruyorlar sana.

Enes Güran : Tamam.

Av. Nahit Eren : Ne cevap verdiğini hatırlıyor musun?

Enes Güran : Yok.

Av. Nahit Eren : Ben okuyayım mı sana? Belki hatırlarsın. Çünkü önemli.

Enes Güran : Tamam buyurun okuyun.

Av. Nahit Eren : Ben diyorsun adli tıpa gittikten sonra adli tıpta çizikler olduğunu söylediklerinden dolayı ben Mısır'a çevirdim diyorsun.

Enes Güran : Mısır'a çevirdim demiyorum ben.

Av. Nahit Eren : Bu mısırdan kaynaklandı. Çünkü çizikler mısırdan kaynaklı olabileceğini düşünerek bu saatten sonra mısır diyorum. Oysa sen daha önce de mısırdan kaynaklı olabileceğini söylemişsin.

Enes Güran : Mısır diyorum ve sonrasında da kendimi darp ettiğimi söylüyorum zaten.

Mahkeme Başkanı : Avukat bey bu yorum mudur? Okuyun.

Av. Nahit Eren : İfade. Okuyup sorun. İfade sordum zaten. Orada oraya söylüyor. Ezberim de. Soruyorum.

Mahkeme Başkanı : Bir tek tane okuyun orada. Çünkü yorum itirazı gelmeden okuyun orada.

Av. Nahit Eren : 23.08.2024 tarihinde soru. Görüşme tutanağında gözündeki morluğun içinde bulunduğu bunalımdan kendisine zarar vermiş olduğunuza ilişkin kolluk birimlerinden beyan okunarak soruldu. "Ben o dönem tam olarak farkında değildim. Ancak adli tıpa götürüldüğümde küçük küçük çiziklerin olduğu söylenince mısır tarlasında da olabileceğini o şekilde aklıma geldi ve sonrasında ifademi de o şekilde belirttim."

Enes Güran : İstanbul adli tıpa gittiğim zaman oradaki bayan doktor bana baktığı zaman gözündeki hafif hafif kesintiler nereden olmuş dediği zaman mısır tarlasında da olmuştur. Çünkü mısır tarlasından sonra kendime vurdum dedim. Tamam dedi. Belimdeki izlere de gelince.

Av. Nahit Eren : Ama hayır bak ben şunu söyle bunu ııı tespit etmeye çalışıyorum.

Enes Güran : Buyurun.

Av. Nahit Eren : Sen adli tıpa bu cevabı veriyorsun ama adli tıpa gitmeden önce de mısırdan kaynaklı olduğunu söylüyorsun. Ben bu çelişkiyi zaten sana soruyorum.

Enes Güran : Zaten ilk başta mısır tarlasının olduğunu söylemiyor muyum ben size?

Av. Nahit Eren : Tamam söylüyorsun.

Enes Güran : Tamam.

Av. Nahit Eren : Ama savcılar sana bunu soruyor. Neden? Neden şu anda yumruk diyorsun mısır demiyorsun? Sen de sen de diyorsun ki, ben İstanbul'a gidip geldikten sonra mısır olduğunu anladım. Oysa daha önceki ifadenden de mısır var.

Enes Güran : Bu ifade ne zaman alındı? Ben de onu sana sorabilir miyim Avukat Bey? Bu kardeşimin cesedi bulunduğu zaman hatta aradan..

Av. Nahit Eren : 12.09.2024

Enes Güran : 12.09 değil mi?

Av. Nahit Eren : Evet.

Enes Güran : Hatta sonradan mahkemeye çıkıp cezaevine gittiğimizde söylüyorsunuz değil mi?

Av. Nahit Eren : Daha çıkmamışsın savcılık.

Enes Güran : Yani zaten biz savcılarımızın karşısına çıktığımız zaman kendimizde bile değildik. Değildik.

Av. Nahit Eren : Ha tamam orayı anlatabilirsin. Suç duyurusunda da bulunabilirsin. İfade et. Ya bu ifadeler işkence, kötü muamele, baskı altında alındı. Hiçbiri gerçek değil mi diyorsun?

Enes Güran : Evet.

Av. Nahit Eren : Tamam bunu söyleyebilirsin.

Mahkeme Başkanı : Tamam şöyle sorayım. Hangi 12.09 tarihinde vermiş olduğun ifade, Diyarbakır CBS'ce alınan ifade işkence kapsamında alınan bir ifade mi?

Enes Güran : İşkenceye koyulduğumdan sonra alınan ifade.

Mahkeme Başkanı : Zaten orada suçu kabul etmiyor ki. Yani Enes'in suçu kabul ettiği gibi bir beyanı yok ki. Yani işkenceden sonra aldığın aldığın işkence kabul etsek bile işkenceden sonra aldığın beyan ile bizim söylediğimiz saat farkı dışındaki beyanlarla çelişki yok ki. Neyse biz o beyanları kabul etmiyorsun. Doğru mu? Diyarbakır Cumhuriyet Baş Savcılığı'nda alınan beyanları işkence kapsamında verdiğin için kabul etmiyorsun. Tamam zapta yazdım.

Av. Nahit Eren : Ben sana gerçekten bu çelişkileri gidermek adına soru soruyorum Enes. Sen hatırlarsan alındın. İstanbul'a götürüldün.

Enes Güran : Evet.

Av. Nahit Eren : Adli tıpta kolundaki inceleme yapıldı. Geldin serbest bırakıldın.

Enes Güran : Doğrudur.

Av. Nahit Eren : Serbest bırakıldıktan sonra köye gittiğinde.

Enes Güran : Evet.

Av. Nahit Eren : Nereye gittin ilk?

Enes Güran : İlk mi?

Av. Nahit Eren : Evet.

Enes Güran : Gittiğim yer evimdir. Yok, Hüseyin Güran.

Av. Nahit Eren : Hüseyin Güran amcanın evine gittiğin zaman kimler vardı?

Enes Güran : Hüseyin Güran orada oturuyordu. Hüseyin Güran amcamdır. Ona sarıldım. İlk baş hasta olduğu için ve beni jandarmada eli kelepçeli gördü ve sonradan da bana dediğinden şey işte seni öyle görüp de çok rahatsızlanmış. İlk başta onlara gidelim dedi. Ve onlara gittiğimiz zaman Hüseyin Güran'ı orada gördüm. Muzaffer Güran galiba vardı. Bir de şey vardı. Osman Güran vardı galiba.

Av. Nahit Eren : Peki ne konuştunuz hatırlıyor musun?

Enes Güran : Yani amcam sadece işte ne oldu? Ne dedi? Bu bu oldu amca. Sonrasında evisine çıkıp elimi yüzümü yıkadım. Kendime oturdum orada, sonrasında eve çıktım.

Av. Nahit Eren : Peki altında konusunda Diyarbakır Cumhuriyet Başsavcılığı'nda senden ifade aldığını iddia ediyorsun ama oradan sana bir soru sorabilir miyim? O ifadeden kaynaklı.

Enes Güran : Buyurun.

Av. Nahit Eren : Sen peki Birsen'le Melike'yle bir görüşme yaptın mı?

Enes Güran : Hayır.

Av. Nahit Eren : Çıktıktan sonra 29'unda serbest bırakılıyorsun ya.

Enes Güran : Evet.

Av. Nahit Eren : Bir görüşme yaptın mı?

Enes Güran : Evlerine zaten gitmiştim. Dedim ya elimi yüzümü yıkamaya gittim ya. E tamam elimi yüzümü yıkamaya gittim dedim. Oturdum dedim ya. Zaten Berzan Güran orada vardı. Muhammed Kaya vardı. Abdurrahman Güran vardı ve Birsen Kaya da. Birsen Güran pardon. O sandalyede oturuyordu ve ağlıyordu.

Av. Nahit Eren : Peki Birsen'le Melike'yle bir sohbetin oldu mu?

Enes Güran : Yok.

Av. Nahit Eren : Peki sana bir soru soruyorlar.

Enes Güran : Buyurun.

Av. Nahit Eren : Maşallah, Birsen ve Melike Güran'ın ifadelerini okuyorlar sana.

Enes Güran : Bana mı?

Av. Nahit Eren : Evet savcılıkta. Birsen'in Melike'nin ve Maşallah'ın niye sana bu ifadeleri okutuyorlar? Sen de çok iyi biliyorsun ki konu zaten o. Onlar Maşallah pardon Narin'i saat 17:40'ta gördüklerine dair ilk günden itibaren istikrarlı bir ifadeleri var.

Enes Güran : Doğrudur.

Av. Nahit Eren : Yani Narin'in 13:11'den sonra on 13:40'a kadar öldürüldüğünü, katledildiğini artık bu salondaki herkes biliyor.

Enes Güran : Doğrudur.

Av. Nahit Eren : Ama bunlar 15:40'ta kapılarına gelip kapıyı çalıp gittiğini söylemiştiler. Sen bu konuyla ilgili.

Mahkeme Başkanı : Neyse çok önemli değil. Müdahale etmeyelim.

Av. Nahit Eren : 17:40 pardon 17:40. 17:40. Tamam. Tamam 17:40. 17:40. 17:40. 11'le 15:40 arasında öldüğünü biliyoruz artık.

Enes Güran : Tamam.

Av. Nahit Eren : Ama 17:40'ta gördüklerini iddia eden Birsen ve Melike vardı.

Enes Güran : Tamam.

Av. Nahit Eren : Hatta Maşallah da Birsen'in kapıyı açtığından bahisle bana da kapıdakinin Narin olduğunu söylemişti.

Enes Güran : Tamam.

Av. Nahit Eren : Sen bu konuyla ilgili hiç görüşmedin mi Birsen'le? Peki bir şey okuyacağım. Başkanım yine okuyorum.

Mahkeme Başkanı : Tabii ki daha güzel olur okursanız.

Av. Nahit Eren : Bizim bu şahıslarla ya da Hüseyin amcamla da herhangi bir sorunumuz ya da husumetimiz yoktur. Neden bu şekilde beyanda bulunduklarını bilmiyorum.

Enes Güran : Doğrudur.

Av. Nahit Eren : Hatta ilk olarak gözaltına alındıktan sonra köye gittiğimde Birsen'de iyice düşünmesini söyleyerek sormuştum. Bir sene. İyice düşünmesini isteyerek sormuştum. Az evvel bir şey söyledim. Hepimiz artık 15:11, 15:40'ta öldüğünü biliyoruz.

Enes Güran : Doğrudur.

Av. Nahit Eren : Ya dosyadaki delilere göre.

Enes Güran : Evet.

Av. Nahit Eren : Sormuştuk. O da Narin'in geldiğine emin olduğunu söylemişti. Kendimce düşünmüştüm. O saatte Narin'in onlara gitmesinin mümkün olmayacağını devam devam ediyorsun. Narin'in o saatte onlara gitmeyeceğinin mümkün olmayacağını cümlesinden kastettiğin şey nedir?

Enes Güran : Hatırlamıyorum. O ifademi verdiğim zaman da hatırlamıyorum.

Av. Nahit Eren : 29'unda sen çıktın. Eve gidiyorsun.

Enes Güran : Evet.

Av. Nahit Eren : Bu görüşmeyi yapıyorsun. Biz henüz 8-9'da Narin'in naaşının Eğertutmaz deresinde bulunmasına kadar hiçbirimiz Narin'in 15:11 ve 15:40 arasında öldüğünü bilmiyoruz.

Enes Güran : Doğrudur.

Av. Nahit Eren : Ama sen şöyle bir cümle kuruyorsun ve ben bu cümle cümlen üzerine şu kanaate varıyorum ve soruyu soruyorum.

Enes Güran : Buyurun.

Av. Nahit Eren : O saatte Narin'in onlara gitmesinin mümkün olmayacağını düşündün. Neden böyle düşündün?

Enes Güran : Kameralarda tepeye doğru çıktığını söylüyorlar ve sonrasında tepeden bir kişi, Sayın Hakimim, bizim evin yukarısındaki olan evlerde bir kişi bize dedi ki, tanımadığım bir adam vardı ve arabasıyla hızlı bir şekilde bana ters şekilde baktığı bir adam vardı. O adamdan şüphelendik ve onun için o zaman yani Narin oraya gitmiş mi gitmemiş mi onu bilmiyoruz.

Av. Nahit Eren : Yani sen o gün itibariyle 15:11'le 15:30'a 15:40 arasında öldüğüyle ilgili bir bilgiye isnaden sormadın.

Enes Güran : Evet. Sormadım.

Av. Nahit Eren : Tamam. Az evvel dar baz çalışmasından bahsedildi. Ben sana istersen avukatların izah ettiğimi başkan bey müsaade ederse baz istasyonu nihayetinde baz verileri dosyada bir delil. Meslektaşlarım itiraz etti. Tabii ki de mahkeme bunları değerlendirecek. Henüz ama henüz geçerli konusunda ya da delilin reddi konusunda mahkemenin verdiği bir karar yok. Bu açıdan ben o delile bağlı olarak sana soru soracağım.

Enes Güran : Buyurun.

Av. Nahit Eren : O Savcı Hanım da size sordu.

Enes Güran : Evet.

Av. Nahit Eren : Saat 15:57'de çıktıkça evden çıktığınız gözüküyor.

Enes Güran : 15:57'de.

Av. Nahit Eren : Evet.

Enes Güran : Tamam.

Av. Nahit Eren : Salim'in evine gittiğiniz gözüküyor.

Enes Güran : Oraya gitmemişim kesinlikle.

Av. Nahit Eren : Salim'in evine o gün hiç gitmedin.

Enes Güran : Hiç gitmedim.

Av. Nahit Eren : O gün Salim'le herhangi bir telefon görüşmesi yaptınız?

Enes Güran : Kesinlikle yok.

Av. Nahit Eren : Hiç yüz yüze gelmediniz? Arama esnasında?

Enes Güran : Yok.

Av. Nahit Eren : Gece arama yaparken?

Enes Güran : Yok. Narini ararken?

Av. Nahit Eren : Yok.

Av. Nahit Eren : Tamam şimdi az evvel bir şey söyledin. Dedin ki, iki defa evden çıktığını söylüyorsun.

Enes Güran : Doğru.

Av. Nahit Eren : Baz istasyonu bize evden çıkmadığını söylüyor. Telefonu evden bırakıp çıkmış olsan senin evden çıkmış olduğun yine kabul edebilir. Çünkü biz burada telefon bizim ayak izlerimiz.

Enes Güran : Tamam.

Av. Nahit Eren : Baz dediğimiz şey o. Şimdi sen ben tepeye ilk çıktığında bir hikaye anlatıyorsun. Olay örgüsü anlatıyorsun. Gidiyor gittiğini söylüyorsun. Birileriyle temas kurduğunu söylüyorsun. Geliyorsun.

Enes Güran : Evet.

Av. Nahit Eren : İkinci çıkışında. Evet. Furkan ve Umut bir de Yusuf'la görüştüğünüzü söylüyorsun. Ufuk, Furkan. Evet. Yusuf.

Enes Güran : Evet.

Av. Nahit Eren : Annen bir yerde İsa diyor. Yanılmış mı? Yanlış mı demiş sence yoksa?

Enes Güran : İsa yoktu o zaman.

Av. Nahit Eren : İsa yoktu orada. Peki bir şey söyleyeceğim. Seni o gün Furkan hiç aradı mı?

Enes Güran : Furkan o zaman tepeye geldi. Bizim yanımıza. Ben seni arıyorum, niye telefonlarımı açmıyorsun diye? Ben de dedim, hele bir yine ara. Telefonum evde ve şarjdadır. Ben bunu Furkan kendisine ondan söyledim zaten.

Av. Nahit Eren : Tamam. Furkan'ın ifadesini hiç okuma şansın oldu mu?

Enes Güran : Yok.

Av. Nahit Eren : Ben sana Furkan'ın ifadesinden bir şey anlatıp soracağım.

Enes Güran : Tamam buyurun.

Av. Nahit Eren : Furkan diyor ki, ben 18'de eve geldim.

Enes Güran : Tamam.

Av. Nahit Eren : Demek ki, siz henüz 18'de tepede değilsiniz.

Enes Güran : Doğrudur.

Av. Nahit Eren : Bunun saati hatırlıyor musun?

Enes Güran : Yok.

Av. Nahit Eren : Hatırlamıyorsun. Diyor ki, ben 18'de eve geldim. Geldikten sonra ben ilk geldiğimde tepede tek başına Ufuk'u otururken gördüm.

Enes Güran : Ufuk'u.

Av. Nahit Eren : Eve girdim. Duş aldım. Çıktım. Ufuk ve Enes bu defa birlikte oturuyordular. Birlikte oturuyorlar. Bu doğru mu? Değil mi?

Enes Güran : Bu doğru değil.

Av. Nahit Eren : Bir şey daha soracağım.

Enes Güran : Buyurun.

Av. Nahit Eren : Ufuk, onun da ifadesini okumadın?

Enes Güran : Yok okumadım.

Av. Nahit Eren : Ufuk diyor ki, ben Ufuk'un dedesi kim biliyor musun?

Enes Güran : Dedesi mi? Evet. Biliyorum nasıl bilmiyorum?

Av. Nahit Eren : Kim?

Enes Güran : İsmini tam şey yapmıyor.

Av. Nahit Eren : Tamam. Diyor ben dedemin evindeyken Furkan işten geldi.

Enes Güran : Evet.

Av. Nahit Eren : Furkan geldiğinde saat 17:00 - 17:30 arasıydı ve geldiğinde Enes'i aradı. Enes'i aradığında ben telefonla Enes'i aradığında ben su içmeye gittim. Bana Enes'i aradım. Uykudan yeni uyanmış tepeye doğru gidiyor. Siz gidin ben de geleceğim.

Enes Güran : Yok kesinlikle.

Av. Nahit Eren : Böyle bir arama olup olmadığını soruyorum.

Enes Güran : Yok.

Av. Nahit Eren : Arama olmadı. Zaten Ufuk'la Furkan'ın da ifadeleri birbirleriyle çelişiyor. Ben oraya gittikten sonra.

Enes Güran : Evet.

Av. Nahit Eren : Annen geldiğinde, annen geliyor ya size sigara içmeyin diyor

Enes Güran : Aşağı gelip beni çağırıyor pencereyi kapatmam için.

Av. Nahit Eren : O sırada Furkan yanınızda mıydı?

Enes Güran : Yok.

Av. Nahit Eren : Furkan sonra mı geldi?

Enes Güran : Sonradan geldi.

Av. Nahit Eren : Furkan sonradan yanınıza geldi. Annen sen az evvel Hakim Bey sorunca anlatınca olay örgünle ben bir daha yukarı gittim diyorsun. Hindileri şeye koyduktan sonra. Bir daha yukarı yanlarına gittin mi? Bir daha arkadaşların yanına bir daha gittin.

Enes Güran : Hindileri bir de pencereyi kapattığım zaman mı?

Av. Nahit Eren : Evet.

Enes Güran : Evet gittim.

Av. Nahit Eren : Onlar da diyor ki, biz Furkan diyor ki annesi hiç bizim yanımıza gelmedi.

Enes Güran : Çünkü Furkan, annem o zaman geldiği zaman Furkan yanımızda değildi.

Av. Nahit Eren : Yanınızda değildi?

Enes Güran : Evet.

Av. Nahit Eren : Furkan aslında olayı doğru mu anlatıyordu sence?

Enes Güran : Doğrudur. Furkan o zaman annemi hiç görmedi.

Av. Nahit Eren : Furkan hiç anneni görmedi.

Enes Güran : Evet.

Av. Nahit Eren : Az evvel meslektaşım sordu dedi ki kolunu bize göster.

Enes Güran : Evet.

Av. Nahit Eren : Gösterdin.

Enes Güran : Evet.

Av. Nahit Eren : Dedin ki belki o an gözden kaçmış olabilir. Isırdım. Sonra bir yerin üstüne mi koydum dedin? Ben mi yanlış anladım?

Enes Güran : Ben koltukta oturuyorum dedim. Kolumu böyle açtım. Böyle ısırarak koltuğun tarafına sert bir şekilde ısırarak bıraktım. Sırf ki ağlama sesim babama gitmesin diye.

Av. Nahit Eren : Odada hiç senin dışında kim vardı?

Enes Güran : Kimse yoktu.

Av. Nahit Eren : Tek başınaydın?

Enes Güran : Tek başınaydım.

Av. Nahit Eren : Tamam. Savcı Hanım da sordu. Ben de sana soracağım.

Enes Güran : Buyurun sorun.

Av. Nahit Eren : Bu biraz hani hayatın olağan akışında insanın sormak istediği bir soru. Aynı buradaysan Nevzat'a da sorduğum bir soru.

Enes Güran : Buyurun.

Av. Nahit Eren : Nevzat'a nasıl ki eğer normal bir kayıpsa baba daha doğrusu Salim seni aramalı mı aramamalı mı diye sordum. Sana da o minvalde bir soru soracağım. Cevap vermeme hakkına sahipsin. Şunu soracağım. İnsanın kardeşi kaybolsa iletişim anlamında en çok ihtiyaç duyduğu şey telefondur değil mi?


Enes Güran : Doğrudur.

Av. Nahit Eren : Mesela bu telefonu yanına almama konusunda mesela tatmin edecek bir şeyi bize hepinize bu salona izah edebilir misin?

Enes Güran : Tabii ki de izah edebilirim. Çünkü, sayın hakimim, annem telefonu aldığı zaman işte Hediye falan aradığı zaman annemle birlikte Muhammed kardeşimle birlikte Maşallah Güran'a bakan tepeye oraya çıktığımız zaman Maşallah Güran da bizim evimize gelmemiş. Yok dediği zaman telaşlandım. Ve hemen aşağı Muhammed'i alıp aşağı indim. Cami tarafına. Aynı yoldan ha saat dörtten de indim yoldan. Aynı yoldan oraya indim. Ve Muhammed'i Azize Kaya'nın evine gönderdim. Ben de cami tarafında kısık sesle Narin'i çağırıyordum. Yani telefon ya da ailem ya da babam. Kimse aklımda değildir. Sadece Narin nerede?

Av. Nahit Eren : Mesela o an hiç telefon arama yaparken hiç telefona ihtiyaç duymadın o zaman.

Enes Güran : Yok. Hatta ben Mısır tarlasına girdiğim zaman da Yunus Karacoşan'ın telefonu alarak ışığı açmıştım.

Av. Nahit Eren : Tamam. Şimdi eve geldiğinde uyandığında Hediye'yi gördüğünü söyledin.

Enes Güran : Doğrudur.

Av. Nahit Eren : Hediyeyle birbirimizi sorduğunuzu söylediniz.

Enes Güran : Doğrudur.

Av. Nahit Eren : Hediye'nin evinizden ne zaman çıktığını biliyor musun?

Enes Güran : Bilmiyorum. Nasıl bileyim ben?

Av. Nahit Eren : Yani görmedin anlamında yok?

Enes Güran : Ben zaten Hediye yengemi gördüğüm zaman zaten oradan çıkıp aşağı iniyorum. Ben Hediye'yi bir daha görmüyorum.

Av. Nahit Eren : Hediye iki saat kadar evinizde kaldı. Çıktığım zaman Enes dışarıdan geldi gibi bir ifadesi var. Bu yalan mı?

Enes Güran : Yani ben öyle bir şey Hediye Güran'ı kesinlikle görmedim.

Av. Nahit Eren : Hediye'yi evde görmedin?

Enes Güran : Yok. Sadece saat 4 civarlarında uyandığım zaman Hediye Güran'ı sordun. Başka Hediye Güran'ı görmedim yani.

Av. Nahit Eren : Çıkıştan sonra döndüğünde bir daha evde Hediye'yi görmedin?

Enes Güran : Yok. Görmedim.

Mahkeme Başkanı : Hediye şey diyor. Ben evdeyken Enes vardı. Ben daha sonradan kapıda Enes'i gördüm. Hangi ara çıktığını bilmiyorum. Tekrar eve geldi diyor. Avukat Bey oyunu soruyor. Sen bunu bilmediğim için ben izah etmedim.

Av. Nahit Eren : Sen Hediye'yi bir daha görmedin.

Enes Güran : Evet.

Av. Nahit Eren : Muhammed'den ilk çıkışında dışarı çeşmeye gittin geldin ya.

Enes Güran : Evet.

Av. Nahit Eren : Sonra Muhammed kardeşin olan Muhammed Emre'den bahsediyorsun değil mi?

Enes Güran : Evet, Emre'den bahsediyorum.

Av. Nahit Eren : Muhammed Emre'nin ifadesini okudun mu?

Enes Güran : Yok.

Av. Nahit Eren : Muhammed Emre kendisini ifade edebilecek bir yaşta mı sence?

Enes Güran : Yani çocuk hala kardeşinin kaybolduğunu bildiği sürece yani bence belli bir yaşta değil.

Av. Nahit Eren : Hediye size geldiği zaman sen Muhammed'in ne yaptığını hatırlıyor musun?

Enes Güran : Hediye'yi bize geldiğini ben ne zaman geldiğini bilmiyorum. Ben uyanıyorum ya. Onu mu diyorsun. Muhammed'in yattığını sadece gördüm.

Av. Nahit Eren : Muhammed yatıyordu. Muhammed sen uyanmış ki daha sonra senin yanına geldi.

Enes Güran : Tamam.

Av. Nahit Eren : Muhammed senin yanına geldiği zaman evde kimin olduğuna ya kimlerin olduğundan bahsetti mi?

Enes Güran : Yok.

Av. Nahit Eren : Muhammed peki evde kendisi uyandığında Hediye'yi görebilecek koşullara sahip mi?

Enes Güran : Yani zaten yattığımda..

Av. Nahit Eren : Hepiniz aynı odada mı?

Enes Güran : Hepimiz aynı odadayız yani. Hediye Güran'ı o saatte uyandığı zaman zaten Hediye Güran'ı görse der görmüşüm.

Av. Nahit Eren : Muhammed bütün ifadelerine diyor ki ben o gün Hediye'yi hiç görmedim.

Enes Güran : E yani ben sadece saat 4 civarında uyandığım zaman hatta sana koltuğu da tarif edeyim abi. Annem bu tarafta Hediye Güran bu tarafta yatıyor. Oturuyorlardı. Ben de bu tarafta pencere tarafında klima vuran tarafta yatıyordum. Uyandığım zaman yengem Hediye hoş geldin. İşte yengem hoş geldin falan filan dedikten sonra kapıdan aşağı indim.

Mahkeme Başkanı : Şey bir sayın savcım buyurun.

Duruşma Savcısı : Başkanıma destek olarak bir cümle kuracağım sana. Hediyeyi görmedim diyorsun ya.
Hediye seninle ilgili Eren eee Enes kapıdan dışarıdan gelirken ben kapıdan çıkıyordum. 17:00 - 17:30 civarı diyor. Çıkarken diyor hatta annesi Enes'e seslendi. Enes dedi, sen niye erken geldin dedi diyor. Enes sen de cevap olarak dışarıda kimse yoktu. Böyle bir diyaloğu bile söylüyor Hediye. Yani Hediye senin eve döndüğünü söylüyor o şekilde.

Enes Güran : Öyle bir şey yok.

Mahkeme Başkanı : Zaten hatırlamadığın için Hediye'nin beyanlarına teferruatlı girmedik biz. Onu sordum hatırlamadım dediği için Hediye'nin beyanlarına teferruatlı girmedik. Onu Hediye'yi dinleyince soracağız.

Av. Nahit Eren : Tamam başkanım.

Mahkeme Başkanı : Ben artık toparlayalım. Sizden rica ediyorum.

Av. Nahit Eren : Soru sorup bitireceğim. Sana yine senin işkence ve kötü muamele altında savcılığa ifade vermişsin. Ondan ilgili Salim'le ilgili yaptığın değerlendirmeleri de o baskı, o işkence altında mı verdin yoksa Salim'le ilgili yaptığın tanımlamalar doğru mu?

Enes Güran : Doğru değildir.

Av. Nahit Eren : Hayır Salim mesela seni gözünde Salim diyorum. Çok özür diliyorum. Nevzat. Nevzat'la ilgili bir tanımlama yapıyorsun ya.

Enes Güran : Evet.

Av. Nahit Eren : Bu tanımlama o bu işkence altında Nevzat'la ilgili yaptığın tanım.

Enes Güran : Nevzat'la ilgili bana işkence yapılmadı.

Av. Nahit Eren : Sadece Salim Güran tarafından bana işkence yapıldı. Hayır değil. Tamam.

Mahkeme Başkanı : Yani Nevzat'la ilgili söylediklerim doğrudur diyor.

Av. Nahit Eren : Nevzat'la ilgili söylediklerin baskı ve işkence altında söylediğin ifadeler değil.

Enes Güran : Evet.

Av. Nahit Eren : Nevzat'la ilgili bize bir tarif tarifleme yapabiliriz.

Av. Nahit Eren : "Pis bir insandır. Hıh. Ben açık konuşayım. Pis bir insandır. Köyün en pis insanıdır. Gider gelir ama hiç kimse ondan şey yapmaz yani. İşe gitti, ne yaptı, kimse bilmez. Yani bir araba altında var, bir oğlunun altındadır, bir onun altındadır. Hatta bir avukatım galiba burada dedi zaten. Onun avukatıydı galiba. Hatta dedi Nevzat işte geceleri artık Çarıklı'da kalıyordu. İşte o zaman da biz göz altındayken şey gelmiş işte Barış Güran. Amcam olur kendisi" dedi. "Ben kendim onları jandarma ekiplerini kendim onların evine götürdüm ve Nevzat'ın pencereden kaçtığını görüp Nevzat'ı orada yakaladılar" dedi.

Av. Nahit Eren : Peki Nevzat'la Salim arasındaki ilişkiyi bize nasıl tanımlayabilirsin?

Enes Güran : Yani Nevzat'la Salim, Salim Güran'ın arasında olan ilişkide benim bildiğim kadarıyla dostlar. Yani birbirlerini çok çoktan çok görüyordum birbirleriyle. Yan yanalar.

Av. Nahit Eren : İki kişi dost dost diye burada mantık yürütüyoruz birbirimize yani ifadeyi anlayabilmek için bu soruları açıyorum.

Enes Güran : Tamam buyurun.

Av. Nahit Eren : Dost olan biri birine şöyle bir cümle kullanıyorsun. Salim'in dediğini sorgulamayacak şekilde korkak bir insandır. Salim'in dediğini sorgulamayacak kadar korkak bir insan.

Enes Güran : Evet.

Av. Nahit Eren : Dost ilişkisinde mi arkadaşlar mı? Bu arkadaş ilişkisinde bir cesedi yani bir pardon Narin'in naaşını alıp götürecek kadar korkak biri mi? Yoksa aralarındaki ilişki biat ilişkisi ise hiç sorgulamadan alıp götürecek biri mi? Çünkü bunu bu ifadeyi sana okudukları ve bunun üzerine sana soruyorlar. Ben de o yüzden o ifade. Şunu soruyorum.

Enes Güran : Buyurun.

Av. Nahit Eren : Sen diyorsun ki bu şahıs, bu şahıs korkak bir insan.

Enes Güran : Evet.

Av. Nahit Eren : Bu korkak insanla Salim arasındaki ilişkiyi sen de biliyorsun.

Enes Güran : Evet.

Av. Nahit Eren : Hukukları var, arkadaşlıkları var.

Enes Güran : Evet.

Av. Nahit Eren : Birlikte geziyorlar. Hatta birlikte yedikleri restorana gittiğini ifade edenler var. Sen de ifadende diyorsun ki Salim'in ona Salim'in dediğini sorgulamayacak şekilde korkak biridir.

Enes Güran : Çünkü cevaplayayım mi?

Av. Nahit Eren : Çünkü Nevzat köyün en fakir insanı olduğu için ve hiçbir şeyi olmadığı için arkadaşı olmadığı için Salim Güran köyün muhtarı ve istediği her şeyi yapabilen mesela savcılığa gelebilir. Mesela bir itiraz olursa Nevzat onu arayıp mesela işte bu benim bu sıkıntımı halleder misin diye Salim'le hoş beşlik ya da onun kendi arasını bozulmaması için bunu demiştim.

Mahkeme Başkanı : Ben sana çok amiyane sorayım.

Enes Güran : Buyurun sayın başkanım.

Mahkeme Başkanı : Başkanım ki soran yani naif sordu. Ben direkt direkt arkadaşça soruyorum. Nevzat öldürse özür diliyorum. Salim öldürse, Nevzat bu cesedi kaybet dese. Nevzat bunu yapar mı?

Enes Güran : Yapmaz.

Mahkeme Başkanı : Bu kadar basit. Sorunuzun amiyanesi bu. Doğru mu? Tamam başkanım. Yok. Şey amiyane siz daha süslü cümleler kurdunuz. Ben daha net sordum yani.

Mahkeme Başkanı : Baskı altında anlayan ifadeler olduğu için.

Mahkeme Başkanı : Yok anladım da direkt ben direkt net anlayabileceği sordum yani. Siz daha süslü cümleyle sorunca konu dağıldı. Buyurun. Devam edebilirsiniz.

Av. Nahit Eren : Ben sana son bir soru soracağım.

Enes Güran : Sorun.

Av. Nahit Eren : Arkadaşlarımız sana sordu. Biz de aldık dosyada senin bütün cezaevi görüşmelerinin hepsi dosyada. Bütün hem görüntülü aramaların, görüşmelerin hepsi var.

Enes Güran : Doğrudur. Sosyal medyaya da sızdırılmıştı. Benim ailemle konuştuğum ses görüntüleri.

Av. Nahit Eren : Evet evet ondan bahsediyorum. Evet. Ailenle, babanla, kardeşinle hepsiyle konuştular.

Enes Güran : Evet.

Av. Nahit Eren : Ya benim de dikkatimi bir şey çekti. Buyurun. Narin'in abisi olarak cevap vermeni.

Enes Güran : Evet.

Av. Nahit Eren : Rica edeceğim. Ya ne kadar görüşürseniz özellikle Baran'la yaptığınız bütün görüşmelerde.

Enes Güran : Evet.

Av. Nahit Eren : Sen gerçekten sürekli bir dosyayı merak ediyorsun.

Enes Güran : Evet.

Av. Nahit Eren : Sürekli raporları soruyorsun.

Enes Güran : Evet.

Av. Nahit Eren : Halıların Van'a gidişini soruyorsun. Diş fırçanı soruyorsun.

Enes Güran : Evet.

Av. Nahit Eren : Narin'i öptüm şey hiçbir ifadende olmayan Narin'i öptüm camiye giderken abi bir şey olur mu? Hatta abin söylüyor onu avukatlara dedin mi demedin mi ifadende? Diyorsun ki hayır demedim. Şimdi bir şey sor. Bu tür konulara her girişinde sen anlatırken sen bir şeyleri merak ederken raporu soruyorsun.

Enes Güran : Evet.

Av. Nahit Eren : Raporu bu kadar merak etmendeki biz de ceza hukukçuları olarak avukatlar olarak bir raporu merak ederken kaygılandığın bir delilin çıkma ihtimalini sorguluyorsun diye bakarız. Sana açıklayarak soruyorum. Korktuğun bir şey mi vardı o raporlardan?

Enes Güran : Kesinlikle yok. Kesinlikle yok.

Av. Nahit Eren : Mesela fırçayı sorduğun zaman neyi düşündün? Ya mesela sabah benim fırçamdan dişini fırçaladı Narin.

Enes Güran : Evet.

Av. Nahit Eren : "Abi bir şey olur mu?"'dan kastın ney, ben merak ediyorum.

Enes Güran : Sabahleyin Narin diş fırçamı kullanmadığı zaman ben kullanmıştım o diş fırçayı. Ve Narin sonradan benim diş fırçamı kullandığı zaman cezaevindeyim. Cezaevinde hayatımda ilk kez.

Av. Nahit Eren : Ben de onu soruyorum.

Enes Güran : Tamam işte. Cezaevinde hayatımı ilk kez görmüşüm. Karakolu bile hayatımda ilk kez görmüş bir insanım ben. Yani o dört duvar arasında bazı bazı gardiyanlar var mesela. İyi davranmıyor. Kötü şeyler konuşuyor. İnsanın zoruna gidiyor. Ama insanın babası ya da ailesi arkasında olmadığı zaman insan ses çıkartamıyor. Ben de mesela raporları neden çok merak ediyordum? Diyordum ki kardeşimin raporu çıkacak ve katiller ortaya çıkacak ve bizlerin suçsuz olduğu ortaya çıkacak. Halılara geldiğimiz zaman halılara da yani il jandarmada o kadar rezil ve şekilde küfür ve hakaret yediğimiz zaman ve benim annem işkence yapıldığı zaman gelip de benim önümde sesini açarak izlediği videoda psikolojim bozulduğu için bana sordukları sorularda psikolojim bozulduğu için şüphelendim ben. Ciddi söylüyorum. Bak ben bunu.

Av. Nahit Eren : Nasıl bir şüphe?

Enes Güran : Yani o kadar dediler işte Nevzat işte bunu yapmış, işte bunu yapmış, Salim'le bunu yapmış, bunu da çok şey denildi. Ama ki mesela o il jandarmada bize düzgün bir şekilde insani şekilde davransalardı zaten her şeyi biz onlara konuşurduk. Çünkü ben ilk günden beri askeriyelere de her şeye de ben doğruyu konuşuyorum. Ben ilk günden beri ben kardeşimin bulunmasını istiyorum.

Av. Nahit Eren : Hele diş fırçasından kaynaklı kaygının hani teknik alanda kaygın neydi?

Enes Güran : Ben de raporun ne olduğunu bilmediğim için yani üzerinde kalır mı? Kalmaz mı? Diş fırçamı kullanmış sonuçta. Suçsuz olduğum halde.

Mahkeme Başkanı : Korku ve panikle sorduğum soru diyorsun yani kısaca.

Enes Güran : Yani cezaevi mesela şu anda hücrede kalıyorum mesela ben. Ama ailem bunu bilmiyor.

Mahkeme Başkanı : Diyarbakır Barosu başka soru var mı? Yok. Sayın Arif Güran vekili sormak istediğiniz bir şey var mıdır? Yok. Aile Sosyal Politikalar Bakanlığı tekrara kaçmamak şartıyla soru var mıdır? Avukat Bey çelişkilerini sonra gidereceğiz. Sadece soru alacağız. Buyurun. Adınızı söyleyin.

## Aile ve Sosyal Hiz. Bakanlığı

### Av. Elif Aslı Şahin Torun

Av. Elif Aslı Şahin Torun : Aynı gün olay saatinde anneniz Yüksel Güran'ın saat 14:28'de telefonu kapadığı, 15:38'de açtığı, sizin ise 14:30'da kapadığınız ve 15:41'de açtığınız yani eş zamanlı olarak kapatılmış ve bir saat sonra açılmış. Bu 1 saat sürede neler oldu? Neden kapadınız?

Enes Güran : Zaten saat 4'e kadar ben yatıyorum. Telefonum zaten orada.

Av. Elif Aslı Şahin Torun : 4'e kadar. Ama telefonu 15:41'de açmışsınız. 15:41. Açmışsınız telefonu.

Enes Güran : 15:41'de arama gelmiştir yüzde doksan. Şahin aramıştır beni. Yani o saat o saatte.

Av. Elif Aslı Şahin Torun : O saatte de esas kayıtları zaten orada gösterir. O saatte evde dört tane kişi var. Narin geldi.

Enes Güran : Öyle bir şey, ya vallahi öyle bir şey yok yani, Salim Güran ya da Nevzat Bahtiyar.

Mahkeme Başkanı : Öyleydi zaten. Kimsenin geldiğini bilmiyorum dedi.

Enes Güran : İşte yani gelip de giremezler benim evime. Çünkü ben o evdeyim ben. Kimse gelip benim bacımı benim evimden alamaz. İsterse bu köpek olsun. İsterse karşımdaki amcam olsun.

Mahkeme Başkanı : Hakaret etme de.

Av. Elif Aslı Şahin Torun : Narin görmemesi gereken bir şey mi gördü Enes Bey?

Enes Güran : Bilmiyorum.

Av. Elif Aslı Şahin Torun : Tamam.

Mahkeme Başkanı : Hakaret değil Enes. Tamam sakin. Yani aksi bir durumda sana da burada hakaret edilse hoşuna gider mi? Jandarman hakaretinden şikayet ediyorsun. Biz de hakaret etmeyelim, tamam? Tamam özrünü kabul ettik. Çelişki değil soru.

### Av. Abdullah Yılmaz

Av. Abdullah Yılmaz : Saat 21 sıralarında 24'ü yani Narin kaybolduktan üç gün sonra.

Enes Güran : Evet.

Av. Abdullah Yılmaz : Bir tane yangın çıkıyor.

Enes Güran : Evet.

Av. Abdullah Yılmaz : Bir de sürekli şeyler oluyor. Elektrik kesintileri meydana geliyor. Daha önce böyle şeyler var mıydı köyünüzde?

Enes Güran : Yani elektrik kesintileri pek bilmiyorum. Çünkü ben 20'sinde gelmişim. 21'inde kardeşim.

Mahkeme Başkanı : Daha önce yani iki ay önce, üç ay önce köyde elektrik kesinti olur mu?

Enes Güran : Olurdu. Şartel atıyordu. Mesela gidip şarteli kaldırıyorduk.

Mahkeme Başkanı : Bazen Diyarbakır'da her zaman oluyor elektrik kesintisi.

Av. Abdullah Yılmaz : Bu yangını biraz detaylandıracaklar mı?

Enes Güran : Yangını ben sana abi detaylı olarak anlatayım. Çünkü ben o yangın esnasında ben de oradaydım. Yangın biz hatta Ömer Güran vardır. Bir de Ömer Güran bir arkadaşı vardır. İşte biz cami tarafında oturduğumuz zaman Ömer Güran işte TikTok muydu ya da bir tane şeyhle konuşuyorlardı. Diyordu Narin bir evin kapısının önünde geçen su var. Bir de kırılan bir ağaç var. Bir de bize dedik hani Hacı Rıza Güran vardır. Çünkü ağaç kırılmış. Bir de kapısının önünde su geçiyor. Dedik oraya gidip bakalım. Oraya gittik baktık. Civarları hepsini kontrol ettik. Hiçbir şey bulamadık. Ve o esnada Hacı Rıza Güran bahçesinin tarafına çıkış yapacağımız esnada Erhan Güran evinin tarafına gireceğimiz esnada teller birbirine çarptı. Ve ben de bahçe içi değil de bahçe dışındaki olan telin altındaydım zaten. Yangın, bir baktım burası tutuştu. Burayı söndürmeye çalıştıkları zaman benim tarafa düştü bu sefer. E yok. Sayın hakimim yani dört beş defa yani üst üste ateş düştü. Onu onu mu söndüreyim bunu mu söndüreyim?

Mahkeme Başkanı : Yok canım kimse sana bir şey söndür demiyor. Sadece buradaki iddia şu Enes. Bu yangının şüpheli olduğu, delilleri gizlemek için Salim tarafından ya da sizlerin tarafından organize edildiği, o gün havanın rüzgarlı olmadığı, yangın çıkmasını gerektirecek bir sebep olmadığı dahil tutanak olduğu için avukat bey bunu soruyor.

Av. Abdullah Yılmaz : Şimdi bak Enes samimi konuşacağım sayın başkanım izin verirse.

Mahkeme Başkanı : Tabii ki buyurun.

Av. Abdullah Yılmaz : Şimdi bak Narin kayboluyor 21'inde.

Enes Güran : Evet.

Av. Abdullah Yılmaz : 23, 23'ünde çok sayıda Narin'in kaybolduğu saate ilişkin çelişkili beyan veriliyor.

Enes Güran : Tamam.

Av. Abdullah Yılmaz : Kronolojik sıraya göre sıralıyorum.

Enes Güran : Evet.

Av. Abdullah Yılmaz : 24'ünde bu yangın çıkıyor.

Enes Güran : Evet.

Av. Abdullah Yılmaz : 26'sında senin işte rapor için gönderiyorlar.

Enes Güran : Evet.

Av. Abdullah Yılmaz : Tamam mı? 27'sinde bak kadınlar kavga ediyor.

Enes Güran : Doğru.

Av. Abdullah Yılmaz : Bir sürü kadın var. Hepsini zaten başkanım sordu.

Enes Güran : Evet.

Av. Abdullah Yılmaz : Bak bunlar hepsi şüpheli hareketler değil mi? Normal hayatında yani olağan akışına aykırı değil mi bunlar?

Enes Güran : Yani pek bilmiyorum.

Av. Abdullah Yılmaz : Dolayısıyla onun için bu sorular soruluyor.

Enes Güran : Mesela ateş konusunu sana söyleyeyim abim avukat abim. Yani teller gerçekten yani kimse yani gidip de vurmadı. Çünkü telin altında ben varım.

Mahkeme Başkanı : Görmedin. Kimsenin vurduğunu görmedin yani?

Enes Güran : Teller hepsi birbiriyle çarpıştı. Kendi tarafından.

## Enes Güran müdafi

### Av. Mustafa Demir

Av. Mustafa Demir : Gerçekten hani anlaşılmaz bir soruşturma yürütülmüş doğru kelimeyi bulmakta zorlanıyorum. Dosya içerisinde müvekkilin cezaevinde ailesiyle yaptığı görüşmeler girmiş. Bu görüşmeler iddianamede de yer alıyor ve görüşmelerin tamamı özellikle sokulmuş. Bunlar bilerek servis edilmiş sosyal medyada bunlar algı ya bu dosya tamamen zaten algı üzerine başlayıp devam eden bir dosya şu anda da, algıların devam ettiğini hala görüyoruz.

Mahkeme Başkanı : O sesleri cezaevi görüşmelerini kim yaydı?

Av. Mustafa Demir : Bilmiyoruz.

Mahkeme Başkanı : Bir iddia sizin yaydığınız sizin kendi adınıza algı oluşturduğunuz.

Av. Mustafa Demir : Evet evet biz yaydık şöyle bir algı oluşturmak için. Bakın aile gülüyor ediyor diye.

Mahkeme Başkanı : Bilmiyorum. Bana yani ben bana bu soru sorulduğunda ben mahkeme olarak bütün videolar herkese açık sanık müdafileri başta olmak üzere dosyanın taraflarına.

Av. Mustafa Demir : Girmesi zaten tartışma. Ha o ayrı. Biz verdik bunu. Bu tartışmayı yaşatmadık. Girmedik neden? Zaten herkes her şeyi biliyordu. Şimdi şu algı olmasın. Konuşulması istenmiyor. Sanki bir şeyler gizlenmeye çalışıyor. Ama böyle bir kaygımız, böyle bir şeyimiz kesinlikle yok. Konuşulsun dedik ama sonrasında da bunun yasak delil olduğu için dosyadan da çıkarılması gerektiğini bildiğimizi ifade etmek istiyoruz burada. Neden yasak delil? Şimdi öncelikle konuşmalar kesilmiş zaten. Evet. Konuşmaların tamamı dinlenirse iki konuşma alınıyor. Bir kardeşi Eren'le altı yaşındaki kardeşiyle konuşuyor. Bu konuşmada kimseyle konuşma diyor. Ama öncesini bir dinlemek lazım. Öncesinde şu konuşuluyor. Ne yapıyorsun? Nasılsın abican? İyidir falan diyor. Ben burada çalışıyorum. Merak etme şey etme. Ya unutmayalım. Kendisi de ifade etti. Altı yaşında kardeşi ablasını kaybetti. Yani çok feci şekilde yani bütün aileye yıldırım düştü. Unutmayalım. Annesi alındı bu kişinin çocuğun altı yaşındakinin yok. Bir abisi yok. Ablası yok. Babası zaten artık bitap durumda. Evin içerisinde bunu gizlenmesi insani bir durum mudur? Gerçekten insani bir durumdur. Burada diğerleriyle konuşma hani kimseyle yani konuşma kimsenin dediğini aldırma anlamında olan konuşmayı önüne almayarak bir yere çekmek için neden? Çünkü iddianame zaten zorlama iddianame. Birazdan birçok şeyi göstereceğiz. Yani mesela az önce telefonla ilgili WhatsApp'la ilgili soruluyor ya göreceksiniz onu aslında ne olduğunu. Yani herkes anlayacak ne olduğunu. Çünkü anlaşılmamış ama ben çok net onu anlatacağım. Burada biz dayanak olarak bir içtihat sunulmuş. İçtihat temeline bakıyoruz. Zaten içtihat değişik bir karar. İki bin on altı tarihli on sekizinci ceza dairesinden içtihat şunu söylüyor. Bir hükümlü cezaevindeyken telefon konuşmasında ikinci müdüre küfür etmiş. İlk derece mahkemesi beraat şey ceza vermiş. Yargıtaya gitmiş. Yargıtay beraat vermiş. Üç yüz sekiz uyanınca Cumhuriyet Başsavcısı itiraz etmiş. İtiraz sonucunda oy çokluğuyla oy birliğiyle de değil oy çokluğuyla bir karar çıkmış. Burada kararın dayanan da şunu söylüyor. Diyor ki kişi tutuklu veya hükümlüyse devletin gözetimindedir. Burada kişinin suç işlemesini gözetlemek veya bir suça teşvik etmek azmettirmesini önlemek devletten beklenecek bir şeydir. Bunun için bu kişinin dinlenip buradan oluşacak durumun yani yeni suçun önlenmesi beklenmelidir. Karar bu. Bizim durumumuz buna uygun mu? Kesinlikle değil. Kesinlikle değil. Bakacağız. Yani bizim durumumuz buna uygun değil.

Mahkeme Başkanı : Onların hepsine biz bakacağız.

Av. Mustafa Demir : Yüz otuz beş CMK yüz otuz beşte açık düzenleme var. Bunlar delil uğramazdı. Buradaki kaygılarını yine dediğimiz gibi açıkça anlattı. Lütfen herkesten hani bir kısım şeye baktılar ya herkes bir kısım dinledi. Tamamını dinlesinler. Yani o konuşmaların tamamı dinlensin. Madem hepsi her yerde var. Her herkes paylaştı. İlk günlerde neler olmuş? Çocuk ilk günlerde ağlamaktan aileyle konuşabiliyor mu? Devamında nasıl? Biz burada bu delilin de yasak delil olduğunu ifade etmek istiyoruz. Dosya içerisine ilk başta itiraz etmedik. Sorular da soruldu. Ama bu dosyanın birçok noktasında göreceğiniz üzere hep yasak deliller mevcut. Bu da o yasak delillerden biri. Bu noktada bu delile de itiraz ediyoruz. 
