---
title: Test
---

Metin: 4 YIL, 6 AY, 2.5 yıl, 1-2 yıl, 6 ay, 3–5 ay, 19 gün, 15–20 gün, 3 saat, 3–4 saat, 15 dakika, 5–10 dakika, 1 saniye, 3–4 saniye,  vakti, "22.08.2024 saat 00:31 sıralarında", 3 ayrı bulgu poşeti, 7 dakika’da, aradan 3 ile 6 gün geçmiş. 1.5 saat ile yarım saat arasında çok ciddi bir fark var. Yarım gün. 22 Ağustos’ta diyorsun. 22.08'de diyorum. 17:46 saniye 32’de 41 saniyelik telefon görüşmen var senin. Tavşantepe köyüne; 29.08.2024--30.08.2024 tarihlerinde 47 XX 388 3 adet ve 6 parça.

 19 gün, 15–20 gün, 6 günlük, 6 günden, 6 günlüğüne, 0530XXX0653
 
Metin: 15 saniye, 23 dakika, 3 gün, 4 yıl, 6 ay, 15 SANİYE, 23 DAKİKA, 3 GÜN, 4 YIL, 6 AY, **4 yıl, 6 ay**, **4 YIL, 6 AY**,

41 saniyelik Tavşantepe köyüne; 29.08.2024--30.08.2024 tarihlerinde 2 hafta süreyle

Tavşantepe köyüne; 29.08.2024--30.08.2024 tarihlerinde ve Narin GÜRAN'ın cesedinin bulunduğu tarih olan 08.09.2024--09.09.2024 tarihlerinde gidilerek;

> Tavşantepe köyüne; 29.08.2024--30.08.2024 tarihlerinde ve Narin GÜRAN'ın cesedinin bulunduğu tarih olan 08.09.2024--09.09.2024 tarihlerinde gidilerek;

> * Tavşantepe köyüne; 29.08.2024--30.08.2024 tarihlerinde ve Narin GÜRAN'ın cesedinin bulunduğu tarih olan 08.09.2024--09.09.2024 tarihlerinde gidilerek;

Neden bu 6 günlük süreç zarfında gidip 5 dakikalık itirafçı 3 yıllık olmadınız?
Neden bu 6 günden süreç zarfında gidip 5 dakikanın itirafçı 3 yıllığına olmadınız?
Neden bu 6 günlüğüne süreç zarfında gidip 5 aylığına itirafçı 3 yıllığına olmadınız?
Neden bu 6 günlüğünü süreç zarfında gidip 5 saniyeden itirafçı 3 yıla olmadınız?

Sanığa verilen ceza miktarı, yine verilen cezanın CMK’nın 100/3 maddesinde sayılan
Sözleşmesinin 5. Maddesinde öngörülen geçerli şüphe sebeplerinin, 1982 Anayasasının 19. Maddesinde
2024/9733 numarasına kayıtlı
2024-109 numaralı sayısal
7242 sayılı Kanunun 10. maddesi
5237 karar sayılı TCK’nın 82/1-d-e maddesi gereğince

1 ve 2. fıkraları ile 3. fıkrasının birinci cümlesinin
1. ve 2. fıkraları ile 3. fıkrasının birinci cümlesinin

Ayıplı mal olduğu anlaşıldıktan sonra her zaman alıcı 200 lira "ayıpta bedelde indirim ister ama bedelde indirim gösterilen bedel üzerinden yapılır. Aslında burada Bahtiyar ayıplı olduğunu bildiği aracı önceden indirimini yapmış, veriyor, ucuza veriyor. Hakikaten ucuza veriyor. Daha sonrasında onun önüne bir hesap çıkartılıyor. 80.000 TL. Ben olsam sinirlenirim. Ben olsam kızarım. Hem ucuza araba veriyorsun hem de gelip sende para istiyorlar. 50.000 TL istiyorlar. Bildiğim kadarıyla 40.000 TL vermiş."

Diyarbakır İl Jandarma Komutanlığı tarafından düzenlenen analiz raporunda; sanık Salim Güran’ın kullanımında olan 0530XXX0653 no’lu telefon, Sanık Nevzat Bahtiyar’ın kullanımında olan 0533XXX9779 no’lu telefon, sanık Yüksel Güran’ın kullanımında olan 0536XXX7120 no’lu telefon ile sanık Enes Güran’ın kullanımında olan 0539XXX7358 no’lu telefon HTS kayıtlarının incelendiği ve baz verilerinin karşılaştırıldığı görülmüştür. Söz konusu raporda;
 
[Hello, how are you?]{.bracket-box}
 
:::{.warning}
Hello How are you?
:::
