---
title: "Yüksel Güran Savunması"
word-cloud: true
editor: source
---
## Av. Doğuş Can KURUCU

### Savunmanın Amacı ve Adil Yargılanma İlkeleri

Sayın başkan, biz bir önceki duruşmada savunmamıza başlarken belirtmiş olduğumuz bir hususu yeniden dile getirerek başlayacağız. Çünkü burada bulunmamızın tek nedeni Narin kardeşimizin vahşice bir şekilde katledilmesi ve bu vahşice katledilmesinden kaynaklı olan problemin, bu yaşanan üzücü durumun maddi açıdan şüphe uyandırmayacak şekilde açığa çıkması ve gerçek failin cezalandırılması için buradayız biz. Bunu belirttikten sonra, sayın başkan biz burada savunma müdafiliği rolünü üstlenirken aynı zamanda adil yargılanma için buradayız ve bu adil yargılanma için bizim hukukumuzda ve diğer evrensel bütün hukuklarda Avrupa hukuk sisteminde Çağdaş Ceza Hukukunun evrensel ilkeleri vardır. Bu ilkelerin bu dosya kapsamına da sizin başkanlığınız ve heyetiniz nezdinde şüphe uyardırmayacak şekilde uygulayacağınıza inancımız tamdır. Şimdi sayın başkan kıymetli meslektaşlarımız burada birçok açıklama yaptı. Ben burada sizi çok fazla yormayacağım ancak herkesin değindiği ama ayrıntıya inmediği bir husus var. Önce onunla başlayacağım, şimdi sayın başkan ailenin şüpheli konumuna getirilmesi başta müvekkilim için konuşuyorum. Tabi ben soruşturmanın CMK'nun madde 157 çok açık gizlilik kararı alınıyor ama bu gizlilik kararı alındıktan sonra basına sosyal medyaya dolaylı veya doğrudan nasıl yapıldığını bilmiyoruz, bir şekilde yalan haberlerin pompalandığını biliyoruz. Bu haberler ile birlikte soruşturmanın ben jandarma tutanaklarına gıybet tutanağı diyorum. Bu gıybet tutanakları ile bu objektif olmayan öznel yorumlarla başta müvekkilim olmak üzere ailesi deyim yerindeyse hedef haline getirildi. Şimdi bu yalan haberler ile ilgili ve bu yalan haberlerin soruşturmayı ne kadar etkilediğini, bu soruşturmanın bizce kabul olmayan iddianamesi ve bizce itiraz ettiğimiz mütalaaya dönüşmesine yönelik itirazlarımız var. Biz bunları açıklamak istiyoruz. Tabi bundan önce şundan da bahsetmek istiyorum. Sayın başkanım şimdi artık uzay çağındayız. Bu yüzyılda gerçeklik algısı da oldukça değişkenlik gösteriyor. Maalesef eskisi gibi değil.

### Medya Çağında Gerçeklik Algısı ve İlk Yalan İddialar

Profesör Doktor Hüseyin Hetemi, aslında ceza hukukçusu değildir, ben kendisinin öğrencisiyim son zamanlarda sosyal medyasını iyi de takip eden biriyim, gezerken gerçeklik ile ilgili şöyle bir şey yazdığını gördüm ben. Önce onunla başlayayım. Şöyle diyor hocamız, sosyal medyaya ve televizyona düşmeyen şey artık gerçek kabul edilmiyor. Bu sebeple gerçek yatağında kıvranarak öldü. Bu yüzyılda yalan ve algının çağıdır. Deccal'ın gözü ise medyadır. Maalesef müvekkilime ve ailesine yönelik yapılan yalan haberler iddianameye ve mütalaaya konu edildi, bundan dolayı biz bunları açıklamak istiyoruz. Şimdi sayın başkan ilk kısma bakalım müvekkil ile ilgili bulunan bir terliğin Narin'e ait olduğu ve annenin bu konuda yanılttığı iddiası vardı ilk başlarda. Zaten dosya bu terlik meselesinin kıymetli meslektaşlarımız da konuştu söyledi; terlik meselesi aile bireylerine fotoğrafı atıldıktan hemen sonra Narin'e ait olmadığı anlaşılıyor, ayak numaralarından dolayı. Bu konu bu şekilde kapandı ama bu sosyal medyada kapanmadı hala konuşuluyor. İkincisi burada Arif bey buradaysa ondan çok özür diliyorum, Enes'ten yine çok özür diliyorum, Yüksel ablam'dan çok özür diliyorum, Narin kardeşimizin Salim'in öz kızı olduğu iddiası çok iğrenç bir şey, mide bulandırıcı bir şekilde kamuoyuna oturdu. Bir annenin, kızını kaybetmiş bir annenin yaşadığı sanki acı yetmiyormuş gibi, iffetine yönelik bir sürü iddialarda bulunuldu. Dosya içerisinde var. Narin kızımızın ki yani böyle raporun olmasından ben şahsen utanarak söylüyorum. Annesinin Yüksel Güran, babasının Arif Güran olduğunun belirtildiği bir rapor da dosya içerisinde mevcut. Bunun da yalan olduğunu söylemek istiyoruz. Bunun dışında burası da önemli, müvekkilim Yüksel Güran bu kan kalıntılarını yok etmek için yeniden kan alıp onun gizlice kendi kanını aldırılıp iddiasıyla hani delilleri yok etmeye çalıştığı bir durum var. Şimdi dosya içerisinde yine akıl dışı kolluk görevlilerinin yapmış olduğu bir faaliyet. Üfürükçü meselesi. Herkesin burada değindiği bir konu biliyorsunuz, üfürükçü meselesinde jandarmanın kendi tutanağı var. Bir anne düşünün ki, o kadar kötü bir durumda hiçbir şeyi sorgulamıyor, kızını bulabilme umuduyla bunlara böyle saçma sapan bir şey söyleniyor.

### Yaygınlaşan Asılsız İddialar ve Medyanın Rolü

Bir jandarma tarafından kadın gidip kanını veriyor, bundan dolayı suçlu oluyor. Kimse mesela şunu düşünmüyor, bu kadın o kadar kötü bir durumda ki artık hiçbir şeyi sorgulamıyor. Kızını bulabilmek için o sıra ondan canını isteseler, canını verecek. Bu kan vermenin de bundan başka bir durumu gösterdiğini biz düşünmüyoruz. Yine Salim Güran ile müvekkilim Yüksel Güran'ın olay günü telefon ile görüştüğü iddiası var. Dosya içerisinde zaten mevcut bunlar. Benim müvekkilim Salim Güran'ı hiçbir şekilde aramadığı, dosya içerisindeki belgelerden, arama kayıtlarından net bir şekilde belli ama tabi bunlar yalan haberler. Şimdi bu olay başladığı günden beri bitmek bilmedi. İçişleri Bakanlığı'nın atmış olduğu bir tweet var. Belki görmüşünüzdür. Yaklaşık dört buçuk beş milyonun atıldığı bir tweet var. Narin dosyası ile ilgili bunların %49'u bot hesap, geri kalan normal hesaplardan. Gerçeklik payı burada anlatılan durumlardan ibaret. Hiçbiri gerçek değil. Devam edeceğim. Ben bu halıların yıkandığı iddiası vardı. Halılar şöyle yıkanmış. Yüksel Güran halılarını yıkamış, delilleri karartmış, yok etmiş. Yine rapor da var. Raporda birebir şöyle bir şey geçiyor. "Yapılan tespitler sonucunda halıların yıkanmadığı ve dışarıda herhangi bir müdahaleye ilişkin bir tespit yapılamadığı" direk tutanakta şu şekilde geçiyor. Ama müvekkilim için devam ettiler, durmadılar, durmakta bilmiyorlar. Hala bile atılı tweet'ler var. "Yansın, gebersin". Ya bu tarz şeyler ile bu dosyanın yargılamasını etkileyenlere en büyük cevabı siz vereceksiniz. Biz buna inanıyoruz. Bunun dışında yine tedbir için tuşlu telefon kullandığı iddiası. Benim müvekkilimin bir tane telefonu vardı. Onda direk soruşturma aşamasında zaten alındı, incelendi. Temiz olduğu da ortaya çıktı. Yine Narin'in bir köpeği olduğu, prenses diye bir ismi olduğu, bu köpek işte bu köpeğin şimdi bir problemi var aslında.

### Temelsiz ve Cinsel Fantazilere Dayalı Suçlamalar

Köpek ile ilgili haberlerin anneye dokundu, Enes'e dokundu bir de sanırım bu köpeğin bir de hani mide bulandırıcı ama cinsel şeyler ile ilgili saçma sapan, tutarsız dosya içerisinde bulunmayan iftiralar ile başka haberlerle kamuoyunda algı yarattılar ki dosyada ve diğer tanıkların da vermiş olduğu ifadeler, başta babası müşteki taraf Arif Güran ile vermiş olduğu, Narin'in böyle bir köpeğinin hiçbir zaman olmadığı. Kendisi maalesef biz tanıyamadık, vahşice katledilmesinden dolayı köpeklerden korktuğunu da öğrendik. Evlere kameralar takıldı, bütün evler kameralar ile doldu ve bunu söylemediler. Sayın başkan 4 Eylül'de Erhan Güran'ın kamerası vardı, evine taktı. Onun da kendisi de zaten bunun sebebini belirtti. Başka bir kamera da aile bireyleri tarafından takılmadı. Köyde aileden olmayan başka insanların taktığını biliyoruz. Niye taktıklarını da biliyoruz. Korkuyorlar çünkü gece belki bir şey olur, evlerinin önüne bir şey atarlar, suçlanırlar. Yine Enes Güran'ın uyuşturucu bağımlısı olduğu iddiası. Bu sebeple bir şeyler yaptı, sözüm ona müvekkilim anne Yüksel Güran gördü, oğlunu koruyor iddiası tamamen mesnetsiz. Köyde çok sayıda isimsiz çocuk mezarlarının olduğu mesnetsiz, bir de bu dosyanın konusu değil ama ama aile ile ilgili suçlamalar var ve bu suçlamaların birçoğu maalesef ki hep bir cinsel fantezinin doğurmuş olduğu saçma sapan mesnetsiz şeyler. Mesela Hediye Güran ile ilgili, yok ertesi gün hapı almış, yok şöyle olmuş, böyle olmuş. Şimdi sayın başkan dosyada yapılan araştırmalar belli Çarıklı'da bir sağlık ocağına gidiyor, durumunu anlatıyor. Eczaneden alıyor, eşi oradayken alıyor ve ertesi günü hapı değil. Doğum kontrol hapı alıyor. Unutmayalım ki, ben tabi bilemem biyolojik açıdan bir kadın değilim ama benim bildiğim araştırdığım şey, doğum kontrol hapı ile ertesi gününün o hapın aynı işlevde olmadığı, aynı ürün olmadığı. Yine ceset daha hızlı çürüsün diye DSİ'de çalışan amca Kurtuluş Güran güya suyun debisini bilerek yükseltti, ceset bulunmasın diye. Sayın başkan dosya içerisinde DSİ'ye yönelik yazılan müzekkereler vardı. Bu müzekkerelerden sonra Cumhuriyet Başsavcılığı'ndan talep edilmesi üzerine suyun debisinin daha doğrusunun yönünün değiştirildiği belirtildi.

### Şehir Efsaneleri, Sahte Ses Kayıtları ve Diğer Yalanlar

Yani orada çalışan hiç kimsenin böyle bir şey yapma, böyle bir şey yapma yetkisi olmadığı gibi böyle bir durumda söz konusu değil. Bir de Van konusu meselesi vardı. Yani mesela bunu biraz şehir efsanesi diye ben nitelendirdim. Güya Narin yaşıyormuş, helikopterle Van'a kaçırmışlar, hastaneye bırakmışlar. Ütopik kurgular, en önemlisi sayın başkanım ben buranın çok önemli olduğunu düşünüyorum, maalesef bu dosyadan prim kazanan bazı gazetecilerin en büyük haberi şuydu "Ramazan kız öldü mü, yaşıyor mu" iddiası ile bir ses kaydı varmış. Güya bu ses kaydı bir önceki duruşmada da daha detaylı bir şekilde incelendi. Konuşulan Kürtçe Türkçe'ye çevrildiğinde herkesin bunu gayet iyi anladığını düşünüyorum. Böyle bir durumunda olmadığını, bir de sayın başkan Beşikdüzü Belediyesi varmış Beşikdüzü. Bu bendost diye bir Twitter kullanıcısı varmış sayın başkan. Yardım toplamış Narin için fidan dikilecek diye Beşikdüzü, sonra insanları dolandırmışlar. Beşikdüzü Belediyesi de kendi Twitter hesabında bunu paylaştı. Bu dolandırıcılara ön ayak olmayın diye, inanmayın diye, köyde kanlı eldivenlerin bulunduğu iddiası da vardı, yalanlandı. İmam için iki farklı senaryo üretildi. Bunlardan birincisi imam işin içinde iddiası. Mahkemece dinlenmedi bile. Bu dosya için aslında mahkeme salonunda birde imamın telefonunda uygunsuz içeriklerin bulunduğu yine dava dosyası ile alakası yok ama dava dosyası ile alakası olmayan bir çok husus bugün burada müvekkilimizin yargılamasına sebebiyet verdi diye biz bunları anlatmak zorunda kaldık. İmamın telefonunda uygunsuz içeriklerin bulunduğu iddiası da şu şekilde çıkıyor ortaya. Savcılıkta yapılan bir dosyada, biz gördük, görüşmede şöyle bir şey diyor. Telefonun yeni alınmış gibi temiz bir telefon olması tutanakta öyle geçiyor. Yani herhangi bir telefonda bahsedilen bir şey de yok. Patates hatlar iddiası da yalanlandı. Onu diğer meslektaşlarımız çok iyi açıkladığı için ben burada ekstradan tekrar yapmak istemiyorum.

### Yalan Narratiflerin Yargılamaya Etkisi ve Usul Hataları

Jandarmayı yanıltan işbirlikçiler 6 yaşında, 6 yaşında dedikleri sanırım Narin'in küçük kardeşi. Burada gördük zaten nasıl durumda olduğunu ki o küçük çocuğun iddiaları ile bir keleş bulundu. Yani o sözüne istedikleri zaman itibar ediliyor ama mesela Narin'in eve hiç gelmediğini çıktıktan sonra söyledi. O zaman kimse ona dikkat etmiyor, şimdi son olarak bence en çılgın şey bu konu ile ilgili bir dizi çekildi. Daha doğrusu dizide bir bölüm çekildi, yani sayın başkanım buranın Türkiye olduğunu insanlar maalesef unutuyor ve bu gerçeklik algısı insanlar bir şeye inanmaya başladığı zaman sosyal medyada iyi bir haber yani burada şey denilirdi bir insan köpeği ısırırsa haber olur. Burada öyle bir şey yani sürekli bir şey arıyorlar. Yani kimsenin bir şey bilmediği, olan her şeyin gerçek bir şekilde aklına kimse inanmıyor. Tabi biraz önce başka bir meslektaşımız yine kurtlar vadisinden örnek vermişti. Bu bir karakter öldü, bu karakterin hala biz gıyabi bir şekilde cenaze namazını kılıyoruz, yani bu ülkenin toplumdaki insanların bir şeye inandığı zaman ne kadar sıkı sıkıya bağlı olduğunu görüyoruz. Bu sebeple bunların hiçbirinin yani şimdi bu yalan haberler iddianamede önceden yürütülen soruşturmanın ne kadar niteliksiz olduğu, kolluk personellerinin gıybet tutanakları ile birlikte iddianame konu edilmesini biz doğru bulmuyoruz. Biz iddianameyi son gün sosyal medya aracılığı ile öğrendik. Böyle bir yargılamanın olmasını istemiyoruz. Yine bu daraltılmış baz ile ilgili ve bilirkişiler ile ilgili birçok meslektaşımız burada çok ayrıntılı açıklamalar yaptı. Bizden önceki duruşmada bir beyanda bulunmuştuk, Yargıtay'ın bir çok kararı şunu söylüyor "Alanında uzman olmayan bilirkişilerin raporlarının hükme esas alınması hukuka uygun değildir". Şimdi sayın başkan biz bu bilirkişilerin hangi konuda uzman olduğunu bilmiyoruz. Keşke bilirkişiler buraya gelselerdi, bizde onlara sorular sorsaydık çünkü bu bilirkişi raporlarının diğer yine kıymetli meslektaşlarımızın söylediği gibi ucube bir rapordan başka bir şey olmadığını söylüyoruz. Bunun dışında iştirak iradesi ile ilgili de şimdi müvekkilim çok ayrıntılı açıklama yaptı. Ama bizim müvekkil nezdinde bu iştirak müşterek faillik durumunun suçun oluşma şekillerinin hiçbir şekilde oluşmadığını, bu suçun unsurlarının oluşmadığını düşünmekteyiz. Onun dışında, neyse ona girmeyeceğim, beni dinlediğiniz için teşekkür ederim. Ben müvekkilimin bir an önce beraat kararı ile tahliye edilmesini talep ediyorum. Son savunmaydı, yorulmuştunuz daha fazla da uzatmak istemedim teşekkür ederim. 
