---
title: "Bütün bunların hepsi 18 dakikada mı oldu?"
date: 2024-09-21
author: "Yıldıray Oğur"
source: https://serbestiyet.com/gunun-yazilari/butun-bunlarin-hepsi-18-dakikada-mi-oldu-182151/
description: |
 Narin Güran'ın okul kamerasında son göründüğü 15.15 ile Nevzat Bahtiyar'ın kırmızı aracının dere kenarına geliş saati 15.40 arasındaki 25 dakika, köyden dereye geçen 7 dakikalık yolu da düşersek 18 dakikaya iner. Medyanın ürettiği fantastik senaryoların bu süreye nasıl sıkıştırıldığını sorgulayan bir analiz.
categories: [Narin, Medya eleştirisi, Sahte haber, Tape, Önyargı, Salim Güran, Nevzat Bahtiyar, 18 dakika]
---

Narin'in camiden evine doğru yürürken en son görüntüsü 15.15'te. Nevzat Bahtiyar'ın kırmızı aracının dere kenarına geliş saati ise 15.40. Yani ne olduysa bu 25 dakikada oldu. Hatta köyden dereye yolu da çıkarırsak 18 dakika. Yakalanınca itirafçı olan Bahtiyar'ın ifadelerindeki diyalogları okumak bile üç dakika sürüyor. Peki nasıl oldu da korkunç bir suçu soğukkanlılıkla anlatan, köyde cinayetle doğrudan ilişkisi olduğu kesin tek kişinin itirafları Jandarma'nın ve medyanın baş referansı oldu?

## "Cinayeti çözecek kayıt Halk TV'de"

Son dakika anonsuyla Tavşantepe Köyü'nden muhabir heyecanla anlatıyor:

> "Salim Güran, R… A…'la, Narin'in kaybolduğu 15.15'ten kısa bir süre sonra bir telefon görüşmesi yapıyor. Telefon görüşmesinde şunu soruyor, R… A…'un telefonundan elde edilen ses kaydında; 'R…, kız yaşıyor mu öldü mü?' Tekrar ediyorum, 'R…, kız yaşıyor mu öldü mü?'"

Anlatırken R.A demiyor. Tam adını söylüyor.

Halbuki bahsettiği kişi henüz 15 yaşına girmiş bir tarım işçisi.

Doğruysa, cinayetin itirafı olacak bir görüşme bu.

Ertesi gün medyanın baş şüphelisi olan amca Salim Güran ile 15 yaşındaki işçisi R.A. arasındaki telefonda ses kayıtlı görüşmenin dökümü yayınlandı.

Kürtçe görüşme şöyle tercüme edilmişti:

> **Salim Güran:** "O sondaki köşede bir şeyin düşmüş ha, sana ait bir şey sondaki yamaçta, yamacın köşesi taş"
>
> **R.A.:** "Eee"
>
> **Salim Güran:** "Biri yerde"
>
> **R.A:** "Tamam henüz bende değil, daha ölmemiş"

Anlaşılmayan, kopuk, bağlamsız cümlelerdi bunlar.

Ama dökümde önceki akşam Halk TV'de Salim Güran'ın söylediği iddia edilen "R…, kız yaşıyor mu öldü mü?" diye bir cümle yoktu. Benzeri bir cümle bile yoktu.

Bu köşede çıkan bir önceki yazıda, akıştan kopuk bu "ölmemiş"li cümlenin de bir çeviri hatası olabileceğini yazmıştık.

Şüpheler üzerine yeniden ses kaydı dinlendi ve bu önemli delilin yeni çevirisi yapıldı.

Dün Anadolu Ajansı Salim Güran ve R.A. arasındaki bu ses kayıtlı görüşmenin yeni dökümünü yayınladı:

- 1\. Erkek şahıs (R.A): Alo (Alo)
- 2\. Erkek şahıs (Salim Güran): R…
- 1\. Erkek şahıs: Haa (Efendim)
- 2\. Erkek şahıs: Sona doğru senin bir şeyin düşmüş, sınırın orda, sona doğru
- 1\. Erkek şahıs: Hııı
- 2\. Erkek şahıs: Sınırın orada, senin bir şeyin
- 1\. Erkek şahıs: Tamam, Hıı
- 2\. Erkek şahıs: Sınırın orada, sınırda, taşların orda
- 1\. Erkek şahıs: Heeee
- 1\. Erkek şahıs: Biri yerdedir haaa
- 2\. Erkek şahıs: Tamam ben şimdi gider alırım
- 1\. Erkek şahıs: Ee Tamam
- 2\. Erkek şahıs: Tamam.

Yeni dökümde "Ölmemiş" diye bir kelime de yoktu.

Zaten olması da mümkün değildi.

Çünkü bu telefon konuşması, Nevzat Bahtiyar'ın Narin'i gömmek için dereye götürdüğü 15.40'dan üç saat sonra 18.35'te yapılmıştı.

Sadece zaman akışını bilen birinin bile bu görüşmenin cinayetle bir ilişkisi olmayacağını tahmin etmesi gerekirdi.

Salim Güran, ifadesinde bu görüşmeyi bir suç itirafı da yaparak anlatmıştı:

> "Ben mısır arazisinin sulamasını yaparken kullandığım trafonun elektriğini bazen kaçak yapmak için bir alet kullanıyordum. Olay günü de o aleti R.A.'ya bırakmış olduğum taş dibinden alması için aradım. Görüşme içeriği tamamen bununla alakalıdır. Narin'in ölümü ile bir alakası yoktur."

Yani özetle medya açıkça tape uydurmuştu.

Jandarma, şüpheleneden tapeyi yanlış çevirip servis etmişti.

Ama bu son uydurma olmadı.

## Diğer sahte haberler

Birkaç gün sonra yine Halk TV'de iddialı bir başlık daha son dakika olarak dönmeye başladı.

> "Narin cinayeti aydınlanıyor. Halk TV haklı çıktı, yengenin ifadesi her şeyi açıkladı"

Bir trajediden kendisine "haklılık" çıkaran bu bencilce haber kısa bir süre sonra bütün medyada copy paste haberlerle dönmeye başladı:

"Cinayeti bu ifade aydınlatacak", "Düğüm çözülüyor", "Biri konuştu"

Hediye Güran, kapı komşuları olan Narin'in amcasının eşiydi. Cinayet günü her zamanki gibi Narinlerin evine gelmişti.

Halk Tv ve diğer copy paste medyası Güran'ın ifadesinde şöyle dediğini iddia ettiler:

> "Narin bu ahırda öldürülmüş olabilir iddiasında bulunan yenge Hediye Güran, anne Yüksel Güran'ın, oğlu Enes'i dövdüğünü ve aralarında bir boğuşma yaşandığını gördüğünü aktardı."

Hatta bu ifade üzerine bir teori de yazılmıştı:

> "Narin bir şey gördü. Bunun üzerine ya bağırdı ya da 'Babama söyleyeceğim' gibi tepki verdi. Bağırmasını engellemek için abi Enes, Narin'in ağzını bir eliyle kapattı bir eliyle de ensesinden bastırdı."

Ertesi gün Hediye Güran'ın ifadesi çıktı.

İçinde ne ahır geçiyordu ne boğuşma ne de Enes.

Bu iddia da uydurma çıkmıştı.

Diğer pek çok iddia gibi.

Salim Güran'ı arabasının ön koltuğunda battaniyeye sarılı Narin'le benzincide gördüğünü iddia eden benzincinin ifade verdiği, kamera kayıtlarını Jandarma'ya teslim ettiği iddia edilmişti. Benzinci sahte bir profildi, ifade vermemişti, benzinciden kamera kaydı da yoktu.

Ama tecrübeli Emniyet muhabirleri bile oturup soruşturma evraklarına bakmadan, bu iddianın üzerine küçük bir kızı öldürmek için planlı aile cinayeti teorileri yazdılar.

## Medya ve siyaset önyargısı

Köyde 2015'de HDP'nin, 2023'de İYİ Parti'nin birinci çıktığı, 2024'de DEM'in Hüda Par'dan çok ay aldığı defalarca yazılmasına, köyün Hizbullah ile bir ilgisi olmadığı anlaşılmasına, köyde gizli silah deposu olduğu iddialarının boş olduğu bilinmesine rağmen, gerçekler DEM Eş Genel Başkanı'nı kafasındaki ideolojik ezberleri tekrarlamaktan alıkoymadı.

Narin'i paramiliter güçlerin öldürdüğü iddiası, cinayetin gizli ayinle işlendiği iddiası kadar deli saçmasıydı.

Ama Ahaber, Halk TV ve DEM Parti'yi farklı nedenlerle biraraya getiren önyargı ittifakı herkesin gözünü kör etmişti.

## Basit gerçekler: 18 dakika

Geceleri aile meclisini toplayarak ertesi günkü ifadeleri belirleyen, ceset bulunmasın diye derenin debisini artıran, elektrikleri kesen, cep telefonu kullanmayı bırakan, ceset bulunmasın diye Jandarma'yı yanlış ihbarlarla oyalayan, sorguda İbrahim Kaypakkaya'dan daha sert çıkıp ser verip sır vermeyen şeytani "Omerta Köyü" ve sekiz yaşındaki kız çocuklarını öldürüp, cinayeti saklamak için birleşmiş bir aile ve köy hakkında nasıl olsa her şeyi söylemek serbestti.

Kimse oturup bunlar doğru olabilir mi diye sorgulamadı.

Halbuki ortada bir Omerta'da da yoktu. İfadelerinde aile üyeleri ve köylüler birbirleri hakkında pek çok aleyhte şey de söylemişlerdi.

Muhtarın karısı eşinden şüphelendiğini söylemiş, Narin'in abisi; amcası muhtar Salim ve Nevzat'ın samimiyetini, Nevzat'ın para karşılığı her şeyi yapabilecek ezik biri olduğunu anlatmış, anne, Narin ile amcanın arabasının önüne değil arkasına bindiklerini söyleyerek, ilk önce arabanın ön koltuğunda bulunan DNA ile ilgili muhtar amcayı zor durumda bırakmıştı.

Ama günlerce ana haber bültenlerinde yayınlanan Müge Anlı programına dönen cinayet vakasında, "Kan donduran iddia", "şeytani plan", "bunu da yapmışlar" gibi başlıklarla ne verilirse gidiyordu.

Koca gazeteciler, birkaç fazla tık uğruna, "Narin ne gördü de öldürüldü" sorusuna cevap olarak, doğrudan isim vererek ortada hiçbir veri, kanıt olmayan cinsel fantezileri yazmaktan çekinmediler.

Neredeyse son 20 günde ailede herkes birbiriyle hatta köpeklerle bile eşleştirildi.

- "Ahırda amcası S. ile yengesi H'yi gördü"
- "Ağabeyi ve kuzenlerini eşcinsel ilişkide gördü"
- "Ağabeyi ve amcasını ensest ilişkide gördü"
- "Ağabeyi ile yengesini ilişkide gördü"
- "Annesi ile amcasını ilişkide gördü"
- "Amcası, annesi ve yengesini üçlü ilişkide gördü"
- "Ağabeyini köpekle ilişkide gördü"

Bu iddialardaki çelişkiyle ilgili Fransa'dan Narin cinayetini yakından izleyen Diyarbakırlı yüksek lisans öğrencisi Miham Akkul'un tespiti çok yerinde:

> "Medya hem namus cinayeti, féodalité, ataerkillik gibi büyük sosyolojik aşağılamalar konusunda bonkördü ama paradoksal olarak anne ve amca arasındaki ilişkiyi bilen köyün bu 'namussuzluğu' görmezden geldiğini, hatta baba ve Enes'in bile bunu sineye çektiğini, cinayeti örtbas ettiğini iddia ediyordu."

Korkunç bir suçun mağduru olan küçük bir kızdan köyün kahramanı yaratmak gibi ayıplar da işlendi.

Ama milyonlarca insana bu hikaye satılmıştı, tık ve övgü geliyordu, artık kitle "cinayeti işleyen ve susan köy" dışındaki her ihtimale siyasi örtbas olarak bakıyordu.

> "Ortada bir ay boyunca asılsız ve tutarsız iddialar üzerine inşaa edilmiş bir kakafoni ve bu kakafoni içinde şaşkına döndürüp her şeyi inandırabildikleri devasa bir kamuoyu var."

## Zaman hesabı

DHA muhabiri çok doğru bir iş yaptı ve bir bölümü asfalt, bir bölümü ise toprak olan köyden dereye yaklaşık 2 kilometrelik yolu otomobille 40 kilometre hızla 7 dakikada katetti.

Yani 7 dakika daha gitti.

Geriye kaldı 18 dakika.

Üstelik bu 18 dakika Narin'in başına gelen felaketin kameralarda son göründüğü andan hemen sonra olduğunu düşünerek en maksimum süre.

Peki, bu 18 dakikaya neler sığmıştı?

Sahte çıkan ama hala tecrübeli emniyet muhabirlerinin bile doğruymuş gibi davrandığı arabayla benzinciye gitme senaryosunun sığmayacağı açıktı.

Peki, arabasının dere kenarına gittiği tespit edilince çapraz sorguda Narin'i gömdüğünü itiraf eden Nevzat Bahtiyar'ın birbiriyle çelişen iki ifadesi sığar mı 18 dakikaya?

## Nevzat Bahtiyar'ın ifadeleri

Nevzat Bahtiyar'ın arabası dere kenarında güvenlik kamerasına yakalanınca çapraz sorguda Jandarma'ya verdiği ilk ifade, günler önceden dolaşıma giren ve sonra sahte çıkan benzincinin "arabanın ön koltuğunda battaniyeye sarılı ceset" iddiaları üzerine kurulmuştu.

Salim Güran'ın cesedi battaniye sarıp arabasına koyması, benzinciye gitmesi, sonra arabasıyla giderken Nevzat'la sebepsiz yere karşılaşması ve ardından olanların 18 dakikaya sığması hiç de mümkün gözükmüyor.

Nevzat Bahtiyar'ın savcılığa verdiği ve "gerçek ifadem" bu dediği ilkiyle çelişkilerle dolu ikinci ifadesi ise daha da ayrıntılıydı.

Cesedi Salim Güran'dan almış, eve getirmiş, çuval bulmuş, içine koymuş…

Bütün bunların 18 dakikaya sığıp sığamayacağına siz karar verin:

> "İkametime 100 metre mesafedeki Arif Güran'a ait ikametin bahçesinden Salim Güran seslendi. Benimle işinin olduğunu, aracıyla geleceğini, hazırlanmam gerektiğini söyledi. Ağaç sulamayı bırakarak, bekledim. Birkaç dakika sonrası geldi. 'Arabana bin ve beni takip et' dedi. Oğluma ait araçla takibe başladım. 50 metre uzaklıkta mezarlığa giden yolda durduk. Güran'ın sağ ön camını açması üzerine ön koltukta, çocuğun sarılı olduğu battaniyeyi gördüm. Güran'ın araçtan inmesi üzerinde ben de indim. Battaniyeyi göstererek, 'Arif'in kızını öldürdüm' dedi."

İfadedeki eylemleri bırakın, sadece diyalogları okumak bile 3 dakika sürüyor.

Kaldı 15 dakika.

Bütün bu eylemlerin 15 dakikada yaşanmış olması gerekiyor.

Tabii Narin'in patikaya girdikten hemen sonra öldürüldüğünü kabul edersek.

Bu mümkün mü?

Ya değilse?

## Sorular

Peki ya Narin'in camiden gelirken döndüğü evinin patikası üzerindeki diğer evin sahibi olan, o gün evde olduğu ve bahçede ağaçlarını suladığı bizzat kendi ifadesiyle kesin olan, iki ifadesi arasında apaçık çelişkiler olmasına, korkunç bir suçu soğukkanlılıkla anlatmasına rağmen medyada neredeyse itiraf ederek gerçeğin ortaya çıkmasına yardımcı olduğu için korumaya alınan ve Güran ailesinin suçu üzerine atmaya çalıştığı tanık muamelesi yapılan Nevzat Bahtiyar yalan söylüyorsa?

Küçücük bir kızın cesedini, çuvala koyup, çuvalın üzerini kızın çantasının ipiyle bağlayan sonra da üzerine 20 kiloluk kayalar bırakan ve bütün bunları kendi ifadesiyle "korkudan ya da 200 bin lira için" yaptığı itiraf eden, köyde cesede dokunduğu kesin olan tek kişi olan bu berbat adamın, kameralara yakalandıktan sonra çapraz sorgudaki itirafları nasıl oldu da Jandarma'nın ve medyanın baş referansı oldu?

Jandarma nasıl oldu da, "cesedi evime getirdim" diyen adamın evini daha yeni aradı?

Köyde sorgulanmayan neredeyse sadece köpekler kalırken, 5-6 yaşındaki çocuklar bile Jandarma'yı yanıltmakla suçlanıp ifadeye çağırılırken, "cesedi eve getirdiğini" bizaat kendisi anlatan Bahtiyar'ın eşine, annesine, çocuklarına o gün evde ne gördükleri neden sorulmadı?

Ya arabasının görüntüsü güvenlik kamerasına yakalanınca suçunun bir kısmını itiraf edip kurtulmaya çalışan gerçek katil oysa?

Ya en baştan beri davaya önyargıyla ve kafalarındaki tezleri desteklemek için bakan medya, siyasetçiler, vatandaşlar, bütün bu yalanlar, iddialar, fanteziler ve önyargılarla katile suçunu örtbas etmekte yardım ediyorlarsa?

Ya suç her türlü suç, ahlaksız ve suskunlukla suçlanan köylülerde değil de her şeyi çok iyi bilen, çok ahlaklı ve çok konuşan şehirlilerdeyse?

Bu olayın aydınlandığı gün sadece cinayet hakkında değil, Türkiye hakkında da çok şey öğreneceğiz.
